GRANT SELECT ON ALL TABLES IN SCHEMA public TO public;
GRANT SELECT ON ALL SEQUENCES IN SCHEMA public TO public;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO public;

GRANT SELECT ON ALL TABLES IN SCHEMA topology TO public;
GRANT SELECT ON ALL SEQUENCES IN SCHEMA topology TO public;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA topology TO public;
