# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-15 23:06
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80, unique=True)),
                ('provenance', models.CharField(choices=[('sensor', 'Sensor'), ('analyzer', 'Analyzer'), ('informant', 'Informant')], default='system', max_length=20)),
                ('attributes', django.contrib.postgres.fields.jsonb.JSONField()),
                ('event_type', models.CharField(choices=[('analyzer', 'Analyzer'), ('informant', 'Informant')], default='analyzer', max_length=20)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
