# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-09 00:29
from __future__ import unicode_literals

import datetime

import django.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activity", "0005_event_time_default"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="attributes",
            field=django.db.models.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name="event",
            name="event_time",
            field=models.DateTimeField(
                default=datetime.datetime(2016, 2, 9, 0, 29, 18, 934173, tzinfo=datetime.timezone.utc)
            ),
        ),
    ]
