# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-09 00:29
from __future__ import unicode_literals

import datetime
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0005_event_time_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='attributes',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 2, 9, 0, 29, 18, 934173, tzinfo=utc)),
        ),
    ]
