# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-10 23:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0006_event_attributes_default'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='priority',
        ),
        migrations.AddField(
            model_name='event',
            name='_priority',
            field=models.PositiveSmallIntegerField(choices=[(300, 'Urgent'), (200, 'Important'), (100, 'Reference')], db_column='priority', default=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
