# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-18 01:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0008_auto_20160217_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('system', 'System'), ('exclusion-zone-breach', 'Exclusion Zone Breach'), ('perimeter-fence-breach', 'Perimeter Fence Breach'), ('elephant-sighting', 'Elephant Sighting'), ('wounded-animal', 'Wounded Animal'), ('livestock-theft', 'Livestock Theft'), ('fire', 'Fire'), ('proximity', 'Proximity'), ('geofence', 'Geofence'), ('immobility', 'Immobility'), ('speed', 'Speed'), ('containment-breach', 'Containment Breach'), ('footprints', 'Suspicious Signs')], default='system', max_length=40),
        ),
        migrations.AlterField(
            model_name='event',
            name='provenance',
            field=models.CharField(choices=[('ranger', 'Ranger'), ('system', 'System Process'), ('sensor', 'Sensor'), ('analyzer', 'Analyzer'), ('informant', 'Informant')], default='system', max_length=40),
        ),
    ]
