# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-30 21:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0009_auto_20160217_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('system', 'System'), ('proximity', 'Proximity'), ('geofence', 'Geofence'), ('immobility', 'Immobility'), ('speed', 'Speed'), ('exclusion-zone-breach', 'Exclusion Zone Breach'), ('perimeter-fence-breach', 'Perimeter Fence Breach'), ('elephant-sighting', 'Elephant Sighting'), ('wounded-animal', 'Wounded Animal'), ('livestock-theft', 'Livestock Theft'), ('fire', 'Fire'), ('containment-breach', 'Containment Breach'), ('footprints', 'Suspicious Signs'), ('gunshot-heard', 'Gunshot Heard'), ('radio-text-message', 'Radio Text Message'), ('other', 'Other')], default='system', max_length=40),
        ),
    ]
