# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-13 19:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0011_event_revision'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='description',
            new_name='message',
        ),
        migrations.RemoveField(
            model_name='event',
            name='name',
        ),
        migrations.RemoveField(
            model_name='eventrevision',
            name='changed',
        ),
        migrations.AlterField(
            model_name='eventrevision',
            name='action',
            field=models.CharField(
                choices=[('added', 'Added'), ('updated', 'Updated'),
                         ('deleted', 'Deleted')], default='added',
                max_length=10),
        ),
    ]
