# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-16 18:22
from __future__ import unicode_literals

import activity.models
from django.conf import settings
from django.db import migrations, models
import revision.manager


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('activity', '0012_event_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.TextField()),
                ('created_by_user', models.ForeignKey(null=True, on_delete=models.SET(activity.models.get_sentinel_user), to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=(revision.manager.RevisionMixin, models.Model),
        ),
        migrations.AlterField(
            model_name='event',
            name='provenance',
            field=models.CharField(
                choices=[('staff', 'Staff'), ('system', 'System Process'),
                         ('sensor', 'Sensor'), ('analyzer', 'Analyzer'),
                         ('community', 'Community')], default='system',
                max_length=40),
        ),
    ]
