# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-17 17:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0013_event_note'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventattachment',
            old_name='id',
            new_name='delete_id',
        ),
    ]
