# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-17 17:12
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0014_attachment_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventattachment',
            name='delete_id',
        ),
        migrations.AddField(
            model_name='eventattachment',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
