# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-03 19:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0017_community'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'permissions': (('admin_event', 'An admin permission to change which users can view a Subject and their view permission.'),)},
        ),
        migrations.AddField(
            model_name='event',
            name='state',
            field=models.CharField(choices=[('new', 'New'), ('active', 'Active'), ('resolved', 'Resolved')], default='new', max_length=40),
        ),
    ]
