# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-03 22:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0018_event_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('system', 'System'), ('proximity', 'Proximity'), ('geofence', 'Geofence'), ('immobility', 'Immobility'), ('speed', 'Speed'), ('exclusion-zone-breach', 'Exclusion Zone Breach'), ('perimeter-fence-breach', 'Perimeter Fence Breach'), ('elephant-sighting', 'Elephant Sighting'), ('wounded-animal', 'Wounded Animal'), ('livestock-theft', 'Livestock Theft'), ('fire', 'Fire'), ('containment-breach', 'Containment Breach'), ('footprints', 'Suspicious Signs'), ('gunshot-heard', 'Gunshot Heard'), ('radio-text-message', 'Radio Text Message'), ('other', 'Other')], db_index=True, default='system', max_length=40),
        ),
        migrations.AlterField(
            model_name='event',
            name='state',
            field=models.CharField(choices=[('new', 'New'), ('active', 'Active'), ('resolved', 'Resolved')], db_index=True, default='new', max_length=40),
        ),
    ]
