# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-08 18:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0019_event_filters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('system', 'System'), ('proximity', 'Proximity'), ('geofence', 'Geofence'), ('immobility', 'Immobility'), ('speed', 'Speed'), ('exclusion-zone-breach', 'Exclusion Zone Breach'), ('perimeter-fence-breach', 'Perimeter Fence Breach'), ('elephant-sighting', 'Elephant Sighting'), ('wounded-animal', 'Wounded Animal'), ('livestock-theft', 'Livestock Theft'), ('fire', 'Fire'), ('containment-breach', 'Containment Breach'), ('footprints', 'Suspicious Signs'), ('gunshot-heard', 'Gunshot Heard'), ('radio-text-message', 'Radio Text Message'), ('other', 'Other')], db_index=True, default='other', max_length=40),
        ),
        migrations.AlterField(
            model_name='event',
            name='priority',
            field=models.PositiveSmallIntegerField(choices=[(100, 'Reference'), (200, 'Important'), (300, 'Urgent')], default=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='provenance',
            field=models.CharField(blank=True, choices=[('staff', 'Staff'), ('system', 'System Process'), ('sensor', 'Sensor'), ('analyzer', 'Analyzer'), ('community', 'Community')], max_length=40),
        ),
    ]
