# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-20 15:55
from __future__ import unicode_literals

import choices.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0020_ease_event_required'),
        ('choices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_subtype',
            field=choices.models.ChoiceCharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=choices.models.ChoiceCharField(default='other', max_length=40),
        ),
        migrations.AlterField(
            model_name='event',
            name='priority',
            field=models.PositiveSmallIntegerField(choices=[(100, 'Low'), (200, 'Medium'), (300, 'High')], default=100),
        ),
    ]
