# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-05 19:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


SQL_MIGRATE_SORT_AT = '''
UPDATE activity_event SET sort_at=updated_at;
'''


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0023_eventphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='sort_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunSQL(SQL_MIGRATE_SORT_AT),
        migrations.AlterField(
            model_name='event',
            name='sort_at',
            field=models.DateTimeField(blank=True,
                                       default=django.utils.timezone.now),
        ),
    ]
