# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-06 20:51
from __future__ import unicode_literals

from django.db import migrations
from django.core.management import call_command
from django.contrib.auth.management import create_permissions



class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0025_eventtype'),
    ]

    operations = [

    ]
