# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-12 16:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0028_eventphoto_filename'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='community',
            options={'verbose_name_plural': 'communities'},
        ),
    ]
