# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-19 00:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0029_communities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventattachmentrevision',
            name='action',
            field=models.CharField(choices=[('added', 'Added'), ('updated', 'Updated'), ('deleted', 'Deleted'), ('rel-del', 'Relation Deleted')], default='added', max_length=10),
        ),
        migrations.AlterField(
            model_name='eventnoterevision',
            name='action',
            field=models.CharField(choices=[('added', 'Added'), ('updated', 'Updated'), ('deleted', 'Deleted'), ('rel-del', 'Relation Deleted')], default='added', max_length=10),
        ),
        migrations.AlterField(
            model_name='eventphotorevision',
            name='action',
            field=models.CharField(choices=[('added', 'Added'), ('updated', 'Updated'), ('deleted', 'Deleted'), ('rel-del', 'Relation Deleted')], default='added', max_length=10),
        ),
        migrations.AlterField(
            model_name='eventrevision',
            name='action',
            field=models.CharField(choices=[('added', 'Added'), ('updated', 'Updated'), ('deleted', 'Deleted'), ('rel-del', 'Relation Deleted')], default='added', max_length=10),
        ),
    ]
