# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-28 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0030_photo_delete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='priority',
            field=models.PositiveSmallIntegerField(choices=[(100, 'Low'), (200, 'Normal'), (300, 'High')], default=100),
        ),
    ]
