# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-09 23:06
from __future__ import unicode_literals
import uuid

from django.db import migrations, models
import django.db.models.deletion
from django.core.management import call_command


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0033_factors'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventClassFactor',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('eventclass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity.EventClass')),
                ('eventfactor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity.EventFactor')),
                ('priority', models.PositiveSmallIntegerField(choices=[(100, 'Low'), (200, 'Normal'), (300, 'High')], default=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterUniqueTogether(
            name='eventclassfactor',
            unique_together=set([('eventclass', 'eventfactor')]),
        ),

    ]
