# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-21 19:26
from __future__ import unicode_literals

from django.db import migrations, models
from django.core.management import call_command
from django.contrib.auth.management import create_permissions


def populate_eventtype(apps, schema_editor):
    #initial data references permissions
    apps.models_module = True
    create_permissions(apps, verbosity=0)
    apps.models_module = None
    call_command('loaddata', 'initial_eventtype')


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0035_null_eventtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventtype',
            name='schema',
            field=models.TextField(blank=True),
        ),
        migrations.RunPython(populate_eventtype),
    ]
