# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-05 16:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0037_event_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='priority',
            field=models.PositiveSmallIntegerField(choices=[(0, 'None'), (100, 'Green'), (200, 'Amber'), (300, 'Red')], default=0),
        ),
        migrations.AlterField(
            model_name='eventclassfactor',
            name='priority',
            field=models.PositiveSmallIntegerField(choices=[(0, 'None'), (100, 'Green'), (200, 'Amber'), (300, 'Red')], default=100),
        ),
    ]
