# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-07 18:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0038_auto_20161005_1615'),
        ('activity', '0038_feature_fields'),
    ]

    operations = [
    ]
