# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-29 00:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0040_auto_20161007_1558'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_events', related_query_name='from_event', to='activity.Event')),
                ('to_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_events', related_query_name='to_event', to='activity.Event')),
            ],
        ),
        migrations.CreateModel(
            name='EventRelationshipType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='eventrelationship',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='activity.EventRelationshipType'),
        ),
        migrations.AddField(
            model_name='event',
            name='related_events',
            field=models.ManyToManyField(through='activity.EventRelationship', to='activity.Event'),
        ),
        migrations.AlterUniqueTogether(
            name='eventrelationship',
            unique_together=set([('type', 'from_event', 'to_event')]),
        ),
    ]
