# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-29 21:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0040_auto_20161007_1558'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventRelationship',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships', related_query_name='relationship', to='activity.Event')),
                ('to_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='activity.Event')),
                ('ordernum', models.SmallIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventRelationshipType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=50, unique=True)),
                ('symmetrical', models.BooleanField(default=False)),
                ('ordernum', models.SmallIntegerField(blank=True, null=True)),

            ],
        ),
        migrations.AddField(
            model_name='eventrelationship',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='activity.EventRelationshipType'),
        ),
        migrations.AlterUniqueTogether(
            name='eventrelationship',
            unique_together=set([('type', 'from_event', 'to_event')]),
        ),

    ]
