# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-29 21:33
from __future__ import unicode_literals

from django.db import migrations


def forward(apps, schema_editor):
    EventRelationshipType = apps.get_model('activity', 'EventRelationshipType')
    db_alias = schema_editor.connection.alias

    EventRelationshipType.objects.using(db_alias).bulk_create([
        EventRelationshipType(value='contains', ordernum=1, symmetrical=False),
        EventRelationshipType(value='is_linked_to', ordernum=2, symmetrical=True)
    ])


def reverse(apps, schema_editor):
    EventRelationshipType = apps.get_model('activity', 'EventRelationshipType')
    db_alias = schema_editor.connection.alias

    EventRelationship = apps.get_model('activity', 'EventRelationship')

    EventRelationship.objects.using(db_alias).all().delete()

    EventRelationshipType.objects.using(db_alias).filter(value='contains').delete()
    EventRelationshipType.objects.using(db_alias).filter(value='is_linked_to').delete()


class Migration(migrations.Migration):

    
    dependencies = [
        ('activity', '0041_eventrelationships'),
    ]

    operations = [
        migrations.RunPython(code=forward, reverse_code=reverse),
    ]
