# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-30 22:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0042_eventrelationshiptypes_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventtype',
            name='is_collection',
            field=models.BooleanField(default=False),
        ),
    ]
