# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-30 23:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0043_eventtype_is_collection'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventrelationship',
            options={'ordering': ['type', 'ordernum']},
        ),
    ]
