# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-12-01 17:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0044_eventreltype_ordernum'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='serial_number',
            field=models.BigIntegerField(default=-1, unique=False, null=True, blank=True, verbose_name='Serial Number'),
            preserve_default=False,
        ),
    ]
