# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-12-16 13:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0047_event_serial_number_null'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventcategory',
            options={'permissions': (('security_events', 'Permission to see security events'), ('standard_events', 'Permission to see reporting events.'))},
        ),
    ]
