# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-12-06 18:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0047_event_serial_number_null'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='serial_number',
            field=models.BigIntegerField(blank=True, unique=True, verbose_name='Serial Number'),
        ),
    ]
