# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-12-16 13:05
from __future__ import unicode_literals

from django.db import migrations
from django.core.management import call_command

import utils.models

def populate_initial_event_permission_sets(apps, schema_editor):
    utils.models.migrate_permissions(apps)
    call_command('loaddata', 'initial_event_permission_sets')


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0047_event_serial_number_null'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventcategory',
            options={'permissions': (('security_events', 'Permission to see security events'), ('standard_events', 'Permission to see reporting events.'))},
        ),
        migrations.RunPython(populate_initial_event_permission_sets),
    ]
