# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-01-06 22:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0048_auto_20161216_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Additional message text'),
        ),
    ]
