# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-03-30 20:32
from __future__ import unicode_literals

from django.db import migrations

from accounts.models import User, PermissionSet
from django.contrib.auth.models import Permission

all_perms = ['standard_create',  'standard_read',  'standard_update',  'standard_delete',
             'security_create',  'security_read',  'security_update',  'security_delete',
             'logistics_create', 'logistics_read', 'logistics_update', 'logistics_delete']

restricted_perms = ['security_create',  'security_read',  'security_update',
                    'logistics_create', 'logistics_read', 'logistics_update']


def create_new_permission_sets(apps, schema_editor):
    all_group, created = PermissionSet.objects.get_or_create(
        name='all_event_permissions')
    restricted_group, created = PermissionSet.objects.get_or_create(
        name='restricted_event_permissions')

    existing_security_group = PermissionSet.objects.get_or_create(
        name='security_events')

    for perm_name in all_perms:
        perm = Permission.objects.get_by_natural_key(perm_name, 'activity', 'event')
        all_group.permissions.add(perm)

    for perm_name in restricted_perms:
        perm = Permission.objects.get_by_natural_key(perm_name, 'activity', 'event')
        restricted_group.permissions.add(perm)

    for user in User.objects.all():
        if user.permission_sets.filter(name='security_events').exists():
            user.permission_sets.add(all_group)
            continue

        # If they didn't get all perms, they get restricted perms by default
        user.permission_sets.add(restricted_group)


def reverse_new_permission_sets(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0050_fix_serial_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'permissions': (('view_event', 'Permission to view an event'), ('admin_event', 'An admin permission to change which users can view a Subject and their view permission.'), ('security_create', 'Create security reports'), ('security_read', 'View security reports'), ('security_update', 'Modify security reports'), ('security_delete', 'Delete security reports'), ('standard_create', 'Create monitoring reports'), ('standard_read', 'View monitoring reports'), ('standard_update', 'Modify monitoring reports'), ('standard_delete', 'Delete monitoring reports'), ('logistics_create', 'Create logistics reports'), ('logistics_read', 'View logistics reports'), ('logistics_update', 'Modify logistics reports'), ('logistics_delete', 'Delete logistics reports'))},
        ),
        migrations.AlterModelOptions(
            name='eventcategory',
            options={'permissions': (('security_events', 'Permission to see security events'), ('standard_events', 'Permission to see reporting events.'))},
        ),

        migrations.RunPython(create_new_permission_sets, reverse_new_permission_sets),
    ]
