# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-03-30 20:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0049_event_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventcategory',
            options={'permissions': (('security_create', 'Create security reports'), ('security_read', 'View security reports'), ('security_update', 'Modify security reports'), ('security_delete', 'Delete security reports'), ('standard_create', 'Create monitoring reports'), ('standard_read', 'View monitoring reports'), ('standard_update', 'Modify monitoring reports'), ('standard_delete', 'Delete monitoring reports'), ('logistics_create', 'Create logistics reports'), ('logistics_read', 'View logistics reports'), ('logistics_update', 'Modify logistics reports'), ('logistics_delete', 'Delete logistics reports'))},
        ),
    ]
