# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-05-01 19:31
from __future__ import unicode_literals

from django.db import migrations


def update_all_contenttypes(**kwargs):
    from django.apps import apps
    from django.contrib.contenttypes.management import update_contenttypes

    for app_config in apps.get_app_configs():
        update_contenttypes(app_config, **kwargs)

def create_all_permissions(**kwargs):
    from django.contrib.auth.management import create_permissions
    from django.apps import apps

    for app_config in apps.get_app_configs():
        create_permissions(app_config, **kwargs)

def forward(apps, schema_editor):
    update_all_contenttypes()
    create_all_permissions()

def backward(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0051_add_new_permissions'),

    ]

    operations = [
        migrations.RunPython(forward, backward)
    ]
