# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-05-01 19:31
from __future__ import unicode_literals

from django.db import migrations

from utils.models import update_all_contenttypes, create_all_permissions


def forward(apps, schema_editor):
    update_all_contenttypes()
    create_all_permissions()


def backward(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0051_add_new_permissions'),

    ]

    operations = [
        migrations.RunPython(forward, backward)
    ]
