# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-03-30 20:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0051_add_new_granular_permissions'),
        ('activity', '0050_fix_serial_number'),
    ]

    operations = [
    ]
