# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-04-20 20:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usercontent', '0001_usercontent'),
        ('activity', '0051_event_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='documents',
            field=models.ManyToManyField(to='usercontent.FileContent'),
        ),
    ]
