# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-03-05 16:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0053_migrate_existing_user_permissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='related_events',
        ),
        migrations.AlterField(
            model_name='eventrelationship',
            name='from_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    related_name='out_relationships', related_query_name='out_relationship', to='activity.Event'),
        ),
        migrations.AlterField(
            model_name='eventrelationship',
            name='to_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    related_name='in_relationships', related_query_name='in_relationship', to='activity.Event'),
        ),
    ]
