# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-06-05 22:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('usercontent', '0001_initial'),
        ('activity', '0053_migrate_existing_user_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventDocument',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('ordernum', models.SmallIntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='event',
            name='documents',
            field=models.ManyToManyField(to='usercontent.FileContent'),
        ),
        migrations.AddField(
            model_name='eventdocument',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', related_query_name='document', to='activity.Event'),
        ),
        migrations.AddField(
            model_name='eventdocument',
            name='filecontent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='usercontent.FileContent'),
        ),
    ]
