# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-06-10 13:43
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import revision.manager
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('usercontent', '0001_squashed_0002_filecontent-revision'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('activity', '0053_migrate_existing_user_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventFile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('ordernum', models.SmallIntegerField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', related_query_name='file', to='activity.Event')),
                ('filecontent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='usercontent.FileContent')),
            ],
            options={
                'ordering': ['ordernum', '-updated_at'],
            },
            bases=(models.Model, revision.manager.RevisionMixin),
        ),
        migrations.CreateModel(
            name='EventFileRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('object_id', models.UUIDField()),
                ('action', models.CharField(choices=[('added', 'Added'), ('updated', 'Updated'), ('deleted', 'Deleted'), ('rel-del', 'Relation Deleted')], default='added', max_length=10)),
                ('revision_at', models.DateTimeField(auto_now_add=True)),
                ('sequence', models.IntegerField(help_text='Revision sequence')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ('user', revision.manager.UserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='_eventfile_revision', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.AlterUniqueTogether(
            name='eventfilerevision',
            unique_together=set([('object_id', 'sequence')]),
        ),
    ]
