# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-04-17 23:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0054_fix_serial_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='title',
            field=models.TextField(blank=True, null=True, verbose_name='Event Title.'),
        ),
    ]
