# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-06-14 17:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0055_event_title'),
    ]

    operations = [
    ]
