# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-06-14 17:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('activity', '0056_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventfile',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_files', related_query_name='event_file', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='eventattachment',
            name='reason',
            field=models.CharField(choices=[('target', 'Target'), ('analyzer-result', 'Analyzer Result')], default='target', max_length=20),
        ),
    ]
