# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-01-06 22:37
from __future__ import unicode_literals

from django.db import migrations
from django.contrib.contenttypes.models import ContentType

def forward_f(apps, schema_editor):
    '''
    For each EventPhoto object, create an ImageFileContent object and the corresponding association with an Event.
    '''
    EventFile = apps.get_model('activity', 'EventFile')
    EventPhoto = apps.get_model('activity', 'EventPhoto')
    ImageFileContent = apps.get_model('usercontent', 'ImageFileContent')

    db_alias = schema_editor.connection.alias

    for e in EventPhoto.objects.using(db_alias).all():

        # Create an ImageFileContent.
        ifc, created = ImageFileContent.objects.using(db_alias).get_or_create(
            id=e.id, defaults=dict(file=e.image,
                                   filename=e.filename,
                                   created_at=e.created_at,
                                   updated_at=e.updated_at,
                                   created_by=e.created_by_user)
        )


        # Would prefer to use ContentType.objects.get_for_model(ifc), but apparently it's not available
        # on the queryset returned by using(). So instead, using this.
        ct = ContentType.objects.using(db_alias).get(app_label=ifc._meta.app_label, model=ifc._meta.model_name)


        # Create EventFile.
        ef, created = EventFile.objects.using(db_alias).get_or_create(event=e.event, usercontent_id=ifc.id,
                                                                      usercontent_type_id=ct.id,
                                                                      defaults=dict(created_at=e.created_at,
                                                                                    updated_at=e.updated_at,
                                                                                    created_by=e.created_by_user)
                                                                      )



class Migration(migrations.Migration):
    dependencies = [
        ('activity', '0057_eventfile_createdby'),
        ('usercontent', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(forward_f, reverse_code=None),
    ]
