# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-06-14 19:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0058_migrate_eventphotos_to_imagefilecontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventfile',
            name='comment',
            field=models.TextField(blank=True, default='', verbose_name='Comment about the file.'),
        ),
    ]
