# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-06-19 22:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0059_eventfile_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventcategory',
            name='flag',
            field=models.CharField(
                choices=[('user', 'User'), ('system', 'System')], default='user', max_length=40),
        ),
    ]
