# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-09-22 23:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0062_event_serialnumber_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventtype',
            name='schema',
            field=models.TextField(blank=True, default='{\n                "schema": \n                {\n                    "$schema": "http://json-schema.org/draft-04/schema#",\n                    "title": "Empty Event Schema",\n                    "type": "object",\n                    "properties": {}\n                },\n                "definition": []\n                }'),
        ),
    ]
