# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2018-01-04 18:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0063_spatial-analyzers'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventRelatedSubject',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='activity.Event')),
                ('subject', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='observations.Subject')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='related_subjects',
            field=models.ManyToManyField(
                through='activity.EventRelatedSubject', to='observations.Subject'),
        ),
        migrations.AlterUniqueTogether(
            name='eventrelatedsubject',
            unique_together=set([('event', 'subject')]),
        ),
    ]
