# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2018-01-06 01:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0064_event_relatedsubject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventrelatedsubject',
            name='subject',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to='observations.Subject'),
        ),
    ]
