# Generated by Django 2.0.1 on 2018-01-18 22:01

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.query_utils


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0065_event_relatedsubject_integrity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='reported_by_content_type',
            field=models.ForeignKey(blank=True, limit_choices_to=django.db.models.query_utils.Q(django.db.models.query_utils.Q(('app_label', 'observations'), ('model', 'subject'), _connector='AND'), django.db.models.query_utils.Q(('app_label', 'observations'), ('model', 'source'), _connector='AND'), django.db.models.query_utils.Q(
                ('app_label', 'activity'), ('model', 'community'), _connector='AND'), django.db.models.query_utils.Q(('app_label', 'accounts'), ('model', 'user'), _connector='AND'), _connector='OR'), null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='eventattachment',
            name='content_type',
            field=models.ForeignKey(limit_choices_to=django.db.models.query_utils.Q(django.db.models.query_utils.Q(('app_label', 'observations'), ('model', 'subject'), _connector='AND'), django.db.models.query_utils.Q(('app_label', 'observations'), (
                'model', 'source'), _connector='AND'), django.db.models.query_utils.Q(('app_label', 'analyzers'), ('model', 'subjectanalyzerresult'), _connector='AND'), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='eventfile',
            name='usercontent_type',
            field=models.ForeignKey(limit_choices_to=django.db.models.query_utils.Q(django.db.models.query_utils.Q(('app_label', 'usercontent'), ('model', 'filecontent'), _connector='AND'), django.db.models.query_utils.Q(
                ('app_label', 'usercontent'), ('model', 'imagefilecontent'), _connector='AND'), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
    ]
