# Generated by Django 2.0.2 on 2018-02-22 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0066_post-django2-upgrade'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'permissions': (('security_create', 'Create security reports'), ('security_read', 'View security reports'), ('security_update', 'Modify security reports'), ('security_delete', 'Delete security reports'), ('monitoring_create', 'Create monitoring reports'), ('monitoring_read', 'View monitoring reports'), ('monitoring_update', 'Modify monitoring reports'), ('monitoring_delete', 'Delete monitoring reports'), ('logistics_create', 'Create logistics reports'), ('logistics_read', 'View logistics reports'), ('logistics_update', 'Modify logistics reports'), (
                'logistics_delete', 'Delete logistics reports'), ('analyzer_event_create', 'Create analyzer reports'), ('analyzer_event_read', 'View analyzer reports'), ('analyzer_event_update', 'Modify analyzer reports'), ('analyzer_event_delete', 'Delete analyzer reports'), ('standard__deprecated_read', 'View DEPRECATED monitoring reports'), ('standard__deprecated_update', 'Modify DEPRECATED monitoring reports'), ('security__deprecated_read', 'View DEPRECATED security reports'), ('security__deprecated_update', 'Modify DEPRECATED security reports'))},
        ),
    ]
