# Generated by Django 2.0.1 on 2018-03-09 23:27

from django.db import migrations

FIRMS_REP_UUID = '7b37ff0a-9225-4822-bd32-4fc20f45c85d'
FIRMS_EVENT_TYPE_VALUE = 'firms_rep'

# This schema correlates with the Earthdata FIRMS Active Fire observations
# from VIIRS 375m sensor.
FIRMS_REP_SCHEMA = """
    {
        'schema': 
        {
            '$schema': 'http://json-schema.org/draft-04/schema#',
            'title': 'FIRMS Fire Report Schema',
          
            'type': 'object',
    
            'properties': 
            {
            'bright_ti4': {
                'type': 'string',
                'title': 'VIIRS I-4 channel brightness (Kelvin)'
            },
            'bright_ti5': {
                'type': 'string',
                'title': 'VIIRS I-5 channel brightness (Kelvin)'
            },
            'scan': {
                'type': 'string',
                'title': 'VIIRS Scan'
            },
            'track': {
                'type': 'string',
                'title': 'Satellite Track'
            },
            'confidence': {
                'type': 'string',
                'title': 'FIRMS Confidence'
            },
            'frp': {
                'type': 'string',
                'title': 'Fire Radiative Power (MW)'
            }
        }
      },
      'definition': [
        'confidence',
        'frp',
        'bright_ti4',
        'bright_ti5',
        'scan',
        'track'
      ]
    }
"""


def forward_f(apps, schema_editor):
    EventCategory = apps.get_model('activity', 'EventCategory')
    EventType = apps.get_model('activity', 'EventType')

    db_alias = schema_editor.connection.alias

    event_category = EventCategory.objects.using(
        db_alias).get(value='analyzer_event')

    EventType.objects.using(db_alias).create(id=FIRMS_REP_UUID,
                                             value=FIRMS_EVENT_TYPE_VALUE,
                                             display='FIRMS Fire Detection',
                                             category_id=event_category.id,
                                             ordernum=500,
                                             is_collection=False,
                                             schema=FIRMS_REP_SCHEMA.strip())


def reverse_f(apps, schema_editor):

    EventType = apps.get_model('activity', 'EventType')
    db_alias = schema_editor.connection.alias
    EventType.objects.using(db_alias).filter(
        id=FIRMS_REP_UUID, value=FIRMS_EVENT_TYPE_VALUE).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0068_event_filter'),
    ]

    operations = [
        migrations.RunPython(forward_f, reverse_f),
    ]
