# Generated by Django 2.0.2 on 2018-05-29 23:55

from django.db import migrations

FIX_CREATE_PERMISSION = """
update auth_permission set name = 'Create analyzer reports' where codename = 'analyzer_event_create';
"""

FIX_READ_PERMISSION = """
update auth_permission set name = 'View analyzer reports' where codename = 'analyzer_event_read';
"""

FIX_UPDATE_PERMISSION = """
update auth_permission set name = 'Modify analyzer reports' where codename = 'analyzer_event_update';
"""

FIX_DELETE_PERMISSION = """
update auth_permission set name = 'Delete analyzer reports' where codename = 'analyzer_event_delete';
"""


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0068_event_filter'),
    ]

    operations = [
        migrations.RunSQL(sql=FIX_CREATE_PERMISSION,
                          reverse_sql=migrations.RunSQL.noop),

        migrations.RunSQL(sql=FIX_READ_PERMISSION,
                          reverse_sql=migrations.RunSQL.noop),

        migrations.RunSQL(sql=FIX_UPDATE_PERMISSION,
                          reverse_sql=migrations.RunSQL.noop),

        migrations.RunSQL(sql=FIX_DELETE_PERMISSION,
                          reverse_sql=migrations.RunSQL.noop),

    ]
