# Generated by Django 2.0.2 on 2018-06-22 21:22

import django.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("activity", "0069_fix_analyzer_permission_titles"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="attributes",
            field=django.db.models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="eventattachmentrevision",
            name="data",
            field=django.db.models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="eventdetailsrevision",
            name="data",
            field=django.db.models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="eventfilerevision",
            name="data",
            field=django.db.models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="eventnoterevision",
            name="data",
            field=django.db.models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="eventphotorevision",
            name="data",
            field=django.db.models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="eventrevision",
            name="data",
            field=django.db.models.JSONField(default=dict),
        ),
    ]
