# Generated by Django 2.0.2 on 2018-07-10 19:51

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('activity', '0070_jsonfield_default'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventSource',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4,
                                        primary_key=True, serialize=False)),
                ('external_event_type', models.SlugField(help_text='External event-type identifier.',
                                                         max_length=100, unique=True, verbose_name='External Event Type')),
                ('display', models.CharField(blank=True, default='',
                                             help_text='Friendly description of the event source.', max_length=50, verbose_name='Description')),
                ('is_active', models.BooleanField(
                    default=True, verbose_name='Whether this EventSource may accept new events.')),
                ('additional', django.contrib.postgres.fields.jsonb.JSONField(
                    blank=True, default=dict)),
            ],
            options={
                'permissions': (('create_event_for_eventsource', 'Permission to add an event for an event source'),),
            },
        ),
        migrations.CreateModel(
            name='EventsourceEvent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4,
                                        primary_key=True, serialize=False)),
                ('external_event_id', models.CharField(max_length=100)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                            related_name='eventsource_event_refs', related_query_name='eventsource_event_ref', to='activity.Event')),
                ('eventsource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                                  related_name='eventsource_event_refs', related_query_name='eventsource_event_ref', to='activity.EventSource')),
            ],
        ),
        migrations.AddField(
            model_name='eventtype',
            name='default_priority',
            field=models.PositiveSmallIntegerField(
                choices=[(0, 'None'), (100, 'Green'), (200, 'Amber'), (300, 'Red')], default=0),
        ),
        migrations.AddField(
            model_name='eventtype',
            name='icon',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='eventsource',
            name='event_type',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='activity.EventType'),
        ),
        migrations.AddField(
            model_name='eventsource',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='eventsources', related_query_name='eventsource', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='eventsourceevent',
            unique_together={('eventsource', 'external_event_id')},
        ),
        migrations.AlterUniqueTogether(
            name='eventsource',
            unique_together={('owner', 'external_event_type')},
        ),
    ]
