# Generated by Django 2.0.2 on 2018-07-25 17:17

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('activity', '0072_eventtype_defaultpriority'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventProvider',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4,
                                        primary_key=True, serialize=False)),
                ('display', models.CharField(blank=True, default='',
                                             help_text='Friendly description of the Event Provider.', max_length=50, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True,
                                                  verbose_name='Whether this Event Provider is active.')),
                ('additional', django.contrib.postgres.fields.jsonb.JSONField(
                    blank=True, default=dict)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                            related_name='eventproviders', related_query_name='eventprovider', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='eventsource',
            name='external_event_type',
            field=models.SlugField(help_text='External event-type identifier.',
                                   max_length=100, verbose_name='External Event Type'),
        ),
        migrations.AddField(
            model_name='eventsource',
            name='eventprovider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='eventsources', related_query_name='eventsource', to='activity.EventProvider'),
        ),
        migrations.AlterUniqueTogether(
            name='eventsource',
            unique_together={('eventprovider', 'external_event_type')},
        ),
        migrations.RemoveField(
            model_name='eventsource',
            name='owner',
        ),
    ]
