# Generated by Django 2.0.2 on 2018-09-11 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0074_remove_sentinel_user_function'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventtype',
            name='default_state',
            field=models.CharField(choices=[('new', 'New'), ('active', 'Active'), (
                'resolved', 'Resolved')], default='new', max_length=20),
        ),
    ]
