# Generated by Django 2.0.2 on 2019-02-12 16:55

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('activity', '0076_blanks'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('display', models.CharField(blank=True, max_length=100)),
                ('ordernum', models.SmallIntegerField(blank=True, default=0, null=True)),
                ('definition', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict)),
                ('schedule', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NotificationMethod',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('display', models.CharField(blank=True, max_length=100)),
                ('method', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS')], default='email', max_length=20)),
                ('value', models.CharField(default='', help_text='A phone number or email address.', max_length=100)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_methods', related_query_name='notification_method', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='alertrule',
            name='notification_methods',
            field=models.ManyToManyField(related_name='alert_rules', related_query_name='alert_rule', to='activity.NotificationMethod'),
        ),
        migrations.AddField(
            model_name='alertrule',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alert_rules', related_query_name='alert_rule', to=settings.AUTH_USER_MODEL),
        ),
    ]
