# Generated by Django 2.0.2 on 2019-02-13 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0077_alert_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertrule',
            name='event_types',
            field=models.ManyToManyField(related_name='alert_rules', related_query_name='alert_rule', to='activity.EventType'),
        ),
    ]
