# Generated by Django 2.0.2 on 2019-02-13 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0078_alert_eventtype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alertrule',
            old_name='definition',
            new_name='conditions',
        ),
    ]
