# Generated by Django 2.0.13 on 2019-08-30 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0078_eventnotification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='priority',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Gray'), (100, 'Green'), (200, 'Amber'), (300, 'Red')], default=0),
        ),
        migrations.AlterField(
            model_name='eventclassfactor',
            name='priority',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Gray'), (100, 'Green'), (200, 'Amber'), (300, 'Red')], default=100),
        ),
        migrations.AlterField(
            model_name='eventtype',
            name='default_priority',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Gray'), (100, 'Green'), (200, 'Amber'), (300, 'Red')], default=0),
        ),
        migrations.AddIndex(
            model_name='eventnotification',
            index=models.Index(fields=['event'], name='activity_ev_event_i_172cfd_idx'),
        ),
    ]
