# Generated by Django 2.0.13 on 2019-09-20 05:46

from django.db import migrations

from activity.alerts import create_alerts_permissionset


def forward(apps, schema_editor):
    create_alerts_permissionset()


def reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0078_eventnotification'),
    ]

    operations = [
        migrations.RunPython(forward, reverse),
    ]
