# Generated by Django 2.0.13 on 2019-10-11 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0079_alertrules-permissionset'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventcategory',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
