# Generated by Django 2.0.13 on 2019-11-05 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0080_is_active-eventcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefreshRecreateEventDetailView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('performed_by', models.CharField(blank=True, max_length=255, null=True)),
                ('refresh_at', models.DateTimeField(blank=True, null=True)),
                ('recreated_at', models.DateField(blank=True, null=True)),
                ('maintenance_status', models.CharField(choices=[('SUCCESS', 'Recreate'), ('FAILURE', 'Error'), ('REFRESH', 'Refresh'), ('PENDING', 'Pending'), ('RETRY', 'Retry')], default='PENDING', max_length=255)),
            ],
        )
    ]
