# Generated by Django 2.2.9 on 2020-03-11 21:48

import django.db.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activity", "0082_helper_functions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alertrule",
            name="owner",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="alert_rules",
                related_query_name="alert_rule",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
