# Generated by Django 2.2.9 on 2020-03-11 21:48

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0082_helper_functions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='community',
            options={'verbose_name': 'Event Reporters', 'verbose_name_plural': 'Event Reporters'},
        ),
        migrations.AlterModelOptions(
            name='eventcategory',
            options={'verbose_name': 'Event Category', 'verbose_name_plural': 'Event Categories'},
        ),
        migrations.AlterField(
            model_name='alertrule',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alert_rules', related_query_name='alert_rule', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='event',
            name='priority',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Gray'), (100, 'Green'), (200, 'Amber'), (300, 'Red')], default=0),
        ),
        migrations.AlterField(
            model_name='eventclassfactor',
            name='priority',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Gray'), (100, 'Green'), (200, 'Amber'), (300, 'Red')], default=100),
        ),
        migrations.AlterField(
            model_name='eventfilter',
            name='filter_spec',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, verbose_name='Filter specification'),
        ),
        migrations.AlterField(
            model_name='eventtype',
            name='default_priority',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Gray'), (100, 'Green'), (200, 'Amber'), (300, 'Red')], default=0),
        ),
        migrations.AlterField(
            model_name='eventtype',
            name='schema',
            field=models.TextField(blank=True, default='{\n                "schema":\n                {\n                    "$schema": "http://json-schema.org/draft-04/schema#",\n                    "title": "Empty Event Schema",\n                    "type": "object",\n                    "properties": {}\n                },\n                "definition": []\n                }'),
        ),
        migrations.AddIndex(
            model_name='eventnotification',
            index=models.Index(fields=['event'], name='activity_ev_event_i_172cfd_idx'),
        ),
    ]
