# Generated by Django 2.2.9 on 2020-03-29 12:34

from django.db import migrations

ADD_TSVECTOR_COLUMN = """
 alter table activity_event add column tsvector_doc TSVECTOR;
"""

INDEX_TSVECTOR_DOC = """
create index tsvector_doc_index on activity_event using gin(tsvector_doc);
"""

UPDATE_TSVECTOR_DOC = """
update activity_event e set tsvector_doc = 
     to_tsvector(et.display)||
     to_tsvector(coalesce(e.title,''))||
     to_tsvector(et.schema)||
     to_tsvector(ed.data)
from activity_eventtype et, activity_eventdetails ed where e.event_type_id = et.id and ed.event_id = e.id
"""


# DROP TRIGGER tsvector_update on  activity_eventdetails

TRIGGER_FUNC = """
CREATE OR REPLACE FUNCTION tsvector_doc_trigger() RETURNS trigger as $$
begin
    update activity_event e set tsvector_doc = 
         to_tsvector(et.display)||
         to_tsvector(coalesce(e.title,''))||
         to_tsvector(et.schema)||
         to_tsvector(new.data)
        from activity_eventtype et where e.event_type_id = et.id and new.event_id = e.id;
    return new;
end
$$ LANGUAGE plpgsql;

CREATE TRIGGER tsvector_update BEFORE INSERT OR UPDATE
on activity_eventdetails
FOR EACH ROW EXECUTE PROCEDURE tsvector_doc_trigger();
"""


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0083_alertrule_owner'),
    ]

    operations = [
        migrations.RunSQL(ADD_TSVECTOR_COLUMN,
                          reverse_sql=migrations.RunSQL.noop),
        migrations.RunSQL(INDEX_TSVECTOR_DOC,
                          reverse_sql=migrations.RunSQL.noop),
        migrations.RunSQL(UPDATE_TSVECTOR_DOC,
                          reverse_sql=migrations.RunSQL.noop),
        migrations.RunSQL(TRIGGER_FUNC,
                          reverse_sql=migrations.RunSQL.noop)
    ]
