# Generated by Django 2.2.9 on 2020-03-29 12:34

from django.db import migrations

ADD_TSVECTOR_COLUMN = """
 alter table activity_event add column tsvector_doc TSVECTOR;
"""

INDEX_TSVECTOR_DOC = """
create index tsvector_doc_index on activity_event using gin(tsvector_doc);
"""

UPDATE_TSVECTOR_DOC = """
update activity_event set tsvector_doc = to_tsvector(ef.schema||ae.state||ef.value||ef.display)
from activity_event ae join activity_eventtype ef on ae.event_type_id = ef.id;
"""


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0083_alertrule_owner'),
    ]

    operations = [
        migrations.RunSQL(ADD_TSVECTOR_COLUMN,
                          reverse_sql=migrations.RunSQL.noop),
        migrations.RunSQL(INDEX_TSVECTOR_DOC,
                          reverse_sql=migrations.RunSQL.noop),
        migrations.RunSQL(UPDATE_TSVECTOR_DOC,
                          reverse_sql=migrations.RunSQL.noop)
    ]
