# Generated by Django 2.2.9 on 2020-04-07 02:09

from django.db import migrations

ADD_TSVECTOR_COLUMN_EVENT = """
 alter table activity_tsvectormodel add column tsvector_event TSVECTOR;
"""

INDEX_TSVECTOR_EVENT = """
create index tsvector_event_index on activity_tsvectormodel using gin(tsvector_event);
"""

INSERT_TSVECTOR_EVENT = """
INSERT INTO activity_tsvectormodel (event_id, tsvector_event)
SELECT e.id, et.display::tsvector|| coalesce(e.title,'')::tsvector||to_tsvector(et.schema::text)||to_tsvector(ed.data::text)
FROM activity_event e join activity_eventtype et on e.event_type_id = et.id join activity_eventdetails ed on e.id = ed.event_id
on conflict do nothing;
"""

TRIGGER_FUNC = """
CREATE OR REPLACE FUNCTION tsvector_doc_trigger() RETURNS trigger as $$
begin
    IF (TG_OP = 'INSERT') THEN
        INSERT INTO activity_tsvectormodel (event_id, tsvector_event)
        SELECT e.id, et.display::tsvector|| coalesce(e.title,'')::tsvector||to_tsvector(et.schema::text)||to_tsvector(ed.data::text)
        FROM activity_event e join activity_eventtype et on e.event_type_id = et.id join activity_eventdetails ed on e.id = ed.event_id
        on conflict do nothing;
    ELSIF (TG_OP = 'UPDATE') THEN
        update activity_tsvectormodel ts set
        tsvector_event =
        et.display::tsvector||
        coalesce(e.title,'')::tsvector||
        to_tsvector(et.schema::text)||
        to_tsvector(ed.data::text)
        from activity_event e, activity_eventtype et, activity_eventdetails ed 
        where e.event_type_id = et.id and ed.event_id = e.id and e.id = ts.event_id;
    END IF;
    return new;
end
$$ LANGUAGE plpgsql;

CREATE TRIGGER tsvector_updat AFTER  INSERT OR UPDATE
on activity_eventdetails
FOR EACH ROW EXECUTE PROCEDURE tsvector_doc_trigger();
"""


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0084_tsvector_model'),
    ]

    operations = [
        migrations.RunSQL(ADD_TSVECTOR_COLUMN_EVENT,
                          reverse_sql=migrations.RunSQL.noop),
        migrations.RunSQL(INDEX_TSVECTOR_EVENT,
                          reverse_sql=migrations.RunSQL.noop),
        migrations.RunSQL(INSERT_TSVECTOR_EVENT,
                          reverse_sql=migrations.RunSQL.noop),
        migrations.RunSQL(TRIGGER_FUNC,
                          reverse_sql=migrations.RunSQL.noop)
    ]
