# Generated by Django 2.2.9 on 2020-05-15 14:08

from django.db import migrations, models
import uuid


def generate_uuid(app_registry, schema_editor):
    db_alias = schema_editor.connection.alias
    ts_model = app_registry.get_model('activity', 'tsvectormodel')
    for o in ts_model.objects.using(db_alias).all():
        o.uuid = uuid.uuid4()
        o.save()


class Migration(migrations.Migration):
    dependencies = [
        ('activity', '0086_trigger_event_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='tsvectormodel',
            name='uuid',
            field=models.UUIDField(null=True),
        ),
        migrations.RunPython(generate_uuid,
                             reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='tsvectormodel',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, serialize=False, editable=False, unique=True),
        ),
        migrations.RemoveField('tsvectormodel', 'id'),
        migrations.RenameField(
            model_name='tsvectormodel',
            old_name='uuid',
            new_name='id'
        ),
        migrations.AlterField(
            model_name='tsvectormodel',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        )
    ]
