# Generated by Django 2.2.11 on 2020-05-30 03:56

from django.db import migrations


SQL_FUNC_EVENTNOTE_TRIGGER = """
CREATE OR REPLACE FUNCTION tsvector_eventnote_trigger() RETURNS trigger as $$
begin
    UPDATE activity_tsvectormodel ts SET tsvector_event_note =
        (SELECT to_tsvector(string_agg(text, ','))::tsvector FROM activity_eventnote en
         WHERE en.event_id = NEW.event_id) WHERE ts.event_id = NEW.event_id;
    return new;
end
$$ LANGUAGE plpgsql;
"""

class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0091_triggers2'),
    ]

    operations = [
        migrations.RunSQL(SQL_FUNC_EVENTNOTE_TRIGGER, reverse_sql=migrations.RunSQL.noop),
    ]