# Generated by Django 2.2.9 on 2020-06-11 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0092_triggers3'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='refreshrecreateeventdetailview',
            options={'verbose_name_plural': 'Refresh Data for Tableau'},
        ),
        migrations.AlterField(
            model_name='refreshrecreateeventdetailview',
            name='maintenance_status',
            field=models.CharField(max_length=255),
        ),
    ]
