# Generated by Django 2.2.9 on 2020-06-10 14:44

from django.db import migrations

SQL_FUNC_TSVECTOR_DOC_TRIGGER = """
CREATE OR REPLACE FUNCTION tsvector_doc_trigger() RETURNS trigger as $$
begin
    INSERT INTO activity_tsvectormodel (id, event_id, tsvector_event)
        SELECT  uuid_generate_v4(),
                e.id,  
                setweight(to_tsvector(et.display)::tsvector, 'A')|| 
                setweight(to_tsvector(coalesce(e.title,'')), 'B')||
                setweight(to_tsvector(et.schema::text), 'B')||
                setweight(to_tsvector((ed.data#>> '{event_details}')::text), 'A')
        FROM activity_event e 
              join activity_eventtype et on e.event_type_id = et.id 
              join activity_eventdetails ed on e.id = ed.event_id
          WHERE ed.id = NEW.id
        on conflict(event_id) do update set tsvector_event= excluded.tsvector_event;
    return new;
end
$$ LANGUAGE plpgsql;
"""


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0092_triggers3'),
    ]

    operations = [
        migrations.RunSQL(SQL_FUNC_TSVECTOR_DOC_TRIGGER, reverse_sql=migrations.RunSQL.noop),
    ]
