# Generated by Django 2.2.11 on 2020-06-18 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0093_update_maintenance_status_field'),
        ('activity', '0093_trigger_use_upsert'),
    ]

    operations = [
    ]
