# Generated by Django 2.2.9 on 2020-08-06 14:54

from django.db import migrations


def populate_initial_patroltypes(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    PatrolType = apps.get_model(app_label="activity", model_name="PatrolType")

    patrol_types = [
        {
            "pk": "c6f88fd2-2b87-477a-9c23-3bc4b3eb845d",
            "created_at": "2020-06-23T12:56:41.276Z",
            "updated_at": "2020-06-23T12:57:33.261Z",
            "value": "routine_patrol",
            "display": "Routine Patrol",
            "ordernum": 10,
            "is_active": "False",
        },
        {
            "pk": "e62ca278-8687-455e-ba76-2c7dfa4d6b5f",
            "created_at": "2020-06-24T18:56:40.423Z",
            "updated_at": "2020-06-24T19:23:40.554Z",
            "value": "fence_patrol",
            "display": "Fence Patrol",
            "ordernum": 20,
            "is_active": "False",
        },
        {
            "pk": "ff2f7da6-ade4-4dc1-bd7a-c2c5244017fa",
            "created_at": "2020-06-21T18:56:40.423Z",
            "updated_at": "2020-06-21T19:23:40.554Z",
            "value": "dog_patrol",
            "display": "Dog Patrol",
            "ordernum": 30,
            "is_active": "False",
        },
    ]
    PatrolType.objects.using(db_alias).bulk_create(
        [PatrolType(**patrol_type_fields) for patrol_type_fields in patrol_types]
    )


class Migration(migrations.Migration):
    dependencies = [
        ("activity", "0095_initial_patrol"),
    ]

    operations = [migrations.RunPython(populate_initial_patroltypes)]
