# Generated by Django 2.2.9 on 2020-08-06 14:54

from django.db import migrations


def populate_initial_patroltypes(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("activity", "0095_initial_patrol"),
    ]

    operations = [migrations.RunPython(populate_initial_patroltypes)]
