# Generated by Django 2.2.9 on 2020-08-06 14:54

from django.db import migrations
from django.core.management import call_command


def populate_initial_patroltypes(apps, schema_editor):
    call_command('loaddata', 'initial_patroltypes')


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0095_initial_patrol'),
    ]

    operations = [
        migrations.RunPython(populate_initial_patroltypes)
    ]
