# Generated by Django 2.2.14 on 2020-08-27 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0096_initial_default_patroltype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patrol',
            name='state',
        ),
        migrations.RemoveField(
            model_name='patrolsegment',
            name='state',
        ),
        migrations.AddField(
            model_name='patrol',
            name='state',
            field=models.CharField(choices=[('upcoming', 'Upcoming'), ('active', 'Active'), ('past', 'Past')],
                                   default='active', max_length=25),
        ),
        migrations.AddField(
            model_name='patrolsegment',
            name='state',
            field=models.CharField(choices=[('upcoming', 'Upcoming'), ('active', 'Active'), ('past', 'Past')],
                                   default='active', max_length=25),
        ),
        migrations.AlterField(
            model_name='patrolsegment',
            name='patrol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patrol_segments', related_query_name='patrol_segment', to='activity.Patrol'),
        ),
    ]
