# Generated by Django 2.2.14 on 2020-08-24 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0096_initial_default_patroltype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patrol',
            name='state',
            field=models.CharField(choices=[('upcoming', 'Upcoming'), ('active', 'Active'), ('past', 'Past')], default='active', max_length=25),
        ),
    ]
