# Generated by Django 2.2.14 on 2020-08-25 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0097_auto_20200825_0548'),
    ]

    operations = [
        migrations.AddField(
            model_name='patrolsegment',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patrolsegment',
            name='icon',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patrolsegment',
            name='priority',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Gray'), (100, 'Green'), (200, 'Amber'), (300, 'Red')], default=0),
        ),
        migrations.AddField(
            model_name='patrolsegment',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
