# Generated by Django 2.2.14 on 2020-09-14 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('activity', '0097_update_patrol_state_and_segments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patrolsegment',
            name='source',
        ),
        migrations.AddField(
            model_name='patrolsegment',
            name='leader_content_type',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(models.Q(('app_label', 'observations'), ('model', 'subject')), models.Q(('app_label', 'accounts'), ('model', 'user')), _connector='OR'), null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='patrolsegment',
            name='leader_id',
            field=models.UUIDField(blank=True, default=None, null=True),
        ),
    ]
