# Generated by Django 2.2.14 on 2020-08-26 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0098_auto_20200825_0738'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patrolsegment',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='patrolsegment',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='patrolsegment',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='patrolsegment',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='patrolsegment',
            name='state',
        ),
        migrations.AlterField(
            model_name='patrol',
            name='state',
            field=models.CharField(choices=[(0, 'Upcoming'), (1, 'Active'), (2, 'Past')], default=1, max_length=25),
        ),
    ]
