# Generated by Django 2.2.14 on 2020-09-22 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0099_patrol_serial_and_time_range'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patrol',
            name='objective',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patrol',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
