# Generated by Django 2.2.14 on 2020-08-26 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0099_auto_20200826_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='patrolsegment',
            name='state',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Upcoming'), (1, 'Active'), (2, 'Past')], default=1),
        ),
    ]
