# Generated by Django 2.2.14 on 2020-09-21 21:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0099_patrol_serial_and_time_range'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventtype',
            name='value',
            field=models.CharField(max_length=40, unique=True, validators=[django.core.validators.RegexValidator(message='An invalid character was detected in the Event type Value field.\n        Supported characters are: Letters a-z (lowercase), Numbers 0-9 and Underscore', regex='^[A-Za-z0-9-_]*$')]),
        ),
    ]
