# Generated by Django 2.2.14 on 2020-09-24 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0100_null_title_and_objective'),
        ('activity', '0100_eventtype_value_validator'),
    ]

    operations = [
    ]
