# Generated by Django 2.2.14 on 2020-08-27 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0100_patrolsegment_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patrolsegment',
            name='state',
        ),
        migrations.AlterField(
            model_name='patrol',
            name='state',
            field=models.CharField(choices=[('upcoming', 'Upcoming'), ('active', 'Active'), ('past', 'Past')], default='active', max_length=25),
        ),
    ]
