# Generated by Django 2.2.14 on 2020-09-30 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0101_eventtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patrol',
            name='state',
            field=models.CharField(choices=[('upcoming', 'Upcoming'), ('active', 'Active'), ('past', 'Past'), ('done', 'Done'), ('completed', 'Completed')], default='active', max_length=25),
        ),
        migrations.AlterField(
            model_name='patrolsegment',
            name='state',
            field=models.CharField(choices=[('upcoming', 'Upcoming'), ('active', 'Active'), ('past', 'Past'), ('done', 'Done'), ('completed', 'Completed')], default='active', max_length=25),
        ),
    ]
