# Generated by Django 2.2.14 on 2020-08-27 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0101_auto_20200827_0346'),
    ]

    operations = [
        migrations.AddField(
            model_name='patrolsegment',
            name='state',
            field=models.CharField(choices=[('upcoming', 'Upcoming'), ('active', 'Active'), ('past', 'Past')], default='active', max_length=25),
        ),
    ]
