# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-12-01 17:47
from __future__ import unicode_literals
from django.db import migrations, models
from django.conf import settings

# current DB owner for default db, needed for multiple platforms/databases
db = getattr(settings, 'DATABASES', {})
db_user = db['default']['USER'] if 'default' in db else 'postgres'
# and because Azure requires the host name to be prepended, we need to
# strip off anything with an '@' in it
if '@' in db_user:
    parts = db_user.split('@')
    db_user = parts[0]

class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0102_done_and_cancelled_states'),
    ]

    operations = [
        migrations.RunSQL(
            sql='''CREATE SEQUENCE public.activity_patrol_serial_number_seq
                      INCREMENT 1
                      MINVALUE 1
                      MAXVALUE 9223372036854775807
                      START 1
                      CACHE 1;
                    ALTER TABLE public.activity_patrol_serial_number_seq
                      OWNER TO {};'''.format(db_user),
            reverse_sql='''drop sequence activity_patrol_serial_number_seq ;'''
        ),
        migrations.RunSQL(
            sql="select setval('public.activity_patrol_serial_number_seq', (select max(serial_number) from activity_patrol), true);",
            reverse_sql=migrations.RunSQL.noop
        ),
        migrations.RunSQL(
            sql="alter table activity_patrol alter column serial_number set default nextval('activity_patrol_serial_number_seq'::regclass);",
            reverse_sql="alter table activity_patrol alter COLUMN serial_number drop default;"
        ),
        migrations.AlterField(
            model_name='patrol',
            name='serial_number',
            field=models.BigIntegerField(
                blank=True, null=True, unique=True, verbose_name='Serial Number'),
        ),

    ]
