# Generated by Django 2.2.14 on 2020-10-08 18:55

from django.db import migrations


class Migration(migrations.Migration):

    '''
    Merge sibling ancestors.
    '''
    dependencies = [
        ('activity', '0103_Update_patrol_states'),
        ('activity', '0103_serial_number_unique'),
    ]

    operations = [
    ]
