# Generated by Django 2.2.9 on 2020-11-26 11:22

from django.db import migrations

ACOUSTIC_DETECTION_SCHEMA = """{
   "schema": {
       "$schema": "http://json-schema.org/draft-04/schema#",
       "title": "Acoustic Detection (acoustic_detection)",
       "type": "object",
       "properties": {
            "acoustic_detection_classification": {
                "type": "string",
                "title": "What was detected"
            },
            "acoustic_detection_device": {
                "type": "string",
                "title": "Device name"
            },
            "acoustic_detection_audio_url": {
                "type": "string",
                "title": "Audio URL",
                "format": "uri"
            }
       }
   },
 "definition": [
    {
        "key":    "acoustic_detection_classification",
        "htmlClass": "col-lg-6"
    },
    {
        "key":    "acoustic_detection_device",
        "htmlClass": "col-lg-6"
    },
    {
        "key":    "acoustic_detection_audio_url",
        "htmlClass": "col-lg-6"
    }
 ]
}
"""


def forwards(apps, schema_editor):
    EventCategory = apps.get_model('activity', 'EventCategory')
    EventType = apps.get_model('activity', 'EventType')

    db_alias = schema_editor.connection.alias

    event_category, _ = EventCategory.objects.using(db_alias).get_or_create(value='analyzer_event',
                                                                            defaults={"display": "Analyzer Event",
                                                                                      "ordernum": 1})

    defaults = dict(display='Acoustic Detection',
                    category_id=event_category.id,
                    default_priority=200,
                    icon='radar_rep',
                    is_collection=False,
                    schema=ACOUSTIC_DETECTION_SCHEMA)
    EventType.objects.using(db_alias).update_or_create(defaults=defaults,
     value='acoustic_detection')


class Migration(migrations.Migration):
    dependencies=[
        ('activity', '0105_patrol_scheduled_end'),
    ]

    operations = [
        migrations.RunPython(forwards, reverse_code=migrations.RunPython.noop)
    ]
