# Generated by Django 2.2.9 on 2020-12-06 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0106_add_accoustic_eventtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='patrol_segment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='activity.PatrolSegment'),
        ),
    ]
