# Generated by Django 2.2.9 on 2020-12-07 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0107_add_subject_proximity_evevnttype'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='patrol_segment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', related_query_name='report', to='activity.PatrolSegment'),
        ),
    ]
