# Generated by Django 2.2.9 on 2020-12-10 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0107_add_subject_proximity_evevnttype'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventRelatedSegments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity.Event')),
                ('patrol_segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity.PatrolSegment')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='patrol_segments',
            field=models.ManyToManyField(related_name='events', related_query_name='event', through='activity.EventRelatedSegments', to='activity.PatrolSegment'),
        ),
    ]
