# Generated by Django 2.2.14 on 2021-01-12 23:20
import logging
from django.db import migrations

PATROL_TYPES = {
    "routine_patrol": {"is_active": True, "icon": "routine-patrol-icon"},
    "dog_patrol": {"icon": "dog-patrol-icon"},
    "fence_patrol": {"icon": "fence-patrol-icon"},
}

logger = logging.getLogger(__name__)


def patroltype_icons(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    PatrolType = apps.get_model('activity', 'PatrolType')

    for value, defaults in PATROL_TYPES.items():
        try:
            pt = PatrolType.objects.using(db_alias).get(value=value)
            for k, v in defaults.items():
                setattr(pt, k, v)
            pt.save()

        except PatrolType.DoesNotExist:
            logger.warn(
                f"{value} PatrolType not found while updating properties")


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0109_patrol_permissionset'),
    ]

    operations = [
        migrations.RunPython(code=patroltype_icons,
                             reverse_code=migrations.RunPython.noop)
    ]
