# Generated by Django 2.2.9 on 2021-01-28 17:23

from django.db import migrations

# Chris D: I moved the Entry Alert event-type into the event_data_model fixture, so
# removed it from here. Leaving this migration in place for continunity.

class Migration(migrations.Migration):
    dependencies = [
        ('activity', '0110_patrolicon'),
    ]

    operations = [
    ]
