# Generated by Django 2.2.14 on 2021-02-06 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0112_patrol_segement_integrity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patrolsegment',
            name='leader_content_type',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(models.Q(('app_label', 'observations'), ('model', 'subject')), models.Q(
                ('app_label', 'accounts'), ('model', 'user')), _connector='OR'), null=True, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='patrolsegment',
            name='patrol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    related_name='patrol_segments', related_query_name='patrol_segment', to='activity.Patrol'),
        ),
    ]
