# Generated by Django 2.2.14 on 2021-02-10 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0113_psegment_cascade'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventtype',
            name='auto_resolve',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eventtype',
            name='resolve_time',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='eventtype',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('auto_resolve', False), ('resolve_time__isnull', True)), models.Q(
                ('auto_resolve', True), ('resolve_time__isnull', False)), _connector='OR'), name='auto_resolve_constraint'),
        ),
    ]
