# Generated by Django 2.2.9 on 2021-03-15 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0114_auto_resolve_eventtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventattachmentrevision',
            name='object_id',
            field=models.UUIDField(db_index=True),
        ),
        migrations.AlterField(
            model_name='eventdetailsrevision',
            name='object_id',
            field=models.UUIDField(db_index=True),
        ),
        migrations.AlterField(
            model_name='eventfilerevision',
            name='object_id',
            field=models.UUIDField(db_index=True),
        ),
        migrations.AlterField(
            model_name='eventnoterevision',
            name='object_id',
            field=models.UUIDField(db_index=True),
        ),
        migrations.AlterField(
            model_name='eventphotorevision',
            name='object_id',
            field=models.UUIDField(db_index=True),
        ),
        migrations.AlterField(
            model_name='eventrevision',
            name='object_id',
            field=models.UUIDField(db_index=True),
        ),
        migrations.AlterField(
            model_name='patrolfilerevision',
            name='object_id',
            field=models.UUIDField(db_index=True),
        ),
        migrations.AlterField(
            model_name='patrolnoterevision',
            name='object_id',
            field=models.UUIDField(db_index=True),
        ),
        migrations.AlterField(
            model_name='patrolrevision',
            name='object_id',
            field=models.UUIDField(db_index=True),
        ),
        migrations.AlterField(
            model_name='patrolsegmentrevision',
            name='object_id',
            field=models.UUIDField(db_index=True),
        ),
    ]
