# Generated by Django 2.2.9 on 2021-03-22 16:41

import logging
from django.db import migrations

PATROL_TYPES = {
    "vehicle_patrol": {"icon": "vehicle-patrol-icon"},
    "training_scenario_patrol": {"icon": "training-scenario-patrol-icon"},
    "plane_patrol": {"icon": "plane-patrol-icon"},
    "observation_patrol": {"icon": "observation-patrol-icon"},
    "listening_patrol": {"icon": "listening-patrol-icon"},
    "drone_patrol": {"icon": "drone-patrol-icon"},
    "incident_response_patrol": {"icon": "incident-response-patrol-icon"},
}

logger = logging.getLogger(__name__)


def patroltype_icons(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    PatrolType = apps.get_model('activity', 'PatrolType')

    for value, defaults in PATROL_TYPES.items():
        try:
            pt = PatrolType.objects.using(db_alias).get(value=value)
            for k, v in defaults.items():
                setattr(pt, k, v)
            pt.save()

        except PatrolType.DoesNotExist:
            logger.info(
                f"{value} PatrolType not found while updating properties")


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0114_auto_resolve_eventtype'),
    ]

    operations = [
        migrations.RunPython(code=patroltype_icons,
                             reverse_code=migrations.RunPython.noop)
    ]
