# Generated by Django 2.2.9 on 2021-03-29 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0115_patroltype_icons'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='eventattachmentrevision',
            index_together={('object_id', 'sequence')},
        ),
        migrations.AlterIndexTogether(
            name='eventdetailsrevision',
            index_together={('object_id', 'sequence')},
        ),
        migrations.AlterIndexTogether(
            name='eventfilerevision',
            index_together={('object_id', 'sequence')},
        ),
        migrations.AlterIndexTogether(
            name='eventnoterevision',
            index_together={('object_id', 'sequence')},
        ),
        migrations.AlterIndexTogether(
            name='eventphotorevision',
            index_together={('object_id', 'sequence')},
        ),
        migrations.AlterIndexTogether(
            name='eventrevision',
            index_together={('object_id', 'sequence')},
        ),
        migrations.AlterIndexTogether(
            name='patrolfilerevision',
            index_together={('object_id', 'sequence')},
        ),
        migrations.AlterIndexTogether(
            name='patrolnoterevision',
            index_together={('object_id', 'sequence')},
        ),
        migrations.AlterIndexTogether(
            name='patrolrevision',
            index_together={('object_id', 'sequence')},
        ),
        migrations.AlterIndexTogether(
            name='patrolsegmentrevision',
            index_together={('object_id', 'sequence')},
        ),
    ]
