# Generated by Django 2.2.9 on 2021-03-26 18:42

from django.db import migrations, models


def forwards(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    patrol_conf = apps.get_model('activity', 'PatrolConfiguration')
    subject_groups = apps.get_model('observations', 'SubjectGroup')

    sgs = subject_groups.objects.using(db_alias).filter(
        subjects__subject_subtype__subject_type__value='person')

    instance, created = \
        patrol_conf.objects.using(db_alias).get_or_create(pk=1, defaults={'name': 'Default Patrol Configuration'})
    instance.subject_groups.add(*sgs)


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0096_add_subtypes_icons'),
        ('activity', '0115_patroltype_icons'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatrolConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('subject_groups', models.ManyToManyField(blank=True, related_name='groups', to='observations.SubjectGroup')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RunPython(code=forwards, reverse_code=migrations.RunPython.noop)
    ]
