# Generated by Django 2.2.9 on 2021-03-26 15:10

from django.db import migrations, models

# db_alias = schema_editor.connection.alias
# SubjectType = apps.get_model('observations', 'SubjectType')
# SubjectSubType = apps.get_model('observations', 'SubjectSubType')
# subject_type = SubjectType.objects.using(
#     db_alias).get(value=SUBJECT_TYPE_VALUE)
# for subtype in NEW_SUBTYPES:
#     defaults = {'display': subtype['display'],
#                 'subject_type': subject_type}
#     SubjectSubType.objects.using(db_alias).get_or_create(value=subtype['value'],
#                                                          defaults=defaults)


def forwards(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    patrol_conf = apps.get_model('activity', 'PatrolConfiguration')
    subject_groups = apps.get_model('observations', 'SubjectGroup')

    sgs = subject_groups.objects.using(db_alias).filter(
        subjects__subject_subtype__subject_type__value='person')

    instance, created = patrol_conf.objects.using(db_alias).get_or_create(pk=1,
                                                                          defaults={'name': 'Default Patrol Configuration'})
    instance.subject_groups.add(*sgs)


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0096_add_subtypes_icons'),
        ('activity', '0115_patroltype_icons'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatrolConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('subject_groups', models.ManyToManyField(blank=True, related_name='groups', to='observations.SubjectGroup')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RunPython(code=forwards, reverse_code=migrations.RunPython.noop)
    ]
