# Generated by Django 2.2.14 on 2021-04-03 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0116_patrol_configuration'),
        ('activity', '0116_db_index_revision'),
    ]

    operations = [
    ]
