# Generated by Django 2.2.9 on 2021-05-06 13:58

from django.db import migrations

IMMOBILITY_SCHEMA = """{
      "schema": {
        "$schema": "http://json-schema.org/draft-04/schema#",
        "title": "EventType Immobility",
        "type": "object",
        "properties": {
          "details": {
            "type": "string",
            "title": "Details"
          },
          "name": {
            "type": "string",
            "title": "Name of animal"
          },
          "cluster_fix_count": {
            "type": "number",
            "title": "Cluster Fix Count"
          },
          "total_fix_count": {
            "type": "number",
            "title": "Total Fix Count"
          },
          "cluster_radius": {
            "type": "number",
            "title": "Cluster Search Radius"
          },
          "probability_value": {
            "type": "number",
            "title": "Probability"
          },
          "immobility_time": {
          "type": "number",
          "title": "Duration of Immobility (Seconds)"
          }
        },
        "definition": [
          "name",
          "details",
          "probability_value",
          "total_fix_count",
          "cluster_fix_count",
          "cluster_radius",
          "immobility_time"
        ]
      }
    }"""


def forward_f(apps, schema_editor):
    EventType = apps.get_model('activity', 'EventType')
    db_alias = schema_editor.connection.alias

    EventType.objects.using(db_alias).filter(id='c419acac-874d-422e-8b7b-54470afe56c5',
                                             value='immobility').update(schema=IMMOBILITY_SCHEMA)

    EventType.objects.using(db_alias).filter(id='8bf325e7-2880-447a-b2d8-156c66bc5708',
                                             value='immobility_all_clear').update(schema=IMMOBILITY_SCHEMA)


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0119_add_active_field'),
    ]

    operations = [
        migrations.RunPython(forward_f, migrations.RunPython.noop)
    ]
