# Generated by Django 2.2.9 on 2021-05-24 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0120_update_immobility_et'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['created_at'], name='activity_ev_created_bade74_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['updated_at'], name='activity_ev_updated_1568c9_idx'),
        ),
    ]
