# Generated by Django 2.2.9 on 2021-05-28 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0121_index_event_timestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='refreshrecreateeventdetailview',
            old_name='refresh_at',
            new_name='ended_at',
        ),
        migrations.RemoveField(
            model_name='refreshrecreateeventdetailview',
            name='recreated_at',
        ),
        migrations.AddField(
            model_name='refreshrecreateeventdetailview',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='refreshrecreateeventdetailview',
            name='task_mode',
            field=models.CharField(blank=True, choices=[('Refresh', 'refresh'), ('Recreate', 'recreate')], max_length=255, null=True),
        ),
    ]
