# Generated by Django 2.2.9 on 2021-06-08 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0122_auto_20210528_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='refreshrecreateeventdetailview',
            name='error_details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
