# Generated by Django 2.2.9 on 2021-06-10 14:04

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0122_auto_20210528_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='refreshrecreateeventdetailview',
            name='error_details',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list, verbose_name='error details'),
        ),
    ]
