# Generated by Django 2.2.14 on 2021-08-10 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0123_add_error_details_field'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventtype',
            options={'ordering': ['display']},
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['event_time'], name='activity_ev_event_t_28b799_idx'),
        ),
    ]
