# Generated by Django 2.2.9 on 2021-06-09 14:00

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0123_add_error_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refreshrecreateeventdetailview',
            name='error_details',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list, verbose_name='error details'),
        ),
    ]
