# Generated by Django 2.2.24 on 2022-02-28 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0124_event_time_index'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'permissions': (
            ('security_create', 'Create security reports'), ('security_read', 'View security reports'),
            ('security_update', 'Modify security reports'), ('security_delete', 'Delete security reports'),
            ('monitoring_create', 'Create monitoring reports'), ('monitoring_read', 'View monitoring reports'),
            ('monitoring_update', 'Modify monitoring reports'), ('monitoring_delete', 'Delete monitoring reports'),
            ('logistics_create', 'Create logistics reports'), ('logistics_read', 'View logistics reports'),
            ('logistics_update', 'Modify logistics reports'), ('logistics_delete', 'Delete logistics reports'),
            ('analyzer_event_create', 'Create analyzer reports'), ('analyzer_event_read', 'View analyzer reports'),
            ('analyzer_event_update', 'Modify analyzer reports'), ('analyzer_event_delete', 'Delete analyzer reports'),
            ('add_security_geographic_distance', 'Create security reports in a certain distance'),
            ('view_security_geographic_distance', 'View security reports in a certain distance'),
            ('change_security_geographic_distance', 'Modify security reports in a certain distance'),
            ('delete_security_geographic_distance', 'Delete security reports in a certain distance'),
            ('add_monitoring_geographic_distance', 'Create monitoring reports in a certain distance'),
            ('view_monitoring_geographic_distance', 'View monitoring reports in a certain distance'),
            ('change_monitoring_geographic_distance', 'Modify monitoring reports in a certain distance'),
            ('delete_monitoring_geographic_distance', 'Delete monitoring reports in a certain distance'),
            ('add_logistics_geographic_distance', 'Create logistics reports in a certain distance'),
            ('view_logistics_geographic_distance', 'View logistics reports in a certain distance'),
            ('change_logistics_geographic_distance', 'Modify logistics reports in a certain distance'),
            ('delete_logistics_geographic_distance', 'Delete logistics reports in a certain distance'),
            ('add_analyzer_event_geographic_distance', 'Create analyzer reports in a certain distance'),
            ('view_analyzer_event_geographic_distance', 'View analyzer reports in a certain distance'),
            ('change_analyzer_event_geographic_distance', 'Modify analyzer reports in a certain distance'),
            ('delete_analyzer_event_geographic_distance', 'Delete analyzer reports in a certain distance'),
            ('standard__deprecated_read', 'View DEPRECATED monitoring reports'),
            ('standard__deprecated_update', 'Modify DEPRECATED monitoring reports'),
            ('security__deprecated_read', 'View DEPRECATED security reports'),
            ('security__deprecated_update', 'Modify DEPRECATED security reports'))},
        ),
    ]
