# Generated by Django 2.2.24 on 2022-01-24 18:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0125_add_geographic_permissions_to_event_categories'),
    ]

    operations = [
        # Drop existing materialized view, to allow altering activity EventType model.
        migrations.RunSQL(sql='drop materialized view if exists event_details_view;'),
        migrations.AlterField(
            model_name='eventtype',
            name='display',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='eventtype',
            name='value',
            field=models.CharField(max_length=255, unique=True, validators=[django.core.validators.RegexValidator(message='An invalid character was detected in the Event type Value field.\n        Supported characters are: Letters a-z (lowercase), Numbers 0-9 and Underscore', regex='^[A-Za-z0-9-_]*$')]),
        ),
    ]
