# Generated by Django 2.2.24 on 2022-02-28 21:23

from django.db import migrations


def create_permission_set(apps, schema_editor):
    PermissionSet = apps.get_model("accounts", "PermissionSet")
    Permission = apps.get_model("auth", "Permission")
    permission_set = PermissionSet.objects.create(name="Geographic Permissions by Distance - View")
    permission_value = ["view_analyzer_event_gd", "view_logistics_gd", "view_monitoring_gd", "view_security_gd"]
    for codename in permission_value:
        permission_set.permissions.add(Permission.objects.get(codename=codename))

    permission_set = PermissionSet.objects.create(name="Geographic Permissions by Distance - Edit")
    permission_value = [
        "view_analyzer_event_gd",
        "view_logistics_gd",
        "view_monitoring_gd",
        "view_security_gd",
        "add_analyzer_event_gd",
        "add_logistics_gd",
        "add_monitoring_gd",
        "add_security_gd",
        "change_analyzer_event_gd",
        "change_logistics_gd",
        "change_monitoring_gd",
        "change_security_gd",
        "delete_analyzer_event_gd",
        "delete_logistics_gd",
        "delete_monitoring_gd",
        "delete_security_gd",
    ]
    for codename in permission_value:
        permission_set.permissions.add(Permission.objects.get(codename=codename))


class Migration(migrations.Migration):
    dependencies = [
        ("activity", "0126_lengthen_event_type_value"),
    ]

    operations = [migrations.RunPython(create_permission_set, reverse_code=migrations.RunPython.noop)]
