# Generated by Django 2.2.24 on 2022-02-28 21:23

from django.db import migrations


def create_permission_set(apps, schema_editor):
    PermissionSet = apps.get_model('accounts', 'PermissionSet')
    Permission = apps.get_model("auth", "Permission")
    permission_set = PermissionSet.objects.create(name="Geographic Permissions by Distance - View")
    permission_value = [
        "view_analyzer_event_geographic_distance",
        "view_logistics_geographic_distance",
        "view_monitoring_geographic_distance",
        "view_security_geographic_distance"
    ]
    for codename in permission_value:
        permission_set.permissions.add(Permission.objects.get(codename=codename))


class Migration(migrations.Migration):
    dependencies = [
        ('activity', '0126_lengthen_event_type_value'),
    ]

    operations = [
        migrations.RunPython(
            create_permission_set,
            reverse_code=migrations.RunPython.noop
        )
    ]
