# Generated by Django 2.2.24 on 2022-06-30 17:57
from django.db import migrations

from utils.categories import GEO_ACTIONS, make_eventcategory_permission_codename


def ensure_geographic_perms_exists(instance, apps):
    ContentType = apps.get_model("contenttypes", "ContentType")
    PermissionSet = apps.get_model("accounts", "PermissionSet")
    Permission = apps.get_model("auth", "Permission")

    content_type = ContentType.objects.get(app_label="activity", model="event")
    category_name = instance.value

    permission_set_name = f"View {instance.display} Event Geographic Permissions"
    permission_set, created = PermissionSet.objects.get_or_create(name=permission_set_name)

    for action in GEO_ACTIONS:
        codename = make_eventcategory_permission_codename(category_name, action, True)

        defaults = {
            "name": f"Can {action} {category_name} reports in a certain distance",
            "content_type": content_type,
        }
        permission, created = Permission.objects.get_or_create(codename=codename, defaults=defaults)
        permission_set.permissions.add(permission)


def create_geo_perms_for_existing_categories(apps, schema_editor):
    EventCategory = apps.get_model("activity", "EventCategory")

    for category in EventCategory.objects.all():
        print(f"category: {category}")
        ensure_geographic_perms_exists(category, apps)


class Migration(migrations.Migration):
    dependencies = [
        ("activity", "0127_add_geographic_distance_permission_set"),
    ]

    operations = [
        migrations.RunPython(
            create_geo_perms_for_existing_categories,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
