# Generated by Django 3.1 on 2022-06-22 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0128_create_geo_permission_for_previously_existing_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertrule',
            name='conditions',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='alertrule',
            name='schedule',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='event',
            name='attributes',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='eventattachmentrevision',
            name='data',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='eventdetails',
            name='data',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='eventdetailsrevision',
            name='data',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='eventfilerevision',
            name='data',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='eventfilter',
            name='filter_spec',
            field=models.JSONField(
                default=dict, verbose_name='Filter specification'),
        ),
        migrations.AlterField(
            model_name='eventnoterevision',
            name='data',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='eventphotorevision',
            name='data',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='eventprovider',
            name='additional',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='eventrevision',
            name='data',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='eventsource',
            name='additional',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='patrolfilerevision',
            name='data',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='patrolnoterevision',
            name='data',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='patrolrevision',
            name='data',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='patrolsegmentrevision',
            name='data',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='refreshrecreateeventdetailview',
            name='error_details',
            field=models.JSONField(
                blank=True, default=list, verbose_name='error details'),
        ),
    ]
