# Generated by Django 3.1 on 2022-08-02 13:52

import uuid

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import revision.manager


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('activity', '0129_use_models_JSONField_instead_postgres_fields_JSONField'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventGeometry',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4,
                 primary_key=True, serialize=False)),
                ('geometry', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,
                 related_name='geometries', related_query_name='geometries', to='activity.event')),
            ],
            options={
                'abstract': False,
            },
            bases=(revision.manager.RevisionMixin, models.Model),
        ),
        migrations.CreateModel(
            name='EventGeometryRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4,
                 primary_key=True, serialize=False)),
                ('object_id', models.UUIDField()),
                ('action', models.CharField(choices=[('added', 'Added'), ('updated', 'Updated'), (
                    'deleted', 'Deleted'), ('rel-del', 'Relation Deleted')], default='added', max_length=10)),
                ('revision_at', models.DateTimeField(auto_now_add=True)),
                ('sequence', models.IntegerField(help_text='Revision sequence')),
                ('data', models.JSONField(default=dict)),
                ('user', revision.manager.UserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL,
                 related_name='_eventgeometry_revision', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'default_permissions': (),
                'unique_together': {('object_id', 'sequence')},
            },
        ),
    ]
