# Generated by Django 3.1 on 2022-08-11 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0130_create_event_geometry_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventtype',
            name='enable_geometry',
            field=models.BooleanField(default=False),
        ),
    ]
