# Generated by Django 3.1 on 2022-09-05 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0131_add_enable_geometry_event_type_field'),
        ('activity', '0131_add_properties_field_in_event_geometry'),
    ]

    operations = [
    ]
