# Generated by Django 3.1 on 2022-09-06 18:03

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0132_fix_merge_conflicts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventgeometry',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    related_name='geometries', related_query_name='geometries', to='activity.event'),
        ),
        migrations.AlterField(
            model_name='eventgeometry',
            name='geometry',
            field=django.contrib.gis.db.models.fields.GeometryField(
                geography=True, srid=4326),
        ),
    ]
