# Generated by Django 3.1 on 2022-09-21 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0133_auto_20220906_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventtype',
            name='geometry_type',
            field=models.CharField(choices=[(
                'Point', 'Point'), ('Polygon', 'Polygon')], default='Point', max_length=20),
        ),
        migrations.AddIndex(
            model_name='eventtype',
            index=models.Index(
                fields=['geometry_type'], name='activity_ev_geometr_48865d_idx'),
        ),
        migrations.AddIndex(
            model_name='eventtype',
            index=models.Index(fields=['is_active'],
                               name='activity_ev_is_acti_621e37_idx'),
        ),
        migrations.AddIndex(
            model_name='eventtype',
            index=models.Index(
                fields=['is_collection'], name='activity_ev_is_coll_ea95ac_idx'),
        ),
    ]
