# Generated by Django 3.1 on 2022-09-21 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0134_add_geometry_type_and_indexes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventtype',
            name='enable_geometry',
        ),
    ]
