# Generated by Django 3.1 on 2022-10-26 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activity", "0135_removing_enable_geometry"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventgeometry",
            name="properties",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
