# Generated by Django 3.2 on 2022-12-16 16:59

import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("activity", "0136_blank_properties_for_event_geometry"),
    ]

    operations = [
        migrations.AddField(
            model_name="tsvectormodel",
            name="tsvector_event",
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddField(
            model_name="tsvectormodel",
            name="tsvector_event_note",
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
    ]

    def apply(self, project_state, schema_editor, collect_sql=False):
        return project_state.clone()

    def unapply(self, project_state, schema_editor, collect_sql=False):
        return project_state.clone()
