# Generated by Django 3.2 on 2023-04-06 20:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("activity", "0137_register_missing_tsvectormodel_columns"),
    ]

    operations = [
        migrations.AlterField(
            model_name="community",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="eventcategory",
            name="value",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="eventprovider",
            name="display",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Friendly description of the Event Provider.",
                max_length=100,
                verbose_name="Description",
            ),
        ),
        migrations.AlterField(
            model_name="eventsource",
            name="display",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Friendly description of the event source.",
                max_length=100,
                verbose_name="Description",
            ),
        ),
        migrations.AlterField(
            model_name="membershiptype",
            name="value",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
