# Generated by Django 3.2.19 on 2023-08-09 16:33
import uuid
from functools import partial

from django.db import migrations, models

from utils.migrations import populate_model_uuid_column

APP_NAME = "activity"
ID_COLUMN = "id"
MODEL_NAME = "EventRelatedSegments"
UUID_COLUMN = "uuid"

populate_uuid = partial(populate_model_uuid_column, APP_NAME, MODEL_NAME, UUID_COLUMN)


class Migration(migrations.Migration):
    dependencies = [(APP_NAME, "0140_alter_refreshrecreateeventdetailview_id")]

    operations = [
        migrations.AddField(
            model_name=MODEL_NAME.lower(),
            name=UUID_COLUMN,
            field=models.UUIDField(null=True),
        ),
        migrations.RunPython(populate_uuid),
        migrations.RemoveField(
            model_name=MODEL_NAME.lower(),
            name=ID_COLUMN,
        ),
        migrations.RenameField(
            model_name=MODEL_NAME.lower(),
            old_name=UUID_COLUMN,
            new_name=ID_COLUMN,
        ),
        migrations.AlterField(
            model_name=MODEL_NAME.lower(),
            name=ID_COLUMN,
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
