# Generated by Django 3.2.19 on 2023-08-23 20:52
# This approach is taken from Django documentation
#
# For details See: /writing-migrations/#changing-a-manytomanyfield-to-use-a-through-model
# at https://docs.djangoproject.com/en/3.2/howto
from django.db import migrations, models

ACTIVITY = "activity"
OBSERVATIONS = "observations"
MODEL_NAME = "PatrolConfigurationSubjectGroup"
PATROL_CONFIGURATION = "PatrolConfiguration"
SUBJECT_GROUP = "SubjectGroup"


class Migration(migrations.Migration):
    dependencies = [
        (ACTIVITY, "0143_change_eventrelatedsubject_pk_type_to_uuid"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=f"ALTER TABLE {ACTIVITY}_patrolconfiguration_subject_groups RENAME TO {ACTIVITY}_{MODEL_NAME.lower()}",
                    reverse_sql=f"ALTER TABLE {ACTIVITY}_{MODEL_NAME.lower()} RENAME TO {ACTIVITY}_patrolconfiguration_subject_groups",
                ),
            ],
            state_operations=[
                migrations.CreateModel(
                    name=MODEL_NAME,
                    fields=[
                        (
                            "id",
                            models.AutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        (
                            PATROL_CONFIGURATION.lower(),
                            models.ForeignKey(
                                on_delete=models.deletion.DO_NOTHING,
                                to=f"{ACTIVITY}.{PATROL_CONFIGURATION}",
                            ),
                        ),
                        (
                            SUBJECT_GROUP.lower(),
                            models.ForeignKey(
                                on_delete=models.DO_NOTHING,
                                to=f"{OBSERVATIONS}.{SUBJECT_GROUP}",
                            ),
                        ),
                    ],
                ),
                migrations.AlterField(
                    model_name=PATROL_CONFIGURATION,
                    name="subject_groups",
                    field=models.ManyToManyField(
                        to=f"{OBSERVATIONS}.{SUBJECT_GROUP}",
                        through=f"{ACTIVITY}.{MODEL_NAME}",
                    ),
                ),
            ],
        ),
    ]
