# Generated by Django 3.2.19 on 2023-08-23 21:26
import uuid
from functools import partial

import django.db.models.deletion
from django.db import migrations, models

from utils.migrations import populate_model_uuid_column

ACTIVITY = "activity"
ID_COLUMN = "id"
MODEL_NAME = "PatrolConfigurationSubjectGroup"
OBSERVATIONS = "observations"
PATROL_CONFIGURATION = "PatrolConfiguration"
SUBJECT_GROUP = "SubjectGroup"
UUID_COLUMN = "uuid"

populate_uuid = partial(populate_model_uuid_column, ACTIVITY, MODEL_NAME, UUID_COLUMN)


class Migration(migrations.Migration):
    dependencies = [
        (OBSERVATIONS, "0141_change_subjectstatus_pk_type_to_uuid"),
        (ACTIVITY, "0144_add_patrolconfigurationsubjectgroup_model"),
    ]

    operations = [
        migrations.AddField(
            model_name=MODEL_NAME.lower(),
            name=UUID_COLUMN,
            field=models.UUIDField(null=True),
        ),
        migrations.RunPython(populate_uuid),
        migrations.RemoveField(
            model_name=MODEL_NAME.lower(),
            name=ID_COLUMN,
        ),
        migrations.RenameField(
            model_name=MODEL_NAME.lower(),
            old_name=UUID_COLUMN,
            new_name=ID_COLUMN,
        ),
        migrations.AlterField(
            model_name=MODEL_NAME.lower(),
            name=ID_COLUMN,
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=True),
        ),
        migrations.AlterField(
            model_name=PATROL_CONFIGURATION.lower(),
            name="subject_groups",
            field=models.ManyToManyField(
                blank=True,
                related_name="groups",
                through="activity.PatrolConfigurationSubjectGroup",
                to="observations.SubjectGroup",
            ),
        ),
        migrations.AlterField(
            model_name=MODEL_NAME.lower(),
            name=PATROL_CONFIGURATION.lower(),
            field=models.ForeignKey(
                on_delete=models.CASCADE, to=f"{ACTIVITY}.{PATROL_CONFIGURATION.lower()}", blank=True
            ),
        ),
        migrations.AlterField(
            model_name=MODEL_NAME.lower(),
            name=SUBJECT_GROUP.lower(),
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=f"{OBSERVATIONS}.{SUBJECT_GROUP.lower()}", blank=True
            ),
        ),
    ]
