# Generated by Django 3.2.19 on 2023-08-24 00:05
import uuid
from functools import partial

from django.db import migrations, models

from utils.migrations import set_column_value

APP_NAME = "activity"
ID_COLUMN = "id"
MODEL_NAME = "PatrolConfiguration"
REFERRER_MODEL_NAME = "PatrolConfigurationSubjectGroup"
UUID_COLUMN = "uuid"
REFERRER_UUID_COLUMN = "patrolconfiguration_uuid"
REFERRER_ID_COLUMN = "patrolconfiguration"
PATROL_CONFIGURATION_ID = uuid.UUID("deb99202-2373-4c6c-b05f-e71d29cb2b26")

update_references = partial(
    set_column_value, APP_NAME, REFERRER_MODEL_NAME, REFERRER_UUID_COLUMN, PATROL_CONFIGURATION_ID
)


def set_patrolconfiguration_uuid(apps, schema_editor):
    schema_editor.connection.alias
    PatrolConfiguration = apps.get_model(APP_NAME, MODEL_NAME)
    patrol_configuration = PatrolConfiguration.objects.first()
    setattr(patrol_configuration, UUID_COLUMN, PATROL_CONFIGURATION_ID)
    patrol_configuration.save()


class Migration(migrations.Migration):
    dependencies = [
        (APP_NAME, "0145_change_pk_type_patrolconfiguration_subjectgroup"),
    ]

    operations = [
        migrations.AddField(
            model_name=MODEL_NAME.lower(),
            name=UUID_COLUMN,
            field=models.UUIDField(null=True),
        ),
        migrations.RunPython(set_patrolconfiguration_uuid),
        migrations.AddField(
            model_name=REFERRER_MODEL_NAME.lower(),
            name=REFERRER_UUID_COLUMN,
            field=models.UUIDField(null=True),
        ),
        migrations.RunPython(update_references),
        migrations.RemoveField(
            model_name=MODEL_NAME.lower(),
            name=ID_COLUMN,
        ),
        migrations.RenameField(
            model_name=MODEL_NAME.lower(),
            old_name=UUID_COLUMN,
            new_name=ID_COLUMN,
        ),
        migrations.AlterField(
            model_name=MODEL_NAME.lower(),
            name=ID_COLUMN,
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=True),
        ),
        migrations.RemoveField(
            model_name=REFERRER_MODEL_NAME.lower(),
            name=REFERRER_ID_COLUMN,
        ),
        migrations.RenameField(
            model_name=REFERRER_MODEL_NAME.lower(),
            old_name=REFERRER_UUID_COLUMN,
            new_name=REFERRER_ID_COLUMN,
        ),
        migrations.AlterField(
            model_name=REFERRER_MODEL_NAME.lower(),
            name=REFERRER_ID_COLUMN,
            field=models.ForeignKey(
                blank=True, on_delete=models.CASCADE, to=f"{APP_NAME.lower()}.{MODEL_NAME.lower()}"
            ),
        ),
    ]
