# Generated by Django 3.2.19 on 2023-08-24 22:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_add_das_tenant_model"),
        ("activity", "0146_change_pk_type_patrolconfiguration"),
    ]

    operations = [
        migrations.AddField(
            model_name="community",
            name="das_tenant",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="core.dastenant"
            ),
        ),
        migrations.AddField(
            model_name="eventcategory",
            name="das_tenant",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="core.dastenant"
            ),
        ),
        migrations.AddField(
            model_name="eventclass",
            name="das_tenant",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="core.dastenant"
            ),
        ),
        migrations.AddField(
            model_name="eventfactor",
            name="das_tenant",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="core.dastenant"
            ),
        ),
        migrations.AddField(
            model_name="eventfilter",
            name="das_tenant",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="core.dastenant"
            ),
        ),
        migrations.AddField(
            model_name="eventrelationshiptype",
            name="das_tenant",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="core.dastenant"
            ),
        ),
        migrations.AddField(
            model_name="membershiptype",
            name="das_tenant",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="core.dastenant"
            ),
        ),
        migrations.AddField(
            model_name="patrol",
            name="das_tenant",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="core.dastenant"
            ),
        ),
        migrations.AddField(
            model_name="patroltype",
            name="das_tenant",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="core.dastenant"
            ),
        ),
        migrations.AddField(
            model_name="refreshrecreateeventdetailview",
            name="das_tenant",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="core.dastenant"
            ),
        ),
        migrations.AddField(
            model_name="team",
            name="das_tenant",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="core.dastenant"
            ),
        ),
        migrations.AddField(
            model_name="tsvectormodel",
            name="das_tenant",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="core.dastenant"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="community",
            unique_together={("id", "das_tenant")},
        ),
        migrations.AlterUniqueTogether(
            name="eventcategory",
            unique_together={("id", "das_tenant")},
        ),
        migrations.AlterUniqueTogether(
            name="eventclass",
            unique_together={("id", "das_tenant")},
        ),
        migrations.AlterUniqueTogether(
            name="eventfactor",
            unique_together={("id", "das_tenant")},
        ),
        migrations.AlterUniqueTogether(
            name="eventfilter",
            unique_together={("id", "das_tenant")},
        ),
        migrations.AlterUniqueTogether(
            name="eventrelationshiptype",
            unique_together={("id", "das_tenant")},
        ),
        migrations.AlterUniqueTogether(
            name="membershiptype",
            unique_together={("id", "das_tenant")},
        ),
        migrations.AlterUniqueTogether(
            name="patrol",
            unique_together={("id", "das_tenant")},
        ),
        migrations.AlterUniqueTogether(
            name="patroltype",
            unique_together={("id", "das_tenant")},
        ),
        migrations.AlterUniqueTogether(
            name="refreshrecreateeventdetailview",
            unique_together={("id", "das_tenant")},
        ),
        migrations.AlterUniqueTogether(
            name="team",
            unique_together={("id", "das_tenant")},
        ),
        migrations.AlterUniqueTogether(
            name="tsvectormodel",
            unique_together={("id", "das_tenant")},
        ),
    ]
