# Generated by Django 3.2.19 on 2023-08-24 22:24
import logging

from django.apps import apps
from django.conf import settings
from django.db import migrations

from core.utils import DASTenantManagement, update_tenant_models
from utils.tenant.managers import set_tenant

logger = logging.getLogger(__name__)


def populate_das_tenant_in_activity_models(unused, schema_editor):
    Community = apps.get_model("activity", "Community")
    EventClass = apps.get_model("activity", "EventClass")
    EventFactor = apps.get_model("activity", "EventFactor")
    EventCategory = apps.get_model("activity", "EventCategory")
    EventRelationshipType = apps.get_model("activity", "EventRelationshipType")
    EventFilter = apps.get_model("activity", "EventFilter")
    TSVectorModel = apps.get_model("activity", "TSVectorModel")
    MembershipType = apps.get_model("activity", "MembershipType")
    Patrol = apps.get_model("activity", "Patrol")
    PatrolType = apps.get_model("activity", "PatrolType")
    RefreshRecreateEventDetailView = apps.get_model("activity", "RefreshRecreateEventDetailView")
    Team = apps.get_model("activity", "Team")

    # we specifically do not use loaddata_with_tenant here
    # the next loaddata fails for existing sites because they already have these records
    # call_command("loaddata", "initial_patroltypes")

    class_models = [
        Community,
        EventClass,
        EventFactor,
        EventCategory,
        EventRelationshipType,
        EventFilter,
        TSVectorModel,
        MembershipType,
        Patrol,
        PatrolType,
        RefreshRecreateEventDetailView,
        Team,
    ]

    das_tenant_management = DASTenantManagement(domain=settings.SERVER_FQDN)
    tenant = das_tenant_management.get_or_create_tenant()
    set_tenant(domain=settings.SERVER_FQDN)

    if tenant:
        update_tenant_models(models=class_models, tenant=tenant)
    else:
        logger.error("DAS Tenant not found.")


class Migration(migrations.Migration):
    dependencies = [
        ("activity", "0147_add_tenant_model_mixin_and_tenant_manager_mixin"),
    ]

    operations = [
        migrations.RunPython(code=populate_das_tenant_in_activity_models, reverse_code=migrations.RunPython.noop)
    ]
