# Generated by Django 3.2.19 on 2023-08-25 17:12
import logging

from django.apps import apps
from django.conf import settings
from django.db import migrations

from core.utils import DASTenantManagement, update_tenant_models
from utils.tenant.managers import set_tenant

logger = logging.getLogger(__name__)


def populate_das_tenant_tenant_foreign_key_in_activity_models(unused, schema_editor):
    AlertRule = apps.get_model("activity", "AlertRule")
    EventAttachment = apps.get_model("activity", "EventAttachment")
    EventClassFactor = apps.get_model("activity", "EventClassFactor")
    EventDetails = apps.get_model("activity", "EventDetails")
    EventFile = apps.get_model("activity", "EventFile")
    EventGeometry = apps.get_model("activity", "EventGeometry")
    EventNote = apps.get_model("activity", "EventNote")
    EventNotification = apps.get_model("activity", "EventNotification")
    EventPhoto = apps.get_model("activity", "EventPhoto")
    EventProvider = apps.get_model("activity", "EventProvider")
    EventRelatedSegments = apps.get_model("activity", "EventRelatedSegments")
    EventRelatedSubject = apps.get_model("activity", "EventRelatedSubject")
    EventRelationship = apps.get_model("activity", "EventRelationship")
    EventSource = apps.get_model("activity", "EventSource")
    EventsourceEvent = apps.get_model("activity", "EventsourceEvent")
    Event = apps.get_model("activity", "Event")
    EventType = apps.get_model("activity", "EventType")
    NotificationMethod = apps.get_model("activity", "NotificationMethod")
    PatrolFile = apps.get_model("activity", "PatrolFile")
    PatrolNote = apps.get_model("activity", "PatrolNote")
    PatrolSegment = apps.get_model("activity", "PatrolSegment")
    PatrolSegmentMembership = apps.get_model("activity", "PatrolSegmentMembership")
    TeamMembership = apps.get_model("activity", "TeamMembership")

    class_models = [
        AlertRule,
        EventAttachment,
        EventClassFactor,
        EventDetails,
        EventFile,
        EventGeometry,
        EventNote,
        EventNotification,
        EventPhoto,
        EventProvider,
        EventRelatedSegments,
        EventRelatedSubject,
        EventRelationship,
        EventSource,
        EventsourceEvent,
        Event,
        EventType,
        NotificationMethod,
        PatrolFile,
        PatrolSegment,
        PatrolNote,
        PatrolSegmentMembership,
        TeamMembership,
    ]

    das_tenant_management = DASTenantManagement(domain=settings.SERVER_FQDN)
    tenant = das_tenant_management.get_or_create_tenant()
    set_tenant(settings.SERVER_FQDN)

    if tenant:
        update_tenant_models(models=class_models, tenant=tenant)
    else:
        logger.error("DAS Tenant not found.")
        raise Exception("DAS Tenant not found.")


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ("activity", "0149_add_tenant_foreign_key"),
    ]

    operations = [
        migrations.RunPython(
            code=populate_das_tenant_tenant_foreign_key_in_activity_models, reverse_code=migrations.RunPython.noop
        )
    ]
