# Generated by Django 3.2.19 on 2023-09-25 20:29

from django.conf import settings
from django.contrib.auth.models import Permission
from django.core.management import call_command
from django.db import migrations

import utils.models
from accounts.models import PermissionSet, User
from activity.alerts import create_alerts_permissionset
from core.utils import DASTenantManagement
from utils.tenant import set_tenant


def create_new_permission_sets(apps, _):  # comes from das/activity/migrations/0053_migrate_existing_user_permissions.py
    all_perms = [
        "monitoring_create",
        "monitoring_read",
        "monitoring_update",
        "monitoring_delete",
        "security_create",
        "security_read",
        "security_update",
        "security_delete",
        "logistics_create",
        "logistics_read",
        "logistics_update",
        "logistics_delete",
    ]

    restricted_perms = [
        "security_create",
        "security_read",
        "security_update",
        "logistics_create",
        "logistics_read",
        "logistics_update",
    ]

    das_tenant_management = DASTenantManagement(domain=settings.SERVER_FQDN)
    tenant = das_tenant_management.get_or_create_tenant()

    all_group, _ = PermissionSet.objects.get_or_create(name="all_event_permissions", das_tenant=tenant)
    restricted_group, _ = PermissionSet.objects.get_or_create(name="restricted_event_permissions", das_tenant=tenant)

    existing_security_group, _ = PermissionSet.objects.get_or_create(name="security_events", das_tenant=tenant)

    for perm_name in all_perms:
        try:
            perm = Permission.objects.get_by_natural_key(perm_name, "activity", "event")
            all_group.permissions.add(perm)
        except Permission.DoesNotExist:
            pass
    for perm_name in restricted_perms:
        try:
            perm = Permission.objects.get_by_natural_key(perm_name, "activity", "event")
            restricted_group.permissions.add(perm)
        except Permission.DoesNotExist:
            pass
    for user in User.objects.all():
        if user.permission_sets.filter(name="security_events").exists():
            user.permission_sets.add(all_group)
            continue

        # If they didn't get all perms, they get restricted perms by default
        user.permission_sets.add(restricted_group)


def forward_pre(apps, _):  # comes from das/activity/migrations/0061_event_permission_cleanup.py
    security_users = []
    monitoring_users = []
    old_set_names = [
        "security_events",
        "View Security Events",
        "View Reporting Events ",
        "Add/Edit Events",
        "all_event_permissions",
        "all_event_permissions",
        "restricted_event_permissions",
        "Events Read-Only",
        "Only Add Events",
    ]
    # First let's see who the users are who can currently see security events
    for user in User.objects.all():
        if (
            user.permission_sets.filter(name="security_events").exists()
            or user.permission_sets.filter(name="all_event_permissions").exists()
        ):
            security_users.append(user)
        else:
            monitoring_users.append(user)

    # Next, delete all event permission sets because some are old and some
    # were created incorrectly
    for set_name in old_set_names:
        pset = PermissionSet.objects.filter(name=set_name).first()
        if pset:
            pset.delete()


def populate_new_permission_sets(apps):
    utils.models.migrate_permissions(apps)
    set_tenant(domain=settings.SERVER_FQDN)
    call_command("loaddata_with_tenant", "new_permission_sets", app_label="activity")


def forward_post(apps, schema_editor):
    security_users = []
    monitoring_users = []
    old_set_names = [
        "security_events",
        "View Security Events",
        "View Reporting Events ",
        "Add/Edit Events",
        "all_event_permissions",
        "all_event_permissions",
        "restricted_event_permissions",
        "Events Read-Only",
        "Only Add Events",
    ]
    new_security_group_name = "Admin User Event Permissions"
    new_monitoring_group_name = "Radio Room Operator Event Permissions"
    # Populate the new permission sets from a fixture
    populate_new_permission_sets(apps)

    security_permission_set = PermissionSet.objects.get(name=new_security_group_name)
    monitoring_permission_set = PermissionSet.objects.get(name=new_monitoring_group_name)

    for security_user in security_users:
        security_user.permission_sets.add(security_permission_set)
        security_user.save()

    for monitoring_user in monitoring_users:
        monitoring_user.permission_sets.add(monitoring_permission_set)
        monitoring_user.save()


def migrate_create_alerts_permissionset(apps, _):  # comes from das/activity/migrations/0079_alertrules-permissionset.py
    das_tenant_management = DASTenantManagement(domain=settings.SERVER_FQDN)
    tenant = das_tenant_management.get_or_create_tenant()
    create_alerts_permissionset(tenant)


class Migration(migrations.Migration):
    dependencies = [
        ("activity", "0150_populate_tenant_foreign_key_in_activity"),
    ]

    operations = [
        migrations.RunPython(code=create_new_permission_sets, reverse_code=migrations.RunPython.noop),
        migrations.RunPython(code=forward_pre, reverse_code=migrations.RunPython.noop),
        migrations.RunPython(code=forward_post, reverse_code=migrations.RunPython.noop),
        migrations.RunPython(code=migrate_create_alerts_permissionset, reverse_code=migrations.RunPython.noop),
    ]
