# Generated by Django 3.2.19 on 2023-09-27 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_populate_oauth_models_with_tenant"),
        ("activity", "0151_populate_permission_sets"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventattachmentrevision",
            name="das_tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activity_eventattachmentrevision",
                to="core.dastenant",
            ),
        ),
        migrations.AddField(
            model_name="eventdetailsrevision",
            name="das_tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activity_eventdetailsrevision",
                to="core.dastenant",
            ),
        ),
        migrations.AddField(
            model_name="eventfilerevision",
            name="das_tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activity_eventfilerevision",
                to="core.dastenant",
            ),
        ),
        migrations.AddField(
            model_name="eventgeometryrevision",
            name="das_tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activity_eventgeometryrevision",
                to="core.dastenant",
            ),
        ),
        migrations.AddField(
            model_name="eventnoterevision",
            name="das_tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activity_eventnoterevision",
                to="core.dastenant",
            ),
        ),
        migrations.AddField(
            model_name="eventphotorevision",
            name="das_tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activity_eventphotorevision",
                to="core.dastenant",
            ),
        ),
        migrations.AddField(
            model_name="eventrevision",
            name="das_tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activity_eventrevision",
                to="core.dastenant",
            ),
        ),
        migrations.AddField(
            model_name="patrolfilerevision",
            name="das_tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activity_patrolfilerevision",
                to="core.dastenant",
            ),
        ),
        migrations.AddField(
            model_name="patrolnoterevision",
            name="das_tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activity_patrolnoterevision",
                to="core.dastenant",
            ),
        ),
        migrations.AddField(
            model_name="patrolrevision",
            name="das_tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activity_patrolrevision",
                to="core.dastenant",
            ),
        ),
        migrations.AddField(
            model_name="patrolsegmentrevision",
            name="das_tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activity_patrolsegmentrevision",
                to="core.dastenant",
            ),
        ),
        migrations.AddConstraint(
            model_name="eventattachmentrevision",
            constraint=models.UniqueConstraint(
                fields=("das_tenant", "id"), name="activity_eventattachmentrevision_tenant_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="eventdetailsrevision",
            constraint=models.UniqueConstraint(
                fields=("das_tenant", "id"), name="activity_eventdetailsrevision_tenant_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="eventfilerevision",
            constraint=models.UniqueConstraint(
                fields=("das_tenant", "id"), name="activity_eventfilerevision_tenant_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="eventgeometryrevision",
            constraint=models.UniqueConstraint(
                fields=("das_tenant", "id"), name="activity_eventgeometryrevision_tenant_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="eventnoterevision",
            constraint=models.UniqueConstraint(
                fields=("das_tenant", "id"), name="activity_eventnoterevision_tenant_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="eventphotorevision",
            constraint=models.UniqueConstraint(
                fields=("das_tenant", "id"), name="activity_eventphotorevision_tenant_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="eventrevision",
            constraint=models.UniqueConstraint(
                fields=("das_tenant", "id"), name="activity_eventrevision_tenant_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="patrolfilerevision",
            constraint=models.UniqueConstraint(
                fields=("das_tenant", "id"), name="activity_patrolfilerevision_tenant_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="patrolnoterevision",
            constraint=models.UniqueConstraint(
                fields=("das_tenant", "id"), name="activity_patrolnoterevision_tenant_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="patrolrevision",
            constraint=models.UniqueConstraint(
                fields=("das_tenant", "id"), name="activity_patrolrevision_tenant_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="patrolsegmentrevision",
            constraint=models.UniqueConstraint(
                fields=("das_tenant", "id"), name="activity_patrolsegmentrevision_tenant_unique"
            ),
        ),
    ]
