# Generated by Django 3.2.19 on 2023-09-27 21:25
import logging

from django.apps import apps
from django.conf import settings
from django.db import migrations

from core.utils import DASTenantManagement, update_tenant_models
from utils.tenant.managers import set_tenant

logger = logging.getLogger(__name__)


def populate_tenant_into_models(unused, schema_editor):
    model_names = [
        "EventFileRevision",
        "EventRevision",
        "EventAttachmentRevision",
        "EventNoteRevision",
        "EventDetailsRevision",
        "EventPhotoRevision",
        "PatrolRevision",
        "PatrolNoteRevision",
        "PatrolFileRevision",
        "PatrolSegmentRevision",
        "EventGeometryRevision",
    ]
    class_models = [apps.get_model("activity", model_name) for model_name in model_names]

    das_tenant_management = DASTenantManagement(domain=settings.SERVER_FQDN)
    tenant = das_tenant_management.get_or_create_tenant()
    set_tenant(settings.SERVER_FQDN)

    if tenant:
        update_tenant_models(models=class_models, tenant=tenant)

    else:
        logger.error("DAS Tenant not found.")


class Migration(migrations.Migration):
    dependencies = [
        ("activity", "0152_add_das_tenant_to_activity_revision_models"),
    ]

    operations = [
        migrations.RunPython(
            populate_tenant_into_models,
            migrations.RunPython.noop,
        )
    ]
