# Generated by Django 3.2.19 on 2023-10-02 03:39

from django.db import migrations

from utils.migrations.update_primary_key import add_tenant_to_primary_key

activity_models = [
    "AlertRule",
    "Community",
    "EventCategory",
    "EventClass",
    "EventFactor",
    "EventFilter",
    "EventRelationshipType",
    "Event",
    "EventAttachment",
    "EventClassFactor",
    "EventDetails",
    "EventFile",
    "EventGeometry",
    "EventNote",
    "EventNotification",
    "EventPhoto",
    "EventProvider",
    "EventRelatedSegments",
    "EventRelatedSubject",
    "EventRelationship",
    "EventSource",
    "EventsourceEvent",
    "EventType",
    "MembershipType",
    "NotificationMethod",
    "Patrol",
    "PatrolType",
    "PatrolFile",
    "PatrolNote",
    "PatrolSegment",
    "PatrolSegmentMembership",
    "RefreshRecreateEventDetailView",
    "Team",
    "TSVectorModel",
    "TeamMembership",
]

eventrevision_models = [
    "EventFileRevision",
    "EventRevision",
    "EventAttachmentRevision",
    "EventNoteRevision",
    "EventDetailsRevision",
    "EventPhotoRevision",
    "PatrolRevision",
    "PatrolNoteRevision",
    "PatrolFileRevision",
    "PatrolSegmentRevision",
    "EventGeometryRevision",
]


def regenerate_primary_keys(apps, schema_editor):
    add_tenant_to_primary_key("activity", activity_models)
    add_tenant_to_primary_key("activity", eventrevision_models)


class Migration(migrations.Migration):
    dependencies = [
        ("activity", "0153_populate_activity_revision_models_with_tenant"),
        ("reports", "0005_add_event_source_history_models"),
    ]

    operations = [migrations.RunPython(code=regenerate_primary_keys, reverse_code=migrations.RunPython.noop)]
