# Generated by Django 3.2.19 on 2023-10-04 17:45

from django.db import migrations

CREATE_TS_VECTOR_DOC_TRIGGER_FUNCTION = """
CREATE OR REPLACE FUNCTION tsvector_doc_trigger() RETURNS TRIGGER AS
$$
BEGIN
    IF (TG_OP = 'INSERT') THEN
        INSERT INTO activity_tsvectormodel (event_id, tsvector_event, id, das_tenant_id)
        SELECT e.id,
               setweight(to_tsvector(et.display)::tsvector, 'A') ||
               setweight(to_tsvector(coalesce(e.title, '')), 'B') ||
               setweight(to_tsvector(et.schema::text), 'B') ||
               setweight(to_tsvector((ed.data #>> '{event_details}')::text), 'A'),
               uuid_generate_v4(),
               new.das_tenant_id
        FROM activity_event e
                 JOIN activity_eventtype et ON e.event_type_id = et.id
                 JOIN activity_eventdetails ed ON e.id = ed.event_id
        WHERE ed.id = NEW.id
        ON CONFLICT DO NOTHING;
    ELSIF (TG_OP = 'UPDATE') THEN
        UPDATE activity_tsvectormodel ts
        SET tsvector_event = setweight(to_tsvector(et.display)::TSVECTOR, 'A') ||
                             setweight(to_tsvector(coalesce(e.title, '')), 'B') ||
                             setweight(to_tsvector(et.schema::TEXT), 'B') ||
                             setweight(to_tsvector((ed.data #>> '{event_details}')::TEXT), 'A')
        FROM activity_event e,
             activity_eventtype et,
             activity_eventdetails ed
        WHERE e.event_type_id = et.id
          AND ed.event_id = e.id
          AND e.id = ts.event_id
          AND ed.id = OLD.id
          AND ed.das_tenant_id = OLD.das_tenant_id;
    END IF;
    RETURN new;
END
$$ LANGUAGE plpgsql;
"""

CREATE_TS_VECTOR_UPDATE_TRIGGER = """
CREATE OR REPLACE TRIGGER tsvector_update
    AFTER INSERT OR UPDATE
    ON activity_eventdetails
    FOR EACH ROW
EXECUTE PROCEDURE tsvector_doc_trigger();
"""


class Migration(migrations.Migration):
    dependencies = [
        ("activity", "0154_regenerate_primary_keys"),
    ]

    operations = [
        migrations.RunSQL(
            sql=CREATE_TS_VECTOR_DOC_TRIGGER_FUNCTION,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql=CREATE_TS_VECTOR_UPDATE_TRIGGER,
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
