# Generated by Django 3.2.19 on 2023-10-04 19:16

from django.db import migrations

CREATE_TS_VECTOR_EVENT_TITLE_TRIGGER_FUNCTION = """
CREATE OR REPLACE FUNCTION tsvector_event_title_trigger() RETURNS trigger as
$$
begin
    update activity_tsvectormodel ts
    set tsvector_event = setweight(to_tsvector(et.display)::tsvector, 'A') ||
                         setweight(to_tsvector(coalesce(e.title, '')), 'B') ||
                         setweight(to_tsvector(et.schema::text), 'B') ||
                         setweight(to_tsvector((ed.data #>> '{event_details}')::text), 'A')
    from activity_event e,
         activity_eventtype et,
         activity_eventdetails ed
    where e.event_type_id = et.id
      and ed.event_id = e.id
      and e.id = ts.event_id
      and e.id = OLD.id
      AND e.das_tenant_id = OLD.das_tenant_id;
    return new;
end
$$ LANGUAGE plpgsql;
"""

CREATE_TS_VECTOR_EVENT_TITLE_UPDATE_TRIGGER = """
CREATE OR REPLACE TRIGGER tsvector_event_title_update
    AFTER UPDATE OF title
    on activity_event
    FOR EACH ROW
EXECUTE PROCEDURE tsvector_event_title_trigger();
"""


class Migration(migrations.Migration):
    dependencies = [
        ("activity", "0155_update_tsvector_update_trigger"),
    ]

    operations = [
        migrations.RunSQL(
            sql=CREATE_TS_VECTOR_EVENT_TITLE_TRIGGER_FUNCTION,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql=CREATE_TS_VECTOR_EVENT_TITLE_UPDATE_TRIGGER,
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
