# Generated by Django 3.2.19 on 2023-10-04 22:22

from django.db import migrations

CREATE_TS_VECTOR_EVEN_NOTE_UPDATE_TRIGGER_FUNCTION = """
CREATE OR REPLACE FUNCTION tsvector_eventnote_trigger() RETURNS trigger as
$$
begin
    UPDATE activity_tsvectormodel ts
    SET (tsvector_event_note) = (SELECT to_tsvector(string_agg(text, ','))::TSVECTOR
                                 FROM activity_eventnote en
                                 WHERE en.event_id = NEW.event_id
                                   AND ts.das_tenant_id = NEW.das_tenant_id)
    WHERE ts.das_tenant_id = NEW.das_tenant_id
      AND ts.event_id = NEW.event_id;
    RETURN new;
end
$$ LANGUAGE plpgsql;
"""

CREATE_TS_VECTOR_EVEN_NOTE_UPDATE_TRIGGER = """
CREATE OR REPLACE TRIGGER tsvector_evennote_update
    AFTER INSERT OR UPDATE
    on activity_eventnote
    FOR EACH ROW
EXECUTE PROCEDURE tsvector_eventnote_trigger();
"""


class Migration(migrations.Migration):
    dependencies = [
        ("activity", "0156_update_tsvector_event_title_update_trigger"),
    ]

    operations = [
        migrations.RunSQL(
            sql=CREATE_TS_VECTOR_EVEN_NOTE_UPDATE_TRIGGER_FUNCTION,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql=CREATE_TS_VECTOR_EVEN_NOTE_UPDATE_TRIGGER,
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
