# Generated by Django 3.2.19 on 2023-10-05 14:13

from django.conf import settings
from django.db import migrations, models

# current DB owner for default db, needed for multiple platforms/databases
db = getattr(settings, "DATABASES", {})
db_user = db["default"]["USER"] if "default" in db else "postgres"
# and because Azure requires the host name to be prepended, we need to
# strip off anything with an '@' in it
if "@" in db_user:
    parts = db_user.split("@")
    db_user = parts[0]


class Migration(migrations.Migration):
    dependencies = [
        ("activity", "0157_update_tsvector_evennote_update_trigger"),
    ]

    operations = [
        migrations.RunSQL(
            sql="alter table activity_event alter COLUMN serial_number drop default;",
            reverse_sql="alter table activity_event alter column serial_number set default nextval('activity_event_serial_number_seq'::regclass);",
        ),
        migrations.RunSQL(
            sql="""drop sequence activity_event_serial_number_seq ;""",
            reverse_sql="""CREATE SEQUENCE public.activity_event_serial_number_seq
                          INCREMENT 1
                          MINVALUE 1
                          MAXVALUE 9223372036854775807
                          START 1
                          CACHE 1;
                          ALTER TABLE public.activity_event_serial_number_seq
                          OWNER TO {};""".format(
                db_user
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="serial_number",
            field=models.BigIntegerField(blank=True, null=True, verbose_name="Serial Number"),
        ),
    ]
