# Generated by Django 3.2.19 on 2023-10-06 02:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("activity", "0158_alter_event_serial_number"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="event",
            constraint=models.UniqueConstraint(
                fields=("das_tenant", "serial_number"), name="activity_event_tenant_serial_number_unique"
            ),
        ),
    ]
