# Generated by Django 3.2.19 on 2023-10-06 02:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("activity", "0158_alter_event_serial_number"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="event",
            index=models.Index(fields=["das_tenant", "serial_number"], name="activity_ev_das_ten_0f89c5_idx"),
        ),
    ]
