# Generated by Django 3.2.19 on 2023-10-16 15:52

import django.db.models.deletion
from django.db import migrations, models

import utils.migrations.columns


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0011_regenerate_primary_keys"),
        ("activity", "0160_make_das_tenant_field_required"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventattachmentrevision",
            name="das_tenant",
            field=models.ForeignKey(
                default=utils.migrations.columns.default_tenant_id,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activity_eventattachmentrevision",
                to="core.dastenant",
            ),
        ),
        migrations.AlterField(
            model_name="eventdetailsrevision",
            name="das_tenant",
            field=models.ForeignKey(
                default=utils.migrations.columns.default_tenant_id,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activity_eventdetailsrevision",
                to="core.dastenant",
            ),
        ),
        migrations.AlterField(
            model_name="eventfilerevision",
            name="das_tenant",
            field=models.ForeignKey(
                default=utils.migrations.columns.default_tenant_id,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activity_eventfilerevision",
                to="core.dastenant",
            ),
        ),
        migrations.AlterField(
            model_name="eventgeometryrevision",
            name="das_tenant",
            field=models.ForeignKey(
                default=utils.migrations.columns.default_tenant_id,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activity_eventgeometryrevision",
                to="core.dastenant",
            ),
        ),
        migrations.AlterField(
            model_name="eventnoterevision",
            name="das_tenant",
            field=models.ForeignKey(
                default=utils.migrations.columns.default_tenant_id,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activity_eventnoterevision",
                to="core.dastenant",
            ),
        ),
        migrations.AlterField(
            model_name="eventphotorevision",
            name="das_tenant",
            field=models.ForeignKey(
                default=utils.migrations.columns.default_tenant_id,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activity_eventphotorevision",
                to="core.dastenant",
            ),
        ),
        migrations.AlterField(
            model_name="eventrevision",
            name="das_tenant",
            field=models.ForeignKey(
                default=utils.migrations.columns.default_tenant_id,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activity_eventrevision",
                to="core.dastenant",
            ),
        ),
        migrations.AlterField(
            model_name="patrolfilerevision",
            name="das_tenant",
            field=models.ForeignKey(
                default=utils.migrations.columns.default_tenant_id,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activity_patrolfilerevision",
                to="core.dastenant",
            ),
        ),
        migrations.AlterField(
            model_name="patrolnoterevision",
            name="das_tenant",
            field=models.ForeignKey(
                default=utils.migrations.columns.default_tenant_id,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activity_patrolnoterevision",
                to="core.dastenant",
            ),
        ),
        migrations.AlterField(
            model_name="patrolrevision",
            name="das_tenant",
            field=models.ForeignKey(
                default=utils.migrations.columns.default_tenant_id,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activity_patrolrevision",
                to="core.dastenant",
            ),
        ),
        migrations.AlterField(
            model_name="patrolsegmentrevision",
            name="das_tenant",
            field=models.ForeignKey(
                default=utils.migrations.columns.default_tenant_id,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activity_patrolsegmentrevision",
                to="core.dastenant",
            ),
        ),
    ]
