# Generated by Django 3.2.19 on 2023-10-11 12:42

from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models

# current DB owner for default db, needed for multiple platforms/databases
db = getattr(settings, "DATABASES", {})
db_user = db["default"]["USER"] if "default" in db else "postgres"
# and because Azure requires the host name to be prepended, we need to
# strip off anything with an '@' in it
if "@" in db_user:
    parts = db_user.split("@")
    db_user = parts[0]


class Migration(migrations.Migration):
    dependencies = [
        ("activity", "0161_auto_20231016_0852"),
    ]

    operations = [
        migrations.RunSQL(
            sql="alter table activity_patrol alter COLUMN serial_number drop default;",
            reverse_sql="alter table activity_patrol alter column serial_number set default nextval('activity_patrol_serial_number_seq'::regclass);",
        ),
        migrations.RunSQL(
            sql="DROP SEQUENCE IF EXISTS activity_patrol_unique_serial",
            reverse_sql="CREATE SEQUENCE activity_patrol_unique_serial START 1 INCREMENT 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1",
        ),
        migrations.RunSQL(
            sql="""drop sequence activity_patrol_serial_number_seq ;""",
            reverse_sql="""CREATE SEQUENCE public.activity_patrol_serial_number_seq
                         INCREMENT 1
                         MINVALUE 1
                         MAXVALUE 9223372036854775807
                         START 1
                         CACHE 1;
                         ALTER TABLE public.activity_patrol_serial_number_seq
                         OWNER TO {};""".format(
                db_user
            ),
        ),
        migrations.AlterField(
            model_name="patrol",
            name="serial_number",
            field=models.BigIntegerField(blank=True, null=True, verbose_name="Serial Number"),
        ),
    ]
