# Generated by Django 3.2.19 on 2023-10-11 12:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("activity", "0162_alter_patrol_serial_number"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="patrol",
            constraint=models.UniqueConstraint(
                fields=("das_tenant", "serial_number"), name="activity_patrol_tenant_serial_number_unique"
            ),
        ),
    ]
