# Generated by Django 3.2.21 on 2023-11-01 22:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("activity", "0163_patrol_tenant_serial_number_unique"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventcategory",
            name="value",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="eventclass",
            name="value",
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name="eventfactor",
            name="value",
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name="eventrelationshiptype",
            name="value",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="eventtype",
            name="value",
            field=models.CharField(
                max_length=255,
                validators=[
                    django.core.validators.RegexValidator(
                        message="An invalid character was detected in the Event type Value field.\n        Supported characters are: Letters a-z (lowercase), Numbers 0-9 and Underscore",
                        regex="^[A-Za-z0-9-_]*$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="membershiptype",
            name="value",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="patroltype",
            name="value",
            field=models.CharField(max_length=50),
        ),
        migrations.AddIndex(
            model_name="eventcategory",
            index=models.Index(fields=["das_tenant", "value"], name="eventcategory_val_idx"),
        ),
        migrations.AddIndex(
            model_name="eventclass",
            index=models.Index(fields=["das_tenant", "value"], name="eventclass_val_idx"),
        ),
        migrations.AddIndex(
            model_name="eventfactor",
            index=models.Index(fields=["das_tenant", "value"], name="eventfactor_val_idx"),
        ),
        migrations.AddIndex(
            model_name="eventrelationshiptype",
            index=models.Index(fields=["das_tenant", "value"], name="eventrelationshiptype_val_idx"),
        ),
        migrations.AddIndex(
            model_name="eventtype",
            index=models.Index(fields=["das_tenant", "value"], name="activity_eventtype_val_idx"),
        ),
        migrations.AddIndex(
            model_name="membershiptype",
            index=models.Index(fields=["das_tenant", "value"], name="membershiptype_val_idx"),
        ),
        migrations.AddIndex(
            model_name="patroltype",
            index=models.Index(fields=["das_tenant", "value"], name="patroltype_val_idx"),
        ),
        migrations.AddConstraint(
            model_name="eventcategory",
            constraint=models.UniqueConstraint(
                fields=("das_tenant", "value"), name="activity_eventcategory_unique_value_across_tenants"
            ),
        ),
        migrations.AddConstraint(
            model_name="eventclass",
            constraint=models.UniqueConstraint(
                fields=("das_tenant", "value"), name="activity_eventclass_unique_value_across_tenants"
            ),
        ),
        migrations.AddConstraint(
            model_name="eventfactor",
            constraint=models.UniqueConstraint(
                fields=("das_tenant", "value"), name="activity_eventfactor_unique_value_across_tenants"
            ),
        ),
        migrations.AddConstraint(
            model_name="eventrelationshiptype",
            constraint=models.UniqueConstraint(
                fields=("das_tenant", "value"), name="activity_eventrelationshiptype_unique_value_across_tenants"
            ),
        ),
        migrations.AddConstraint(
            model_name="eventtype",
            constraint=models.UniqueConstraint(
                fields=("das_tenant", "value"), name="activity_eventtype_unique_value_across_tenants"
            ),
        ),
        migrations.AddConstraint(
            model_name="membershiptype",
            constraint=models.UniqueConstraint(
                fields=("das_tenant", "value"), name="activity_membershiptype_unique_value_across_tenants"
            ),
        ),
        migrations.AddConstraint(
            model_name="patroltype",
            constraint=models.UniqueConstraint(
                fields=("das_tenant", "value"), name="activity_patroltype_unique_value_across_tenants"
            ),
        ),
    ]
