# Generated by Django 3.2.21 on 2023-11-16 15:46

import django_multitenant.fields

import django.db.models.deletion
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("activity", "0164_made_activity_models_fields_unique_per_tenant"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tsvectormodel",
            name="event",
            field=django_multitenant.fields.TenantOneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="activity.event"
            ),
        ),
    ]
