# Generated by Django 3.2.21 on 2023-11-16 19:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0013_auto_20231115_1758"),
        ("activity", "0165_update_field_to_tenantonetoonefield"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="eventattachmentrevision",
            unique_together={("das_tenant", "object_id", "sequence")},
        ),
        migrations.AlterUniqueTogether(
            name="eventdetailsrevision",
            unique_together={("das_tenant", "object_id", "sequence")},
        ),
        migrations.AlterUniqueTogether(
            name="eventfilerevision",
            unique_together={("das_tenant", "object_id", "sequence")},
        ),
        migrations.AlterUniqueTogether(
            name="eventgeometryrevision",
            unique_together={("das_tenant", "object_id", "sequence")},
        ),
        migrations.AlterUniqueTogether(
            name="eventnoterevision",
            unique_together={("das_tenant", "object_id", "sequence")},
        ),
        migrations.AlterUniqueTogether(
            name="eventphotorevision",
            unique_together={("das_tenant", "object_id", "sequence")},
        ),
        migrations.AlterUniqueTogether(
            name="eventrevision",
            unique_together={("das_tenant", "object_id", "sequence")},
        ),
        migrations.AlterUniqueTogether(
            name="patrolfilerevision",
            unique_together={("das_tenant", "object_id", "sequence")},
        ),
        migrations.AlterUniqueTogether(
            name="patrolnoterevision",
            unique_together={("das_tenant", "object_id", "sequence")},
        ),
        migrations.AlterUniqueTogether(
            name="patrolrevision",
            unique_together={("das_tenant", "object_id", "sequence")},
        ),
        migrations.AlterUniqueTogether(
            name="patrolsegmentrevision",
            unique_together={("das_tenant", "object_id", "sequence")},
        ),
    ]
