# Generated by Django 3.2.21 on 2023-11-19 00:56

from django.db import migrations

import activity.models
import utils.models


class Migration(migrations.Migration):
    dependencies = [
        ("activity", "0166_auto_20231116_1118"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="community",
            options={
                "base_manager_name": "objects",
                "verbose_name": "Event Reporters",
                "verbose_name_plural": "Event Reporters",
            },
        ),
        migrations.AlterModelManagers(
            name="alertrule",
            managers=[
                ("objects", utils.models.CommonTenantManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="community",
            managers=[
                ("objects", activity.models.CommunityManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="event",
            managers=[
                ("objects", activity.models.EventManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="eventattachment",
            managers=[
                ("objects", activity.models.EventAttachmentManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="eventcategory",
            managers=[
                ("objects", activity.models.EventBaseManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="eventclass",
            managers=[
                ("objects", activity.models.EventBaseManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="eventclassfactor",
            managers=[
                ("objects", utils.models.CommonTenantManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="eventdetails",
            managers=[
                ("objects", activity.models.EventDetailsManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="eventfactor",
            managers=[
                ("objects", activity.models.EventBaseManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="eventfile",
            managers=[
                ("objects", utils.models.CommonTenantManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="eventfilter",
            managers=[
                ("objects", utils.models.CommonTenantManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="eventgeometry",
            managers=[
                ("objects", utils.models.CommonTenantManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="eventnote",
            managers=[
                ("objects", activity.models.EventNoteManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="eventnotification",
            managers=[
                ("objects", utils.models.CommonTenantManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="eventphoto",
            managers=[
                ("objects", utils.models.CommonTenantManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="eventprovider",
            managers=[
                ("objects", utils.models.CommonTenantManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="eventrelatedsegments",
            managers=[
                ("objects", utils.models.CommonTenantManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="eventrelatedsubject",
            managers=[
                ("objects", utils.models.CommonTenantManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="eventrelationship",
            managers=[
                ("objects", activity.models.EventRelationshipManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="eventrelationshiptype",
            managers=[
                ("objects", activity.models.EventBaseManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="eventsource",
            managers=[
                ("objects", utils.models.CommonTenantManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="eventsourceevent",
            managers=[
                ("objects", activity.models.EventsourceEventManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="eventtype",
            managers=[
                ("objects", activity.models.EventTypeManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="membershiptype",
            managers=[
                ("objects", utils.models.CommonTenantManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="notificationmethod",
            managers=[
                ("objects", utils.models.CommonTenantManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="patrol",
            managers=[
                ("objects", activity.models.PatrolManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="patrolconfiguration",
            managers=[
                ("objects", utils.models.CommonTenantManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="patrolconfigurationsubjectgroup",
            managers=[
                ("objects", utils.models.CommonTenantManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="patrolfile",
            managers=[
                ("objects", utils.models.CommonTenantManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="patrolnote",
            managers=[
                ("objects", utils.models.CommonTenantManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="patrolsegment",
            managers=[
                ("objects", activity.models.PatrolSegmentManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="patrolsegmentmembership",
            managers=[
                ("objects", utils.models.CommonTenantManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="patroltype",
            managers=[
                ("objects", activity.models.PatrolTypeManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="refreshrecreateeventdetailview",
            managers=[
                ("objects", activity.models.RefreshRecreateEventDetailViewManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="team",
            managers=[
                ("objects", utils.models.CommonTenantManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="teammembership",
            managers=[
                ("objects", utils.models.CommonTenantManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="tsvectormodel",
            managers=[
                ("objects", utils.models.CommonTenantManager()),
            ],
        ),
    ]
