# Generated by Django 3.2.21 on 2023-11-19 01:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("activity", "0167_tenantmanager"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="patrolconfiguration",
            managers=[],
        ),
        migrations.AlterModelManagers(
            name="patrolconfigurationsubjectgroup",
            managers=[],
        ),
    ]
