# Generated by Django 3.2.21 on 2023-11-19 17:58

import django.db.models.deletion
from django.db import migrations, models

import utils.migrations.columns
import utils.models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0013_auto_20231115_1758"),
        ("activity", "0168_tenantmanager"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="patrolconfiguration",
            managers=[
                ("objects", utils.models.CommonTenantManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="patrolconfigurationsubjectgroup",
            managers=[
                ("objects", utils.models.CommonTenantManager()),
            ],
        ),
        migrations.AddField(
            model_name="patrolconfiguration",
            name="das_tenant",
            field=models.ForeignKey(
                default=utils.migrations.columns.default_tenant_id,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.dastenant",
            ),
        ),
    ]
