# Generated by Django 3.2.21 on 2023-11-19 19:27

import uuid

import django_multitenant.fields

import django.db.models.deletion
from django.db import migrations, models

import utils.migrations.columns


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0013_auto_20231115_1758"),
        ("observations", "0156_update_field_to_tenantonetoonefield"),
        ("activity", "0169_singleton_tenant_aware"),
    ]

    operations = [
        migrations.AddField(
            model_name="patrolconfiguration",
            name="instance_id",
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AddField(
            model_name="patrolconfigurationsubjectgroup",
            name="das_tenant",
            field=models.ForeignKey(
                default=utils.migrations.columns.default_tenant_id,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.dastenant",
            ),
        ),
        migrations.AlterField(
            model_name="patrolconfigurationsubjectgroup",
            name="patrolconfiguration",
            field=django_multitenant.fields.TenantForeignKey(
                blank=True, on_delete=django.db.models.deletion.CASCADE, to="activity.patrolconfiguration"
            ),
        ),
        migrations.AlterField(
            model_name="patrolconfigurationsubjectgroup",
            name="subjectgroup",
            field=django_multitenant.fields.TenantForeignKey(
                blank=True, on_delete=django.db.models.deletion.CASCADE, to="observations.subjectgroup"
            ),
        ),
    ]
