# Generated by Django 3.2.21 on 2023-11-22 17:11

from django.db import migrations

from utils.migrations.update_primary_key import (
    add_tenant_to_primary_key,
    drop_constraint,
)

APP_NAME = "activity"

activity_models = [
    "PatrolConfigurationSubjectGroup",
]


def regenerate_primary_keys(apps, schema_editor):
    add_tenant_to_primary_key(APP_NAME, activity_models)


def drop_constraints(apps, schema_editor):
    drop_constraint(
        app=APP_NAME,
        model="PatrolConfigurationSubjectGroup",
        constraint="activity_patrolconfigurationsubjectgroup_id_a8d9f2df_uniq",
    )
    drop_constraint(
        app=APP_NAME,
        model="RefreshRecreateEventDetailView",
        constraint="activity_refreshrecreateeventdetailview_id_43c6e3d6_uniq",
    )
    drop_constraint(app=APP_NAME, model="TSVectorModel", constraint="activity_tsvectormodel_event_id_key")


class Migration(migrations.Migration):
    dependencies = [
        ("activity", "0170_patrolconfigurationsubjectgroup_tenant_aware"),
    ]

    operations = [
        migrations.RunPython(code=regenerate_primary_keys, reverse_code=migrations.RunPython.noop),
        migrations.RunPython(code=drop_constraints, reverse_code=migrations.RunPython.noop),
    ]
