# Generated by Django 3.2.21 on 2023-11-24 21:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("activity", "0171_regenerate_pk_activity_models"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="eventtype",
            options={"base_manager_name": "objects", "default_manager_name": "objects", "ordering": ["display"]},
        ),
    ]
