# Generated by Django 3.2.21 on 2023-11-25 00:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("activity", "0172_alter_eventtype_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="alertrule",
            options={"base_manager_name": "objects", "default_manager_name": "objects"},
        ),
        migrations.AlterModelOptions(
            name="notificationmethod",
            options={"base_manager_name": "objects", "default_manager_name": "objects"},
        ),
    ]
