# Generated by Django 3.2.21 on 2023-11-25 18:50

from django.db import migrations

from utils.migrations.update_primary_key import (
    add_tenant_to_primary_key,
    drop_constraint,
)

APP_NAME = "activity"

activity_models = [
    "PatrolConfiguration",
]


def regenerate_primary_keys(apps, schema_editor):
    add_tenant_to_primary_key(APP_NAME, activity_models)


def drop_constraints(apps, schema_editor):
    drop_constraint(
        app=APP_NAME,
        model="PatrolConfiguration",
        constraint="activity_patrolconfiguration_id_012673d1_uniq",
        cascade=True,
    )


class Migration(migrations.Migration):
    dependencies = [
        ("activity", "0173_defaultmanager"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="patrolconfiguration",
            name="instance_id",
        ),
        migrations.RunPython(code=regenerate_primary_keys, reverse_code=migrations.RunPython.noop),
        migrations.RunPython(code=drop_constraints, reverse_code=migrations.RunPython.noop),
    ]
