# Generated by Django 3.2.21 on 2023-11-26 21:09
import logging

from django_multitenant.utils import get_current_tenant, set_current_tenant

from django.apps import apps
from django.contrib.contenttypes.models import ContentType
from django.core.management import CommandError, call_command
from django.db import migrations, models
from django.db.models import Q

from accounts.utils import add_tenant_to_permission_codename, parse_permission_codename
from activity.util import ensure_eventcategory_perms_exist
from utils.tenant.managers import UnsetDASTenantContextManager

logger = logging.getLogger(__name__)


def migrate_eventcategory_permissions(unused, schema_editor):
    PermissionSet = apps.get_model("accounts", "PermissionSet")
    Permission = apps.get_model("auth", "Permission")
    EventCategory = apps.get_model("activity", "EventCategory")
    DASTenant = apps.get_model("core", "DASTenant")

    previous_tenant = get_current_tenant()
    ct_event = ContentType.objects.get(app_label="activity", model="event")
    origin_tenant = DASTenant.objects.get_origin()

    set_current_tenant(origin_tenant)

    # fixing the origin tenant event model permissions by adding codename
    permissions_updated = 0
    for permission in Permission.objects.filter(content_type=ct_event, permission_sets__in=PermissionSet.objects.all()):
        if permission.codename.endswith("_geographic_distance"):
            permission.codename = permission.codename[: -len("_geographic_distance")] + "_gd"
        permission.codename = add_tenant_to_permission_codename(origin_tenant.id, permission.codename)
        permission.save(update_fields=["codename"])
        permissions_updated += 1

    logger.info("Found %s permission records for the Event model", permissions_updated)

    with UnsetDASTenantContextManager():
        das_tenants = list(DASTenant.objects.all().exclude(Q(id=origin_tenant.id)))

    # fix all the other existing tenants
    for das_tenant in das_tenants:
        set_current_tenant(das_tenant)

        # first we unhook any event model permission that does not have a codename pointed to this tenant
        for permissionset in PermissionSet.objects.filter(permissions__content_type=ct_event):
            for permission in list(permissionset.permissions.filter(content_type=ct_event)):
                p_tenant_id, codename = parse_permission_codename(permission.codename)
                if p_tenant_id:
                    if p_tenant_id != das_tenant.id:
                        permissionset.permissions.remove(permission)
                    else:
                        pass
                else:
                    if permission.codename.endswith("_geographic_distance"):
                        permission.codename = permission.codename[: -len("_geographic_distance")] + "_gd"
                    permission.codename = add_tenant_to_permission_codename(das_tenant.id, permission.codename)
                    permission.save(update_fields=["codename"])

        # ensure all tenant eventcategories have permissionset permissions scoped to this tenant
        for eventcategory in EventCategory.objects.all():
            ensure_eventcategory_perms_exist(eventcategory, tenant_id=das_tenant.id)

        try:
            # next we re-load the standard event related permissions sets
            call_command(
                "loaddata_with_tenant", "migrate_event_permissionsets_codename.json", tenant_domain=das_tenant.domain
            )
        except CommandError as cex:
            if "Error setting tenant" in str(cex):
                logger.error(
                    "Tenant %s not found in TMS while running loaddata_with_tenant to load migrate_event_permissionssets_codename",
                    das_tenant.domain,
                )
            else:
                raise

    set_current_tenant(previous_tenant)


class Migration(migrations.Migration):
    dependencies = [("activity", "0174_patrolconfig"), ("core", "0016_alter_dastenant_managers")]

    operations = [
        migrations.AlterModelOptions(
            name="event",
            options={"permissions": ()},
        ),
        migrations.AlterField(
            model_name="eventcategory",
            name="value",
            field=models.CharField(max_length=67),
        ),
        migrations.RunPython(migrate_eventcategory_permissions, reverse_code=migrations.RunPython.noop),
    ]
