# Generated by Django 3.2.21 on 2024-02-08 01:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("activity", "0175_tenantpermissions"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="community",
            options={
                "base_manager_name": "objects",
                "default_manager_name": "objects",
                "verbose_name": "Event Reporters",
                "verbose_name_plural": "Event Reporters",
            },
        ),
        migrations.AlterModelOptions(
            name="event",
            options={"base_manager_name": "objects", "default_manager_name": "objects", "permissions": ()},
        ),
        migrations.AlterModelOptions(
            name="eventattachment",
            options={"base_manager_name": "objects", "default_manager_name": "objects"},
        ),
        migrations.AlterModelOptions(
            name="eventcategory",
            options={
                "base_manager_name": "objects",
                "default_manager_name": "objects",
                "verbose_name": "Event Category",
                "verbose_name_plural": "Event Categories",
            },
        ),
        migrations.AlterModelOptions(
            name="eventdetails",
            options={"base_manager_name": "objects", "default_manager_name": "objects"},
        ),
        migrations.AlterModelOptions(
            name="eventfile",
            options={
                "base_manager_name": "objects",
                "default_manager_name": "objects",
                "ordering": ["ordernum", "-updated_at"],
            },
        ),
        migrations.AlterModelOptions(
            name="eventfilter",
            options={"base_manager_name": "objects", "default_manager_name": "objects"},
        ),
        migrations.AlterModelOptions(
            name="eventgeometry",
            options={"base_manager_name": "objects", "default_manager_name": "objects"},
        ),
        migrations.AlterModelOptions(
            name="eventnote",
            options={"base_manager_name": "objects", "default_manager_name": "objects"},
        ),
        migrations.AlterModelOptions(
            name="eventnotification",
            options={"base_manager_name": "objects", "default_manager_name": "objects"},
        ),
        migrations.AlterModelOptions(
            name="eventphoto",
            options={"base_manager_name": "objects", "default_manager_name": "objects"},
        ),
        migrations.AlterModelOptions(
            name="eventprovider",
            options={"base_manager_name": "objects", "default_manager_name": "objects"},
        ),
        migrations.AlterModelOptions(
            name="eventrelatedsegments",
            options={"base_manager_name": "objects", "default_manager_name": "objects"},
        ),
        migrations.AlterModelOptions(
            name="eventrelatedsubject",
            options={"base_manager_name": "objects", "default_manager_name": "objects"},
        ),
        migrations.AlterModelOptions(
            name="eventrelationship",
            options={
                "base_manager_name": "objects",
                "default_manager_name": "objects",
                "ordering": ["type", "ordernum"],
            },
        ),
        migrations.AlterModelOptions(
            name="eventrelationshiptype",
            options={"base_manager_name": "objects", "default_manager_name": "objects"},
        ),
        migrations.AlterModelOptions(
            name="eventsource",
            options={
                "base_manager_name": "objects",
                "default_manager_name": "objects",
                "permissions": (("create_event_for_eventsource", "Permission to add an event for an event source"),),
            },
        ),
        migrations.AlterModelOptions(
            name="eventsourceevent",
            options={"base_manager_name": "objects", "default_manager_name": "objects"},
        ),
        migrations.AlterModelOptions(
            name="membershiptype",
            options={"base_manager_name": "objects", "default_manager_name": "objects"},
        ),
        migrations.AlterModelOptions(
            name="patrol",
            options={"base_manager_name": "objects", "default_manager_name": "objects"},
        ),
        migrations.AlterModelOptions(
            name="patrolconfiguration",
            options={"base_manager_name": "objects", "default_manager_name": "objects"},
        ),
        migrations.AlterModelOptions(
            name="patrolconfigurationsubjectgroup",
            options={"base_manager_name": "objects", "default_manager_name": "objects"},
        ),
        migrations.AlterModelOptions(
            name="patrolfile",
            options={"base_manager_name": "objects", "default_manager_name": "objects"},
        ),
        migrations.AlterModelOptions(
            name="patrolnote",
            options={"base_manager_name": "objects", "default_manager_name": "objects"},
        ),
        migrations.AlterModelOptions(
            name="patrolsegment",
            options={"base_manager_name": "objects", "default_manager_name": "objects"},
        ),
        migrations.AlterModelOptions(
            name="patrolsegmentmembership",
            options={
                "base_manager_name": "objects",
                "default_manager_name": "objects",
                "ordering": ["type", "ordernum"],
            },
        ),
        migrations.AlterModelOptions(
            name="patroltype",
            options={"base_manager_name": "objects", "default_manager_name": "objects"},
        ),
        migrations.AlterModelOptions(
            name="refreshrecreateeventdetailview",
            options={
                "base_manager_name": "objects",
                "default_manager_name": "objects",
                "verbose_name_plural": "Refresh Data for Tableau",
            },
        ),
        migrations.AlterModelOptions(
            name="team",
            options={"base_manager_name": "objects", "default_manager_name": "objects"},
        ),
        migrations.AlterModelOptions(
            name="teammembership",
            options={
                "base_manager_name": "objects",
                "default_manager_name": "objects",
                "ordering": ["type", "ordernum"],
            },
        ),
        migrations.AlterModelOptions(
            name="tsvectormodel",
            options={"base_manager_name": "objects", "default_manager_name": "objects"},
        ),
    ]
