# Generated by Django 3.2.21 on 2024-02-26 16:48

import uuid
from functools import partial

from django_multitenant.fields import TenantForeignKey

import django.db.models.deletion
from django.db import migrations, models

import utils.migrations.columns
from core.utils import backfill_through_model_with_tenant
from utils.migrations import populate_model_uuid_column
from utils.migrations.update_primary_key import add_tenant_to_primary_key

APP_NAME = "activity"
ACTIVITY_MODELS = ["AlertRuleNotificationMethod"]

CURRENT_TABLE_NAME = "activity_alertrule_notification_methods"
NEW_TABLE_NAME = "activity_alertrulenotificationmethod"


populate_uuid = partial(populate_model_uuid_column, "activity", "AlertRuleNotificationMethod", "uuid")
populate_through_model_tenant_id = partial(
    backfill_through_model_with_tenant, "activity_alertrule", "id", NEW_TABLE_NAME, "alertrule_id"
)


def regenerate_primary_keys(apps, schema_editor):
    add_tenant_to_primary_key(APP_NAME, ACTIVITY_MODELS)


class Migration(migrations.Migration):
    dependencies = [
        ("activity", "0176_defaultmanager"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=f"ALTER TABLE {CURRENT_TABLE_NAME} RENAME TO {NEW_TABLE_NAME}",
                    reverse_sql=f"ALTER TABLE {NEW_TABLE_NAME} RENAME TO {CURRENT_TABLE_NAME}",
                ),
            ],
            state_operations=[
                migrations.CreateModel(
                    name="AlertRuleNotificationMethod",
                    fields=[
                        ("id", models.AutoField(serialize=False)),
                        (
                            "alertrule",
                            TenantForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                to="activity.AlertRule",
                            ),
                        ),
                        (
                            "notificationmethod",
                            TenantForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                to="activity.NotificationMethod",
                            ),
                        ),
                    ],
                ),
                migrations.AlterField(
                    model_name="AlertRule",
                    name="notification_methods",
                    field=models.ManyToManyField(
                        to="self",
                        related_name="alert_rules",
                        through="activity.AlertRuleNotificationMethod",
                        through_fields=("alertrule", "notificationmethod"),
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="AlertRuleNotificationMethod",
            name="uuid",
            field=models.UUIDField(null=True),
        ),
        migrations.RunPython(
            code=populate_uuid,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name="AlertRuleNotificationMethod",
            name="id",
        ),
        migrations.RenameField(
            model_name="AlertRuleNotificationMethod",
            old_name="uuid",
            new_name="id",
        ),
        migrations.AlterField(
            model_name="AlertRuleNotificationMethod",
            name="id",
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, editable=False, serialize=True),
        ),
        migrations.AlterModelManagers(
            name="AlertRuleNotificationMethod",
            managers=[
                ("objects", utils.models.CommonTenantManager()),
            ],
        ),
        migrations.AlterModelOptions(
            name="AlertRuleNotificationMethod",
            options={"base_manager_name": "objects", "default_manager_name": "objects"},
        ),
        migrations.AddField(
            model_name="AlertRuleNotificationMethod",
            name="das_tenant",
            field=models.ForeignKey(
                default=utils.migrations.columns.default_tenant_id,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.dastenant",
            ),
        ),
        migrations.RunPython(
            code=regenerate_primary_keys,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RunPython(
            code=populate_through_model_tenant_id,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
