# Generated by Django 3.2.21 on 2024-06-05 17:41

from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("core", "0024_recreate_useragreement_eula_fk"),
        ("activity", "0178_add_custom_through_table_for_alertrule_eventtype"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventcategory",
            name="ordernum",
            field=models.FloatField(default=0),
        ),
        migrations.AddIndex(
            model_name="eventcategory",
            index=models.Index(fields=["das_tenant", "ordernum"], name="eventcategory_order_idx"),
        ),
    ]
