# Generated by Django 3.2.21 on 2024-06-05 17:41

from django.apps import apps
from django.db import migrations, models

from utils.rank import RankedTool


def set_default_ordernum_value_ranked(migration_apps, schema_editor):
    EventCategory = apps.get_model("activity", "EventCategory")
    DASTenant = apps.get_model("core", "DASTenant")

    for tenant in DASTenant.objects.all():
        qs = EventCategory.objects.filter(das_tenant_id=tenant.id).order_by("ordernum", "value")
        RankedTool.make_full_rebalance(queryset=qs)


class Migration(migrations.Migration):
    dependencies = [
        ("activity", "0179_change_ordernum_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventcategory",
            name="ordernum",
            field=models.FloatField(db_index=True, default=0),
        ),
        migrations.RunPython(code=set_default_ordernum_value_ranked, reverse_code=migrations.RunPython.noop),
    ]
