# Generated by Django 3.2.21 on 2024-06-12 19:47

from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ("core", "0024_recreate_useragreement_eula_fk"),
        ("activity", "0180_ranking_all_ordernums"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventtype",
            name="ordernum",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="eventcategory",
            name="ordernum",
            field=models.FloatField(default=0),
        ),
        migrations.RemoveIndex(
            model_name="eventcategory",
            name="eventcategory_order_idx",
        ),
        migrations.AddIndex(
            model_name="eventcategory",
            index=models.Index(fields=["das_tenant", "ordernum"], name="eventcategory_ordernum_idx"),
        ),
        migrations.AddIndex(
            model_name="eventtype",
            index=models.Index(fields=["das_tenant", "ordernum"], name="eventtype_ordernum_idx"),
        ),
    ]
