# Generated by Django 3.2.21 on 2024-06-12 19:55

import uuid

from django_multitenant.fields import TenantForeignKey
from django_multitenant.mixins import TenantModelMixin

from django.db import migrations, models
from django.db.models import Index, Q, UniqueConstraint

from utils.rank import RankedTool
from utils.tenant.managers import TenantContextManager


# pylint: disable=import-outside-toplevel, invalid-name
def get_migration_models():
    """
    A place to return the historical versions of the models used in this migration.
    This isolates the model definitions from changes in the live code.

    Notes:
    - Give an alias to the model classes to avoid conflicts with the live models or any other model definitions across
      the project. E.g., Migration0182EventType
    - In the meta class, the following attributes are important:
        - `managed = False`: This is to prevent Django from modifying the table for this model.
        - `app_label = "activity"`: This is to ensure that the model is in the correct app.
        - `db_table = "activity_eventtype"`: This is to ensure that the model is mapped to the correct table.
    """

    # For models that are not likely to change like DASTenant, import them `directly`.
    from core.models import DASTenant, TimestampedModel
    from utils.migrations.columns import default_tenant_id

    PRI_URGENT = 300
    PRI_IMPORTANT = 200
    PRI_REFERENCE = 100
    PRI_NONE = 0
    PRIORITY_CHOICES = (
        (PRI_NONE, "Gray"),
        (PRI_REFERENCE, "Green"),
        (PRI_IMPORTANT, "Amber"),
        (PRI_URGENT, "Red"),
    )

    SC_NEW = "new"
    SC_ACTIVE = "active"
    SC_RESOLVED = "resolved"
    STATE_CHOICES = (
        (SC_NEW, "New"),
        (SC_ACTIVE, "Active"),
        (SC_RESOLVED, "Resolved"),
    )

    class Migration0182EventCategory(TenantModelMixin, TimestampedModel):

        id = models.UUIDField(primary_key=True, default=uuid.uuid4)
        value = models.CharField(max_length=67)
        display = models.CharField(max_length=100, blank=True)
        ordernum = models.FloatField(default=0)
        is_active = models.BooleanField(default=True)
        flag = models.CharField(max_length=40, default="user", choices=(("user", "User"), ("system", "System")))

        das_tenant = models.ForeignKey(DASTenant, on_delete=models.CASCADE, default=default_tenant_id)
        tenant_id = "das_tenant_id"

        class Meta:
            managed = False
            app_label = "activity"
            db_table = "activity_eventcategory"
            constraints = [
                UniqueConstraint(
                    fields=["das_tenant", "value"],
                    name="%(app_label)s_%(class)s_unique_value_across_tenants",
                )
            ]
            indexes = [
                Index(fields=["das_tenant", "value"], name="%(class)s_val_idx"),
                Index(fields=["das_tenant", "ordernum"], name="%(class)s_ordernum_idx"),
            ]

        def save(self, *args, **kwargs):
            if not self.ordernum:
                ranked_tool = RankedTool(instance=self, before_key=None)
                new_order_value = ranked_tool.get_first_value_to_insert()
                self.ordernum = new_order_value
            super().save(*args, **kwargs)

        def natural_key(self):
            return (self.value,)

        @property
        def auto_permissionset_name(self):
            return f"View {self.display} Event Permissions"

        @property
        def auto_geographic_permission_set_name(self):
            return f"View {self.display} Event Geographic Permissions"

    class Migration0182EventType(TenantModelMixin, TimestampedModel):
        """
        Frozen version of EventType model as it existed at the time of this migration.
        """

        class GeometryTypesChoices(models.TextChoices):
            POINT = "Point"
            POLYGON = "Polygon"

        id = models.UUIDField(primary_key=True, default=uuid.uuid4)
        value = models.CharField(max_length=255)
        display = models.CharField(max_length=255, blank=True)
        category = TenantForeignKey(
            Migration0182EventCategory, null=True, on_delete=models.PROTECT, related_name="eventtypes"
        )
        ordernum = models.FloatField(default=0)
        default_priority = models.PositiveSmallIntegerField(default=PRI_NONE, choices=PRIORITY_CHOICES)
        default_state = models.CharField(default=SC_NEW, choices=STATE_CHOICES, max_length=20)
        icon = models.CharField(max_length=100, blank=True, null=True)
        schema = models.TextField(
            blank=True,
            default="""{
                "schema": {
                    "$schema": "http://json-schema.org/draft-04/schema#",
                    "title": "Empty Event Schema",
                    "type": "object",
                    "properties": {}
                },
                "definition": []
            }""",
        )
        is_collection = models.BooleanField(default=False)
        is_active = models.BooleanField(default=True)
        auto_resolve = models.BooleanField(default=False)
        resolve_time = models.PositiveSmallIntegerField(blank=True, null=True)
        geometry_type = models.CharField(
            choices=GeometryTypesChoices.choices,
            default=GeometryTypesChoices.POINT,
            max_length=20,
        )

        das_tenant = models.ForeignKey(DASTenant, on_delete=models.CASCADE, default=default_tenant_id)
        tenant_id = "das_tenant_id"

        class Meta:
            managed = False
            app_label = "activity"
            db_table = "activity_eventtype"
            base_manager_name = "objects"
            default_manager_name = "objects"
            constraints = [
                models.CheckConstraint(
                    check=Q(auto_resolve=False, resolve_time__isnull=True)
                    | Q(auto_resolve=True, resolve_time__isnull=False),
                    name="auto_resolve_constraint",
                ),
                UniqueConstraint(
                    fields=["das_tenant", "value"],
                    name="%(app_label)s_%(class)s_unique_value_across_tenants",
                ),
            ]
            ordering = ["display"]
            indexes = [
                Index(fields=["das_tenant", "geometry_type"]),
                Index(fields=["das_tenant", "is_active"]),
                Index(fields=["das_tenant", "is_collection"]),
                Index(fields=["das_tenant", "value"], name="%(app_label)s_%(class)s_val_idx"),
                Index(fields=["das_tenant", "ordernum"], name="%(class)s_ordernum_idx"),
            ]

        def save(self, *args, **kwargs):
            if not self.ordernum:
                ranked_tool = RankedTool(instance=self, before_key=None)
                new_order_value = ranked_tool.get_first_value_to_insert()
                self.ordernum = new_order_value
            super().save(*args, **kwargs)

    return Migration0182EventCategory, Migration0182EventType, DASTenant


def set_default_ordernum_value_ranked(migration_apps, schema_editor):

    EventCategory, EventType, DASTenant = get_migration_models()

    db_alias = schema_editor.connection.alias

    for tenant in DASTenant.objects.all():
        with TenantContextManager(domain=tenant.domain):
            for category in EventCategory.objects.filter(das_tenant_id=tenant.id, eventtypes__isnull=False):
                qs = (
                    EventType.objects.using(db_alias)
                    .filter(das_tenant_id=tenant.id, category_id=category.id)
                    .order_by("ordernum", "value")
                )
                RankedTool.make_full_rebalance(queryset=qs)


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0024_recreate_useragreement_eula_fk"),
        ("activity", "0181_event_type_change_ordernum_type"),
    ]

    operations = [
        migrations.RunPython(code=set_default_ordernum_value_ranked, reverse_code=migrations.RunPython.noop),
    ]
