# Generated by Django 3.2.21 on 2024-06-12 19:55

from django.apps import apps
from django.db import migrations

from utils.rank import RankedTool
from utils.tenant.managers import TenantContextManager


def set_default_ordernum_value_ranked(migration_apps, schema_editor):
    EventCategory = apps.get_model("activity", "EventCategory")
    EventType = apps.get_model("activity", "EventType")
    DASTenant = apps.get_model("core", "DASTenant")

    for tenant in DASTenant.objects.all():
        with TenantContextManager(domain=tenant.domain):
            for category in EventCategory.objects.filter(das_tenant_id=tenant.id, eventtype__isnull=False):
                qs = EventType.objects.filter(das_tenant_id=tenant.id, category_id=category.id).order_by(
                    "ordernum", "value"
                )
                RankedTool.make_full_rebalance(queryset=qs)


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0024_recreate_useragreement_eula_fk"),
        ("activity", "0181_event_type_change_ordernum_type"),
    ]

    operations = [
        migrations.RunPython(code=set_default_ordernum_value_ranked, reverse_code=migrations.RunPython.noop),
    ]
