# Generated by Django 3.2.21 on 2024-08-29 15:19

from django.db import migrations

# The code for this migration was moved to activity.migrations.0184
# because it had already been applied and required some modifications.


class Migration(migrations.Migration):

    dependencies = [
        ("activity", "0182_event_type_ranking_all_ordernums"),
    ]

    operations = []
