# Generated by Django 3.2.21 on 2024-08-29 15:19

from django.db import migrations
from django.db.models import Count

from activity.models import Event, EventDetails
from core.models.core import DASTenant
from utils.tenant.managers import TenantContextManager, UnsetDASTenantContextManager


def add_empty_event_details_to_events_with_no_details(*args, **kwargs):
    with UnsetDASTenantContextManager():
        das_tenants = DASTenant.objects.all()

    for tenant in das_tenants:
        with TenantContextManager(tenant.domain):
            events_without_details = Event.objects.annotate(count_details=Count("event_details")).filter(
                count_details=0
            )
            for event in events_without_details:
                EventDetails.objects.create(event=event, data={}, update_parent_event=False)


class Migration(migrations.Migration):

    dependencies = [
        ("activity", "0182_event_type_ranking_all_ordernums"),
    ]

    operations = [
        migrations.RunPython(
            code=add_empty_event_details_to_events_with_no_details,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
