# Generated by Django 3.2.21 on 2024-09-06 19:49

import logging

from django.apps import apps
from django.db import migrations
from django.db.models import Count

from activity.models import Event, EventDetails
from core.models.core import DASTenant
from utils.tenant import TenantNotFoundException
from utils.tenant.managers import TenantContextManager, UnsetDASTenantContextManager

logger = logging.getLogger(__name__)


def add_empty_event_details_to_events_with_no_details(*args, **kwargs):
    apps.get_model("activity", "EventDetailsRevision")
    EventDetailsRevision = apps.get_model("activity", "EventDetailsRevision")

    with UnsetDASTenantContextManager():
        das_tenants = DASTenant.objects.all()

    for tenant in das_tenants:
        try:
            with TenantContextManager(tenant.domain):
                events_without_details = Event.objects.annotate(count_details=Count("event_details")).filter(
                    count_details=0
                )
                for event in events_without_details:
                    event_detail = EventDetails.objects.create(
                        event=event,
                        created_at=event.created_at,
                        updated_at=event.updated_at,
                        data={},
                        update_parent_event=False,
                    )
                    event_revision = event.revision.last()
                    if event_revision:
                        event_details_revision = EventDetailsRevision.objects.filter(object_id=event_detail.id).first()
                        if event_details_revision:
                            event_details_revision.user_id = event_revision.id
                            event_details_revision.save(update_fields=["user_id"])

        except TenantNotFoundException:
            logger.warning(
                "Tenant with domain %s found in current cluster domain list does not exist in TMS", tenant.domain
            )


class Migration(migrations.Migration):

    dependencies = [
        ("activity", "0183_add_empty_details_to_events_with_no_details"),
    ]

    operations = [
        migrations.RunPython(
            code=add_empty_event_details_to_events_with_no_details,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
