# Generated by Django 3.2.21 on 2024-12-03 20:13

from django.db import migrations

DELETE_DUPLICATED_EVENT_TSVECTORS = """
WITH duplicates AS (
    SELECT
        ctid,
        das_tenant_id,
        event_id,
        tsvector_event,
        tsvector_event_note,
        ROW_NUMBER() OVER (
            PARTITION BY
                das_tenant_id,
                event_id,
                COALESCE(tsvector_event, ''::tsvector),
                COALESCE(tsvector_event_note, ''::tsvector)
            ORDER BY
                id
        ) AS rn
    FROM
        activity_tsvectormodel
)
DELETE FROM activity_tsvectormodel
WHERE ctid IN (
    SELECT ctid FROM duplicates WHERE rn > 1
);
"""


class Migration(migrations.Migration):

    dependencies = [
        ("activity", "0184_add_empty_details_to_events_with_no_details_and_update_ed_revision"),
    ]

    operations = [
        migrations.RunSQL(
            sql=DELETE_DUPLICATED_EVENT_TSVECTORS,
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
