# Generated by Django 3.2.21 on 2024-12-03 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activity", "0185_remove_duplicated_event_tsvectors"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="tsvectormodel",
            constraint=models.UniqueConstraint(fields=("das_tenant", "event"), name="activity_tsvectormodel_unique"),
        ),
    ]
