# Generated by Django 3.2.21 on 2024-12-03 20:21

from django.db import migrations, models

DELETE_DUPLICATED_EVENT_TSVECTORS = """
WITH duplicates AS (
    SELECT
        ctid,
        das_tenant_id,
        event_id,
        tsvector_event,
        tsvector_event_note,
        ROW_NUMBER() OVER (
            PARTITION BY
                das_tenant_id,
                event_id
            ORDER BY
                ctid desc
        ) AS rn
    FROM
        activity_tsvectormodel
)
DELETE FROM activity_tsvectormodel
WHERE ctid IN (
    SELECT ctid FROM duplicates WHERE rn > 1
);
"""


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ("activity", "0185_remove_duplicated_event_tsvectors"),
    ]

    operations = [
        migrations.RunSQL(sql=DELETE_DUPLICATED_EVENT_TSVECTORS, reverse_sql=migrations.RunSQL.noop),
        migrations.AddConstraint(
            model_name="tsvectormodel",
            constraint=models.UniqueConstraint(fields=("das_tenant", "event"), name="activity_tsvectormodel_unique"),
        ),
    ]
