# Generated by Django 3.2.21 on 2024-12-03 20:21
from django.db import migrations, models
from django.db.models import Count

from activity.models import TSVectorModel
from core.models import DASTenant
from utils.tenant.managers import TenantContextManager


def delete_duplicates_tsvectormodel_records(apps, schema_editor):
    for tenant in DASTenant.objects.all():
        with TenantContextManager(tenant.domain):
            duplicate_event_ids = (
                TSVectorModel.objects.values("event_id").annotate(count=Count("event_id")).filter(count__gt=1)
            )
            for duplicate_event in duplicate_event_ids:
                queryset = TSVectorModel.objects.filter(event_id=duplicate_event["event_id"])
                to_exclude = queryset.last()
                queryset.exclude(id=to_exclude.id).delete()
                # Force update in Event to update TSVector record
                to_exclude.event.title = f"{to_exclude.event.title}" + ""
                to_exclude.event.save(update_fields=["title"])


class Migration(migrations.Migration):

    dependencies = [
        ("activity", "0185_remove_duplicated_event_tsvectors"),
    ]

    operations = [
        migrations.RunPython(code=delete_duplicates_tsvectormodel_records, reverse_code=migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="tsvectormodel",
            constraint=models.UniqueConstraint(fields=("das_tenant", "event"), name="activity_tsvectormodel_unique"),
        ),
    ]
