# Generated by Django 3.2.21 on 2024-12-14 22:13

import django.db.models.deletion
from django.db import migrations, models

import utils.migrations.columns


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0028_remove_prefixex_tenant_hash_from_export_data_permissions"),
        ("activity", "0186_add_event_tsvectormodel_unique_constraint"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alertrule",
            name="event_types",
            field=models.ManyToManyField(
                related_name="alert_rules",
                related_query_name="alert_rule",
                through="activity.AlertRuleEventType",
                to="activity.EventType",
            ),
        ),
        migrations.AlterField(
            model_name="alertrule",
            name="notification_methods",
            field=models.ManyToManyField(
                related_name="alert_rules",
                related_query_name="alert_rule",
                through="activity.AlertRuleNotificationMethod",
                to="activity.NotificationMethod",
            ),
        ),
        migrations.AlterField(
            model_name="alertruleeventtype",
            name="das_tenant",
            field=models.ForeignKey(
                default=utils.migrations.columns.default_tenant_id,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activity_alertruleeventtype",
                to="core.dastenant",
            ),
        ),
        migrations.AlterField(
            model_name="alertrulenotificationmethod",
            name="das_tenant",
            field=models.ForeignKey(
                default=utils.migrations.columns.default_tenant_id,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activity_alertrulenotificationmethod",
                to="core.dastenant",
            ),
        ),
    ]
