# Generated by Django 3.2.21 on 2025-02-10 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activity", "0187_alertrule_alter_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventtype",
            name="version",
            field=models.CharField(choices=[("1", "Version 1"), ("2", "Version 2")], default="1", max_length=1),
        ),
        migrations.AddIndex(
            model_name="eventtype",
            index=models.Index(fields=["das_tenant", "version"], name="activity_ev_das_ten_361658_idx"),
        ),
    ]
