# Generated by Django 3.2.25 on 2025-03-20 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activity", "0188_event_type_add_version_field"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="eventtype",
            options={"base_manager_name": "objects", "default_manager_name": "objects"},
        ),
        migrations.AddField(
            model_name="eventtype",
            name="readonly",
            field=models.BooleanField(default=False),
        ),
    ]
