# Generated by Django 3.2.25 on 2025-06-12 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("activity", "0189_readonly_eventtypes"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="alertrule",
            options={
                "base_manager_name": "objects",
                "default_manager_name": "objects",
                "verbose_name": "Alert Rule",
                "verbose_name_plural": "Alert Rules",
            },
        ),
        migrations.AlterModelOptions(
            name="event",
            options={
                "base_manager_name": "objects",
                "default_manager_name": "objects",
                "permissions": (),
                "verbose_name": "Event",
                "verbose_name_plural": "Events",
            },
        ),
        migrations.AlterModelOptions(
            name="eventattachment",
            options={
                "base_manager_name": "objects",
                "default_manager_name": "objects",
                "verbose_name": "Event Attachment",
                "verbose_name_plural": "Event Attachments",
            },
        ),
        migrations.AlterModelOptions(
            name="eventfile",
            options={
                "base_manager_name": "objects",
                "default_manager_name": "objects",
                "ordering": ["ordernum", "-updated_at"],
                "verbose_name": "Event File",
                "verbose_name_plural": "Event Files",
            },
        ),
        migrations.AlterModelOptions(
            name="eventnote",
            options={
                "base_manager_name": "objects",
                "default_manager_name": "objects",
                "verbose_name": "Event Note",
                "verbose_name_plural": "Event Notes",
            },
        ),
        migrations.AlterModelOptions(
            name="eventnotification",
            options={
                "base_manager_name": "objects",
                "default_manager_name": "objects",
                "verbose_name": "Event Notification",
                "verbose_name_plural": "Event Notifications",
            },
        ),
        migrations.AlterModelOptions(
            name="eventprovider",
            options={
                "base_manager_name": "objects",
                "default_manager_name": "objects",
                "verbose_name": "Event Provider",
                "verbose_name_plural": "Event Providers",
            },
        ),
        migrations.AlterModelOptions(
            name="eventsource",
            options={
                "base_manager_name": "objects",
                "default_manager_name": "objects",
                "permissions": (("create_event_for_eventsource", "Permission to add an event for an event source"),),
                "verbose_name": "Event Source",
                "verbose_name_plural": "Event Sources",
            },
        ),
        migrations.AlterModelOptions(
            name="eventtype",
            options={
                "base_manager_name": "objects",
                "default_manager_name": "objects",
                "verbose_name": "Event Type",
                "verbose_name_plural": "Event Types",
            },
        ),
        migrations.AlterModelOptions(
            name="notificationmethod",
            options={
                "base_manager_name": "objects",
                "default_manager_name": "objects",
                "verbose_name": "Notification Method",
                "verbose_name_plural": "Notification Methods",
            },
        ),
        migrations.AlterModelOptions(
            name="patroltype",
            options={
                "base_manager_name": "objects",
                "default_manager_name": "objects",
                "verbose_name": "Patrol Type",
                "verbose_name_plural": "Patrol Types",
            },
        ),
        migrations.AlterModelOptions(
            name="person",
            options={"verbose_name": "Person", "verbose_name_plural": "People"},
        ),
    ]
