# Generated by Django 3.2.25 on 2025-06-13 15:31

import uuid

import django_multitenant.mixins

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import revision.manager
import utils.migrations.columns


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0029_efb_new_oauth_app"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("activity", "0190_auto_20250612_1613"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventTypeRevision",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ("object_id", models.UUIDField()),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("added", "Added"),
                            ("updated", "Updated"),
                            ("deleted", "Deleted"),
                            ("rel-del", "Relation Deleted"),
                        ],
                        default="added",
                        max_length=10,
                    ),
                ),
                ("revision_at", models.DateTimeField(auto_now_add=True)),
                ("sequence", models.IntegerField(help_text="Revision sequence")),
                ("data", models.JSONField(default=dict)),
                (
                    "das_tenant",
                    models.ForeignKey(
                        default=utils.migrations.columns.default_tenant_id,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity_eventtyperevision",
                        to="core.dastenant",
                    ),
                ),
                (
                    "user",
                    revision.manager.UserField(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="_eventtype_revision",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "default_permissions": (),
                "unique_together": {("das_tenant", "object_id", "sequence")},
            },
            bases=(django_multitenant.mixins.TenantModelMixin, models.Model),
        ),
    ]
