# Generated by Django 3.2.25 on 2025-06-13 22:43

from django.db import migrations

from utils.migrations.update_primary_key import add_tenant_to_primary_key

APP_NAME = "activity"

activity_models = [
    "EventTypeRevision",
]


def regenerate_primary_keys(apps, schema_editor):
    add_tenant_to_primary_key(APP_NAME, activity_models)


class Migration(migrations.Migration):

    dependencies = [
        ("activity", "0191_eventtyperevision"),
    ]

    operations = [
        migrations.RunPython(code=regenerate_primary_keys, reverse_code=migrations.RunPython.noop),
    ]
