# Generated by Django 3.2.25 on 2025-07-15 23:24

import django.core.validators
from django.db import migrations, models

import activity.models


class Migration(migrations.Migration):

    dependencies = [
        ("activity", "0192_eventtyperevisionpk"),
    ]

    operations = [
        migrations.CreateModel(
            name="FormBuilderProxy",
            fields=[],
            options={
                "verbose_name": "Event Types and Category 2.0",
                "verbose_name_plural": "Event Types and Category 2.0",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("activity.eventtype",),
            managers=[
                ("objects", activity.models.EventTypeManager()),
            ],
        ),
        migrations.AlterField(
            model_name="eventtype",
            name="value",
            field=models.CharField(
                max_length=255,
                validators=[
                    django.core.validators.RegexValidator(
                        message="An invalid character was detected in the Event type Value field. Supported characters are: Letters a-z (lowercase), Numbers 0-9 and Underscore",
                        regex="^[A-Za-z0-9-_]*$",
                    )
                ],
            ),
        ),
    ]
