# Generated by Django 3.2.25 on 2025-09-04 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("activity", "0193_et20"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="eventrelationship",
            options={
                "base_manager_name": "objects",
                "default_manager_name": "objects",
                "ordering": ["type", "ordernum"],
                "permissions": [("delete_event_relationship", "Can delete event relationships")],
            },
        ),
    ]
