# Generated by Django 3.2.25 on 2025-09-08 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("activity", "0194_alter_eventrelationship_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="eventrelatedsegments",
            options={
                "base_manager_name": "objects",
                "default_manager_name": "objects",
                "permissions": [("delete_event_related_segments", "Can delete events from patrol segments")],
            },
        ),
    ]
