# Generated by Django 3.2.25 on 2026-02-10 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activity", "0195_alter_eventrelatedsegments_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="alertrule",
            name="override_message",
            field=models.TextField(
                blank=True,
                help_text="If set, this message will be sent instead of the default alert message.",
                null=True,
            ),
        ),
    ]
