# Generated by Django 3.2.25 on 2026-04-02 03:50

import django_multitenant.fields

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import utils.migrations.columns


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("core", "0030_token"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("activity", "0198_fix_v2_link_fields"),
    ]

    operations = [
        # Add composite indexes for common tenant-scoped queries
        migrations.AddIndex(
            model_name="event",
            index=models.Index(fields=["das_tenant", "sort_at"], name="evt_tenant_sort_at_idx"),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(fields=["das_tenant", "event_type"], name="evt_tenant_event_type_idx"),
        ),
        migrations.AddIndex(
            model_name="eventrelationship",
            index=models.Index(fields=["das_tenant", "from_event"], name="evtrel_tenant_from_evt_idx"),
        ),
        migrations.AddIndex(
            model_name="eventrelationship",
            index=models.Index(fields=["das_tenant", "to_event"], name="evtrel_tenant_to_evt_idx"),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(fields=["das_tenant", "state"], name="evt_tenant_state_idx"),
        ),
        # Drop redundant single-column indexes now covered by composite indexes above
        migrations.AlterField(
            model_name="event",
            name="event_type",
            field=django_multitenant.fields.TenantForeignKey(
                blank=True,
                db_index=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="activity.eventtype",
            ),
        ),
        migrations.AlterField(
            model_name="eventrelationship",
            name="from_event",
            field=django_multitenant.fields.TenantForeignKey(
                db_index=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="out_relationships",
                related_query_name="out_relationship",
                to="activity.event",
            ),
        ),
        migrations.AlterField(
            model_name="eventrelationship",
            name="to_event",
            field=django_multitenant.fields.TenantForeignKey(
                db_index=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="in_relationships",
                related_query_name="in_relationship",
                to="activity.event",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="created_by_user",
            field=django_multitenant.fields.TenantForeignKey(
                blank=True,
                db_index=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="events",
                related_query_name="event",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="das_tenant",
            field=models.ForeignKey(
                db_index=False,
                default=utils.migrations.columns.default_tenant_id,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.dastenant",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="reported_by_content_type",
            field=models.ForeignKey(
                blank=True,
                db_index=False,
                limit_choices_to=models.Q(
                    models.Q(("app_label", "observations"), ("model", "subject")),
                    models.Q(("app_label", "observations"), ("model", "source")),
                    models.Q(("app_label", "activity"), ("model", "community")),
                    models.Q(("app_label", "accounts"), ("model", "user")),
                    _connector="OR",
                ),
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="state",
            field=models.CharField(
                choices=[("new", "New"), ("active", "Active"), ("resolved", "Resolved")],
                default="new",
                max_length=40,
            ),
        ),
        # Drop function-based index on bigint_to_char(serial_number) — useless without tenant scoping
        migrations.RunSQL(
            sql="DROP INDEX IF EXISTS activity_event_bigint_to_char_idx;",
            reverse_sql=(
                "CREATE INDEX IF NOT EXISTS activity_event_bigint_to_char_idx "
                "ON activity_event (bigint_to_char(serial_number));"
            ),
        ),
    ]
