# Generated by Django 3.2.25 on 2026-03-29 16:41

import uuid

import django_multitenant.fields
import django_multitenant.mixins

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import utils.migrations.columns
import utils.models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0030_token"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("activity", "0200_django_42"),
    ]

    operations = [
        migrations.CreateModel(
            name="CommunityInput",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                (
                    "value",
                    models.CharField(
                        max_length=255,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Value must contain only alphanumeric characters or underscores.",
                                regex="^[A-Za-z0-9_]+$",
                            )
                        ],
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "das_tenant",
                    models.ForeignKey(
                        default=utils.migrations.columns.default_tenant_id,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.dastenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Community Input",
                "verbose_name_plural": "Community Inputs",
                "base_manager_name": "objects",
                "default_manager_name": "objects",
            },
            bases=(django_multitenant.mixins.TenantModelMixin, models.Model),
            managers=[
                ("objects", utils.models.CommonTenantManager()),
            ],
        ),
        migrations.AlterField(
            model_name="event",
            name="state",
            field=models.CharField(
                choices=[("new", "New"), ("active", "Active"), ("resolved", "Resolved"), ("review", "Review")],
                db_index=True,
                default="new",
                max_length=40,
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="title",
            field=models.TextField(blank=True, null=True, verbose_name="Event Title"),
        ),
        migrations.AlterField(
            model_name="eventnote",
            name="created_by_user",
            field=django_multitenant.fields.TenantForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="eventtype",
            name="default_state",
            field=models.CharField(
                choices=[("new", "New"), ("active", "Active"), ("resolved", "Resolved"), ("review", "Review")],
                default="new",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="CommunityInputEventType",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "community_input",
                    django_multitenant.fields.TenantForeignKey(
                        db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to="activity.communityinput"
                    ),
                ),
                (
                    "das_tenant",
                    models.ForeignKey(
                        default=utils.migrations.columns.default_tenant_id,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity_communityinputeventtype",
                        to="core.dastenant",
                    ),
                ),
                (
                    "event_type",
                    django_multitenant.fields.TenantForeignKey(
                        db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to="activity.eventtype"
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
                "abstract": False,
                "base_manager_name": "objects",
                "default_manager_name": "objects",
            },
            bases=(django_multitenant.mixins.TenantModelMixin, models.Model),
            managers=[
                ("objects", utils.models.CommonTenantManager()),
            ],
        ),
        migrations.CreateModel(
            name="CommunityInputEvent",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "community_input",
                    django_multitenant.fields.TenantForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="submitted_events",
                        to="activity.communityinput",
                    ),
                ),
                (
                    "das_tenant",
                    models.ForeignKey(
                        default=utils.migrations.columns.default_tenant_id,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity_communityinputevent",
                        to="core.dastenant",
                    ),
                ),
                (
                    "event",
                    django_multitenant.fields.TenantForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="community_input_submission",
                        to="activity.event",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
                "default_manager_name": "objects",
            },
            bases=(django_multitenant.mixins.TenantModelMixin, models.Model),
            managers=[
                ("objects", utils.models.CommonTenantManager()),
            ],
        ),
        migrations.AddField(
            model_name="communityinput",
            name="event_types",
            field=models.ManyToManyField(
                blank=True,
                related_name="community_inputs",
                through="activity.CommunityInputEventType",
                to="activity.EventType",
            ),
        ),
        migrations.AddConstraint(
            model_name="communityinput",
            constraint=models.UniqueConstraint(
                fields=("value", "das_tenant"), name="unique_community_input_value_per_tenant"
            ),
        ),
        migrations.AddConstraint(
            model_name="communityinputeventtype",
            constraint=models.UniqueConstraint(
                fields=("community_input", "event_type", "das_tenant"),
                name="unique_community_input_event_type_per_tenant",
            ),
        ),
        migrations.AddConstraint(
            model_name="communityinputevent",
            constraint=models.UniqueConstraint(
                fields=("event", "das_tenant"),
                name="unique_community_input_event_per_tenant",
            ),
        ),
    ]
