# Generated by Django 4.2.30 on 2026-07-27 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("activity", "0203_repair_v2_collection_schemas"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="eventdetails",
            options={
                "base_manager_name": "objects",
                "default_manager_name": "objects",
                "verbose_name": "Event Details",
                "verbose_name_plural": "Event Details",
            },
        ),
    ]
