# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-15 23:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations

from core.utils import DASTenantManagement
from reports.distribution import create_report_permissionset


def forward(apps, schema_editor):
    das_tenant_management = DASTenantManagement(domain=settings.SERVER_FQDN)
    tenant = das_tenant_management.get_or_create_tenant()
    create_report_permissionset(tenant=tenant)


def reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        # Must run after PermissionSet has das_tenant (used in create_report_permissionset)
        ("accounts", "0037_alter_permissionset_das_tenant"),
    ]

    operations = [
        migrations.RunPython(forward, reverse),
    ]
