# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-15 23:06
from __future__ import unicode_literals

from django.db import migrations, models
from reports.distribution import create_report_permissionset


def forward(apps, schema_editor):
    create_report_permissionset()


def reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_reported_by_permission_set'),
    ]

    operations = [
        migrations.RunPython(forward, reverse),
    ]
