# Generated by Django 2.0.2 on 2019-01-23 22:57

from django.db import migrations
from reports.distribution import create_lag_notify_permissionset

def forward(apps, schema_editor):
    create_lag_notify_permissionset()


def reverse(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_reports_permissions_data'),
    ]

    operations = [
        migrations.RunPython(forward, reverse),
    ]
