# Generated by Django 2.0.2 on 2019-01-23 22:57

from django.conf import settings
from django.db import migrations

from core.utils import DASTenantManagement
from reports.distribution import create_lag_notify_permissionset


def forward(apps, schema_editor):
    das_tenant_management = DASTenantManagement(domain=settings.SERVER_FQDN)
    tenant = das_tenant_management.get_or_create_tenant()
    create_lag_notify_permissionset(tenant=tenant)


def reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0001_reports_permissions_data"),
    ]

    operations = [
        migrations.RunPython(forward, reverse),
    ]
