# Generated by Django 2.0.2 on 2019-02-22 19:14

from django.db import migrations
from reports.distribution import create_silent_source_notify_permissionset

def forward(apps, schema_editor):
    create_silent_source_notify_permissionset()

def reverse(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_observations_lag_permissions'),
    ]

    operations = [
        migrations.RunPython(forward, reverse),
    ]
