# Generated by Django 2.2.14 on 2021-10-28 23:45
from django.db import migrations


def forwards(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0003_silent_source_permissions"),
    ]

    operations = [
        # migrations.RunPython(forwards, reverse_code=migrations.RunPython.noop)
    ]
