# Generated by Django 3.2.19 on 2023-08-30 18:54
import uuid
from functools import partial

from django.db import migrations, models

from utils.migrations import populate_model_uuid_column

APP_NAME = "reports"
MODEL_NAME = "SourceProviderEvent"
UUID_COLUMN = "uuid"
ID_COLUMN = "id"

populate_uuid = partial(populate_model_uuid_column, APP_NAME, MODEL_NAME, UUID_COLUMN)


class Migration(migrations.Migration):
    dependencies = [
        ("activity", "0146_change_pk_type_patrolconfiguration"),
        ("observations", "0142_add_crocodiles_and_vehicles"),
        (APP_NAME, "0006_change_sourceevent_pk_type_to_uuid"),
    ]

    operations = [
        migrations.AddField(
            model_name=MODEL_NAME.lower(),
            name=UUID_COLUMN,
            field=models.UUIDField(null=True),
        ),
        migrations.RunPython(populate_uuid),
        migrations.RemoveField(
            model_name=MODEL_NAME.lower(),
            name=ID_COLUMN,
        ),
        migrations.RenameField(
            model_name=MODEL_NAME.lower(),
            old_name=UUID_COLUMN,
            new_name=ID_COLUMN,
        ),
        migrations.AlterField(
            model_name=MODEL_NAME.lower(),
            name=ID_COLUMN,
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=True),
        ),
    ]
