# Generated by Django 3.2.19 on 2023-09-14 22:14

import django_multitenant.fields

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("activity", "0150_populate_tenant_foreign_key_in_activity"),
        ("core", "0008_migrate_oauth_tables_to_das_custom_models"),
        ("observations", "0144_populate_das_tenant_in_subject_model"),
        ("reports", "0007_change_sourceproviderevent_pk_type_to_uuid"),
    ]

    operations = [
        migrations.AddField(
            model_name="sourceevent",
            name="das_tenant",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="core.dastenant"
            ),
        ),
        migrations.AddField(
            model_name="sourceproviderevent",
            name="das_tenant",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="core.dastenant"
            ),
        ),
        migrations.AlterField(
            model_name="sourceevent",
            name="event",
            field=django_multitenant.fields.TenantForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sources_event",
                related_query_name="source_event",
                to="activity.event",
            ),
        ),
        migrations.AlterField(
            model_name="sourceevent",
            name="source",
            field=django_multitenant.fields.TenantForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="events_reached_threshold",
                related_query_name="event_reached_threshold",
                to="observations.source",
            ),
        ),
        migrations.AlterField(
            model_name="sourceproviderevent",
            name="event",
            field=django_multitenant.fields.TenantForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sources_provider_event",
                related_query_name="source_provider_event",
                to="activity.event",
            ),
        ),
        migrations.AlterField(
            model_name="sourceproviderevent",
            name="source_provider",
            field=django_multitenant.fields.TenantForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="events_reached_threshold",
                related_query_name="event_reached_threshold",
                to="observations.sourceprovider",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="sourceevent",
            unique_together={("id", "das_tenant")},
        ),
        migrations.AlterUniqueTogether(
            name="sourceproviderevent",
            unique_together={("id", "das_tenant")},
        ),
    ]
