# Generated by Django 3.2.19 on 2023-09-14 22:15
import logging

from django.apps import apps
from django.conf import settings
from django.db import migrations

from core.utils import DASTenantManagement, update_tenant_models

logger = logging.getLogger(__name__)


def update_tenant_models_on_reports_models(unused, schema_editor) -> None:
    SourceEvent = apps.get_model("reports", "SourceEvent")
    SourceProviderEvent = apps.get_model("reports", "SourceProviderEvent")

    das_tenant_management = DASTenantManagement(domain=settings.SERVER_FQDN)
    tenant = das_tenant_management.get_or_create_tenant()
    class_models = [SourceEvent, SourceProviderEvent]

    if not tenant:
        logger.error("DAS Tenant not found.")
        return
    update_tenant_models(models=class_models, tenant=tenant)


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0008_add_tenant_id_tenant_foreign_key"),
    ]

    operations = [
        migrations.RunPython(
            code=update_tenant_models_on_reports_models,
            reverse_code=migrations.RunPython.noop,
        )
    ]
