# Generated by Django 3.2.19 on 2023-09-25 18:24
import uuid

from django_multitenant.fields import TenantForeignKey
from django_multitenant.mixins import TenantModelMixin

from django.conf import settings
from django.db import migrations, models
from django.db.models import Q

from core.utils import DASTenantManagement
from utils.tenant.managers import set_tenant

SILENCE_SOURCE_SCHEMA = """{
    "schema": {
        "$schema": "http://json-schema.org/draft-04/schema#",
        "title": "Entry Alert",
        "type": "object",
        "readonly": true,
        "properties": {
            "report_time": {
                "type": "number",
                "title": "Heading at entry (deg)"
            },
            "location": {
                "type": "number",
                "title": "Speed at entry (knots)"
            },
            "device_id": {
                "type": "string",
                "title": "Device ID"
            },
            "name_assigned_subject": {
                "type": "string",
                "title": "Name of assigned subject"
            },
            "source_provider": {
                "type": "string",
                "title": "Source Provider"
            },
            "silence_threshold": {
                "type": "string",
                "title": "Silence Threshold"
            },
            "latest_position_recorded_at": {
                "type": "string",
                "title": "Latest position recorded at"
            }
        }
    },
    "definition": [
        "report_time",
        "location",
        "device_id",
        "name_assigned_subject",
        "source_provider",
        "silence_threshold",
        "latest_position_recorded_at"
    ]
}
"""

SILENCE_SOURCE_PROVIDER_SCHEMA = """
{
    "schema": {
        "$schema": "http://json-schema.org/draft-04/schema#",
        "title": "Entry Alert",
        "type": "object",
        "readonly": true,
        "properties": {
            "report_time": {
                "type": "string",
                "title": "Report Time"
            },
            "silence_threshold": {
                "type": "string",
                "title": "Silence threshold(hh:mm)"
            },
            "last_device_reported_at": {
                "type": "string",
                "title": "Last device reported at"
            }
        }
    },
    "definition": [
        "report_time",
        "silence_threshold",
        "last_device_reported_at"
    ]
}
"""


# pylint: disable=import-outside-toplevel, invalid-name
def get_migration_models():
    """
    A place to return the historical versions of the models used in this migration.
    This isolates the model definitions from changes in the live code.

    Notes:
    - Give an alias to the model classes to avoid conflicts with the live models.
    - In the meta class, the following attributes are important:
        - `managed = False`: This is to prevent Django from modifying the table for this model.
        - `app_label = "activity"`: This is to ensure that the model is in the correct app.
        - `db_table = "activity_eventtype"`: This is to ensure that the model is mapped to the correct table.
    """

    from activity.models import EventCategory
    from core.models import DASTenant, TimestampedModel

    PRI_URGENT = 300
    PRI_IMPORTANT = 200
    PRI_REFERENCE = 100
    PRI_NONE = 0
    PRIORITY_CHOICES = (
        (PRI_NONE, "Gray"),
        (PRI_REFERENCE, "Green"),
        (PRI_IMPORTANT, "Amber"),
        (PRI_URGENT, "Red"),
    )

    SC_NEW = "new"
    SC_ACTIVE = "active"
    SC_RESOLVED = "resolved"
    STATE_CHOICES = (
        (SC_NEW, "New"),
        (SC_ACTIVE, "Active"),
        (SC_RESOLVED, "Resolved"),
    )

    class Migration0010EventType(TenantModelMixin, TimestampedModel):
        """
        Frozen version of EventType model as it existed at the time of this migration.
        """

        class GeometryTypesChoices(models.TextChoices):
            POINT = "Point"
            POLYGON = "Polygon"

        id = models.UUIDField(primary_key=True, default=uuid.uuid4)
        value = models.CharField(max_length=40, unique=True)
        display = models.CharField(max_length=100, blank=True)
        category = TenantForeignKey(EventCategory, null=True, on_delete=models.PROTECT)
        ordernum = models.SmallIntegerField(blank=True, null=True)

        default_priority = models.PositiveSmallIntegerField(default=PRI_NONE, choices=PRIORITY_CHOICES)

        default_state = models.CharField(default=SC_NEW, choices=STATE_CHOICES, max_length=20)

        icon = models.CharField(max_length=100, blank=True, null=True)

        schema = models.TextField(
            blank=True,
            default="""{
                    "schema":
                    {
                        "$schema": "http://json-schema.org/draft-04/schema#",
                        "title": "Empty Event Schema",
                        "type": "object",
                        "properties": {}
                    },
                    "definition": []
                    }""",
        )

        is_collection = models.BooleanField(default=False)
        is_active = models.BooleanField(default=True)
        auto_resolve = models.BooleanField(default=False)
        # Specify integer of hour(s).
        resolve_time = models.PositiveSmallIntegerField(blank=True, null=True)
        geometry_type = models.CharField(
            choices=GeometryTypesChoices.choices, default=GeometryTypesChoices.POINT, max_length=20
        )

        das_tenant = models.ForeignKey(DASTenant, on_delete=models.CASCADE, blank=True, null=True)
        tenant_id = "das_tenant_id"

        class Meta:
            managed = False
            app_label = "activity"
            db_table = "activity_eventtype"
            constraints = [
                models.CheckConstraint(
                    check=Q(auto_resolve=False, resolve_time__isnull=True)
                    | Q(auto_resolve=True, resolve_time__isnull=False),
                    name="auto_resolve_constraint",
                )
            ]
            unique_together = ["id", "das_tenant"]

    return EventCategory, Migration0010EventType


def forwards(apps, schema_editor):
    EventCategory, EventType = get_migration_models()

    db_alias = schema_editor.connection.alias

    das_tenant_management = DASTenantManagement(domain=settings.SERVER_FQDN)
    tenant = das_tenant_management.get_or_create_tenant()
    set_tenant(tenant.domain)

    event_category, _ = EventCategory.objects.using(db_alias).get_or_create(
        value="analyzer_event", defaults={"display": "Analyzer Event", "ordernum": 1}
    )

    events_type = [
        {
            "display": "Silent Source",
            "value": "silence_source_rep",
            "category_id": event_category.id,
            "default_priority": 200,
            "is_collection": False,
            "schema": SILENCE_SOURCE_SCHEMA,
            "das_tenant_id": tenant.id,
        },
        {
            "display": "Silent Source Provider",
            "value": "silence_source_provider_rep",
            "category_id": event_category.id,
            "default_priority": 200,
            "is_collection": False,
            "schema": SILENCE_SOURCE_PROVIDER_SCHEMA,
            "das_tenant_id": tenant.id,
        },
    ]

    for event_type in events_type:
        EventType.objects.using(db_alias).update_or_create(defaults=event_type, value=event_type.get("value"))


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0009_populate_tenant_foreign_key"),
    ]

    operations = [
        migrations.RunPython(
            forwards,
            migrations.RunPython.noop,
        )
    ]
