# Generated by Django 3.2.19 on 2023-09-25 21:04

from django.db import migrations
from utils.migrations.update_primary_key import AppsHandler, QueryManager

reports_models = ["SourceProviderEvent", "SourceEvent"]


def regenerate_primary_keys(apps, schema_editor):
    query_manager = QueryManager()
    apps_handler = AppsHandler(query_manager=query_manager)
    apps_handler.handle("reports", reports_models)


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0010_create_silence_source_event_types"),
    ]

    operations = [migrations.RunPython(code=regenerate_primary_keys, reverse_code=migrations.RunPython.noop)]
