# Generated by Django 3.2.19 on 2023-10-13 18:51

import django.db.models.deletion
from django.db import migrations, models

import utils.migrations.columns


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0011_regenerate_primary_keys"),
        ("reports", "0011_regenerate_default_primary_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sourceevent",
            name="das_tenant",
            field=models.ForeignKey(
                default=utils.migrations.columns.default_tenant_id,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.dastenant",
            ),
        ),
        migrations.AlterField(
            model_name="sourceproviderevent",
            name="das_tenant",
            field=models.ForeignKey(
                default=utils.migrations.columns.default_tenant_id,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.dastenant",
            ),
        ),
    ]
