# Generated by Django 3.2.21 on 2023-11-20 17:05

from django.db import migrations

import utils.models


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0012_make_das_tenant_field_required"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="sourceevent",
            managers=[
                ("objects", utils.models.CommonTenantManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="sourceproviderevent",
            managers=[
                ("objects", utils.models.CommonTenantManager()),
            ],
        ),
    ]
