# Generated by Django 3.2.21 on 2023-11-24 15:40

from django.db import migrations

from utils.migrations.update_primary_key import drop_constraint

APP_NAME = "reports"


def drop_constraints(apps, schema_editor):
    drop_constraint(
        app=APP_NAME,
        model="SourceProviderEvent",
        constraint="reports_sourceproviderevent_id_f9587c45_uniq",
    )
    drop_constraint(
        app=APP_NAME,
        model="SourceEvent",
        constraint="reports_sourceevent_id_07c3904d_uniq",
    )


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0013_add_common_tenant_manager"),
    ]

    operations = [
        migrations.RunPython(code=drop_constraints, reverse_code=migrations.RunPython.noop),
    ]
