# Generated by Django 3.2.21 on 2024-10-18 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0014_delete_unique_constraints"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sourceevent",
            options={"base_manager_name": "objects", "default_manager_name": "objects"},
        ),
        migrations.AlterModelOptions(
            name="sourceproviderevent",
            options={"base_manager_name": "objects", "default_manager_name": "objects"},
        ),
    ]
