# Generated by Django 4.2.28 on 2026-02-16 15:01

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0015_sourceevent_base_manager"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sourceevent",
            name="id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="sourceproviderevent",
            name="id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
