# -*- coding: utf-8 -*-
# Generated by Django 1.9b1 on 2015-11-03 21:13
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Map',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80, unique=True)),
                ('attributes', django.contrib.postgres.fields.jsonb.JSONField()),
                ('center', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('zoom', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TileLayer',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80, unique=True)),
                ('attributes', django.contrib.postgres.fields.jsonb.JSONField()),
                ('version', models.CharField(default='1.0.0', max_length=80)),
                ('tile_type', models.CharField(choices=[('raster', 'Local Raster'), ('mbtiles', 'Local MBTiles'), ('external', 'External Tile Server')], default='raster', max_length=20)),
                ('maps', models.ManyToManyField(to='mapping.Map')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
