# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-05 16:50
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0003_featuresets'),
    ]

    operations = [
        migrations.AddField(
            model_name='linefeature',
            name='external_id',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='linefeature',
            name='fields',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
        migrations.AddField(
            model_name='pointfeature',
            name='external_id',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='pointfeature',
            name='fields',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
        migrations.AddField(
            model_name='polygonfeature',
            name='external_id',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='polygonfeature',
            name='fields',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
    ]
