# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-11 08:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0005_common_name'),
        ('mapping', '0004_initial_features'),
    ]

    operations = [
    ]
