# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-12 20:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0006_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linefeature',
            name='name',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='pointfeature',
            name='name',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='polygonfeature',
            name='name',
            field=models.CharField(max_length=80),
        ),
    ]
