# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-15 08:01
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0007_feature_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='featuretype',
            name='presentation',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
    ]
