# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-03-27 22:45
from __future__ import unicode_literals

import uuid

import django.contrib.gis.db.models.fields
import django.db.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mapping", "0009_raster"),
    ]

    operations = [
        migrations.CreateModel(
            name="GeoFeature",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=80)),
                ("description", models.TextField(blank=True, null=True)),
                ("short_name", models.CharField(max_length=20)),
                ("categorization", django.db.models.JSONField(default={})),
                ("attributes", django.db.models.JSONField(default={})),
                ("presentation", django.db.models.JSONField(default={})),
                ("fields", django.db.models.JSONField(default={})),
                ("external_id", models.CharField(blank=True, max_length=80, null=True)),
                ("feature_geometry", django.contrib.gis.db.models.fields.GeometryField(geography=True, srid=4326)),
                (
                    "featureset",
                    models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to="mapping.FeatureSet"),
                ),
                ("type", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="mapping.FeatureType")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="linefeature",
            name="attributes",
            field=django.db.models.JSONField(default={}),
        ),
        migrations.AddField(
            model_name="linefeature",
            name="categorization",
            field=django.db.models.JSONField(default={}),
        ),
        migrations.AddField(
            model_name="linefeature",
            name="short_name",
            field=models.CharField(default="default", max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="pointfeature",
            name="attributes",
            field=django.db.models.JSONField(default={}),
        ),
        migrations.AddField(
            model_name="pointfeature",
            name="categorization",
            field=django.db.models.JSONField(default={}),
        ),
        migrations.AddField(
            model_name="pointfeature",
            name="short_name",
            field=models.CharField(default="default", max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="polygonfeature",
            name="attributes",
            field=django.db.models.JSONField(default={}),
        ),
        migrations.AddField(
            model_name="polygonfeature",
            name="categorization",
            field=django.db.models.JSONField(default={}),
        ),
        migrations.AddField(
            model_name="polygonfeature",
            name="short_name",
            field=models.CharField(default="default", max_length=20),
            preserve_default=False,
        ),
    ]
