# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-06-17 15:45
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import tagulous.models.fields
import tagulous.models.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0010_annotations'),
    ]

    operations = [
        migrations.CreateModel(
            name='_Tagulous_SpatialFeature_tags',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField()),
                ('count', models.IntegerField(
                    default=0, help_text='Internal counter of how many times this tag is in use')),
                ('protected', models.BooleanField(default=False,
                                                  help_text='Will not be deleted when the count reaches 0')),
            ],
            options={
                'ordering': ('name',),
                'abstract': False,
            },
            bases=(tagulous.models.models.BaseTagModel, models.Model),
        ),
        migrations.CreateModel(
            name='_Tagulous_SpatialFeatureType_tags',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField()),
                ('count', models.IntegerField(
                    default=0, help_text='Internal counter of how many times this tag is in use')),
                ('protected', models.BooleanField(default=False,
                                                  help_text='Will not be deleted when the count reaches 0')),
            ],
            options={
                'ordering': ('name',),
                'abstract': False,
            },
            bases=(tagulous.models.models.BaseTagModel, models.Model),
        ),
        migrations.CreateModel(
            name='DisplayClass',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4,
                                        primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SpatialFeatureGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4,
                                        primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SpatialFeatureType',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('attribute_schema',
                 django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('presentation', django.contrib.postgres.fields.jsonb.JSONField(
                    default=dict)),
                ('display_class', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='mapping.DisplayClass')),
                ('tags', tagulous.models.fields.TagField(_set_tag_meta=True,
                                                         help_text='Enter a comma-separated tag string', to='mapping._Tagulous_SpatialFeatureType_tags')),
            ],
        ),
        migrations.RemoveField(
            model_name='geofeature',
            name='featureset',
        ),
        migrations.RemoveField(
            model_name='geofeature',
            name='type',
        ),
        migrations.RemoveField(
            model_name='linefeature',
            name='attributes',
        ),
        migrations.RemoveField(
            model_name='linefeature',
            name='categorization',
        ),
        migrations.RemoveField(
            model_name='linefeature',
            name='short_name',
        ),
        migrations.RemoveField(
            model_name='pointfeature',
            name='attributes',
        ),
        migrations.RemoveField(
            model_name='pointfeature',
            name='categorization',
        ),
        migrations.RemoveField(
            model_name='pointfeature',
            name='short_name',
        ),
        migrations.RemoveField(
            model_name='polygonfeature',
            name='attributes',
        ),
        migrations.RemoveField(
            model_name='polygonfeature',
            name='categorization',
        ),
        migrations.RemoveField(
            model_name='polygonfeature',
            name='short_name',
        ),
        migrations.AlterField(
            model_name='featuretype',
            name='presentation',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='linefeature',
            name='fields',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='linefeature',
            name='presentation',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='pointfeature',
            name='fields',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='pointfeature',
            name='presentation',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='polygonfeature',
            name='fields',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='polygonfeature',
            name='presentation',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.DeleteModel(
            name='GeoFeature',
        ),
        migrations.AlterUniqueTogether(
            name='_tagulous_spatialfeaturetype_tags',
            unique_together=set([('slug',)]),
        ),
        migrations.AlterUniqueTogether(
            name='_tagulous_spatialfeature_tags',
            unique_together=set([('slug',)]),
        ),
    ]
