# Generated by Django 2.0.2 on 2018-06-22 21:22

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0013_post-django2-upgrade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spatialfeaturerevision',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
