# Generated by Django 2.0.2 on 2018-07-12 10:30

from django.db import migrations, models
import django.db.models.deletion
import mapping.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0014_jsonfield_default'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpatialFile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=25)),
                ('description', models.CharField(blank=True, max_length=100)),
                ('data', models.FileField(blank=True, storage=mapping.models.TempStorage(), upload_to='')),
                ('layer_number', models.IntegerField(blank=True, default=0, null=True)),
                ('name_field', models.CharField(blank=True, max_length=100)),
                ('id_field', models.CharField(blank=True, max_length=100)),
                ('feature_set', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mapping.FeatureSet')),
                ('feature_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mapping.FeatureType')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
