# Generated by Django 2.0.2 on 2018-08-13 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0015_spatialfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spatialfeaturegroupstatic',
            name='features',
            field=models.ManyToManyField(
                blank=True, related_name='groups', related_query_name='group', to='mapping.SpatialFeature'),
        ),
    ]
