# Generated by Django 2.0.6 on 2018-09-13 00:37

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0016_split_geofence_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featuretype',
            name='presentation',
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='linefeature',
            name='fields',
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='linefeature',
            name='presentation',
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='map',
            name='attributes',
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='pointfeature',
            name='fields',
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='pointfeature',
            name='presentation',
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='polygonfeature',
            name='fields',
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='polygonfeature',
            name='presentation',
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='spatialfeature',
            name='attributes',
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='spatialfeature',
            name='provenance',
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='spatialfeaturetype',
            name='attribute_schema',
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='spatialfeaturetype',
            name='presentation',
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='spatialfeaturetype',
            name='provenance',
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='tilelayer',
            name='attributes',
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True, default=dict),
        ),
    ]
