# Generated by Django 2.0.13 on 2019-07-19 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0018_tile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='displaycategory',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='featureset',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='featuretype',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='linefeature',
            name='external_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='linefeature',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='map',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='pointfeature',
            name='external_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pointfeature',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='polygonfeature',
            name='external_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='polygonfeature',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='spatialfeature',
            name='external_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='spatialfeature',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='spatialfeaturegroup',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='spatialfeaturetype',
            name='external_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='spatialfeaturetype',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='spatialfile',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='tilelayer',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
