# Generated by Django 2.0.13 on 2019-12-13 23:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0019_bump_name_length'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='displaycategory',
            options={'verbose_name': 'Display Category', 'verbose_name_plural': 'Display Categories'},
        ),
        migrations.AlterModelOptions(
            name='spatialfeature',
            options={'verbose_name': 'Feature'},
        ),
        migrations.AlterModelOptions(
            name='spatialfeaturegroup',
            options={'verbose_name': 'Base Feature Group'},
        ),
        migrations.AlterModelOptions(
            name='spatialfeaturegroupquery',
            options={'verbose_name': 'Calculated Feature Group'},
        ),
        migrations.AlterModelOptions(
            name='spatialfeaturegroupstatic',
            options={'verbose_name': 'Feature Group'},
        ),
        migrations.AlterModelOptions(
            name='spatialfeaturetype',
            options={'verbose_name': 'Feature Class', 'verbose_name_plural': 'Feature Classes'},
        ),
        migrations.AlterModelOptions(
            name='tilelayer',
            options={'verbose_name': 'Map Layer'},
        ),
        migrations.AddField(
            model_name='displaycategory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='displaycategory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='spatialfeaturegroup',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='spatialfeaturegroup',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='spatialfeaturetype',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='spatialfeaturetype',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
