# Generated by Django 2.0.13 on 2019-12-16 15:03

from django.db import migrations, models
import django.db.models.deletion
import mapping.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0020_mapping_feature_v2_models_extend_timestampedmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpatialFeatureFile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('description', models.CharField(blank=True, max_length=100)),
                ('data', models.FileField(blank=True, storage=mapping.models.TempStorage(), upload_to='')),
                ('feature_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='mapping.SpatialFeatureType')),
            ],
            options={
                'verbose_name': 'Spatial Feature File',
            },
        ),
        migrations.RenameModel(
            old_name='SpatialFile',
            new_name='SpatialLayerFile',
        ),
        migrations.AlterModelOptions(
            name='spatiallayerfile',
            options={'verbose_name': 'Spatial Layer File'},
        ),
    ]
