# Generated by Django 2.0.13 on 2019-12-22 19:48

from django.db import migrations, models
import mapping.models


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0021_create_spatialfeaturefile_and_spatiallayerfile_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='spatialfeaturefile',
            name='feature_types_file',
            field=models.FileField(blank=True, null=True, storage=mapping.models.TempStorage(), upload_to=''),
        ),
    ]
