# Generated by Django 2.0.13 on 2020-01-17 00:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import mapping.models
import tagulous.models.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0021_auto_20191212_0428'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='displaycategory',
            options={'verbose_name': 'Display Category', 'verbose_name_plural': 'Display Categories'},
        ),
        migrations.AlterModelOptions(
            name='spatialfeature',
            options={'verbose_name': 'Feature'},
        ),
        migrations.AlterModelOptions(
            name='spatialfeaturegroup',
            options={'verbose_name': 'Base Feature Group'},
        ),
        migrations.AlterModelOptions(
            name='spatialfeaturegroupquery',
            options={'verbose_name': 'Calculated Feature Group'},
        ),
        migrations.AlterModelOptions(
            name='spatialfeaturegroupstatic',
            options={'verbose_name': 'Feature Group'},
        ),
        migrations.AlterModelOptions(
            name='spatialfeaturetype',
            options={'verbose_name': 'Feature Class', 'verbose_name_plural': 'Feature Classes'},
        ),
        migrations.AlterModelOptions(
            name='tilelayer',
            options={'verbose_name': 'Basemap'},
        ),
        migrations.AddField(
            model_name='displaycategory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='displaycategory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='spatialfeaturegroup',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='spatialfeaturegroup',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='spatialfeaturetype',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='spatialfeaturetype',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='displaycategory',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='spatialfeature',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='SpatialFeatureFile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='SpatialFile Name')),
                ('description', models.CharField(blank=True, max_length=100)),
                ('data', models.FileField(storage=mapping.models.TempStorage(), upload_to='')),
                ('layer_number', models.IntegerField(blank=True, default=0, null=True)),
                ('name_field', models.CharField(blank=True, max_length=100, null=True)),
                ('id_field', models.CharField(blank=True, max_length=100, null=True)),
                ('feature_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='mapping.SpatialFeatureType')),
                ('feature_types_file', models.FileField(blank=True, null=True, storage=mapping.models.TempStorage(), upload_to='')),
                ('file_type', models.CharField(choices=[('shapefile', 'Shapefile'), ('geojson', 'GeoJSON')], default='shapefile', max_length=100)),
            ],
            options={
                'verbose_name': 'Feature Import File',
            },
        ),
        migrations.AddField(
            model_name='spatialfeature',
            name='spatialfile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mapping.SpatialFeatureFile'),
        ),
        migrations.AlterModelOptions(
            name='spatialfeaturetype',
            options={},
        ),
        migrations.AlterModelOptions(
            name='spatialfile',
            options={'verbose_name': 'Spatial File'},
        ),
        migrations.AlterField(
            model_name='spatialfeaturetype',
            name='tags',
            field=tagulous.models.fields.TagField(_set_tag_meta=True, help_text='Enter a comma-separated tag string', to='mapping.SpatialFeatureTypeTag'),
        ),
        migrations.AlterField(
            model_name='spatialfile',
            name='data',
            field=models.FileField(storage=mapping.models.TempStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='spatialfile',
            name='id_field',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='spatialfile',
            name='name_field',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterModelOptions(
            name='spatialfeaturetype',
            options={'verbose_name': 'Feature Class', 'verbose_name_plural': 'Feature Classes'},
        ),
        migrations.AlterField(
            model_name='spatialfeaturetype',
            name='display_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='mapping.DisplayCategory'),
        ),
        migrations.AlterField(
            model_name='spatialfeaturetype',
            name='tags',
            field=tagulous.models.fields.TagField(_set_tag_meta=True, blank=True, help_text='Enter a comma-separated tag string', to='mapping.SpatialFeatureTypeTag'),
        ),
        migrations.AddField(
            model_name='spatialfeaturetype',
            name='is_visible',
            field=models.BooleanField(default=True, verbose_name='visible'),
        ),
        migrations.AlterField(
            model_name='spatialfile',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='SpatialFile Name'),
        ),
        migrations.AlterModelOptions(
            name='map',
            options={'verbose_name': 'Map Quicklink'},
        ),
        migrations.AlterField(
            model_name='spatialfeature',
            name='external_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
