# Generated by Django 2.0.13 on 2020-01-17 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0022_mapping_features_v2'),
    ]

    operations = [
    ]
