# Generated by Django 2.0.13 on 2020-01-16 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0022_mapping_features_v2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spatialfeaturefile',
            name='file_type',
            field=models.CharField(choices=[('shapefile', 'Shapefile'), ('geodatabase', 'Geodatabase'), ('geojson', 'GeoJSON')], default='shapefile', max_length=100),
        ),
    ]
