# Generated by Django 2.0.13 on 2020-02-12 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0022_mapping_features_v2'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArcgisConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service_url', models.CharField(blank=True, max_length=100, null=True)),
                ('group_name', models.CharField(max_length=100, unique=True)),
                ('group_id', models.CharField(max_length=100, unique=True)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('polling_interval', models.PositiveIntegerField(default=0)),
                ('name_field', models.CharField(blank=True, max_length=100, null=True)),
                ('id_field', models.CharField(blank=True, max_length=100, null=True)),
                ('source', models.CharField(blank=True, default='ArcGis', max_length=100, null=True)),
                ('type_label', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Feature Service Configuration',
            },
        ),
    ]
