# Generated by Django 2.0.13 on 2020-01-31 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0022_mapping_features_v2'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArcgisConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group_name', models.CharField(max_length=100, unique=True)),
                ('group_id', models.CharField(max_length=100, unique=True)),
                ('owner', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
