# Generated by Django 2.0.13 on 2019-12-18 13:02

from django.db import migrations, models
import django.db.models.deletion
import mapping.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0022_mapping_feature_v2'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpatialFeatureFile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('description', models.CharField(blank=True, max_length=100)),
                ('data', models.FileField(storage=mapping.models.TempStorage(), upload_to='')),
                ('layer_number', models.IntegerField(blank=True, default=0, null=True)),
                ('name_field', models.CharField(blank=True, max_length=100, null=True)),
                ('id_field', models.CharField(blank=True, max_length=100, null=True)),
                ('feature_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='mapping.SpatialFeatureType')),
            ],
            options={
                'verbose_name': 'Spatial Feature File',
            },
        ),
        migrations.CreateModel(
            name='SpatialLayerFile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('description', models.CharField(blank=True, max_length=100)),
                ('data', models.FileField(storage=mapping.models.TempStorage(), upload_to='')),
                ('layer_number', models.IntegerField(blank=True, default=0, null=True)),
                ('name_field', models.CharField(blank=True, max_length=100, null=True)),
                ('id_field', models.CharField(blank=True, max_length=100, null=True)),
                ('feature_set', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mapping.FeatureSet')),
                ('feature_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mapping.FeatureType')),
            ],
            options={
                'verbose_name': 'Spatial Layer File',
            },
        ),
        migrations.RemoveField(
            model_name='spatialfile',
            name='feature_set',
        ),
        migrations.RemoveField(
            model_name='spatialfile',
            name='feature_type',
        ),
        migrations.DeleteModel(
            name='SpatialFile',
        ),
    ]
