# Generated by Django 2.0.13 on 2019-12-22 19:48

from django.db import migrations, models
import django.db.models.deletion
import mapping.models


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0023_create_spatialfeaturefile_and_spatiallayerfile_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='spatialfeaturefile',
            name='feature_types_file',
            field=models.FileField(blank=True, null=True, storage=mapping.models.TempStorage(), upload_to=''),
        ),
        migrations.AddField(
            model_name='spatialfeature',
            name='spatialfile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to='mapping.SpatialFeatureFile'),
        ),
    ]
