# Generated by Django 2.0.13 on 2020-02-15 00:16

import django.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mapping", "0023_maps"),
    ]

    operations = [
        migrations.AddField(
            model_name="spatialfeature",
            name="presentation",
            field=django.db.models.JSONField(blank=True, default=dict),
        ),
    ]
