# Generated by Django 2.0.13 on 2020-01-05 20:40

from django.db import migrations, models
import django.db.models.deletion
import mapping.models
import tagulous.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0024_add_spatial_features_types_to_spatial_feature_files_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spatiallayerfile',
            name='feature_set',
        ),
        migrations.RemoveField(
            model_name='spatiallayerfile',
            name='feature_type',
        ),
        migrations.AlterModelOptions(
            name='spatialfeature',
            options={},
        ),
        migrations.AlterModelOptions(
            name='spatialfeaturegroup',
            options={},
        ),
        migrations.AlterModelOptions(
            name='spatialfeaturegroupstatic',
            options={},
        ),
        migrations.AlterModelOptions(
            name='spatialfeaturetype',
            options={},
        ),
        migrations.AlterModelOptions(
            name='spatialfile',
            options={'verbose_name': 'Spatial File'},
        ),
        migrations.AlterModelOptions(
            name='tilelayer',
            options={},
        ),
        migrations.AlterField(
            model_name='linefeature',
            name='spatialfile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mapping.SpatialFile'),
        ),
        migrations.AlterField(
            model_name='pointfeature',
            name='spatialfile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mapping.SpatialFile'),
        ),
        migrations.AlterField(
            model_name='polygonfeature',
            name='spatialfile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mapping.SpatialFile'),
        ),
        migrations.AlterField(
            model_name='spatialfeaturetype',
            name='tags',
            field=tagulous.models.fields.TagField(_set_tag_meta=True, help_text='Enter a comma-separated tag string', to='mapping.SpatialFeatureTypeTag'),
        ),
        migrations.AlterField(
            model_name='spatialfile',
            name='data',
            field=models.FileField(storage=mapping.models.TempStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='spatialfile',
            name='id_field',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='spatialfile',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='spatialfile',
            name='name_field',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='SpatialLayerFile',
        ),
    ]
