# Generated by Django 2.2.9 on 2020-02-19 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0024_spatialfeature_presentation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArcgisGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('group_id', models.CharField(max_length=100)),
                ('config_id', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ArcgisConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service_url', models.CharField(blank=True, help_text='Leave blank to connect to ArcGIS Online, or enter your ArcGIS Enterprise service URL', max_length=100, null=True)),
                ('config_name', models.CharField(max_length=100, unique=True, verbose_name='Configuration name')),
                ('search_text', models.CharField(blank=True, help_text='Leave blank to get groups within your ArcGIS org\nor enter text for groups to search for outside your ArdGIS org', max_length=100, verbose_name='Search text')),
                ('username', models.CharField(help_text='ArcGIS account username', max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('source', models.CharField(blank=True, default='ArcGis', max_length=100, null=True)),
                ('name_field', models.CharField(blank=True, help_text='Name of field in your GIS data that has the feature name. Default is Name', max_length=100, null=True)),
                ('id_field', models.CharField(blank=True, help_text='Name of field in your GIS data that has the feature ID. Default is GlobalID', max_length=100, null=True)),
                ('type_label', models.CharField(blank=True, help_text='Name of field in your GIS data that has the feature type. Defaults are Type and FeatureType', max_length=100, null=True, verbose_name='Type field')),
                ('last_download', models.DateTimeField(blank=True, null=True, verbose_name='Last Download Time')),
                ('groups', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mapping.ArcgisGroup')),
            ],
            options={
                'verbose_name': 'Feature Service Configuration',
            },
        ),
    ]
