# Generated by Django 2.2.9 on 2020-02-28 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0025_arcgisconfiguration_arcgisgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='spatialfeaturefile',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Feature Load Status'),
        ),
        migrations.AddField(
            model_name='spatialfile',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Feature Load Status'),
        ),
        migrations.AlterField(
            model_name='spatialfeaturetype',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
