# Generated by Django 2.0.13 on 2020-01-07 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0025_auto_20200105_1240'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='spatialfeature',
            options={'verbose_name': 'Feature'},
        ),
        migrations.AlterModelOptions(
            name='spatialfeaturegroup',
            options={'verbose_name': 'Base Feature Group'},
        ),
        migrations.AlterModelOptions(
            name='spatialfeaturegroupstatic',
            options={'verbose_name': 'Feature Group'},
        ),
        migrations.AlterModelOptions(
            name='spatialfeaturetype',
            options={'verbose_name': 'Feature Class', 'verbose_name_plural': 'Feature Classes'},
        ),
        migrations.AlterModelOptions(
            name='tilelayer',
            options={'verbose_name': 'Map Layer'},
        ),
        migrations.AddField(
            model_name='spatialfeaturefile',
            name='file_type',
            field=models.CharField(choices=[('shapefile', 'Shapefile'), ('ste', 'Ste')], default='shapefile', max_length=100),
        ),
    ]
