# Generated by Django 2.2.9 on 2020-02-16 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0025_arcgisconfiguration_arcgisgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='arcgisconfiguration',
            name='last_download',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Download Time'),
        ),
    ]
