# Generated by Django 2.2.9 on 2020-03-06 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0026_arcgis_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arcgisconfiguration',
            name='id_field',
            field=models.CharField(blank=True, default='GlobalID', help_text='Name of field in your GIS data that has the feature ID. Default is GlobalID', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='arcgisconfiguration',
            name='name_field',
            field=models.CharField(blank=True, default='Name', help_text='Name of field in your GIS data that has the feature name. Default is Name', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='arcgisconfiguration',
            name='type_label',
            field=models.CharField(blank=True, default='FeatureType', help_text='Name of field in your GIS data that has the feature type. Defaults are Type and FeatureType', max_length=100, null=True, verbose_name='Type field'),
        ),
    ]
