# Generated by Django 2.2.9 on 2020-03-05 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0026_add_feature_download_status_and_spatialfeaturetype_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spatialfeaturefile',
            name='status',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Feature Load Status'),
        ),
        migrations.AlterField(
            model_name='spatialfile',
            name='status',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Feature Load Status'),
        ),
    ]
