# Generated by Django 2.2.9 on 2020-03-18 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0026_arcgisitem_etc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spatialfeaturefile',
            name='data',
            field=models.FileField(upload_to='mapping/spatialfiles'),
        ),
        migrations.AlterField(
            model_name='spatialfeaturefile',
            name='feature_types_file',
            field=models.FileField(blank=True, null=True, upload_to='mapping/spatialfiles'),
        ),
        migrations.AlterField(
            model_name='spatialfeaturefile',
            name='id_field',
            field=models.CharField(blank=True, default='globalid', max_length=100),
        ),
        migrations.AlterField(
            model_name='spatialfeaturefile',
            name='name_field',
            field=models.CharField(blank=True, default='Name', max_length=100),
        ),
        migrations.AlterField(
            model_name='spatialfile',
            name='data',
            field=models.FileField(upload_to='mapping/spatialfiles'),
        ),
        migrations.AlterField(
            model_name='spatialfile',
            name='id_field',
            field=models.CharField(blank=True, default='globalid', max_length=100),
        ),
        migrations.AlterField(
            model_name='spatialfile',
            name='name_field',
            field=models.CharField(blank=True, default='Name', max_length=100),
        ),
    ]
