# Generated by Django 2.2.9 on 2020-03-13 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0027_increase_status_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='spatialfeaturefile',
            name='data_filename',
            field=models.TextField(default='data_file', verbose_name='Data file'),
        ),
        migrations.AddField(
            model_name='spatialfeaturefile',
            name='feature_types_filename',
            field=models.TextField(blank=True, null=True, verbose_name='Featuretypes file'),
        ),
        migrations.AddField(
            model_name='spatialfile',
            name='data_filename',
            field=models.TextField(default='data_file', verbose_name='Data file'),
        ),
        migrations.AlterField(
            model_name='spatialfeaturefile',
            name='data',
            field=models.FileField(upload_to='spatialfiles'),
        ),
        migrations.AlterField(
            model_name='spatialfeaturefile',
            name='feature_types_file',
            field=models.FileField(blank=True, null=True, upload_to='spatialfiles'),
        ),
        migrations.AlterField(
            model_name='spatialfile',
            name='data',
            field=models.FileField(upload_to='spatialfiles'),
        ),
    ]
