# Generated by Django 2.2.11 on 2020-05-16 13:50

from django.db import migrations, models
import mapping.models


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0027_spatialfile_storage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='map',
            options={},
        ),
        migrations.AlterModelOptions(
            name='spatialfeature',
            options={},
        ),
        migrations.AlterModelOptions(
            name='spatialfeaturegroup',
            options={},
        ),
        migrations.AlterModelOptions(
            name='spatialfeaturegroupstatic',
            options={},
        ),
        migrations.AlterModelOptions(
            name='spatialfeaturetype',
            options={},
        ),
        migrations.AlterModelOptions(
            name='tilelayer',
            options={},
        ),
        migrations.AlterField(
            model_name='spatialfeaturefile',
            name='data',
            field=models.FileField(upload_to=mapping.models.upload_to),
        ),
        migrations.AlterField(
            model_name='spatialfeaturefile',
            name='feature_types_file',
            field=models.FileField(blank=True, null=True, upload_to=mapping.models.upload_to),
        ),
        migrations.AlterField(
            model_name='spatialfile',
            name='data',
            field=models.FileField(upload_to=mapping.models.upload_to),
        ),
    ]
