# Generated by Django 2.2.9 on 2020-03-13 16:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0027_increase_status_max_length'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='map',
            options={},
        ),
        migrations.AlterModelOptions(
            name='spatialfeature',
            options={},
        ),
        migrations.AlterModelOptions(
            name='spatialfeaturegroup',
            options={},
        ),
        migrations.AlterModelOptions(
            name='spatialfeaturegroupstatic',
            options={},
        ),
        migrations.AlterModelOptions(
            name='spatialfeaturetype',
            options={},
        ),
        migrations.AlterModelOptions(
            name='tilelayer',
            options={},
        ),
        migrations.AddField(
            model_name='spatialfeaturefile',
            name='data_filename',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='Data file'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='spatialfeaturefile',
            name='feature_types_filename',
            field=models.TextField(blank=True, null=True, verbose_name='Featuretypes file'),
        ),
        migrations.AddField(
            model_name='spatialfile',
            name='data_filename',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='Data file'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='spatialfeaturefile',
            name='data',
            field=models.FileField(upload_to='spatialfiles'),
        ),
        migrations.AlterField(
            model_name='spatialfeaturefile',
            name='feature_types_file',
            field=models.FileField(blank=True, null=True, upload_to='spatialfiles'),
        ),
        migrations.AlterField(
            model_name='spatialfile',
            name='data',
            field=models.FileField(upload_to='spatialfiles'),
        ),
    ]
