# Generated by Django 2.2.11 on 2020-07-02 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0028_meta'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='displaycategory',
            options={'ordering': ['name'], 'verbose_name': 'Display Category', 'verbose_name_plural': 'Display Categories'},
        ),
        migrations.AlterModelOptions(
            name='linefeature',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='pointfeature',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='polygonfeature',
            options={'ordering': ['name']},
        ),
    ]
