# Generated by Django 2.2.9 on 2020-03-17 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0028_add_upload_file_names'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='map',
            options={'verbose_name': 'Map Quicklink'},
        ),
        migrations.AlterModelOptions(
            name='spatialfeature',
            options={'verbose_name': 'Feature'},
        ),
        migrations.AlterModelOptions(
            name='spatialfeaturegroup',
            options={'verbose_name': 'Base Feature Group'},
        ),
        migrations.AlterModelOptions(
            name='spatialfeaturegroupstatic',
            options={'verbose_name': 'Feature Group'},
        ),
        migrations.AlterModelOptions(
            name='spatialfeaturetype',
            options={'verbose_name': 'Feature Class', 'verbose_name_plural': 'Feature Classes'},
        ),
        migrations.AlterModelOptions(
            name='tilelayer',
            options={'verbose_name': 'Basemap'},
        ),
        migrations.RemoveField(
            model_name='spatialfeaturefile',
            name='data_filename',
        ),
        migrations.RemoveField(
            model_name='spatialfeaturefile',
            name='feature_types_filename',
        ),
        migrations.RemoveField(
            model_name='spatialfile',
            name='data_filename',
        ),
        migrations.AlterField(
            model_name='spatialfeaturefile',
            name='data',
            field=models.FileField(upload_to='mapping/spatialfiles'),
        ),
        migrations.AlterField(
            model_name='spatialfeaturefile',
            name='feature_types_file',
            field=models.FileField(blank=True, null=True, upload_to='mapping/spatialfiles'),
        ),
        migrations.AlterField(
            model_name='spatialfile',
            name='data',
            field=models.FileField(upload_to='mapping/spatialfiles'),
        ),
    ]
