# Generated by Django 2.2.9 on 2020-08-18 13:53

from django.db import migrations

google_satellite_pk = "d57ea783-dbf6-4e2f-aa35-89d24b9ed30a"
google_satellite_url = "https://mt1.google.com/vt/lyrs=s&x={x}&y={y}&z={z}"


def update_google_sat_url(app_registry, schema_editor):
    tile_layer = app_registry.get_model('mapping', 'TileLayer')
    db_alias = schema_editor.connection.alias
    # Update Google Satellite url
    google_sat_pk = google_satellite_pk
    try:
        google_sat_qs = tile_layer.objects.using(db_alias).get(pk=google_sat_pk)
    except tile_layer.DoesNotExist:
        pass
    else:
        google_sat_qs.attributes['url'] = google_satellite_url
        google_sat_qs.save()


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0029_spatial_meta'),
    ]

    operations = [
        migrations.RunPython(update_google_sat_url, reverse_code=migrations.RunPython.noop)
    ]
