# Generated by Django 2.2.14 on 2020-08-20 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0030_update_google_satellite'),
        ('mapping', '0030_external_source_length'),
    ]

    operations = [
    ]
