# Generated by Django 2.2.14 on 2020-08-18 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0029_spatial_meta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spatialfeature',
            name='external_source',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
