# Generated by Django 2.2.14 on 2020-08-28 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0031_external_source_and_google_sattelite'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='map',
            options={'verbose_name': 'Map Quicklink'},
        ),
        migrations.AlterModelOptions(
            name='spatialfeature',
            options={'ordering': ['name'], 'verbose_name': 'Feature'},
        ),
        migrations.AlterModelOptions(
            name='spatialfeaturegroup',
            options={'ordering': ['name'], 'verbose_name': 'Base Feature Group'},
        ),
        migrations.AlterModelOptions(
            name='spatialfeaturegroupstatic',
            options={'verbose_name': 'Feature Group'},
        ),
        migrations.AlterModelOptions(
            name='spatialfeaturetype',
            options={'ordering': ['name'], 'verbose_name': 'Feature Class', 'verbose_name_plural': 'Feature Classes'},
        ),
        migrations.AlterModelOptions(
            name='tilelayer',
            options={'ordering': ['name'], 'verbose_name': 'Basemap'},
        ),
    ]
