# Generated by Django 2.2.14 on 2020-09-21 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0032_spatial_v2_migration'),
    ]

    operations = [
        migrations.AddField(
            model_name='arcgisconfiguration',
            name='disable_import_feature_classes',
            field=models.BooleanField(default=False),
        ),
    ]
