# Generated by Django 2.2.9 on 2020-09-29 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0033_arcgisconfiguration_disable_import_feature_classes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arcgisconfiguration',
            name='service_url',
            field=models.CharField(blank=True, help_text='Leave blank to connect to ArcGIS Online, or enter your ArcGIS Enterprise service URL', max_length=2000, null=True),
        ),
    ]
