# Generated by Django 2.2.14 on 2020-12-06 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0035_unique_name_spf'),
    ]

    operations = [
        migrations.RenameField(
            model_name='arcgisconfiguration',
            old_name='disable_import_feature_classes',
            new_name='disable_import_feature_class_presentation',
        ),
        migrations.AlterField(
            model_name='arcgisconfiguration',
            name='type_label',
            field=models.CharField(blank=True, default='FeatureType',
                                   help_text='Name of field in your GIS data that has the feature type. Defaults are type and FeatureType',
                                   max_length=100, null=True, verbose_name='Type field'),
        ),
    ]
