# Generated by Django 2.2.14 on 2020-12-06 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0035_unique_name_spf'),
    ]

    operations = [
        migrations.RenameField(
            model_name='arcgisconfiguration',
            old_name='disable_import_feature_classes',
            new_name='disable_import_feature_class_presentation',
        ),
    ]
