# Generated by Django 2.2.9 on 2021-02-19 14:18
import logging
from django.db import migrations

logger = logging.getLogger(__name__)


def forward(apps, schema_editor):
    # update existing spatialfeaturetype presentation's opacity property to type float.
    db_alias = schema_editor.connection.alias
    spf = apps.get_model('mapping', 'SpatialFeatureType')

    for o in spf.objects.using(db_alias).all():

        # Skip a presentation value if it's not a dict as we expect.
        if not isinstance(o.presentation, dict): continue
        
        fill_opacity = o.presentation.get('fill-opacity')
        stroke_opacity = o.presentation.get('stroke-opacity')

        try:
            if fill_opacity:
                o.presentation['fill-opacity'] = float(fill_opacity)
            if stroke_opacity:
                o.presentation['stroke-opacity'] = float(stroke_opacity)
        except ValueError as exc:
            logging.warning(exc)
        finally:
            o.save()


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0036_arcgisconfiguration_display_changes'),
    ]

    operations = [
        migrations.RunPython(code=forward, reverse_code=migrations.RunPython.noop)
    ]
