# Generated by Django 3.1 on 2022-06-22 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0037_update_opacity_to_float'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featuretype',
            name='presentation',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='linefeature',
            name='fields',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='linefeature',
            name='presentation',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='map',
            name='attributes',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='pointfeature',
            name='fields',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='pointfeature',
            name='presentation',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='polygonfeature',
            name='fields',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='polygonfeature',
            name='presentation',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='spatialfeature',
            name='attributes',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='spatialfeature',
            name='presentation',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='spatialfeature',
            name='provenance',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='spatialfeaturerevision',
            name='data',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='spatialfeaturetype',
            name='attribute_schema',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='spatialfeaturetype',
            name='presentation',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='spatialfeaturetype',
            name='provenance',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='tilelayer',
            name='attributes',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
