# Generated by Django 3.2.19 on 2023-08-15 10:50
import uuid
from functools import partial

from django.db import migrations, models

from utils.migrations import copy_uuid_references, populate_model_uuid_column

APP_NAME = "mapping"
ID_COLUMN = "id"
MODEL_NAME = "ArcgisConfiguration"
REFERRER_ID_COLUMN = "arcgis_config"
REFERRER_MODEL_NAME = "ArcgisItem"
REFERRER_UUID_COLUMN = "arcgis_config_uuid"
UUID_COLUMN = "uuid"
RELATIONSHIP_FIELD = "arcgisitem_set"

populate_uuid = partial(populate_model_uuid_column, APP_NAME, MODEL_NAME, UUID_COLUMN)
update_references = partial(
    copy_uuid_references, APP_NAME, MODEL_NAME, RELATIONSHIP_FIELD, UUID_COLUMN, REFERRER_UUID_COLUMN
)


class Migration(migrations.Migration):
    dependencies = [(APP_NAME, "0039_change_arcgisgroup_pk_type_to_uuid")]

    operations = [
        migrations.AddField(
            model_name=MODEL_NAME.lower(),
            name=UUID_COLUMN,
            field=models.UUIDField(null=True),
        ),
        migrations.RunPython(populate_uuid),
        migrations.AddField(
            model_name=REFERRER_MODEL_NAME.lower(),
            name=REFERRER_UUID_COLUMN,
            field=models.UUIDField(null=True),
        ),
        migrations.RunPython(update_references),
        migrations.AlterField(
            model_name=REFERRER_MODEL_NAME.lower(),
            name=REFERRER_ID_COLUMN,
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name=MODEL_NAME.lower(),
            name=ID_COLUMN,
        ),
        migrations.RenameField(
            model_name=MODEL_NAME.lower(),
            old_name=UUID_COLUMN,
            new_name=ID_COLUMN,
        ),
        migrations.AlterField(
            model_name=MODEL_NAME.lower(),
            name=ID_COLUMN,
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.RemoveField(
            model_name=REFERRER_MODEL_NAME.lower(),
            name=REFERRER_ID_COLUMN,
        ),
        migrations.RenameField(
            model_name=REFERRER_MODEL_NAME.lower(),
            old_name=REFERRER_UUID_COLUMN,
            new_name=REFERRER_ID_COLUMN,
        ),
        migrations.AlterField(
            model_name=REFERRER_MODEL_NAME.lower(),
            name=REFERRER_ID_COLUMN,
            field=models.ForeignKey(MODEL_NAME, blank=True, on_delete=models.SET_NULL, null=True),
        ),
    ]
