# Generated by Django 3.2.19 on 2023-09-14 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_migrate_oauth_tables_to_das_custom_models"),
        ("mapping", "0040_change_arcgisconfiguration_pk_type_to_uuid"),
    ]

    operations = [
        migrations.AddField(
            model_name="arcgisgroup",
            name="das_tenant",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="core.dastenant"
            ),
        ),
        migrations.AddField(
            model_name="arcgisitem",
            name="das_tenant",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="core.dastenant"
            ),
        ),
        migrations.AddField(
            model_name="displaycategory",
            name="das_tenant",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="core.dastenant"
            ),
        ),
        migrations.AddField(
            model_name="featureset",
            name="das_tenant",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="core.dastenant"
            ),
        ),
        migrations.AddField(
            model_name="featuretype",
            name="das_tenant",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="core.dastenant"
            ),
        ),
        migrations.AddField(
            model_name="map",
            name="das_tenant",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="core.dastenant"
            ),
        ),
        migrations.AddField(
            model_name="spatialfeaturefile",
            name="das_tenant",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="core.dastenant"
            ),
        ),
        migrations.AddField(
            model_name="spatialfeaturegroup",
            name="das_tenant",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="core.dastenant"
            ),
        ),
        migrations.AddField(
            model_name="spatialfile",
            name="das_tenant",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="core.dastenant"
            ),
        ),
        migrations.AddField(
            model_name="tilelayer",
            name="das_tenant",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="core.dastenant"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="arcgisgroup",
            unique_together={("id", "das_tenant")},
        ),
        migrations.AlterUniqueTogether(
            name="arcgisitem",
            unique_together={("id", "das_tenant")},
        ),
        migrations.AlterUniqueTogether(
            name="displaycategory",
            unique_together={("id", "das_tenant")},
        ),
        migrations.AlterUniqueTogether(
            name="featureset",
            unique_together={("id", "das_tenant")},
        ),
        migrations.AlterUniqueTogether(
            name="featuretype",
            unique_together={("id", "das_tenant")},
        ),
        migrations.AlterUniqueTogether(
            name="map",
            unique_together={("id", "das_tenant")},
        ),
        migrations.AlterUniqueTogether(
            name="spatialfeaturegroup",
            unique_together={("id", "das_tenant")},
        ),
        migrations.AlterUniqueTogether(
            name="tilelayer",
            unique_together={("id", "das_tenant")},
        ),
    ]
