# Generated by Django 3.2.19 on 2023-09-14 18:42
import logging

from django.conf import settings
from django.db import migrations

from core.utils import DASTenantManagement, update_tenant_models

logger = logging.getLogger(__name__)


def populate_das_tenant_in_mapping_models(apps, schema_editor):
    ArcgisGroup = apps.get_model("mapping", "ArcgisGroup")
    ArcgisItem = apps.get_model("mapping", "ArcgisItem")
    DisplayCategory = apps.get_model("mapping", "DisplayCategory")
    FeatureType = apps.get_model("mapping", "FeatureType")
    FeatureSet = apps.get_model("mapping", "FeatureSet")
    Map = apps.get_model("mapping", "Map")
    SpatialFeatureFile = apps.get_model("mapping", "SpatialFeatureFile")
    SpatialFeatureGroup = apps.get_model("mapping", "SpatialFeatureGroup")
    SpatialFile = apps.get_model("mapping", "SpatialFile")
    TileLayer = apps.get_model("mapping", "TileLayer")

    class_models = [
        ArcgisGroup,
        ArcgisItem,
        DisplayCategory,
        FeatureType,
        FeatureSet,
        Map,
        SpatialFeatureFile,
        SpatialFeatureGroup,
        SpatialFile,
        TileLayer,
    ]

    das_tenant_management = DASTenantManagement(domain=settings.SERVER_FQDN)
    tenant = das_tenant_management.get_or_create_tenant()

    if tenant:
        update_tenant_models(models=class_models, tenant=tenant)
    else:
        logger.error("DAS Tenant not found.")


class Migration(migrations.Migration):
    dependencies = [
        ("mapping", "0041_add_tenant_model_mixin_and_tenant_manager_mixin"),
    ]

    operations = [
        migrations.RunPython(code=populate_das_tenant_in_mapping_models, reverse_code=migrations.RunPython.noop)
    ]
