# Generated by Django 3.2.19 on 2023-09-14 19:42

import django_multitenant.fields

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_migrate_oauth_tables_to_das_custom_models"),
        ("mapping", "0042_populate_mapping_das_tenant_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="arcgisconfiguration",
            name="das_tenant",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="core.dastenant"
            ),
        ),
        migrations.AddField(
            model_name="linefeature",
            name="das_tenant",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="core.dastenant"
            ),
        ),
        migrations.AddField(
            model_name="pointfeature",
            name="das_tenant",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="core.dastenant"
            ),
        ),
        migrations.AddField(
            model_name="polygonfeature",
            name="das_tenant",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="core.dastenant"
            ),
        ),
        migrations.AddField(
            model_name="spatialfeature",
            name="das_tenant",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="core.dastenant"
            ),
        ),
        migrations.AddField(
            model_name="spatialfeaturetype",
            name="das_tenant",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="core.dastenant"
            ),
        ),
        migrations.AlterField(
            model_name="arcgisconfiguration",
            name="groups",
            field=django_multitenant.fields.TenantForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="mapping.arcgisgroup"
            ),
        ),
        migrations.AlterField(
            model_name="arcgisitem",
            name="arcgis_config",
            field=django_multitenant.fields.TenantForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="mapping.arcgisconfiguration"
            ),
        ),
        migrations.AlterField(
            model_name="linefeature",
            name="featureset",
            field=django_multitenant.fields.TenantForeignKey(
                null=True, on_delete=django.db.models.deletion.PROTECT, to="mapping.featureset"
            ),
        ),
        migrations.AlterField(
            model_name="linefeature",
            name="spatialfile",
            field=django_multitenant.fields.TenantForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="mapping.spatialfile"
            ),
        ),
        migrations.AlterField(
            model_name="linefeature",
            name="type",
            field=django_multitenant.fields.TenantForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="mapping.featuretype"
            ),
        ),
        migrations.AlterField(
            model_name="pointfeature",
            name="featureset",
            field=django_multitenant.fields.TenantForeignKey(
                null=True, on_delete=django.db.models.deletion.PROTECT, to="mapping.featureset"
            ),
        ),
        migrations.AlterField(
            model_name="pointfeature",
            name="spatialfile",
            field=django_multitenant.fields.TenantForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="mapping.spatialfile"
            ),
        ),
        migrations.AlterField(
            model_name="pointfeature",
            name="type",
            field=django_multitenant.fields.TenantForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="mapping.featuretype"
            ),
        ),
        migrations.AlterField(
            model_name="polygonfeature",
            name="featureset",
            field=django_multitenant.fields.TenantForeignKey(
                null=True, on_delete=django.db.models.deletion.PROTECT, to="mapping.featureset"
            ),
        ),
        migrations.AlterField(
            model_name="polygonfeature",
            name="spatialfile",
            field=django_multitenant.fields.TenantForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="mapping.spatialfile"
            ),
        ),
        migrations.AlterField(
            model_name="polygonfeature",
            name="type",
            field=django_multitenant.fields.TenantForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="mapping.featuretype"
            ),
        ),
        migrations.AlterField(
            model_name="spatialfeature",
            name="arcgis_item",
            field=django_multitenant.fields.TenantForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="mapping.arcgisitem"
            ),
        ),
        migrations.AlterField(
            model_name="spatialfeature",
            name="feature_type",
            field=django_multitenant.fields.TenantForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="mapping.spatialfeaturetype"
            ),
        ),
        migrations.AlterField(
            model_name="spatialfeature",
            name="spatialfile",
            field=django_multitenant.fields.TenantForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="mapping.spatialfeaturefile"
            ),
        ),
        migrations.AlterField(
            model_name="spatialfeaturefile",
            name="feature_type",
            field=django_multitenant.fields.TenantForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="mapping.spatialfeaturetype"
            ),
        ),
        migrations.AlterField(
            model_name="spatialfeaturetype",
            name="display_category",
            field=django_multitenant.fields.TenantForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="mapping.displaycategory"
            ),
        ),
        migrations.AlterField(
            model_name="spatialfile",
            name="feature_set",
            field=django_multitenant.fields.TenantForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="mapping.featureset"
            ),
        ),
        migrations.AlterField(
            model_name="spatialfile",
            name="feature_type",
            field=django_multitenant.fields.TenantForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="mapping.featuretype"
            ),
        ),
    ]
