# Generated by Django 3.2.19 on 2023-09-14 19:43
import logging

from django.apps import apps
from django.conf import settings
from django.db import migrations

from core.utils import DASTenantManagement, update_tenant_models

logger = logging.getLogger(__name__)


def populate_das_tenant_tenant_foreign_key_in_mapping_models(unused, schema_editor):
    ArcgisConfiguration = apps.get_model("mapping", "ArcgisConfiguration")
    LineFeature = apps.get_model("mapping", "LineFeature")
    PolygonFeature = apps.get_model("mapping", "PolygonFeature")
    PointFeature = apps.get_model("mapping", "PointFeature")
    SpatialFeature = apps.get_model("mapping", "SpatialFeature")
    SpatialFeatureType = apps.get_model("mapping", "SpatialFeatureType")

    class_models = [ArcgisConfiguration, LineFeature, PolygonFeature, PointFeature, SpatialFeature, SpatialFeatureType]

    das_tenant_management = DASTenantManagement(domain=settings.SERVER_FQDN)
    tenant = das_tenant_management.get_or_create_tenant()

    if tenant:
        update_tenant_models(models=class_models, tenant=tenant)
    else:
        logger.error("DAS Tenant not found.")


class Migration(migrations.Migration):
    dependencies = [
        ("mapping", "0043_add_tenant_foreign_key"),
    ]

    operations = [
        migrations.RunPython(
            code=populate_das_tenant_tenant_foreign_key_in_mapping_models, reverse_code=migrations.RunPython.noop
        )
    ]
