# Generated by Django 3.2.19 on 2023-09-27 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_populate_oauth_models_with_tenant"),
        ("mapping", "0044_populate_tenant_foreign_key_in_mapping"),
    ]

    operations = [
        migrations.AddField(
            model_name="spatialfeaturerevision",
            name="das_tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mapping_spatialfeaturerevision",
                to="core.dastenant",
            ),
        ),
        migrations.AddConstraint(
            model_name="spatialfeaturerevision",
            constraint=models.UniqueConstraint(
                fields=("das_tenant", "id"), name="mapping_spatialfeaturerevision_tenant_unique"
            ),
        ),
    ]
