# Generated by Django 3.2.19 on 2023-09-27 20:29
import logging

import django.db.models.deletion
from django.apps import apps
from django.conf import settings
from django.db import migrations, models

from core.utils import DASTenantManagement, update_tenant_models
from utils.migrations.update_primary_key import add_tenant_to_primary_key

logger = logging.getLogger(__name__)
mapping_models = [
    "ArcgisConfiguration",
    "LineFeature",
    "PolygonFeature",
    "PointFeature",
    "SpatialFeature",
    "SpatialFeatureType",
]


def regenerate_primary_keys(apps, schema_editor):
    add_tenant_to_primary_key("mapping", mapping_models)


def populate_tenant_into_models(unused, schema_editor):
    models_names = ["SpatialFeatureRevision"]
    class_models = [apps.get_model("mapping", model_name) for model_name in models_names]

    das_tenant_management = DASTenantManagement(domain=settings.SERVER_FQDN)
    tenant = das_tenant_management.get_or_create_tenant()

    if tenant:
        update_tenant_models(models=class_models, tenant=tenant)
    else:
        logger.error("DAS Tenant not found.")


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_populate_oauth_models_with_tenant"),
        ("mapping", "0044_populate_tenant_foreign_key_in_mapping"),
    ]

    operations = [
        migrations.AddField(
            model_name="spatialfeaturerevision",
            name="das_tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mapping_spatialfeaturerevision",
                to="core.dastenant",
            ),
        ),
        migrations.RunPython(code=regenerate_primary_keys, reverse_code=migrations.RunPython.noop),
        migrations.RunPython(
            populate_tenant_into_models,
            migrations.RunPython.noop,
        ),
    ]
