# Generated by Django 3.2.19 on 2023-09-27 21:25
import logging

from django.db import migrations

from utils.migrations.update_primary_key import add_tenant_to_primary_key

logger = logging.getLogger(__name__)


mapping_models = ["SpatialFeatureRevision"]


def regenerate_primary_keys(unused, schema_editor):
    add_tenant_to_primary_key("mapping", mapping_models)


class Migration(migrations.Migration):
    dependencies = [
        ("mapping", "0045_add_das_tenant_to_mapping_revision_models"),
    ]

    operations = [
        migrations.RunPython(code=regenerate_primary_keys, reverse_code=migrations.RunPython.noop),
    ]
