# Generated by Django 3.2.19 on 2023-10-16 15:52

import django.db.models.deletion
from django.db import migrations, models

import utils.migrations.columns


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0011_regenerate_primary_keys"),
        ("mapping", "0047_make_das_tenant_field_required"),
    ]

    operations = [
        migrations.AlterField(
            model_name="spatialfeaturerevision",
            name="das_tenant",
            field=models.ForeignKey(
                default=utils.migrations.columns.default_tenant_id,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mapping_spatialfeaturerevision",
                to="core.dastenant",
            ),
        ),
    ]
