# Generated by Django 3.2.21 on 2023-11-07 22:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mapping", "0048_alter_spatialfeaturerevision_das_tenant"),
    ]

    operations = [
        migrations.AlterField(
            model_name="arcgisconfiguration",
            name="config_name",
            field=models.CharField(max_length=100, verbose_name="Configuration name"),
        ),
        migrations.AlterField(
            model_name="displaycategory",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="featureset",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="featuretype",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="map",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="spatialfeaturegroup",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="spatialfeaturetype",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="tilelayer",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AddIndex(
            model_name="arcgisconfiguration",
            index=models.Index(fields=["das_tenant", "config_name"], name="mapping_arc_das_ten_f695c1_idx"),
        ),
        migrations.AddIndex(
            model_name="displaycategory",
            index=models.Index(fields=["das_tenant", "name"], name="mapping_dis_das_ten_5c3d20_idx"),
        ),
        migrations.AddIndex(
            model_name="featureset",
            index=models.Index(fields=["das_tenant", "name"], name="mapping_fea_das_ten_8766b1_idx"),
        ),
        migrations.AddIndex(
            model_name="featuretype",
            index=models.Index(fields=["das_tenant", "name"], name="mapping_featuretype_name_idx"),
        ),
        migrations.AddIndex(
            model_name="map",
            index=models.Index(fields=["das_tenant", "name"], name="mapping_map_name_idx"),
        ),
        migrations.AddIndex(
            model_name="spatialfeaturegroup",
            index=models.Index(fields=["das_tenant", "name"], name="mapping_spa_das_ten_c09416_idx"),
        ),
        migrations.AddIndex(
            model_name="spatialfeaturetype",
            index=models.Index(fields=["das_tenant", "name"], name="mapping_spa_das_ten_509612_idx"),
        ),
        migrations.AddIndex(
            model_name="tilelayer",
            index=models.Index(fields=["das_tenant", "name"], name="mapping_tilelayer_name_idx"),
        ),
        migrations.AddConstraint(
            model_name="arcgisconfiguration",
            constraint=models.UniqueConstraint(
                fields=("das_tenant", "config_name"), name="mapping_arcgisconfiguration_unique_name_across_tenants"
            ),
        ),
        migrations.AddConstraint(
            model_name="displaycategory",
            constraint=models.UniqueConstraint(
                fields=("das_tenant", "name"), name="mapping_displaycategory_unique_name_across_tenants"
            ),
        ),
        migrations.AddConstraint(
            model_name="featureset",
            constraint=models.UniqueConstraint(
                fields=("das_tenant", "name"), name="mapping_featureset_unique_name_across_tenants"
            ),
        ),
        migrations.AddConstraint(
            model_name="featuretype",
            constraint=models.UniqueConstraint(
                fields=("das_tenant", "name"), name="mapping_featuretype_unique_name_across_tenants"
            ),
        ),
        migrations.AddConstraint(
            model_name="map",
            constraint=models.UniqueConstraint(
                fields=("das_tenant", "name"), name="mapping_map_unique_name_across_tenants"
            ),
        ),
        migrations.AddConstraint(
            model_name="spatialfeaturegroup",
            constraint=models.UniqueConstraint(
                fields=("das_tenant", "name"), name="mapping_spatialfeaturegroup_unique_name_across_tenants"
            ),
        ),
        migrations.AddConstraint(
            model_name="spatialfeaturetype",
            constraint=models.UniqueConstraint(
                fields=("das_tenant", "name"), name="mapping_spatialfeaturetype_unique_name_across_tenants"
            ),
        ),
        migrations.AddConstraint(
            model_name="tilelayer",
            constraint=models.UniqueConstraint(
                fields=("das_tenant", "name"), name="mapping_tilelayer_unique_name_across_tenants"
            ),
        ),
    ]
