# Generated by Django 3.2.21 on 2023-11-16 19:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0013_auto_20231115_1758"),
        ("mapping", "0049_mapping_models_fields_unique_per_tenant"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="spatialfeaturerevision",
            unique_together={("das_tenant", "object_id", "sequence")},
        ),
    ]
