# Generated by Django 3.2.21 on 2023-11-20 17:06

from django.db import migrations

import mapping.models
import utils.models


class Migration(migrations.Migration):
    dependencies = [
        ("mapping", "0050_alter_spatialfeaturerevision_unique_together"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="arcgisconfiguration",
            managers=[
                ("objects", utils.models.CommonTenantManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="arcgisgroup",
            managers=[
                ("objects", mapping.models.ArcgisGroupManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="arcgisitem",
            managers=[
                ("objects", mapping.models.ArcgisItemManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="displaycategory",
            managers=[
                ("objects", mapping.models.DisplayCategoryManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="featureset",
            managers=[
                ("objects", mapping.models.FeatureSetManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="featuretype",
            managers=[
                ("objects", mapping.models.FeatureTypeManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="linefeature",
            managers=[
                ("objects", mapping.models.FeatureManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="map",
            managers=[
                ("objects", mapping.models.MapManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="pointfeature",
            managers=[
                ("objects", mapping.models.FeatureManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="polygonfeature",
            managers=[
                ("objects", mapping.models.FeatureManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="spatialfeature",
            managers=[
                ("objects", mapping.models.SpatialFeatureManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="spatialfeaturefile",
            managers=[
                ("objects", mapping.models.SpatialFileBaseManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="spatialfeaturegroup",
            managers=[
                ("objects", mapping.models.SpatialFeatureGroupManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="spatialfeaturegroupquery",
            managers=[
                ("objects", mapping.models.SpatialFeatureGroupManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="spatialfeaturegroupstatic",
            managers=[
                ("objects", mapping.models.SpatialFeatureGroupManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="spatialfeaturetype",
            managers=[
                ("objects", mapping.models.TagulousCastTaggedSpatialFeatureTypeManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="spatialfile",
            managers=[
                ("objects", mapping.models.SpatialFileBaseManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="tilelayer",
            managers=[
                ("objects", mapping.models.TileLayerManager()),
            ],
        ),
    ]
