# Generated by Django 3.2.21 on 2023-11-22 17:13

import uuid

from django_multitenant.fields import TenantForeignKey

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mapping", "0051_auto_20231120_0906"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="ALTER TABLE mapping_featureset_types RENAME TO mapping_featuresetfeaturetype",
                    reverse_sql="ALTER TABLE mapping_featuresetfeaturetype RENAME TO mapping_featureset_types",
                ),
            ],
            state_operations=[
                migrations.CreateModel(
                    name="FeatureSetFeatureType",
                    fields=[
                        ("id", models.AutoField(serialize=True)),
                        (
                            "featureset",
                            TenantForeignKey(to="mapping.featureset", on_delete=django.db.models.deletion.CASCADE),
                        ),
                        (
                            "featuretype",
                            TenantForeignKey(to="mapping.featuretype", on_delete=django.db.models.deletion.CASCADE),
                        ),
                    ],
                ),
                migrations.AlterField(
                    model_name="featureset",
                    name="types",
                    field=models.ManyToManyField(
                        to="mapping.featuretype",
                        related_name="feature_sets",
                        through="mapping.featuresetfeaturetype",
                        through_fields=("feature_set", "feature_type"),
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="featuresetfeaturetype",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.RemoveField(
            model_name="featuresetfeaturetype",
            name="id",
        ),
        migrations.RenameField(
            model_name="featuresetfeaturetype",
            old_name="uuid",
            new_name="id",
        ),
        migrations.AlterField(
            model_name="featuresetfeaturetype",
            name="id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=True),
        ),
    ]
