# Generated by Django 3.2.21 on 2023-11-22 22:34

import django.db.models.deletion
from django.db import migrations, models

import utils.migrations.columns
import utils.models
from utils.migrations.update_primary_key import add_tenant_to_primary_key

APP_NAME = "mapping"
MAPPING_MODELS = ["FeatureSetFeatureType"]


def regenerate_primary_keys(apps, schema_editor):
    add_tenant_to_primary_key(APP_NAME, MAPPING_MODELS)


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0014_auto_20231119_1706"),
        ("mapping", "0052_custom_through_model_featureset_feature_type"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="featuresetfeaturetype",
            managers=[
                ("objects", utils.models.CommonTenantManager()),
            ],
        ),
        migrations.AddField(
            model_name="featuresetfeaturetype",
            name="das_tenant",
            field=models.ForeignKey(
                default=utils.migrations.columns.default_tenant_id,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.dastenant",
            ),
        ),
        migrations.RunPython(code=regenerate_primary_keys, reverse_code=migrations.RunPython.noop),
    ]
