# Generated by Django 3.2.21 on 2023-11-23 22:46

from django.db import migrations

from utils.migrations.update_primary_key import drop_constraint

APP_NAME = "mapping"


def drop_constraints(apps, schema_editor):
    drop_constraint(app=APP_NAME, model="ArcgisGroup", constraint="mapping_arcgisgroup_id_ff9f5808_uniq", cascade=True)
    drop_constraint(
        app=APP_NAME,
        model="ArcgisItem",
        constraint="mapping_arcgisitem_arcgis_config_id_a4990d36_fk_mapping_a",
        cascade=True,
    )
    drop_constraint(
        app=APP_NAME,
        model="ArcgisConfiguration",
        constraint="mapping_arcgisconfiguration_id_2d76956c_uniq",
        cascade=True,
    )


class Migration(migrations.Migration):
    dependencies = [
        ("mapping", "0053_add_das_tenant_to_featuresetfeaturetype"),
    ]

    operations = [
        migrations.RunPython(code=drop_constraints, reverse_code=migrations.RunPython.noop),
    ]
