# Generated by Django 3.2.21 on 2023-11-24 13:00

from django.db import migrations, models

from utils.migrations.update_primary_key import drop_constraint

APP_NAME = "mapping"


def drop_constraints(apps, schema_editor):
    drop_constraint(
        app=APP_NAME,
        model="SpatialFeatureType",
        constraint="mapping_spatialfeaturetype_external_id_key",
    )


class Migration(migrations.Migration):
    dependencies = [
        ("mapping", "0054_arcgis_drop_constraints"),
    ]

    operations = [
        migrations.RunPython(code=drop_constraints, reverse_code=migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="spatialfeaturetype",
            constraint=models.UniqueConstraint(
                fields=("das_tenant", "external_id"),
                name="mapping_spatialfeaturetype_unique_external_id_across_tenants",
            ),
        ),
    ]
