# Generated by Django 3.2.21 on 2023-11-25 19:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mapping", "0055_spatialfeaturetype_constraints"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="arcgisconfiguration",
            options={
                "base_manager_name": "objects",
                "default_manager_name": "objects",
                "verbose_name": "Feature Service Configuration",
            },
        ),
        migrations.AlterModelOptions(
            name="arcgisgroup",
            options={"base_manager_name": "objects", "default_manager_name": "objects"},
        ),
        migrations.AlterModelOptions(
            name="arcgisitem",
            options={"base_manager_name": "objects", "default_manager_name": "objects"},
        ),
        migrations.AlterModelOptions(
            name="displaycategory",
            options={
                "base_manager_name": "objects",
                "default_manager_name": "objects",
                "ordering": ["name"],
                "verbose_name": "Display Category",
                "verbose_name_plural": "Display Categories",
            },
        ),
        migrations.AlterModelOptions(
            name="featureset",
            options={"base_manager_name": "objects", "default_manager_name": "objects", "ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="featuretype",
            options={"base_manager_name": "objects", "default_manager_name": "objects", "ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="linefeature",
            options={"base_manager_name": "objects", "default_manager_name": "objects", "ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="map",
            options={
                "base_manager_name": "objects",
                "default_manager_name": "objects",
                "verbose_name": "Map Quicklink",
            },
        ),
        migrations.AlterModelOptions(
            name="pointfeature",
            options={"base_manager_name": "objects", "default_manager_name": "objects", "ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="polygonfeature",
            options={"base_manager_name": "objects", "default_manager_name": "objects", "ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="spatialfeature",
            options={
                "base_manager_name": "objects",
                "default_manager_name": "objects",
                "ordering": ["name"],
                "verbose_name": "Feature",
            },
        ),
        migrations.AlterModelOptions(
            name="spatialfeaturegroup",
            options={
                "base_manager_name": "objects",
                "default_manager_name": "objects",
                "ordering": ["name"],
                "verbose_name": "Base Feature Group",
            },
        ),
        migrations.AlterModelOptions(
            name="spatialfeaturetype",
            options={
                "base_manager_name": "objects",
                "default_manager_name": "objects",
                "ordering": ["name"],
                "verbose_name": "Feature Class",
                "verbose_name_plural": "Feature Classes",
            },
        ),
        migrations.AlterModelOptions(
            name="tilelayer",
            options={
                "base_manager_name": "objects",
                "default_manager_name": "objects",
                "ordering": ["name"],
                "verbose_name": "Basemap",
            },
        ),
    ]
