# Generated by Django 3.2.21 on 2023-12-06 18:28
import uuid
from functools import partial

from django.db import migrations, models
from django.db.models import deletion

import mapping.models
from utils.migrations import populate_model_uuid_column

APP_NAME = "mapping"

FROM_FIELD = "spatialfeaturetype"
ID_COLUMN = "id"
MANY_TO_MANY_FIELD = "tags"
MODEL_NAME = "SpatialFeatureTypeTags"
REFERED_MODEL = "SpatialFeatureType"
TO_FIELD = "spatialfeaturetypetag"
UUID_COLUMN = "uuid"

populate_uuid = partial(populate_model_uuid_column, APP_NAME, MODEL_NAME, UUID_COLUMN)


class Migration(migrations.Migration):
    dependencies = [("core", "0015_delete_unique_constraints"), ("mapping", "0056_defaultmanager")]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="ALTER TABLE mapping_spatialfeaturetype_tags RENAME TO mapping_spatialfeaturetypetags",
                    reverse_sql=f"ALTER TABLE mapping_spatialfeaturetypetags RENAME TO mapping_spatialfeaturetype_tags",
                ),
            ],
            state_operations=[
                migrations.CreateModel(
                    name="SpatialFeatureTypeTags",
                    fields=[
                        ("id", models.AutoField(serialize=True)),
                        (
                            "spatialfeaturetype",
                            models.ForeignKey(
                                default=uuid.uuid4,
                                on_delete=deletion.CASCADE,
                                related_name="spatialfeaturetype",
                                to="mapping.spatialfeaturetype",
                            ),
                        ),
                        (
                            "spatialfeaturetypetag",
                            models.ForeignKey(
                                default=uuid.uuid4,
                                on_delete=models.deletion.CASCADE,
                                related_name="spatialfeaturetypetag",
                                to="mapping.spatialfeaturetypetag",
                            ),
                        ),
                    ],
                ),
                migrations.AlterField(
                    model_name="SpatialFeatureType",
                    name="tags",
                    field=mapping.models.TagField(
                        _set_tag_meta=True,
                        blank=True,
                        help_text="Enter a comma-separated tag string",
                        through="mapping.SpatialFeatureTypeTags",
                        to="mapping.SpatialFeatureTypeTag",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="SpatialFeatureTypeTags",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.RunPython(populate_uuid),
        migrations.RemoveField(
            model_name="SpatialFeatureTypeTags",
            name="id",
        ),
        migrations.RenameField(
            model_name="SpatialFeatureTypeTags",
            old_name="uuid",
            new_name="id",
        ),
        migrations.AlterField(
            model_name="SpatialFeatureTypeTags",
            name="id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=True),
        ),
    ]
