# Generated by Django 3.2.21 on 2023-12-07 21:14

import uuid

from django_multitenant.fields import TenantForeignKey

from django.db import migrations, models
from django.db.models import deletion

from utils.migrations.columns import default_tenant_id
from utils.models import CommonTenantManager


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0015_delete_unique_constraints"),
        ("mapping", "0057_change_featuretype_tag_m2m_pk_type_to_uuid"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="spatialfeaturetypetags",
            managers=[("objects", CommonTenantManager())],
        ),
        migrations.AddField(
            model_name="spatialfeaturetypetags",
            name="das_tenant",
            field=models.ForeignKey(
                default=default_tenant_id,
                on_delete=deletion.CASCADE,
                related_name="mapping_spatialfeaturetypetags",
                to="core.dastenant",
            ),
        ),
        migrations.AlterField(
            model_name="spatialfeaturetypetags",
            name="spatialfeaturetype",
            field=TenantForeignKey(
                default=uuid.uuid4,
                on_delete=deletion.CASCADE,
                related_name="spatialfeaturetype",
                to="mapping.spatialfeaturetype",
            ),
        ),
        migrations.AlterField(
            model_name="spatialfeaturetypetags",
            name="spatialfeaturetypetag",
            field=TenantForeignKey(
                default=uuid.uuid4,
                on_delete=deletion.CASCADE,
                related_name="spatialfeaturetypetag",
                to="mapping.spatialfeaturetypetag",
            ),
        ),
    ]
