# Generated by Django 3.2.21 on 2023-12-08 19:17

from django.db import migrations, models
from django.db.models import deletion

from utils.migrations.columns import default_tenant_id


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0015_delete_unique_constraints"),
        ("mapping", "0058_add_tenant_awareness_to_spatial_feature_type_tagging"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="spatialfeaturetypetag",
            options={"base_manager_name": "objects", "default_manager_name": "objects", "ordering": ["name"]},
        ),
        migrations.AddField(
            model_name="spatialfeaturetypetag",
            name="das_tenant",
            field=models.ForeignKey(default=default_tenant_id, on_delete=deletion.CASCADE, to="core.dastenant"),
        ),
        migrations.AlterUniqueTogether(
            name="spatialfeaturetypetag",
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name="spatialfeaturetypetag",
            index=models.Index(fields=["das_tenant", "name"], name="mapping_spa_das_ten_934082_idx"),
        ),
        migrations.AddIndex(
            model_name="spatialfeaturetypetag",
            index=models.Index(fields=["das_tenant", "slug"], name="mapping_spa_das_ten_0c3c3d_idx"),
        ),
        migrations.AddConstraint(
            model_name="spatialfeaturetypetag",
            constraint=models.UniqueConstraint(
                fields=("das_tenant", "name"), name="mapping_spatialfeaturetypetag_unique_name_across_tenants"
            ),
        ),
        migrations.AddConstraint(
            model_name="spatialfeaturetypetag",
            constraint=models.UniqueConstraint(
                fields=("das_tenant", "slug"), name="mapping_spatialfeaturetypetag_unique_slug_across_tenants"
            ),
        ),
    ]
