# Generated by Django 3.2.21 on 2023-12-08 23:32

from django.db import migrations

from utils.migrations.update_primary_key import drop_constraint

APP_NAME = "mapping"


def drop_constraints(apps, schema_editor):
    drop_constraint(
        app=APP_NAME, model="SpatialFeatureTypeTag", constraint="mapping_spatialfeaturetypetag_name_key", cascade=True
    )
    drop_constraint(
        app=APP_NAME,
        model="SpatialFeatureTypeTags",
        constraint="mapping_spatialfeaturety_spatialfeaturetype_id_sp_2f5ff974_uniq",
        cascade=True,
    )
    drop_constraint(
        app=APP_NAME,
        model="SpatialFeatureTypeTags",
        constraint="mapping_spatialfeaturetypetags_id_995f4fa9_uniq",
        cascade=True,
    )


class Migration(migrations.Migration):
    dependencies = [("mapping", "0059_add_das_tennant_to_feature_type_tag")]
    operations = [migrations.RunPython(code=drop_constraints, reverse_code=migrations.RunPython.noop)]
