# Generated by Django 3.2.21 on 2023-12-08 23:45


from django.db import migrations, models

from utils.migrations.update_primary_key import add_tenant_to_primary_key

mapping_models = ["SpatialFeatureTypeTag", "SpatialFeatureTypeTags"]


def regenerate_primary_keys(apps, schema_editor):
    add_tenant_to_primary_key("mapping", mapping_models)


class Migration(migrations.Migration):
    dependencies = [("mapping", "0060_spatial_feature_type_tags_drop_constraints")]

    operations = [
        migrations.RunPython(code=regenerate_primary_keys, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name="spatialfeaturetypetag",
            name="name",
            field=models.CharField(max_length=255),
        ),
    ]
