# Generated by Django 3.2.21 on 2024-02-29 21:26


from django.db import migrations

SQL_CRATE_UNIQUE_CONSTRAINT = "ALTER TABLE mapping_spatialfeature ADD CONSTRAINT mapping_unique_id UNIQUE (id);"
SQL_REVERSE_CRATE_UNIQUE_CONSTRAINT = "ALTER TABLE mapping_spatialfeature DROP CONSTRAINT mapping_unique_id;"


class Migration(migrations.Migration):
    dependencies = [
        ("mapping", "0061_regenerate_primary_keys"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SpatialFeatureGroupQuery",
        ),
        migrations.RunSQL(
            sql=SQL_CRATE_UNIQUE_CONSTRAINT,
            reverse_sql=SQL_REVERSE_CRATE_UNIQUE_CONSTRAINT,
        ),
    ]
