# Generated by Django 3.2.21 on 2024-03-07 22:40

import uuid

import django_multitenant.fields
import django_multitenant.mixins

import django.db.models.deletion
from django.db import migrations, models

import mapping.models
import utils.migrations.columns
import utils.models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0022_custom_permissions_migration"),
        ("mapping", "0062_delete_spatialfeaturegroupquery"),
    ]

    operations = [
        migrations.CreateModel(
            name="SpatialFeatureGroupStaticFeatures",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "das_tenant",
                    models.ForeignKey(
                        default=utils.migrations.columns.default_tenant_id,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mapping_spatialfeaturegroupstaticfeatures",
                        to="core.dastenant",
                    ),
                ),
                (
                    "spatial_feature",
                    django_multitenant.fields.TenantForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="mapping.spatialfeature"
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
                "default_manager_name": "objects",
            },
            bases=(django_multitenant.mixins.TenantModelMixin, models.Model),
            managers=[
                ("objects", utils.models.CommonTenantManager()),
            ],
        ),
        migrations.CreateModel(
            name="SpatialFeatureGroupStaticTemp",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "das_tenant",
                    models.ForeignKey(
                        default=utils.migrations.columns.default_tenant_id,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.dastenant",
                    ),
                ),
                (
                    "features",
                    models.ManyToManyField(
                        blank=True,
                        related_name="groups_temp",
                        related_query_name="group_temp",
                        through="mapping.SpatialFeatureGroupStaticFeatures",
                        to="mapping.SpatialFeature",
                    ),
                ),
            ],
            options={
                "verbose_name": "Feature Group",
                "ordering": ["name"],
                "base_manager_name": "objects",
                "default_manager_name": "objects",
            },
            bases=(django_multitenant.mixins.TenantModelMixin, models.Model),
            managers=[
                ("objects", mapping.models.SpatialFeatureGroupStaticManager()),
            ],
        ),
        migrations.AddField(
            model_name="spatialfeaturegroupstaticfeatures",
            name="spatial_feature_groupstatic",
            field=django_multitenant.fields.TenantForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="mapping.spatialfeaturegroupstatictemp"
            ),
        ),
        migrations.AddIndex(
            model_name="spatialfeaturegroupstatictemp",
            index=models.Index(fields=["das_tenant", "name"], name="mapping_spa_das_ten_acbd4c_idx"),
        ),
        migrations.AddConstraint(
            model_name="spatialfeaturegroupstatictemp",
            constraint=models.UniqueConstraint(
                fields=("das_tenant", "name"), name="mapping_spatialfeaturegroupstatictemp_unique_name_across_tenants"
            ),
        ),
    ]
