# Generated by Django 3.2.21 on 2024-03-07 22:43

from django.db import migrations

SQL_MIGRATE_SPATIALFEATURE_TEMP = """
INSERT INTO mapping_spatialfeaturegroupstatictemp (id, name, description, created_at, updated_at, das_tenant_id)
SELECT id, name, description, created_at, updated_at, das_tenant_id
FROM mapping_spatialfeaturegroup;
"""

SQL_MIGRATE_SPATIALFEATUREGROUPSTATICFEATURES = """
INSERT INTO mapping_spatialfeaturegroupstaticfeatures (id, das_tenant_id, spatial_feature_id, spatial_feature_groupstatic_id)
SELECT uuid_generate_v4(), spatialfg.das_tenant_id, sff.spatialfeature_id, sff.spatialfeaturegroupstatic_id
FROM mapping_spatialfeaturegroupstatic_features AS sff
         JOIN mapping_spatialfeaturegroup AS spatialfg ON spatialfg.id = sff.spatialfeaturegroupstatic_id;
"""


class Migration(migrations.Migration):
    dependencies = [
        ("mapping", "0063_add_spatialfeaturegroupstatictemp_model"),
    ]

    operations = [
        migrations.RunSQL(
            sql=SQL_MIGRATE_SPATIALFEATURE_TEMP,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql=SQL_MIGRATE_SPATIALFEATUREGROUPSTATICFEATURES,
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
