# Generated by Django 3.2.21 on 2024-03-08 03:47


from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mapping", "0064_migrate_data_to_spatialfeaturegroupstatictemp"),
    ]
    # move operations to mapping 0066 migration to avoid migration state corruption
    operations = []
