# Generated by Django 3.2.21 on 2024-03-08 03:45

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0022_custom_permissions_migration"),
        ("mapping", "0065_delete_spatialfeaturegroup_models"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="SpatialFeatureGroupStaticTemp",
            new_name="SpatialFeatureGroupStatic",
        ),
        migrations.RemoveConstraint(
            model_name="spatialfeaturegroupstatic",
            name="mapping_spatialfeaturegroupstatictemp_unique_name_across_tenants",
        ),
        migrations.RemoveIndex(
            model_name="spatialfeaturegroupstatic",
            name="mapping_spa_das_ten_acbd4c_idx",
        ),
        migrations.AlterField(
            model_name="spatialfeature",
            name="id",
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AddIndex(
            model_name="spatialfeaturegroupstatic",
            index=models.Index(fields=["das_tenant", "name"], name="mapping_spa_das_ten_4f6e73_idx"),
        ),
        migrations.AddConstraint(
            model_name="spatialfeaturegroupstatic",
            constraint=models.UniqueConstraint(
                fields=("das_tenant", "name"), name="mapping_spatialfeaturegroupstatic_unique_name_across_tenants"
            ),
        ),
        migrations.RemoveIndex(
            model_name="spatialfeaturegroupstatic",
            name="mapping_spa_das_ten_4f6e73_idx",
        ),
        migrations.AddIndex(
            model_name="spatialfeaturegroupstatic",
            index=models.Index(fields=["das_tenant", "name"], name="mapping_spa_das_ten_0e9007_idx"),
        ),
    ]
