# Generated by Django 3.2.21 on 2024-06-13 21:24

from django.db import migrations

RENAME_CONSTRAINT_SQL = """
DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM   information_schema.table_constraints
        WHERE  constraint_name = 'mapping_spatialfeaturegroupstatictemp_pkey'
        AND    table_name = 'mapping_spatialfeaturegroupstatic'
    ) THEN
        EXECUTE 'ALTER TABLE mapping_spatialfeaturegroupstatic RENAME CONSTRAINT mapping_spatialfeaturegroupstatictemp_pkey TO mapping_spatialfeaturegroupstatic_pkey';
    END IF;
END
$$;
"""

REVERT_CONSTRAINT_SQL = """
DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM   information_schema.table_constraints
        WHERE  constraint_name = 'mapping_spatialfeaturegroupstatic_pkey'
        AND    table_name = 'mapping_spatialfeaturegroupstatic'
    ) THEN
        EXECUTE 'ALTER TABLE mapping_spatialfeaturegroupstatic RENAME CONSTRAINT mapping_spatialfeaturegroupstatic_pkey TO mapping_spatialfeaturegroupstatictemp_pkey';
    END IF;
END
$$;
"""

DROP_INDEX_1_SQL = """
DROP INDEX IF EXISTS mapping_spa_das_ten_0e9007_idx;
"""

REVERT_INDEX_1_SQL = """
CREATE INDEX mapping_spa_das_ten_0e9007_idx
    ON public.mapping_spatialfeaturegroupstatic
    USING btree (das_tenant_id, name);
"""

DROP_INDEX_2_SQL = """
DROP INDEX IF EXISTS mapping_spa_das_ten_4f6e73_idx
"""

REVERT_INDEX_2_SQL = """
CREATE INDEX mapping_spa_das_ten_4f6e73_idx
    ON public.mapping_spatialfeaturegroupstatic
    USING btree (das_tenant_id, name);
"""


class Migration(migrations.Migration):

    dependencies = [
        ("mapping", "0066_rename_spatialfeaturegrouptemp_model"),
    ]

    operations = [
        migrations.RunSQL(
            sql=RENAME_CONSTRAINT_SQL,
            reverse_sql=REVERT_CONSTRAINT_SQL,
        ),
        migrations.RunSQL(
            sql=DROP_INDEX_1_SQL,
            reverse_sql=REVERT_INDEX_1_SQL,
        ),
        migrations.RunSQL(
            sql=DROP_INDEX_2_SQL,
            reverse_sql=REVERT_INDEX_2_SQL,
        ),
    ]
