# Generated by Django 3.2.21 on 2024-06-19 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mapping", "0067_spatialfeaturegroup_rename_contraint_and_drop_indexes"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="spatialfeaturegroupstatic",
            name="mapping_spa_das_ten_4f6e73_idx",
        ),
    ]
