# Generated by Django 3.2.21 on 2024-08-23 20:12

from django.db import migrations

from utils.migrations.update_primary_key import add_tenant_to_primary_key


def regenerate_primary_keys(apps, schema_editor):
    add_tenant_to_primary_key(app="mapping", models=["SpatialFeatureGroupStatic"])


class Migration(migrations.Migration):

    dependencies = [
        ("mapping", "0068_remove_spatialfeaturegroupstatic_mapping_spa_das_ten_4f6e73_idx"),
    ]

    operations = [
        migrations.RunPython(code=regenerate_primary_keys, reverse_code=migrations.RunPython.noop),
    ]
