# Generated by Django 3.2.21 on 2024-10-15 20:06

from django.db import migrations

unique_constraint_id_sql = """
ALTER TABLE public.mapping_featuresetfeaturetype
    DROP CONSTRAINT mapping_featuresetfeaturetype_id_c3e9663d_uniq;

ALTER TABLE public.mapping_featuresetfeaturetype
    ADD CONSTRAINT mapping_featuresetfeaturetype_id_c3e9663d_uniq
        UNIQUE (id, das_tenant_id);
"""

unique_constraint_sql = """
ALTER TABLE public.mapping_featuresetfeaturetype
    DROP CONSTRAINT mapping_featureset_types_featureset_id_featuretyp_1704523d_uniq;

ALTER TABLE public.mapping_featuresetfeaturetype
    ADD CONSTRAINT mapping_featureset_types_featureset_id_featuretyp_1704523d_uniq
        UNIQUE (das_tenant_id, featureset_id, featuretype_id);
"""

update_feature_set_index_sql = """
DROP INDEX public.mapping_featureset_types_featuretype_id_4ba6a14f;

CREATE INDEX mapping_featureset_types_featuretype_id_4ba6a14f
    ON public.mapping_featuresetfeaturetype (das_tenant_id, featuretype_id);
"""

update_feature_type_index_sql = """
DROP INDEX public.mapping_featureset_types_featureset_id_fb46f6c2;

CREATE INDEX mapping_featureset_types_featureset_id_fb46f6c2
    ON public.mapping_featuresetfeaturetype (das_tenant_id, featureset_id);
"""

drop_tenant_index_sql = """
DROP INDEX public.mapping_featuresetfeaturetype_das_tenant_id_081c6d06;
"""


class Migration(migrations.Migration):

    dependencies = [
        ("mapping", "0069_regenerate_primary_key_spatialfeaturegroup"),
    ]

    operations = [
        migrations.RunSQL(sql=unique_constraint_id_sql, reverse_sql=""),
        migrations.RunSQL(sql=unique_constraint_sql, reverse_sql=""),
        migrations.RunSQL(sql=update_feature_set_index_sql, reverse_sql=""),
        migrations.RunSQL(sql=update_feature_type_index_sql, reverse_sql=""),
        migrations.RunSQL(sql=drop_tenant_index_sql, reverse_sql=""),
    ]
