# Generated by Django 3.2.21 on 2024-10-16 16:36

from django.db import migrations, models

from utils.migrations.update_primary_key import drop_constraint


def fix_mapping_featuresetfeaturetype(apps, schema):
    drop_constraint(
        app="mapping",
        model="FeatureSetFeatureType",
        constraint="mapping_featuresetfeaturetype_id_c3e9663d_uniq",
    )
    drop_constraint(
        app="mapping",
        model="FeatureSetFeatureType",
        constraint="mapping_featureset_types_featureset_id_featuretyp_1704523d_uniq",
    )


# delete stale indexes
drop_das_tenant_index_sql = """DROP INDEX public.mapping_featuresetfeaturetype_das_tenant_id_081c6d06;"""
drop_feature_set_index_sql = """DROP INDEX public.mapping_featureset_types_featureset_id_fb46f6c2;"""
drop_feature_type_index_sql = """DROP INDEX public.mapping_featureset_types_featuretype_id_4ba6a14f;"""


class Migration(migrations.Migration):

    dependencies = [
        ("mapping", "0069_regenerate_primary_key_spatialfeaturegroup"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="featuresetfeaturetype",
            options={"base_manager_name": "objects", "default_manager_name": "objects"},
        ),
        migrations.AddIndex(
            model_name="featuresetfeaturetype",
            index=models.Index(fields=["das_tenant", "featureset"], name="mapping_fea_das_ten_524bed_idx"),
        ),
        migrations.AddIndex(
            model_name="featuresetfeaturetype",
            index=models.Index(fields=["das_tenant", "featuretype"], name="mapping_fea_das_ten_84a4e9_idx"),
        ),
        migrations.AddConstraint(
            model_name="featuresetfeaturetype",
            constraint=models.UniqueConstraint(
                fields=("das_tenant", "featureset", "featuretype"),
                name="mapping_featuresetfeaturetype_unique_across_tenants",
            ),
        ),
        migrations.RunPython(fix_mapping_featuresetfeaturetype),
        migrations.RunSQL(drop_das_tenant_index_sql),
        migrations.RunSQL(drop_feature_set_index_sql),
        migrations.RunSQL(drop_feature_type_index_sql),
    ]
