# Generated by Django 3.2.25 on 2025-07-15 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mapping", "0070_fix_featuresetfeaturetype_tenant_aware"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                ALTER TABLE mapping_spatialfeaturetypetag DROP CONSTRAINT mapping_spatialfeaturetypetag_pkey;

                ALTER TABLE mapping_spatialfeaturetypetag ALTER COLUMN id TYPE bigint;

                -- Handle older database sequence naming convention
                DO $$
                BEGIN
                    -- Check if the old sequence exists and rename it if needed
                    IF EXISTS (SELECT 1 FROM pg_sequences WHERE schemaname = 'public' AND sequencename = 'mapping__tagulous_spatialfeaturetype_tags_id_seq') THEN
                        ALTER SEQUENCE mapping__tagulous_spatialfeaturetype_tags_id_seq RENAME TO mapping_spatialfeaturetypetag_id_seq;
                    END IF;
                END $$;

                -- OWNED BY is not allowed on identity sequences (PostgreSQL 10+); only run for SERIAL-style columns
                DO $$
                BEGIN
                    IF NOT EXISTS (
                        SELECT 1 FROM pg_attribute a
                        JOIN pg_class t ON t.oid = a.attrelid
                        WHERE t.relname = 'mapping_spatialfeaturetypetag'
                          AND a.attname = 'id'
                          AND a.attnum > 0
                          AND NOT a.attisdropped
                          AND a.attidentity != ''
                    ) THEN
                        ALTER SEQUENCE mapping_spatialfeaturetypetag_id_seq OWNED BY mapping_spatialfeaturetypetag.id;
                    END IF;
                END $$;

                ALTER TABLE mapping_spatialfeaturetypetag ADD CONSTRAINT mapping_spatialfeaturetypetag_pkey PRIMARY KEY (das_tenant_id, id);
            """,
                ),
            ],
            state_operations=[
                migrations.AlterField(
                    model_name="spatialfeaturetypetag",
                    name="id",
                    field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
                ),
            ],
        )
    ]
