# Generated by Django 3.2.25 on 2025-07-15 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mapping", "0070_fix_featuresetfeaturetype_tenant_aware"),
    ]

    operations = [
        migrations.AlterField(
            model_name="spatialfeaturetypetag",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
    ]
