# Generated by Django 3.2.25 on 2025-09-14 22:20
import logging

from django.apps import apps
from django.db import migrations

from core.models.core import DASTenant
from utils.tenant import TenantNotFoundException
from utils.tenant.managers import TenantContextManager, UnsetDASTenantContextManager

logger = logging.getLogger(__name__)

Google_satellite_conf = {
    "url": "https://mt.google.com/vt/lyrs=y&x={x}&y={y}&z={z}",
    "type": "tile_server",
    "title": "Google Satellite",
    "icon_url": "https://maps.google.com/mapfiles/ms/icons/red-dot.png",
}


def update_existing_tilelayer_conf(unused, schema_editor):
    # We get the model from the versioned app registry
    TileLayer = apps.get_model("mapping", "TileLayer")

    with UnsetDASTenantContextManager():
        das_tenants = DASTenant.objects.all()

    for tenant in das_tenants:
        try:
            with TenantContextManager(tenant.domain):
                # find all the old Google Satellite records with "accessToken", for service type google_map
                for google_layer in TileLayer.objects.filter(attributes__type="google_map"):
                    google_layer.attributes = Google_satellite_conf
                    google_layer.save()

        except TenantNotFoundException:
            logger.warning(
                "Tenant with domain %s found in current cluster domain list does not exist in TMS", tenant.domain
            )


class Migration(migrations.Migration):

    dependencies = [
        ("mapping", "0071_alter_spatialfeaturetypetag_id"),
    ]

    operations = [
        migrations.RunPython(update_existing_tilelayer_conf, reverse_code=migrations.RunPython.noop),
    ]
