# Generated by Django 3.2.25 on 2025-11-10 18:20

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mapping", "0072_google"),
    ]

    operations = [
        migrations.AddField(
            model_name="spatialfeature",
            name="feature_geometry_webmercator",
            field=django.contrib.gis.db.models.fields.GeometryField(
                blank=True,
                help_text="Simplified Web Mercator geometry for vector tile serving (2.5m tolerance)",
                null=True,
                srid=3857,
            ),
        ),
    ]
