# Generated by Django 3.2.25 on 2025-11-17 20:07

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mapping", "0074_add_webmercator_gist_index"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="spatialfeature",
            name="mapping_spatialfeature_tenant_webmercator_gist",
        ),
        migrations.AddIndex(
            model_name="spatialfeature",
            index=django.contrib.postgres.indexes.GistIndex(
                fields=["das_tenant_id", "feature_geometry_webmercator"], name="map_spatialfeat_webmerc_gist"
            ),
        ),
        migrations.AddIndex(
            model_name="spatialfeature",
            index=django.contrib.postgres.indexes.GistIndex(
                fields=["das_tenant_id", "feature_geometry"], name="map_spatialfeat_geom_gist"
            ),
        ),
        migrations.AddIndex(
            model_name="spatialfeature",
            index=models.Index(fields=["das_tenant_id", "feature_type"], name="map_spatialfeat_type_idx"),
        ),
        migrations.AddIndex(
            model_name="spatialfeature",
            index=models.Index(fields=["das_tenant_id", "spatialfile"], name="map_spatialfeat_file_idx"),
        ),
    ]
