# Generated by Django 3.2.25 on 2026-01-28 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0074_add_spatialfeature_indexes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='spatialfeaturetype',
            options={'base_manager_name': 'objects', 'default_manager_name': 'objects', 'ordering': ['name'], 'verbose_name': 'Feature Type', 'verbose_name_plural': 'Feature Types'},
        ),
    ]
