# Generated by Django 4.2.28 on 2026-02-16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mapping", "0075_django_42"),
        ("mapping", "0076_rename_feature_class_permissions"),
    ]

    operations = []
