# Generated by Django 4.2.30 on 2026-07-11 06:24

import django_multitenant.fields

import django.db.models.deletion
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mapping", "0077_merge_20260216_mapping_0075_0076"),
    ]

    operations = [
        migrations.AlterField(
            model_name="spatialfeaturefile",
            name="feature_type",
            field=django_multitenant.fields.TenantForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="mapping.spatialfeaturetype"
            ),
        ),
    ]
