kind: ConfigMap
apiVersion: v1
metadata:
  namespace: "${KUBERNETES_NAMESPACE}"
  name: server-configmap
data:
  ACCEPT_EULA: "${ACCEPT_EULA}"
  ALERTS_ENABLED: "${ALERTS_ENABLED}"
  ALT_SERVER_NAMES: "${ALT_SERVER_NAMES}"
  API_HOST: "${API_HOST}"
  API_PORT: "${API_PORT}"
  CORS_ORIGIN_ALLOW_ALL: "False"
  CORS_REPLACE_HTTPS_REFERER: "True"
  CSRF_COOKIE_SECURE: "True"
  DAILY_REPORT_ENABLED: "${DAILY_REPORT_ENABLED}"
  DB_HOST: "${DB_HOST}"
  DB_NAME: "${DB_NAME}"
  DB_PORT: "${DB_PORT}"
  DEFAULT_FROM_EMAIL: "${DEFAULT_FROM_EMAIL}"
  EMAIL_HOST: "${EMAIL_HOST}"
  EMAIL_HOST_USER: "${EMAIL_HOST_USER}"
  EMAIL_PORT: "2587"
  ENABLE_DEBUG: "${ENABLE_DEBUG}"
  ENABLE_DEV: "False"
  EUS_EMAIL: "${EUS_EMAIL}"
  EUS_NAME: "${EUS_NAME}"
  EUS_ORG: "${EUS_ORG}"
  EUS_TYPE: "${EUS_TYPE}"
  FQDN: "${FQDN}"
  FROM_EMAIL: "${FROM_EMAIL}"
  GFW_CLUSTER_RADIUS: "${GFW_CLUSTER_RADIUS}"
  GFW_BACKFILL_INTERVAL_DAYS: "${GFW_BACKFILL_INTERVAL_DAYS}"
  GS_BUCKET_NAME: "${GS_BUCKET_NAME}"
  KML_EXPORT: "${KML_EXPORT}"
  MAPPING_FEATURES_V2: "${MAPPING_FEATURES_V2}"
  SESSION_COOKIE_SECURE: "True"
  SHOW_STATIONARY_SUBJECTS_ON_MAP: "${SHOW_STATIONARY_SUBJECTS_ON_MAP}"
  SHOW_TRACK_DAYS: "${SHOW_TRACK_DAYS}"
  SMS_ID: "${SMS_ID}"
  SMS_TOKEN: "${SMS_TOKEN}"
  TIME_ZONE: "${TIME_ZONE}"
  SENDSMS_TWILIO_FROM_NUMBER: "${SENDSMS_TWILIO_FROM_NUMBER}"
  PATROL_ENABLED: "${PATROL_ENABLED}"
  SUBJECT_REGION_ENABLED: "${SUBJECT_REGION_ENABLED}"
  TABLEAU_DEFAULT_DASHBOARD: "${TABLEAU_DEFAULT_DASHBOARD}"
  TABLEAU_ENABLED: "${TABLEAU_ENABLED}"
  TABLEAU_SITE_ID: "${TABLEAU_SITE_ID}"
  TRACK_LENGTH: "${TRACK_LENGTH}"
