apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: api
  namespace: "${KUBERNETES_NAMESPACE}"
spec:
  maxReplicas: 16
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: api
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  behavior:
    scaleDown:
      selectPolicy: Max
      stabilizationWindowSeconds: 300
    scaleUp:
      selectPolicy: Max
      stabilizationWindowSeconds: 30  # Reduced stabilization window for faster scaling
      policies:
      - type: Percent
        value: 100
        periodSeconds: 60  # Allow scaling up by 100% every 60 seconds
      - type: Pods
        value: 4
        periodSeconds: 60  #
