apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: "${KUBERNETES_NAMESPACE}"
  name: nginx
spec:
  selector:
    matchLabels:
      das.component: nginx
  template:
    metadata:
      labels:
        das.component: nginx
    spec:
      imagePullSecrets:
        - name: gcr-secret
      containers:
      - image: "${INGRESS_VERSION}"
        name: das-nginx
        resources:
          requests:
            cpu: "5m"
            memory: "65Mi"
          limits: 
            cpu: "50m"
            memory: "250Mi"
        ports:
        - containerPort: 443
        - containerPort: 8000
        - containerPort: 9001
        env:
        - name: WEB_SERVICE_NAME
          value: "${WEB_SERVICE_NAME}"
        - name: BUNDLE_CRT
          valueFrom:
            secretKeyRef:
              name: pamdas-org-ssl-cert-bundle
              key: value
        - name: PAMDAS_ORG_PRIVATE_KEY_PEM
          valueFrom:
            secretKeyRef:
              name: pamdas-org-private-key-pem
              key: value
