kind: ConfigMap
apiVersion: v1
metadata:
  namespace: "${KUBERNETES_NAMESPACE}"
  name: server-configmap
data:
  ACCEPT_EULA: "${ACCEPT_EULA}"
  ALERTS_ENABLED: "${ALERTS_ENABLED}"
  ALERTS_RATE_LIMIT: "${ALERTS_RATE_LIMIT}"
  ALT_SERVER_NAMES: "${ALT_SERVER_NAMES}"
  API_HOST: "${API_HOST}"
  API_PORT: "${API_PORT}"
  BUOY_API: "${BUOY_API}"
  CLUSTER_NAME: "${CLUSTER_NAME}"
  CLUSTER_NAMESPACE: "${KUBERNETES_NAMESPACE}"
  CORS_ORIGIN_ALLOW_ALL: "False"
  CSRF_COOKIE_SECURE: "True"
  DAILY_REPORT_ENABLED: "${DAILY_REPORT_ENABLED}"
  DB_HOST: "${DB_HOST}"
  DB_NAME: "${DB_NAME}"
  DB_PORT: "${DB_PORT}"
  DEFAULT_FROM_EMAIL: "${DEFAULT_FROM_EMAIL}"
  DJANGO_LOGGING_LEVEL: "${DJANGO_LOGGING_LEVEL}"
  DJANGO_REQUEST_LOGGING_LEVEL: "${DJANGO_REQUEST_LOGGING_LEVEL}"
  DJANGO_SERVER_LOGGING_LEVEL: "${DJANGO_SERVER_LOGGING_LEVEL}"
  EMAIL_HOST: "${EMAIL_HOST}"
  EMAIL_HOST_USER: "${EMAIL_HOST_USER}"
  EMAIL_PORT: "2587"
  ENABLE_DEBUG: "${ENABLE_DEBUG}"
  ENABLE_DEV: "False"
  EUS_EMAIL: "${EUS_EMAIL}"
  EUS_NAME: "${EUS_NAME}"
  EUS_ORG: "${EUS_ORG}"
  EUS_TYPE: "${EUS_TYPE}"
  FEATURE_TMS: "${FEATURE_TMS}"
  FQDN: "${FQDN}"
  FROM_EMAIL: "${FROM_EMAIL}"
  GEO_PERMISSION_SPEED_KM_H: "${GEO_PERMISSION_SPEED_KM_H}"
  GFW_BACKFILL_INTERVAL_DAYS: "${GFW_BACKFILL_INTERVAL_DAYS}"
  GFW_CLUSTER_RADIUS: "${GFW_CLUSTER_RADIUS}"
  GS_BUCKET_NAME: "${GS_BUCKET_NAME}"
  GUNICORN_CMD_ARGS: "--workers 4 --threads 2 --worker-class gthread --max-requests 20000 --limit-request-line 66000 --max-requests-jitter 500 --timeout 120 --graceful-timeout 40 --keep-alive 10"
  KML_EXPORT: "${KML_EXPORT}"
  MAPPING_FEATURES_V2: "${MAPPING_FEATURES_V2}"
  OBSERVATION_ACCURACY_THRESHOLD: "${OBSERVATION_ACCURACY_THRESHOLD}"
  PATROL_ENABLED: "${PATROL_ENABLED}"
  ROOT_LOGGING_LEVEL: "${ROOT_LOGGING_LEVEL}"
  RTAPI_LOGGING_LEVEL: "${RTAPI_LOGGING_LEVEL}"
  RTAPI_PUBSUB_LOGGING_LEVEL: "${RTAPI_PUBSUB_LOGGING_LEVEL}"
  RTAPI_SOCKET_LOGGING_LEVEL: "${RTAPI_SOCKET_LOGGING_LEVEL}"
  SENDSMS_TWILIO_FROM_NUMBER: "${SENDSMS_TWILIO_FROM_NUMBER}"
  SESSION_COOKIE_SECURE: "True"
  SHOW_STATIONARY_SUBJECTS_ON_MAP: "${SHOW_STATIONARY_SUBJECTS_ON_MAP}"
  SHOW_TRACK_DAYS: "${SHOW_TRACK_DAYS}"
  DEFAULT_EVENT_FILTER_FROM_DAYS: "${DEFAULT_EVENT_FILTER_FROM_DAYS}"
  DEFAULT_PATROL_FILTER_FROM_DAYS: "${DEFAULT_PATROL_FILTER_FROM_DAYS}"
  SMS_ID: "${SMS_ID}"
  SMS_TOKEN: "${SMS_TOKEN}"
  SUBJECT_REGION_ENABLED: "${SUBJECT_REGION_ENABLED}"
  TABLEAU_DEFAULT_DASHBOARD: "${TABLEAU_DEFAULT_DASHBOARD}"
  TABLEAU_ENABLED: "${TABLEAU_ENABLED}"
  TABLEAU_SITE_ID: "${TABLEAU_SITE_ID}"
  TIME_ZONE: "${TIME_ZONE}"
  TMS_API_HOST: "${TMS_API_HOST}"
  TMS_API_KEY: "${TMS_API_KEY}"
  TRACK_LENGTH: "${TRACK_LENGTH}"
