apiVersion: apps/v1beta1
kind: Deployment
metadata:
  namespace: "${KUBERNETES_NAMESPACE}"
  name: redis
spec:
  template:
    metadata:
      labels:
        das.component: redis
    spec:
      containers:
        - image: redis
          name: das-redis
          resources:
            requests:
              cpu: "50m"
          ports:
            - containerPort: 6379
          readinessProbe:
            exec:
              command:
                - redis-cli
                - 'bash -c ''[[ $(redis-cli PING) == "PONG" ]]'''
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 3
            successThreshold: 1
          livenessProbe:
            exec:
              command:
                - redis-cli
                - 'bash -c ''[[ $(redis-cli PING) == "PONG" ]]'''
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 3
            successThreshold: 1
