apiVersion: v1
kind: Service
metadata:
  namespace: "${KUBERNETES_NAMESPACE}"
  name: web-react
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    das.component: web-react
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: "${KUBERNETES_NAMESPACE}"
  name: web-react
spec:
  selector:
    matchLabels:
      das.component: web-react
  template:
    metadata:
      labels:
        das.component: web-react
    spec:
      imagePullSecrets:
        - name: gcr-secret
      containers:
      - name: web-react
        image: "${WEB_REACT_VERSION}"
        resources:
          requests:
            cpu: "5m"
            memory: "20Mi"
          limits:
            cpu: "150m"
            memory: "200Mi"

        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            port: 80
            path: /
          initialDelaySeconds: 5
          periodSeconds: 10
          failureThreshold: 3
          successThreshold: 1
        livenessProbe:
          httpGet:
            port: 80
            path: /
          initialDelaySeconds: 15
          periodSeconds: 20
          failureThreshold: 3
          successThreshold: 1
        env:
        - name: APIENDPOINT
          value: "${API_ENDPOINT}"
