apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: "${KUBERNETES_NAMESPACE}"
  name: redis
spec:
  selector:
    matchLabels:
      das.component: redis
  template:
    metadata:
      labels:
        das.component: redis
    spec:
      containers:
        - image: redis:7.0.11
          name: das-redis
          resources:
            requests:
              cpu: "50m"
              memory: "100Mi"
            limits:
              cpu: "100m"
              memory: "200Mi"
          ports:
            - containerPort: 6379
          readinessProbe:
            exec:
              command:
                - /bin/bash
                - -c
                - '[[ $(redis-cli PING) == "PONG" ]]'
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 3
            successThreshold: 1
          livenessProbe:
            exec:
              command:
                - /bin/bash
                - -c
                - '[[ $(redis-cli PING) == "PONG" ]]'
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 3
            successThreshold: 1
