apiVersion: "v1"
kind: "LimitRange"
metadata:
  name: "container-limits"
  namespace: "${KUBERNETES_NAMESPACE}"
spec:
  limits:
    - type: Container
      defaultRequest:
        cpu: 25m
        memory: 100Mi
      min:
        cpu: 10m
        memory: 25Mi
      max:
        cpu: 800m
        memory: 2000Mi
    - type: Pod
      min:
        cpu: 50m
        memory: 100Mi
      max:
        cpu: 2000m
        memory: 3000Mi