apiVersion: v1
kind: Service
metadata:
  namespace: "${KUBERNETES_NAMESPACE}"
  name: nginx
spec:
  type: LoadBalancer
  loadBalancerIP: "${SITE_IP_ADDRESS}"
  ports:
  - port: 80
    targetPort: 80
    name: http-port
  - port: 443
    targetPort: 443
    name: https-port
  selector:
    das.component: nginx
