apiVersion: apps/v1beta1
kind: Deployment
metadata:
  namespace: <<namespace>>
  name: redis
spec:
  template:
    metadata:
      labels:
        das.component: redis
    spec:
      containers:
      - image: redis
        name: das-redis
        resources:
          requests:
            cpu: "25m"
        ports:
          - containerPort: 6379
