apiVersion: apps/v1beta1
kind: Deployment
metadata:
  namespace: <<namespace>>
  name: api
spec:
  template:
    metadata:
      labels:
        das.component: api
    spec:
      imagePullSecrets:
        - name: gcr-secret
      containers:
      - image: gcr.io/padas-app/api:<<server-version>>
        name: das-api
        resources:
          requests:
            cpu: "200m"
            memory: "500Mi"
        ports:
          - containerPort: 8000
        env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: datastore-configmap
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: datastore-configmap
              key: DB_PORT
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: datastore-configmap
              key: DB_NAME
        - name: DB_USER
          valueFrom:
            configMapKeyRef:
              name: datastore-configmap
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: datastore-configmap
              key: DB_PASSWORD
        - name: USE_AZURE_STORAGE
          valueFrom:
            configMapKeyRef:
              name: datastore-configmap
              key: USE_AZURE_STORAGE
        - name: STORAGE_ACCOUNT
          valueFrom:
            configMapKeyRef:
              name: datastore-configmap
              key: STORAGE_ACCOUNT
        - name: STORAGE_ACCOUNT_KEY
          valueFrom:
            configMapKeyRef:
              name: datastore-configmap
              key: STORAGE_ACCOUNT_KEY
        - name: STORAGE_CONTAINER
          valueFrom:
            configMapKeyRef:
              name: datastore-configmap
              key: STORAGE_CONTAINER
        - name: EMAIL_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: default-configmap
              key: EMAIL_PASSWORD

