apiVersion: apps/v1beta1
kind: Deployment
metadata:
  namespace: <<namespace>>
  name: api
spec:
  template:
    metadata:
      labels:
        das.component: api
      annotations:
        prometheus.io/port: "9102"
    spec:
      imagePullSecrets:
        - name: gcr-secret
      containers:
      - image: gcr.io/padas-app/circleci/earthranger-api:<<server-base-version>>
        name: das-api
        resources:
          requests:
            cpu: "200m"
            memory: "500Mi"
        ports:
          - containerPort: 8000
        env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: site-configmap
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: site-configmap
              key: DB_PORT
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: site-configmap
              key: DB_NAME
        - name: DB_USER
          valueFrom:
            configMapKeyRef:
              name: site-configmap
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: site-configmap
              key: DB_PASSWORD
        - name: USE_AZURE_STORAGE
          valueFrom:
            configMapKeyRef:
              name: site-configmap
              key: USE_AZURE_STORAGE
        - name: SERVICE_NAME
          value: "api_server"
        - name: STORAGE_ACCOUNT
          valueFrom:
            configMapKeyRef:
              name: site-configmap
              key: STORAGE_ACCOUNT
        - name: STORAGE_ACCOUNT_KEY
          valueFrom:
            configMapKeyRef:
              name: site-configmap
              key: STORAGE_ACCOUNT_KEY
        - name: STORAGE_CONTAINER
          valueFrom:
            configMapKeyRef:
              name: site-configmap
              key: STORAGE_CONTAINER
        - name: CONFIG_ACCOUNT
          valueFrom:
            configMapKeyRef:
              name: site-configmap
              key: CONFIG_ACCOUNT
        - name: CONFIG_ACCOUNT_KEY
          valueFrom:
            configMapKeyRef:
              name: site-configmap
              key: CONFIG_ACCOUNT_KEY
        - name: CONFIG_CONTAINER
          valueFrom:
            configMapKeyRef:
              name: site-configmap
              key: CONFIG_CONTAINER
        - name: EMAIL_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: default-configmap
              key: EMAIL_PASSWORD
        - name: EMAIL_HOST_USER
          valueFrom:
            configMapKeyRef:
              name: default-configmap
              key: EMAIL_HOST_USER
        - name: EMAIL_HOST
          valueFrom:
            configMapKeyRef:
              name: default-configmap
              key: EMAIL_HOST
        - name: FROM_EMAIL
          valueFrom:
            configMapKeyRef:
              name: default-configmap
              key: FROM_EMAIL
        - name: DEFAULT_FROM_EMAIL
          valueFrom:
            configMapKeyRef:
              name: default-configmap
              key: DEFAULT_FROM_EMAIL
        - name: KML_EXPORT
          valueFrom:
            configMapKeyRef:
              name: site-configmap
              key: KML_EXPORT
      - image: prom/statsd-exporter:v0.8.1
        name: statsd-exporter
        args: ["--statsd.listen-udp=127.0.0.1:8125"]
        ports:
        - containerPort: 9102
