apiVersion: v1
kind: ConfigMap
metadata:
  name: default-configmap
data:
  APIENDPOINT: localhost
  DB_HOST: postgis.default.svc.cluster.local
  DB_PORT: "5432"
  API_HOST: api
  API_PORT: "8000"
  EMAIL_PASSWORD: <<email-password>>
  WEB_SERVICE_NAME: <<web-service-name>>
  BUNDLE_CRT: "<<bundle-crt>>"
  PAMDAS_ORG_PRIVATE_KEY_PEM: "<<pamdas-org-ssl-key>>"
