apiVersion: apps/v1beta1
kind: Deployment
metadata:
  namespace: <<namespace>>
  name: mql
spec:
  template:
    metadata:
      labels:
        das.component: mql
      annotations:
        prometheus.io/port: "9102"
    spec:
      imagePullSecrets:
        - name: gcr-secret
      containers:
      - image: gcr.io/padas-app/mql:<<server-version>>
        name: das-mql
        resources:
          requests:
            cpu: "75m"
        env:
        - name: API_HOST
          valueFrom:
            configMapKeyRef:
              name: default-configmap
              key: API_HOST
        - name: API_PORT
          valueFrom:
            configMapKeyRef:
              name: default-configmap
              key: API_PORT
      - image: prom/statsd-exporter:v0.8.1
        name: statsd-exporter
        args: ["--statsd.listen-udp=127.0.0.1:8125"]
        ports:
        - containerPort: 9102