apiVersion: v1
kind: Service
metadata:
  name: nginx-utility
spec:
  type: LoadBalancer
  loadBalancerIP: <<nginx-utility-service-ip>>
  ports:
  - port: 9200
    targetPort: 9200
    name: elasticsearch
  - port: 5601
    targetPort: 5601
    name: kibana
  - port: 9093
    targetPort: 9093
    name: alertmanager
  - port: 9090
    targetPort: 9090
    name: prometheus
  - port: 3000
    targetPort: 3000
    name: grafana
  selector:
    component: nginx-utility
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: nginx-utility
spec:
  template:
    metadata:
      labels:
        component: nginx-utility
    spec:
      imagePullSecrets:
        - name: gcr-secret
      containers:
      - image: gcr.io/padas-app/nginx-utility:<<git-server-version>>
        name: nginx-utility
        resources:
          requests:
            cpu: "15m"
            memory: "100Mi"
        env:
        - name: SSL_SECRET
          value: "<<nginx-utility-ssl-key>>"
        - name: ELASTIC_BASIC_AUTH_PASSWORD
          value: "<<elastic-basic-auth-password>>"
