apiVersion: apps/v1beta1
kind: Deployment
metadata:
  namespace: <<namespace>>
  name: rt-api
spec:
  template:
    metadata:
      labels:
        das.component: rt-api
      annotations:
        prometheus.io/port: "9102"
    spec:
      imagePullSecrets:
        - name: gcr-secret
      containers:
      - image: gcr.io/padas-app/rt_api:<<server-version>>
        name: das-rt-api
        resources:
          requests:
            cpu: "100m"
            memory: "500Mi"
        ports:
          - containerPort: 8000
        env:
        - name: API_HOST
          valueFrom:
            configMapKeyRef:
              name: default-configmap
              key: API_HOST
        - name: API_PORT
          valueFrom:
            configMapKeyRef:
              name: default-configmap
              key: API_PORT
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: site-configmap
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: site-configmap
              key: DB_PORT
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: site-configmap
              key: DB_NAME
        - name: DB_USER
          valueFrom:
            configMapKeyRef:
              name: site-configmap
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: site-configmap
              key: DB_PASSWORD
      - image: prom/statsd-exporter:v0.8.1
        name: statsd-exporter
        args: ["--statsd.listen-udp=127.0.0.1:8125"]
        ports:
        - containerPort: 9102
