apiVersion: apps/v1beta1
kind: Deployment
metadata:
  namespace: <<namespace>>
  name: worker-analyzer
spec:
  template:
    metadata:
      labels:
        das.component: worker-analyzer
    spec:
      imagePullSecrets:
        - name: gcr-secret
      containers:
      - image: gcr.io/padas-app/worker-analyzer:<<server-version>>
        name: das-worker-analyzer
        resources:
          requests:
            cpu: "100m"
        env:
        - name: API_HOST
          valueFrom:
            configMapKeyRef:
              name: default-configmap
              key: API_HOST
        - name: API_PORT
          valueFrom:
            configMapKeyRef:
              name: default-configmap
              key: API_PORT
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: datastore-configmap
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: datastore-configmap
              key: DB_PORT
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: datastore-configmap
              key: DB_NAME
        - name: DB_USER
          valueFrom:
            configMapKeyRef:
              name: datastore-configmap
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: datastore-configmap
              key: DB_PASSWORD
