resources:
################################################################################
# 
# Resources to fetch
#
################################################################################        
# git resources
- name: git-server-base
  type: versioned-git-resource
  source:
    uri: git@github.com:PADAS/das.git
    branch: ((server-branch-name))
    paths: 
      - dependencies/* 
      - docker/base/*
    private_key: ((das-github))

- name: git-utility
  type: versioned-git-resource
  source:
    uri: git@github.com:PADAS/das.git
    branch: ((server-branch-name))
    paths: 
      - docker/PostGIS/*
      - docker/Nginx/*
      - docker/Nginx_Utility/*
    private_key: ((das-github))

- name: git-monitoring
  type: versioned-git-resource
  source:
    uri: git@github.com:PADAS/das.git
    branch: ((server-branch-name))
    paths:
      - docker/monitoring/*
    private_key: ((das-github))

- name: git-server
  type: versioned-git-resource
  source:
    uri: git@github.com:PADAS/das.git
    branch: ((server-branch-name))
    private_key: ((das-github))

- name: git-deployment
  type: versioned-git-resource
  source:
    uri: git@github.com:PADAS/das.git
    branch: ((server-branch-name))
    paths: 
      - deployment/*
    private_key: ((das-github))

- name: git-web-base
  type: versioned-git-resource
  source:
    uri: git@github.com:PADAS/das-web.git
    branch: ((web-branch-name))
    paths:
      - docker/build/base/*
    private_key: ((das-web-github))

- name: git-web-depends
  type: versioned-git-resource
  source:
    uri: git@github.com:PADAS/das-web.git
    branch: ((web-branch-name))
    paths:
      - docker/build/depends/*
      - bower.json
      - package.json
    private_key: ((das-web-github))

- name: git-web
  type: versioned-git-resource
  source:
    uri: git@github.com:PADAS/das-web.git
    branch: ((web-branch-name))
    private_key: ((das-web-github))

#base docker resources
- name: image-server-base
  type: docker-image
  source:
    tag: $(cat<git-server-base/sha)
    email: ((gcr-io-email))
    username: ((gcr-io-username))
    password: ((padas-app-container-registry-push))
    repository: gcr.io/padas-app/base

- name: image-server-app
  type: docker-image
  source:
    tag: $(cat<git-server/sha)
    email: ((gcr-io-email))
    username: ((gcr-io-username))
    password: ((padas-app-container-registry-push))
    repository: gcr.io/padas-app/app

# AIS_Gap, AIS_Track, API, Beat, MQL, RT_AIS_API, RT_API, Worker
- name: image-server-worker
  type: docker-image
  source:
    email: ((gcr-io-email))
    username: ((gcr-io-username))
    password: ((padas-app-container-registry-push))
    repository: gcr.io/padas-app/worker

- name: image-server-rt-api
  type: docker-image
  source:
    email: ((gcr-io-email))
    username: ((gcr-io-username))
    password: ((padas-app-container-registry-push))
    repository: gcr.io/padas-app/rt_api

- name: image-server-mql
  type: docker-image
  source:
    email: ((gcr-io-email))
    username: ((gcr-io-username))
    password: ((padas-app-container-registry-push))
    repository: gcr.io/padas-app/mql

- name: image-server-beat
  type: docker-image
  source:
    email: ((gcr-io-email))
    username: ((gcr-io-username))
    password: ((padas-app-container-registry-push))
    repository: gcr.io/padas-app/beat

- name: image-server-api
  type: docker-image
  source:
    email: ((gcr-io-email))
    username: ((gcr-io-username))
    password: ((padas-app-container-registry-push))
    repository: gcr.io/padas-app/api


# docker resource images not dependent on base / app
- name: image-postgis
  type: docker-image
  source:
    email: ((gcr-io-email))
    username: ((gcr-io-username))
    password: ((padas-app-container-registry-push))
    repository: gcr.io/padas-app/postgis

- name: image-nginx
  type: docker-image
  source:
    email: ((gcr-io-email))
    username: ((gcr-io-username))
    password: ((padas-app-container-registry-push))
    repository: gcr.io/padas-app/nginx

- name: image-nginx-utility
  type: docker-image
  source:
    email: ((gcr-io-email))
    username: ((gcr-io-username))
    password: ((padas-app-container-registry-push))
    repository: gcr.io/padas-app/nginx-utility

- name: image-prometheus
  type: docker-image
  source:
    email: ((gcr-io-email))
    username: ((gcr-io-username))
    password: ((padas-app-container-registry-push))
    repository: gcr.io/padas-app/utility/prometheus

- name: image-prometheus-alertmanager
  type: docker-image
  source:
    email: ((gcr-io-email))
    username: ((gcr-io-username))
    password: ((padas-app-container-registry-push))
    repository: gcr.io/padas-app/utility/prometheus-alertmanager

- name: image-grafana
  type: docker-image
  source:
    email: ((gcr-io-email))
    username: ((gcr-io-username))
    password: ((padas-app-container-registry-push))
    repository: gcr.io/padas-app/utility/grafana

# Web docker resources
- name: image-web-base
  type: docker-image
  source:
    email: ((gcr-io-email))
    username: ((gcr-io-username))
    password: ((padas-app-container-registry-push))
    repository: gcr.io/padas-app/web/build/base

- name: image-web-depends
  type: docker-image
  source:
    tag: $(cat<git-web-depends/sha)
    email: ((gcr-io-email))
    username: ((gcr-io-username))
    password: ((padas-app-container-registry-push))
    repository: gcr.io/padas-app/web/build/depends
    
- name: image-web-develop
  type: docker-image
  source:
    tag: $(cat<git-web/sha)
    email: ((gcr-io-email))
    username: ((gcr-io-username))
    password: ((padas-app-container-registry-push))
    repository: gcr.io/padas-app/web/develop

- name: image-web-app
  type: docker-image
  source:
    email: ((gcr-io-email))
    username: ((gcr-io-username))
    password: ((padas-app-container-registry-push))
    repository: gcr.io/padas-app/web/app

- name: slack-alert
  type: slack-notification
  source:
    url: ((slack-webhook-url-concourse))


################################################################################
# 
# Custom Resource Types
#
################################################################################
resource_types:
- name: versioned-git-resource
  type: docker-image
  source:
    email: ((gcr-io-email))
    username: ((gcr-io-username))
    password: ((ss-infrastructure-container-registry-pull))
    repository: gcr.io/ss-infrastructure/concourse/versioned-git-resource

- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
    tag: v1.2.0

################################################################################
# 
# Jobs to run
#
################################################################################
jobs:  
- name: docker-build-server-base
  plan:
  - get: git-server-base
    trigger: true
  - put: image-server-base
    params: {
      build: git-server-base,
      dockerfile: git-server-base/docker/base/Dockerfile,
      tag:  git-server-base/sha,
      tag_as_latest: ((tag-as-latest))
    }
    get_params: {skip_download: true}

- name: docker-build-server-app
  plan:
  - aggregate:
    - get: git-server-base
      passed: [docker-build-server-base]
    - get: image-server-base
      passed: [docker-build-server-base]
      trigger: true
      params: {
        skip_download: true
      }
    - get: git-server
      trigger: true
  - put: image-server-app
    params: {
      build: git-server,
      dockerfile: git-server/docker/App/Dockerfile,
      tag:  git-server/sha,
      build_args_file: git-server-base/build_args,
      tag_as_latest: ((tag-as-latest))
    }
    get_params: {skip_download: true}

# API, Beat, MQL, RT_AIS_API, RT_API, Worker
- name: docker-build-server
  plan:
  - aggregate:
    - get: git-server
      trigger: true
      passed: [docker-build-server-app]
    - get: image-server-app
      trigger: true
      passed: [docker-build-server-app]
      params: {
        skip_download: true
      }
  - aggregate:
    - put: image-server-api
      params: { build: git-server/docker/API, tag: git-server/sha, build_args_file: git-server/build_args, tag_as_latest: ((tag-as-latest)) }
      get_params: {skip_download: true}
    - put: image-server-beat
      params: { build: git-server/docker/Beat, tag: git-server/sha, build_args_file: git-server/build_args, tag_as_latest: ((tag-as-latest)) }
      get_params: {skip_download: true}
    - put: image-server-mql
      params: { build: git-server/docker/MQL, tag: git-server/sha, build_args_file: git-server/build_args, tag_as_latest: ((tag-as-latest)) }
      get_params: {skip_download: true}
    - put: image-server-rt-api
      params: { build: git-server/docker/RT_API, tag: git-server/sha, build_args_file: git-server/build_args, tag_as_latest: ((tag-as-latest)) }
      get_params: {skip_download: true}
    - put: image-server-worker
      params: { build: git-server/docker/Worker, tag: git-server/sha, build_args_file: git-server/build_args, tag_as_latest: ((tag-as-latest)) }
      get_params: {skip_download: true}

- name: docker-build-utility
  plan:
  - get: git-utility
    trigger: true
  - aggregate: 
    - put: image-postgis
      params: { build: git-utility/docker/PostGIS, tag: git-utility/sha, tag_as_latest: ((tag-as-latest)) }
      get_params: {skip_download: true}
    - put: image-nginx
      params: { build: git-utility/docker/Nginx, tag: git-utility/sha, tag_as_latest: ((tag-as-latest)) }
      get_params: {skip_download: true}
    - put: image-nginx-utility
      params: { build: git-utility/docker/Nginx_Utility, tag: git-utility/sha, tag_as_latest: ((tag-as-latest)) }
      get_params: {skip_download: true}

- name: docker-build-monitoring
  plan:
  - do:
    - get: git-monitoring
      trigger: true
    - aggregate:
      - put: image-grafana
        params: {
          build: git-monitoring/docker/monitoring/grafana,
          tag_as_latest: ((tag-as-latest)),
          tag: git-monitoring/sha
        }
        get_params: {skip_download: true}
      - put: image-prometheus
        params: {
          build: git-monitoring/docker/monitoring/prometheus,
          tag_as_latest: ((tag-as-latest)),
          tag: git-monitoring/sha
        }
        get_params: {skip_download: true}
      - put: image-prometheus-alertmanager
        params: {
          build: git-monitoring/docker/monitoring/prometheus-alertmanager,
          tag_as_latest: ((tag-as-latest)),
          tag: git-monitoring/sha
        }
        get_params: {skip_download: true}
    on_failure:
      do:
      - put: slack-alert
        params:
          channel: ((slack-notification-channel))
          text: |
            :warning: $BUILD_PIPELINE_NAME job $BUILD_JOB_NAME failed
            $ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME

# Web Jobs
- name: docker-build-web-base
  serial: true
  plan:
  - get: git-web-base
    trigger: true
  - put: image-web-base
    params: {
      build: git-web-base,
      dockerfile: git-web-base/docker/build/base/Dockerfile,
      tag:  git-web-base/sha,
      tag_as_latest: ((tag-as-latest))
    }        
    get_params: {skip_download: true}

- name: docker-build-web-depends
  serial: true
  plan:
  - aggregate:
    - get: image-web-base
      passed: [docker-build-web-base]
      trigger: true
      params: { skip_download: true }
    - get: git-web-base
      passed: [docker-build-web-base]
    - get: git-web-depends
      trigger: true
  - put: image-web-depends
    params: {
      build: git-web-depends,
      dockerfile: git-web-depends/docker/build/depends/Dockerfile,
      tag:  git-web-depends/sha,
      build_args_file: git-web-base/build_args,
      tag_as_latest: ((tag-as-latest))
    }
    get_params: {skip_download: true}

- name: test-web-unit
  serial: true
  plan:
  - aggregate:
    - get: image-web-depends
      passed: [docker-build-web-depends]
      trigger: true
      params: { save: true }
    - get: git-web-depends
      passed: [docker-build-web-depends]
    - get: git-web
      trigger: true
  - task: test
    image: image-web-depends
    config:
      platform: linux      
      inputs:
      - name: git-web
      run:
        dir: git-web
        path: docker/build/compile/test.sh

- name: docker-build-web-develop
  serial: true
  plan:
  - aggregate:
    - get: image-web-depends
      passed: [test-web-unit]
      trigger: true
      params: { skip_download: true }
    - get: git-web-depends
      passed: [test-web-unit]
    - get: git-web
      passed: [test-web-unit]
      trigger: true
  - put: image-web-develop
    params: {
      build: git-web,
      dockerfile: git-web/docker/develop/Dockerfile,
      tag:  git-web/sha,
      tag_as_latest: ((tag-as-latest)),
      build_args_file: git-web-depends/build_args
    }
    get_params: {skip_download: true}

- name: docker-build-web-app
  serial: true
  plan:
  - aggregate:
    - get: image-web-depends
      passed: [test-web-unit]
      trigger: true
    - get: git-web
      passed: [test-web-unit]
      trigger: true
  - task: build
    image: image-web-depends
    config:
      platform: linux
      inputs:
      - name: git-web
      outputs: 
      - name: web-distribution
      run:
        dir: git-web
        path: docker/build/compile/build.sh
  - put: image-web-app
    params: {
      build: web-distribution,
      dockerfile: web-distribution/docker/app/Dockerfile,
      tag:  git-web/sha,
      tag_as_latest: ((tag-as-latest)),
    }
    get_params: {skip_download: true}


- name: deploy-to-k8s
  serial: true
  plan:
    - aggregate:
      - get: git-utility
        passed: [docker-build-utility]
      - get: git-web
        passed: [docker-build-web-app]
      - get: git-server
        passed: [docker-build-server]
      - get: git-deployment
        trigger: true
      - get: git-monitoring
        passed: [docker-build-monitoring]
      - get: image-server-api
        passed: [docker-build-server]
        trigger: true
        params: {skip_download: true}
      - get: image-server-mql
        passed: [docker-build-server]
        trigger: true
        params: {skip_download: true}
      - get: image-server-beat
        passed: [docker-build-server]
        trigger: true
        params: {skip_download: true}
      - get: image-server-rt-api
        passed: [docker-build-server]
        trigger: true
        params: {skip_download: true}
      - get: image-server-worker
        passed: [docker-build-server]
        trigger: true
        params: {skip_download: true}
      - get: image-nginx
        passed: [docker-build-utility]
        trigger: true
        params: {skip_download: true}
      - get: image-postgis
        passed: [docker-build-utility]
        trigger: true
        params: {skip_download: true}
      - get: image-grafana
        passed: [docker-build-monitoring]
        trigger: true
        params: {skip_download: true}
      - get: image-prometheus
        passed: [docker-build-monitoring]
        trigger: true
        params: {skip_download: true}
      - get: image-prometheus-alertmanager
        passed: [docker-build-monitoring]
        trigger: true
        params: {skip_download: true}
      - get: image-web-app
        passed: [docker-build-web-app]
        trigger: true
        params: {skip_download: true}
    - do:
      - task: ensure-disks-exist
        config:
          platform: linux
          image_resource:
            type: docker-image
            source: {
              repository: gcr.io/ss-infrastructure-public/platform/tools,
              tag: ((vp-tools-container-version)),
            }
          inputs:
          - name: git-deployment
          params: {
            PROJECT: padas-app,
            SERVICE_ACCOUNT_KEY: ((padas-app-boshprovisioner)),
            USERNAME: ((creator)),
            ELASTIC_URL: ((elastic-url)),
            BUILD_PIPELINE_NAME: ((pipeline-name))
          }
          run:
            path: /vulcan-platform-tools/run/run.with.gcloud.service.account.sh
            args:
            - vcloud
            - disks
            - create
            - git-deployment/deployment/storage/default.disks.csv
            - --prefix=((cluster-name))
            - --zone=((gcp-compute-zone))
            - --iaas=gcp
            - --workspace=((iaas-workspace))
            - --type=ssd
      - task: ensure-cluster-exists
        config:
          platform: linux
          image_resource:
            type: docker-image
            source: {
              repository: gcr.io/ss-infrastructure-public/platform/tools,
              tag: ((vp-tools-container-version)),
            }
          inputs:
          - name: git-deployment
          params: {
            PROJECT: padas-app,
            SERVICE_ACCOUNT_KEY: ((padas-app-cluster-admin)),
            USERNAME: ((creator)),
            VAULT_TOKEN: ((vault-automation-token)),
            VAULT_ADDR: ((vault-address)),
            ELASTIC_URL: ((elastic-url))
          }
          run:
            path: /vulcan-platform-tools/run/run.with.gcloud.service.account.sh
            args:
            - vcloud
            - clusters
            - create
            - git-deployment/((cluster-spec))
            - --name=((cluster-name))
            - --zone=((gcp-compute-zone))
            - --iaas=gcp
            - --workspace=((iaas-workspace))
      - task: create-deployment-plan
        config:
          platform: linux
          image_resource:
            type: docker-image
            source: {
              repository: gcr.io/ss-infrastructure-public/platform/tools,
              tag: ((vp-tools-container-version)),
            }
          inputs:
          - name: git-utility
          - name: git-web
          - name: git-server
          - name: git-deployment
          params: {
            PROJECT: padas-app,
            USERNAME: ((creator)),
            VAULT_TOKEN: ((vault-automation-token)),
            VAULT_ADDR: ((vault-address)),
            ELASTIC_URL: ((elastic-url)),
            VCLOUD_SERVICE_URL: ((vcloud-service-url))
          }
          run:
            path: /bin/bash
            args:
            - vcloud
            - deployment-plans
            - create
            - git-deployment/deployment/default-deployment-plan-spec.yaml
            - --series=((cluster-name))
      - task: deploy
        config:
          platform: linux
          image_resource:
            type: docker-image
            source: {
              repository: gcr.io/ss-infrastructure-public/platform/tools,
              tag: ((vp-tools-container-version)),
            }
          inputs:
          - name: git-deployment
          params: {
            PROJECT: padas-app,
            SERVICE_ACCOUNT_KEY: ((padas-app-cluster-admin)),
            USERNAME: ((creator)),
            VAULT_TOKEN: ((vault-automation-token)),
            VAULT_ADDR: ((vault-address)),
            ELASTIC_URL: ((elastic-url)),
            VCLOUD_SERVICE_URL: ((vcloud-service-url)),
            STATIC_IP: ((static-ip))
          }
          run:
            path: /vulcan-platform-tools/run/run.with.gcloud.service.account.sh
            args:
            - exec
            - |
              vcloud clusters deploy 
              git-deployment/deployment/components
              --params-file git-deployment/deployment/params/((deploy-params-environment)).params.yaml 
              --name ((cluster-name)) 
              --workspace ((iaas-workspace)) 
              --iaas gcp 
              --zone ((gcp-compute-zone)) 
              --plan ((cluster-name))
