version: 2
updates:
  - package-ecosystem: "uv"
    directory: "/"
    target-branch: "develop"
    schedule:
      interval: "weekly"
      day: "monday"
    ignore:
      - dependency-name: "*"
        update-types: ["semver-minor", "semver-patch"]
    open-pull-requests-limit: 5
    reviewers:
      - "chrisj-er"
