version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/das/dependencies"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5
    reviewers:
      - "chrisdoehring"
      - "chrisj-er"
      - "juanearthranger"
