"""
Django settings for das project.

Generated by 'django-admin startproject' using Django 1.8.2.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os
import sys

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'j(h&tc(u_#z-tf)u(9+3n39gmk92#6-v-he_p0ae+1rs*+2j@b'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False
# running in development mode
DEV = False

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = (
    'accounts.apps.AccountsConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.gis',
    'django_ses',
    #'django.contrib.sites',
    'treebeard',
    'corsheaders',
    'oauth2_provider',
    'rest_framework',
    'rest_framework_swagger',
    'djgeojson',
    'raster',
    'observations',
    'analyzers',
    'das_server',
    'tracking',
    'mapping.apps.MappingConfig',
    'activity',
    'rt_api.apps.RTAPIConfig'
)

MIDDLEWARE_CLASSES = (
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'corsheaders.middleware.CorsPostCsrfMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'oauth2_provider.middleware.OAuth2TokenMiddleware',
    'revision.middleware.RevisionMiddleware',
    #'django.contrib.sites.middleware.CurrentSiteMiddleware',
)

ROOT_URLCONF = 'das_server.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR, 'das_server'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

AUTH_USER_MODEL = 'accounts.User'
WSGI_APPLICATION = 'das_server.wsgi.application'

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 9,
        }
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': (
        #'rest_framework.permissions.DjangoModelPermissionsOrAnonReadOnly',
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'oauth2_provider.ext.rest_framework.OAuth2Authentication',
        'utils.drf.SuperUserSessionAuthentication',
    ),
    #'VIEW_DESCRIPTION_FUNCTION': 'rest_framework_swagger.views.get_restructuredtext',
    'DEFAULT_RENDERER_CLASSES': (
        'utils.json.ExtendedJSONRenderer',
        'utils.json.ExtendedBrowsableAPIRenderer',
    ),
    'EXCEPTION_HANDLER': 'utils.drf.api_exception_handler',
    'TEST_REQUEST_DEFAULT_FORMAT': 'json',
    #'DEFAULT_VERSIONING_CLASS': 'rest_framework.versioning.NamespaceVersioning',
    #'DEFAULT_VERSION': 'v1.0',
}

AUTHENTICATION_BACKENDS = (
    'oauth2_provider.backends.OAuth2Backend',
    'accounts.backends.AccountsModelBackend',

)

SERIALIZATION_MODULES = {
    'geojson' : 'djgeojson.serializers'
}

# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases
# we use postgis, create the db from the spatial db template
# createdb -T template_postgis das ENCODING 'utf8';
DATABASES = {
    'default': {
        'ENGINE': 'django.contrib.gis.db.backends.postgis',
        'NAME': 'das',
        'USER': 'postgres',
    }
}


LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'syslog': {
            'format': 'mw %(levelname)s %(processName)s %(thread)d %(name)s %(message)s'
        },
        'simple': {
            'format': '%(asctime)s mw %(levelname)s %(processName)s %(thread)d %(name)s %(message)s'
        },
    },
    'handlers': {
        # 'syslog': {
        #     'level': 'INFO',
        #     'class': 'logging.handlers.SysLogHandler',
        #     'address': '/dev/log',
        #     'facility': SysLogHandler.LOG_USER,
        #     'formatter': 'syslog'
        # },
        'file': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'filename': '/tmp/das.log',
            'formatter': 'simple'
        },
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'stream': sys.stdout,
            'formatter': 'simple'
        },
    },
    'loggers': {
        'django': {
            'handlers': ['file'],
            'propagate': True,
            'level': 'INFO',
        },
        'das_server': {
            'handlers': ['file'],
            'level': 'INFO',
        },
        'utils': {
            'handlers': ['file'],
            'level': 'INFO',
        },
        'observations': {
            'handlers': ['file'],
            'level': 'INFO',
        },
        'mapping': {
            'handlers': ['file'],
            'level': 'INFO',
        },
        'tracking': {
            'handlers': ['file'],
            'level': 'DEBUG',
        },
        'activity': {
            'handlers': ['file'],
            'level': 'DEBUG',
        },
        'rt_api': {
            'handlers': ['file'],
            'level': 'DEBUG',
        }
    }
}

# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'en-us'

USE_I18N = True
USE_L10N = True

USE_TZ = True
TIME_ZONE = 'UTC'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, "www", "static")
STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'observations'),
    os.path.join(BASE_DIR, 'mapping'),
    os.path.join(BASE_DIR, 'rt_api')
)

SITE_ID = 1

#socket.io uses the CORS_ORIGIN_WHITELIST as well
#caveat is that socket.io matches against the whole ORIGIN ie: http://localhost
# CORS_ALLOW_CREDENTIALS = True
# CORS_ORIGIN_ALLOW_ALL = False
# CORS_ORIGIN_WHITELIST = (
#     )
# CORS_REPLACE_HTTPS_REFERER = True

SWAGGER_SETTINGS = {
    'api_version': 'v1.0',
    'api_path': '/',
    'enabled_methods': [
        'get',
        'post',
        'put',
        'patch',
        'delete'
    ],
    'doc_expansion': 'None',
    'exclude_namespaces': [],
    #'is_authenticated': True,
    #'is_superuser': True,
    'info': {
        'contact': 'guest@test.com',
        'description': 'DAS Server',
        'license': '',
        'licenseUrl': '',
        'termsOfServiceUrl': '',
        'title': 'DAS Server API',
    }
}

OAUTH2_PROVIDER = {'ACCESS_TOKEN_EXPIRE_SECONDS': 3600*48}

#RT API settings
ASYNC_MODE = 'eventlet'

#override these if your libraries are in a different place
GEOS_LIBRARY_PATH = '/usr/local/lib/libgeos_c.so'
GDAL_LIBRARY_PATH = '/usr/lib/libgdal.so'

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.filebased.FileBasedCache',
        'LOCATION': '/tmp/django_cache',
    }
}

RASTER_WORKDIR = '/tmp/raster'

'''
Associate a plugin name with a plugin-configuration dict that will override the plugin's configuration in the database.
'''
DATA_INPUT_PLUGINS = {
}

#would want to set this to where you might have some MBTiles maps
MAPPING = {'MBTILES': {'root': r'\tmp',}}

REALTIME_BROKER_URL = 'redis://localhost:6379/2'
PUBSUB_BROKER_URL = 'redis://localhost:6379/1'

EMAIL_BACKEND = 'django_ses.SESBackend'
# can use console output for email in dev
# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
AWS_SES_REGION_NAME = 'us-west-2'
AWS_SES_REGION_ENDPOINT = 'email.us-west-2.amazonaws.com'

# the address to send notification emails from
FROM_EMAIL = 'notifications@pamdas.org'
