"""
Django settings for das project.

Generated by 'django-admin startproject' using Django 1.8.2.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os
import logging
import sys
from logging.handlers import SysLogHandler

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'j(h&tc(u_#z-tf)u(9+3n39gmk92#6-v-he_p0ae+1rs*+2j@b'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.gis',
    #'django.contrib.sites',
    'corsheaders',
    'oauth2_provider',
    'rest_framework',
    'rest_framework_swagger',
    'djgeojson',
    'raster',
    'observations',
    'api',
    'data_input',
    'mapping',
)

MIDDLEWARE_CLASSES = (
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'oauth2_provider.middleware.OAuth2TokenMiddleware',
    #'django.contrib.sites.middleware.CurrentSiteMiddleware',
)

ROOT_URLCONF = 'das_server.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR,],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

#AUTH_USER_MODEL = 'django.contrib.auth.models.User'
WSGI_APPLICATION = 'das_server.wsgi.application'

REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': (
        #'rest_framework.permissions.DjangoModelPermissionsOrAnonReadOnly',
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'api.auth.SuperUserSessionAuthentication',
        'oauth2_provider.ext.rest_framework.OAuth2Authentication',
    ),
    #'VIEW_DESCRIPTION_FUNCTION': 'rest_framework_swagger.views.get_restructuredtext',
    'DEFAULT_RENDERER_CLASSES': (
        'das_utils.json.ExtendedJSONRenderer',
        'das_utils.json.ExtendedBrowsableAPIRenderer',
    ),
    'EXCEPTION_HANDLER': 'das.api.views.api_exception_handler',
}

AUTHENTICATION_BACKENDS = (
    'oauth2_provider.backends.OAuth2Backend',
    # Uncomment following if you want to access the admin
    'django.contrib.auth.backends.ModelBackend',

)

# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases
# we use postgis, create the db from the spatial db template
# createdb -T template_postgis das ENCODING 'utf8';
DATABASES = {
    'default': {
        'ENGINE': 'django.contrib.gis.db.backends.postgis',
        'NAME': 'das',
        'USER': 'postgres',
    }
}

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'syslog': {
            'format': 'mw %(levelname)s %(processName)s %(thread)d %(name)s %(message)s'
        },
        'simple': {
            'format': '%(asctime)s mw %(levelname)s %(processName)s %(thread)d %(name)s %(message)s'
        },
    },
    'handlers': {
        # 'syslog': {
        #     'level': 'INFO',
        #     'class': 'logging.handlers.SysLogHandler',
        #     'address': '/dev/log',
        #     'facility': SysLogHandler.LOG_USER,
        #     'formatter': 'syslog'
        # },
        'file': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'filename': '/tmp/das.log',
            'formatter': 'simple'
        },
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'stream': sys.stdout,
            'formatter': 'simple'
        },
        'data_input_file':{
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'filename': '/tmp/das-data_input.log',
            'formatter': 'simple'
        }
    },
    'loggers': {
        'django': {
            'handlers': ['file'],
            'propagate': True,
            'level': 'INFO',
        },
        'observations': {
            'handlers': ['file'],
            'level': 'INFO',
        },
        'api': {
            'handlers': ['file'],
            'level': 'INFO',
        },
        'data_input': {
            'handlers': ['data_input_file'],
            'level': 'DEBUG'
        },
        'apscheduler': {
            'handlers': ['data_input_file', 'console'],
            'level': 'INFO'
        }
    }
}

# django-secure
# SECURE_FRAME_DENY = True
# SECURE_CONTENT_TYPE_NOSNIFF = True
# SECURE_BROWSER_XSS_FILTER = True
# SECURE_SSL_REDIRECT = True
# SESSION_COOKIE_SECURE = True
# SESSION_COOKIE_HTTPONLY = True
# SECURE_HSTS_SECONDS = 3600
# SECURE_HSTS_INCLUDE_SUBDOMAINS = True

# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'en-us'

USE_I18N = True
USE_L10N = True

USE_TZ = True
TIME_ZONE = 'UTC'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, "www", "static")
STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'api', 'static'),
    os.path.join(BASE_DIR, 'mapping', 'static')
)

SITE_ID = 1

#CORS_URLS_REGEX = r'^/api/.*$'

# SCHEDULER = {
#     'db_url': 'postgres://postgres:postgres@localhost:5432/dasdb',
#     'executors': {
#         'default': {'type': 'threadpool', 'max_workers': 20},
#         'processpool': {'type': 'processpool', 'max_workers': 4},
#     },
#     'job_defaults': {
#         'coalesce': False,
#         'max_instances': 3
#     }
#
# }

SWAGGER_SETTINGS = {
    'api_version': 'v1.0',
    'api_path': '/',
    'enabled_methods': [
        'get',
        'post',
        'put',
        'patch',
        'delete'
    ],
    'doc_expansion': 'None',
    'exclude_namespaces': [],
    #'is_authenticated': True,
    #'is_superuser': True,
    'info': {
        'contact': 'guest@test.com',
        'description': 'DAS Server',
        'license': '',
        'licenseUrl': '',
        'termsOfServiceUrl': '',
        'title': 'DAS Server API',
    }
}

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.filebased.FileBasedCache',
        'LOCATION': '/tmp/django_cache',
    }
}

'''
Associate a plugin name with a plugin-configuration dict that will override the plugin's configuration in the database.
'''
DATA_INPUT_PLUGINS = {
}
