apiVersion: "v1"
kind: "PersistentVolume"
metadata:
  annotations:
      volume.beta.kubernetes.io/mount-options: "discard"
  name: alertmanager
  labels:
    component: alertmanager
spec:
  capacity:
    storage: "20Gi"
  accessModes:
    - "ReadWriteOnce"
  persistentVolumeReclaimPolicy: Retain
  storageClassName: "<<persistentvolume-storage-class>>"
  azureDisk:
    kind: Managed
    diskURI: "/subscriptions/<<azure-subscription-id>>/resourceGroups/<<iaas-workspace>>/providers/Microsoft.Compute/disks/<<disk-namespace>>-alertmanager-0"
    diskName: "<<cluster-name>>-alertmanager-0"
  gcePersistentDisk:
    fsType: "ext4"
    pdName: "<<cluster-name>>-alertmanager-0"
