apiVersion: "v1"
kind: "PersistentVolume"
metadata:
  annotations:
      volume.beta.kubernetes.io/mount-options: "discard"
  name: elasticsearch
  labels:
    component: elasticsearch
spec:
  capacity:
    storage: "50Gi"
  accessModes:
    - "ReadWriteOnce"
  persistentVolumeReclaimPolicy: Retain
  storageClassName: "azure"
  azureDisk:
    kind: Managed
    diskURI: "/subscriptions/<<azure-subscription-id>>/resourceGroups/<<iaas-workspace>>/providers/Microsoft.Compute/disks/<<disk-namespace>>-elastic-search-data-0"
    diskName: "<<cluster-name>>-elastic-search-data-0"
