version: "3.2"

services:
  load_initial_data:
    image: gcr.io/padas-app/circleci/das-server/develop:latest
    container_name: das_load_initial_data
    env_file: .env
    environment:
      - SERVICE_NAME=load_initial_data
    links:
      - postgis
      - redis
    depends_on:
      - rt-api
