version: "3.2"

services:

  notebook:
    image: gcr.io/padas-app/circleci/earthranger-api
    container_name: das_notebook
    env_file: .env
    environment:
      - SERVICE_NAME=notebook_server
    links:
      - postgis
      - redis
    ports:
      - 9888:8888
    volumes:
      - ../PyMET:/var/www/pymet
      - user-uploads:/user-uploads
      - ./das:/var/www/app
      - ${DAS_NOTEBOOKS_DIR:-notebooks}:/var/notebooks
