version: "3.2"

services:
  nginx:
    build:
      context: ./docker/Nginx
      
  earthranger-api:
    image: gcr.io/padas-app/circleci/earthranger-api:${DAS_TAG:-develop}
    build:
      context: ./docker/

  postgis:
    build:
      context: docker/PostGIS

