version: "3.2"

# These are service declarations for building the das-web project (at relative-path ../das-web/).
# These services mimic what's declared in the ../das-web/compose-build.yml file.
#
# Why would you want to add this file to your compose declarations?
# This allows you to build das-web and run it within the same docker-compose network environment where it will
# be accesed through Nginx just like all the other services.
#
# The soup-to-nuts case is this:
# Within the PADAS/das directory, run this:
#
# docker-compose -f docker-compose.yml -f compose-dev.yml -f compose-build.yml -f compose-build-web.yml build
#
# docker-compose -f docker-compose.yml -f compose-dev.yml -f compose-build.yml -f compose-build-web.yml up -d
#
services:

  web:
    #env_file: $PWD/../das-web-react/.env
    ports:
      - 3000:3000
    build:
      context: $PWD/../das-web-react/
      dockerfile: $PWD/../das-web-react/Dockerfile.dev
    volumes:
      - /app/node_modules
      - $PWD/../das-web-react:/app
#    volumes:
#      - $PWD/../das-web-react:/var/www/app

#  reactapp:
#    container_name: das_reactapp
#    env_file: .reactapp.env
#    build:
#      context: $PWD/../das-react-admin/
#      dockerfile: Dockerfile.dev
