version: "3.2"

services:

#  api:
#    volumes:
#      - ./das:/var/www/app
#      - ./dependencies:/workspace/dependencies
#    ports:
#      - 5400:5400
#      - 9100:8000
#
#  rt-api:
#    volumes:
#      - ./das:/var/www/app
#      - ./dependencies:/workspace/dependencies
#
#  mql:
#    volumes:
#      - ./das:/var/www/app
#      - ./dependencies:/workspace/dependencies
#
#  worker:
#    volumes:
#      - ./das:/var/www/app
#      - ./dependencies:/workspace/dependencies
#
#  worker-rt:
#    volumes:
#      - ./das:/var/www/app
#      - ./dependencies:/workspace/dependencies
#
#  worker-analyzer:
#    volumes:
#      - ./das:/var/www/app
#      - ./dependencies:/workspace/dependencies
#
#  beat:
#    volumes:
#      - ./das:/var/www/app
#      - ./dependencies:/workspace/dependencies

  postgis:
    volumes:
      - ${DAS_POSTGRES_DATA:-pgdata}:/var/lib/postgresql/data/das
    ports:
      - 6432:5432

