version: "3.2"

# These are service declarations for building the das-web project (at relative-path ../das-web/).
# These services mimic what's declared in the ../das-web/compose-build.yml file.
#
# Why would you want to add this file to your compose declarations?
# This allows you to build das-web and run it within the same docker-compose network environment where it will
# be accesed through Nginx just like all the other services.
#
# The soup-to-nuts case is this:
# Within the PADAS/das directory, run this:
#
# docker-compose -f docker-compose.yml -f compose-dev.yml -f compose-build.yml -f compose-build-web.yml build
#
# docker-compose -f docker-compose.yml -f compose-dev.yml -f compose-build.yml -f compose-build-web.yml up -d
#
services:

  web-base:
    build:
      context: $PWD/../das-web/
      dockerfile: docker/build/base/Dockerfile

  web-depends:
    build:
      context: $PWD/../das-web/
      dockerfile: docker/build/depends/Dockerfile
    depends_on:
      - web-base

  web:
    env_file: ../das-web/.env
    ports:
      - 9000:9000
    build:
      context: $PWD/../das-web/
      dockerfile: docker/develop/Dockerfile
    depends_on:
      - web-depends
    volumes:
      - ../das-web:/var/www/app


