version: "3.2"

services:

  api:
    volumes:
      - ./das:/var/www/app
      - ./dependencies:/workspace/dependencies
      - ./docker/base/wait_for.sh:/startup/wait_for.sh
      - ./docker/API/start.sh:/var/www/app/start.sh
    ports:
      - 5400:5400
      - 9100:8000

  rt-api:
    volumes:
      - ./das:/var/www/app
      - ./dependencies:/workspace/dependencies
      - ./docker/base/wait_for.sh:/startup/wait_for.sh
      - ./docker/RT_API/start.sh:/var/www/app/start.sh

  mql:
    volumes:
      - ./das:/var/www/app
      - ./dependencies:/workspace/dependencies
      - ./docker/base/wait_for.sh:/startup/wait_for.sh
      - ./docker/MQL/start.sh:/var/www/app/start.sh

  worker:
    volumes:
      - ./das:/var/www/app
      - ./dependencies:/workspace/dependencies
      - ./docker/base/wait_for.sh:/startup/wait_for.sh
      - ./docker/Worker/start.sh:/var/www/app/start.sh

  beat:
    volumes:
      - ./das:/var/www/app
      - ./dependencies:/workspace/dependencies
      - ./docker/base/wait_for.sh:/startup/wait_for.sh
      - ./docker/Beat/start.sh:/var/www/app/start.sh

  postgis:
    volumes:
      - ${DAS_POSTGRES_DATA:-pgdata}:/var/lib/postgresql/data/das
    ports:
      - 6432:5432

