upstream app_server {
  server das_api:8000;
}
upstream rt_app_server{
  server das_rt_api:8000;
}


server {
    listen 80;

    #access_log /var/log/das/access.log;
    #error_log /var/log/das/error.log;

    server_name _;
    return 301 https://$host$request_uri;
}

server {
  listen 8000;

  server_name  $hostname localhost;

  add_header 'Access-Control-Expose-Headers' 'x-das-download-filename';
  client_max_body_size 50m;

  #access_log  /var/log/das/access.log;
  #error_log /var/log/das/error.log;
  #root /var/www/das/das/das/www;
  index index.html index.htm;

  #location ~^/(app|assets|bower_compenents|static|robots.txt|favicon.ico|index.html|docs|version.txt) {
  #  root   /var/www/das/das/das/www;
  #}
  #location /media/user-uploads/ {
  #  alias   /var/media/user-uploads/;
  #}
  #location ~^/(login|logout|qa|page-speed) {
  #  alias /var/www/das/das/das/www/;
  #  try_files $uri /index.html =404;
  #}
  #location / {
  #  index  index.html index.htm;
  #}
  location /socket.io {
    proxy_pass http://rt_app_server/socket.io;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
  }
  location / {
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header Host $http_host;
    proxy_redirect off;
    proxy_set_header   X-Real-IP $remote_addr;
    proxy_set_header   X-Forwarded-Host $server_name;

    proxy_pass http://app_server;
  }

}