version: "3"

services:
  web:
    image: das/web
    container_name: das_web
    build:
      context: ./das-web
      dockerfile: docker/Dockerfile
    links: 
      - api
    ports:
      - 9000:9000
    volumes: 
      - ./das-web:/var/www/das

  api:
    image: das/server
    container_name: das_api
    build:
      context: ./das
      dockerfile: docker/API/Dockerfile
    links:
      - postgis
      - redis
    ports:
      - 8000:8000
    volumes: 
      - ./das/das:/var/www/das
      - ./das/dependencies:/workspace/dependencies

  postgis:
    image: das/postgis
    container_name: das_postgis
    build:
      context: ./das
      dockerfile: docker/PostGIS/Dockerfile

  redis:
    image: redis
    container_name: das_redis