version: "3.2"

services:
  web:
    image: gcr.io/padas-app/web/app
    container_name: das_web
    env_file: .env

  nginx:
    image: gcr.io/padas-app/nginx
    container_name: das_nginx
#    links:
#      - api
#      - rt-api
#      - web
#      - reactapp
    ports:
      - 8000:8000
      - '35729:35729'

  api:
    image: gcr.io/padas-app/circleci/earthranger-api
    container_name: das_api
    env_file: .env
    environment:
      - SERVICE_NAME=api_server
    links:
      - postgis
      - redis
    volumes:
      - user-uploads:/user-uploads
      - www-static:/var/www/static
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:8000/api/v1.0/status']
      interval: 30s
      timeout: 1s
      retries: 5

#  rt-api:
#    image: gcr.io/padas-app/rt_api
#    container_name: das_rt_api
#    env_file: .env
#    links:
#      - postgis
#      - redis
#    depends_on:
#      - api
#
#  mql:
#    image: gcr.io/padas-app/mql
#    container_name: das_mql
#    env_file: .env
#    links:
#      - postgis
#      - redis
#    depends_on:
#      - rt-api
#
#  worker:
#    image: gcr.io/padas-app/worker
#    container_name: das_worker
#    env_file: .env
#    links:
#      - postgis
#      - redis
#    depends_on:
#      - rt-api
#    volumes:
#      - user-uploads:/user-uploads
#      - www-static:/var/www/static
#
#  worker-rt:
#    image: gcr.io/padas-app/worker-rt
#    container_name: das_worker_rt
#    env_file: .env
#    links:
#      - postgis
#      - redis
#    depends_on:
#      - rt-api
#    volumes:
#      - user-uploads:/user-uploads
#      - www-static:/var/www/static
#
#  worker-analyzer:
#    image: gcr.io/padas-app/worker-analyzer
#    container_name: das_worker_analyzer
#    env_file: .env
#    links:
#      - postgis
#      - redis
#    depends_on:
#      - rt-api
#    volumes:
#      - user-uploads:/user-uploads
#      - www-static:/var/www/static
#
#  beat:
#    image: gcr.io/padas-app/beat
#    container_name: das_beat
#    env_file: .env
#    links:
#      - postgis
#      - redis
#    depends_on:
#      - rt-api

  postgis:
    image: gcr.io/padas-app/postgis
    container_name: das_postgis
    volumes:
      - pgdata:/var/lib/postgresql/data/das

  redis:
    image: redis
    container_name: das_redis
    ports:
      - 6379:6379

volumes:
  pgdata:
  notebooks:
  user-uploads:
  www-static:
