apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-configmap
data:
  config.yaml: |-
    global:
      slack_api_url: "<<alerts-slack-url>>"

    route:
      group_by: [environment, alertname, app]
      receiver: alert-slack
      routes:
      - match:
          severity: none
        receiver: silent-receiver

    inhibit_rules:
    - source_match:
        severity: 'critical'
      target_match:
        severity: 'warning'
      # Apply inhibition if the alertname is the same.
      equal: ['alertname']

    receivers:
    - name: 'alert-slack'
      slack_configs:
      - api_url: "<<alerts-slack-url>>"
        channel: "<<alerts-slack-channel>>"
        color: '{{ if eq .Status "firing" }}danger{{ else }}good{{ end }}'
        title: "{{ range .Alerts }}{{ .Labels.alertname }} | env = {{.Labels.environment}} | severity = {{.Labels.severity}}\n{{ end }}"
        text: "
          {{ range .Alerts }}
            *Summary:* {{ .Annotations.summary }}\n
            *Description:* {{ .Annotations.description }}\n
            *Details:*\n
            {{ range .Labels.SortedPairs }} \t*{{ .Name }}:* `{{ .Value }}`\n
            {{ end }}
          {{ end }}"
        send_resolved: true
    - name: 'silent-receiver'
