apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
spec:
  ports:
  - name: elasticsearch
    port: 9200
    targetPort: 9200
  selector:
    component: elasticsearch
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: elasticsearch
spec:
  serviceName: "elasticsearch"
  updateStrategy:
    type: RollingUpdate
  replicas: 1
  template:
    metadata:
      labels:
        component: elasticsearch
    spec:
      containers:
      - image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.1.2
        name: elasticsearch
        ports:
        - containerPort: 9200
        volumeMounts:
        - mountPath: /usr/share/elasticsearch/data
          name: elasticsearch-data
        env:
        - name: ES_JAVA_OPTS
          value: -Xms512m -Xmx512m
        - name: TAKE_FILE_OWNERSHIP
          value: "true"
        resources:
          requests:
            cpu: "50m"
  volumeClaimTemplates:
  - metadata:
      name: elasticsearch-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: ssd
      resources:
        requests:
          storage: 50Gi
      selector:
        matchLabels:
          component: elasticsearch
