apiVersion: v1
kind: Service
metadata:
  name: prometheus
spec:
  ports:
  - port: 9090
    targetPort: 9090
  selector:
    component: prometheus
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: prometheus
spec:
  serviceName: "prometheus"
  updateStrategy:
    type: RollingUpdate
  replicas: 1
  template:
    metadata:
      labels:
        component: prometheus
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port:   '9100'
    spec:
      imagePullSecrets:
        - name: gcr-secret
      containers:
      - image: gcr.io/padas-app/utility/prometheus:<<prometheus-version>>
        name: prometheus
        resources:
          requests:
            cpu: "50m"
          limits:
            cpu: "1"
        volumeMounts:
        - mountPath: /prometheus
          name: prometheus-data
        env:
        - name: ALERTMANAGER_URL
          valueFrom:
            configMapKeyRef:
              name: default-configmap
              key: ALERTMANAGER_URL
      - image: prom/node-exporter:<<node-exporter-version>>
        name: disk-exporter
        resources:
          requests:
            cpu: "15m"
          limits:
            cpu: "500m"
        volumeMounts:
        - mountPath: /prometheus
          name: prometheus-data
        ports:
        - containerPort: 9100
  volumeClaimTemplates:
  - metadata:
      name: prometheus-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "ssd"
      resources:
        requests:
          storage: 30Gi
      selector:
        matchLabels:
          component: prometheus
