[program:panthera]
command=/var/www/venv/bin/python panthera-camera-trap.py
directory=/var/www/das/das/das/sensors/static/lambda/panthera
environment=PYTHONPATH='//var/www/das/das/das/sensors/static/lambda/panthera:$PYTHONPATH'
user=www-data
environment=PATH="/var/www/venv/bin/"
stdout_logfile=/var/log/das/panthera.log
stderr_logfile=/var/log/das/panthera_stderr.log
autostart=false
startretries=0
startsecs=0
autorestart=false