# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-05 18:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mapping', '0002_map'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('observations', '0006_auto_20160105_1055'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeofenceAnalyzer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_time', models.TimeField(null=True)),
                ('max_time', models.TimeField(null=True)),
                ('interior_buffer', models.FloatField(default=0.0)),
                ('polygon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mapping.PolygonFeature')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ImmobilityAnalyzer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_time', models.TimeField(null=True)),
                ('max_time', models.TimeField(null=True)),
                ('radius', models.FloatField(default=20.0)),
                ('speed_threshold', models.FloatField(default=0.1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubjectAnalyzer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='observations.Subject')),
            ],
        ),
    ]
