# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-23 00:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0002_map'),
        ('analyzers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProximityAnalyzer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_time', models.TimeField(null=True)),
                ('max_time', models.TimeField(null=True)),
                ('distance_m', models.FloatField(default=100)),
                ('polygon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mapping.PolygonFeature')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SpeedAnalyzer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_time', models.TimeField(null=True)),
                ('max_time', models.TimeField(null=True)),
                ('max_speed', models.FloatField(default=2)),
                ('min_speed', models.FloatField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
