# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-29 21:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzers', '0002_proximityanalyzer_speedanalyzer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='immobilityanalyzer',
            name='speed_threshold',
        ),
        migrations.AddField(
            model_name='immobilityanalyzer',
            name='threshold_time',
            field=models.IntegerField(default=18000),
        ),
        migrations.AlterField(
            model_name='immobilityanalyzer',
            name='radius',
            field=models.FloatField(default=13.0),
        ),
    ]
