# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-29 22:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzers', '0003_auto_20160129_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='immobilityanalyzer',
            name='threshold_critical_cluster_ratio',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='immobilityanalyzer',
            name='threshold_warning_cluster_ratio',
            field=models.FloatField(default=0.8),
        ),
    ]
