# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-17 21:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0009_auto_20160217_1316'),
        ('analyzers', '0006_containmentanalyzer'),
    ]

    operations = [
        migrations.AddField(
            model_name='containmentanalyzer',
            name='subject',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='observations.Subject'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='geofenceanalyzer',
            name='subject',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='observations.Subject'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='immobilityanalyzer',
            name='subject',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='observations.Subject'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proximityanalyzer',
            name='subject',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='observations.Subject'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='speedanalyzer',
            name='subject',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='observations.Subject'),
            preserve_default=False,
        ),
    ]
