# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-17 22:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analyzers', '0007_auto_20160217_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='containmentanalyzer',
            name='polygon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mapping.PolygonFeature'),
        ),
        migrations.AlterField(
            model_name='geofenceanalyzer',
            name='fence',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mapping.LineFeature'),
        ),
        migrations.AlterField(
            model_name='proximityanalyzer',
            name='polygon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mapping.PolygonFeature'),
        ),
    ]
