# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-04-25 18:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyzers', '0012_annotations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='containmentanalyzer',
            name='polygon',
        ),
        migrations.RemoveField(
            model_name='containmentanalyzer',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='geofenceanalyzer',
            name='containment_regions',
        ),
        migrations.RemoveField(
            model_name='geofenceanalyzer',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='geofenceanalyzer',
            name='virtual_fences',
        ),
        migrations.RemoveField(
            model_name='geofenceanalyzerresult',
            name='analyzer',
        ),
        migrations.RemoveField(
            model_name='geofenceanalyzerresult',
            name='observations',
        ),
        migrations.RemoveField(
            model_name='immobilityanalyzer',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='immobilityanalyzerresult',
            name='analyzer',
        ),
        migrations.RemoveField(
            model_name='immobilityanalyzerresult',
            name='observations',
        ),
        migrations.RemoveField(
            model_name='observationannotator',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='proximityanalyzer',
            name='polygon',
        ),
        migrations.RemoveField(
            model_name='proximityanalyzer',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='speedanalyzer',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='subjectanalyzer',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='subjectanalyzer',
            name='subject',
        ),
        migrations.DeleteModel(
            name='ContainmentAnalyzer',
        ),
        migrations.DeleteModel(
            name='GeofenceAnalyzer',
        ),
        migrations.DeleteModel(
            name='GeofenceAnalyzerResult',
        ),
        migrations.DeleteModel(
            name='ImmobilityAnalyzer',
        ),
        migrations.DeleteModel(
            name='ImmobilityAnalyzerResult',
        ),
        migrations.DeleteModel(
            name='ObservationAnnotator',
        ),
        migrations.DeleteModel(
            name='ProximityAnalyzer',
        ),
        migrations.DeleteModel(
            name='SpeedAnalyzer',
        ),
        migrations.DeleteModel(
            name='SubjectAnalyzer',
        ),
    ]
