# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-05-16 20:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyzers', '0014_subject_analyzers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ImmobilityAnalyzer',
            new_name='ImmobilityAnalyzerConfig',
        ),
    ]
