# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-08-11 19:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzers', '0017_auto_20170731_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectanalyzerresult',
            name='analyzer_revision',
            field=models.IntegerField(default=1),
        ),
    ]
