# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-10-06 19:41
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import revision.manager
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0011_spatial'),
        ('observations', '0043_spatial-analyzers'),
        ('analyzers', '0018_spatial-analyzers'),
    ]

    operations = [
        migrations.CreateModel(
            name='LowSpeedPercentileAnalyzerConfig',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4,
                                        primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True,
                                          verbose_name='A friendly, unique name for the analyzer.')),
                ('notes', models.TextField(blank=True, default='')),
                ('schedule', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), default=[
                ], size=None, verbose_name='Array of crontab schedule patterns that an analyzer can use to determine whether to run.')),
                ('is_active', models.BooleanField(
                    default=True, help_text='Designates whether this analyzer is active. Set this False instead of deleting this record.', verbose_name='active')),
                ('search_time_hours', models.FloatField(
                    default=24.0, verbose_name='The period of data to retrieve from the database')),
                ('low_threshold_percentile', models.FloatField(default=0.01)),
                ('default_low_speed_value', models.FloatField(default=0.05)),
                ('subject_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                                    to='observations.SubjectGroup', verbose_name='This analyzer applies to subjects in this SubjectGroup.')),
            ],
            options={
                'abstract': False,
            },
            bases=(revision.manager.RevisionMixin, models.Model),
        ),
        migrations.CreateModel(
            name='LowSpeedWilcoxAnalyzerConfig',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4,
                                        primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True,
                                          verbose_name='A friendly, unique name for the analyzer.')),
                ('notes', models.TextField(blank=True, default='')),
                ('schedule', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), default=[
                ], size=None, verbose_name='Array of crontab schedule patterns that an analyzer can use to determine whether to run.')),
                ('is_active', models.BooleanField(
                    default=True, help_text='Designates whether this analyzer is active. Set this False instead of deleting this record.', verbose_name='active')),
                ('search_time_hours', models.FloatField(
                    default=24.0, verbose_name='The period of data to retrieve from the database')),
                ('low_speed_probability_cutoff', models.FloatField(default=0.001)),
                ('subject_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                                    to='observations.SubjectGroup', verbose_name='This analyzer applies to subjects in this SubjectGroup.')),
            ],
            options={
                'abstract': False,
            },
            bases=(revision.manager.RevisionMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ProximityAnalyzerConfig',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4,
                                        primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True,
                                          verbose_name='A friendly, unique name for the analyzer.')),
                ('notes', models.TextField(blank=True, default='')),
                ('schedule', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), default=[
                ], size=None, verbose_name='Array of crontab schedule patterns that an analyzer can use to determine whether to run.')),
                ('is_active', models.BooleanField(
                    default=True, help_text='Designates whether this analyzer is active. Set this False instead of deleting this record.', verbose_name='active')),
                ('search_time_hours', models.FloatField(
                    default=24.0, verbose_name='The period of data to retrieve from the database')),
                ('threshold_time', models.IntegerField(default=86400)),
                ('threshold_dist_meters', models.FloatField(default=500.0)),
                ('proximal_features', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proximal_features',
                                                        to='mapping.SpatialFeatureGroupStatic', verbose_name='This analyzer applies to proximity features in this SpatialFeatureGroupStatic.')),
                ('subject_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                                    to='observations.SubjectGroup', verbose_name='This analyzer applies to subjects in this SubjectGroup.')),
            ],
            options={
                'abstract': False,
            },
            bases=(revision.manager.RevisionMixin, models.Model),
        ),
        migrations.RemoveField(
            model_name='lowspeedanalyzerconfig',
            name='subject_group',
        ),
        migrations.AlterField(
            model_name='environmentalsubjectanalyzerconfig',
            name='search_time_hours',
            field=models.FloatField(
                default=24.0, verbose_name='The period of data to retrieve from the database'),
        ),
        migrations.AlterField(
            model_name='geofenceanalyzerconfig',
            name='search_time_hours',
            field=models.FloatField(
                default=24.0, verbose_name='The period of data to retrieve from the database'),
        ),
        migrations.AlterField(
            model_name='geofenceanalyzerconfig',
            name='threshold_time',
            field=models.IntegerField(default=43200),
        ),
        migrations.AlterField(
            model_name='immobilityanalyzerconfig',
            name='search_time_hours',
            field=models.FloatField(
                default=24.0, verbose_name='The period of data to retrieve from the database'),
        ),
        migrations.DeleteModel(
            name='LowSpeedAnalyzerConfig',
        ),
    ]
