# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-08-18 20:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzers', '0019_environmentalsubjectanalyzerconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectanalyzerresult',
            name='title',
            field=models.TextField(blank=True, default=''),
        ),
    ]
