# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-10-28 22:19
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzers', '0019_spatialfeatures'),
    ]

    operations = [
        migrations.AlterField(
            model_name='environmentalsubjectanalyzerconfig',
            name='schedule',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=[
            ], null=True, size=None, verbose_name='Array of crontab schedule patterns that an analyzer can use to determine whether to run.'),
        ),
        migrations.AlterField(
            model_name='geofenceanalyzerconfig',
            name='schedule',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=[
            ], null=True, size=None, verbose_name='Array of crontab schedule patterns that an analyzer can use to determine whether to run.'),
        ),
        migrations.AlterField(
            model_name='immobilityanalyzerconfig',
            name='schedule',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=[
            ], null=True, size=None, verbose_name='Array of crontab schedule patterns that an analyzer can use to determine whether to run.'),
        ),
        migrations.AlterField(
            model_name='lowspeedpercentileanalyzerconfig',
            name='schedule',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=[
            ], null=True, size=None, verbose_name='Array of crontab schedule patterns that an analyzer can use to determine whether to run.'),
        ),
        migrations.AlterField(
            model_name='lowspeedwilcoxanalyzerconfig',
            name='schedule',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=[
            ], null=True, size=None, verbose_name='Array of crontab schedule patterns that an analyzer can use to determine whether to run.'),
        ),
        migrations.AlterField(
            model_name='proximityanalyzerconfig',
            name='schedule',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=[
            ], null=True, size=None, verbose_name='Array of crontab schedule patterns that an analyzer can use to determine whether to run.'),
        ),
    ]
