# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-11-02 22:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzers', '0020_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geofenceanalyzerconfig',
            name='threshold_time',
            field=models.IntegerField(
                default=43200, verbose_name='Threshold time (seconds)'),
        ),
    ]
