# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-11-06 23:03
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzers', '0021_geofence_threshold_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='speeddistro',
            name='speeds_kmhr',
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.FloatField(), blank=True, null=True, size=None),
        ),
    ]
