# Generated by Django 2.0.1 on 2018-01-18 22:01

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.query_utils


class Migration(migrations.Migration):

    dependencies = [
        ('analyzers', '0022_subjecttracksegment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectanalyzerresult',
            name='subject_analyzer_content_type',
            field=models.ForeignKey(limit_choices_to=django.db.models.query_utils.Q(django.db.models.query_utils.Q(('app_label', 'analyzers'), ('model', 'immobilityanalyzer'), _connector='AND'), django.db.models.query_utils.Q(('app_label', 'analyzers'), (
                'model', 'geofenceanalyzer'), _connector='AND'), django.db.models.query_utils.Q(('app_label', 'analyzers'), ('model', 'environmentalanalyzer'), _connector='AND'), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
    ]
