# Generated by Django 2.0.2 on 2018-08-13 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0016_split_geofence_groups'),
        ('analyzers', '0024_jsonfield_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='geofenceanalyzerconfig',
            name='critical_geofence_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+',
                                    to='mapping.SpatialFeatureGroupStatic', verbose_name='Critical geo-fences for this analyzer'),
        ),
        migrations.AddField(
            model_name='geofenceanalyzerconfig',
            name='warning_geofence_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+',
                                    to='mapping.SpatialFeatureGroupStatic', verbose_name='Warning geo-fences for this analyzer'),
        ),
        migrations.AlterField(
            model_name='geofenceanalyzerconfig',
            name='containment_regions',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='mapping.SpatialFeatureGroupStatic',
                                    verbose_name='This analyzer applies to containment polygons in this SpatialFeatureGroupStatic.'),
        ),
        migrations.AlterField(
            model_name='geofenceanalyzerconfig',
            name='geofences',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+',
                                    to='mapping.SpatialFeatureGroupStatic', verbose_name='This will go away soon.'),
        ),
    ]
