# Generated by Django 2.0.2 on 2018-08-14 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyzers', '0026_update_geofence_groups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geofenceanalyzerconfig',
            name='geofences',
        ),
    ]
