# Generated by Django 2.0.6 on 2018-09-13 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analyzers', '0029_analyzer_view_permissions_v2'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='environmentalsubjectanalyzerconfig',
            options={'verbose_name': 'Environmental Analyzer',
                     'verbose_name_plural': 'Environmental Analyzers'},
        ),
        migrations.AlterModelOptions(
            name='geofenceanalyzerconfig',
            options={'permissions': (('view_geofenceanalyzerconfig', 'Can view Geofence Analyzer configurations'),),
                     'verbose_name': 'Geofence Analyzer', 'verbose_name_plural': 'Geofence Analyzers'},
        ),
        migrations.AlterModelOptions(
            name='immobilityanalyzerconfig',
            options={'verbose_name': 'Immobility Analyzer',
                     'verbose_name_plural': 'Immobility Analyzers'},
        ),
        migrations.AlterModelOptions(
            name='lowspeedpercentileanalyzerconfig',
            options={'verbose_name': 'Low-Speed Analyzer (Percentile method)',
                     'verbose_name_plural': 'Low-Speed Analyzers (Percentile method)'},
        ),
        migrations.AlterModelOptions(
            name='lowspeedwilcoxanalyzerconfig',
            options={'verbose_name': 'Low-Speed Analyzer (Wilcox method)',
                     'verbose_name_plural': 'Low-Speed Analyzers (Wilcox method)'},
        ),
        migrations.AlterModelOptions(
            name='proximityanalyzerconfig',
            options={'permissions': (('view_proximityanalyzerconfig', 'Can view Proximity Analyzer Configurations'),),
                     'verbose_name': 'Proximity Analyzer', 'verbose_name_plural': 'Proximity Analyzers'},
        ),
        migrations.AlterField(
            model_name='environmentalsubjectanalyzerconfig',
            name='GEE_img_band_name',
            field=models.CharField(
                default='b1', max_length=50, verbose_name='Google Earth Engine Image Band Name'),
        ),
        migrations.AlterField(
            model_name='environmentalsubjectanalyzerconfig',
            name='GEE_img_name',
            field=models.CharField(
                default='', max_length=100, verbose_name='Google Earth Engine Image Name'),
        ),
        migrations.AlterField(
            model_name='geofenceanalyzerconfig',
            name='containment_regions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+',
                                    to='mapping.SpatialFeatureGroupStatic', verbose_name='This analyzer applies to containment polygons in this SpatialFeatureGroupStatic.'),
        ),
        migrations.AlterField(
            model_name='geofenceanalyzerconfig',
            name='critical_geofence_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+',
                                    to='mapping.SpatialFeatureGroupStatic', verbose_name='Critical geo-fences for this analyzer'),
        ),
        migrations.AlterField(
            model_name='geofenceanalyzerconfig',
            name='warning_geofence_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+',
                                    to='mapping.SpatialFeatureGroupStatic', verbose_name='Warning geo-fences for this analyzer'),
        ),
        migrations.AlterField(
            model_name='immobilityanalyzerconfig',
            name='threshold_radius',
            field=models.FloatField(
                default=13.0, verbose_name='Threshold Radius (meters)'),
        ),
        migrations.AlterField(
            model_name='immobilityanalyzerconfig',
            name='threshold_time',
            field=models.IntegerField(
                default=18000, verbose_name='Threshold Time (seconds)'),
        ),
    ]
