# Generated by Django 2.0.10 on 2019-03-28 22:33

import django.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("analyzers", "0030_blanks"),
    ]

    operations = [
        migrations.AddField(
            model_name="environmentalsubjectanalyzerconfig",
            name="additional",
            field=django.db.models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="geofenceanalyzerconfig",
            name="additional",
            field=django.db.models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="immobilityanalyzerconfig",
            name="additional",
            field=django.db.models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="lowspeedpercentileanalyzerconfig",
            name="additional",
            field=django.db.models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="lowspeedwilcoxanalyzerconfig",
            name="additional",
            field=django.db.models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="proximityanalyzerconfig",
            name="additional",
            field=django.db.models.JSONField(blank=True, default=dict),
        ),
    ]
