# Generated by Django 2.0.10 on 2019-03-31 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyzers', '0031_analyzer_additional'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='environmentalsubjectanalyzerconfig',
            options={'verbose_name': 'Google Earth Engine Analyzer', 'verbose_name_plural': 'Google Earth Engine Analyzers'},
        ),
    ]
