# Generated by Django 2.0.10 on 2019-07-08 06:09

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0018_tile'),
        ('analyzers', '0033_GFW'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalForestWatchSubscription',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('subscription_id', models.CharField(max_length=100)),
                ('geostore_id', models.CharField(max_length=100)),
                ('additional', django.contrib.postgres.fields.jsonb.JSONField(default=dict, help_text='JSON config for subs')),
                ('spatial_feature_group', models.ForeignKey(help_text='geographical area to monitor', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='mapping.SpatialFeatureGroupStatic')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='globalforeswatchsubscription',
            name='spatial_feature_group',
        ),
        migrations.DeleteModel(
            name='GlobalForesWatchSubscription',
        ),
    ]
