# Generated by Django 2.2.9 on 2020-02-25 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzers', '0033_add_gfw_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalforestwatchsubscription',
            name='Deforestation_confidence',
            field=models.CharField(choices=[('3', 'Confirmed Only'), ('2, 3', 'Confirmed and Unconfirmed')], default='3', max_length=100),
        ),
        migrations.AddField(
            model_name='globalforestwatchsubscription',
            name='Fire_confidence',
            field=models.CharField(choices=[('high', 'High Only'), ('high, nominal', 'High and Nominal'), ('high, nominal, low', 'High, Nominal and Low')], default='high, nominal', max_length=100),
        )
    ]
