# Generated by Django 2.0.10 on 2019-07-08 06:23

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzers', '0034_auto_20190707_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalforestwatchsubscription',
            name='additional',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, help_text='JSON data for subscriptions'),
        ),
        migrations.AlterField(
            model_name='globalforestwatchsubscription',
            name='geostore_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='globalforestwatchsubscription',
            name='subscription_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
