# Generated by Django 2.0.13 on 2019-07-11 19:28

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyzers', '0035_GFW'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='globalforestwatchsubscription',
            options={'verbose_name': 'Global Forest Watch Subscription', 'verbose_name_plural': 'Global Forest Watch Subscriptions'},
        ),
        migrations.RemoveField(
            model_name='globalforestwatchsubscription',
            name='spatial_feature_group',
        ),
        migrations.AddField(
            model_name='globalforestwatchsubscription',
            name='subscription_geometry',
            field=django.contrib.gis.db.models.fields.GeometryField(blank=True, geography=True, null=True, srid=4326),
        ),
    ]
