# Generated by Django 2.2.11 on 2020-05-16 13:50

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analyzers', '0035_num_clustered_events'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='geofenceanalyzerconfig',
            options={'verbose_name': 'Geofence Analyzer', 'verbose_name_plural': 'Geofence Analyzers'},
        ),
        migrations.AlterModelOptions(
            name='observationannotator',
            options={'verbose_name': 'Subject Track Filter', 'verbose_name_plural': 'Subject Track Filters'},
        ),
        migrations.AlterModelOptions(
            name='proximityanalyzerconfig',
            options={'verbose_name': 'Proximity Analyzer', 'verbose_name_plural': 'Proximity Analyzers'},
        ),
        migrations.AlterField(
            model_name='environmentalsubjectanalyzerconfig',
            name='name',
            field=models.CharField(help_text='A friendly, <b>unique</b> name for the analyzer.', max_length=100, unique=True, verbose_name='Analyzer Name'),
        ),
        migrations.AlterField(
            model_name='environmentalsubjectanalyzerconfig',
            name='schedule',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, null=True, size=None, verbose_name='Array of crontab schedule patterns that an analyzer can use to determine whether to run.'),
        ),
        migrations.AlterField(
            model_name='environmentalsubjectanalyzerconfig',
            name='search_time_hours',
            field=models.FloatField(default=24.0, help_text='Analysis will be performed on recent data within this time frame.', verbose_name='Analysis time frame (hours)'),
        ),
        migrations.AlterField(
            model_name='environmentalsubjectanalyzerconfig',
            name='subject_group',
            field=models.ForeignKey(help_text='This analyzer applies to subjects in this Subject Group.', on_delete=django.db.models.deletion.CASCADE, to='observations.SubjectGroup', verbose_name='Subject Group'),
        ),
        migrations.AlterField(
            model_name='geofenceanalyzerconfig',
            name='containment_regions',
            field=models.ForeignKey(blank=True, help_text="A geo-fence break report will indicate a subject's latest location within one of these containment areas.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='mapping.SpatialFeatureGroupStatic', verbose_name='Containment Regions'),
        ),
        migrations.AlterField(
            model_name='geofenceanalyzerconfig',
            name='critical_geofence_group',
            field=models.ForeignKey(blank=True, help_text='A <span style="color:#fff;padding:2px 10px; background-color: #c00; border-radius:3px;">red</span> alert will be recorded when a subject breaks a geo-fence in this Spatial Feature Group.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='mapping.SpatialFeatureGroupStatic', verbose_name='Critical geo-fences'),
        ),
        migrations.AlterField(
            model_name='geofenceanalyzerconfig',
            name='name',
            field=models.CharField(help_text='A friendly, <b>unique</b> name for the analyzer.', max_length=100, unique=True, verbose_name='Analyzer Name'),
        ),
        migrations.AlterField(
            model_name='geofenceanalyzerconfig',
            name='schedule',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, null=True, size=None, verbose_name='Array of crontab schedule patterns that an analyzer can use to determine whether to run.'),
        ),
        migrations.AlterField(
            model_name='geofenceanalyzerconfig',
            name='search_time_hours',
            field=models.FloatField(default=24.0, help_text='Analysis will be performed on recent data within this time frame.', verbose_name='Analysis time frame (hours)'),
        ),
        migrations.AlterField(
            model_name='geofenceanalyzerconfig',
            name='subject_group',
            field=models.ForeignKey(help_text='This analyzer applies to subjects in this Subject Group.', on_delete=django.db.models.deletion.CASCADE, to='observations.SubjectGroup', verbose_name='Subject Group'),
        ),
        migrations.AlterField(
            model_name='geofenceanalyzerconfig',
            name='threshold_time',
            field=models.IntegerField(default=43200, help_text='This does not apply to geofence analysis.', verbose_name='Threshold time (seconds)'),
        ),
        migrations.AlterField(
            model_name='geofenceanalyzerconfig',
            name='warning_geofence_group',
            field=models.ForeignKey(blank=True, help_text='An <span style="color:#000;padding:2px 10px; background-color: #fead38; border-radius:3px;">amber</span> alert will be recorded when a subject breaks a geo-fence in this Spatial Feature Group.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='mapping.SpatialFeatureGroupStatic', verbose_name='Warning geo-fences'),
        ),
        migrations.AlterField(
            model_name='immobilityanalyzerconfig',
            name='name',
            field=models.CharField(help_text='A friendly, <b>unique</b> name for the analyzer.', max_length=100, unique=True, verbose_name='Analyzer Name'),
        ),
        migrations.AlterField(
            model_name='immobilityanalyzerconfig',
            name='schedule',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, null=True, size=None, verbose_name='Array of crontab schedule patterns that an analyzer can use to determine whether to run.'),
        ),
        migrations.AlterField(
            model_name='immobilityanalyzerconfig',
            name='search_time_hours',
            field=models.FloatField(default=24.0, help_text='Analysis will be performed on recent data within this time frame.', verbose_name='Analysis time frame (hours)'),
        ),
        migrations.AlterField(
            model_name='immobilityanalyzerconfig',
            name='subject_group',
            field=models.ForeignKey(help_text='This analyzer applies to subjects in this Subject Group.', on_delete=django.db.models.deletion.CASCADE, to='observations.SubjectGroup', verbose_name='Subject Group'),
        ),
        migrations.AlterField(
            model_name='immobilityanalyzerconfig',
            name='threshold_probability',
            field=models.FloatField(default=0.8, help_text='\n    This indicates a ratio threshold for (number of stationary points) / (total points). If the data indicates\n    a higher ratio, the analyzer will produce an event.\n    ', verbose_name='Threshold ratio'),
        ),
        migrations.AlterField(
            model_name='immobilityanalyzerconfig',
            name='threshold_radius',
            field=models.FloatField(default=13.0, help_text="This determines the circle within which a Subject's points will be considered stationary.", verbose_name='Threshold Radius (meters)'),
        ),
        migrations.AlterField(
            model_name='immobilityanalyzerconfig',
            name='threshold_time',
            field=models.IntegerField(default=18000, help_text='This is the maximum time frame a Subject is expected to be stationary.', verbose_name='Threshold Time (seconds)'),
        ),
        migrations.AlterField(
            model_name='lowspeedpercentileanalyzerconfig',
            name='name',
            field=models.CharField(help_text='A friendly, <b>unique</b> name for the analyzer.', max_length=100, unique=True, verbose_name='Analyzer Name'),
        ),
        migrations.AlterField(
            model_name='lowspeedpercentileanalyzerconfig',
            name='schedule',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, null=True, size=None, verbose_name='Array of crontab schedule patterns that an analyzer can use to determine whether to run.'),
        ),
        migrations.AlterField(
            model_name='lowspeedpercentileanalyzerconfig',
            name='search_time_hours',
            field=models.FloatField(default=24.0, help_text='Analysis will be performed on recent data within this time frame.', verbose_name='Analysis time frame (hours)'),
        ),
        migrations.AlterField(
            model_name='lowspeedpercentileanalyzerconfig',
            name='subject_group',
            field=models.ForeignKey(help_text='This analyzer applies to subjects in this Subject Group.', on_delete=django.db.models.deletion.CASCADE, to='observations.SubjectGroup', verbose_name='Subject Group'),
        ),
        migrations.AlterField(
            model_name='lowspeedwilcoxanalyzerconfig',
            name='name',
            field=models.CharField(help_text='A friendly, <b>unique</b> name for the analyzer.', max_length=100, unique=True, verbose_name='Analyzer Name'),
        ),
        migrations.AlterField(
            model_name='lowspeedwilcoxanalyzerconfig',
            name='schedule',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, null=True, size=None, verbose_name='Array of crontab schedule patterns that an analyzer can use to determine whether to run.'),
        ),
        migrations.AlterField(
            model_name='lowspeedwilcoxanalyzerconfig',
            name='search_time_hours',
            field=models.FloatField(default=24.0, help_text='Analysis will be performed on recent data within this time frame.', verbose_name='Analysis time frame (hours)'),
        ),
        migrations.AlterField(
            model_name='lowspeedwilcoxanalyzerconfig',
            name='subject_group',
            field=models.ForeignKey(help_text='This analyzer applies to subjects in this Subject Group.', on_delete=django.db.models.deletion.CASCADE, to='observations.SubjectGroup', verbose_name='Subject Group'),
        ),
        migrations.AlterField(
            model_name='proximityanalyzerconfig',
            name='name',
            field=models.CharField(help_text='A friendly, <b>unique</b> name for the analyzer.', max_length=100, unique=True, verbose_name='Analyzer Name'),
        ),
        migrations.AlterField(
            model_name='proximityanalyzerconfig',
            name='proximal_features',
            field=models.ForeignKey(help_text='This analyzer applies to proximity features in this Feature Group.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proximal_features', to='mapping.SpatialFeatureGroupStatic', verbose_name='Feature Groups'),
        ),
        migrations.AlterField(
            model_name='proximityanalyzerconfig',
            name='schedule',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, null=True, size=None, verbose_name='Array of crontab schedule patterns that an analyzer can use to determine whether to run.'),
        ),
        migrations.AlterField(
            model_name='proximityanalyzerconfig',
            name='search_time_hours',
            field=models.FloatField(default=24.0, help_text='Analysis will be performed on recent data within this time frame.', verbose_name='Analysis time frame (hours)'),
        ),
        migrations.AlterField(
            model_name='proximityanalyzerconfig',
            name='subject_group',
            field=models.ForeignKey(help_text='This analyzer applies to subjects in this Subject Group.', on_delete=django.db.models.deletion.CASCADE, to='observations.SubjectGroup', verbose_name='Subject Group'),
        ),
        migrations.AlterField(
            model_name='proximityanalyzerconfig',
            name='threshold_dist_meters',
            field=models.FloatField(default=500.0, help_text="A proximity event occurs when a subject's path passes within this distance of a designated spatial feature. <br/>A subject's path is drawn using a straight line between reported positions.", verbose_name='Proximity Distance (meters)'),
        ),
    ]
