# Generated by Django 2.2.14 on 2020-08-06 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzers', '0036_meta'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalforestwatchsubscription',
            name='last_check_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Check Time'),
        ),
    ]
