# Generated by Django 2.2.14 on 2020-08-06 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzers', '0036_meta'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalforestwatchsubscription',
            name='last_check_status',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='globalforestwatchsubscription',
            name='last_check_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
