# Generated by Django 2.2.9 on 2020-11-11 22:25

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import revision.manager
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0034_update_arcgis_url'),
        ('observations', '0084_addax'),
        ('analyzers', '0037_gfw_download_status_fields'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProximityAnalyzerConfig',
            new_name='FeatureProximityAnalyzerConfig',
        ),
        migrations.AlterModelOptions(
            name='featureproximityanalyzerconfig',
            options={},
        ),
        migrations.CreateModel(
            name='SubjectProximityAnalyzerConfig',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='A friendly, <b>unique</b> name for the analyzer.', max_length=100, unique=True, verbose_name='Analyzer Name')),
                ('notes', models.TextField(blank=True, default='')),
                ('schedule', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, null=True, size=None, verbose_name='Array of crontab schedule patterns that an analyzer can use to determine whether to run.')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this analyzer is active. Set this False instead of deleting this record.', verbose_name='active')),
                ('search_time_hours', models.FloatField(default=24.0, help_text='Analysis will be performed on recent data within this time frame.', verbose_name='Analysis time frame (hours)')),
                ('additional', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict)),
                ('threshold_time', models.IntegerField(default=86400)),
                ('threshold_dist_meters', models.FloatField(default=500.0, help_text="A proximity event occurs when a subject's path passes within this distance of a designated spatial feature. <br/>A subject's path is drawn using a straight line between reported positions.", verbose_name='Proximity Distance (meters)')),
                ('proximal_time_frame', models.FloatField(default=24.0, help_text='Report will be created only if the subjects are of close proximity distance within this time frame', verbose_name='Proximal time frame (hours)')),
                ('second_subject_group', models.ForeignKey(help_text='This analyzer applies to subjects in this Subject Group.', on_delete=django.db.models.deletion.CASCADE, related_name='subject_group_2', to='observations.SubjectGroup', verbose_name='Subject Group 2')),
                ('subject_group', models.ForeignKey(help_text='This analyzer applies to subjects in this Subject Group.', on_delete=django.db.models.deletion.CASCADE, related_name='subject_group_1', to='observations.SubjectGroup', verbose_name='Subject Group 1')),
            ],
            options={
                'abstract': False,
            },
            bases=(revision.manager.RevisionMixin, models.Model),
        ),
    ]
