# Generated by Django 2.0.13 on 2019-07-11 19:51

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyzers', '0037_gfw_subs_added_geometry_object'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalforestwatchsubscription',
            name='subscription_geometry',
            field=django.contrib.gis.db.models.fields.PolygonField(geography=True, null=True, srid=4326),
        ),
    ]
