# Generated by Django 2.2.14 on 2020-12-18 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzers', '0038_proximity_feature_and_subject_analyzers_split'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalforestwatchsubscription',
            name='glad_confirmed_backfill_days',
            field=models.IntegerField(default=180),
        ),
    ]
