# Generated by Django 2.0.13 on 2019-07-11 20:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('analyzers', '0038_gfw_subs_added_geometry_object'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalforestwatchsubscription',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gfw_subscriptions', related_query_name='gfw_subscription', to=settings.AUTH_USER_MODEL),
        ),
    ]
