# Generated by Django 2.2.14 on 2021-10-05 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzers', '0039_globalforestwatchsubscription_glad_confirmed_backfill_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='environmentalsubjectanalyzerconfig',
            name='quiet_period',
            field=models.DurationField(blank=True, help_text='This will be used to override the configured quiet period.',
                                       null=True, verbose_name='Quiet period (HH:MM:SS)'),
        ),
        migrations.AddField(
            model_name='featureproximityanalyzerconfig',
            name='quiet_period',
            field=models.DurationField(blank=True, help_text='This will be used to override the configured quiet period.',
                                       null=True, verbose_name='Quiet period (HH:MM:SS)'),
        ),
        migrations.AddField(
            model_name='geofenceanalyzerconfig',
            name='quiet_period',
            field=models.DurationField(blank=True, help_text='This will be used to override the configured quiet period.',
                                       null=True, verbose_name='Quiet period (HH:MM:SS)'),
        ),
        migrations.AddField(
            model_name='immobilityanalyzerconfig',
            name='quiet_period',
            field=models.DurationField(blank=True, help_text='This will be used to override the configured quiet period.',
                                       null=True, verbose_name='Quiet period (HH:MM:SS)'),
        ),
        migrations.AddField(
            model_name='lowspeedpercentileanalyzerconfig',
            name='quiet_period',
            field=models.DurationField(blank=True, help_text='This will be used to override the configured quiet period.',
                                       null=True, verbose_name='Quiet period (HH:MM:SS)'),
        ),
        migrations.AddField(
            model_name='lowspeedwilcoxanalyzerconfig',
            name='quiet_period',
            field=models.DurationField(blank=True, help_text='This will be used to override the configured quiet period.',
                                       null=True, verbose_name='Quiet period (HH:MM:SS)'),
        ),
        migrations.AddField(
            model_name='subjectproximityanalyzerconfig',
            name='quiet_period',
            field=models.DurationField(blank=True, help_text='This will be used to override the configured quiet period.',
                                       null=True, verbose_name='Quiet period (HH:MM:SS)'),
        ),
    ]
