# Generated by Django 3.2.19 on 2023-08-23 23:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("analyzers", "0041_use_models_JSONField_instead_postgres_fields_JSONField"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Schedule",
        ),
    ]
