# Generated by Django 3.2.19 on 2023-08-24 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_add_das_tenant_model"),
        ("analyzers", "0042_delete_schedule"),
    ]

    operations = [
        migrations.AddField(
            model_name="globalforestwatchsubscription",
            name="das_tenant",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="core.dastenant"
            ),
        ),
        migrations.AddField(
            model_name="observationannotator",
            name="das_tenant",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="core.dastenant"
            ),
        ),
        migrations.AddField(
            model_name="subjectspeedprofile",
            name="das_tenant",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="core.dastenant"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="globalforestwatchsubscription",
            unique_together={("id", "das_tenant")},
        ),
        migrations.AlterUniqueTogether(
            name="observationannotator",
            unique_together={("id", "das_tenant")},
        ),
        migrations.AlterUniqueTogether(
            name="subjectspeedprofile",
            unique_together={("id", "das_tenant")},
        ),
    ]
