# Generated by Django 3.2.19 on 2023-09-05 21:41

import django_multitenant.fields

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_migrate_oauth_tables_to_das_custom_models"),
        ("analyzers", "0043_add_tenant_mixing_to_models_with_no_relations"),
    ]

    operations = [
        migrations.AddField(
            model_name="environmentalsubjectanalyzerconfig",
            name="das_tenant",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="core.dastenant"
            ),
        ),
        migrations.AddField(
            model_name="featureproximityanalyzerconfig",
            name="das_tenant",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="core.dastenant"
            ),
        ),
        migrations.AddField(
            model_name="geofenceanalyzerconfig",
            name="das_tenant",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="core.dastenant"
            ),
        ),
        migrations.AddField(
            model_name="immobilityanalyzerconfig",
            name="das_tenant",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="core.dastenant"
            ),
        ),
        migrations.AddField(
            model_name="lowspeedpercentileanalyzerconfig",
            name="das_tenant",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="core.dastenant"
            ),
        ),
        migrations.AddField(
            model_name="lowspeedwilcoxanalyzerconfig",
            name="das_tenant",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="core.dastenant"
            ),
        ),
        migrations.AddField(
            model_name="speeddistro",
            name="das_tenant",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="core.dastenant"
            ),
        ),
        migrations.AddField(
            model_name="subjectanalyzerresult",
            name="das_tenant",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="core.dastenant"
            ),
        ),
        migrations.AddField(
            model_name="subjectproximityanalyzerconfig",
            name="das_tenant",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="core.dastenant"
            ),
        ),
        migrations.AlterField(
            model_name="speeddistro",
            name="subject_speed_profile",
            field=django_multitenant.fields.TenantForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="SpeedDistros",
                to="analyzers.subjectspeedprofile",
            ),
        ),
    ]
