# Generated by Django 3.2.19 on 2023-09-05 21:42
import logging

from django.apps import apps
from django.conf import settings
from django.db import migrations

from core.utils import DASTenantManagement, update_tenant_models

logger = logging.getLogger(__name__)


def populate_tenant_into_models(unused, schema_editor):
    models_names = [
        "SubjectAnalyzerResult",
        "ObservationAnnotator",
        "ImmobilityAnalyzerConfig",
        "GeofenceAnalyzerConfig",
        "FeatureProximityAnalyzerConfig",
        "SubjectProximityAnalyzerConfig",
        "EnvironmentalSubjectAnalyzerConfig",
        "LowSpeedPercentileAnalyzerConfig",
        "LowSpeedWilcoxAnalyzerConfig",
        "SubjectSpeedProfile",
        "SpeedDistro",
        "GlobalForestWatchSubscription",
    ]
    class_models = []

    for model_name in models_names:
        class_models.append(apps.get_model("analyzers", model_name))

    das_tenant_management = DASTenantManagement(domain=settings.SERVER_FQDN)
    tenant = das_tenant_management.get_or_create_tenant()

    if tenant:
        update_tenant_models(models=class_models, tenant=tenant)
    else:
        logger.error("DAS Tenant not found.")


class Migration(migrations.Migration):
    dependencies = [
        ("analyzers", "0044_add_das_tenant_to_analyzers_models"),
    ]

    operations = [
        migrations.RunPython(populate_tenant_into_models, reverse_code=migrations.RunPython.noop),
    ]
