# Generated by Django 3.2.19 on 2023-09-13 00:09

import django_multitenant.fields

import django.db.models.deletion
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("observations", "0146_populate_obsevations_with_tenant"),
        ("analyzers", "0045_populate_das_tenant_to_analyzers_models"),
    ]

    operations = [
        migrations.AlterField(
            model_name="environmentalsubjectanalyzerconfig",
            name="subject_group",
            field=django_multitenant.fields.TenantForeignKey(
                help_text="This analyzer applies to subjects in this Subject Group.",
                on_delete=django.db.models.deletion.CASCADE,
                to="observations.subjectgroup",
                verbose_name="Subject Group",
            ),
        ),
        migrations.AlterField(
            model_name="featureproximityanalyzerconfig",
            name="subject_group",
            field=django_multitenant.fields.TenantForeignKey(
                help_text="This analyzer applies to subjects in this Subject Group.",
                on_delete=django.db.models.deletion.CASCADE,
                to="observations.subjectgroup",
                verbose_name="Subject Group",
            ),
        ),
        migrations.AlterField(
            model_name="geofenceanalyzerconfig",
            name="subject_group",
            field=django_multitenant.fields.TenantForeignKey(
                help_text="This analyzer applies to subjects in this Subject Group.",
                on_delete=django.db.models.deletion.CASCADE,
                to="observations.subjectgroup",
                verbose_name="Subject Group",
            ),
        ),
        migrations.AlterField(
            model_name="immobilityanalyzerconfig",
            name="subject_group",
            field=django_multitenant.fields.TenantForeignKey(
                help_text="This analyzer applies to subjects in this Subject Group.",
                on_delete=django.db.models.deletion.CASCADE,
                to="observations.subjectgroup",
                verbose_name="Subject Group",
            ),
        ),
        migrations.AlterField(
            model_name="lowspeedpercentileanalyzerconfig",
            name="subject_group",
            field=django_multitenant.fields.TenantForeignKey(
                help_text="This analyzer applies to subjects in this Subject Group.",
                on_delete=django.db.models.deletion.CASCADE,
                to="observations.subjectgroup",
                verbose_name="Subject Group",
            ),
        ),
        migrations.AlterField(
            model_name="lowspeedwilcoxanalyzerconfig",
            name="subject_group",
            field=django_multitenant.fields.TenantForeignKey(
                help_text="This analyzer applies to subjects in this Subject Group.",
                on_delete=django.db.models.deletion.CASCADE,
                to="observations.subjectgroup",
                verbose_name="Subject Group",
            ),
        ),
        migrations.AlterField(
            model_name="observationannotator",
            name="subject",
            field=django_multitenant.fields.TenantForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="observations.subject"
            ),
        ),
        migrations.AlterField(
            model_name="subjectanalyzerresult",
            name="subject",
            field=django_multitenant.fields.TenantForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="observations.subject"
            ),
        ),
        migrations.AlterField(
            model_name="subjectproximityanalyzerconfig",
            name="second_subject_group",
            field=django_multitenant.fields.TenantForeignKey(
                help_text="This analyzer applies to subjects in this Subject Group.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subject_group_2",
                to="observations.subjectgroup",
                verbose_name="Subject Group 2",
            ),
        ),
        migrations.AlterField(
            model_name="subjectproximityanalyzerconfig",
            name="subject_group",
            field=django_multitenant.fields.TenantForeignKey(
                help_text="This analyzer applies to subjects in this Subject Group.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subject_group_1",
                to="observations.subjectgroup",
                verbose_name="Subject Group 1",
            ),
        ),
    ]
