# Generated by Django 3.2.21 on 2023-11-07 22:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analyzers", "0047_make_das_tenant_field_required"),
    ]

    operations = [
        migrations.AlterField(
            model_name="environmentalsubjectanalyzerconfig",
            name="name",
            field=models.CharField(
                help_text="A friendly, <b>unique</b> name for the analyzer.",
                max_length=100,
                verbose_name="Analyzer Name",
            ),
        ),
        migrations.AlterField(
            model_name="featureproximityanalyzerconfig",
            name="name",
            field=models.CharField(
                help_text="A friendly, <b>unique</b> name for the analyzer.",
                max_length=100,
                verbose_name="Analyzer Name",
            ),
        ),
        migrations.AlterField(
            model_name="geofenceanalyzerconfig",
            name="name",
            field=models.CharField(
                help_text="A friendly, <b>unique</b> name for the analyzer.",
                max_length=100,
                verbose_name="Analyzer Name",
            ),
        ),
        migrations.AlterField(
            model_name="immobilityanalyzerconfig",
            name="name",
            field=models.CharField(
                help_text="A friendly, <b>unique</b> name for the analyzer.",
                max_length=100,
                verbose_name="Analyzer Name",
            ),
        ),
        migrations.AlterField(
            model_name="lowspeedpercentileanalyzerconfig",
            name="name",
            field=models.CharField(
                help_text="A friendly, <b>unique</b> name for the analyzer.",
                max_length=100,
                verbose_name="Analyzer Name",
            ),
        ),
        migrations.AlterField(
            model_name="lowspeedwilcoxanalyzerconfig",
            name="name",
            field=models.CharField(
                help_text="A friendly, <b>unique</b> name for the analyzer.",
                max_length=100,
                verbose_name="Analyzer Name",
            ),
        ),
        migrations.AlterField(
            model_name="subjectproximityanalyzerconfig",
            name="name",
            field=models.CharField(
                help_text="A friendly, <b>unique</b> name for the analyzer.",
                max_length=100,
                verbose_name="Analyzer Name",
            ),
        ),
        migrations.AddIndex(
            model_name="environmentalsubjectanalyzerconfig",
            index=models.Index(fields=["das_tenant", "name"], name="analyzers_e_das_ten_17c5a2_idx"),
        ),
        migrations.AddIndex(
            model_name="featureproximityanalyzerconfig",
            index=models.Index(fields=["das_tenant", "name"], name="analyzers_f_das_ten_ba58ea_idx"),
        ),
        migrations.AddIndex(
            model_name="geofenceanalyzerconfig",
            index=models.Index(fields=["das_tenant", "name"], name="analyzers_g_das_ten_1c96bd_idx"),
        ),
        migrations.AddIndex(
            model_name="immobilityanalyzerconfig",
            index=models.Index(fields=["das_tenant", "name"], name="analyzers_i_das_ten_4e19ce_idx"),
        ),
        migrations.AddIndex(
            model_name="lowspeedpercentileanalyzerconfig",
            index=models.Index(fields=["das_tenant", "name"], name="analyzers_l_das_ten_9b611f_idx"),
        ),
        migrations.AddIndex(
            model_name="lowspeedwilcoxanalyzerconfig",
            index=models.Index(fields=["das_tenant", "name"], name="analyzers_l_das_ten_fb7f7c_idx"),
        ),
        migrations.AddIndex(
            model_name="subjectproximityanalyzerconfig",
            index=models.Index(fields=["das_tenant", "name"], name="analyzers_s_das_ten_b2db59_idx"),
        ),
        migrations.AddConstraint(
            model_name="environmentalsubjectanalyzerconfig",
            constraint=models.UniqueConstraint(
                fields=("das_tenant", "name"),
                name="analyzers_environmentalsubjectanalyzerconfig_unique_name_across_tenants",
            ),
        ),
        migrations.AddConstraint(
            model_name="featureproximityanalyzerconfig",
            constraint=models.UniqueConstraint(
                fields=("das_tenant", "name"),
                name="analyzers_featureproximityanalyzerconfig_unique_name_across_tenants",
            ),
        ),
        migrations.AddConstraint(
            model_name="geofenceanalyzerconfig",
            constraint=models.UniqueConstraint(
                fields=("das_tenant", "name"), name="analyzers_geofenceanalyzerconfig_unique_name_across_tenants"
            ),
        ),
        migrations.AddConstraint(
            model_name="immobilityanalyzerconfig",
            constraint=models.UniqueConstraint(
                fields=("das_tenant", "name"), name="analyzers_immobilityanalyzerconfig_unique_name_across_tenants"
            ),
        ),
        migrations.AddConstraint(
            model_name="lowspeedpercentileanalyzerconfig",
            constraint=models.UniqueConstraint(
                fields=("das_tenant", "name"),
                name="analyzers_lowspeedpercentileanalyzerconfig_unique_name_across_tenants",
            ),
        ),
        migrations.AddConstraint(
            model_name="lowspeedwilcoxanalyzerconfig",
            constraint=models.UniqueConstraint(
                fields=("das_tenant", "name"), name="analyzers_lowspeedwilcoxanalyzerconfig_unique_name_across_tenants"
            ),
        ),
        migrations.AddConstraint(
            model_name="subjectproximityanalyzerconfig",
            constraint=models.UniqueConstraint(
                fields=("das_tenant", "name"),
                name="analyzers_subjectproximityanalyzerconfig_unique_name_across_tenants",
            ),
        ),
    ]
