# Generated by Django 3.2.21 on 2023-11-16 15:46

import django_multitenant.fields

import django.db.models.deletion
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("observations", "0156_update_field_to_tenantonetoonefield"),
        ("analyzers", "0048_analyzers_models_fields_unique_per_tenant"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subjectspeedprofile",
            name="subject",
            field=django_multitenant.fields.TenantOneToOneField(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="observations.subject"
            ),
        ),
    ]
