# Generated by Django 3.2.21 on 2023-11-19 00:50

from django.db import migrations

import utils.models


class Migration(migrations.Migration):
    dependencies = [
        ("analyzers", "0049_update_field_to_tenantonetoonefield"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="environmentalsubjectanalyzerconfig",
            managers=[
                ("objects", utils.models.CommonTenantManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="featureproximityanalyzerconfig",
            managers=[
                ("objects", utils.models.CommonTenantManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="geofenceanalyzerconfig",
            managers=[
                ("objects", utils.models.CommonTenantManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="immobilityanalyzerconfig",
            managers=[
                ("objects", utils.models.CommonTenantManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="lowspeedpercentileanalyzerconfig",
            managers=[
                ("objects", utils.models.CommonTenantManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="lowspeedwilcoxanalyzerconfig",
            managers=[
                ("objects", utils.models.CommonTenantManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="subjectanalyzerresult",
            managers=[
                ("objects", utils.models.CommonTenantManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="subjectproximityanalyzerconfig",
            managers=[
                ("objects", utils.models.CommonTenantManager()),
            ],
        ),
    ]
