# Generated by Django 3.2.21 on 2023-11-22 22:32

from django.db import migrations

from utils.migrations.update_primary_key import drop_constraint

APP_NAME = "analyzers"


def drop_constraints(apps, schema_editor):
    drop_constraint(
        app=APP_NAME,
        model="FeatureProximityAnalyzerConfig",
        constraint="analyzers_proximitya_proximal_features_id_453c012b_fk_mapping_s",
    )
    drop_constraint(
        app=APP_NAME,
        model="SubjectSpeedProfile",
        constraint="analyzers_subjectspeedprofile_subject_id_key",
    )


class Migration(migrations.Migration):
    dependencies = [
        ("analyzers", "0050_tenantmanager"),
    ]

    operations = [
        migrations.RunPython(code=drop_constraints, reverse_code=migrations.RunPython.noop),
    ]
