# Generated by Django 3.2.21 on 2023-11-24 21:37

from django.db import migrations

import utils.models


class Migration(migrations.Migration):
    dependencies = [
        ("analyzers", "0051_delete_unique_constraints"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="environmentalsubjectanalyzerconfig",
            options={
                "base_manager_name": "objects",
                "default_manager_name": "objects",
                "verbose_name": "Google Earth Engine Analyzer",
                "verbose_name_plural": "Google Earth Engine Analyzers",
            },
        ),
        migrations.AlterModelOptions(
            name="featureproximityanalyzerconfig",
            options={
                "base_manager_name": "objects",
                "default_manager_name": "objects",
                "verbose_name": "Feature Proximity Analyzer",
            },
        ),
        migrations.AlterModelOptions(
            name="geofenceanalyzerconfig",
            options={
                "base_manager_name": "objects",
                "default_manager_name": "objects",
                "verbose_name": "Geofence Analyzer",
                "verbose_name_plural": "Geofence Analyzers",
            },
        ),
        migrations.AlterModelOptions(
            name="immobilityanalyzerconfig",
            options={
                "base_manager_name": "objects",
                "default_manager_name": "objects",
                "verbose_name": "Immobility Analyzer",
                "verbose_name_plural": "Immobility Analyzers",
            },
        ),
        migrations.AlterModelOptions(
            name="lowspeedpercentileanalyzerconfig",
            options={
                "base_manager_name": "objects",
                "default_manager_name": "objects",
                "verbose_name": "Low-Speed Analyzer (Percentile method)",
                "verbose_name_plural": "Low-Speed Analyzers (Percentile method)",
            },
        ),
        migrations.AlterModelOptions(
            name="lowspeedwilcoxanalyzerconfig",
            options={
                "base_manager_name": "objects",
                "default_manager_name": "objects",
                "verbose_name": "Low-Speed Analyzer (Wilcox method)",
                "verbose_name_plural": "Low-Speed Analyzers (Wilcox method)",
            },
        ),
        migrations.AlterModelOptions(
            name="observationannotator",
            options={
                "base_manager_name": "objects",
                "default_manager_name": "objects",
                "verbose_name": "Subject Track Filter",
                "verbose_name_plural": "Subject Track Filters",
            },
        ),
        migrations.AlterModelOptions(
            name="subjectanalyzerresult",
            options={"base_manager_name": "objects", "default_manager_name": "objects"},
        ),
        migrations.AlterModelOptions(
            name="subjectproximityanalyzerconfig",
            options={
                "base_manager_name": "objects",
                "default_manager_name": "objects",
                "verbose_name": "Subject Proximity Analyzer",
            },
        ),
        migrations.AlterModelManagers(
            name="observationannotator",
            managers=[
                ("objects", utils.models.CommonTenantManager()),
            ],
        ),
    ]
