# Generated by Django 3.2.21 on 2023-11-25 00:01

from django.db import migrations

import utils.models


class Migration(migrations.Migration):
    dependencies = [
        ("analyzers", "0052_auto_20231124_1337"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="speeddistro",
            options={"base_manager_name": "objects", "default_manager_name": "objects"},
        ),
        migrations.AlterModelOptions(
            name="subjectspeedprofile",
            options={"base_manager_name": "objects", "default_manager_name": "objects"},
        ),
        migrations.AlterModelManagers(
            name="speeddistro",
            managers=[
                ("objects", utils.models.CommonTenantManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="subjectspeedprofile",
            managers=[
                ("objects", utils.models.CommonTenantManager()),
            ],
        ),
    ]
