# Generated by Django 3.2.21 on 2023-11-25 00:07

from django.db import migrations

import utils.models


class Migration(migrations.Migration):
    dependencies = [
        ("analyzers", "0053_auto_20231124_1601"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="globalforestwatchsubscription",
            options={
                "base_manager_name": "objects",
                "default_manager_name": "objects",
                "verbose_name": "Global Forest Watch Subscription",
                "verbose_name_plural": "Global Forest Watch Subscriptions",
            },
        ),
        migrations.AlterModelManagers(
            name="globalforestwatchsubscription",
            managers=[
                ("objects", utils.models.CommonTenantManager()),
            ],
        ),
    ]
