# Generated by Django 3.2.21 on 2024-03-07 22:16

import uuid
from functools import partial

from django_multitenant.fields import TenantForeignKey

import django.db.models.deletion
from django.db import migrations, models

import utils.migrations.columns
import utils.models
from core.utils import backfill_through_model_with_tenant
from utils.migrations import populate_model_uuid_column
from utils.migrations.update_primary_key import add_tenant_to_primary_key

APP_LABEL = "analyzers"
MODEL_NAME = "subjectanalyzerresultobservations"
CURRENT_TABLE_NAME = "analyzers_subjectanalyzerresult_observations"
NEW_TABLE_NAME = "analyzers_subjectanalyzerresultobservations"

populate_uuid = partial(populate_model_uuid_column, "analyzers", "SubjectAnalyzerResultObservations", "uuid")

populate_through_model_tenant_id = partial(
    backfill_through_model_with_tenant,
    "analyzers_subjectanalyzerresult",
    "id",
    NEW_TABLE_NAME,
    "subjectanalyzerresult_id",
)


def regenerate_primary_keys(apps, schema_editor):
    models = ["SubjectAnalyzerResultObservations"]
    add_tenant_to_primary_key(APP_LABEL, models)


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0022_custom_permissions_migration"),
        ("observations", "0170_sourcegroupsource"),
        ("analyzers", "0054_add_globalforestwatchsubscription_custom_manager"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=f"ALTER TABLE {CURRENT_TABLE_NAME} RENAME TO {NEW_TABLE_NAME}",
                    reverse_sql=f"ALTER TABLE {NEW_TABLE_NAME} RENAME TO {CURRENT_TABLE_NAME}",
                ),
            ],
            state_operations=[
                migrations.CreateModel(
                    name="SubjectAnalyzerResultObservations",
                    fields=[
                        ("id", models.AutoField(serialize=False)),
                        (
                            "subjectanalyzerresult",
                            TenantForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                to="analyzers.SubjectAnalyzerResult",
                            ),
                        ),
                        (
                            "observation",
                            TenantForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                to="observations.Observation",
                            ),
                        ),
                    ],
                ),
                migrations.AlterField(
                    model_name="subjectanalyzerresult",
                    name="observations",
                    field=models.ManyToManyField(
                        to="observations.Observation",
                        related_name="+",
                        through=f"{APP_LABEL}.{MODEL_NAME}",
                        through_fields=("subjectanalyzerresult", "observation"),
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name=MODEL_NAME,
            name="uuid",
            field=models.UUIDField(null=True),
        ),
        migrations.RunPython(
            code=populate_uuid,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name=MODEL_NAME,
            name="id",
        ),
        migrations.RenameField(
            model_name=MODEL_NAME,
            old_name="uuid",
            new_name="id",
        ),
        migrations.AlterField(
            model_name=MODEL_NAME,
            name="id",
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, editable=False, serialize=True),
        ),
        migrations.AlterModelManagers(
            name=MODEL_NAME,
            managers=[
                ("objects", utils.models.CommonTenantManager()),
            ],
        ),
        migrations.AlterModelOptions(
            name=MODEL_NAME,
            options={"base_manager_name": "objects", "default_manager_name": "objects"},
        ),
        migrations.AddField(
            model_name=MODEL_NAME,
            name="das_tenant",
            field=models.ForeignKey(
                default=utils.migrations.columns.default_tenant_id,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.dastenant",
            ),
        ),
        migrations.RunPython(
            code=regenerate_primary_keys,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RunPython(
            code=populate_through_model_tenant_id,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name=MODEL_NAME,
            constraint=models.UniqueConstraint(
                fields=["das_tenant", "subjectanalyzerresult", "observation"],
                name="analyzers_subjectanalyzerresultobservations_tenant_from_to_unique",
            ),
        ),
    ]
