# Generated by Django 3.2.21 on 2024-07-18 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0025_add_export_permission_set_and_permission"),
        ("analyzers", "0055_add_custom_through_table_for_subjectanalyzerresult_and_observation"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="subjectanalyzerresult",
            index=models.Index(
                fields=["subject_analyzer_id", "subject", "das_tenant"],
                name="analyzers_s_subject_c9e0f9_idx",
            ),
        ),
    ]
