# Generated by Django 3.2.21 on 2024-07-18 16:23

import django.db.models.deletion
from django.db import migrations, models

import utils.migrations.columns


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0025_add_export_permission_set_and_permission"),
        ("analyzers", "0055_add_custom_through_table_for_subjectanalyzerresult_and_observation"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="subjectanalyzerresult",
            index=models.Index(
                fields=["das_tenant", "subject_analyzer_id", "subject", "-estimated_time"],
                name="analyzers_s_das_ten_1b6998_idx",
            ),
        ),
        migrations.AlterModelOptions(
            name="subjectanalyzerresultobservations",
            options={},
        ),
        migrations.AlterField(
            model_name="subjectanalyzerresultobservations",
            name="das_tenant",
            field=models.ForeignKey(
                default=utils.migrations.columns.default_tenant_id,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="analyzers_subjectanalyzerresultobservations",
                to="core.dastenant",
            ),
        ),
    ]
