# Generated by Django 3.2.21 on 2024-07-03 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0025_add_export_permission_set_and_permission"),
        ("analyzers", "0055_add_custom_through_table_for_subjectanalyzerresult_and_observation"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="subjectanalyzerresult",
            index=models.Index(
                fields=["subject_analyzer_id", "subject"],
                name="analyzers_s_subject_43eace_idx",
            ),
        ),
    ]
