# Generated by Django 3.2.25 on 2026-02-13 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analyzers", "0056_ad_index_to_subject_analyzer_id_subject_in_subjectanalyzerresult"),
    ]

    operations = [
        migrations.AddField(
            model_name="geofenceanalyzerconfig",
            name="trigger_on_corner_clip",
            field=models.BooleanField(
                default=True,
                help_text="If enabled, the analyzer will trigger events when a subject's path clips a corner of a geofence (going out and back in without an observation point being logged outside the fence). It will create a geofence event for every point where their line crossed the fence.",
                verbose_name="Trigger on corner clip",
            ),
        ),
    ]
