# Generated by Django 3.2.25 on 2026-02-11 01:24

import uuid

import django_multitenant.mixins

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models

import core.fields
import utils.migrations.columns
import utils.models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0030_token"),
        ("observations", "0199_vicuna"),
        ("analyzers", "0056_ad_index_to_subject_analyzer_id_subject_in_subjectanalyzerresult"),
    ]

    operations = [
        migrations.CreateModel(
            name="ObservationAttributeAnalyzerConfig",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                (
                    "name",
                    models.CharField(
                        help_text="A friendly, <b>unique</b> name for the analyzer.",
                        max_length=100,
                        verbose_name="Analyzer Name",
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "schedule",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=50),
                        blank=True,
                        default=list,
                        null=True,
                        size=None,
                        verbose_name="Array of crontab schedule patterns that an analyzer can use to determine whether to run.",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this analyzer is active. Set this False instead of deleting this record.",
                        verbose_name="active",
                    ),
                ),
                (
                    "search_time_hours",
                    models.FloatField(
                        default=24.0,
                        help_text="Analysis will be performed on recent data within this time frame.",
                        verbose_name="Analysis time frame (hours)",
                    ),
                ),
                ("additional", models.JSONField(blank=True, default=dict)),
                (
                    "quiet_period",
                    models.DurationField(
                        blank=True,
                        help_text="This will be used to override the configured quiet period.",
                        null=True,
                        verbose_name="Quiet period (HH:MM:SS)",
                    ),
                ),
                (
                    "attribute_name",
                    models.CharField(
                        help_text="Name of the observation attribute to analyze.",
                        max_length=100,
                        verbose_name="Attribute Name",
                    ),
                ),
                (
                    "true_if_null",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the rule should be evaluated as having been met if no observations are found with non-null values for the target attribute.",
                    ),
                ),
                (
                    "aggregation",
                    models.CharField(
                        choices=[
                            ("all", "All"),
                            ("mean", "Mean"),
                            ("median", "Median"),
                            ("min", "Minimum"),
                            ("max", "Maximum"),
                            ("range", "Range"),
                            ("stdev", "Standard Deviation"),
                        ],
                        default="all",
                        max_length=20,
                    ),
                ),
                (
                    "adjust_to_order_of_magnitude",
                    models.IntegerField(
                        blank=True,
                        help_text="If present, non-zero attribute values are multiplied by successive powers of 10 until they are above this threshold before evaluating their values.",
                        null=True,
                    ),
                ),
                (
                    "das_tenant",
                    models.ForeignKey(
                        default=utils.migrations.columns.default_tenant_id,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.dastenant",
                    ),
                ),
                (
                    "subject_group",
                    core.fields.CompoundTenantForeignKey(
                        help_text="This analyzer applies to subjects in this Subject Group.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="observations.subjectgroup",
                        verbose_name="Subject Group",
                    ),
                ),
            ],
            options={
                "verbose_name": "Observation Attribute Analyzer",
                "verbose_name_plural": "Observation Attribute Analyzers",
                "abstract": False,
                "base_manager_name": "objects",
                "default_manager_name": "objects",
            },
            bases=(django_multitenant.mixins.TenantModelMixin, models.Model),
            managers=[
                ("objects", utils.models.CommonTenantManager()),
            ],
        ),
        migrations.AddIndex(
            model_name="observationattributeanalyzerconfig",
            index=models.Index(fields=["das_tenant", "name"], name="analyzers_o_das_ten_2c575b_idx"),
        ),
        migrations.AddConstraint(
            model_name="observationattributeanalyzerconfig",
            constraint=models.UniqueConstraint(
                fields=("das_tenant", "name"),
                name="analyzers_observationattributeanalyzerconfig_unique_name_across_tenants",
            ),
        ),
    ]
