# Generated by Django 3.2.25 on 2026-03-12 01:05

import django_multitenant.fields

import django.db.models.deletion
from django.db import migrations, models

import core.fields


class Migration(migrations.Migration):

    dependencies = [
        ("mapping", "0076_rename_feature_class_permissions"),
        ("analyzers", "0060_subjectanalyzerresult_event"),
    ]

    operations = [
        migrations.AddField(
            model_name="environmentalsubjectanalyzerconfig",
            name="feature_group_filter",
            field=core.fields.CompoundTenantForeignKey(
                blank=True,
                help_text="When set, events will only be created for detections that occur within the spatial features of this Feature Group.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="mapping.spatialfeaturegroupstatic",
                verbose_name="Feature Group Filter",
            ),
        ),
        migrations.AddField(
            model_name="featureproximityanalyzerconfig",
            name="feature_group_filter",
            field=core.fields.CompoundTenantForeignKey(
                blank=True,
                help_text="When set, events will only be created for detections that occur within the spatial features of this Feature Group.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="mapping.spatialfeaturegroupstatic",
                verbose_name="Feature Group Filter",
            ),
        ),
        migrations.AddField(
            model_name="geofenceanalyzerconfig",
            name="feature_group_filter",
            field=core.fields.CompoundTenantForeignKey(
                blank=True,
                help_text="When set, events will only be created for detections that occur within the spatial features of this Feature Group.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="mapping.spatialfeaturegroupstatic",
                verbose_name="Feature Group Filter",
            ),
        ),
        migrations.AddField(
            model_name="immobilityanalyzerconfig",
            name="feature_group_filter",
            field=core.fields.CompoundTenantForeignKey(
                blank=True,
                help_text="When set, events will only be created for detections that occur within the spatial features of this Feature Group.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="mapping.spatialfeaturegroupstatic",
                verbose_name="Feature Group Filter",
            ),
        ),
        migrations.AddField(
            model_name="lowspeedpercentileanalyzerconfig",
            name="feature_group_filter",
            field=core.fields.CompoundTenantForeignKey(
                blank=True,
                help_text="When set, events will only be created for detections that occur within the spatial features of this Feature Group.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="mapping.spatialfeaturegroupstatic",
                verbose_name="Feature Group Filter",
            ),
        ),
        migrations.AddField(
            model_name="lowspeedwilcoxanalyzerconfig",
            name="feature_group_filter",
            field=core.fields.CompoundTenantForeignKey(
                blank=True,
                help_text="When set, events will only be created for detections that occur within the spatial features of this Feature Group.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="mapping.spatialfeaturegroupstatic",
                verbose_name="Feature Group Filter",
            ),
        ),
        migrations.AddField(
            model_name="observationattributeanalyzerconfig",
            name="feature_group_filter",
            field=core.fields.CompoundTenantForeignKey(
                blank=True,
                help_text="When set, events will only be created for detections that occur within the spatial features of this Feature Group.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="mapping.spatialfeaturegroupstatic",
                verbose_name="Feature Group Filter",
            ),
        ),
        migrations.AddField(
            model_name="subjectproximityanalyzerconfig",
            name="feature_group_filter",
            field=core.fields.CompoundTenantForeignKey(
                blank=True,
                help_text="When set, events will only be created for detections that occur within the spatial features of this Feature Group.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="mapping.spatialfeaturegroupstatic",
                verbose_name="Feature Group Filter",
            ),
        ),
        migrations.RemoveIndex(
            model_name="movementclusteranalyzerconfig",
            name="analyzers_m_das_ten_mvclst_idx",
        ),
        migrations.AddField(
            model_name="movementclusteranalyzerconfig",
            name="feature_group_filter",
            field=core.fields.CompoundTenantForeignKey(
                blank=True,
                help_text="When set, events will only be created for detections that occur within the spatial features of this Feature Group.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="mapping.spatialfeaturegroupstatic",
                verbose_name="Feature Group Filter",
            ),
        ),
        migrations.AlterField(
            model_name="movementclusteranalyzerconfig",
            name="min_cluster_duration_seconds",
            field=models.IntegerField(
                default=3600,
                help_text="Minimum time span a cluster must cover before it is reported as a significant event.  Clusters with a shorter duration are ignored.",
                verbose_name="Minimum Cluster Duration (seconds)",
            ),
        ),
        migrations.AlterField(
            model_name="movementclusteranalyzerconfig",
            name="subject_group",
            field=django_multitenant.fields.TenantForeignKey(
                help_text="This analyzer applies to subjects in this Subject Group.",
                on_delete=django.db.models.deletion.CASCADE,
                to="observations.subjectgroup",
                verbose_name="Subject Group",
            ),
        ),
        migrations.AlterField(
            model_name="subjectanalyzerresult",
            name="event",
            field=django_multitenant.fields.TenantForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="analyzer_results",
                to="activity.event",
            ),
        ),
        migrations.AddIndex(
            model_name="movementclusteranalyzerconfig",
            index=models.Index(fields=["das_tenant", "name"], name="analyzers_m_das_ten_5ecf10_idx"),
        ),
    ]
