# Generated by Django 4.2.28 on 2026-02-16 15:01

import uuid

import django.db.models.deletion
from django.db import migrations, models

import utils.migrations.columns


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0031_django_42"),
        ("observations", "0207_django_42"),
        ("analyzers", "0061_add_feature_group_filter"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subjectanalyzerresult",
            name="observations",
            field=models.ManyToManyField(
                related_name="+", through="analyzers.SubjectAnalyzerResultObservations", to="observations.observation"
            ),
        ),
        migrations.AlterField(
            model_name="subjectanalyzerresultobservations",
            name="das_tenant",
            field=models.ForeignKey(
                default=utils.migrations.columns.default_tenant_id,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s",
                to="core.dastenant",
            ),
        ),
        migrations.AlterField(
            model_name="subjectanalyzerresultobservations",
            name="id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
