# Generated by Django 4.2.30 on 2026-06-30 11:14

from django.db import migrations, models

import analyzers.models.proximity


class Migration(migrations.Migration):

    dependencies = [
        ("analyzers", "0064_add_analyzer_name_to_analyzer_eventtype_schemas"),
    ]

    operations = [
        migrations.AlterField(
            model_name="featureproximityanalyzerconfig",
            name="threshold_dist_meters",
            field=models.FloatField(
                default=500.0,
                help_text="A proximity event occurs when a subject's path passes within this distance of a designated spatial feature. <br/>A subject's path is drawn using a straight line between reported positions.",
                validators=[analyzers.models.proximity.validate_positive],
                verbose_name="Proximity Distance (meters)",
            ),
        ),
        migrations.AlterField(
            model_name="subjectproximityanalyzerconfig",
            name="threshold_dist_meters",
            field=models.FloatField(
                default=100.0,
                help_text="A proximity event will only occur when either subject's path passes within this distance of the other subject. A subject's path is drawn using a straight line between reported positions.",
                validators=[analyzers.models.proximity.validate_positive],
                verbose_name="Proximity Distance (meters)",
            ),
        ),
    ]
