# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-07 04:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations
from django.utils import crypto, timezone

# Functions from the following migrations need manual copying.
# Move them and any dependencies into this file, then update the
# RunPython operations to refer to the local versions:
# das_server.migrations.0001_initial
# das_server.migrations.0002_add_kml_application


def load_default_clients(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    User = apps.get_model(settings.AUTH_USER_MODEL)
    Application = apps.get_model(settings.OAUTH2_PROVIDER_APPLICATION_MODEL)

    if not User.objects.using(db_alias).filter(username="das_oauth_act").exists():
        user = User.objects.using(db_alias).get_or_create(
            username="das_oauth_act",
            email="das_oauth_act@das.org",
            first_name="das",
            last_name="oauth",
            password=crypto.get_random_string(length=12),
            is_active=False,
            last_login=timezone.now(),
        )[0]

        Application.objects.using(db_alias).get_or_create(
            client_id="das_web_client",
            client_type="Confidential",
            authorization_grant_type="password",
            client_secret="",
            name="DAS Web",
            skip_authorization=True,
            user=user,
        )

        Application.objects.using(db_alias).get_or_create(
            client_id="das_ios_client",
            client_type="Confidential",
            authorization_grant_type="password",
            client_secret="",
            name="DAS IOS App",
            skip_authorization=True,
            user=user,
        )

        Application.objects.using(db_alias).get_or_create(
            client_id="das_kml_export",
            client_type="Confidential",
            authorization_grant_type="password",
            client_secret="",
            name="DAS KML",
            skip_authorization=True,
            user=user,
        )


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0007_add_oauth_custom_models"),
    ]

    operations = [
        migrations.RunPython(load_default_clients),
    ]
