# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-07 04:34
from __future__ import unicode_literals

from oauth2_provider.models import Application

from django.contrib.auth import get_user_model
from django.db import migrations
from django.utils import crypto, timezone

# Functions from the following migrations need manual copying.
# Move them and any dependencies into this file, then update the
# RunPython operations to refer to the local versions:
# das_server.migrations.0001_initial
# das_server.migrations.0002_add_kml_application


def load_default_clients(apps, schema_editor):
    User = get_user_model()

    if not User.objects.filter(username='das_oauth_act').exists():
        user = User(username='das_oauth_act',
                    email='das_oauth_act@das.org',
                    first_name='das',
                    last_name='oauth',
                    password=crypto.get_random_string(length=12),
                    is_active=False,
                    last_login=timezone.now())
        user.save()

        #Application = apps.get_model('oauth2_provider.Application')

        Application(client_id='das_web_client',
                    client_type='Confidential',
                    authorization_grant_type='password',
                    client_secret='',
                    name='DAS Web',
                    skip_authorization=True,
                    user=user
                    ).save()
        Application(client_id='das_ios_client',
                    client_type='Confidential',
                    authorization_grant_type='password',
                    client_secret='',
                    name='DAS IOS App',
                    skip_authorization=True,
                    user=user
                    ).save()

        Application(client_id='das_kml_export',
                    client_type='Confidential',
                    authorization_grant_type='password',
                    client_secret='',
                    name='DAS KML',
                    skip_authorization=True,
                    user=user
                    ).save()


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('oauth2_provider', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_default_clients),
    ]
