# Generated by Django 2.0.13 on 2020-01-31 13:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('das_server', '0001_squashed_0002_add_kml_application'),
    ]

    operations = [
        migrations.CreateModel(
            name='EULA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version_number', models.DecimalField(decimal_places=2, default=1.0, max_digits=6, unique=True)),
                ('content', models.TextField(blank=True, help_text="Provide users with some info about what's changed and why", null=True)),
                ('active', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserAgreement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date_accepted', models.DateTimeField(auto_now_add=True, verbose_name='Date Accepted')),
                ('accepted', models.BooleanField(default=False)),
                ('eula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userterms', to='das_server.EULA')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userterms', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='eula',
            name='users',
            field=models.ManyToManyField(blank=True, through='das_server.UserAgreement', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='useragreement',
            unique_together={('user', 'eula')},
        ),
    ]
