# Generated by Django 2.2.14 on 2020-07-15 22:51

from django.db import migrations


def load_default_clients(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    Application = apps.get_model('oauth2_provider.Application')

    defaults = dict(
        client_type='Confidential',
        authorization_grant_type='password',
        client_secret='',
        name='ER Track',
        skip_authorization=True
    )
    Application.objects.using(db_alias).get_or_create(
        client_id='er_mobile_tracker',
        defaults=defaults)

    defaults = dict(
        client_type='Confidential',
        authorization_grant_type='password',
        client_secret='',
        name='CyberTracker',
        skip_authorization=True
    )
    Application.objects.using(db_alias).get_or_create(
        client_id='cybertracker',
        defaults=defaults)
    

class Migration(migrations.Migration):

    dependencies = [
        ('das_server', '0001_squashed_0002_add_kml_application'),
    ]

    operations = [
        migrations.RunPython(load_default_clients,
                             reverse_code=migrations.RunPython.noop),
    ]
