# Generated by Django 2.0.13 on 2020-02-10 18:13

from django.db import migrations
from django.core import management


def update_eula(apps, schema_editor):
    management.call_command("update_eula", version_number=1.0,
                            eula="https://earthranger.com/EULA",
                            sla="https://earthranger.com/SLA"
                            )


class Migration(migrations.Migration):

    dependencies = [
        ('das_server', '0002_added_eula'),
    ]

    operations = [
        migrations.RunPython(update_eula)
    ]
