# Generated by Django 3.1 on 2022-06-22 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usercontent', '0002_jsonfield_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filecontentrevision',
            name='data',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='imagefilecontentrevision',
            name='data',
            field=models.JSONField(default=dict),
        ),
    ]
