# Generated by Django 3.2.19 on 2023-09-13 19:58

import django_multitenant.fields

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0008_migrate_oauth_tables_to_das_custom_models"),
        ("usercontent", "0003_use_models_JSONField_instead_postgres_fields_JSONField"),
    ]

    operations = [
        migrations.AddField(
            model_name="filecontent",
            name="das_tenant",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="core.dastenant"
            ),
        ),
        migrations.AddField(
            model_name="imagefilecontent",
            name="das_tenant",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="core.dastenant"
            ),
        ),
        migrations.AlterField(
            model_name="filecontent",
            name="created_by",
            field=django_multitenant.fields.TenantForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="file_contents",
                related_query_name="file_content",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="imagefilecontent",
            name="created_by",
            field=django_multitenant.fields.TenantForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="imagefile_contents",
                related_query_name="imagefile_content",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="filecontent",
            unique_together={("id", "das_tenant")},
        ),
        migrations.AlterUniqueTogether(
            name="imagefilecontent",
            unique_together={("id", "das_tenant")},
        ),
    ]
