# Generated by Django 3.2.19 on 2023-09-13 20:05
import logging

from django.apps import apps
from django.conf import settings
from django.db import migrations

from core.utils import DASTenantManagement, update_tenant_models

logger = logging.getLogger(__name__)


def update_tenant_models_on_usercontent_models(unused, schema_editor) -> None:
    FileContent = apps.get_model("usercontent", "FileContent")
    ImageFileContent = apps.get_model("usercontent", "ImageFileContent")

    class_models = [FileContent, ImageFileContent]

    das_tenant_management = DASTenantManagement(domain=settings.SERVER_FQDN)
    tenant = das_tenant_management.get_or_create_tenant()

    if tenant:
        update_tenant_models(models=class_models, tenant=tenant)
    else:
        logger.error("DAS Tenant not found.")


class Migration(migrations.Migration):
    dependencies = [
        ("usercontent", "0004_add_tenant_id_tenant_foreign_key"),
    ]

    operations = [
        migrations.RunPython(code=update_tenant_models_on_usercontent_models, reverse_code=migrations.RunPython.noop)
    ]
