# Generated by Django 3.2.19 on 2023-09-27 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_populate_oauth_models_with_tenant"),
        ("usercontent", "0005_populate_tenant_foreign_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="filecontentrevision",
            name="das_tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="usercontent_filecontentrevision",
                to="core.dastenant",
            ),
        ),
        migrations.AddField(
            model_name="imagefilecontentrevision",
            name="das_tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="usercontent_imagefilecontentrevision",
                to="core.dastenant",
            ),
        ),
        migrations.AddConstraint(
            model_name="filecontentrevision",
            constraint=models.UniqueConstraint(
                fields=("das_tenant", "id"), name="usercontent_filecontentrevision_tenant_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="imagefilecontentrevision",
            constraint=models.UniqueConstraint(
                fields=("das_tenant", "id"), name="usercontent_imagefilecontentrevision_tenant_unique"
            ),
        ),
    ]
