# Generated by Django 3.2.19 on 2023-09-27 20:29

import django.db.models.deletion
from django.db import migrations, models

from utils.migrations.update_primary_key import add_tenant_to_primary_key

usercontent_models = ["FileContent", "ImageFileContent"]


def regenerate_primary_keys(apps, schema_editor):
    add_tenant_to_primary_key("usercontent", usercontent_models)


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_populate_oauth_models_with_tenant"),
        ("usercontent", "0005_populate_tenant_foreign_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="filecontentrevision",
            name="das_tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="usercontent_filecontentrevision",
                to="core.dastenant",
            ),
        ),
        migrations.AddField(
            model_name="imagefilecontentrevision",
            name="das_tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="usercontent_imagefilecontentrevision",
                to="core.dastenant",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="filecontent",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="imagefilecontent",
            unique_together=set(),
        ),
        migrations.RunPython(code=regenerate_primary_keys, reverse_code=migrations.RunPython.noop),
    ]
