# Generated by Django 3.2.19 on 2023-10-13 19:10

import django.db.models.deletion
from django.db import migrations, models

import utils.migrations.columns


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0011_regenerate_primary_keys"),
        ("usercontent", "0007_populate_usercontent_revision_models_with_tenant"),
    ]

    operations = [
        migrations.AlterField(
            model_name="filecontent",
            name="das_tenant",
            field=models.ForeignKey(
                default=utils.migrations.columns.default_tenant_id,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.dastenant",
            ),
        ),
        migrations.AlterField(
            model_name="imagefilecontent",
            name="das_tenant",
            field=models.ForeignKey(
                default=utils.migrations.columns.default_tenant_id,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.dastenant",
            ),
        ),
    ]
