# Generated by Django 3.2.21 on 2023-11-16 19:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0013_auto_20231115_1758"),
        ("usercontent", "0009_auto_20231016_0852"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="filecontentrevision",
            unique_together={("das_tenant", "object_id", "sequence")},
        ),
        migrations.AlterUniqueTogether(
            name="imagefilecontentrevision",
            unique_together={("das_tenant", "object_id", "sequence")},
        ),
    ]
