# Generated by Django 3.2.21 on 2023-11-20 17:50

from django.db import migrations

import utils.models


class Migration(migrations.Migration):
    dependencies = [
        ("usercontent", "0010_auto_20231116_1118"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="filecontent",
            managers=[
                ("objects", utils.models.CommonTenantManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="imagefilecontent",
            managers=[
                ("objects", utils.models.CommonTenantManager()),
            ],
        ),
    ]
