# Generated by Django 3.2.21 on 2023-11-24 20:58

from django.db import migrations

from utils.migrations.update_primary_key import add_tenant_to_primary_key

APP_NAME = "usercontent"

models = [
    "ImageFileContentRevision",
]


def regenerate_primary_keys(apps, schema_editor):
    add_tenant_to_primary_key(APP_NAME, models)


class Migration(migrations.Migration):
    dependencies = [
        ("usercontent", "0012_filecontentrevision_regenerate_pk"),
    ]

    operations = [
        migrations.RunPython(code=regenerate_primary_keys, reverse_code=migrations.RunPython.noop),
    ]
