# Generated by Django 3.2.21 on 2025-01-10 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("usercontent", "0012_filecontentrevision_regenerate_pk"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="filecontent",
            options={"base_manager_name": "objects", "default_manager_name": "objects"},
        ),
        migrations.AlterModelOptions(
            name="imagefilecontent",
            options={"base_manager_name": "objects", "default_manager_name": "objects"},
        ),
    ]
