# Generated for ERA-9210: increase FileContent.file max_length to 512 to match
# ImageFileContent.file and accommodate full storage paths generated by chunked uploads.

from django.db import migrations, models

import usercontent.models


class Migration(migrations.Migration):

    dependencies = [
        ("usercontent", "0013_base_manager_update"),
    ]

    operations = [
        migrations.AlterField(
            model_name="filecontent",
            name="file",
            field=models.FileField(max_length=512, upload_to=usercontent.models.file_content_upload_to),
        ),
    ]
