# Generated by Django 4.2.28 on 2026-02-16 15:01

import django.db.models.deletion
from django.db import migrations, models

import utils.migrations.columns


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0031_django_42"),
        ("usercontent", "0014_filecontent_file_max_length"),
    ]

    operations = [
        migrations.AlterField(
            model_name="filecontentrevision",
            name="das_tenant",
            field=models.ForeignKey(
                default=utils.migrations.columns.default_tenant_id,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s",
                to="core.dastenant",
            ),
        ),
        migrations.AlterField(
            model_name="imagefilecontentrevision",
            name="das_tenant",
            field=models.ForeignKey(
                default=utils.migrations.columns.default_tenant_id,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s",
                to="core.dastenant",
            ),
        ),
    ]
