# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-29 00:10
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('observations', '0006_auto_20160105_1055'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavannahPlugin',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('min_time', models.TimeField(null=True)),
                ('max_time', models.TimeField(null=True)),
                ('status', models.CharField(default='enabled', max_length=15)),
                ('additional', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('service_user_id', models.CharField(help_text='The username for querying the Savannah Tracking service.', max_length=50)),
                ('service_password', models.CharField(help_text='The password for querying the Savannah Tracking service.', max_length=50)),
                ('service_api_host', models.CharField(help_text='the ip-address or host-name for the Savannah Tracking service.', max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SourcePlugin',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('plugin_id', models.UUIDField()),
                ('cursor_data', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('status', models.CharField(default='enabled', max_length=15)),
                ('plugin_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_plugins', related_query_name='source_plugin', to='observations.Source')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
