# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-29 20:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourceplugin',
            name='last_run',
            field=models.DateTimeField(default=datetime.datetime(2016, 1, 29, 20, 43, 31, 259600, tzinfo=utc), verbose_name='Timestamp for when this plugin last executed.'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='savannahplugin',
            name='status',
            field=models.CharField(choices=[('enabled', 'Enabled'), ('disabled', 'Disabled')], default='enabled', max_length=15),
        ),
    ]
