# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-29 23:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0002_auto_20160129_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourceplugin',
            name='last_run',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Timestamp for when this plugin last executed.'),
        ),
    ]
