# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-03 18:49
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0002_spidertracksplugin'),
    ]

    operations = [
        migrations.CreateModel(
            name='AWETelemetryPlugin',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, null=True, unique=True, verbose_name='Unique name to identify the plugin.')),
                ('status', models.CharField(choices=[('enabled', 'Enabled'), ('disabled', 'Disabled')], default='enabled', max_length=15)),
                ('additional', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('service_username', models.CharField(help_text='The username for querying the AWE Telemetry/AWT service.', max_length=50)),
                ('service_password', models.CharField(help_text='The password for querying the AWE Telemetry/AWT service.', max_length=50)),
                ('service_url', models.CharField(help_text='the ip-address or host-name for the AWE Telemetry/AWT service.', max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
