# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-05-18 20:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0003_awetelemetryplugin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='awetelemetryplugin',
            name='service_url',
            field=models.CharField(help_text='The API endpoint for the AWE Telemetry/AWT service.', max_length=50),
        ),
        migrations.AlterField(
            model_name='sourceplugin',
            name='last_run',
            field=models.DateTimeField(default=datetime.datetime(2000, 1, 1, 0, 0, tzinfo=utc),
                                       verbose_name='Timestamp for when this plugin last executed.'),
        ),
    ]
