# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-30 00:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0002_map'),
        ('tracking', '0004_auto_20160129_2346'),
    ]

    operations = [
        migrations.AddField(
            model_name='demosubjectplugin',
            name='range_polygon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mapping.PolygonFeature'),
        ),
    ]
