# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-06-22 16:51
from __future__ import unicode_literals

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracking", "0004_source_provider"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sourceplugin",
            name="last_run",
            field=models.DateTimeField(
                default=datetime.datetime(2000, 1, 1, 0, 0, tzinfo=datetime.timezone.utc),
                verbose_name="Timestamp for when this plugin last executed.",
            ),
        ),
    ]
