# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-07-20 23:05
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import observations.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0039_auto_20170622_2305'),
        ('tracking', '0005_source_plugin_last_run_default'),
    ]

    operations = [
        migrations.CreateModel(
            name='SirtrackPlugin',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4,
                                        primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, null=True, unique=True,
                                          verbose_name='Unique name to identify the plugin.')),
                ('status', models.CharField(choices=[
                 ('enabled', 'Enabled'), ('disabled', 'Disabled')], default='enabled', max_length=15)),
                ('additional', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('service_username', models.CharField(
                    help_text='The username for querying the SirTrack service.', max_length=50)),
                ('service_password', models.CharField(
                    help_text='The password for querying the SirTrack service.', max_length=50)),
                ('service_api', models.CharField(
                    help_text='The API endpoint for SirTrack data.', max_length=50)),
                ('provider', models.ForeignKey(default=observations.models.get_default_source_provider_id,
                                               on_delete=django.db.models.deletion.CASCADE, related_name='+', to='observations.SourceProvider')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
