# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-01 19:46
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0006_inreachplugin'),
    ]

    operations = [
        migrations.CreateModel(
            name='AWTHttpPlugin',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, null=True, unique=True, verbose_name='Unique name to identify the plugin.')),
                ('min_time', models.TimeField(null=True)),
                ('max_time', models.TimeField(null=True)),
                ('status', models.CharField(choices=[('enabled', 'Enabled'), ('disabled', 'Disabled')], default='enabled', max_length=15)),
                ('additional', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('service_api_url', models.URLField(default='http://www.yrless.co.za/STE/yrserv/datanew.phtml', help_text='The URL for the AWT service.')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
