# Generated by Django 2.0.1 on 2018-01-18 22:01

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.query_utils
import observations.models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0006_sirtrack'),
    ]

    operations = [
        migrations.AlterField(
            model_name='awetelemetryplugin',
            name='provider',
            field=models.ForeignKey(default=observations.models.get_default_source_provider_id,
                                    on_delete=django.db.models.deletion.PROTECT, related_name='+', to='observations.SourceProvider'),
        ),
        migrations.AlterField(
            model_name='awthttpplugin',
            name='provider',
            field=models.ForeignKey(default=observations.models.get_default_source_provider_id,
                                    on_delete=django.db.models.deletion.PROTECT, related_name='+', to='observations.SourceProvider'),
        ),
        migrations.AlterField(
            model_name='demosourceplugin',
            name='provider',
            field=models.ForeignKey(default=observations.models.get_default_source_provider_id,
                                    on_delete=django.db.models.deletion.PROTECT, related_name='+', to='observations.SourceProvider'),
        ),
        migrations.AlterField(
            model_name='demosourceplugin',
            name='range_polygon',
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.PROTECT, to='mapping.PolygonFeature'),
        ),
        migrations.AlterField(
            model_name='firmsplugin',
            name='provider',
            field=models.ForeignKey(default=observations.models.get_default_source_provider_id,
                                    on_delete=django.db.models.deletion.PROTECT, related_name='+', to='observations.SourceProvider'),
        ),
        migrations.AlterField(
            model_name='inreachkmlplugin',
            name='provider',
            field=models.ForeignKey(default=observations.models.get_default_source_provider_id,
                                    on_delete=django.db.models.deletion.PROTECT, related_name='+', to='observations.SourceProvider'),
        ),
        migrations.AlterField(
            model_name='inreachplugin',
            name='provider',
            field=models.ForeignKey(default=observations.models.get_default_source_provider_id,
                                    on_delete=django.db.models.deletion.PROTECT, related_name='+', to='observations.SourceProvider'),
        ),
        migrations.AlterField(
            model_name='savannahplugin',
            name='provider',
            field=models.ForeignKey(default=observations.models.get_default_source_provider_id,
                                    on_delete=django.db.models.deletion.PROTECT, related_name='+', to='observations.SourceProvider'),
        ),
        migrations.AlterField(
            model_name='sirtrackplugin',
            name='provider',
            field=models.ForeignKey(default=observations.models.get_default_source_provider_id,
                                    on_delete=django.db.models.deletion.PROTECT, related_name='+', to='observations.SourceProvider'),
        ),
        migrations.AlterField(
            model_name='skygisticssatelliteplugin',
            name='provider',
            field=models.ForeignKey(default=observations.models.get_default_source_provider_id,
                                    on_delete=django.db.models.deletion.PROTECT, related_name='+', to='observations.SourceProvider'),
        ),
        migrations.AlterField(
            model_name='sourceplugin',
            name='plugin_type',
            field=models.ForeignKey(limit_choices_to=django.db.models.query_utils.Q(django.db.models.query_utils.Q(('app_label', 'tracking'), ('model', 'savannahplugin'), _connector='AND'), django.db.models.query_utils.Q(('app_label', 'tracking'), ('model', 'inreachplugin'), _connector='AND'), django.db.models.query_utils.Q(('app_label', 'tracking'), ('model', 'demosourceplugin'), _connector='AND'), django.db.models.query_utils.Q(('app_label', 'tracking'), ('model', 'awthttpplugin'), _connector='AND'), django.db.models.query_utils.Q(('app_label', 'tracking'), (
                'model', 'inreachkmlplugin'), _connector='AND'), django.db.models.query_utils.Q(('app_label', 'tracking'), ('model', 'skygisticssatelliteplugin'), _connector='AND'), django.db.models.query_utils.Q(('app_label', 'tracking'), ('model', 'firmsplugin'), _connector='AND'), django.db.models.query_utils.Q(('app_label', 'tracking'), ('model', 'spidertracksplugin'), _connector='AND'), django.db.models.query_utils.Q(('app_label', 'tracking'), ('model', 'awetelemetryplugin'), _connector='AND'), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='spidertracksplugin',
            name='provider',
            field=models.ForeignKey(default=observations.models.get_default_source_provider_id,
                                    on_delete=django.db.models.deletion.PROTECT, related_name='+', to='observations.SourceProvider'),
        ),
    ]
