# Generated by Django 2.0.2 on 2018-03-28 04:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0013_post-django2-upgrade'),
        ('tracking', '0007_post-django2-upgrade'),
    ]

    operations = [
        migrations.AddField(
            model_name='firmsplugin',
            name='firms_region_name',
            field=models.CharField(default='Northern_and_Central_Africa',
                                   help_text='Earthdata FIRMS region name from which to fetch active fire observations.', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='firmsplugin',
            name='spatial_feature_group',
            field=models.ForeignKey(help_text='FIRMS data will be filtered by boundaries in this group.', null=True,
                                    on_delete=django.db.models.deletion.PROTECT, related_name='+', to='mapping.SpatialFeatureGroupStatic'),
        ),
    ]
