# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-01 20:57
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0008_inreachkmlplugin'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkygisticsSatellitePlugin',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, null=True, unique=True, verbose_name='Unique name to identify the plugin.')),
                ('min_time', models.TimeField(null=True)),
                ('max_time', models.TimeField(null=True)),
                ('status', models.CharField(choices=[('enabled', 'Enabled'), ('disabled', 'Disabled')], default='enabled', max_length=15)),
                ('additional', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('service_user_id', models.CharField(help_text='The username for Skygistics API.', max_length=50)),
                ('service_password', models.CharField(help_text='The password for Skygistics API.', max_length=50)),
                ('service_api_url', models.CharField(default='http://skyq1.skygistics.com', help_text='API endpoint for Skygistics service.', max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
