# Generated by Django 2.0.2 on 2018-06-22 21:22

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.query_utils


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0008_firms_spatial_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firmsplugin',
            name='firms_region_name',
            field=models.CharField(choices=[('Alaska', 'Alaska'), ('Australia_NewZealand', 'Australia_NewZealand'), ('Canada', 'Canada'), ('Central_America', 'Central_America'), ('Europe', 'Europe'), ('Global', 'Global'), ('Northern_and_Central_Africa', 'Northern_and_Central_Africa'), ('Russia_Asia', 'Russia_Asia'), ('SouthEast_Asia', 'SouthEast_Asia'), ('South_America', 'South_America'), ('South_Asia', 'South_Asia'), (
                'Southern_Africa', 'Southern_Africa'), ('USA_contiguous_and_Hawaii', 'USA_contiguous_and_Hawaii')], help_text="Earthdata FIRMS region name from which to fetch active fire observations. This is the region published\n    by NASA's Earthdata platform. See this link for more details: https://earthdata.nasa.gov/earth-observation-data/near-real-time/firms/active-fire-data.\n    ", max_length=100),
        ),
        migrations.AlterField(
            model_name='sourceplugin',
            name='plugin_type',
            field=models.ForeignKey(limit_choices_to=django.db.models.query_utils.Q(django.db.models.query_utils.Q(('app_label', 'tracking'), ('model', 'savannahplugin'), _connector='AND'), django.db.models.query_utils.Q(('app_label', 'tracking'), ('model', 'inreachplugin'), _connector='AND'), django.db.models.query_utils.Q(('app_label', 'tracking'), ('model', 'demosourceplugin'), _connector='AND'), django.db.models.query_utils.Q(('app_label', 'tracking'), ('model', 'awthttpplugin'), _connector='AND'), django.db.models.query_utils.Q(
                ('app_label', 'tracking'), ('model', 'inreachkmlplugin'), _connector='AND'), django.db.models.query_utils.Q(('app_label', 'tracking'), ('model', 'skygisticssatelliteplugin'), _connector='AND'), django.db.models.query_utils.Q(('app_label', 'tracking'), ('model', 'spidertracksplugin'), _connector='AND'), django.db.models.query_utils.Q(('app_label', 'tracking'), ('model', 'awetelemetryplugin'), _connector='AND'), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
    ]
