# Generated by Django 2.0.6 on 2018-09-30 13:55

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import observations.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0060_vectronics'),
        ('tracking', '0009_jsonfield_default'),
    ]

    operations = [
        migrations.CreateModel(
            name='VectronicsPlugin',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4,
                                        primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, null=True, unique=True,
                                          verbose_name='Unique name to identify the plugin.')),
                ('status', models.CharField(choices=[
                 ('enabled', 'Enabled'), ('disabled', 'Disabled')], default='enabled', max_length=15)),
                ('additional', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('provider', models.ForeignKey(default=observations.models.get_default_source_provider_id,
                                               on_delete=django.db.models.deletion.PROTECT, related_name='+', to='observations.SourceProvider')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='sourceplugin',
            name='plugin_type',
            field=models.ForeignKey(limit_choices_to=models.Q(models.Q(('app_label', 'tracking'), ('model', 'savannahplugin')), models.Q(('app_label', 'tracking'), ('model', 'inreachplugin')), models.Q(('app_label', 'tracking'), ('model', 'demosourceplugin')), models.Q(('app_label', 'tracking'), ('model', 'awthttpplugin')), models.Q(('app_label', 'tracking'), ('model', 'inreachkmlplugin')), models.Q(
                ('app_label', 'tracking'), ('model', 'skygisticssatelliteplugin')), models.Q(('app_label', 'tracking'), ('model', 'spidertracksplugin')), models.Q(('app_label', 'tracking'), ('model', 'awetelemetryplugin')), models.Q(('app_label', 'tracking'), ('model', 'vectronicsplugin')), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
    ]
