# Generated by Django 2.0.2 on 2018-11-08 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0011_awt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sirtrackplugin',
            name='service_api',
            field=models.CharField(default='https://data.sirtrack.com',
                                   help_text='The API endpoint for SirTrack data.', max_length=50),
        ),
    ]
