# Generated by Django 2.0.2 on 2019-01-13 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0012_sirtrack_defaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='firmsplugin',
            name='app_key',
            field=models.CharField(blank=True, help_text='App Key for accessing data on NASA server.', max_length=50),
        ),
    ]
