# Generated by Django 2.0.2 on 2019-01-14 18:04

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0013_firms_updates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firmsplugin',
            name='service_password',
        ),
        migrations.RemoveField(
            model_name='firmsplugin',
            name='service_username',
        ),
        migrations.AlterField(
            model_name='awetelemetryplugin',
            name='additional',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='awthttpplugin',
            name='additional',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='awtplugin',
            name='additional',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='demosourceplugin',
            name='additional',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='firmsplugin',
            name='additional',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='firmsplugin',
            name='app_key',
            field=models.CharField(blank=True, help_text="You'll need an App Key in order to get data from NASA's EarthData website. \n    Visit https://nrt4.modaps.eosdis.nasa.gov/, create a Profile, and generate an App Key (available in the Profile menu).", max_length=50),
        ),
        migrations.AlterField(
            model_name='inreachkmlplugin',
            name='additional',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='inreachplugin',
            name='additional',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='savannahplugin',
            name='additional',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='sirtrackplugin',
            name='additional',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='skygisticssatelliteplugin',
            name='additional',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='spidertracksplugin',
            name='additional',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='vectronicsplugin',
            name='additional',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
    ]
