# Generated by Django 2.0.2 on 2019-04-21 01:04

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0014_removing_firms_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inreachkmlplugin',
            options={'verbose_name': 'inReach Personal plugin',
                     'verbose_name_plural': 'inReach Personal plugins'},
        ),
        migrations.AlterModelOptions(
            name='inreachplugin',
            options={'verbose_name': 'inReach Professional plugin',
                     'verbose_name_plural': 'inReach Professional plugins'},
        ),
        migrations.AlterField(
            model_name='sourceplugin',
            name='cursor_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True, default=dict),
        ),
    ]
