# Generated by Django 2.2.9 on 2020-11-19 22:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0084_addax'),
        ('tracking', '0015_inreach'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackConfiguration',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('new_device_config', models.CharField(choices=[('create_new', 'Create a new subject'), ('use_existing', 'Use existing matching subject')], default='use_existing', help_text='Specifies whether to create a new subject or use an existing one when setting up a new device.', max_length=50, verbose_name='New device setting')),
                ('name_change_config', models.CharField(choices=[('create_new', 'Create a new subject'), ('use_existing', 'Use existing matching subject'), ('update_name', 'Update the name of the existing subject')], default='use_existing', help_text='Specifies whether to update the existing subject name, create a new subject, or reassign to an existing matching subject when changing the device name.', max_length=50, verbose_name='Name change setting')),
                ('name_change_excluded_subject_types', models.ManyToManyField(default='wildlife', help_text='Select any Subject Types to exclude from matching', related_name='name_change_excluded_subject_types', to='observations.SubjectType')),
                ('new_subject_excluded_subject_types', models.ManyToManyField(default='wildlife', help_text='Select any Subject Types to exclude from matching', related_name='new_subject_excluded_subject_types', to='observations.SubjectType')),
            ],
            options={
                'verbose_name': 'EarthRanger Track Configuration',
            },
        ),
    ]
