# Generated by Django 2.2.9 on 2020-12-15 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0016_track_configuration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackconfiguration',
            name='name_change_config',
            field=models.CharField(choices=[('create_new', 'Create a new subject'), ('use_existing', 'Use existing matching subject'), ('update_name', 'Update the name of the existing subject')], default='use_existing', help_text='Specifies whether to update the existing subject name, create a new subject, or reassign to an existing subject with a name that matches the new device name.', max_length=50, verbose_name='Name change setting'),
        ),
        migrations.AlterField(
            model_name='trackconfiguration',
            name='name_change_excluded_subject_types',
            field=models.ManyToManyField(blank=True, default='wildlife', related_name='name_change_excluded_subject_types', to='observations.SubjectType', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='trackconfiguration',
            name='new_device_config',
            field=models.CharField(choices=[('create_new', 'Create a new subject'), ('use_existing', 'Use existing matching subject')], default='use_existing', help_text='Specifies whether to create a new subject or use an existing one with a name that matches the device name when setting up a new device.', max_length=50, verbose_name='New device setting'),
        ),
        migrations.AlterField(
            model_name='trackconfiguration',
            name='new_subject_excluded_subject_types',
            field=models.ManyToManyField(blank=True, default='wildlife', related_name='new_subject_excluded_subject_types', to='observations.SubjectType', verbose_name=''),
        ),
    ]
