# Generated by Django 2.2.9 on 2020-11-25 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0016_track_configuration'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackconfiguration',
            name='configuration_type',
            field=models.CharField(choices=[('default_config', 'Default Configuration')], default='default_config', max_length=50),
        ),
        migrations.AddConstraint(
            model_name='trackconfiguration',
            constraint=models.UniqueConstraint(condition=models.Q(configuration_type='default_config'), fields=('configuration_type',), name='default_track_configuration'),
        ),
    ]
