# Generated by Django 2.2.9 on 2020-12-14 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0086_er_track_source_provider'),
        ('tracking', '0016_track_configuration'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackconfiguration',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='default subject group'),
        ),
        migrations.AddField(
            model_name='trackconfiguration',
            name='source_provider',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='observations.SourceProvider'),
        ),
        migrations.AlterField(
            model_name='trackconfiguration',
            name='name_change_excluded_subject_types',
            field=models.ManyToManyField(blank=True, default='wildlife', help_text='Select any Subject Types to exclude from matching', related_name='name_change_excluded_subject_types', to='observations.SubjectType'),
        ),
        migrations.AlterField(
            model_name='trackconfiguration',
            name='new_subject_excluded_subject_types',
            field=models.ManyToManyField(blank=True, default='wildlife', help_text='Select any Subject Types to exclude from matching', related_name='new_subject_excluded_subject_types', to='observations.SubjectType'),
        ),
        migrations.AddConstraint(
            model_name='trackconfiguration',
            constraint=models.UniqueConstraint(condition=models.Q(is_default=True), fields=('is_default',), name='default_track_config'),
        ),
    ]
