# Generated by Django 2.2.9 on 2020-11-24 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0017_track_configuration_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackconfiguration',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Set as the default configuration.', verbose_name='default configuration'),
        ),
    ]
