# Generated by Django 2.2.9 on 2020-12-22 21:55

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0087_er_track_source_provider'),
        ('tracking', '0017_track_configuration_default'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceProviderConfiguration',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('new_device_config', models.CharField(choices=[('create_new', 'Create a new subject'), ('use_existing', 'Use existing matching subject')], default='use_existing', help_text='Specifies whether to create a new subject or use an existing one with a name that matches the device name when setting up a new device.', max_length=50, verbose_name='New device setting')),
                ('name_change_config', models.CharField(choices=[('create_new', 'Create a new subject'), ('use_existing', 'Use existing matching subject'), ('update_name', 'Update the name of the existing subject')], default='use_existing', help_text='Specifies whether to update the existing subject name, create a new subject, or reassign to an existing subject with a name that matches the new device name.', max_length=50, verbose_name='Name change setting')),
                ('is_default', models.BooleanField(default=False, help_text='Used this as the default configuration', verbose_name='Use as default?')),
                ('name_change_excluded_subject_types', models.ManyToManyField(blank=True, default='wildlife', related_name='name_change_excluded_subject_types', to='observations.SubjectType', verbose_name='')),
                ('new_subject_excluded_subject_types', models.ManyToManyField(blank=True, default='wildlife', related_name='new_subject_excluded_subject_types', to='observations.SubjectType', verbose_name='')),
                ('source_provider', models.OneToOneField(blank=True, help_text='This configuration will be used for this SourceProvider', null=True, on_delete=django.db.models.deletion.SET_NULL, to='observations.SourceProvider')),
            ],
            options={
                'verbose_name': 'EarthRanger Track Configuration',
            },
        ),
        migrations.DeleteModel(
            name='TrackConfiguration',
        ),
        migrations.AddConstraint(
            model_name='sourceproviderconfiguration',
            constraint=models.UniqueConstraint(condition=models.Q(is_default=True), fields=('is_default',), name='default_track_config'),
        ),
    ]
