# Generated by Django 2.2.9 on 2021-02-09 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0019_default_track_configuration'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourceproviderconfiguration',
            name='name_change_match_case',
            field=models.BooleanField(
                default=False, verbose_name='Match case'),
        ),
        migrations.AddField(
            model_name='sourceproviderconfiguration',
            name='new_device_match_case',
            field=models.BooleanField(
                default=False, verbose_name='Match case'),
        ),
    ]
