# Generated by Django 2.2.14 on 2021-06-22 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0020_track_config_match_case'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firmsplugin',
            name='app_key',
            field=models.CharField(
                blank=True, help_text="You'll need an App Key in order to get data from NASA's EarthData website. \n    Visit https://nrt4.modaps.eosdis.nasa.gov/, create a Profile, and generate an App Key (available in the Profile menu).", max_length=1024),
        ),
    ]
