# Generated by Django 2.2.14 on 2021-07-09 04:33
from django.db import migrations


def forwards(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("tracking", "0021_appkey"),
    ]

    operations = [migrations.RunPython(forwards, migrations.RunPython.noop)]
