# Generated by Django 2.2.14 on 2021-07-09 04:33

from django.db import migrations

FIRMS_SCHEMA = """{
    "schema": 
    {
        "$schema": "http://json-schema.org/draft-04/schema#",
        "title": "FIRMS Fire Report Schema",
      
        "type": "object",

        "properties": 
        {
        "bright_ti4": {
            "type": "number",
            "title": "VIIRS I-4 channel brightness (Kelvin)"
        },
        "bright_ti5": {
            "type": "number",
            "title": "VIIRS I-5 channel brightness (Kelvin)"
        },
        "scan": {
            "type": "number",
            "title": "VIIRS Scan"
        },
        "track": {
            "type": "number",
            "title": "Satellite Track"
        },
        "confidence": {
            "type": "string",
            "title": "FIRMS Confidence"
        },
        "frp": {
            "type": "number",
            "title": "Fire Radiative Power (MW)"
        }
    }
  },
  "definition": [
    "confidence",
    "frp",
    "bright_ti4",
    "bright_ti5",
    "scan",
    "track"
  ]
}"""


def forwards(apps, schema_editor):
    EventCategory = apps.get_model('activity', 'EventCategory')
    EventType = apps.get_model('activity', 'EventType')

    db_alias = schema_editor.connection.alias

    category, created = EventCategory.objects.using(db_alias).get_or_create(
        value='analyzer_event',
        defaults={"display": "Analyzer Event",
                  "ordernum": 1})

    firms_defaults = {'schema': FIRMS_SCHEMA, 'display': 'FIRMS Report',
                      'category_id': category.id, 'icon': 'firms_rep'}

    EventType.objects.using(db_alias).update_or_create(
        value="firms_rep",
        defaults=firms_defaults
    )


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0021_appkey'),
    ]

    operations = [
        migrations.RunPython(forwards, migrations.RunPython.noop)
    ]
