# Generated by Django 3.1 on 2022-06-22 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0022_firms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='awetelemetryplugin',
            name='additional',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='awthttpplugin',
            name='additional',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='awtplugin',
            name='additional',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='demosourceplugin',
            name='additional',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='firmsplugin',
            name='additional',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='inreachkmlplugin',
            name='additional',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='inreachplugin',
            name='additional',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='savannahplugin',
            name='additional',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='sirtrackplugin',
            name='additional',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='skygisticssatelliteplugin',
            name='additional',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='sourceplugin',
            name='cursor_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='spidertracksplugin',
            name='additional',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='vectronicsplugin',
            name='additional',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
