# Generated by Django 3.2.19 on 2023-08-23 16:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracking", "0023_use_models_JSONField_instead_postgres_fields_JSONField"),
    ]

    operations = [
        migrations.AlterField(
            model_name="firmsplugin",
            name="app_key",
            field=models.CharField(
                blank=True,
                help_text="You'll need an App Key in order to get data from NASA's EarthData website.\n    Visit https://nrt4.modaps.eosdis.nasa.gov/, create a Profile, and generate an App Key (available in the Profile menu).",
                max_length=1024,
            ),
        ),
    ]
