# Generated by Django 3.2.19 on 2023-09-15 22:10

import django_multitenant.fields

import django.db.models.deletion
from django.db import migrations, models

import observations.models


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("observations", "0144_populate_das_tenant_in_subject_model"),
        ("mapping", "0040_change_arcgisconfiguration_pk_type_to_uuid"),
        ("core", "0008_migrate_oauth_tables_to_das_custom_models"),
        ("tracking", "0024_alter_firmsplugin_app_key"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="sourceproviderconfiguration",
            name="default_track_config",
        ),
        migrations.AddField(
            model_name="awetelemetryplugin",
            name="das_tenant",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="core.dastenant"
            ),
        ),
        migrations.AddField(
            model_name="awthttpplugin",
            name="das_tenant",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="core.dastenant"
            ),
        ),
        migrations.AddField(
            model_name="awtplugin",
            name="das_tenant",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="core.dastenant"
            ),
        ),
        migrations.AddField(
            model_name="demosourceplugin",
            name="das_tenant",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="core.dastenant"
            ),
        ),
        migrations.AddField(
            model_name="firmsplugin",
            name="das_tenant",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="core.dastenant"
            ),
        ),
        migrations.AddField(
            model_name="inreachkmlplugin",
            name="das_tenant",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="core.dastenant"
            ),
        ),
        migrations.AddField(
            model_name="inreachplugin",
            name="das_tenant",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="core.dastenant"
            ),
        ),
        migrations.AddField(
            model_name="savannahplugin",
            name="das_tenant",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="core.dastenant"
            ),
        ),
        migrations.AddField(
            model_name="sirtrackplugin",
            name="das_tenant",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="core.dastenant"
            ),
        ),
        migrations.AddField(
            model_name="skygisticssatelliteplugin",
            name="das_tenant",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="core.dastenant"
            ),
        ),
        migrations.AddField(
            model_name="sourceplugin",
            name="das_tenant",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="core.dastenant"
            ),
        ),
        migrations.AddField(
            model_name="sourceproviderconfiguration",
            name="das_tenant",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="core.dastenant"
            ),
        ),
        migrations.AddField(
            model_name="spidertracksplugin",
            name="das_tenant",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="core.dastenant"
            ),
        ),
        migrations.AddField(
            model_name="vectronicsplugin",
            name="das_tenant",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="core.dastenant"
            ),
        ),
        migrations.AlterField(
            model_name="awetelemetryplugin",
            name="provider",
            field=django_multitenant.fields.TenantForeignKey(
                default=observations.models.get_default_source_provider_id,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="observations.sourceprovider",
            ),
        ),
        migrations.AlterField(
            model_name="awthttpplugin",
            name="provider",
            field=django_multitenant.fields.TenantForeignKey(
                default=observations.models.get_default_source_provider_id,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="observations.sourceprovider",
            ),
        ),
        migrations.AlterField(
            model_name="awtplugin",
            name="provider",
            field=django_multitenant.fields.TenantForeignKey(
                default=observations.models.get_default_source_provider_id,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="observations.sourceprovider",
            ),
        ),
        migrations.AlterField(
            model_name="demosourceplugin",
            name="provider",
            field=django_multitenant.fields.TenantForeignKey(
                default=observations.models.get_default_source_provider_id,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="observations.sourceprovider",
            ),
        ),
        migrations.AlterField(
            model_name="firmsplugin",
            name="provider",
            field=django_multitenant.fields.TenantForeignKey(
                default=observations.models.get_default_source_provider_id,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="observations.sourceprovider",
            ),
        ),
        migrations.AlterField(
            model_name="firmsplugin",
            name="spatial_feature_group",
            field=django_multitenant.fields.TenantForeignKey(
                help_text="FIRMS data will be filtered by boundaries in this group.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="mapping.spatialfeaturegroupstatic",
            ),
        ),
        migrations.AlterField(
            model_name="inreachkmlplugin",
            name="provider",
            field=django_multitenant.fields.TenantForeignKey(
                default=observations.models.get_default_source_provider_id,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="observations.sourceprovider",
            ),
        ),
        migrations.AlterField(
            model_name="inreachplugin",
            name="provider",
            field=django_multitenant.fields.TenantForeignKey(
                default=observations.models.get_default_source_provider_id,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="observations.sourceprovider",
            ),
        ),
        migrations.AlterField(
            model_name="savannahplugin",
            name="provider",
            field=django_multitenant.fields.TenantForeignKey(
                default=observations.models.get_default_source_provider_id,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="observations.sourceprovider",
            ),
        ),
        migrations.AlterField(
            model_name="sirtrackplugin",
            name="provider",
            field=django_multitenant.fields.TenantForeignKey(
                default=observations.models.get_default_source_provider_id,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="observations.sourceprovider",
            ),
        ),
        migrations.AlterField(
            model_name="skygisticssatelliteplugin",
            name="provider",
            field=django_multitenant.fields.TenantForeignKey(
                default=observations.models.get_default_source_provider_id,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="observations.sourceprovider",
            ),
        ),
        migrations.AlterField(
            model_name="sourceplugin",
            name="plugin_type",
            field=django_multitenant.fields.TenantForeignKey(
                limit_choices_to=models.Q(
                    models.Q(("app_label", "tracking"), ("model", "savannahplugin")),
                    models.Q(("app_label", "tracking"), ("model", "inreachplugin")),
                    models.Q(("app_label", "tracking"), ("model", "demosourceplugin")),
                    models.Q(("app_label", "tracking"), ("model", "awthttpplugin")),
                    models.Q(("app_label", "tracking"), ("model", "inreachkmlplugin")),
                    models.Q(("app_label", "tracking"), ("model", "skygisticssatelliteplugin")),
                    models.Q(("app_label", "tracking"), ("model", "spidertracksplugin")),
                    models.Q(("app_label", "tracking"), ("model", "awetelemetryplugin")),
                    models.Q(("app_label", "tracking"), ("model", "vectronicsplugin")),
                    models.Q(("app_label", "tracking"), ("model", "awtplugin")),
                    _connector="OR",
                ),
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AlterField(
            model_name="sourceplugin",
            name="source",
            field=django_multitenant.fields.TenantForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="source_plugins",
                related_query_name="source_plugin",
                to="observations.source",
            ),
        ),
        migrations.AlterField(
            model_name="spidertracksplugin",
            name="provider",
            field=django_multitenant.fields.TenantForeignKey(
                default=observations.models.get_default_source_provider_id,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="observations.sourceprovider",
            ),
        ),
        migrations.AlterField(
            model_name="vectronicsplugin",
            name="provider",
            field=django_multitenant.fields.TenantForeignKey(
                default=observations.models.get_default_source_provider_id,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="observations.sourceprovider",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="awetelemetryplugin",
            unique_together={("id", "das_tenant")},
        ),
        migrations.AlterUniqueTogether(
            name="awthttpplugin",
            unique_together={("id", "das_tenant")},
        ),
        migrations.AlterUniqueTogether(
            name="awtplugin",
            unique_together={("id", "das_tenant")},
        ),
        migrations.AlterUniqueTogether(
            name="demosourceplugin",
            unique_together={("id", "das_tenant")},
        ),
        migrations.AlterUniqueTogether(
            name="firmsplugin",
            unique_together={("id", "das_tenant")},
        ),
        migrations.AlterUniqueTogether(
            name="savannahplugin",
            unique_together={("id", "das_tenant")},
        ),
        migrations.AlterUniqueTogether(
            name="sirtrackplugin",
            unique_together={("id", "das_tenant")},
        ),
        migrations.AlterUniqueTogether(
            name="skygisticssatelliteplugin",
            unique_together={("id", "das_tenant")},
        ),
        migrations.AlterUniqueTogether(
            name="sourceplugin",
            unique_together={("id", "das_tenant")},
        ),
        migrations.AlterUniqueTogether(
            name="spidertracksplugin",
            unique_together={("id", "das_tenant")},
        ),
        migrations.AlterUniqueTogether(
            name="vectronicsplugin",
            unique_together={("id", "das_tenant")},
        ),
        migrations.AddConstraint(
            model_name="sourceproviderconfiguration",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_default", True)),
                fields=("is_default", "das_tenant"),
                name="default_track_config",
            ),
        ),
        migrations.AddConstraint(
            model_name="sourceproviderconfiguration",
            constraint=models.UniqueConstraint(fields=("id", "das_tenant"), name="tenant_id"),
        ),
    ]
