# Generated by Django 3.2.19 on 2023-09-15 22:10
import logging

from django.conf import settings
from django.db import migrations

from core.utils import DASTenantManagement, update_tenant_models

logger = logging.getLogger(__name__)


def update_tenant_models_on_tracking_models(apps, schema_editor) -> None:
    AWETelemetryPlugin = apps.get_model("tracking", "AWETelemetryPlugin")
    AWTHttpPlugin = apps.get_model("tracking", "AWTHttpPlugin")
    AwtPlugin = apps.get_model("tracking", "AwtPlugin")
    DemoSourcePlugin = apps.get_model("tracking", "DemoSourcePlugin")
    FirmsPlugin = apps.get_model("tracking", "FirmsPlugin")
    InreachPlugin = apps.get_model("tracking", "InreachPlugin")
    InreachKMLPlugin = apps.get_model("tracking", "InreachKMLPlugin")
    SavannahPlugin = apps.get_model("tracking", "SavannahPlugin")
    SirtrackPlugin = apps.get_model("tracking", "SirtrackPlugin")
    SkygisticsSatellitePlugin = apps.get_model("tracking", "SkygisticsSatellitePlugin")
    SourcePlugin = apps.get_model("tracking", "SourcePlugin")
    SourceProviderConfiguration = apps.get_model("tracking", "SourceProviderConfiguration")
    SpiderTracksPlugin = apps.get_model("tracking", "SpiderTracksPlugin")
    VectronicsPlugin = apps.get_model("tracking", "VectronicsPlugin")

    das_tenant_management = DASTenantManagement(domain=settings.SERVER_FQDN)
    tenant = das_tenant_management.get_or_create_tenant()

    class_models = [
        AWETelemetryPlugin,
        AWTHttpPlugin,
        AwtPlugin,
        DemoSourcePlugin,
        FirmsPlugin,
        InreachPlugin,
        InreachKMLPlugin,
        SavannahPlugin,
        SirtrackPlugin,
        SkygisticsSatellitePlugin,
        SourcePlugin,
        SourceProviderConfiguration,
        SpiderTracksPlugin,
        VectronicsPlugin,
    ]

    if not tenant:
        logger.error("DAS Tenant not found.")
        return
    update_tenant_models(models=class_models, tenant=tenant)


class Migration(migrations.Migration):
    dependencies = [
        ("tracking", "0025_add_tenant_id_tenant_foreign_key"),
    ]

    operations = [
        migrations.RunPython(
            code=update_tenant_models_on_tracking_models,
            reverse_code=migrations.RunPython.noop,
        )
    ]
