# Generated by Django 3.2.19 on 2023-09-18 23:20

import django.db.models.deletion
from django.db import migrations, models

import observations.models


class Migration(migrations.Migration):
    dependencies = [
        ("observations", "0144_populate_das_tenant_in_subject_model"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("mapping", "0040_change_arcgisconfiguration_pk_type_to_uuid"),
        ("tracking", "0026_populate_tenant_foreign_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="awetelemetryplugin",
            name="provider",
            field=models.ForeignKey(
                default=observations.models.get_default_source_provider_id,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="observations.sourceprovider",
            ),
        ),
        migrations.AlterField(
            model_name="awthttpplugin",
            name="provider",
            field=models.ForeignKey(
                default=observations.models.get_default_source_provider_id,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="observations.sourceprovider",
            ),
        ),
        migrations.AlterField(
            model_name="awtplugin",
            name="provider",
            field=models.ForeignKey(
                default=observations.models.get_default_source_provider_id,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="observations.sourceprovider",
            ),
        ),
        migrations.AlterField(
            model_name="demosourceplugin",
            name="provider",
            field=models.ForeignKey(
                default=observations.models.get_default_source_provider_id,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="observations.sourceprovider",
            ),
        ),
        migrations.AlterField(
            model_name="firmsplugin",
            name="provider",
            field=models.ForeignKey(
                default=observations.models.get_default_source_provider_id,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="observations.sourceprovider",
            ),
        ),
        migrations.AlterField(
            model_name="firmsplugin",
            name="spatial_feature_group",
            field=models.ForeignKey(
                help_text="FIRMS data will be filtered by boundaries in this group.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="mapping.spatialfeaturegroupstatic",
            ),
        ),
        migrations.AlterField(
            model_name="inreachkmlplugin",
            name="provider",
            field=models.ForeignKey(
                default=observations.models.get_default_source_provider_id,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="observations.sourceprovider",
            ),
        ),
        migrations.AlterField(
            model_name="inreachplugin",
            name="provider",
            field=models.ForeignKey(
                default=observations.models.get_default_source_provider_id,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="observations.sourceprovider",
            ),
        ),
        migrations.AlterField(
            model_name="savannahplugin",
            name="provider",
            field=models.ForeignKey(
                default=observations.models.get_default_source_provider_id,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="observations.sourceprovider",
            ),
        ),
        migrations.AlterField(
            model_name="sirtrackplugin",
            name="provider",
            field=models.ForeignKey(
                default=observations.models.get_default_source_provider_id,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="observations.sourceprovider",
            ),
        ),
        migrations.AlterField(
            model_name="skygisticssatelliteplugin",
            name="provider",
            field=models.ForeignKey(
                default=observations.models.get_default_source_provider_id,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="observations.sourceprovider",
            ),
        ),
        migrations.AlterField(
            model_name="sourceplugin",
            name="plugin_type",
            field=models.ForeignKey(
                limit_choices_to=models.Q(
                    models.Q(("app_label", "tracking"), ("model", "savannahplugin")),
                    models.Q(("app_label", "tracking"), ("model", "inreachplugin")),
                    models.Q(("app_label", "tracking"), ("model", "demosourceplugin")),
                    models.Q(("app_label", "tracking"), ("model", "awthttpplugin")),
                    models.Q(("app_label", "tracking"), ("model", "inreachkmlplugin")),
                    models.Q(("app_label", "tracking"), ("model", "skygisticssatelliteplugin")),
                    models.Q(("app_label", "tracking"), ("model", "spidertracksplugin")),
                    models.Q(("app_label", "tracking"), ("model", "awetelemetryplugin")),
                    models.Q(("app_label", "tracking"), ("model", "vectronicsplugin")),
                    models.Q(("app_label", "tracking"), ("model", "awtplugin")),
                    _connector="OR",
                ),
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AlterField(
            model_name="sourceplugin",
            name="source",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="source_plugins",
                related_query_name="source_plugin",
                to="observations.source",
            ),
        ),
        migrations.AlterField(
            model_name="spidertracksplugin",
            name="provider",
            field=models.ForeignKey(
                default=observations.models.get_default_source_provider_id,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="observations.sourceprovider",
            ),
        ),
        migrations.AlterField(
            model_name="vectronicsplugin",
            name="provider",
            field=models.ForeignKey(
                default=observations.models.get_default_source_provider_id,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="observations.sourceprovider",
            ),
        ),
    ]
