# Generated by Django 3.2.21 on 2023-11-07 22:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracking", "0029_make_das_tenant_field_required"),
    ]

    operations = [
        migrations.AlterField(
            model_name="awetelemetryplugin",
            name="name",
            field=models.CharField(max_length=50, null=True, verbose_name="Unique name to identify the plugin."),
        ),
        migrations.AlterField(
            model_name="awthttpplugin",
            name="name",
            field=models.CharField(max_length=50, null=True, verbose_name="Unique name to identify the plugin."),
        ),
        migrations.AlterField(
            model_name="awtplugin",
            name="name",
            field=models.CharField(max_length=50, null=True, verbose_name="Unique name to identify the plugin."),
        ),
        migrations.AlterField(
            model_name="demosourceplugin",
            name="name",
            field=models.CharField(max_length=50, null=True, verbose_name="Unique name to identify the plugin."),
        ),
        migrations.AlterField(
            model_name="firmsplugin",
            name="name",
            field=models.CharField(max_length=50, null=True, verbose_name="Unique name to identify the plugin."),
        ),
        migrations.AlterField(
            model_name="inreachkmlplugin",
            name="name",
            field=models.CharField(max_length=50, null=True, verbose_name="Unique name to identify the plugin."),
        ),
        migrations.AlterField(
            model_name="inreachplugin",
            name="name",
            field=models.CharField(max_length=50, null=True, verbose_name="Unique name to identify the plugin."),
        ),
        migrations.AlterField(
            model_name="savannahplugin",
            name="name",
            field=models.CharField(max_length=50, null=True, verbose_name="Unique name to identify the plugin."),
        ),
        migrations.AlterField(
            model_name="sirtrackplugin",
            name="name",
            field=models.CharField(max_length=50, null=True, verbose_name="Unique name to identify the plugin."),
        ),
        migrations.AlterField(
            model_name="skygisticssatelliteplugin",
            name="name",
            field=models.CharField(max_length=50, null=True, verbose_name="Unique name to identify the plugin."),
        ),
        migrations.AlterField(
            model_name="spidertracksplugin",
            name="name",
            field=models.CharField(max_length=50, null=True, verbose_name="Unique name to identify the plugin."),
        ),
        migrations.AlterField(
            model_name="vectronicsplugin",
            name="name",
            field=models.CharField(max_length=50, null=True, verbose_name="Unique name to identify the plugin."),
        ),
        migrations.AddIndex(
            model_name="awetelemetryplugin",
            index=models.Index(fields=["das_tenant", "name"], name="tracking_aw_das_ten_766ade_idx"),
        ),
        migrations.AddIndex(
            model_name="awthttpplugin",
            index=models.Index(fields=["das_tenant", "name"], name="tracking_aw_das_ten_16b05a_idx"),
        ),
        migrations.AddIndex(
            model_name="awtplugin",
            index=models.Index(fields=["das_tenant", "name"], name="tracking_aw_das_ten_314613_idx"),
        ),
        migrations.AddIndex(
            model_name="demosourceplugin",
            index=models.Index(fields=["das_tenant", "name"], name="tracking_de_das_ten_040b53_idx"),
        ),
        migrations.AddIndex(
            model_name="firmsplugin",
            index=models.Index(fields=["das_tenant", "name"], name="tracking_fi_das_ten_ac5382_idx"),
        ),
        migrations.AddIndex(
            model_name="inreachkmlplugin",
            index=models.Index(fields=["das_tenant", "name"], name="tracking_in_das_ten_703dd9_idx"),
        ),
        migrations.AddIndex(
            model_name="inreachplugin",
            index=models.Index(fields=["das_tenant", "name"], name="tracking_in_das_ten_3f085e_idx"),
        ),
        migrations.AddIndex(
            model_name="savannahplugin",
            index=models.Index(fields=["das_tenant", "name"], name="tracking_sa_das_ten_9126bb_idx"),
        ),
        migrations.AddIndex(
            model_name="sirtrackplugin",
            index=models.Index(fields=["das_tenant", "name"], name="tracking_si_das_ten_4a96b1_idx"),
        ),
        migrations.AddIndex(
            model_name="skygisticssatelliteplugin",
            index=models.Index(fields=["das_tenant", "name"], name="tracking_sk_das_ten_5fe825_idx"),
        ),
        migrations.AddIndex(
            model_name="spidertracksplugin",
            index=models.Index(fields=["das_tenant", "name"], name="tracking_sp_das_ten_2a4e44_idx"),
        ),
        migrations.AddIndex(
            model_name="vectronicsplugin",
            index=models.Index(fields=["das_tenant", "name"], name="tracking_ve_das_ten_fccd89_idx"),
        ),
        migrations.AddConstraint(
            model_name="awetelemetryplugin",
            constraint=models.UniqueConstraint(
                fields=("das_tenant", "name"), name="tracking_awetelemetryplugin_unique_name_across_tenants"
            ),
        ),
        migrations.AddConstraint(
            model_name="awthttpplugin",
            constraint=models.UniqueConstraint(
                fields=("das_tenant", "name"), name="tracking_awthttpplugin_unique_name_across_tenants"
            ),
        ),
        migrations.AddConstraint(
            model_name="awtplugin",
            constraint=models.UniqueConstraint(
                fields=("das_tenant", "name"), name="tracking_awtplugin_unique_name_across_tenants"
            ),
        ),
        migrations.AddConstraint(
            model_name="demosourceplugin",
            constraint=models.UniqueConstraint(
                fields=("das_tenant", "name"), name="tracking_demosourceplugin_unique_name_across_tenants"
            ),
        ),
        migrations.AddConstraint(
            model_name="firmsplugin",
            constraint=models.UniqueConstraint(
                fields=("das_tenant", "name"), name="tracking_firmsplugin_unique_name_across_tenants"
            ),
        ),
        migrations.AddConstraint(
            model_name="inreachkmlplugin",
            constraint=models.UniqueConstraint(
                fields=("das_tenant", "name"), name="tracking_inreachkmlplugin_unique_name_across_tenants"
            ),
        ),
        migrations.AddConstraint(
            model_name="inreachplugin",
            constraint=models.UniqueConstraint(
                fields=("das_tenant", "name"), name="tracking_inreachplugin_unique_name_across_tenants"
            ),
        ),
        migrations.AddConstraint(
            model_name="savannahplugin",
            constraint=models.UniqueConstraint(
                fields=("das_tenant", "name"), name="tracking_savannahplugin_unique_name_across_tenants"
            ),
        ),
        migrations.AddConstraint(
            model_name="sirtrackplugin",
            constraint=models.UniqueConstraint(
                fields=("das_tenant", "name"), name="tracking_sirtrackplugin_unique_name_across_tenants"
            ),
        ),
        migrations.AddConstraint(
            model_name="skygisticssatelliteplugin",
            constraint=models.UniqueConstraint(
                fields=("das_tenant", "name"), name="tracking_skygisticssatelliteplugin_unique_name_across_tenants"
            ),
        ),
        migrations.AddConstraint(
            model_name="spidertracksplugin",
            constraint=models.UniqueConstraint(
                fields=("das_tenant", "name"), name="tracking_spidertracksplugin_unique_name_across_tenants"
            ),
        ),
        migrations.AddConstraint(
            model_name="vectronicsplugin",
            constraint=models.UniqueConstraint(
                fields=("das_tenant", "name"), name="tracking_vectronicsplugin_unique_name_across_tenants"
            ),
        ),
    ]
