# Generated by Django 3.2.21 on 2023-11-24 17:48

import django_multitenant.fields

import django.db.models.deletion
from django.db import migrations

import observations.models


class Migration(migrations.Migration):
    dependencies = [
        ("mapping", "0055_spatialfeaturetype_constraints"),
        ("tracking", "0032_auto_20231120_0951"),
    ]

    operations = [
        migrations.AlterField(
            model_name="awetelemetryplugin",
            name="provider",
            field=django_multitenant.fields.TenantForeignKey(
                default=observations.models.get_default_source_provider_id,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="observations.sourceprovider",
            ),
        ),
        migrations.AlterField(
            model_name="awthttpplugin",
            name="provider",
            field=django_multitenant.fields.TenantForeignKey(
                default=observations.models.get_default_source_provider_id,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="observations.sourceprovider",
            ),
        ),
        migrations.AlterField(
            model_name="awtplugin",
            name="provider",
            field=django_multitenant.fields.TenantForeignKey(
                default=observations.models.get_default_source_provider_id,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="observations.sourceprovider",
            ),
        ),
        migrations.AlterField(
            model_name="demosourceplugin",
            name="provider",
            field=django_multitenant.fields.TenantForeignKey(
                default=observations.models.get_default_source_provider_id,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="observations.sourceprovider",
            ),
        ),
        migrations.AlterField(
            model_name="firmsplugin",
            name="provider",
            field=django_multitenant.fields.TenantForeignKey(
                default=observations.models.get_default_source_provider_id,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="observations.sourceprovider",
            ),
        ),
        migrations.AlterField(
            model_name="firmsplugin",
            name="spatial_feature_group",
            field=django_multitenant.fields.TenantForeignKey(
                help_text="FIRMS data will be filtered by boundaries in this group.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="mapping.spatialfeaturegroupstatic",
            ),
        ),
        migrations.AlterField(
            model_name="inreachkmlplugin",
            name="provider",
            field=django_multitenant.fields.TenantForeignKey(
                default=observations.models.get_default_source_provider_id,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="observations.sourceprovider",
            ),
        ),
        migrations.AlterField(
            model_name="inreachplugin",
            name="provider",
            field=django_multitenant.fields.TenantForeignKey(
                default=observations.models.get_default_source_provider_id,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="observations.sourceprovider",
            ),
        ),
        migrations.AlterField(
            model_name="savannahplugin",
            name="provider",
            field=django_multitenant.fields.TenantForeignKey(
                default=observations.models.get_default_source_provider_id,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="observations.sourceprovider",
            ),
        ),
        migrations.AlterField(
            model_name="sirtrackplugin",
            name="provider",
            field=django_multitenant.fields.TenantForeignKey(
                default=observations.models.get_default_source_provider_id,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="observations.sourceprovider",
            ),
        ),
        migrations.AlterField(
            model_name="skygisticssatelliteplugin",
            name="provider",
            field=django_multitenant.fields.TenantForeignKey(
                default=observations.models.get_default_source_provider_id,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="observations.sourceprovider",
            ),
        ),
        migrations.AlterField(
            model_name="sourceplugin",
            name="source",
            field=django_multitenant.fields.TenantForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="source_plugins",
                related_query_name="source_plugin",
                to="observations.source",
            ),
        ),
        migrations.AlterField(
            model_name="spidertracksplugin",
            name="provider",
            field=django_multitenant.fields.TenantForeignKey(
                default=observations.models.get_default_source_provider_id,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="observations.sourceprovider",
            ),
        ),
        migrations.AlterField(
            model_name="vectronicsplugin",
            name="provider",
            field=django_multitenant.fields.TenantForeignKey(
                default=observations.models.get_default_source_provider_id,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="observations.sourceprovider",
            ),
        ),
    ]
