# Generated by Django 3.2.21 on 2023-11-25 00:10

from django.db import migrations

import utils.models


class Migration(migrations.Migration):
    dependencies = [
        ("tracking", "0033_migrate_fk_to_tfk"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="awetelemetryplugin",
            options={"base_manager_name": "objects", "default_manager_name": "objects"},
        ),
        migrations.AlterModelOptions(
            name="awthttpplugin",
            options={"base_manager_name": "objects", "default_manager_name": "objects"},
        ),
        migrations.AlterModelOptions(
            name="awtplugin",
            options={"base_manager_name": "objects", "default_manager_name": "objects"},
        ),
        migrations.AlterModelOptions(
            name="demosourceplugin",
            options={"base_manager_name": "objects", "default_manager_name": "objects"},
        ),
        migrations.AlterModelOptions(
            name="firmsplugin",
            options={"base_manager_name": "objects", "default_manager_name": "objects"},
        ),
        migrations.AlterModelOptions(
            name="inreachkmlplugin",
            options={
                "base_manager_name": "objects",
                "default_manager_name": "objects",
                "verbose_name": "inReach Personal plugin",
                "verbose_name_plural": "inReach Personal plugins",
            },
        ),
        migrations.AlterModelOptions(
            name="inreachplugin",
            options={
                "base_manager_name": "objects",
                "default_manager_name": "objects",
                "verbose_name": "inReach Professional plugin",
                "verbose_name_plural": "inReach Professional plugins",
            },
        ),
        migrations.AlterModelOptions(
            name="savannahplugin",
            options={"base_manager_name": "objects", "default_manager_name": "objects"},
        ),
        migrations.AlterModelOptions(
            name="sirtrackplugin",
            options={"base_manager_name": "objects", "default_manager_name": "objects"},
        ),
        migrations.AlterModelOptions(
            name="skygisticssatelliteplugin",
            options={"base_manager_name": "objects", "default_manager_name": "objects"},
        ),
        migrations.AlterModelOptions(
            name="sourceplugin",
            options={"base_manager_name": "objects", "default_manager_name": "objects"},
        ),
        migrations.AlterModelOptions(
            name="spidertracksplugin",
            options={"base_manager_name": "objects", "default_manager_name": "objects"},
        ),
        migrations.AlterModelOptions(
            name="vectronicsplugin",
            options={"base_manager_name": "objects", "default_manager_name": "objects"},
        ),
        migrations.AlterModelManagers(
            name="sourceplugin",
            managers=[
                ("objects", utils.models.CommonTenantManager()),
            ],
        ),
    ]
