# Generated by Django 3.2.21 on 2023-11-28 18:18
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0015_delete_unique_constraints"),
        ("tracking", "0034_tenantmanager"),
    ]
    operations = [
        migrations.AlterField(
            model_name="SourceProviderConfiguration",
            name="name_change_excluded_subject_types",
            field=models.ManyToManyField(
                blank=True,
                db_table="tracking_sourceproviderconfiguration_name_change_excluded",
                default="wildlife",
                related_name="name_change_excluded_subject_types",
                to="observations.SubjectType",
                verbose_name="",
            ),
        ),
        migrations.AlterField(
            model_name="SourceProviderConfiguration",
            name="new_subject_excluded_subject_types",
            field=models.ManyToManyField(
                to="observations.SubjectType",
                db_table="tracking_sourceproviderconfiguration_new_subject_excluded",
                related_name="new_subject_excluded_subject_types",
                default="wildlife",
                blank=True,
                verbose_name="",
            ),
        ),
    ]
