# Generated by Django 3.2.21 on 2023-11-28 18:18

import uuid

import django_multitenant.mixins
from django_multitenant.fields import TenantForeignKey

import django.db.models.deletion
from django.db import migrations, models

import utils.migrations.columns
import utils.models

APP_NAME = "tracking"

THROUGH_MODEL = "SourceProviderConfigurationNewSubjectExcludedSubjectTypes"
OLD_TABLE_NAME = "sourceproviderconfiguration_new_subject_excluded"
NEW_TABLE_NAME = "newsubjectexcludedsubjecttypes"
MAIN_MODEL_NAME = "SourceProviderConfiguration"
RELATED_NAME = "new_subject_excluded_subject_types"


class Migration(migrations.Migration):
    dependencies = [
        ("tracking", "0036_custom_through_model_name_change_excluded_subject_types"),
    ]
    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=f"ALTER TABLE {APP_NAME}_{OLD_TABLE_NAME} RENAME TO {APP_NAME}_{NEW_TABLE_NAME}",
                    reverse_sql=f"ALTER TABLE {APP_NAME}_{NEW_TABLE_NAME} RENAME TO {APP_NAME}_{OLD_TABLE_NAME}",
                ),
            ],
            state_operations=[
                migrations.CreateModel(
                    name=THROUGH_MODEL,
                    fields=[
                        ("id", models.AutoField(serialize=True)),
                        (
                            "subjecttype",
                            TenantForeignKey(
                                to="observations.SubjectType",
                                related_name="new_subjects_excluded_subject_types",
                                on_delete=django.db.models.deletion.CASCADE,
                            ),
                        ),
                        (
                            "sourceproviderconfiguration",
                            TenantForeignKey(
                                to=MAIN_MODEL_NAME.lower(),
                                related_name="source_provider_from_new_subjects_excluded_subject_types",
                                on_delete=django.db.models.deletion.CASCADE,
                            ),
                        ),
                    ],
                    options={
                        "db_table": "tracking_newsubjectexcludedsubjecttypes",
                    },
                    bases=(django_multitenant.mixins.TenantModelMixin, models.Model),
                    managers=[
                        ("objects", utils.models.CommonTenantManager()),
                    ],
                ),
                migrations.AlterField(
                    model_name=MAIN_MODEL_NAME,
                    name=RELATED_NAME,
                    field=models.ManyToManyField(
                        to="observations.SubjectType",
                        related_name=RELATED_NAME,
                        through=THROUGH_MODEL,
                        through_fields=("source_provider_configuration", "subject_type"),
                        default="wildlife",
                        blank=True,
                        verbose_name="",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name=THROUGH_MODEL,
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.RemoveField(
            model_name=THROUGH_MODEL,
            name="id",
        ),
        migrations.RenameField(
            model_name=THROUGH_MODEL,
            old_name="uuid",
            new_name="id",
        ),
        migrations.AlterField(
            model_name=THROUGH_MODEL,
            name="id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=True),
        ),
        migrations.AlterModelManagers(
            name=THROUGH_MODEL,
            managers=[
                ("objects", utils.models.CommonTenantManager()),
            ],
        ),
        migrations.AddField(
            model_name=THROUGH_MODEL,
            name="das_tenant",
            field=models.ForeignKey(
                default=utils.migrations.columns.default_tenant_id,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.dastenant",
            ),
        ),
    ]
