# Generated by Django 4.2.28 on 2026-02-16 15:01

import uuid

import django_multitenant.fields

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("observations", "0207_django_42"),
        ("tracking", "0037_custom_through_model_new_subject_excluded_subject_types"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sourceproviderconfiguration",
            name="name_change_excluded_subject_types",
            field=models.ManyToManyField(
                blank=True,
                default="wildlife",
                related_name="name_change_excluded_subject_types",
                through="tracking.SourceProviderConfigurationNameChangeExcludedSubjectTypes",
                to="observations.subjecttype",
                verbose_name="",
            ),
        ),
        migrations.AlterField(
            model_name="sourceproviderconfiguration",
            name="new_subject_excluded_subject_types",
            field=models.ManyToManyField(
                blank=True,
                default="wildlife",
                related_name="new_subject_excluded_subject_types",
                through="tracking.SourceProviderConfigurationNewSubjectExcludedSubjectTypes",
                to="observations.subjecttype",
                verbose_name="",
            ),
        ),
        migrations.AlterField(
            model_name="sourceproviderconfigurationnamechangeexcludedsubjecttypes",
            name="id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="sourceproviderconfigurationnamechangeexcludedsubjecttypes",
            name="sourceproviderconfiguration",
            field=django_multitenant.fields.TenantForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="source_provider_from_name_change_excluded_subject_types",
                to="tracking.sourceproviderconfiguration",
            ),
        ),
        migrations.AlterField(
            model_name="sourceproviderconfigurationnewsubjectexcludedsubjecttypes",
            name="id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="sourceproviderconfigurationnewsubjectexcludedsubjecttypes",
            name="sourceproviderconfiguration",
            field=django_multitenant.fields.TenantForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="source_provider_from_new_subjects_excluded_subject_types",
                to="tracking.sourceproviderconfiguration",
            ),
        ),
    ]
