{
 "title": "Elasticsearch",
 "tags": [
  "elasticsearch",
  "App"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "Interval",
    "query": "5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(elasticsearch_indices_docs,cluster)"
   },
   {
    "name": "name",
    "label": "Node name",
    "query": "label_values(elasticsearch_indices_docs{cluster=\"$cluster\", name!=\"\"},name)"
   },
   {
    "name": "instance",
    "label": "Source of metrics",
    "query": "label_values(elasticsearch_indices_docs{cluster=\"$cluster\", name!=\"\"},instance)"
   }
  ]
 },
 "panels": [
  { "title": "KPI", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Cluster health",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "elasticsearch_cluster_health_status{cluster=\"$cluster\",color=\"green\"}==1 or (elasticsearch_cluster_health_status{cluster=\"$cluster\",color=\"yellow\"}==1)+1 or (elasticsearch_cluster_health_status{cluster=\"$cluster\",color=\"red\"}==1)+2"
    }
   ]
  },
  {
   "title": "Max JVM Heap Usage %",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "max (elasticsearch_jvm_memory_used_bytes{area=\"heap\",cluster=\"$cluster\",name=~\"$name\"} / elasticsearch_jvm_memory_max_bytes{area=\"heap\",cluster=\"$cluster\",name=~\"$name\"}) * 100"
    }
   ]
  },
  {
   "title": "CPU usage Avg.",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (elasticsearch_process_cpu_percent{cluster=\"$cluster\",name=~\"$name\"} ) / count (elasticsearch_process_cpu_percent{cluster=\"$cluster\",name=~\"$name\"} )"
    }
   ]
  },
  {
   "title": "Total Nodes",
   "type": "singlestat",
   "description": "Number of nodes in the cluster",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "elasticsearch_cluster_health_number_of_nodes{cluster=\"$cluster\"}"
    }
   ]
  },
  {
   "title": "Data nodes",
   "type": "singlestat",
   "description": "Number of data nodes in the cluster",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "elasticsearch_cluster_health_number_of_data_nodes{cluster=\"$cluster\"}"
    }
   ]
  },
  {
   "title": "Unassigned shards",
   "type": "singlestat",
   "description": "The number of shards that exist in the cluster state, but cannot be found in the cluster itself",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "elasticsearch_cluster_health_unassigned_shards{cluster=\"$cluster\"}"
    }
   ]
  },
  {
   "title": "Initializing shards",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "elasticsearch_cluster_health_initializing_shards{cluster=\"$cluster\"} "
    }
   ]
  },
  { "title": "Counts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Documents",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 5 },
   "repeat": "shard_type",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (elasticsearch_indices_docs{cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Store Size KB",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 5 },
   "repeat": "shard_type",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (elasticsearch_indices_store_size_bytes{cluster=\"$cluster\"}) / 1000"
    }
   ]
  },
  {
   "title": "Active primary shards",
   "type": "singlestat",
   "description": "The number of primary shards in your cluster. This is an aggregate total across all indices.",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 5 },
   "repeat": "shard_type",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "elasticsearch_cluster_health_active_primary_shards{cluster=\"$cluster\"}"
    }
   ]
  },
  {
   "title": "Active shards",
   "type": "singlestat",
   "description": "Aggregate total of all shards across all indices, which includes replica shards",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "elasticsearch_cluster_health_active_shards{cluster=\"$cluster\"}"
    }
   ]
  },
  { "title": "JVM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "JVM Heap Usage %",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "percent", "label": "Percent" }
   ],
   "targets": [
    {
     "expr": "(elasticsearch_jvm_memory_used_bytes{area=\"heap\",cluster=\"$cluster\",name=~\"$name\"} / elasticsearch_jvm_memory_max_bytes{area=\"heap\",cluster=\"$cluster\",name=~\"$name\"}) * 100",
     "legendFormat": "{{name}} used: {{area}}"
    }
   ]
  },
  {
   "title": "Garbage Collections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "irate(elasticsearch_jvm_gc_collection_seconds_count{cluster=\"$cluster\",name=~\"$name\"}[$interval])",
     "legendFormat": "{{name}} - {{gc}}"
    }
   ]
  },
  {
   "title": "Garbage Collection Duration",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "s", "label": "Seconds" }
   ],
   "targets": [
    {
     "expr": "irate(elasticsearch_jvm_gc_collection_seconds_sum{cluster=\"$cluster\",name=~\"$name\"}[$interval])",
     "legendFormat": "{{name}} - {{gc}}"
    }
   ]
  },
  {
   "title": "Indexing Performance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true,
   "panels": [
    {
     "title": "Indexing Latency",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short", "label": "Seconds per Indexing Call" }
     ],
     "targets": [
      {
       "expr": "irate(elasticsearch_indices_indexing_index_time_seconds_total{cluster=\"$cluster\"}[$interval]) / irate(elasticsearch_indices_indexing_index_total{cluster=\"$cluster\"}[$interval])",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Flush Latency",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "short", "label": "Seconds per Flush Call" }
     ],
     "targets": [
      {
       "expr": "irate(elasticsearch_indices_flush_time_seconds{cluster=\"$cluster\"}[$interval]) / irate(elasticsearch_indices_flush_total{cluster=\"$cluster\"}[$interval])",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Query Performance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "collapsed": true,
   "panels": [
    {
     "title": "Query Latency",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "s", "label": "Seconds per Query" }
     ],
     "targets": [
      {
       "expr": "irate(elasticsearch_indices_search_query_time_seconds{cluster=\"$cluster\",name=~\"$name\"}[$interval]) / irate(elasticsearch_indices_search_query_total{cluster=\"$cluster\",name=~\"$name\"}[$interval]) ",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Fetch Latency",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "s", "label": "Seconds per Fetch" }
     ],
     "targets": [
      {
       "expr": "irate(elasticsearch_indices_search_fetch_time_seconds{cluster=\"$cluster\",name=~\"$name\"}[$interval]) / irate(elasticsearch_indices_search_fetch_total{cluster=\"$cluster\",name=~\"$name\"}[$interval]) ",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Thread Pools",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "collapsed": true,
   "panels": [
    {
     "title": "Thread Pool (en)Queue (/s)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(elasticsearch_thread_pool_queue_count{cluster=\"$cluster\", name=~\"$name\"}[$interval])",
       "legendFormat": "{{name}}: {{type}}"
      }
     ]
    },
    {
     "title": "Thread Pool Rejected (/s)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(elasticsearch_thread_pool_rejected_count{cluster=\"$cluster\", name=~\"$name\"}[$interval])",
       "legendFormat": "{{name}}: {{type}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Index Parsing",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "collapsed": true,
   "panels": [
    {
     "title": "Json Parse Exceptions (/s)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(elasticsearch_cluster_health_json_parse_failures[$interval])"
      }
     ]
    }
   ]
  },
  {
   "title": "Shards",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "collapsed": true,
   "panels": [
    {
     "title": "Unassigned Shards",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 40 },
     "yaxes": [
      { "format": "short", "label": "Count" }
     ]
    }
   ]
  }
 ]
}