# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases
# we use postgis, create the db from the spatial db template
FROM mdillon/postgis:9.6
MAINTAINER MAtt Korwel, mattko@vulcan.com

ENV PGDATA=/var/lib/postgresql/data/das
ENV POSTGRES_USER das
ENV POSTGRES_DB das
ENV POSTGRES_PASSWORD password
