version: 2.1
commands:
  docker_login:
    steps:
      - run: echo "$GCR_PUSH_KEY" | docker login --username _json_key --password-stdin https://gcr.io
  terraform_plan:
    parameters:
      terraform_workspace:
        type: string
        default: "dev"
      init_args:
        type: string
        default: "-input=false"
      plan_args:
        type: string
        default: "-input=false -out=tfplan"
    steps:
      - 'checkout'
      - run: 'export GOOGLE_CREDENTIALS="$(echo $ENCODED_GOOGLE_CREDENTIALS | base64 --decode)" && cd terraform && make terraform_init init_args="<< parameters.init_args >>"'
      - run: 'export GOOGLE_CREDENTIALS="$(echo $ENCODED_GOOGLE_CREDENTIALS | base64 --decode)" && cd terraform && make terraform_workspace_select terraform_workspace="<< parameters.terraform_workspace >>"'
      - run: 'export GOOGLE_CREDENTIALS="$(echo $ENCODED_GOOGLE_CREDENTIALS | base64 --decode)" && cd terraform && make terraform_plan plan_args="<< parameters.plan_args >>"'
      - persist_to_workspace:
          root: './'
          paths:
            - '*.*'
            - '*'
  terraform_apply:
    parameters:
      apply_args:
        type: string
        default: "-input=false tfplan"
    steps:
      - attach_workspace:
          at: './'
      - run: 'export GOOGLE_CREDENTIALS="$(echo $ENCODED_GOOGLE_CREDENTIALS | base64 --decode)" && cd terraform && make terraform_apply apply_args="<< parameters.apply_args >>"'
executors:
  default:
    docker:
      - image: 'circleci/buildpack-deps:stretch'
jobs:
  terraform_plan_dev:
    environment:
      TF_IN_AUTOMATION: 'not-empty'
    executor: 'default'
    steps:
      - terraform_plan:
          terraform_workspace: 'dev'
  terraform_apply_dev:
    environment:
      TF_IN_AUTOMATION: 'not-empty'
    executor: 'default'
    steps:
      - terraform_apply
  docker_build:
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - setup_remote_docker
      - docker_login
      - checkout
      - run: 'cd circleci-docker && make earthranger_api_build_and_push tag=$CIRCLE_BRANCH'
workflows:
  version: 2
  build_and_terraform_dev:
    jobs:
      - docker_build
      - terraform_plan_dev:
          requires:
            - 'docker_build'
      - review_plan_dev:
          requires:
            - 'terraform_plan_dev'
          type: 'approval'
      - terraform_apply_dev:
          requires:
            - 'review_plan_dev'

