version: 2.1
commands:
  docker_login:
    steps:
      - run: echo "$GCR_PUSH_KEY" | docker login --username _json_key --password-stdin https://gcr.io
  #add_deploy_key_for_common_terraform_modules:
  #  steps:
  #    - add_ssh_keys:
  #        fingerprints:
  #          - ''
executors:
  default:
    docker:
      - image: 'circleci/buildpack-deps:stretch'
jobs:
  terraform_plan:
    environment:
      TF_IN_AUTOMATION: 'not-empty'
    executor: 'default'
    steps:
      - 'checkout'
        #- 'add_deploy_key_for_common_terraform_modules'
      - run: 'export GOOGLE_CREDENTIALS="$(echo $ENCODED_GOOGLE_CREDENTIALS | base64 --decode)" && cd terraform && make terraform_init init_args="-input=false"'
      - run: 'export GOOGLE_CREDENTIALS="$(echo $ENCODED_GOOGLE_CREDENTIALS | base64 --decode)" && cd terraform && make terraform_plan plan_args="-input=false -out=tfplan"'
      - persist_to_workspace:
          root: './'
          paths:
            - '*.*'
            - '*'
  terraform_apply:
    environment:
      TF_IN_AUTOMATION: 'not-empty'
    executor: 'default'
    steps:
      - attach_workspace:
          at: './'
      - run: 'export GOOGLE_CREDENTIALS="$(echo $ENCODED_GOOGLE_CREDENTIALS | base64 --decode)" && cd terraform && make terraform_apply apply_args="-input=false tfplan"'
  docker_build:
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - setup_remote_docker
      - docker_login
      - checkout
      - run: 'cd circleci-docker && make base_build_and_push tag=latest'
      - run: 'cd circleci-docker && make earthranger_api_build_and_push tag=$CIRCLE_BRANCH'
workflows:
  version: 2
  build_and_terraform:
    jobs:
      - docker_build:
          filters:
            branches:
              only:
                - develop
                - consolidate-docker-images-step2
      - terraform_plan:
          requires:
            - 'docker_build'
      - review_plan:
          filters:
            branches:
              only: 'develop'
          requires:
            - 'terraform_plan'
          type: 'approval'
      - terraform_apply:
          filters:
            branches:
              only: 'develop'
          requires:
            - 'review_plan'

