version: 2.1
commands:
  configure_git_for_commit_and_push:
    steps:
      - run: 'git config user.email "circleci@vulcan.com"'
      - run: 'git config user.name "circleci"'
      - run: 'git config push.default current'
      - add_ssh_keys:
          fingerprints:
            - ''
  add_deploy_key_for_common_terraform_modules:
    steps:
      - add_ssh_keys:
          fingerprints:
            - "ca:a6:a4:87:70:0b:8c:92:b5:06:65:00:13:4d:c9:c4"
  docker_login:
    steps:
      - run: echo "$GCR_PUSH_KEY" | docker login --username _json_key --password-stdin https://gcr.io
  terraform_plan:
    parameters:
      terraform_workspace:
        type: string
        default: "dev"
      init_args:
        type: string
        default: "-input=false"
      plan_args:
        type: string
        default: "-input=false -out=tfplan"
    steps:
      - 'checkout'
      - 'add_deploy_key_for_common_terraform_modules'
      - run: 'export GOOGLE_CREDENTIALS="$(echo $ENCODED_GOOGLE_CREDENTIALS | base64 --decode)" && cd terraform && make terraform_init init_args="<< parameters.init_args >>"'
      - run: 'export GOOGLE_CREDENTIALS="$(echo $ENCODED_GOOGLE_CREDENTIALS | base64 --decode)" && cd terraform && make terraform_workspace_select terraform_workspace="<< parameters.terraform_workspace >>"'
      - run: 'export GOOGLE_CREDENTIALS="$(echo $ENCODED_GOOGLE_CREDENTIALS | base64 --decode)" && cd terraform && make terraform_plan plan_args="<< parameters.plan_args >>"'
      - persist_to_workspace:
          root: './'
          paths:
            - '*.*'
            - '*'
  terraform_apply:
    parameters:
      apply_args:
        type: string
        default: "-input=false tfplan"
    steps:
      - 'add_deploy_key_for_common_terraform_modules'
      - attach_workspace:
          at: './'
      - run: 'export GOOGLE_CREDENTIALS="$(echo $ENCODED_GOOGLE_CREDENTIALS | base64 --decode)" && cd terraform && make terraform_apply apply_args="<< parameters.apply_args >>"'
executors:
  default:
    docker:
      - image: 'circleci/buildpack-deps:stretch'
jobs:
  terraform_plan_dev:
    environment:
      TF_IN_AUTOMATION: 'not-empty'
    executor: 'default'
    steps:
      - terraform_plan:
          terraform_workspace: 'dev'
  terraform_plan_prod1:
    environment:
      TF_IN_AUTOMATION: 'not-empty'
    executor: 'default'
    steps:
      - terraform_plan:
          terraform_workspace: 'prod1'
  terraform_apply_dev:
    environment:
      TF_IN_AUTOMATION: 'not-empty'
    executor: 'default'
    steps:
      - terraform_apply
  terraform_apply_prod1:
    environment:
      TF_IN_AUTOMATION: 'not-empty'
    executor: 'default'
    steps:
      - terraform_apply
  generate_manifest:
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - setup_remote_docker
      - docker_login
      - checkout
      - run: 'cd circleci-docker && make generate_manifest semver_metadata_suffix=$CIRCLE_SHA1'
      - persist_to_workspace:
          root: './'
          paths:
            - '*'
  docker_build:
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - attach_workspace:
          at: './'
      - setup_remote_docker
      - docker_login
      - checkout
      - run: 'cd circleci-docker && make earthranger_api_build_and_push tag=$CIRCLE_BRANCH'
      - persist_to_workspace:
          root: './'
          paths:
            - '*'
  commit_and_push_manifest:
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - attach_workspace:
          at: './'
      - setup_remote_docker
      - docker_login
      - checkout
      - configure_git_for_commit_and_push
      - run: 'cd circleci-docker && make commit_and_push_manifest'
workflows:
  version: 2
  build_and_terraform_dev:
  # This is our eager workflow for deploying from our main code branch.
  # So no review step.
    jobs:
      - docker_build:
          filters:
            branches:
              only: 'develop'
      - terraform_plan_dev:
          requires:
            - 'docker_build'
      - terraform_apply_dev:
          requires:
            - 'terraform_plan_dev'

  build_and_terraform_feature_branch:
  # Build for all branches except develop and release.
  # Include a review step.
    jobs:
      - generate_manifest
      - docker_build:
          requires:
            - 'generate_manifest'
          filters:
            branches:
              ignore:
                - 'develop'
                - /release*/
      - commit_and_push_manifest:
          requires:
            - 'docker_build'
      - terraform_plan_dev:
          requires:
            - 'docker_build'
      - review_plan_dev:
          requires:
            - 'terraform_plan_dev'
          type: 'approval'
      - terraform_apply_dev:
          requires:
            - 'review_plan_dev'

  build_and_terraform_prod1:
  # Build for all release branches
  # Review step for apply
    jobs:
      - docker_build:
          filters:
            branches:
              only: /release*/
      - terraform_plan_prod1:
          requires:
            - 'docker_build'
      - review_plan_prod1:
          requires:
            - 'terraform_plan_prod1'
          type: 'approval'
      - terraform_apply_prod1:
          requires:
            - 'review_plan_prod1'
