apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "telegraf"
  namespace: "<<infra-namespace>>"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "telegraf"
  template:
    metadata:
      annotations:
        prometheus.io/port: "9273"
      labels:
        app: "telegraf"
    spec:
      containers:
      - name: "telegraf"
        image: "telegraf:1.10.0"
        livenessProbe:
          httpGet:
            path: "/metrics"
            port: "telegraf"
          initialDelaySeconds: 60
          periodSeconds: 60
          timeoutSeconds: 5
        ports:
        - name: "telegraf"
          containerPort: 9273
        readinessProbe:
          httpGet:
            path: "/metrics"
            port: "telegraf"
          initialDelaySeconds: 60
          timeoutSeconds: 5
        volumeMounts:
        - name: "config"
          mountPath: "/etc/telegraf/telegraf.conf"
          readOnly: true
      volumes:
      - name: "config"
        configMap:
          name: "telegraf"
