import logging
import os

from django import forms
from django.contrib import messages
from django.contrib.staticfiles.storage import staticfiles_storage
from django.forms.widgets import Widget
from django.utils.translation import ugettext_lazy as _
from django.forms import TextInput
from django.contrib.admin.widgets import FilteredSelectMultiple

from activity.exceptions import SchemaValidationError, \
    SCHEMA_ERROR_INCORRECT_RENDER_TAG, SCHEMA_ERROR_JSON_DECODE_ERROR
from core.forms_utils import JSONFieldFormMixin

import json
import jsonschema
from core.utils import OneWeekSchedule
from activity.alerting.conditions import Conditions
from activity.models import EventProvider, NotificationMethod, EventType, Event
from utils.schema_utils import get_schema_renderer_method, \
    validate_rendered_schema_is_wellformed
from core.widget import IconKeyInput, get_icon_select_list
from core.common import TIMEZONE_USED

logger = logging.getLogger(__name__)


class MonospaceTextWidget(forms.Textarea):
    template_name = 'admin/activity/monospace_textarea.html'

    def __init__(self, attrs=None):
        # Use slightly better defaults than HTML's 20x2 box
        default_attrs = {'cols': '70', 'rows': '30'}
        if attrs:
            default_attrs.update(attrs)
        super().__init__(default_attrs)

    class Media:
        css = {
            'all': ('css/monospace_textarea.css',),
        }


class SchemaWidget(forms.Textarea):
    template_name = 'admin/activity/eventtype/schema_textarea.html'

    def __init__(self, attrs=None):
        # Use slightly better defaults than HTML's 20x2 box
        default_attrs = {'cols': '50', 'rows': '100'}
        if attrs:
            default_attrs.update(attrs)
        super().__init__(default_attrs)

    class Media:
        css = {
            'all': ('css/schema_textarea.css',),
        }


def validate_schema_is_well_formed(schema):

    try:
        rendered_schema = get_schema_renderer_method()(schema)
    except NameError as ne:
        raise forms.ValidationError(
            f'Schema includes an invalid token {str(ne)}')
    except Exception:
        raise forms.ValidationError(SCHEMA_ERROR_JSON_DECODE_ERROR)
    else:
        try:
            validate_rendered_schema_is_wellformed(rendered_schema)
        except SchemaValidationError as e:
            raise forms.ValidationError(str(e))


class EventTypeForm(forms.ModelForm):
    schema = forms.CharField(widget=SchemaWidget(
        attrs={'rows': 30, 'cols': 100}))

    icon = forms.CharField(required=False,
                           label='Icon Override',
                           widget=IconKeyInput(image_list_fn=get_icon_select_list))

    class Meta:
        model = EventType
        fields = ['icon', 'display', 'schema',]

    def clean_schema(self):
        schema = self.cleaned_data.get('schema')
        name = self.cleaned_data['display']
        schema_warning = f'Warning: The event type schema for {name} is not properly formatted JSON. The event type might not properly render in the EarthRanger client.'
        try:
            rendered_schema = get_schema_renderer_method()(schema)
        except NameError as ne:
            messages.add_message(self.request, messages.WARNING, schema_warning)
        except Exception:
            messages.add_message(self.request, messages.WARNING, schema_warning)
        else:
            try:
                validate_rendered_schema_is_wellformed(rendered_schema)
            except SchemaValidationError as e:
                messages.add_message(self.request, messages.WARNING, schema_warning)
        return self.cleaned_data


class NotificationMethodSelectField(forms.ModelMultipleChoiceField):

    def label_from_instance(self, obj):
        return f'owner > {obj.owner.username} | {obj.method} : {obj.value}'


class AlertRuleForm(forms.ModelForm):

    def get_initial_for_field(self, field, field_name):
        value = super().get_initial_for_field(field, field_name)

        if field_name in ('conditions', 'schedule',):
            return json.dumps(value, indent=2)
        return value

    conditions = forms.CharField(widget=MonospaceTextWidget,
                                 help_text=_('The data in this field is generated by the system. Do not edit it directly.'))
    schedule = forms.CharField(widget=MonospaceTextWidget,
                               help_text=_('The data in this field is generated by the system. Do not edit it directly.'))

    notification_methods = NotificationMethodSelectField(
        queryset=NotificationMethod.objects.all(),
        required=False,
        widget=FilteredSelectMultiple(
            verbose_name=_('Notification Methods'),
            is_stacked=False))

    event_types = forms.ModelMultipleChoiceField(
        queryset=EventType.objects.all(),
        required=False,
        widget=FilteredSelectMultiple(
            verbose_name=_('Event Types'),
            is_stacked=False))

    def clean_conditions(self):

        value = self.clean_jsonfield('conditions')
        try:
            Conditions(value)
            return value
        except jsonschema.ValidationError as ve:
            rpath = '/'.join([''] + [str(x) for x in ve.relative_path])
            error_message = f'JSON schema validation error at {rpath}. Value {ve.instance} failed {ve.validator} ' \
                f'validation against {ve.validator_value}'
            raise forms.ValidationError(error_message)

    def clean_schedule(self):
        value = self.clean_jsonfield('schedule')
        try:
            OneWeekSchedule(value)
            return value
        except jsonschema.ValidationError as ve:
            rpath = '/'.join([''] + [str(x) for x in ve.relative_path])
            error_message = f'JSON schema validation error at {rpath}. Value {ve.instance} failed {ve.validator} ' \
                f'validation against {ve.validator_value}'
            raise forms.ValidationError(error_message)

    def clean_jsonfield(self, key):
        value = self.cleaned_data[key]
        try:
            return json.loads(value)
        except json.JSONDecodeError as ex:
            raise forms.ValidationError(str(ex))


class EventProviderForm(JSONFieldFormMixin, forms.ModelForm):

    provider_api = forms.URLField(label='Provider API', required=True, widget=TextInput(attrs={'size': '100'}),
                                  help_text=_('A URL or web service endpoint for the external data source.'))
    provider_username = forms.CharField(label='Provider API Username', required=False,
                                        help_text=_('If the external data source requires a username, enter it here.'))
    provider_password = forms.CharField(label='Provider API Password', required=False,
                                        help_text=_('If the external data source requires a password, enter it here.'))
    provider_token = forms.CharField(label='Provider Authorization Token', widget=TextInput(attrs={'size': '100'}),
                                     required=False,
                                     help_text=_('If you were given an authorization token for the external data source, enter it here.'))

    icon_url = forms.CharField(label='Provider Icon URL', required=False, widget=TextInput(attrs={'size': '100'}),
                               help_text=_(
                                   'A URL for an Icon to use with this Event Provider.'),
                               initial='/static/smart-logo.svg')
    external_event_url = forms.CharField(label='Provider Link', required=False, widget=TextInput(attrs={'size': '100'}),
                                         help_text=_('A web link to the user interface for this Event Provider\'s data'))

    class Meta:
        model = EventProvider
        json_fields = ('provider_api', 'provider_username',
                       'provider_password', 'provider_token',
                       'icon_url', 'external_event_url',)
        fields = ('additional',) + json_fields


class EventForm(forms.ModelForm):
    class Meta:
        labels = {
            'created_at': f'Created at {TIMEZONE_USED}',
            'updated_at': f'Updated at {TIMEZONE_USED}',
            'event_time': f'Event time in {TIMEZONE_USED}',
            'end_time': f'End Time in {TIMEZONE_USED}'
        }