apiVersion: v1
kind: Namespace
metadata:
  name: <<namespace>>
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: request-quota
  name: <<namespace>>
spec:
  hard:
    requests.cpu: <<cpu-request-quota>>
    requests.memory: <<memory-request-quota>>
---
apiVersion: v1
kind: LimitRange
metadata:
  name: limits # this name intentionally overwrites the defaults which GCP applies
  name: <<namespace>>
spec:
  limits:
  - defaultRequest:
      cpu: <<default-cpu-request>>
      memory: <<default-memory-request>>
    type: Container
