artifacts:
  git-utility-version: git-utility/sha
  git-web-version: git-web/sha
  git-server-version: git-server/sha
  smartconnect-provider-version: git-smartconnect-provider/sha
  monitoring-version: 0.0.6
