apiVersion: v1
kind: ConfigMap
metadata:
  name: default-configmap
data:
  APIENDPOINT: localhost
  DB_HOST: postgis.default.svc.cluster.local
  DB_PORT: "5432"
  API_HOST: api
  API_PORT: "8000"
  EMAIL_PASSWORD: ${EMAIL_PASSWORD}
  WEB_SERVICE_NAME: ${WEB_SERVICE_NAME}
  BUNDLE_CRT: "${BUNDLE_CRT}"
  PAMDAS_ORG_PRIVATE_KEY_PEM: "${PAMDAS_ORG_PRIVATE_KEY_PEM}"