apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: mql
spec:
  template:
    metadata:
      labels:
        das.component: mql
    spec:
      imagePullSecrets:
        - name: gcr-secret
      containers:
      - image: gcr.io/padas-app/mql:${GIT_SERVER_SHA}
        name: das-mql
        env:
        - name: API_HOST
          valueFrom:
            configMapKeyRef:
              name: default-configmap
              key: API_HOST
        - name: API_PORT
          valueFrom:
            configMapKeyRef:
              name: default-configmap
              key: API_PORT
