from analyzers.models.base import SubjectAnalyzerConfig, SubjectAnalyzerResult, OK, CRITICAL, WARNING
from analyzers.models.annotations import ObservationAnnotator
from analyzers.models.immobility import ImmobilityAnalyzerConfig
from analyzers.models.geofence import GeofenceAnalyzerConfig
from analyzers.models.environmental import EnvironmentalSubjectAnalyzerConfig
from analyzers.models.low_speed import LowSpeedAnalyzerConfig