from django.test import TestCase

from activity.forms import EventTypeForm, SCHEMA_ERROR_JSON_DECODE_ERROR, \
    SCHEMA_ERROR_INCORRECT_RENDER_TAG

EVENT_SCHEMA = """{\r\n   \"schema\": \r\n   {\r\n       \"$schema\": \"http://json-schema.org/draft-04/schema#\",\r\n       \"title\": \"Shot Rep Report\",\r\n     \r\n       \"type\": \"object\",\r\n\r\n       \"properties\": \r\n       {\r\n            \"shotrepTimeOfShot\": {\r\n                \"type\": \"string\",\r\n                \"title\": \"Line 1: Time when shot was heard\"\r\n            },\r\n            \"shotrepBearing\": {\r\n                \"type\": \"number\",\r\n                \"title\": \"Line 2: Bearing to Shot\",\r\n                \"minimum\": 0,\r\n                \"maximum\":  360\r\n            },                      \r\n            \"shotrepDistance\": {\r\n                \"type\": \"number\",\r\n                \"title\": \"Line 3: Distance of Shots\",\r\n                \"minimum\": 0\r\n            },                      \r\n            \"shotrepNumberOfShots\": {\r\n                \"type\": \"number\",\r\n                \"title\": \"Line 4: Number of Shots\",\r\n                \"minimum\": 0\r\n            },\r\n            \"shotrepTypeOfShots\": {\r\n            \t\"type\": \"string\",\r\n            \t\"title\": \"Line 5. Type of Shots\",\r\n                \"enum\": {{table___TypeOfShots___values}},\r\n                \"enumNames\": {{table___TypeOfShots___names}}\r\n            },              \r\n            \"shotrepEstimatedCaliber\": {\r\n                \"type\": \"string\",\r\n                \"title\": \"Line 6: Estimated Caliber\"\r\n            },\r\n            \"shotrepEstimatedTarget\": {\r\n                \"type\": \"string\",\r\n                \"title\": \"Line 7: Estimated Target\"\r\n            }\r\n       }\r\n   },\r\n \"definition\": [\r\n   {\r\n   \"key\": \"shotrepTimeOfShot\",\r\n   \"fieldHtmlClass\": \"date-time-picker json-schema\",\r\n   \"readonly\": false\r\n   },\r\n   \"shotrepBearing\",\r\n   \"shotrepDistance\",\r\n   \"shotrepNumberOfShots\",\r\n   \"shotrepTypeOfShots\",\r\n   \"shotrepEstimatedCaliber\",\r\n   \"shotrepEstimatedTarget\"\r\n ]\r\n}"""

EVENT_SCHEMA_MISSING_BRACE_ON_VARIABLE = """{\r\n   \"schema\": \r\n   {\r\n       \"$schema\": \"http://json-schema.org/draft-04/schema#\",\r\n       \"title\": \"Shot Rep Report\",\r\n     \r\n       \"type\": \"object\",\r\n\r\n       \"properties\": \r\n       {\r\n            \"shotrepTimeOfShot\": {\r\n                \"type\": \"string\",\r\n                \"title\": \"Line 1: Time when shot was heard\"\r\n            },\r\n            \"shotrepBearing\": {\r\n                \"type\": \"number\",\r\n                \"title\": \"Line 2: Bearing to Shot\",\r\n                \"minimum\": 0,\r\n                \"maximum\":  360\r\n            },                      \r\n            \"shotrepDistance\": {\r\n                \"type\": \"number\",\r\n                \"title\": \"Line 3: Distance of Shots\",\r\n                \"minimum\": 0\r\n            },                      \r\n            \"shotrepNumberOfShots\": {\r\n                \"type\": \"number\",\r\n                \"title\": \"Line 4: Number of Shots\",\r\n                \"minimum\": 0\r\n            },\r\n            \"shotrepTypeOfShots\": {\r\n            \t\"type\": \"string\",\r\n            \t\"title\": \"Line 5. Type of Shots\",\r\n                \"enum\": {{table___TypeOfShots___values},\r\n                \"enumNames\": {{table___TypeOfShots___names}}\r\n            },              \r\n            \"shotrepEstimatedCaliber\": {\r\n                \"type\": \"string\",\r\n                \"title\": \"Line 6: Estimated Caliber\"\r\n            },\r\n            \"shotrepEstimatedTarget\": {\r\n                \"type\": \"string\",\r\n                \"title\": \"Line 7: Estimated Target\"\r\n            }\r\n       }\r\n   },\r\n \"definition\": [\r\n   {\r\n   \"key\": \"shotrepTimeOfShot\",\r\n   \"fieldHtmlClass\": \"date-time-picker json-schema\",\r\n   \"readonly\": false\r\n   },\r\n   \"shotrepBearing\",\r\n   \"shotrepDistance\",\r\n   \"shotrepNumberOfShots\",\r\n   \"shotrepTypeOfShots\",\r\n   \"shotrepEstimatedCaliber\",\r\n   \"shotrepEstimatedTarget\"\r\n ]\r\n}"""

EVENT_SCHEMA_MISSING_COMMA_AFTER_VARIABLE = """{\r\n   \"schema\": \r\n   {\r\n       \"$schema\": \"http://json-schema.org/draft-04/schema#\",\r\n       \"title\": \"Shot Rep Report\",\r\n     \r\n       \"type\": \"object\",\r\n\r\n       \"properties\": \r\n       {\r\n            \"shotrepTimeOfShot\": {\r\n                \"type\": \"string\",\r\n                \"title\": \"Line 1: Time when shot was heard\"\r\n            },\r\n            \"shotrepBearing\": {\r\n                \"type\": \"number\",\r\n                \"title\": \"Line 2: Bearing to Shot\",\r\n                \"minimum\": 0,\r\n                \"maximum\":  360\r\n            },                      \r\n            \"shotrepDistance\": {\r\n                \"type\": \"number\",\r\n                \"title\": \"Line 3: Distance of Shots\",\r\n                \"minimum\": 0\r\n            },                      \r\n            \"shotrepNumberOfShots\": {\r\n                \"type\": \"number\",\r\n                \"title\": \"Line 4: Number of Shots\",\r\n                \"minimum\": 0\r\n            },\r\n            \"shotrepTypeOfShots\": {\r\n            \t\"type\": \"string\",\r\n            \t\"title\": \"Line 5. Type of Shots\",\r\n                \"enum\": {{table___TypeOfShots___values}}\r\n                \"enumNames\": {{table___TypeOfShots___names}}\r\n            },              \r\n            \"shotrepEstimatedCaliber\": {\r\n                \"type\": \"string\",\r\n                \"title\": \"Line 6: Estimated Caliber\"\r\n            },\r\n            \"shotrepEstimatedTarget\": {\r\n                \"type\": \"string\",\r\n                \"title\": \"Line 7: Estimated Target\"\r\n            }\r\n       }\r\n   },\r\n \"definition\": [\r\n   {\r\n   \"key\": \"shotrepTimeOfShot\",\r\n   \"fieldHtmlClass\": \"date-time-picker json-schema\",\r\n   \"readonly\": false\r\n   },\r\n   \"shotrepBearing\",\r\n   \"shotrepDistance\",\r\n   \"shotrepNumberOfShots\",\r\n   \"shotrepTypeOfShots\",\r\n   \"shotrepEstimatedCaliber\",\r\n   \"shotrepEstimatedTarget\"\r\n ]\r\n}"""

EVENT_SCHEMA_INCORRECT_TAG = """{\r\n   \"schema\": \r\n   {\r\n       \"$schema\": \"http://json-schema.org/draft-04/schema#\",\r\n       \"title\": \"Shot Rep Report\",\r\n     \r\n       \"type\": \"object\",\r\n\r\n       \"properties\": \r\n       {\r\n            \"shotrepTimeOfShot\": {\r\n                \"type\": \"string\",\r\n                \"title\": \"Line 1: Time when shot was heard\"\r\n            },\r\n            \"shotrepBearing\": {\r\n                \"type\": \"number\",\r\n                \"title\": \"Line 2: Bearing to Shot\",\r\n                \"minimum\": 0,\r\n                \"maximum\":  360\r\n            },                      \r\n            \"shotrepDistance\": {\r\n                \"type\": \"number\",\r\n                \"title\": \"Line 3: Distance of Shots\",\r\n                \"minimum\": 0\r\n            },                      \r\n            \"shotrepNumberOfShots\": {\r\n                \"type\": \"number\",\r\n                \"title\": \"Line 4: Number of Shots\",\r\n                \"minimum\": 0\r\n            },\r\n            \"shotrepTypeOfShots\": {\r\n            \t\"type\": \"string\",\r\n            \t\"title\": \"Line 5. Type of Shots\",\r\n                \"enum\": {{table__TypeOfShots___values}},\r\n                \"enumNames\": {{table___TypeOfShots___names}}\r\n            },              \r\n            \"shotrepEstimatedCaliber\": {\r\n                \"type\": \"string\",\r\n                \"title\": \"Line 6: Estimated Caliber\"\r\n            },\r\n            \"shotrepEstimatedTarget\": {\r\n                \"type\": \"string\",\r\n                \"title\": \"Line 7: Estimated Target\"\r\n            }\r\n       }\r\n   },\r\n \"definition\": [\r\n   {\r\n   \"key\": \"shotrepTimeOfShot\",\r\n   \"fieldHtmlClass\": \"date-time-picker json-schema\",\r\n   \"readonly\": false\r\n   },\r\n   \"shotrepBearing\",\r\n   \"shotrepDistance\",\r\n   \"shotrepNumberOfShots\",\r\n   \"shotrepTypeOfShots\",\r\n   \"shotrepEstimatedCaliber\",\r\n   \"shotrepEstimatedTarget\"\r\n ]\r\n}"""


class TestEventTypeForm(TestCase):
    def test_schema_with_missing_comma_returns_error(self):
        form = EventTypeForm(
            data={"schema": EVENT_SCHEMA_MISSING_COMMA_AFTER_VARIABLE})
        self.assertFalse(form.is_valid())
        self.assertEqual(form.errors["schema"],
                         [SCHEMA_ERROR_JSON_DECODE_ERROR])

    def test_schema_with_malformed_enum_returns_error(self):
        form = EventTypeForm(
            data={"schema": EVENT_SCHEMA_MISSING_BRACE_ON_VARIABLE})
        self.assertFalse(form.is_valid())
        self.assertEqual(form.errors["schema"],
                         [SCHEMA_ERROR_JSON_DECODE_ERROR])

    def test_correct_schema_form_is_valid(self):
        form = EventTypeForm(data={"schema": EVENT_SCHEMA})
        self.assertTrue(form.is_valid())

    def test_incorrect_tag_throws_error(self):
        form = EventTypeForm(
            data={"schema": EVENT_SCHEMA_INCORRECT_TAG})
        self.assertFalse(form.is_valid())
        self.assertEqual(form.errors["schema"],
                         [SCHEMA_ERROR_INCORRECT_RENDER_TAG])
