"""Tests for ``EventTypeRevisionHistory`` primitives.

These tests pin the **fingerprint definitions** (what counts as a
migration revision, what counts as a "schema-touching" diff) and the
**replay semantics** of ``schema_at`` separately from any classifier
or apply logic. Future ops (``revision_as_of``, ``revision_restore``,
ad-hoc repairs) all build on these primitives, so changes here are
load-bearing.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any

from activity.schemas.ops import revision_history as ops_revision_history
from activity.schemas.ops.revision_history import EventTypeRevisionHistory
from revision.manager import ACTION_ADDED, ACTION_DELETED, ACTION_UPDATED


def test_inlined_action_constants_match_revision_manager():
    """Guard against drift between the inlined action constants in
    :mod:`activity.schemas.ops.revision_history` and the canonical values
    in :mod:`revision.manager`. The constants are inlined so the ops
    module stays importable without triggering Django's app-registry; if
    the revision system ever renames its action strings, this test fires
    immediately.
    """
    assert ops_revision_history.ACTION_ADDED == ACTION_ADDED
    assert ops_revision_history.ACTION_UPDATED == ACTION_UPDATED


@dataclass
class FakeRevision:
    """Minimal stand-in for an ``EventTypeRevision`` row.

    Satisfies :class:`activity.schemas.ops.revision_history.RevisionLike`
    without standing up the autogenerated revision model.
    """

    sequence: int
    action: str
    data: dict[str, Any] | None


def _history(*revisions: FakeRevision) -> EventTypeRevisionHistory:
    return EventTypeRevisionHistory.from_revisions(
        event_type_value="x",
        event_type_id="11111111-1111-1111-1111-111111111111",
        revisions=revisions,
    )


# ── from_revisions / ordering ─────────────────────────────────────────────


class TestFromRevisions:
    def test_revisions_sorted_ascending_even_when_passed_unordered(self):
        history = _history(
            FakeRevision(3, ACTION_UPDATED, {"schema": "v3"}),
            FakeRevision(1, ACTION_ADDED, {"schema": "v1"}),
            FakeRevision(2, ACTION_UPDATED, {"schema": "v2"}),
        )
        assert [r.sequence for r in history.revisions] == [1, 2, 3]

    def test_empty_history_is_legal(self):
        history = _history()
        assert history.revisions == ()
        assert history.creation_snapshot() is None
        assert history.migration_revision() is None
        assert history.schema_at(1) is None
        assert history.post_migration_schema_edit_count() == 0


# ── creation_snapshot ─────────────────────────────────────────────────────


class TestCreationSnapshot:
    def test_returns_first_action_added(self):
        history = _history(
            FakeRevision(1, ACTION_ADDED, {"schema": "v1"}),
            FakeRevision(2, ACTION_UPDATED, {"schema": "v2"}),
        )
        snapshot = history.creation_snapshot()
        assert snapshot is not None
        assert snapshot.sequence == 1

    def test_returns_none_when_no_added_revision(self):
        history = _history(
            FakeRevision(1, ACTION_UPDATED, {"schema": "v1"}),
        )
        assert history.creation_snapshot() is None


# ── migration_revision ────────────────────────────────────────────────────


class TestMigrationRevision:
    """Pin the V1→V2 fingerprint: ACTION_UPDATED + data contains both
    'schema' and 'version' AND version == "2"."""

    def test_detects_schema_plus_version_2_diff(self):
        history = _history(
            FakeRevision(1, ACTION_ADDED, {"schema": "v1text", "version": "1"}),
            FakeRevision(2, ACTION_UPDATED, {"schema": "v2text", "version": "2"}),
        )
        rev = history.migration_revision()
        assert rev is not None
        assert rev.sequence == 2

    def test_ignores_schema_only_diffs(self):
        history = _history(
            FakeRevision(1, ACTION_ADDED, {"schema": "v1text", "version": "1"}),
            FakeRevision(2, ACTION_UPDATED, {"schema": "edited"}),  # no version key
        )
        assert history.migration_revision() is None

    def test_ignores_version_only_diffs(self):
        history = _history(
            FakeRevision(1, ACTION_ADDED, {"schema": "v1text", "version": "1"}),
            FakeRevision(2, ACTION_UPDATED, {"version": "2"}),  # no schema key
        )
        assert history.migration_revision() is None

    def test_ignores_action_added_even_when_payload_matches(self):
        # The creation snapshot of a V2-from-creation EventType has both
        # 'schema' and 'version=2' in its data — but it's ACTION_ADDED,
        # not a migration. The classifier downstream relies on this.
        history = _history(
            FakeRevision(1, ACTION_ADDED, {"schema": "v2text", "version": "2"}),
        )
        assert history.migration_revision() is None

    def test_returns_first_match_when_multiple_present(self):
        # Anomalous history (e.g. direct DB writes); first match wins.
        # Surfacing the anomaly is the caller's responsibility.
        history = _history(
            FakeRevision(1, ACTION_ADDED, {"schema": "v1text", "version": "1"}),
            FakeRevision(2, ACTION_UPDATED, {"schema": "v2a", "version": "2"}),
            FakeRevision(3, ACTION_UPDATED, {"schema": "v2b", "version": "2"}),
        )
        rev = history.migration_revision()
        assert rev is not None
        assert rev.sequence == 2

    def test_handles_none_data(self):
        history = _history(
            FakeRevision(1, ACTION_ADDED, {"schema": "v1text"}),
            FakeRevision(2, ACTION_UPDATED, None),
        )
        assert history.migration_revision() is None


# ── revisions_modifying ───────────────────────────────────────────────────


class TestRevisionsModifying:
    def test_returns_only_updated_revisions_with_field(self):
        history = _history(
            FakeRevision(1, ACTION_ADDED, {"schema": "v1", "display": "X"}),
            FakeRevision(2, ACTION_UPDATED, {"schema": "v2"}),
            FakeRevision(3, ACTION_UPDATED, {"display": "Y"}),
            FakeRevision(4, ACTION_UPDATED, {"schema": "v3"}),
        )
        seqs = [r.sequence for r in history.revisions_modifying("schema")]
        assert seqs == [2, 4]

    def test_after_filter_is_exclusive(self):
        history = _history(
            FakeRevision(1, ACTION_ADDED, {"schema": "v1"}),
            FakeRevision(2, ACTION_UPDATED, {"schema": "v2"}),
            FakeRevision(3, ACTION_UPDATED, {"schema": "v3"}),
        )
        seqs = [r.sequence for r in history.revisions_modifying("schema", after=2)]
        assert seqs == [3]

    def test_excludes_action_deleted(self):
        history = _history(
            FakeRevision(1, ACTION_ADDED, {"schema": "v1"}),
            FakeRevision(2, ACTION_DELETED, {}),
            FakeRevision(3, ACTION_UPDATED, {"schema": "v3"}),
        )
        seqs = [r.sequence for r in history.revisions_modifying("schema")]
        assert seqs == [3]


# ── schema_at ─────────────────────────────────────────────────────────────


class TestSchemaAt:
    def test_returns_snapshot_value_at_snapshot_sequence(self):
        history = _history(
            FakeRevision(1, ACTION_ADDED, {"schema": "v1text"}),
            FakeRevision(2, ACTION_UPDATED, {"schema": "v2text"}),
        )
        assert history.schema_at(1) == "v1text"

    def test_replays_diffs_inclusive_of_target(self):
        history = _history(
            FakeRevision(1, ACTION_ADDED, {"schema": "a"}),
            FakeRevision(2, ACTION_UPDATED, {"schema": "b"}),
            FakeRevision(3, ACTION_UPDATED, {"schema": "c"}),
        )
        assert history.schema_at(2) == "b"
        assert history.schema_at(3) == "c"

    def test_skips_revisions_that_do_not_touch_schema(self):
        history = _history(
            FakeRevision(1, ACTION_ADDED, {"schema": "a"}),
            FakeRevision(2, ACTION_UPDATED, {"display": "X"}),  # no schema diff
            FakeRevision(3, ACTION_UPDATED, {"schema": "c"}),
        )
        assert history.schema_at(2) == "a"
        assert history.schema_at(3) == "c"

    def test_returns_none_when_sequence_predates_snapshot(self):
        history = _history(
            FakeRevision(2, ACTION_ADDED, {"schema": "a"}),
            FakeRevision(3, ACTION_UPDATED, {"schema": "b"}),
        )
        assert history.schema_at(1) is None

    def test_returns_none_when_no_creation_snapshot(self):
        history = _history(
            FakeRevision(1, ACTION_UPDATED, {"schema": "b"}),
        )
        assert history.schema_at(1) is None

    def test_returns_none_when_snapshot_lacks_schema_key(self):
        history = _history(
            FakeRevision(1, ACTION_ADDED, {"display": "X"}),
            FakeRevision(2, ACTION_UPDATED, {"schema": "b"}),
        )
        assert history.schema_at(2) is None

    def test_returns_none_when_value_is_not_a_string(self):
        # Defensive: an UPDATE row that explicitly sets schema to null
        # should not poison schema_at — return None instead of raising.
        history = _history(
            FakeRevision(1, ACTION_ADDED, {"schema": "a"}),
            FakeRevision(2, ACTION_UPDATED, {"schema": None}),
        )
        assert history.schema_at(2) is None


# ── schema_just_before_migration ──────────────────────────────────────────


class TestSchemaJustBeforeMigration:
    def test_happy_path_returns_replayed_v1(self):
        history = _history(
            FakeRevision(1, ACTION_ADDED, {"schema": "v1a", "version": "1"}),
            FakeRevision(2, ACTION_UPDATED, {"schema": "v1b"}),
            FakeRevision(3, ACTION_UPDATED, {"schema": "v2", "version": "2"}),
        )
        schema, notes = history.schema_just_before_migration()
        assert schema == "v1b"
        assert notes == []

    def test_notes_when_no_migration_revision(self):
        history = _history(
            FakeRevision(1, ACTION_ADDED, {"schema": "v1"}),
        )
        schema, notes = history.schema_just_before_migration()
        assert schema is None
        assert notes  # diagnostic populated

    def test_notes_when_no_creation_snapshot(self):
        history = _history(
            FakeRevision(5, ACTION_UPDATED, {"schema": "v2", "version": "2"}),
        )
        schema, notes = history.schema_just_before_migration()
        assert schema is None
        assert notes

    def test_notes_when_snapshot_missing_schema_key(self):
        history = _history(
            FakeRevision(1, ACTION_ADDED, {"display": "X"}),
            FakeRevision(2, ACTION_UPDATED, {"schema": "v2", "version": "2"}),
        )
        schema, notes = history.schema_just_before_migration()
        assert schema is None
        assert notes

    def test_notes_when_replay_yields_empty_string(self):
        history = _history(
            FakeRevision(1, ACTION_ADDED, {"schema": "", "version": "1"}),
            FakeRevision(2, ACTION_UPDATED, {"schema": "v2", "version": "2"}),
        )
        schema, notes = history.schema_just_before_migration()
        assert schema is None
        assert notes


# ── post_migration_schema_edit_count ──────────────────────────────────────


class TestPostMigrationSchemaEditCount:
    def test_zero_when_no_migration(self):
        history = _history(
            FakeRevision(1, ACTION_ADDED, {"schema": "v1", "version": "1"}),
        )
        assert history.post_migration_schema_edit_count() == 0

    def test_zero_when_no_post_migration_edits(self):
        history = _history(
            FakeRevision(1, ACTION_ADDED, {"schema": "v1", "version": "1"}),
            FakeRevision(2, ACTION_UPDATED, {"schema": "v2", "version": "2"}),
        )
        assert history.post_migration_schema_edit_count() == 0

    def test_counts_only_post_migration_schema_diffs(self):
        history = _history(
            FakeRevision(1, ACTION_ADDED, {"schema": "v1", "version": "1"}),
            FakeRevision(2, ACTION_UPDATED, {"schema": "v2", "version": "2"}),
            FakeRevision(3, ACTION_UPDATED, {"display": "X"}),  # not schema
            FakeRevision(4, ACTION_UPDATED, {"schema": "v3"}),
            FakeRevision(5, ACTION_UPDATED, {"schema": "v4"}),
        )
        assert history.post_migration_schema_edit_count() == 2
