"""Tests for ``EventTypeRevisionHistory`` primitives.

These tests pin the **fingerprint definitions** (what counts as a
migration revision, what counts as a "schema-touching" diff) and the
**replay semantics** of ``schema_at`` separately from any classifier
or apply logic. Future ops (``revision_as_of``, ``revision_restore``,
ad-hoc repairs) all build on these primitives, so changes here are
load-bearing.
"""

from __future__ import annotations

import json
from dataclasses import dataclass
from typing import Any

import pytest

from django.db import connection
from django.db.migrations.executor import MigrationExecutor

from activity.models import EventType
from activity.schemas.ops import revision_history as ops_revision_history
from activity.schemas.ops.revision_history import (
    EventTypeRevisionHistory,
    fetch_in_migration,
)
from factories import EventTypeFactory
from revision.manager import ACTION_ADDED, ACTION_DELETED, ACTION_UPDATED


def _historical_apps():
    """App-registry state that ``RunPython`` hands the 0202 migration body
    (the project state as of its parent migration). Using this instead of the
    live ``django.apps.apps`` reproduces the historical ``__fake__`` models, so
    these tests exercise the real migration surface."""
    return MigrationExecutor(connection).loader.project_state(("activity", "0201_community_input")).apps


def test_inlined_action_constants_match_revision_manager():
    """Guard against drift between the inlined action constants in
    :mod:`activity.schemas.ops.revision_history` and the canonical values
    in :mod:`revision.manager`. The constants are inlined so the ops
    module stays importable without triggering Django's app-registry; if
    the revision system ever renames its action strings, this test fires
    immediately.
    """
    assert ops_revision_history.ACTION_ADDED == ACTION_ADDED
    assert ops_revision_history.ACTION_UPDATED == ACTION_UPDATED


@dataclass
class FakeRevision:
    """Minimal stand-in for an ``EventTypeRevision`` row.

    Satisfies :class:`activity.schemas.ops.revision_history.RevisionLike`
    without standing up the autogenerated revision model.
    """

    sequence: int
    action: str
    data: dict[str, Any] | None


def _history(*revisions: FakeRevision) -> EventTypeRevisionHistory:
    return EventTypeRevisionHistory.from_revisions(
        event_type_value="x",
        event_type_id="11111111-1111-1111-1111-111111111111",
        revisions=revisions,
    )


# ── from_revisions / ordering ─────────────────────────────────────────────


class TestFromRevisions:
    def test_revisions_sorted_ascending_even_when_passed_unordered(self):
        history = _history(
            FakeRevision(3, ACTION_UPDATED, {"schema": "v3"}),
            FakeRevision(1, ACTION_ADDED, {"schema": "v1"}),
            FakeRevision(2, ACTION_UPDATED, {"schema": "v2"}),
        )
        assert [r.sequence for r in history.revisions] == [1, 2, 3]

    def test_empty_history_is_legal(self):
        history = _history()
        assert history.revisions == ()
        assert history.creation_snapshot() is None
        assert history.migration_revision() is None
        assert history.schema_at(1) is None
        assert history.post_migration_schema_edit_count() == 0


# ── creation_snapshot ─────────────────────────────────────────────────────


class TestCreationSnapshot:
    def test_returns_first_action_added(self):
        history = _history(
            FakeRevision(1, ACTION_ADDED, {"schema": "v1"}),
            FakeRevision(2, ACTION_UPDATED, {"schema": "v2"}),
        )
        snapshot = history.creation_snapshot()
        assert snapshot is not None
        assert snapshot.sequence == 1

    def test_returns_none_when_no_added_revision(self):
        history = _history(
            FakeRevision(1, ACTION_UPDATED, {"schema": "v1"}),
        )
        assert history.creation_snapshot() is None


# ── migration_revision ────────────────────────────────────────────────────


class TestMigrationRevision:
    """Pin the V1→V2 fingerprint: ACTION_UPDATED + data contains both
    'schema' and 'version' AND version == "2"."""

    def test_detects_schema_plus_version_2_diff(self):
        history = _history(
            FakeRevision(1, ACTION_ADDED, {"schema": "v1text", "version": "1"}),
            FakeRevision(2, ACTION_UPDATED, {"schema": "v2text", "version": "2"}),
        )
        rev = history.migration_revision()
        assert rev is not None
        assert rev.sequence == 2

    def test_ignores_schema_only_diffs(self):
        history = _history(
            FakeRevision(1, ACTION_ADDED, {"schema": "v1text", "version": "1"}),
            FakeRevision(2, ACTION_UPDATED, {"schema": "edited"}),  # no version key
        )
        assert history.migration_revision() is None

    def test_ignores_version_only_diffs(self):
        history = _history(
            FakeRevision(1, ACTION_ADDED, {"schema": "v1text", "version": "1"}),
            FakeRevision(2, ACTION_UPDATED, {"version": "2"}),  # no schema key
        )
        assert history.migration_revision() is None

    def test_ignores_action_added_even_when_payload_matches(self):
        # The creation snapshot of a V2-from-creation EventType has both
        # 'schema' and 'version=2' in its data — but it's ACTION_ADDED,
        # not a migration. The classifier downstream relies on this.
        history = _history(
            FakeRevision(1, ACTION_ADDED, {"schema": "v2text", "version": "2"}),
        )
        assert history.migration_revision() is None

    def test_returns_first_match_when_multiple_present(self):
        # Anomalous history (e.g. direct DB writes); first match wins.
        # Surfacing the anomaly is the caller's responsibility.
        history = _history(
            FakeRevision(1, ACTION_ADDED, {"schema": "v1text", "version": "1"}),
            FakeRevision(2, ACTION_UPDATED, {"schema": "v2a", "version": "2"}),
            FakeRevision(3, ACTION_UPDATED, {"schema": "v2b", "version": "2"}),
        )
        rev = history.migration_revision()
        assert rev is not None
        assert rev.sequence == 2

    def test_handles_none_data(self):
        history = _history(
            FakeRevision(1, ACTION_ADDED, {"schema": "v1text"}),
            FakeRevision(2, ACTION_UPDATED, None),
        )
        assert history.migration_revision() is None


# ── revisions_modifying ───────────────────────────────────────────────────


class TestRevisionsModifying:
    def test_returns_only_updated_revisions_with_field(self):
        history = _history(
            FakeRevision(1, ACTION_ADDED, {"schema": "v1", "display": "X"}),
            FakeRevision(2, ACTION_UPDATED, {"schema": "v2"}),
            FakeRevision(3, ACTION_UPDATED, {"display": "Y"}),
            FakeRevision(4, ACTION_UPDATED, {"schema": "v3"}),
        )
        seqs = [r.sequence for r in history.revisions_modifying("schema")]
        assert seqs == [2, 4]

    def test_after_filter_is_exclusive(self):
        history = _history(
            FakeRevision(1, ACTION_ADDED, {"schema": "v1"}),
            FakeRevision(2, ACTION_UPDATED, {"schema": "v2"}),
            FakeRevision(3, ACTION_UPDATED, {"schema": "v3"}),
        )
        seqs = [r.sequence for r in history.revisions_modifying("schema", after=2)]
        assert seqs == [3]

    def test_excludes_action_deleted(self):
        history = _history(
            FakeRevision(1, ACTION_ADDED, {"schema": "v1"}),
            FakeRevision(2, ACTION_DELETED, {}),
            FakeRevision(3, ACTION_UPDATED, {"schema": "v3"}),
        )
        seqs = [r.sequence for r in history.revisions_modifying("schema")]
        assert seqs == [3]


# ── schema_at ─────────────────────────────────────────────────────────────


class TestSchemaAt:
    def test_returns_snapshot_value_at_snapshot_sequence(self):
        history = _history(
            FakeRevision(1, ACTION_ADDED, {"schema": "v1text"}),
            FakeRevision(2, ACTION_UPDATED, {"schema": "v2text"}),
        )
        assert history.schema_at(1) == "v1text"

    def test_replays_diffs_inclusive_of_target(self):
        history = _history(
            FakeRevision(1, ACTION_ADDED, {"schema": "a"}),
            FakeRevision(2, ACTION_UPDATED, {"schema": "b"}),
            FakeRevision(3, ACTION_UPDATED, {"schema": "c"}),
        )
        assert history.schema_at(2) == "b"
        assert history.schema_at(3) == "c"

    def test_skips_revisions_that_do_not_touch_schema(self):
        history = _history(
            FakeRevision(1, ACTION_ADDED, {"schema": "a"}),
            FakeRevision(2, ACTION_UPDATED, {"display": "X"}),  # no schema diff
            FakeRevision(3, ACTION_UPDATED, {"schema": "c"}),
        )
        assert history.schema_at(2) == "a"
        assert history.schema_at(3) == "c"

    def test_returns_none_when_sequence_predates_any_schema_revision(self):
        history = _history(
            FakeRevision(2, ACTION_ADDED, {"schema": "a"}),
            FakeRevision(3, ACTION_UPDATED, {"schema": "b"}),
        )
        assert history.schema_at(1) is None

    def test_reconstructs_from_update_when_no_creation_snapshot(self):
        # A truncated history (no ACTION_ADDED) is still reconstructable:
        # the schema value is stored verbatim on the UPDATE row.
        history = _history(
            FakeRevision(1, ACTION_UPDATED, {"schema": "b"}),
        )
        assert history.schema_at(1) == "b"

    def test_reconstructs_from_update_when_snapshot_lacks_schema_key(self):
        # Snapshot carries no schema, but a later revision sets one — the
        # later revision is a valid anchor, no creation snapshot required.
        history = _history(
            FakeRevision(1, ACTION_ADDED, {"display": "X"}),
            FakeRevision(2, ACTION_UPDATED, {"schema": "b"}),
        )
        assert history.schema_at(2) == "b"
        # ...but only from the sequence the schema first appears onward.
        assert history.schema_at(1) is None

    def test_returns_none_when_value_is_not_a_string(self):
        # Defensive: an UPDATE row that explicitly sets schema to null
        # should not poison schema_at — return None instead of raising.
        history = _history(
            FakeRevision(1, ACTION_ADDED, {"schema": "a"}),
            FakeRevision(2, ACTION_UPDATED, {"schema": None}),
        )
        assert history.schema_at(2) is None


# ── schema_just_before_migration ──────────────────────────────────────────


class TestSchemaJustBeforeMigration:
    def test_happy_path_returns_replayed_v1(self):
        history = _history(
            FakeRevision(1, ACTION_ADDED, {"schema": "v1a", "version": "1"}),
            FakeRevision(2, ACTION_UPDATED, {"schema": "v1b"}),
            FakeRevision(3, ACTION_UPDATED, {"schema": "v2", "version": "2"}),
        )
        schema, notes = history.schema_just_before_migration()
        assert schema == "v1b"
        assert notes == []

    def test_notes_when_no_migration_revision(self):
        history = _history(
            FakeRevision(1, ACTION_ADDED, {"schema": "v1"}),
        )
        schema, notes = history.schema_just_before_migration()
        assert schema is None
        assert notes  # diagnostic populated

    def test_notes_when_only_schema_is_the_migration_itself(self):
        # The migration revision carries the (V2) schema, but nothing
        # before it does — there is no pre-migration V1 to reconstruct.
        history = _history(
            FakeRevision(5, ACTION_UPDATED, {"schema": "v2", "version": "2"}),
        )
        schema, notes = history.schema_just_before_migration()
        assert schema is None
        assert notes

    def test_notes_when_snapshot_missing_schema_and_no_other_pre_migration_schema(self):
        history = _history(
            FakeRevision(1, ACTION_ADDED, {"display": "X"}),
            FakeRevision(2, ACTION_UPDATED, {"schema": "v2", "version": "2"}),
        )
        schema, notes = history.schema_just_before_migration()
        assert schema is None
        assert notes

    def test_reconstructs_v1_from_update_when_no_creation_snapshot(self):
        # Truncated history: no ACTION_ADDED, but a pre-migration UPDATE
        # carries the V1 schema verbatim → reconstructable.
        history = _history(
            FakeRevision(1, ACTION_UPDATED, {"schema": "v1text"}),
            FakeRevision(2, ACTION_UPDATED, {"schema": "v2text", "version": "2"}),
        )
        schema, notes = history.schema_just_before_migration()
        assert schema == "v1text"
        assert notes == []

    def test_reconstructs_v1_when_snapshot_lacks_schema_but_update_sets_it(self):
        history = _history(
            FakeRevision(1, ACTION_ADDED, {"display": "X"}),
            FakeRevision(2, ACTION_UPDATED, {"schema": "v1text"}),
            FakeRevision(3, ACTION_UPDATED, {"schema": "v2text", "version": "2"}),
        )
        schema, notes = history.schema_just_before_migration()
        assert schema == "v1text"
        assert notes == []

    def test_notes_when_replay_yields_empty_string(self):
        history = _history(
            FakeRevision(1, ACTION_ADDED, {"schema": "", "version": "1"}),
            FakeRevision(2, ACTION_UPDATED, {"schema": "v2", "version": "2"}),
        )
        schema, notes = history.schema_just_before_migration()
        assert schema is None
        assert notes


# ── post_migration_schema_edit_count ──────────────────────────────────────


class TestPostMigrationSchemaEditCount:
    def test_zero_when_no_migration(self):
        history = _history(
            FakeRevision(1, ACTION_ADDED, {"schema": "v1", "version": "1"}),
        )
        assert history.post_migration_schema_edit_count() == 0

    def test_zero_when_no_post_migration_edits(self):
        history = _history(
            FakeRevision(1, ACTION_ADDED, {"schema": "v1", "version": "1"}),
            FakeRevision(2, ACTION_UPDATED, {"schema": "v2", "version": "2"}),
        )
        assert history.post_migration_schema_edit_count() == 0

    def test_counts_only_post_migration_schema_diffs(self):
        history = _history(
            FakeRevision(1, ACTION_ADDED, {"schema": "v1", "version": "1"}),
            FakeRevision(2, ACTION_UPDATED, {"schema": "v2", "version": "2"}),
            FakeRevision(3, ACTION_UPDATED, {"display": "X"}),  # not schema
            FakeRevision(4, ACTION_UPDATED, {"schema": "v3"}),
            FakeRevision(5, ACTION_UPDATED, {"schema": "v4"}),
        )
        assert history.post_migration_schema_edit_count() == 2


# ── fetch_in_migration with historical app-registry models ────────────────


def _v1_schema_text() -> str:
    return json.dumps(
        {
            "schema": {"type": "object", "properties": {"field": {"type": "string", "title": "Field"}}},
            "definition": ["field"],
        }
    )


def _v2_schema_text() -> str:
    return json.dumps({"json": {"properties": {"field": {"type": "string"}}}, "ui": {"fields": {}}})


@pytest.mark.django_db
@pytest.mark.usefixtures("tenant_settings", "das_tenant_monkeypatch")
class TestFetchInMigrationWithHistoricalModels:
    """Guard that ``fetch_in_migration`` survives ``__fake__`` revision models.

    This test fails with ``AttributeError`` if ``fetch_in_migration`` is
    reverted to constructing model instances (the root cause of the production
    bug), and passes when ``values_list(..., named=True)`` is used instead.
    """

    def test_returns_history_with_migration_revision_when_given_historical_model(self) -> None:
        # Seed an EventType that was created as V1 and then migrated to V2, so
        # the revision log contains an ACTION_UPDATED row with both ``schema``
        # and ``version == "2"`` — the migration fingerprint.
        event_type = EventTypeFactory.create(
            value="fetch_in_migration_guard",
            schema=_v1_schema_text(),
            version=EventType.VersionChoices.VERSION_1,
        )
        event_type.schema = _v2_schema_text()
        event_type.version = EventType.VersionChoices.VERSION_2
        event_type.save()

        # Obtain the historical revision model — the same ``__fake__``
        # TenantModel that ``RunPython`` passes to the 0202 migration body.
        # Constructing instances of this model raises AttributeError under
        # django_multitenant; ``fetch_in_migration`` avoids that via
        # ``values_list``.
        revision_model = _historical_apps().get_model("activity", "EventTypeRevision")

        history = fetch_in_migration(
            event_type,
            revision_model=revision_model,
            db_alias="default",
            tenant_id=event_type.das_tenant_id,
        )

        assert len(history.revisions) > 0, "expected at least one revision row"
        assert history.migration_revision() is not None, (
            "expected a migration revision (ACTION_UPDATED with schema+version==2); "
            "fetch_in_migration may have returned empty revisions due to the __fake__ "
            "model AttributeError bug"
        )
