# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-05 18:55
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields.jsonb
import django.contrib.postgres.fields.ranges
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0005_regions_slug_uniq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='row created at'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='point location'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='recorded_at',
            field=models.DateTimeField(verbose_name='recorded at'),
        ),
        migrations.AlterField(
            model_name='region',
            name='country',
            field=models.CharField(max_length=100, verbose_name='country mostly containing region'),
        ),
        migrations.AlterField(
            model_name='region',
            name='region',
            field=models.CharField(max_length=100, verbose_name='region or pa'),
        ),
        migrations.AlterField(
            model_name='region',
            name='slug',
            field=models.SlugField(max_length=100, unique=True, verbose_name='unique id'),
        ),
        migrations.AlterField(
            model_name='source',
            name='additional',
            field=django.contrib.postgres.fields.jsonb.JSONField(verbose_name='additional data'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='additional',
            field=django.contrib.postgres.fields.jsonb.JSONField(verbose_name='additional data'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=100, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_type',
            field=models.CharField(choices=[('wildlife', 'Wildlife'), ('vehicle', 'Vehicle'), ('stationary-object', 'Stationary Object'), ('person', 'Person')], default='wildlife', max_length=100, verbose_name='subject type'),
        ),
        migrations.AlterField(
            model_name='subjectsource',
            name='additional',
            field=django.contrib.postgres.fields.jsonb.JSONField(verbose_name='additional'),
        ),
        migrations.AlterField(
            model_name='subjectsource',
            name='assigned_range',
            field=django.contrib.postgres.fields.ranges.DateTimeRangeField(verbose_name='time assigned to subject'),
        ),
    ]
