# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-17 21:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0008_subject_subtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='group',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='observations.SubjectGroup'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_subtype',
            field=models.CharField(choices=[('Wildlife', (('elephant', 'Elephant'), ('zebra', 'Zebra'), ('rhino', 'Rhino'), ('lion', 'Lion'))), ('Person', (('ranger', 'Ranger'), ('driver', 'Driver'), ('manager', 'Manager'))), ('Vehicle', (('security', 'Security Vehicle'), ('research', 'Research Vehicle'))), ('Stationary Sensor', (('camera-trap', 'Camera Trap'), ('weather-station', 'Weather Sensor')))], db_column='subject_subtype', default='elephant', max_length=100),
        ),
    ]
