# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-30 21:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_use_al'),
        ('observations', '0009_auto_20160217_1316'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='name')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='observations.SourceGroup')),
                ('permission_sets', models.ManyToManyField(blank=True, help_text='The permission sets applied to this table. A user in a permission set is granted these permissions.', to='accounts.PermissionSet')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'permissions': (('view_last_position', 'Allow the user to view the last reported position of a Subject.'), ('view_real_time', 'Access to updated observations as they become available, includes view_last_position.'), ('view_delayed', 'Access to a time dated observation feed. The delay is 24 hours, i.e. can only see yesterday and older observations. No real-time or last position.'), ('subscribe_alerts', 'Permission to subscribe to an alert on this Subject.'), ('change_alerts', 'Permission to configure alerts for subject, includes setting geofences, proximity and immobility settings.'), ('change_view', 'An admin permission to change which users can view a Subject and their view permission.'))},
        ),
        migrations.AlterModelManagers(
            name='subjectgroup',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='subjectgroup',
            name='level',
        ),
        migrations.RemoveField(
            model_name='subjectgroup',
            name='lft',
        ),
        migrations.RemoveField(
            model_name='subjectgroup',
            name='rght',
        ),
        migrations.RemoveField(
            model_name='subjectgroup',
            name='tree_id',
        ),
        migrations.AlterField(
            model_name='subject',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='observations.SubjectGroup'),
        ),
        migrations.AlterField(
            model_name='subjectgroup',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='observations.SubjectGroup'),
        ),
    ]
