# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-10 15:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0010_use_al'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='source',
            options={'permissions': (
            ('view_source', 'Permission to view a source'),)},
        ),
        migrations.AlterModelOptions(
            name='sourcegroup',
            options={'verbose_name': 'source group', 'verbose_name_plural': 'source groups'},
        ),
        migrations.AlterModelOptions(
            name='subjectgroup',
            options={'verbose_name': 'subject group', 'verbose_name_plural': 'subject groups'},
        ),
        migrations.RemoveField(
            model_name='sourcegroup',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='group',
        ),
        migrations.RemoveField(
            model_name='subjectgroup',
            name='parent',
        ),
        migrations.AddField(
            model_name='sourcegroup',
            name='children',
            field=models.ManyToManyField(blank=True, related_name='_parents',
                                         to='observations.SourceGroup'),
        ),
        migrations.AddField(
            model_name='sourcegroup',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sourcegroup',
            name='sources',
            field=models.ManyToManyField(blank=True, related_name='groups',
                                         to='observations.Source'),
        ),
        migrations.AddField(
            model_name='sourcegroup',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subjectgroup',
            name='children',
            field=models.ManyToManyField(blank=True, related_name='_parents',
                                         to='observations.SubjectGroup'),
        ),
        migrations.AddField(
            model_name='subjectgroup',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subjectgroup',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='groups',
                                         to='observations.Subject'),
        ),
        migrations.AddField(
            model_name='subjectgroup',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
