# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-10 17:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0011_group_update'),
    ]

    operations = [

    ]
