# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-12 22:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("observations", "0012_group_data"),
    ]

    operations = []
