# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-13 21:37
from __future__ import unicode_literals

from django.db import migrations
from django.core.management import call_command
from django.contrib.auth.management import create_permissions


def populate_default_groups(apps, schema_editor):
    #initial data references permissions
    apps.models_module = True
    create_permissions(apps, verbosity=0)
    apps.models_module = None
    call_command('loaddata', 'initial_groups')

class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0013_group_permission'),
    ]

    operations = [
        migrations.RunPython(populate_default_groups),
    ]
