# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-28 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0014_group_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='is_active',
            field=models.BooleanField(default=True, help_text='This subject is actively shown in visualizations.', verbose_name='active'),
        ),
    ]
