# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-29 05:36
from __future__ import unicode_literals

import accounts.mixins
import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0015_subject_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('additional', django.contrib.postgres.fields.jsonb.JSONField(verbose_name='additional')),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='location')),
                ('location_at', models.DateTimeField(verbose_name='location at')),
                ('delayed_location', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='delayed location')),
                ('delayed_location_at', models.DateTimeField(verbose_name='delayed location at')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='observations.Subject')),
            ],
            options={
                'abstract': False,
            },
            bases=(accounts.mixins.PermissionSetGroupMixin, models.Model),
        ),
    ]
