# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-03 23:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0016_subject_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subjectstatus',
            options={'verbose_name': 'Subject Status', 'verbose_name_plural': 'Subject Statuses'},
        ),
    ]
