# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-04 23:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0017_featuresets'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'permissions': (('view_last_position', 'Permission to view the last reported position of a Subject only.'), ('view_real_time', 'Access to real-time observations.'), ('view_delayed', 'Access to a 24 hour delayed observation feed. No real-time or last reported position.'), ('subscribe_alerts', 'Permission to subscribe to an alert on this Subject.'), ('change_alerts', 'Permission to configure alerts for subject, includes setting geofences, proximity and immobility settings.'), ('change_view', 'An admin permission to change which users can view a Subject and their view permission.'))},
        ),
    ]
