# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-13 17:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0018_permission_strings'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='provider_name',
            field=models.CharField(default='default', max_length=100, null='False', verbose_name='unique name for data provider'),
        ),
        migrations.AddField(
            model_name='subject',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2015, 11, 1, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subject',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 9, 13, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='source',
            unique_together=set([('provider_name', 'manufacturer_id')]),
        ),
    ]
