# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-13 17:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0019_source_provider_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2015, 11, 1, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='source',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2015, 11, 1, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
