# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-21 19:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0021_update_sources'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='subject_subtype',
            field=models.CharField(choices=[('Wildlife', (('elephant', 'Elephant'), ('zebra', 'Zebra'), ('rhino', 'Rhino'), ('lion', 'Lion'))), ('Person', (('ranger', 'Ranger'), ('driver', 'Driver'), ('manager', 'Manager'))), ('Vehicle', (('security', 'Security Vehicle'), ('research', 'Research Vehicle'))), ('Stationary Sensor', (('camera-trap', 'Camera Trap'), ('weather-station', 'Weather Sensor'))), ('Aircraft', (('plane', 'Plane'), ('helicopter', 'Helicopter')))], db_column='subject_subtype', default='elephant', max_length=100),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_type',
            field=models.CharField(choices=[('wildlife', 'Wildlife'), ('person', 'Person'), ('vehicle', 'Vehicle'), ('stationary-object', 'Stationary Sensor'), ('aircraft', 'Aircraft')], default='wildlife', max_length=100, verbose_name='subject type'),
        ),
    ]
