# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-12 20:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0024_common_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commonname',
            name='subject_subtype',
            field=models.CharField(choices=[('Wildlife', (('elephant', 'Elephant'), ('zebra', 'Zebra'), ('rhino', 'Rhino'), ('lion', 'Lion'), ('giraffe', 'Giraffe'))), ('Person', (('ranger', 'Ranger'), ('ranger_team', 'Ranger Team'), ('driver', 'Driver'), ('manager', 'Manager'))), ('Vehicle', (('security', 'Security Vehicle'), ('research', 'Research Vehicle'), ('motorcycle', 'Motorcycle'))), ('Stationary Sensor', (('camera-trap', 'Camera Trap'), ('weather-station', 'Weather Sensor'))), ('Aircraft', (('plane', 'Plane'), ('helicopter', 'Helicopter')))], max_length=100),
        ),
        migrations.AlterField(
            model_name='subject',
            name='common_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='observations.CommonName'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_subtype',
            field=models.CharField(choices=[('Wildlife', (('elephant', 'Elephant'), ('zebra', 'Zebra'), ('rhino', 'Rhino'), ('lion', 'Lion'), ('giraffe', 'Giraffe'))), ('Person', (('ranger', 'Ranger'), ('ranger_team', 'Ranger Team'), ('driver', 'Driver'), ('manager', 'Manager'))), ('Vehicle', (('security', 'Security Vehicle'), ('research', 'Research Vehicle'), ('motorcycle', 'Motorcycle'))), ('Stationary Sensor', (('camera-trap', 'Camera Trap'), ('weather-station', 'Weather Sensor'))), ('Aircraft', (('plane', 'Plane'), ('helicopter', 'Helicopter')))], db_column='subject_subtype', default='elephant', max_length=100),
        ),
    ]
