# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-01-07 22:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0025_feature_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='observation',
            unique_together=set([('source', 'recorded_at')]),
        ),
        migrations.AlterIndexTogether(
            name='observation',
            index_together=set([]),
        ),
    ]
