# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-12-21 00:35
from __future__ import unicode_literals

import uuid

import django.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("observations", "0025_feature_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubjectTrackSegmentFilter",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ("subject_type", models.TextField(default="SUBTYPE_ELEPHANT")),
                ("speed_KmHr", models.FloatField(default=7.0)),
                ("additional", django.db.models.JSONField()),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
