# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-02-08 20:44
from __future__ import unicode_literals

import datetime

import django.contrib.postgres.fields.ranges
import django.db.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("accounts", "0026_deleting_longer_active_access_token"),
        ("observations", "0028_merge"),
    ]

    operations = [
        migrations.AddField(
            model_name="source",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sources",
                related_query_name="source",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="subject",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="subjects",
                related_query_name="subject",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="source",
            name="additional",
            field=django.db.models.JSONField(default={}, verbose_name="additional data"),
        ),
        migrations.AlterField(
            model_name="subject",
            name="additional",
            field=django.db.models.JSONField(default={}, verbose_name="additional data"),
        ),
        migrations.AlterField(
            model_name="subjectsource",
            name="additional",
            field=django.db.models.JSONField(default={}, verbose_name="additional"),
        ),
        migrations.AlterField(
            model_name="subjectsource",
            name="assigned_range",
            field=django.contrib.postgres.fields.ranges.DateTimeRangeField(
                default=[
                    datetime.datetime(1, 1, 1, 0, 0, tzinfo=datetime.timezone.utc),
                    datetime.datetime(9999, 12, 31, 23, 59, 59, 999999, tzinfo=datetime.timezone.utc),
                ],
                verbose_name="time assigned to subject",
            ),
        ),
    ]
