# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-01-21 08:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0027_recorded_at_index'),
        ('observations', '0027_analyzer_metadata'),
    ]

    operations = [
    ]
