# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-02-08 20:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0028_source_owner'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='source',
            unique_together=set([('owner', 'manufacturer_id')]),
        ),
    ]
