# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-03-22 21:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("observations", "0030_source_provider"),
    ]

    operations = [
        migrations.AddField(
            model_name="observation",
            name="exclusion_flags",
            field=models.BigIntegerField(default=0, verbose_name="Exclusion flags as a bitmap"),
        ),
    ]
