# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-03-22 21:16
from __future__ import unicode_literals

import datetime
import django.contrib.postgres.fields.jsonb
import django.contrib.postgres.fields.ranges
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0030_source_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='observation',
            name='exclusion_flags',
            field=models.BigIntegerField(default=0, verbose_name='Exclusion flags as a bitmap'),
        ),
    ]
