# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-03-27 22:45
from __future__ import unicode_literals

import datetime
import django.contrib.postgres.fields.jsonb
import django.contrib.postgres.fields.ranges
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0032_fix_observations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commonname',
            name='subject_subtype',
            field=models.CharField(choices=[('Wildlife', (('elephant', 'Elephant'), ('zebra', 'Zebra'), ('rhino', 'Rhino'), ('lion', 'Lion'), ('giraffe', 'Giraffe'), ('antelope', 'Antelope'))), ('Person', (('ranger', 'Ranger'), ('ranger_team', 'Ranger Team'), ('driver', 'Driver'), ('manager', 'Manager'))), ('Vehicle', (('security_vehicle', 'Security Vehicle'), ('research', 'Research Vehicle'), ('tourist_vehicle', 'Tourist Vehicle'), ('motorcycle', 'Motorcycle'))), ('Stationary Sensor', (('camera-trap', 'Camera Trap'), ('weather-station', 'Weather Sensor'))), ('Aircraft', (('plane', 'Plane'), ('helicopter', 'Helicopter'))), ('Unassigned', (('unassigned', 'Unassigned'),))], max_length=100),
        ),
        migrations.AlterField(
            model_name='source',
            name='additional',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}, verbose_name='additional data'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='additional',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}, verbose_name='additional data'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_subtype',
            field=models.CharField(choices=[('Wildlife', (('elephant', 'Elephant'), ('zebra', 'Zebra'), ('rhino', 'Rhino'), ('lion', 'Lion'), ('giraffe', 'Giraffe'), ('antelope', 'Antelope'))), ('Person', (('ranger', 'Ranger'), ('ranger_team', 'Ranger Team'), ('driver', 'Driver'), ('manager', 'Manager'))), ('Vehicle', (('security_vehicle', 'Security Vehicle'), ('research', 'Research Vehicle'), ('tourist_vehicle', 'Tourist Vehicle'), ('motorcycle', 'Motorcycle'))), ('Stationary Sensor', (('camera-trap', 'Camera Trap'), ('weather-station', 'Weather Sensor'))), ('Aircraft', (('plane', 'Plane'), ('helicopter', 'Helicopter'))), ('Unassigned', (('unassigned', 'Unassigned'),))], db_column='subject_subtype', default='elephant', max_length=100),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_type',
            field=models.CharField(choices=[('wildlife', 'Wildlife'), ('person', 'Person'), ('vehicle', 'Vehicle'), ('stationary-object', 'Stationary Sensor'), ('aircraft', 'Aircraft'), ('unassigned', 'Unassigned')], default='wildlife', max_length=100, verbose_name='subject type'),
        ),
        migrations.AlterField(
            model_name='subjectsource',
            name='additional',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}, verbose_name='additional'),
        ),
        migrations.AlterField(
            model_name='subjectsource',
            name='assigned_range',
            field=django.contrib.postgres.fields.ranges.DateTimeRangeField(default=[datetime.datetime(1, 1, 1, 0, 0, tzinfo=utc), datetime.datetime(9999, 12, 31, 23, 59, 59, 999999, tzinfo=utc)], verbose_name='time assigned to subject'),
        ),
    ]
