# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-06-15 22:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0037_update_user_permission_sets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commonname',
            name='subject_subtype',
            field=models.CharField(choices=[('Wildlife', (('elephant', 'Elephant'), ('zebra', 'Zebra'), ('rhino', 'Rhino'), ('lion', 'Lion'), ('giraffe', 'Giraffe'), ('antelope', 'Antelope'))), ('Person', (('ranger', 'Ranger'), ('ranger_team', 'Ranger Team'), ('driver', 'Driver'), ('manager', 'Manager'))), ('Vehicle', (('security_vehicle', 'Security Vehicle'), ('research', 'Research Vehicle'), ('tourist_vehicle', 'Tourist Vehicle'), ('motorcycle', 'Motorcycle'))), ('Stationary Sensor', (('camera-trap', 'Camera Trap'), ('weather-station', 'Weather Sensor'))), ('Aircraft', (('plane', 'Plane'), ('helicopter', 'Helicopter'), ('drone', 'Drone'))), ('Unassigned', (('unassigned', 'Unassigned'),))], max_length=100),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_subtype',
            field=models.CharField(choices=[('Wildlife', (('elephant', 'Elephant'), ('zebra', 'Zebra'), ('rhino', 'Rhino'), ('lion', 'Lion'), ('giraffe', 'Giraffe'), ('antelope', 'Antelope'))), ('Person', (('ranger', 'Ranger'), ('ranger_team', 'Ranger Team'), ('driver', 'Driver'), ('manager', 'Manager'))), ('Vehicle', (('security_vehicle', 'Security Vehicle'), ('research', 'Research Vehicle'), ('tourist_vehicle', 'Tourist Vehicle'), ('motorcycle', 'Motorcycle'))), ('Stationary Sensor', (('camera-trap', 'Camera Trap'), ('weather-station', 'Weather Sensor'))), ('Aircraft', (('plane', 'Plane'), ('helicopter', 'Helicopter'), ('drone', 'Drone'))), ('Unassigned', (('unassigned', 'Unassigned'),))], db_column='subject_subtype', default='unassigned', max_length=100),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_type',
            field=models.CharField(choices=[('wildlife', 'Wildlife'), ('person', 'Person'), ('vehicle', 'Vehicle'), ('stationary-object', 'Stationary Sensor'), ('aircraft', 'Aircraft'), ('unassigned', 'Unassigned')], default='unassigned', max_length=100, verbose_name='subject type'),
        ),
    ]
