# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-09-22 23:46
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0042_socketclient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjecttracksegmentfilter',
            name='additional',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
    ]
