# Generated by Django 2.0.1 on 2018-01-18 22:01

from django.db import migrations, models
import django.db.models.deletion
import observations.models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0046_observations_ordering'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='provider',
            field=models.ForeignKey(default=observations.models.get_default_source_provider_id, on_delete=django.db.models.deletion.PROTECT,
                                    related_name='sources', related_query_name='source', to='observations.SourceProvider'),
        ),
    ]
