# Generated by Django 2.0.1 on 2018-03-04 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0047_post-django2-upgrade'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sourceprovider',
            old_name='name',
            new_name='provider_key',
        ),
        migrations.AddField(
            model_name='sourceprovider',
            name='display_name',
            field=models.CharField(
                default='', max_length=100, verbose_name='Display name for source provider.'),
            preserve_default=False,
        ),

        migrations.RunSQL(
            sql='UPDATE observations_sourceprovider SET display_name=provider_key;',
            reverse_sql='',
        )
    ]
