# Generated by Django 2.0.2 on 2018-05-15 22:18

from django.db import migrations, models
import django.db.models.deletion
import observations.models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0049_subject_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourceprovider',
            name='provider_key',
            field=models.CharField(max_length=100, null='False', unique=True,
                                   verbose_name='Natural key for source provider'),
        ),
    ]
