# Generated by Django 2.0.2 on 2018-05-15 22:18

from django.db import migrations, models
import django.db.models.deletion
import observations.models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0049_subject_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subjecttracksegmentfilter',
            old_name='subject_subtype',
            new_name='subject_type',
        ),
        migrations.AlterField(
            model_name='commonname',
            name='subject_type',
            field=models.ForeignKey(default=observations.models.get_default_subjecttype,
                                    on_delete=django.db.models.deletion.PROTECT,
                                    to='observations.SubjectType'),
        ),
        migrations.AlterField(
            model_name='sourceprovider',
            name='provider_key',
            field=models.CharField(max_length=100, null='False', unique=True,
                                   verbose_name='Natural key for source provider'),
        ),
    ]
