# Generated by Django 2.0.2 on 2018-05-15 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0050_subject_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjecttracksegmentfilter',
            name='subject_type',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to='observations.SubjectType'),
        ),
    ]
