# Generated by Django 2.0.2 on 2018-05-15 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0050_subject_type'),
    ]

    operations = [

    ]
