# Generated by Django 2.0.2 on 2018-05-23 20:53
import os
from sys import path
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import observations.models
from django.core.management import call_command

fixture_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), '../fixtures'))
fixture_filename = 'subject_types.yaml'

def load_fixture(apps, schema_editor):
    fixture_file = os.path.join(fixture_dir, fixture_filename)
    call_command('loaddata', fixture_file) 

class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0051_subject_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourceprovider',
            name='additional',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}, verbose_name='additional data'),
        ),
        migrations.RunPython(load_fixture),
    ]
