# Generated by Django 2.0.2 on 2018-05-23 20:53
from functools import partial

import django.db.models
import django.db.models.deletion
from django.core.management import call_command
from django.core.serializers import python
from django.db import migrations

from utils.migrations.defaults import _get_model


def load_subject_types(apps, schema_editor):
    old_get_model = python._get_model

    python._get_model = python._get_model = partial(_get_model, apps)
    try:
        call_command("loaddata", "subject_types")
    finally:
        python._get_model = old_get_model


class Migration(migrations.Migration):
    dependencies = [
        ("observations", "0051_subject_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="sourceprovider",
            name="additional",
            field=django.db.models.JSONField(default={}, verbose_name="additional data"),
        ),
        migrations.RunPython(load_subject_types, reverse_code=migrations.RunPython.noop),
    ]
