# Generated by Django 2.0.2 on 2018-05-23 20:53
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
from django.core.management import call_command


def load_subject_types(apps, schema_editor):
    call_command('loaddata', 'subject_types')


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0051_subject_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourceprovider',
            name='additional',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}, verbose_name='additional data'),
        ),
        migrations.RunPython(load_subject_types,
                             reverse_code=migrations.RunPython.noop),
    ]
