# Generated by Django 2.0.2 on 2018-06-11 19:46

from django.db import migrations, models
import django.db.models.deletion
import observations.models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0051_subject_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectPositionSummary',
            fields=[
            ],
            options={
                'verbose_name': 'Subject Positions',
                'verbose_name_plural': 'Subject Positions',
                'proxy': True,
                'indexes': [],
            },
            bases=('observations.observation',),
        ),
        migrations.CreateModel(
            name='SubjectSummary',
            fields=[
            ],
            options={
                'verbose_name': 'Subject Summary',
                'verbose_name_plural': 'Subject Summary',
                'proxy': True,
                'indexes': [],
            },
            bases=('observations.subject',),
        ),
        migrations.AlterModelOptions(
            name='subjectsource',
            options={'verbose_name': 'Subject Source Assignment',
                     'verbose_name_plural': 'Subject Source Assignments'},
        ),
        migrations.AlterModelOptions(
            name='subjectstatus',
            options={'verbose_name': 'Subject Status',
                     'verbose_name_plural': 'Subject Status'},
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_subtype',
            field=models.ForeignKey(default=observations.models.get_default_subject_subtype,
                                    on_delete=django.db.models.deletion.PROTECT, to='observations.SubjectSubType'),
        ),
        migrations.AlterField(
            model_name='subjectsource',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjectsources',
                                    related_query_name='subjectsource', to='observations.Subject'),
        ),
        migrations.AlterField(
            model_name='subjectsubtype',
            name='display',
            field=models.CharField(blank=True, help_text='Subject Sub-Type description',
                                   max_length=100, verbose_name='Subject Sub-Type'),
        ),
        migrations.AlterField(
            model_name='subjectsubtype',
            name='value',
            field=models.CharField(help_text='System key for the sub-type', max_length=40,
                                   primary_key=True, serialize=False, unique=True, verbose_name='Sub-Type Key'),
        ),
        migrations.AlterField(
            model_name='subjecttype',
            name='display',
            field=models.CharField(blank=True, help_text='Subject Type description',
                                   max_length=100, verbose_name='Subject Type'),
        ),
        migrations.AlterField(
            model_name='subjecttype',
            name='value',
            field=models.CharField(help_text='System key for the subject type', max_length=40,
                                   primary_key=True, serialize=False, unique=True, verbose_name='Subject Type Key'),
        ),
    ]
