# Generated by Django 2.0.2 on 2018-06-11 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0052_observations_friendlynames'),
        ('observations', '0052_sourceprovider_additional'),
    ]

    operations = [
    ]
