# Generated by Django 2.0.2 on 2018-06-22 21:22

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import observations.models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0053_merge_observations_migrations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourceprovider',
            name='additional',
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True, default=dict, verbose_name='additional data'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='additional',
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True, default=dict, verbose_name='additional data'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_subtype',
            field=models.ForeignKey(default=observations.models.get_default_subject_subtype,
                                    on_delete=django.db.models.deletion.PROTECT, to='observations.SubjectSubType'),
        ),
        migrations.AlterField(
            model_name='subjectsource',
            name='additional',
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True, default=dict, verbose_name='additional'),
        ),
        migrations.AlterField(
            model_name='subjecttracksegmentfilter',
            name='additional',
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='source',
            name='additional',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict,
                                                                 verbose_name='additional data'),
        ),
    ]
