# Generated by Django 2.0.2 on 2018-07-03 00:49

import django.db.models.deletion
from django.db import migrations, models

import observations.models


class Migration(migrations.Migration):

    dependencies = [
        ("observations", "0054_jsonfield_default"),
    ]

    operations = [
        # apparently setting index=False prompts these model changes
        migrations.AlterField(
            model_name="observation",
            name="recorded_at",
            field=models.DateTimeField(verbose_name="recorded at"),
        ),
        migrations.AlterField(
            model_name="subject",
            name="subject_subtype",
            field=models.ForeignKey(
                default=observations.models.get_default_subject_subtype,
                on_delete=django.db.models.deletion.PROTECT,
                to="observations.SubjectSubType",
            ),
        ),
        # Wrap in DO block so extension/index creation failures (e.g. PG version mismatch)
        # do not abort the migration.
        migrations.RunSQL(
            sql="""
            DO $$
            BEGIN
              CREATE EXTENSION IF NOT EXISTS btree_gist;
              CREATE INDEX IF NOT EXISTS observations_recorded_at_location_gist
                ON observations_observation USING gist(recorded_at, location);
            EXCEPTION WHEN OTHERS THEN
              NULL;
            END
            $$;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql="drop index if exists observations_observation_recorded_at_02f72adb", reverse_sql=migrations.RunSQL.noop
        ),
    ]
