# Generated by Django 2.0.2 on 2018-08-05 17:00

from django.db import migrations, models
import django.db.models.deletion
import observations.models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0055_change_recorded_at_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectstatus',
            name='last_voice_call_start_at',
            field=models.DateTimeField(
                blank=True, null=True, verbose_name='Last time voice call was initiated'),
        ),
        migrations.AddField(
            model_name='subjectstatus',
            name='location_requested_at',
            field=models.DateTimeField(
                blank=True, null=True, verbose_name='Last time location was requested'),
        ),
        migrations.AddField(
            model_name='subjectstatus',
            name='radio_state',
            field=models.CharField(choices=[('online-gps', 'Online w/GPS'), ('online', 'Online'), ('offline', 'Offline'),
                                            ('alarm', 'Alarm'), ('na', 'Unknown')], default='na', max_length=20, verbose_name='state'),
        ),
        migrations.AddField(
            model_name='subjectstatus',
            name='radio_state_at',
            field=models.DateTimeField(
                blank=True, null=True, verbose_name='Time of state'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_subtype',
            field=models.ForeignKey(default=observations.models.get_default_subject_subtype,
                                    on_delete=django.db.models.deletion.PROTECT, to='observations.SubjectSubType'),
        ),
        migrations.RunSQL(sql='alter table {} set UNLOGGED'.format(observations.models.SubjectStatus._meta.db_table,),
                          reverse_sql='alter table {} set LOGGED'.format(observations.models.SubjectStatus._meta.db_table,))
    ]
