# Generated by Django 2.0.2 on 2018-08-24 00:08

from django.db import migrations


UPDATE_SQL = '''update only observations_subjectstatus
   set radio_state = additional->>'state' || case
                                        when additional->>'state' = 'online' and additional->>'gps_fix' = 'true' then '-gps'
                                        else '' 
                                        end,
       radio_state_at = updated_at
    where additional ? 'state'
         and radio_state is null;


update only observations_subjectstatus
   set last_voice_call_start_at = case
                                   when additional ? 'last_voice_call_start_at' then (additional->>'last_voice_call_start_at')::timestamp with time zone
                                    else last_voice_call_start_at
                                    end
    where additional ? 'last_voice_call_start_at'
         and last_voice_call_start_at is null;
         '''


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0056_subjectstatus'),
    ]

    operations = [
        migrations.RunSQL(sql=UPDATE_SQL, reverse_sql=migrations.RunSQL.noop),
    ]
