# Generated by Django 2.0.6 on 2018-09-13 00:37

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import observations.models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0057_subject_status_retrofit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='subject_subtype',
            field=models.ForeignKey(default=observations.models.get_default_subject_subtype,
                                    on_delete=django.db.models.deletion.PROTECT, to='observations.SubjectSubType'),
        ),
        migrations.AlterField(
            model_name='subjectstatus',
            name='additional',
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True, default=dict, verbose_name='additional'),
        ),
        migrations.AlterField(
            model_name='subjectstatus',
            name='radio_state',
            field=models.CharField(choices=[('online-gps', 'online-gps'), ('online', 'online'), ('offline', 'offline'),
                                            ('alarm', 'alarm'), ('na', 'n/a')], default='na', max_length=20, verbose_name='state'),
        ),
    ]
