# Generated by Django 2.0.2 on 2018-09-14 07:46

from django.db import migrations, models
import django.db.models.deletion
import observations.models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0058_blanks'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectgroup',
            name='is_visible',
            field=models.BooleanField(default=True, help_text='This Subject group is visible in visualizations.', verbose_name='visible'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_subtype',
            field=models.ForeignKey(default=observations.models.get_default_subject_subtype, on_delete=django.db.models.deletion.PROTECT, to='observations.SubjectSubType'),
        ),
    ]
