# Generated by Django 2.0.2 on 2019-02-28 17:44

from django.db import migrations, models
import django.db.models.deletion
import observations.models


NEW_ANIMALS = [{'display': 'Serval', 'value': 'serval'},
               ]

SUBJECT_TYPE_VALUE = 'wildlife'


def load_serval_subtypes(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    SubjectType = apps.get_model('observations', 'SubjectType')
    SubjectSubType = apps.get_model('observations', 'SubjectSubType')
    subject_type = SubjectType.objects.using(
        db_alias).get(value=SUBJECT_TYPE_VALUE)
    for subtype in NEW_ANIMALS:
        defaults = {'display': subtype['display'],
                    'subject_type': subject_type}
        SubjectSubType.objects.using(db_alias).get_or_create(value=subtype['value'],
                                                             defaults=defaults)


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0064_wildebeest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='subject_subtype',
            field=models.ForeignKey(default=observations.models.get_default_subject_subtype, on_delete=django.db.models.deletion.PROTECT, to='observations.SubjectSubType'),
        ),
        migrations.RunPython(load_serval_subtypes,
                             reverse_code=migrations.RunPython.noop),
    ]
