# Generated by Django 2.0.13 on 2019-08-30 13:53

from django.db import migrations, models
import django.db.models.deletion
import observations.models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0068_balloon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='subject_subtype',
            field=models.ForeignKey(default=observations.models.get_default_subject_subtype, on_delete=django.db.models.deletion.PROTECT, to='observations.SubjectSubType'),
        ),
    ]
