# Generated by Django 2.0.13 on 2020-01-14 17:10

from django.db import migrations, models
import django.db.models.deletion
import observations.models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0070_eland'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='row created at'),
        ),
    ]
