# Generated by Django 2.0.13 on 2020-01-07 07:56

from django.db import migrations, models
import django.db.models.deletion
import observations.models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzers', '0034_auto_20200106_2356'),
        ('observations', '0070_eland'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectMaximumSpeed',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('analyzers.observationannotator',),
        ),
        migrations.CreateModel(
            name='SubjectSourceSummary',
            fields=[
            ],
            options={
                'verbose_name': 'Subject Configuration',
                'proxy': True,
                'indexes': [],
            },
            bases=('observations.subjectsource',),
        ),
        migrations.AlterField(
            model_name='observation',
            name='exclusion_flags',
            field=models.BigIntegerField(choices=[(0, 'DEFAULT'), (1, 'EXCLUDED_MANUALLY'), (2, 'EXCLUDED_AUTOMATICALLY'), (3, 'EXCLUDED_BOTH_AUTOMATICALLY_MANUALLY')], default=0, verbose_name='Exclusion flags as a bitmap'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_subtype',
            field=models.ForeignKey(default=observations.models.get_default_subject_subtype, on_delete=django.db.models.deletion.PROTECT, to='observations.SubjectSubType'),
        ),
    ]
