# Generated by Django 2.0.13 on 2019-12-12 12:42

from django.db import migrations, models
import django.db.models.deletion
import observations.models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0070_eland'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation',
            name='exclusion_flags',
            field=models.BigIntegerField(choices=[(0, 'DEFAULT'), (1, 'EXCLUDED_MANUALLY'), (2, 'EXCLUDED_AUTOMATICALLY')], default=0, verbose_name='Exclusion flags as a bitmap'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_subtype',
            field=models.ForeignKey(default=observations.models.get_default_subject_subtype, on_delete=django.db.models.deletion.PROTECT, to='observations.SubjectSubType'),
        ),
    ]
