# Generated by Django 2.0.13 on 2020-01-07 14:47

import bitfield.models
from django.db import migrations, models
import django.db.models.deletion
import observations.models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0070_eland'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation',
            name='exclusion_flags',
            field=bitfield.models.BitField([('EXCLUDED_MANUALLY', 'EXCLUDED_MANUALLY'), ('EXCLUDED_AUTOMATICALLY', 'EXCLUDED_AUTOMATICALLY')], default=0),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_subtype',
            field=models.ForeignKey(default=observations.models.get_default_subject_subtype, on_delete=django.db.models.deletion.PROTECT, to='observations.SubjectSubType'),
        ),
    ]
