# Generated by Django 2.0.13 on 2020-01-17 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0071_auto_20200107_0647'),
        ('observations', '0071_index_observation_created_at'),
    ]

    operations = [
    ]
