# Generated by Django 2.0.3 on 2020-02-07 14:09

import django.db.models
import django.db.models.deletion
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("observations", "0073_husky"),
    ]

    operations = [
        migrations.AlterField(
            model_name="observation",
            name="additional",
            field=django.db.models.JSONField(blank=True, null=True),
        )
    ]
