# Generated by Django 2.2.9 on 2020-06-15 14:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import observations.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('observations', '0077_meta'),
    ]

    operations = [
        migrations.CreateModel(
            name='GPXTrackFile',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('f3e4f74e-0a75-4a7a-8697-6f52d960cafa'), primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255)),
                ('data', models.FileField(upload_to=observations.models.TempStorage)),
                ('file_size', models.IntegerField()),
                ('processed_date', models.DateTimeField(auto_now_add=True)),
                ('processed_status', models.CharField(choices=[('success', 'Success'), ('failure', 'Failure')], max_length=255)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gpx_track_files', related_query_name='gpx_track_file', to=settings.AUTH_USER_MODEL)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='observations.Source')),
            ],
        ),
        migrations.AddField(
            model_name='subject',
            name='import_gpx_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='observations.GPXTrackFile'),
        ),
    ]
