# Generated by Django 2.2.9 on 2020-07-01 18:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import observations.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('observations', '0077_meta'),
    ]

    operations = [
        migrations.CreateModel(
            name='GPXTrackFile',
            fields=[
                ('file_name', models.CharField(blank=True, max_length=225, null=True)),
                ('file_size', models.IntegerField(blank=True, null=True)),
                ('processed_date', models.DateTimeField(auto_now_add=True)),
                ('processed_status', models.CharField(choices=[('success', 'Success'), ('pending', 'Pending'), ('failure', 'Failure')], max_length=255)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('data', models.FileField(blank=True, null=True, upload_to=observations.models.upload_to)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gpx_track_files', related_query_name='gpx_track_file', to=settings.AUTH_USER_MODEL)),
                ('source_assignment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='observations.SubjectSource')),
            ],
            options={
                'verbose_name_plural': 'GPX track file',
                'ordering': ('processed_date',),
            },
        ),
        migrations.AddField(
            model_name='subject',
            name='import_gpx_data',
            field=models.ForeignKey(blank=True, help_text='Click on the button to import gpx data', null=True, on_delete=django.db.models.deletion.SET_NULL, to='observations.GPXTrackFile'),
        ),
    ]
