# Generated by Django 2.2.9 on 2020-06-17 12:21

from django.db import migrations, models
import observations.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0078_auto_20200615_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gpxtrackfile',
            name='data',
            field=models.FileField(blank=True, null=True, upload_to=observations.models.TempStorage),
        ),
        migrations.AlterField(
            model_name='gpxtrackfile',
            name='id',
            field=models.UUIDField(default=uuid.UUID('953e1c5f-ba14-412c-88ea-0e3d45ac2bf5'), primary_key=True, serialize=False),
        ),
    ]
