# Generated by Django 2.2.9 on 2020-06-17 14:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0079_auto_20200617_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gpxtrackfile',
            name='id',
            field=models.UUIDField(default=uuid.UUID('3cc540bd-ba76-4ee2-9bf1-f1d38d0f1e2f'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='subject',
            name='import_gpx_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='observations.GPXTrackFile'),
        ),
    ]
