# Generated by Django 2.2.9 on 2020-07-03 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0079_nest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='import_gpx_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='observations.GPXTrackFile'),
        ),
    ]
