# Generated by Django 2.2.14 on 2020-07-30 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0080_auto_20200703_2253'),
    ]

    operations = [
        migrations.AddField(
            model_name='gpxtrackfile',
            name='points_imported',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='gpxtrackfile',
            name='status_description',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
