# Generated by Django 2.2.14 on 2020-07-23 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0080_auto_20200703_2253'),
    ]

    operations = [
        migrations.AddField(
            model_name='gpxtrackfile',
            name='points_imported',
            field=models.IntegerField(default=0),
        ),
    ]
