# Generated by Django 2.2.9 on 2020-06-17 15:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0080_auto_20200617_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gpxtrackfile',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
