# Generated by Django 2.2.14 on 2020-08-07 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0081_auto_20200730_2134'),
        ('observations', '0081_bearicons'),
    ]

    operations = [
    ]
