# Generated by Django 2.2.9 on 2020-06-17 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0081_auto_20200617_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gpxtrackfile',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
