# Generated by Django 2.2.14 on 2020-07-30 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0081_auto_20200730_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gpxtrackfile',
            name='points_imported',
            field=models.CharField(max_length=225),
        ),
    ]
