# Generated by Django 2.2.9 on 2020-09-21 11:21

from django.db import migrations, models

DEFAULT_SUBJECT_GROUP_ID = "b4c8e9f6-1ccb-4e3f-8c07-3b727b9ec057"


def default_subjectgroup(app_registry, schema_editor):
    db_alias = schema_editor.connection.alias
    subjectgroup = app_registry.get_model('observations', 'SubjectGroup')

    sg = subjectgroup.objects.using(db_alias).filter(id=DEFAULT_SUBJECT_GROUP_ID).first()
    if not sg:
        sg = subjectgroup.objects.using(db_alias).order_by('name').first()
    sg.is_default = True
    sg.save()


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0082_bearicons_and_patrolpoints'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectgroup',
            name='is_default',
            field=models.BooleanField(default=False, help_text='This Subject group is the default for new subjects.', verbose_name='default subject group'),
        ),
        migrations.AddConstraint(
            model_name='subjectgroup',
            constraint=models.UniqueConstraint(condition=models.Q(is_default=True), fields=('is_default',), name='default_subject_group'),
        ),
        migrations.RunPython(default_subjectgroup, reverse_code=migrations.RunPython.noop)
    ]
