# Generated by Django 2.2.9 on 2020-06-18 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0082_auto_20200617_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gpxtrackfile',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='observations.Source'),
        ),
    ]
