# Generated by Django 2.2.9 on 2020-06-18 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0083_auto_20200618_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gpxtrackfile',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='observations.SubjectSource'),
        ),
    ]
