# Generated by Django 2.2.9 on 2020-11-13 15:04

import django.contrib.postgres.fields.ranges
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0084_addax'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(db_column='sid', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('time_range', django.contrib.postgres.fields.ranges.DateTimeRangeField(blank=True, null=True, verbose_name='user session time')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
