# Generated by Django 2.2.14 on 2020-12-11 15:28

from django.db import migrations

NEW_SUBTYPE = {'display': 'Spraycraft', 'value': 'spraycraft'}
SUBJECT_TYPE_VALUE = 'aircraft'


def load_new_subtypes(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    SubjectType = apps.get_model('observations', 'SubjectType')
    SubjectSubType = apps.get_model('observations', 'SubjectSubType')
    subject_type = SubjectType.objects.using(
        db_alias).get(value=SUBJECT_TYPE_VALUE)
    defaults = {
        'display': NEW_SUBTYPE['display'], 'subject_type': subject_type}
    SubjectSubType.objects.using(db_alias).get_or_create(value=NEW_SUBTYPE['value'],
                                                         defaults=defaults)


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0085_user_session_time'),
    ]

    operations = [
        migrations.RunPython(load_new_subtypes,
                             reverse_code=migrations.RunPython.noop),
    ]
