# Generated by Django 2.2.14 on 2021-02-01 12:11

from django.db import migrations

NEW_SUBTYPES = [
    {'display': 'Horse', 'value': 'horse'},
    {'display': 'Great White Shark', 'value': 'great_white_shark'}
]

SUBJECT_TYPE_VALUE = 'wildlife'


def load_new_subtype(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    SubjectType = apps.get_model('observations', 'SubjectType')
    SubjectSubType = apps.get_model('observations', 'SubjectSubType')

    subject_type = SubjectType.objects.using(db_alias).get(value=SUBJECT_TYPE_VALUE)

    for subtype in NEW_SUBTYPES:
        defaults = {'display': subtype['display'], 'subject_type': subject_type}
        SubjectSubType.objects.using(db_alias).get_or_create(value=subtype['value'],
                                                             defaults=defaults)


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0088_socketclient_patrol_filter'),
    ]

    operations = [
        migrations.RunPython(load_new_subtype, reverse_code=migrations.RunPython.noop)

    ]
