# Generated by Django 2.2.9 on 2021-02-24 12:15

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0089_horse_and_shark'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourceprovider',
            name='transforms',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True, verbose_name='transforms'),
        ),
    ]
