# Generated by Django 2.2.9 on 2021-03-04 17:17

from datetime import datetime, timezone

from django.db import migrations


def forward(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    SubjectSource = apps.get_model("observations", "SubjectSource")

    subjectsources = SubjectSource.objects.using(db_alias).all()
    for ss in subjectsources:
        if ss.assigned_range:
            if not ss.assigned_range.upper:
                ss.assigned_range.upper = datetime.max.replace(tzinfo=timezone.utc)
            if not ss.assigned_range.lower:
                ss.assigned_range.lower = datetime.min.replace(tzinfo=timezone.utc)
        ss.save()


class Migration(migrations.Migration):

    dependencies = [
        ("observations", "0090_add_transforms_field"),
    ]

    operations = [migrations.RunPython(forward, reverse_code=migrations.RunPython.noop)]
