# Generated by Django 2.2.9 on 2021-03-08 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0091_update_subjectsource_assignrange'),
    ]

    operations = [
        migrations.RunSQL(
            sql='''DROP MATERIALIZED VIEW IF EXISTS patrols_view''',
            reverse_sql=migrations.RunSQL.noop
        )
    ]
