# Generated by Django 2.2.14 on 2021-03-22 18:17

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0092_drop_patrols_materialized_view'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourceprovider',
            name='transforms',
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True, default=dict, null=True),
        ),
    ]
