# Generated by Django 2.2.14 on 2021-03-22 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0093_transforms'),
        ('observations', '0093_cougar_and_bobcat'),
    ]

    operations = [
    ]
