# Generated by Django 2.2.9 on 2021-03-22 18:59

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0094_merge_20210322_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourceprovider',
            name='transforms',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list, null=True),
        ),
    ]
