# Generated by Django 2.2.9 on 2021-03-25 21:48

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('observations', '0096_add_subtypes_icons'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('sender_id', models.UUIDField(blank=True, default=None, null=True)),
                ('receiver_id', models.UUIDField(blank=True, default=None, null=True)),
                ('message_type', models.CharField(choices=[('inbox', 'Inbox'), ('outbox', 'Outbox')], default='outbox', max_length=40)),
                ('text', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('errored', 'Errored'), ('received', 'received')], default='pending', max_length=40)),
                ('sender_location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('device_location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('message_time', models.DateTimeField()),
                ('read', models.BooleanField(default=False)),
                ('additional', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True, verbose_name='additional data')),
                ('device', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='observations.Source')),
                ('receiver_content_type', models.ForeignKey(blank=True, limit_choices_to=models.Q(models.Q(('app_label', 'observations'), ('model', 'subject')), models.Q(('app_label', 'accounts'), ('model', 'user')), _connector='OR'), null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receiver_content_type', to='contenttypes.ContentType')),
                ('sender_content_type', models.ForeignKey(blank=True, limit_choices_to=models.Q(models.Q(('app_label', 'observations'), ('model', 'subject')), models.Q(('app_label', 'accounts'), ('model', 'user')), _connector='OR'), null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sender_content_type', to='contenttypes.ContentType')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
