# Generated by Django 2.2.9 on 2021-03-24 11:21

from django.db import migrations, models
from observations.materialized_views import PatrolsMaterializedView

view = PatrolsMaterializedView(table_name="patrols_view")
create_patrols_view = view.generate_ddl
drop_patrols_view = '''DROP MATERIALIZED VIEW IF EXISTS patrols_view'''


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0096_add_subtypes_icons'),
    ]

    operations = [
        migrations.RunSQL(
            sql=drop_patrols_view,
            reverse_sql=migrations.RunSQL.noop
        ),
        migrations.AlterField(
            model_name='source',
            name='model_name',
            field=models.CharField(
                max_length=201, null=True, verbose_name='device model name'),
        ),
        migrations.RunSQL(
            sql=create_patrols_view,
            reverse_sql=drop_patrols_view
        ),
    ]
