# Generated by Django 2.2.14 on 2021-04-04 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0098_default_patrol_conf'),
        ('observations', '0097_two_way_messaging'),
    ]

    operations = [
    ]
