# Generated by Django 2.2.9 on 2021-04-14 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0099_two_way'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='sender_location',
        ),
    ]
