# Generated by Django 2.2.9 on 2021-04-22 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0100_vultures_subtypes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='sender_location',
        ),
    ]