# Generated by Django 2.2.9 on 2021-04-30 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0101_two_way_messaging_permissionset'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='sender_location',
        ),
    ]
