# Generated by Django 2.2.9 on 2021-04-08 21:55

from django.db import migrations

NEW_SUBTYPES = [{"display": "Tapir", "value": "tapir"},
                {"display": "Peccary", "value": "peccary"},
                ]


def forwards(apps, schema_editor):
    db_alias = schema_editor.connection.alias

    subject_type_model = apps.get_model('observations', 'SubjectType')
    subject_subtype_model = apps.get_model('observations', 'SubjectSubType')

    subject_type = subject_type_model.objects.using(
        db_alias).get(value='wildlife')

    for subtype in NEW_SUBTYPES:
        defaults = {'display': subtype['display'],
                    'subject_type': subject_type}
        subject_subtype_model.objects.using(db_alias).get_or_create(value=subtype['value'],
                                                                    defaults=defaults)


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0102_remove_sender_location'),
    ]

    operations = [
        migrations.RunPython(forwards, reverse_code=migrations.RunPython.noop)
    ]
