# Generated by Django 2.2.9 on 2021-05-05 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0102_remove_sender_location'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ('-message_time',)},
        ),
        migrations.AlterIndexTogether(
            name='message',
            index_together={('sender_id', 'message_time'), ('receiver_id', 'message_time')},
        ),
    ]
