# Generated by Django 2.2.9 on 2021-05-05 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0102_remove_sender_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message_time',
            field=models.DateTimeField(db_index=True),
        ),
    ]
