# Generated by Django 2.2.9 on 2021-05-07 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0103_tapir'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ('-message_time',)},
        ),
        migrations.AlterIndexTogether(
            name='message',
            index_together={('sender_id', 'message_time'), ('receiver_id', 'message_time')},
        ),
    ]
