# Generated by Django 2.2.9 on 2021-06-25 17:19

import uuid

import django.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("observations", "0104_index_message"),
    ]

    operations = [
        migrations.CreateModel(
            name="Announcement",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255, null=True)),
                ("description", django.db.models.JSONField(blank=True, default=dict, null=True)),
                ("link", models.URLField(null=True, verbose_name="Link to topic")),
                ("related_users", models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
