# Generated by Django 2.2.9 on 2021-07-14 17:38

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


def forwards(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    announcements = apps.get_model('observations', 'Announcement')
    announcements.objects.using(db_alias).all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0105_announcements'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='additional',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.RunPython(code=forwards, reverse_code=migrations.RunPython.noop)
    ]
