# Generated by Django 2.2.14 on 2021-10-18 15:25

from django.db import migrations, models
import django.db.models.deletion
import observations.models


NEW_SUBTYPES = [
    
    {'display': 'Door', 'value': 'static-door'},
    {'display': 'Fence', 'value': 'static-fence'},
    {'display': 'Gas Tank', 'value': "static-gas-tank"},
    {'display': 'Gate', 'value': "static-gate"},
    {'display': 'Water Tank', 'value': "static-water-tank"},
    {'display': 'Weather', 'value': "static-weather"},
    {'display': 'Water Gauge', 'value': "static-water-gauge"},
    
]

SUBJECT_TYPE_VALUE = 'stationary-object'


def load_new_subtypes(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    SubjectType = apps.get_model('observations', 'SubjectType')
    SubjectSubType = apps.get_model('observations', 'SubjectSubType')
    subject_type = SubjectType.objects.using(
        db_alias).get(value=SUBJECT_TYPE_VALUE)
    for subtype in NEW_SUBTYPES:
        defaults = {'display': subtype['display'],
                    'subject_type': subject_type}
        SubjectSubType.objects.using(db_alias).get_or_create(value=subtype['value'],
                                                             defaults=defaults)


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0109_chimp'),
    ]

    operations = [
        migrations.RunPython(load_new_subtypes,
                             reverse_code=migrations.RunPython.noop),
    ]
