# Generated by Django 2.2.24 on 2022-01-15 00:59

from django.db import migrations
import observations.models

class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0111_aardvark'),
    ]

    operations = [
        migrations.RunSQL(sql='alter table {} set LOGGED'.format(
                              observations.models.SubjectStatus._meta.db_table, ),
                        reverse_sql='alter table {} set UNLOGGED'.format(observations.models.SubjectStatus._meta.db_table, ))
    ]
