# Generated by Django 2.2.14 on 2021-12-07 15:39

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0112_make_subjectstatus_logged_again'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectsource',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True, null=True, srid=4326, verbose_name='Assigned location'),
        ),
    ]
