# Generated by Django 2.2.24 on 2022-02-02 23:55

from django.db import migrations


def rename_subject_type_stationary_sensor(apps, schema_editor):
    SubjectType = apps.get_model('observations', 'SubjectType')

    subject_type = SubjectType.objects.filter(display="Stationary Sensor")
    subject_type.update(display="Stationary subject")


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0113_add_static_sensor_position_field'),
    ]

    operations = [
        migrations.RunPython(rename_subject_type_stationary_sensor,
                             reverse_code=migrations.RunPython.noop),
    ]
