# Generated by Django 2.2.24 on 2022-02-14 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0114_rename_stationary_sensor'),
        ('observations', '0113_elkmale'),
    ]

    operations = [
    ]
