# Generated by Django 2.2.24 on 2022-02-14 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0114_atlantic_shark'),
        ('observations', '0115_elk_merge'),
    ]

    operations = [
    ]
