# Generated by Django 2.2.24 on 2022-04-21 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0119_create_latest_observation_source_table'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE FUNCTION populate_latest_observation_source_table()
                RETURNS VOID
                LANGUAGE plpgsql
            AS
            $$
            DECLARE
                source_item     RECORD;
                tmp_source      UUID;
                tmp_observation UUID;
                tmp_recorded_at TIMESTAMP;
            BEGIN
                FOR source_item IN SELECT DISTINCT(id) FROM observations_source
                    LOOP
                        IF exists(SELECT *
                                  FROM observations_observation
                                  WHERE source_id = source_item.id
                                  ORDER BY recorded_at DESC
                                  LIMIT 1) THEN
                            SELECT source_id, id, recorded_at
                            INTO tmp_source, tmp_observation, tmp_recorded_at
                            FROM observations_observation
                            WHERE source_id = source_item.id
                            ORDER BY recorded_at DESC
                            LIMIT 1;
                            INSERT INTO observations_latestobservationsource(source_id, observation_id, recorded_at)
                            VALUES (tmp_source, tmp_observation, tmp_recorded_at);
                        END IF;
                    END LOOP;
            END;
            $$;
            """,
            reverse_sql="DROP FUNCTION IF EXISTS populate_latest_observation_source_table();"
        ),
        migrations.RunSQL(
            sql="""
            SELECT populate_latest_observation_source_table()
                FROM observations_observation
                LIMIT 1;
            """,
            reverse_sql="TRUNCATE TABLE latest_observation_source;"
        )
    ]
