# Generated by Django 2.2.24 on 2022-05-18 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0121_create_triggers_for_observations'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            DROP TRIGGER IF EXISTS trigger_delete_latest_observation_source on observations_observation;
            """
        ),
        migrations.RunSQL(
            sql="""
            DROP FUNCTION IF EXISTS delete_latest_observation_source();
            """
        ),
    ]
