# Generated by Django 3.1 on 2022-06-22 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0123_add_canine_tck9_subject_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='additional',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='additional',
            field=models.JSONField(
                blank=True, default=dict, null=True, verbose_name='additional data'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='additional',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='socketclient',
            name='event_filter',
            field=models.JSONField(default=dict, verbose_name='Event filter'),
        ),
        migrations.AlterField(
            model_name='socketclient',
            name='patrol_filter',
            field=models.JSONField(default=dict, verbose_name='Patrol filter'),
        ),
        migrations.AlterField(
            model_name='source',
            name='additional',
            field=models.JSONField(
                blank=True, default=dict, verbose_name='additional data'),
        ),
        migrations.AlterField(
            model_name='sourceprovider',
            name='additional',
            field=models.JSONField(
                blank=True, default=dict, verbose_name='additional data'),
        ),
        migrations.AlterField(
            model_name='sourceprovider',
            name='transforms',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='additional',
            field=models.JSONField(
                blank=True, default=dict, verbose_name='additional data'),
        ),
        migrations.AlterField(
            model_name='subjectsource',
            name='additional',
            field=models.JSONField(
                blank=True, default=dict, verbose_name='additional'),
        ),
        migrations.AlterField(
            model_name='subjectstatus',
            name='additional',
            field=models.JSONField(
                blank=True, default=dict, verbose_name='additional'),
        ),
        migrations.AlterField(
            model_name='subjecttracksegmentfilter',
            name='additional',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
