# Generated by Django 3.2 on 2022-12-21 18:33

from django.db import migrations

from observations.migration_utils import SubjectSubTypeLoader

subject_subtype_loader = (
    SubjectSubTypeLoader(subject_type_value="wildlife")
    .add_subject_subtype(display="Albatross Antipodean", value="albatross_antipodean")
    .add_subject_subtype(display="Albatross Gibsons", value="albatross_gibsons")
    .add_subject_subtype(display="Albatross Northern Royal", value="albatross_northern_royal")
    .add_subject_subtype(display="Albatross Salvins", value="albatross_salvins")
    .add_subject_subtype(display="Hartebeest", value="hartebeest")
    .add_subject_subtype(display="Lynx", value="lynx")
    .add_subject_subtype(display="Petrel Northern Giant", value="petrel_northern_giant")
    .add_subject_subtype(display="Roan", value="roan")
    .add_subject_subtype(display="Tiang", value="tiang")
)


class Migration(migrations.Migration):
    dependencies = [("observations", "0134_add_wing_subtype")]
    operations = [migrations.RunPython(subject_subtype_loader.load, reverse_code=migrations.RunPython.noop)]
