# Generated by Django 3.2 on 2023-02-01 18:42
from django.db import migrations

from observations.migration_utils import SubjectSubTypeLoader

subject_subtype_loader = SubjectSubTypeLoader(subject_type_value="wildlife").add_subject_subtype(
    display="Ocelot", value="ocelot"
)


class Migration(migrations.Migration):
    dependencies = [
        ("observations", "0135_add_albatross_hartesbeest_lynx_petrel_roan_and_tiang_subtypes"),
    ]

    operations = [migrations.RunPython(subject_subtype_loader.load, reverse_code=migrations.RunPython.noop)]
