# Generated by Django 3.2 on 2023-02-03 17:00

from django.db import migrations

from utils.migrations import SubjectSubTypeLoader

subject_subtype_loader = SubjectSubTypeLoader(subject_type_value="stationary-object").add_subject_subtype(
    display="Pump Station", value="static_pump_station"
)


class Migration(migrations.Migration):

    dependencies = [
        ("observations", "0136_add_ocelot_subject_subtypes"),
    ]

    operations = [migrations.RunPython(subject_subtype_loader.load, reverse_code=migrations.RunPython.noop)]
