# Generated by Django 3.2 on 2023-05-08 22:43

from django.db import migrations

from observations.migration_utils import SubjectSubTypeLoader

subject_subtype_loader = SubjectSubTypeLoader(subject_type_value="stationary-object").add_subject_subtype(
    display="Sensor", value="static-sensor"
)


class Migration(migrations.Migration):
    dependencies = [
        ("observations", "0137_add_pump_station_subject_stationary_object"),
    ]

    operations = [
        migrations.RunPython(subject_subtype_loader.load, reverse_code=migrations.RunPython.noop),
    ]
