# Generated by Django 3.2 on 2023-05-23 19:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("observations", "0138_add_static_sensor_icon"),
    ]

    operations = [
        migrations.AddField(
            model_name="subject",
            name="linked_user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="linked_subject",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
