# Generated by Django 3.2.19 on 2023-08-10 12:16
from functools import partial

from django.db import migrations, models

from observations.materialized_views import patrols_view
from utils.migrations import copy_model_column

APP_NAME = "observations"
ID_COLUMN = "id"
MODEL_NAME = "SubjectStatus"
SERIAL_COLUMN = "serial_number"

copy_serial_number = partial(copy_model_column, APP_NAME, MODEL_NAME, ID_COLUMN, SERIAL_COLUMN)


def drop_patrols_view(*args):
    patrols_view.drop_view()


def refresh_patrols_view(*args):
    patrols_view.refresh_view()


class Migration(migrations.Migration):
    dependencies = [(APP_NAME, "0139_add_linked_user_to_subject")]

    operations = [
        migrations.RunPython(drop_patrols_view),
        migrations.AddField(
            model_name=MODEL_NAME.lower(),
            name=SERIAL_COLUMN,
            field=models.IntegerField(null=True),
        ),
        migrations.RunPython(copy_serial_number),
        migrations.AlterField(
            model_name=MODEL_NAME.lower(),
            name=SERIAL_COLUMN,
            field=models.IntegerField(null=False),
        ),
        migrations.RunPython(refresh_patrols_view),
    ]
