# Generated by Django 3.2.19 on 2023-08-25 20:19

from django.db import migrations


def load_new_crocodile_subtype(apps, schema_editor):
    new_subtypes = [
        {"display": "Crocodile", "value": "crocodile"},
    ]

    db_alias = schema_editor.connection.alias
    SubjectType = apps.get_model("observations", "SubjectType")
    SubjectSubType = apps.get_model("observations", "SubjectSubType")
    subject_type = SubjectType.objects.using(db_alias).get(value="wildlife")

    for subtype in new_subtypes:
        defaults = {"display": subtype["display"], "subject_type": subject_type}
        SubjectSubType.objects.using(db_alias).get_or_create(value=subtype["value"], defaults=defaults)


def load_new_vehicles_subtypes(apps, schema_editor):
    new_subtypes = [
        {"display": "SUV", "value": "suv"},
        {"display": "Truck 2", "value": "truck_2"},
        {"display": "Truck 3", "value": "truck_3"},
    ]

    db_alias = schema_editor.connection.alias
    SubjectType = apps.get_model("observations", "SubjectType")
    SubjectSubType = apps.get_model("observations", "SubjectSubType")
    subject_type = SubjectType.objects.using(db_alias).get(value="vehicle")

    for subtype in new_subtypes:
        defaults = {"display": subtype["display"], "subject_type": subject_type}
        SubjectSubType.objects.using(db_alias).get_or_create(value=subtype["value"], defaults=defaults)


class Migration(migrations.Migration):
    dependencies = [
        ("observations", "0141_change_subjectstatus_pk_type_to_uuid"),
    ]

    operations = [
        migrations.RunPython(
            code=load_new_crocodile_subtype,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RunPython(
            code=load_new_vehicles_subtypes,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
