# Generated by Django 3.2.19 on 2023-08-24 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("observations", "0142_add_crocodiles_and_vehicles"),
        ("core", "0006_add_das_tenant_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="subject",
            name="das_tenant",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="core.dastenant"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="subject",
            unique_together={("id", "das_tenant")},
        ),
    ]
