# Generated by Django 3.2.19 on 2023-08-24 19:59

import logging

from django.conf import settings
from django.db import migrations

from core.utils import DASTenantManagement

logger = logging.getLogger(__name__)


def populate_das_tenant_in_subject_model(apps, schema_editor):
    Subject = apps.get_model("observations", "Subject")

    class_models = [Subject]

    das_tenant_management = DASTenantManagement(domain=settings.SERVER_FQDN)
    tenant = das_tenant_management.get_or_create_tenant()

    if tenant:
        for class_model in class_models:
            updated_objects = class_model.objects.all().update(das_tenant=tenant)
            logger.info("%d objects updated of model %s." % (updated_objects, class_model._meta.object_name))
    else:
        logger.error("DAS Tenant not found.")


class Migration(migrations.Migration):
    dependencies = [
        ("observations", "0143_add_das_tenant_into_subject_model"),
    ]

    operations = [
        migrations.RunPython(code=populate_das_tenant_in_subject_model, reverse_code=migrations.RunPython.noop)
    ]
