# Generated by Django 3.2.19 on 2023-09-18 19:32

import django_multitenant.fields

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import observations.models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_migrate_oauth_tables_to_das_custom_models"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("observations", "0144_populate_das_tenant_in_subject_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="announcement",
            name="das_tenant",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="core.dastenant"
            ),
        ),
        migrations.AddField(
            model_name="commonname",
            name="das_tenant",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="core.dastenant"
            ),
        ),
        migrations.AddField(
            model_name="gpxtrackfile",
            name="das_tenant",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="core.dastenant"
            ),
        ),
        migrations.AddField(
            model_name="latestobservationsource",
            name="das_tenant",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="core.dastenant"
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="das_tenant",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="core.dastenant"
            ),
        ),
        migrations.AddField(
            model_name="observation",
            name="das_tenant",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="core.dastenant"
            ),
        ),
        migrations.AddField(
            model_name="region",
            name="das_tenant",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="core.dastenant"
            ),
        ),
        migrations.AddField(
            model_name="socketclient",
            name="das_tenant",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="core.dastenant"
            ),
        ),
        migrations.AddField(
            model_name="source",
            name="das_tenant",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="core.dastenant"
            ),
        ),
        migrations.AddField(
            model_name="sourcegroup",
            name="das_tenant",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="core.dastenant"
            ),
        ),
        migrations.AddField(
            model_name="sourceprovider",
            name="das_tenant",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="core.dastenant"
            ),
        ),
        migrations.AddField(
            model_name="subjectgroup",
            name="das_tenant",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="core.dastenant"
            ),
        ),
        migrations.AddField(
            model_name="subjectsource",
            name="das_tenant",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="core.dastenant"
            ),
        ),
        migrations.AddField(
            model_name="subjectstatus",
            name="das_tenant",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="core.dastenant"
            ),
        ),
        migrations.AddField(
            model_name="subjectsubtype",
            name="das_tenant",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="core.dastenant"
            ),
        ),
        migrations.AddField(
            model_name="subjecttracksegmentfilter",
            name="das_tenant",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="core.dastenant"
            ),
        ),
        migrations.AddField(
            model_name="subjecttype",
            name="das_tenant",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="core.dastenant"
            ),
        ),
        migrations.AddField(
            model_name="usersession",
            name="das_tenant",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="core.dastenant"
            ),
        ),
        migrations.AlterField(
            model_name="commonname",
            name="subject_subtype",
            field=django_multitenant.fields.TenantForeignKey(
                default=observations.models.get_default_subject_subtype,
                on_delete=django.db.models.deletion.PROTECT,
                to="observations.subjectsubtype",
            ),
        ),
        migrations.AlterField(
            model_name="gpxtrackfile",
            name="created_by",
            field=django_multitenant.fields.TenantForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="gpx_track_files",
                related_query_name="gpx_track_file",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="gpxtrackfile",
            name="source_assignment",
            field=django_multitenant.fields.TenantForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="observations.subjectsource"
            ),
        ),
        migrations.AlterField(
            model_name="latestobservationsource",
            name="observation",
            field=django_multitenant.fields.TenantForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="observations.observation"
            ),
        ),
        migrations.AlterField(
            model_name="latestobservationsource",
            name="source",
            field=django_multitenant.fields.TenantForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                related_name="last_observation_sources",
                related_query_name="last_observation_source",
                serialize=False,
                to="observations.source",
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="device",
            field=django_multitenant.fields.TenantForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="observations.source"
            ),
        ),
        migrations.AlterField(
            model_name="observation",
            name="source",
            field=django_multitenant.fields.TenantForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="observations.source"
            ),
        ),
        migrations.AlterField(
            model_name="source",
            name="owner",
            field=django_multitenant.fields.TenantForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sources",
                related_query_name="source",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="source",
            name="provider",
            field=django_multitenant.fields.TenantForeignKey(
                default=observations.models.get_default_source_provider_id,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sources",
                related_query_name="source",
                to="observations.sourceprovider",
            ),
        ),
        migrations.AlterField(
            model_name="subject",
            name="common_name",
            field=django_multitenant.fields.TenantForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="observations.commonname"
            ),
        ),
        migrations.AlterField(
            model_name="subject",
            name="import_gpx_data",
            field=django_multitenant.fields.TenantForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="observations.gpxtrackfile"
            ),
        ),
        migrations.AlterField(
            model_name="subject",
            name="owner",
            field=django_multitenant.fields.TenantForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="subjects",
                related_query_name="subject",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="subject",
            name="subject_subtype",
            field=django_multitenant.fields.TenantForeignKey(
                default=observations.models.get_default_subject_subtype,
                on_delete=django.db.models.deletion.PROTECT,
                to="observations.subjectsubtype",
            ),
        ),
        migrations.AlterField(
            model_name="subjectsource",
            name="source",
            field=django_multitenant.fields.TenantForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="observations.source"
            ),
        ),
        migrations.AlterField(
            model_name="subjectsource",
            name="subject",
            field=django_multitenant.fields.TenantForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subjectsources",
                related_query_name="subjectsource",
                to="observations.subject",
            ),
        ),
        migrations.AlterField(
            model_name="subjectstatus",
            name="subject",
            field=django_multitenant.fields.TenantForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="observations.subject"
            ),
        ),
        migrations.AlterField(
            model_name="subjectsubtype",
            name="subject_type",
            field=django_multitenant.fields.TenantForeignKey(
                default=observations.models.get_default_subject_type,
                on_delete=django.db.models.deletion.PROTECT,
                to="observations.subjecttype",
            ),
        ),
        migrations.AlterField(
            model_name="subjecttracksegmentfilter",
            name="subject_subtype",
            field=django_multitenant.fields.TenantForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="observations.subjectsubtype"
            ),
        ),
        migrations.AlterField(
            model_name="subjectstatus",
            name="serial_number",
            field=models.IntegerField(verbose_name="Serial Number"),
        ),
        migrations.AlterUniqueTogether(
            name="announcement",
            unique_together={("id", "das_tenant")},
        ),
        migrations.AlterUniqueTogether(
            name="commonname",
            unique_together={("value", "das_tenant")},
        ),
        migrations.AlterUniqueTogether(
            name="gpxtrackfile",
            unique_together={("id", "das_tenant")},
        ),
        migrations.AlterUniqueTogether(
            name="latestobservationsource",
            unique_together={("source", "das_tenant")},
        ),
        migrations.AlterUniqueTogether(
            name="message",
            unique_together={("id", "das_tenant")},
        ),
        migrations.AlterUniqueTogether(
            name="observation",
            unique_together={("source", "recorded_at"), ("id", "das_tenant")},
        ),
        migrations.AlterUniqueTogether(
            name="region",
            unique_together={("id", "das_tenant")},
        ),
        migrations.AlterUniqueTogether(
            name="socketclient",
            unique_together={("id", "das_tenant")},
        ),
        migrations.AlterUniqueTogether(
            name="source",
            unique_together={("provider", "manufacturer_id"), ("id", "das_tenant")},
        ),
        migrations.AlterUniqueTogether(
            name="sourcegroup",
            unique_together={("id", "das_tenant")},
        ),
        migrations.AlterUniqueTogether(
            name="sourceprovider",
            unique_together={("id", "das_tenant")},
        ),
        migrations.AlterUniqueTogether(
            name="subjectsource",
            unique_together={("id", "das_tenant")},
        ),
        migrations.AlterUniqueTogether(
            name="subjectstatus",
            unique_together={("subject", "delay_hours"), ("id", "das_tenant")},
        ),
        migrations.AlterUniqueTogether(
            name="subjectsubtype",
            unique_together={("id", "das_tenant")},
        ),
        migrations.AlterUniqueTogether(
            name="subjecttracksegmentfilter",
            unique_together={("id", "das_tenant")},
        ),
        migrations.AlterUniqueTogether(
            name="subjecttype",
            unique_together={("id", "das_tenant")},
        ),
        migrations.AlterUniqueTogether(
            name="usersession",
            unique_together={("id", "das_tenant")},
        ),
        migrations.AddConstraint(
            model_name="subjectgroup",
            constraint=models.UniqueConstraint(fields=("id", "das_tenant"), name="id_and_das_tenant_unique"),
        ),
    ]
