# Generated by Django 3.2.19 on 2023-09-14 15:51

from django.db import migrations, models

from utils.migrations.update_primary_key import add_tenant_to_primary_key

observations_models = [
    "SourceGroup",
    "SourceProvider",
    "Source",
    "Observation",
    "SocketClient",
    "SubjectSource",
    "SubjectSourceSummary",
    "SubjectType",
    "SubjectSubType",
    "SubjectTrackSegmentFilter",
    "SubjectGroup",
    "Subject",
    "SubjectSummary",
    "SubjectPositionSummary",
    "SubjectStatus",
    "SubjectStatusLatest",
    "UserSession",
    "Region",
    "GPXTrackFile",
    "Message",
    "Announcement",
]


def regenerate_primary_keys(apps, schema_editor):
    add_tenant_to_primary_key("observations", observations_models)


class Migration(migrations.Migration):
    dependencies = [
        ("analyzers", "0043_add_tenant_mixing_to_models_with_no_relations"),
        ("observations", "0146_populate_obsevations_with_tenant"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subjectstatus",
            name="serial_number",
            field=models.IntegerField(verbose_name="Serial Number"),
        ),
        migrations.RunPython(code=regenerate_primary_keys, reverse_code=migrations.RunPython.noop),
    ]
