# Generated by Django 3.2.19 on 2023-09-14 15:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("observations", "0146_populate_obsevations_with_tenant"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subjectstatus",
            name="serial_number",
            field=models.IntegerField(verbose_name="Serial Number"),
        ),
    ]
