# Generated by Django 3.2.19 on 2023-09-14 15:51
import logging

from django.apps import apps
from django.conf import settings
from django.db import migrations, models

from core.utils import DASTenantManagement, update_tenant_models
from utils.migrations.update_primary_key import add_tenant_to_primary_key
from utils.tenant.managers import set_tenant

logger = logging.getLogger(__name__)

observations_models = [
    "SourceGroup",
    "SourceProvider",
    "Source",
    "Observation",
    "SocketClient",
    "SubjectSource",
    "SubjectSourceSummary",
    "SubjectType",
    "SubjectSubType",
    "SubjectTrackSegmentFilter",
    "SubjectGroup",
    "Subject",
    "SubjectSummary",
    "SubjectPositionSummary",
    "SubjectStatus",
    "SubjectStatusLatest",
    "UserSession",
    "Region",
    "GPXTrackFile",
    "Message",
    "Announcement",
]


def regenerate_primary_keys(apps, schema_editor):
    add_tenant_to_primary_key("observations", observations_models)


def populate_tenant_into_models(unused, schema_editor):
    models_names = ["Observation", "SubjectStatus", "LatestObservationSource"]
    class_models = [apps.get_model(f"observations.{model_name}") for model_name in models_names]

    das_tenant_management = DASTenantManagement(domain=settings.SERVER_FQDN)
    tenant = das_tenant_management.get_or_create_tenant()
    set_tenant(settings.SERVER_FQDN)

    if tenant:
        update_tenant_models(models=class_models, tenant=tenant)
    else:
        logger.error("DAS Tenant not found.")


class Migration(migrations.Migration):
    dependencies = [
        ("analyzers", "0043_add_tenant_mixing_to_models_with_no_relations"),
        ("observations", "0146_populate_obsevations_with_tenant"),
    ]

    operations = [
        migrations.RunPython(populate_tenant_into_models, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name="subjectstatus",
            name="serial_number",
            field=models.IntegerField(verbose_name="Serial Number"),
        ),
        migrations.RunPython(code=regenerate_primary_keys, reverse_code=migrations.RunPython.noop),
    ]
