# Generated by Django 3.2.19 on 2023-09-25 20:27
from django.conf import settings
from django.core.management import call_command
from django.db import migrations

from utils.models import create_all_permissions, update_all_contenttypes
from utils.tenant.managers import set_tenant


def forward(apps, schema_editor):
    update_all_contenttypes()
    create_all_permissions()
    set_tenant(domain=settings.SERVER_FQDN)
    call_command("loaddata_with_tenant", "new_permission_sets", app_label="observations")


class Migration(migrations.Migration):
    dependencies = [
        ("observations", "0148_update_triggers_for_observations_with_tenant"),
    ]

    operations = [migrations.RunPython(code=forward, reverse_code=migrations.RunPython.noop)]
