# Generated by Django 3.2.19 on 2023-09-25 20:27


from django.conf import settings
from django.core.management import call_command
from django.db import migrations

from accounts.models import PermissionSet, User
from utils.models import create_all_permissions, update_all_contenttypes
from utils.tenant import set_tenant


def update_user_permission_sets():  # comes from observations 0037
    all_time_group = PermissionSet.objects.get(id="cfa2b7b3-4bae-42f3-8691-b119da54af4e")
    restricted_time_group = PermissionSet.objects.get(id="e8211a8b-226e-44bf-8235-598a67427348")

    for user in User.objects.all():
        if user.permission_sets.filter(name="view_realtime").exists():
            user.permission_sets.add(all_time_group)
        else:
            user.permission_sets.add(restricted_time_group)


def forward(apps, schema_editor):
    update_all_contenttypes()
    create_all_permissions()
    set_tenant(domain=settings.SERVER_FQDN)
    call_command("loaddata_with_tenant", "new_permission_sets", app_label="observations")

    update_user_permission_sets()


class Migration(migrations.Migration):
    dependencies = [
        ("observations", "0148_update_triggers_for_observations_with_tenant"),
    ]

    operations = [migrations.RunPython(code=forward, reverse_code=migrations.RunPython.noop)]
