# Generated by Django 3.2.21 on 2023-10-04 00:24

import uuid

from django.apps import apps
from django.db import migrations, models


def cleanup_socket_table_data(unused, schema_editor):
    db_alias = schema_editor.connection.alias
    SocketClient = apps.get_model("observations", "SocketClient")
    UserSession = apps.get_model("observations", "UserSession")

    SocketClient.objects.using(db_alias).all().delete()
    UserSession.objects.using(db_alias).all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_populate_oauth_models_with_tenant"),
        ("observations", "0149_populate_permission_sets"),
    ]

    operations = [
        migrations.RunPython(code=cleanup_socket_table_data, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name="socketclient",
            name="id",
            field=models.UUIDField(db_column="id", default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="usersession",
            name="id",
            field=models.UUIDField(db_column="id", default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name="socketclient",
            name="sid",
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name="usersession",
            name="sid",
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterUniqueTogether(
            name="socketclient",
            unique_together={("das_tenant", "sid")},
        ),
        migrations.AlterUniqueTogether(
            name="usersession",
            unique_together={("das_tenant", "sid")},
        ),
    ]
