# Generated by Django 3.2.21 on 2023-10-10 02:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("observations", "0150_sid_type_change"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="socketclient",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="usersession",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="socketclient",
            constraint=models.UniqueConstraint(
                fields=("das_tenant", "sid"), name="observations_socketclient_tenant_sid_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="usersession",
            constraint=models.UniqueConstraint(
                fields=("das_tenant", "sid"), name="observations_usersession_tenant_sid_unique"
            ),
        ),
    ]
