# Generated by Django 3.2.21 on 2023-11-07 22:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("observations", "0152_make_das_tenant_field_required"),
    ]

    operations = [
        migrations.AlterField(
            model_name="region",
            name="slug",
            field=models.SlugField(max_length=100, verbose_name="unique id"),
        ),
        migrations.AlterField(
            model_name="sourceprovider",
            name="provider_key",
            field=models.CharField(max_length=100, null="False", verbose_name="Natural key for source provider"),
        ),
        migrations.AlterField(
            model_name="subjectgroup",
            name="name",
            field=models.CharField(max_length=80, verbose_name="name"),
        ),
        migrations.AddIndex(
            model_name="region",
            index=models.Index(fields=["das_tenant", "slug"], name="observations_region_slug_idx"),
        ),
        migrations.AddIndex(
            model_name="sourceprovider",
            index=models.Index(fields=["das_tenant", "provider_key"], name="observation_das_ten_f741ab_idx"),
        ),
        migrations.AddIndex(
            model_name="subjectgroup",
            index=models.Index(fields=["das_tenant", "name"], name="observation_das_ten_7f8f4c_idx"),
        ),
        migrations.AddConstraint(
            model_name="region",
            constraint=models.UniqueConstraint(
                fields=("das_tenant", "slug"), name="observations_region_unique_slug_across_tenants"
            ),
        ),
        migrations.AddConstraint(
            model_name="sourceprovider",
            constraint=models.UniqueConstraint(
                fields=("das_tenant", "provider_key"),
                name="observations_sourceprovider_unique_provider_key_across_tenants",
            ),
        ),
        migrations.AddConstraint(
            model_name="subjectgroup",
            constraint=models.UniqueConstraint(
                fields=("das_tenant", "name"), name="observations_subjectgroup_unique_name_across_tenants"
            ),
        ),
    ]
