# Generated by Django 3.2.21 on 2023-11-14 19:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("observations", "0153_observations_models_fields_unique_per_tenant"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sourcegroup",
            name="name",
            field=models.CharField(max_length=80, verbose_name="name"),
        ),
        migrations.AddIndex(
            model_name="sourcegroup",
            index=models.Index(fields=["das_tenant", "name"], name="observation_das_ten_1c4d13_idx"),
        ),
        migrations.AddConstraint(
            model_name="sourcegroup",
            constraint=models.UniqueConstraint(
                fields=("das_tenant", "name"), name="observations_sourcegroup_unique_name_across_tenants"
            ),
        ),
    ]
