# Generated by Django 3.2.21 on 2023-11-16 00:36

from django.db import migrations

from utils.migrations.update_primary_key import add_tenant_to_primary_key

models = [
    "SubjectType",
    "SubjectSubType",
    "CommonName",
]


def regenerate_primary_keys(apps, schema_editor):
    add_tenant_to_primary_key("observations", models)


class Migration(migrations.Migration):
    dependencies = [
        ("observations", "0154_made_sourcegroup_unique_across_tenants"),
    ]

    operations = [
        migrations.RunPython(
            code=regenerate_primary_keys,
            reverse_code=migrations.RunPython.noop,
        )
    ]
