# Generated by Django 3.2.21 on 2023-11-16 15:46

import django_multitenant.fields

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("observations", "0155_regenerate_pk_for_subjecttype_subjectsubtype"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subject",
            name="linked_user",
            field=django_multitenant.fields.TenantOneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="linked_subject",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="subjectsubtype",
            index=models.Index(fields=["das_tenant", "value"], name="observation_das_ten_c8d2ca_idx"),
        ),
        migrations.AddIndex(
            model_name="subjecttype",
            index=models.Index(fields=["das_tenant", "value"], name="observation_das_ten_99a840_idx"),
        ),
        migrations.AddConstraint(
            model_name="subjectsubtype",
            constraint=models.UniqueConstraint(
                fields=("das_tenant", "value"), name="observations_subjectsubtype_unique_value_across_tenants"
            ),
        ),
        migrations.AddConstraint(
            model_name="subjecttype",
            constraint=models.UniqueConstraint(
                fields=("das_tenant", "value"), name="observations_subjecttype_unique_value_across_tenants"
            ),
        ),
    ]
