# Generated by Django 3.2.21 on 2023-11-19 23:55

from django.db import migrations

import observations.models
import utils.models


class Migration(migrations.Migration):
    dependencies = [
        ("observations", "0156_update_field_to_tenantonetoonefield"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="announcement",
            managers=[
                ("objects", observations.models.AnnouncementManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="commonname",
            managers=[
                ("objects", observations.models.CommonNameManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="gpxtrackfile",
            managers=[
                ("objects", observations.models.GPXManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="latestobservationsource",
            managers=[
                ("objects", utils.models.CommonTenantManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="message",
            managers=[
                ("objects", observations.models.MessagesManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="observation",
            managers=[
                ("objects", observations.models.ObservationManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="region",
            managers=[
                ("objects", utils.models.CommonTenantManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="socketclient",
            managers=[
                ("objects", observations.models.SocketClientManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="source",
            managers=[
                ("objects", observations.models.SourceManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="sourcegroup",
            managers=[
                ("objects", observations.models.SourceGroupManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="sourceprovider",
            managers=[
                ("objects", observations.models.SourceProviderManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="subject",
            managers=[
                ("objects", observations.models.SubjectManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="subjectgroup",
            managers=[
                ("objects", observations.models.SubjectGroupManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="subjectsource",
            managers=[
                ("objects", observations.models.SubjectSourceManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="subjectstatus",
            managers=[
                ("objects", observations.models.SubjectStatusManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="subjectsubtype",
            managers=[
                ("objects", observations.models.SubjectSubTypeManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="subjecttracksegmentfilter",
            managers=[
                ("objects", utils.models.CommonTenantManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="subjecttype",
            managers=[
                ("objects", observations.models.SubjectTypeManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="usersession",
            managers=[
                ("objects", observations.models.UserSessionManager()),
            ],
        ),
    ]
