# Generated by Django 3.2.21 on 2023-11-20 00:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("observations", "0157_auto_20231119_1555"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subjectsubtype",
            options={"base_manager_name": "objects"},
        ),
        migrations.AlterModelOptions(
            name="subjecttype",
            options={"base_manager_name": "objects"},
        ),
    ]
