# Generated by Django 3.2.21 on 2023-11-23 22:33

from django.db import migrations

from utils.migrations.update_primary_key import drop_constraint

APP_NAME = "observations"


def drop_constraints(apps, schema_editor):
    drop_constraint(
        app=APP_NAME,
        model="SubjectStatus",
        constraint="observations_subjectstatus_id_fbbae65f_uniq",
    )


class Migration(migrations.Migration):
    dependencies = [
        ("observations", "0158_auto_20231119_1706"),
    ]

    operations = [
        migrations.RunPython(code=drop_constraints, reverse_code=migrations.RunPython.noop),
    ]
