# Generated by Django 3.2.21 on 2023-11-23 23:39

import uuid
from functools import partial

from django_multitenant.fields import TenantForeignKey

import django.db.models.deletion
from django.db import migrations, models

import utils.migrations.columns
from utils.migrations import populate_model_uuid_column
from utils.migrations.update_primary_key import add_tenant_to_primary_key

APP_NAME = "observations"
MAPPING_MODELS = ["SubjectGroupChildren"]

populate_uuid = partial(populate_model_uuid_column, "observations", "SubjectGroupChildren", "uuid")


def regenerate_primary_keys(apps, schema_editor):
    add_tenant_to_primary_key(APP_NAME, MAPPING_MODELS)


class Migration(migrations.Migration):
    dependencies = [
        ("observations", "0160_auto_20231124_1337"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="ALTER TABLE observations_subjectgroup_children RENAME TO observations_subjectgroupchildren",
                    reverse_sql="ALTER TABLE observations_subjectgroupchildren RENAME TO observations_subjectgroup_children",
                ),
            ],
            state_operations=[
                migrations.CreateModel(
                    name="SubjectGroupChildren",
                    fields=[
                        ("id", models.AutoField(serialize=False)),
                        (
                            "from_subjectgroup",
                            TenantForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                to="observations.SubjectGroup",
                            ),
                        ),
                        (
                            "to_subjectgroup",
                            TenantForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                to="observations.SubjectGroup",
                            ),
                        ),
                    ],
                ),
                migrations.AlterField(
                    model_name="SubjectGroup",
                    name="children",
                    field=models.ManyToManyField(
                        to="self",
                        related_name="_parents",
                        through="observations.SubjectGroupChildren",
                        through_fields=("from_subjectgroup", "to_subjectgroup"),
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="SubjectGroupChildren",
            name="uuid",
            field=models.UUIDField(null=True),
        ),
        migrations.RunPython(populate_uuid),
        migrations.RemoveField(
            model_name="SubjectGroupChildren",
            name="id",
        ),
        migrations.RenameField(
            model_name="SubjectGroupChildren",
            old_name="uuid",
            new_name="id",
        ),
        migrations.AlterField(
            model_name="SubjectGroupChildren",
            name="id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=True),
        ),
        migrations.AlterModelManagers(
            name="SubjectGroupChildren",
            managers=[
                ("objects", utils.models.CommonTenantManager()),
            ],
        ),
        migrations.AddField(
            model_name="SubjectGroupChildren",
            name="das_tenant",
            field=models.ForeignKey(
                default=utils.migrations.columns.default_tenant_id,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.dastenant",
            ),
        ),
        migrations.RunPython(code=regenerate_primary_keys, reverse_code=migrations.RunPython.noop),
    ]
