# Generated by Django 3.2.21 on 2023-11-30 19:50

import django_multitenant.fields

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0015_delete_unique_constraints"),
        ("observations", "0161_custom_through_model_subjectgroupchildren"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subjectgroup",
            name="children",
            field=models.ManyToManyField(
                blank=True,
                related_name="_parents",
                through="observations.subjectgroupchildren",
                to="observations.SubjectGroup",
            ),
        ),
        migrations.AlterField(
            model_name="subjectgroupchildren",
            name="from_subjectgroup",
            field=django_multitenant.fields.TenantForeignKey(
                db_column="from_subjectgroup_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="self",
                to="observations.subjectgroup",
            ),
        ),
        migrations.AlterField(
            model_name="subjectgroupchildren",
            name="to_subjectgroup",
            field=django_multitenant.fields.TenantForeignKey(
                db_column="to_subjectgroup_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children_to",
                to="observations.subjectgroup",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="subjectgroupchildren",
            unique_together={("das_tenant", "from_subjectgroup", "to_subjectgroup")},
        ),
        migrations.AlterModelTable(
            name="subjectgroupchildren",
            table="observations_subjectgroupchildren",
        ),
    ]
