# Generated by Django 3.2.21 on 2023-11-30 20:08

import uuid
from functools import partial

from django_multitenant.fields import TenantForeignKey

import django.db.models.deletion
from django.db import migrations, models

import utils.migrations.columns
from utils.migrations import populate_model_uuid_column
from utils.migrations.update_primary_key import add_tenant_to_primary_key

APP_NAME = "observations"
OBSERVATIONS_MODELS = ["SourceGroupChildren"]

populate_uuid = partial(populate_model_uuid_column, "observations", "SourceGroupChildren", "uuid")


def regenerate_primary_keys(apps, schema_editor):
    add_tenant_to_primary_key(APP_NAME, OBSERVATIONS_MODELS)


class Migration(migrations.Migration):
    dependencies = [
        ("observations", "0162_auto_20231130_1150"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="ALTER TABLE observations_sourcegroup_children RENAME TO observations_sourcegroupchildren",
                    reverse_sql="ALTER TABLE observations_sourcegroupchildren RENAME TO observations_sourcegroup_children",
                ),
            ],
            state_operations=[
                migrations.CreateModel(
                    name="SourceGroupChildren",
                    fields=[
                        ("id", models.AutoField(serialize=False)),
                        (
                            "from_sourcegroup",
                            TenantForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                to="observations.SourceGroup",
                            ),
                        ),
                        (
                            "to_sourcegroup",
                            TenantForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                to="observations.SourceGroup",
                            ),
                        ),
                    ],
                ),
                migrations.AlterField(
                    model_name="SourceGroup",
                    name="children",
                    field=models.ManyToManyField(
                        to="self",
                        related_name="_parents",
                        through="observations.SourceGroupChildren",
                        through_fields=("from_sourcegroup", "to_sourcegroup"),
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="SourceGroupChildren",
            name="uuid",
            field=models.UUIDField(null=True),
        ),
        migrations.RunPython(
            code=populate_uuid,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name="SourceGroupChildren",
            name="id",
        ),
        migrations.RenameField(
            model_name="SourceGroupChildren",
            old_name="uuid",
            new_name="id",
        ),
        migrations.AlterField(
            model_name="SourceGroupChildren",
            name="id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=True),
        ),
        migrations.AlterModelManagers(
            name="SourceGroupChildren",
            managers=[
                ("objects", utils.models.CommonTenantManager()),
            ],
        ),
        migrations.AddField(
            model_name="SourceGroupChildren",
            name="das_tenant",
            field=models.ForeignKey(
                default=utils.migrations.columns.default_tenant_id,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.dastenant",
            ),
        ),
        migrations.RunPython(code=regenerate_primary_keys, reverse_code=migrations.RunPython.noop),
    ]
