# Generated by Django 3.2.21 on 2023-12-07 19:25

import django_multitenant.fields

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0015_delete_unique_constraints"),
        ("observations", "0163_custom_through_model_sourcegroupchildren"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sourcegroup",
            name="children",
            field=models.ManyToManyField(
                blank=True,
                related_name="_parents",
                through="observations.sourcegroupchildren",
                to="observations.SourceGroup",
            ),
        ),
        migrations.AlterField(
            model_name="sourcegroupchildren",
            name="from_sourcegroup",
            field=django_multitenant.fields.TenantForeignKey(
                db_column="from_sourcegroup_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="self",
                to="observations.sourcegroup",
            ),
        ),
        migrations.AlterField(
            model_name="sourcegroupchildren",
            name="to_sourcegroup",
            field=django_multitenant.fields.TenantForeignKey(
                db_column="to_sourcegroup_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children_to",
                to="observations.sourcegroup",
            ),
        ),
        migrations.AlterField(
            model_name="subjectgroup",
            name="children",
            field=models.ManyToManyField(
                blank=True,
                related_name="_parents",
                through="observations.subjectgroupchildren",
                to="observations.SubjectGroup",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="sourcegroupchildren",
            unique_together={("das_tenant", "from_sourcegroup", "to_sourcegroup")},
        ),
        migrations.AlterModelTable(
            name="sourcegroupchildren",
            table="observations_sourcegroupchildren",
        ),
    ]
