# Generated by Django 3.2.21 on 2023-12-13 22:16

import django_multitenant.fields

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("observations", "0164_auto_20231207_1125"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sourcegroup",
            name="children",
            field=models.ManyToManyField(
                blank=True,
                related_name="_parents",
                through="observations.sourcegroupchildren",
                to="observations.SourceGroup",
            ),
        ),
        migrations.AlterField(
            model_name="subject",
            name="subject_subtype",
            field=django_multitenant.fields.TenantForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="observations.subjectsubtype"
            ),
        ),
        migrations.AlterField(
            model_name="subjectgroup",
            name="children",
            field=models.ManyToManyField(
                blank=True,
                related_name="_parents",
                through="observations.subjectgroupchildren",
                to="observations.SubjectGroup",
            ),
        ),
        migrations.AlterField(
            model_name="subjectsubtype",
            name="subject_type",
            field=django_multitenant.fields.TenantForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="observations.subjecttype"
            ),
        ),
    ]
