# Generated by Django 3.2.21 on 2023-12-13 22:16

import django_multitenant.fields

import django.db.models.deletion
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("observations", "0164_auto_20231207_1125"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subject",
            name="subject_subtype",
            field=django_multitenant.fields.TenantForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="observations.subjectsubtype"
            ),
        ),
        migrations.AlterField(
            model_name="subjectsubtype",
            name="subject_type",
            field=django_multitenant.fields.TenantForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="observations.subjecttype"
            ),
        ),
    ]
