# Generated by Django 3.2.21 on 2024-01-25 15:19
from django.db import migrations

from observations.migration_utils import TenantSubjectSubTypeLoader

wildlife_subtype_loader = (
    TenantSubjectSubTypeLoader(subject_type_value="wildlife")
    .add_subject_subtype(display="Meerkat", value="meerkat")
    .add_subject_subtype(display="Topi", value="topi")
)

person_subtype_loader = TenantSubjectSubTypeLoader(subject_type_value="person").add_subject_subtype(
    display="ER Mobile", value="er_mobile"
)


class Migration(migrations.Migration):
    dependencies = [("observations", "0165_auto_20231213_1416")]
    operations = [
        migrations.RunPython(wildlife_subtype_loader.load, reverse_code=migrations.RunPython.noop),
        migrations.RunPython(person_subtype_loader.load, reverse_code=migrations.RunPython.noop),
    ]
