# Generated by Django 3.2.21 on 2024-02-21 17:38

from django.db import migrations

sql = """
ALTER TABLE observations_subjectgroupchildren
    DROP CONSTRAINT observations_subjectgrou_from_subjectgroup_id_to__84bde0cb_uniq;
"""

reverse_sql = """
ALTER TABLE observations_subjectgroupchildren
    ADD CONSTRAINT observations_subjectgrou_from_subjectgroup_id_to__84bde0cb_uniq
        UNIQUE (from_subjectgroup_id, to_subjectgroup_id);
"""


class Migration(migrations.Migration):
    dependencies = [
        ("observations", "0166_add_topi_and_meerkat_wildlife_icons"),
    ]

    operations = [
        migrations.RunSQL(
            sql=sql,
            reverse_sql=reverse_sql,
        )
    ]
