# Generated by Django 3.2.21 on 2024-02-27 01:25

from django.db import migrations

from observations.migration_utils import TenantSubjectSubTypeLoader

wildlife_subtype_loader = (
    TenantSubjectSubTypeLoader(subject_type_value="wildlife")
    .add_subject_subtype(display="Moose", value="moose")
    .add_subject_subtype(display="Pronghorn", value="pronghorn")
    .add_subject_subtype(display="Rocky Mountain Bighorn Sheep", value="bighorn_sheep_rocky_mountain")
    .add_subject_subtype(display="Desert Bighorn Sheep", value="bighorn_sheep_desert")
)


class Migration(migrations.Migration):
    dependencies = [
        ("observations", "0167_drop_constraint_in_observations_subjectgroupchildren"),
    ]

    operations = [
        migrations.RunPython(wildlife_subtype_loader.load, reverse_code=migrations.RunPython.noop),
    ]
