# Generated by Django 3.2.21 on 2024-03-05 05:10

# Generated by Django 3.2.21 on 2024-03-05 01:48

import uuid
from functools import partial

from django_multitenant.fields import TenantForeignKey

import django.db.models.deletion
from django.db import migrations, models

import utils.migrations.columns
from observations.models import SourceGroupSourceManager
from utils.migrations import populate_model_uuid_column
from utils.migrations.update_primary_key import add_tenant_to_primary_key

APP_NAME = "observations"
OBSERVATIONS_MODELS = ["SourceGroupSource"]

populate_uuid = partial(populate_model_uuid_column, "observations", "SourceGroupSource", "uuid")


def regenerate_primary_keys(apps, schema_editor):
    add_tenant_to_primary_key(APP_NAME, OBSERVATIONS_MODELS)


class Migration(migrations.Migration):
    dependencies = [
        ("observations", "0169_subjectgroupsubject"),
    ]
    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="ALTER TABLE observations_sourcegroup_sources RENAME TO observations_sourcegroupsource",
                    reverse_sql="ALTER TABLE observations_sourcegroupsource RENAME TO observations_sourcegroup_sources",
                ),
            ],
            state_operations=[
                migrations.CreateModel(
                    name="SourceGroupSource",
                    fields=[
                        ("id", models.AutoField(serialize=False)),
                        (
                            "sourcegroup",
                            TenantForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                to="observations.SourceGroup",
                            ),
                        ),
                        (
                            "source",
                            TenantForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                to="observations.Source",
                            ),
                        ),
                    ],
                ),
                migrations.AlterField(
                    model_name="sourcegroup",
                    name="sources",
                    field=models.ManyToManyField(
                        to="observations.Source",
                        related_name="groups",
                        blank=True,
                        through="observations.SourceGroupSource",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="sourcegroupsource",
            name="uuid",
            field=models.UUIDField(null=True),
        ),
        migrations.RunPython(
            code=populate_uuid,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name="sourcegroupsource",
            name="id",
        ),
        migrations.RenameField(
            model_name="sourcegroupsource",
            old_name="uuid",
            new_name="id",
        ),
        migrations.AlterField(
            model_name="sourcegroupsource",
            name="id",
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, editable=False, serialize=True),
        ),
        migrations.AlterModelManagers(
            name="sourcegroupsource",
            managers=[
                ("objects", SourceGroupSourceManager()),
            ],
        ),
        migrations.AlterModelOptions(
            name="sourcegroupsource",
            options={"base_manager_name": "objects", "default_manager_name": "objects"},
        ),
        migrations.AddField(
            model_name="sourcegroupsource",
            name="das_tenant",
            field=models.ForeignKey(
                default=utils.migrations.columns.default_tenant_id,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="observations_sourcegroupsource",
                to="core.dastenant",
            ),
        ),
        migrations.RunPython(
            code=regenerate_primary_keys,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
