# Generated by Django 3.2.21 on 2024-03-06 23:55
import uuid
from functools import partial

from django_multitenant.fields import TenantForeignKey

import django.db.models.deletion
from django.db import migrations, models

import utils.migrations.columns
from core.utils import backfill_through_model_with_tenant
from observations.models import SubjectGroupPermissionSetManager
from utils.migrations import populate_model_uuid_column
from utils.migrations.update_primary_key import add_tenant_to_primary_key

APP_NAME = "observations"
OBSERVATIONS_MODELS = ["SubjectGroupPermissionSet"]

CURRENT_TABLE_NAME = "observations_subjectgroup_permission_sets"
NEW_TABLE_NAME = "observations_subjectgrouppermissionset"


populate_uuid = partial(populate_model_uuid_column, "observations", "SubjectGroupPermissionSet", "uuid")
populate_through_model_tenant_id = partial(
    backfill_through_model_with_tenant, "observations_subjectgroup", "id", NEW_TABLE_NAME, "subjectgroup_id"
)


def regenerate_primary_keys(apps, schema_editor):
    add_tenant_to_primary_key(APP_NAME, OBSERVATIONS_MODELS)


class Migration(migrations.Migration):
    dependencies = [
        ("observations", "0170_sourcegroupsource"),
    ]
    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=f"ALTER TABLE {CURRENT_TABLE_NAME} RENAME TO {NEW_TABLE_NAME}",
                    reverse_sql=f"ALTER TABLE {NEW_TABLE_NAME} RENAME TO {CURRENT_TABLE_NAME}",
                ),
            ],
            state_operations=[
                migrations.CreateModel(
                    name="SubjectGroupPermissionSet",
                    fields=[
                        ("id", models.AutoField(serialize=False)),
                        (
                            "subjectgroup",
                            TenantForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                to="observations.SubjectGroup",
                            ),
                        ),
                        (
                            "permissionset",
                            TenantForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                to="accounts.PermissionSet",
                            ),
                        ),
                    ],
                ),
                migrations.AlterField(
                    model_name="subjectgroup",
                    name="permission_sets",
                    field=models.ManyToManyField(
                        blank=True,
                        help_text="The permission sets applied to this table. A user in a permission set is granted these permissions.",
                        through="observations.SubjectGroupPermissionSet",
                        to="accounts.PermissionSet",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="subjectgrouppermissionset",
            name="uuid",
            field=models.UUIDField(null=True),
        ),
        migrations.RunPython(
            code=populate_uuid,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name="subjectgrouppermissionset",
            name="id",
        ),
        migrations.RenameField(
            model_name="subjectgrouppermissionset",
            old_name="uuid",
            new_name="id",
        ),
        migrations.AlterField(
            model_name="subjectgrouppermissionset",
            name="id",
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, editable=False, serialize=True),
        ),
        migrations.AlterModelManagers(
            name="subjectgrouppermissionset",
            managers=[
                ("objects", SubjectGroupPermissionSetManager()),
            ],
        ),
        migrations.AlterModelOptions(
            name="subjectgrouppermissionset",
            options={"base_manager_name": "objects", "default_manager_name": "objects"},
        ),
        migrations.AddField(
            model_name="subjectgrouppermissionset",
            name="das_tenant",
            field=models.ForeignKey(
                default=utils.migrations.columns.default_tenant_id,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="observations_subjectgrouppermissionset",
                to="core.dastenant",
            ),
        ),
        migrations.RunPython(
            code=regenerate_primary_keys,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RunPython(
            code=populate_through_model_tenant_id,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name="subjectgrouppermissionset",
            constraint=models.UniqueConstraint(
                fields=("das_tenant", "subjectgroup", "permissionset"),
                name="observations_subjectgrouppermissionset_tenant_from_to_unique",
            ),
        ),
    ]
