# Generated by Django 3.2.21 on 2024-03-08 18:47

import uuid
from functools import partial

from django_multitenant.fields import TenantForeignKey

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import utils.migrations.columns
from core.utils import backfill_through_model_with_tenant
from observations.models import AnnouncementUserManager
from utils.migrations import populate_model_uuid_column
from utils.migrations.update_primary_key import add_tenant_to_primary_key

APP_NAME = "observations"
OBSERVATIONS_MODELS = ["AnnouncementUser"]

CURRENT_TABLE_NAME = "observations_announcement_related_users"
NEW_TABLE_NAME = "observations_announcementuser"


populate_uuid = partial(populate_model_uuid_column, "observations", "AnnouncementUser", "uuid")
populate_through_model_tenant_id = partial(
    backfill_through_model_with_tenant, "observations_announcement", "id", NEW_TABLE_NAME, "announcement_id"
)


def regenerate_primary_keys(apps, schema_editor):
    add_tenant_to_primary_key(APP_NAME, OBSERVATIONS_MODELS)


class Migration(migrations.Migration):
    dependencies = [
        ("observations", "0172_sourcegrouppermissionset"),
    ]
    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=f"ALTER TABLE {CURRENT_TABLE_NAME} RENAME TO {NEW_TABLE_NAME}",
                    reverse_sql=f"ALTER TABLE {NEW_TABLE_NAME} RENAME TO {CURRENT_TABLE_NAME}",
                ),
            ],
            state_operations=[
                migrations.CreateModel(
                    name="AnnouncementUser",
                    fields=[
                        ("id", models.AutoField(serialize=False)),
                        (
                            "announcement",
                            TenantForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                to="observations.Announcement",
                            ),
                        ),
                        (
                            "user",
                            TenantForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                to=settings.AUTH_USER_MODEL,
                            ),
                        ),
                    ],
                ),
                migrations.AlterField(
                    model_name="announcement",
                    name="related_users",
                    field=models.ManyToManyField(
                        blank=True,
                        through="observations.AnnouncementUser",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="announcementuser",
            name="uuid",
            field=models.UUIDField(null=True),
        ),
        migrations.RunPython(
            code=populate_uuid,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name="announcementuser",
            name="id",
        ),
        migrations.RenameField(
            model_name="announcementuser",
            old_name="uuid",
            new_name="id",
        ),
        migrations.AlterField(
            model_name="announcementuser",
            name="id",
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, editable=False, serialize=True),
        ),
        migrations.AlterModelManagers(
            name="announcementuser",
            managers=[
                ("objects", AnnouncementUserManager()),
            ],
        ),
        migrations.AlterModelOptions(
            name="announcementuser",
            options={"base_manager_name": "objects", "default_manager_name": "objects"},
        ),
        migrations.AddField(
            model_name="announcementuser",
            name="das_tenant",
            field=models.ForeignKey(
                default=utils.migrations.columns.default_tenant_id,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="observations_announcementuser",
                to="core.dastenant",
            ),
        ),
        migrations.RunPython(
            code=regenerate_primary_keys,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RunPython(
            code=populate_through_model_tenant_id,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name="announcementuser",
            constraint=models.UniqueConstraint(
                fields=("das_tenant", "announcement", "user"),
                name="observations_announcementuser_tenant_from_to_unique",
            ),
        ),
    ]
