# Generated by Django 3.2.21 on 2024-03-21 18:43

from django.db import migrations

from observations.migration_utils import TenantSubjectSubTypeLoader

wildlife_subtype_loader = (
    TenantSubjectSubTypeLoader(subject_type_value="wildlife")
    .add_subject_subtype(display="Duiker", value="duiker")
    .add_subject_subtype(display="Frog", value="frog")
    .add_subject_subtype(display="Gorilla", value="gorilla")
    .add_subject_subtype(display="Hirola", value="hirola")
    .add_subject_subtype(display="Manta ray", value="mantaray")
    .add_subject_subtype(display="Sloth", value="sloth")
)


class Migration(migrations.Migration):
    dependencies = [
        ("observations", "0173_announcmentusertenant"),
    ]

    operations = [
        migrations.RunPython(wildlife_subtype_loader.load, reverse_code=migrations.RunPython.noop),
    ]
