# Generated by Django 3.2.21 on 2024-04-11 16:29

import os
from functools import partial

from django.db import migrations

from utils.migrations.update_primary_key import drop_constraint
from utils.permission_sets import create_permissionset_csv, set_permissions_set_hash

current_file = os.path.basename(__file__)
create_csv = partial(create_permissionset_csv, migration_filename=current_file)


def drop_constraints(apps, schema_editor):
    drop_constraint(
        app="observations",
        model="SubjectGroupPermissionSet",
        constraint="observations_subjectgrou_subjectgroup_id_permissi_e73024b3_uniq",
    )


class Migration(migrations.Migration):

    dependencies = [
        ("observations", "0174_duicker_icons"),
    ]

    operations = [
        migrations.RunPython(
            set_permissions_set_hash,
            migrations.RunPython.noop,
        ),
        migrations.RunPython(code=drop_constraints, reverse_code=migrations.RunPython.noop),
        migrations.RunPython(
            create_csv,
            migrations.RunPython.noop,
        ),
    ]
