# Generated by Django 3.2.21 on 2024-04-11 17:39
from django.db import migrations

from utils.migrations.update_primary_key import drop_constraint


def drop_constraints(apps, schema_editor):
    drop_constraint(
        app="observations",
        model="SourceGroupPermissionSet",
        constraint="observations_sourcegroup_sourcegroup_id_permissio_c8c0d134_uniq",
    )


class Migration(migrations.Migration):

    dependencies = [
        ("observations", "0175_remove_constraint_subjectgrouppermissionset"),
    ]

    operations = [
        migrations.RunPython(
            code=drop_constraints,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
