# Generated by Django 3.2.21 on 2024-04-11 19:11
from django.db import migrations, models

from utils.migrations.update_primary_key import drop_constraint


def drop_constraints(apps, schema_editor):
    drop_constraint(
        app="observations",
        model="Subject",
        constraint="observations_subject_linked_user_id_key",
    )


class Migration(migrations.Migration):

    dependencies = [
        ("observations", "0176_remove_constraint_sourcegroupgrouppermissionset"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="subject",
            constraint=models.UniqueConstraint(
                fields=("das_tenant", "linked_user"), name="observations_subject_unique_across_tenants"
            ),
        ),
        migrations.RunPython(code=drop_constraints, reverse_code=migrations.RunPython.noop),
    ]
