# Generated by Django 3.2.21 on 2024-05-01 23:54


from django.db import migrations

from observations.migration_utils import TenantSubjectSubTypeLoader

wildlife_subtype_loader = (
    TenantSubjectSubTypeLoader(subject_type_value="wildlife")
    .add_subject_subtype(display="Sheep", value="sheep")
    .add_subject_subtype(display="Mule", value="mule")
    .add_subject_subtype(display="Wild Boar", value="wild_boar")
    .add_subject_subtype(display="Hirola", value="hirola")
    .add_subject_subtype(display="Mule Deer", value="mule_deer")
    .add_subject_subtype(display="Jaguar", value="jaguar")
    .add_subject_subtype(display="Black Jaguar", value="jaguar_black")
    .add_subject_subtype(display="Macaw", value="macaw")
    .add_subject_subtype(display="Tortoise", value="tortoise")
    .add_subject_subtype(display="Drone Quad-copter", value="drone_quadcopter")
)


class Migration(migrations.Migration):
    dependencies = [
        ("observations", "0177_subject_observations_subject_unique_across_tenants"),
    ]

    operations = [
        migrations.RunPython(wildlife_subtype_loader.load, reverse_code=migrations.RunPython.noop),
    ]
