# Generated by Django 3.2.21 on 2024-08-15 18:48

from django.db import migrations

from observations.migration_utils import TenantSubjectSubTypeLoader

subject_subtype_loader = (
    TenantSubjectSubTypeLoader(subject_type_value="wildlife")
    .add_subject_subtype(display="Rabbit", value="rabbit")
    .add_subject_subtype(display="Hare", value="hare")
)


class Migration(migrations.Migration):

    dependencies = [
        ("observations", "0178_sheepicons"),
    ]

    operations = [
        migrations.RunPython(
            code=subject_subtype_loader.load,
            reverse_code=migrations.RunPython.noop,
        )
    ]
