# Generated by Django 3.2.21 on 2024-08-16 22:24

from django.db import migrations

from observations.migration_utils import TenantSubjectSubTypeLoader

stationary_subtype_loader = TenantSubjectSubTypeLoader(subject_type_value="stationary-object").add_subject_subtype(
    display="Nest", value="nest"
)


class Migration(migrations.Migration):

    dependencies = [
        ("observations", "0179_add_subject_icons_rabbit_and_hare"),
    ]

    operations = [
        migrations.RunPython(stationary_subtype_loader.load, reverse_code=migrations.RunPython.noop),
    ]
