# Generated by Django 3.2.21 on 2024-08-21 22:29

from django.db import migrations

from observations.migration_utils import TenantSubjectSubTypeLoader

subject_subtype_loader = (
    TenantSubjectSubTypeLoader(subject_type_value="wildlife")
    .add_subject_subtype(display="Bearded Vulture", value="bearded_vulture")
    .add_subject_subtype(display="Cinereous Vulture", value="cinereous_vulture")
)


class Migration(migrations.Migration):

    dependencies = [
        ("observations", "0180_nest_icons"),
    ]

    operations = [
        migrations.RunPython(
            code=subject_subtype_loader.load,
            reverse_code=migrations.RunPython.noop,
        )
    ]
