# Generated by Django 3.2.21 on 2024-10-16 18:10

from django.db import migrations

from observations.migration_utils import TenantSubjectSubTypeLoader

subject_subtype_wildlife_loader = (
    TenantSubjectSubTypeLoader(subject_type_value="wildlife")
    .add_subject_subtype(display="Monkey", value="monkey")
    .add_subject_subtype(display="Pangolin", value="pangolin")
)


class Migration(migrations.Migration):

    dependencies = [
        ("observations", "0182_add_baboon_icon"),
    ]

    operations = [
        migrations.RunPython(
            subject_subtype_wildlife_loader.load,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
