# Generated by Django 3.2.21 on 2024-10-30 19:07

from django.db import migrations

from observations.migration_utils import TenantSubjectSubTypeLoader

subject_subtype_loader = (
    TenantSubjectSubTypeLoader(subject_type_value="wildlife")
    .add_subject_subtype(display="Secretary Bird", value="secretary_bird")
    .add_subject_subtype(display="European Roller", value="european_roller")
)


class Migration(migrations.Migration):

    dependencies = [
        ("observations", "0183_add_monkey_pangolin_and_pin_icons"),
    ]

    operations = [
        migrations.RunPython(
            code=subject_subtype_loader.load,
            reverse_code=migrations.RunPython.noop,
        )
    ]
