# Generated by Django 3.2.21 on 2024-11-12 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("observations", "0184_add_subjectsubtype_icons_secretary_bird_and_european_roller"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="message",
            index=models.Index(fields=["das_tenant", "-message_time"], name="observation_das_ten_570e94_idx"),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(fields=["das_tenant", "read"], name="observation_das_ten_9d1d3b_idx"),
        ),
    ]
