# Generated by Django 3.2.19 on 2023-09-15 21:40

from django.db import migrations

from utils.migrations.update_primary_key import add_tenant_to_primary_key


def regenerate_primary_keys(apps, schema_editor):
    add_tenant_to_primary_key(app="observations", models=["LatestObservationSource"])


DROP_INDEX_SQL = """DROP INDEX IF EXISTS observations_latestobservationsource_observation_id_7f808c60;
                    DROP INDEX IF EXISTS observations_latestobservationsource_das_tenant_id_f7aeaf70;
"""

NEW_INSERT_LATEST_OBSERVATION_SOURCE = """
        CREATE OR REPLACE FUNCTION insert_latest_observation_source()
            RETURNS TRIGGER
            LANGUAGE plpgsql
        AS
        $$
        BEGIN
            if exists(SELECT * FROM observations_latestobservationsource WHERE source_id = new.source_id AND das_tenant_id = new.das_tenant_id) THEN
                IF new.recorded_at > (SELECT observations_latestobservationsource.recorded_at
                                      FROM observations_latestobservationsource
                                      WHERE source_id = new.source_id AND das_tenant_id = new.das_tenant_id) THEN
                    UPDATE observations_latestobservationsource
                    SET observation_id=new.id,
                        recorded_at=new.recorded_at
                    where source_id = new.source_id and das_tenant_id = new.das_tenant_id;
                END IF;
            ELSE
                INSERT INTO observations_latestobservationsource(source_id, observation_id, recorded_at, das_tenant_id)
                VALUES (new.source_id, new.id, new.recorded_at, new.das_tenant_id);
            END IF;
            RETURN New;
        END;
        $$;
        """

NEW_UPDATE_LATEST_OBSERVATION_SOURCE = """
              CREATE OR REPLACE FUNCTION update_latest_observation_source()
                  RETURNS TRIGGER
                  LANGUAGE plpgsql
              AS
              $$
              BEGIN
                  IF EXISTS(SELECT *
                            FROM observations_latestobservationsource
                            WHERE observations_latestobservationsource.source_id = new.source_id AND observations_latestobservationsource.das_tenant_id = new.das_tenant_id) THEN
                      IF new.recorded_at > (SELECT observations_latestobservationsource.recorded_at
                                            FROM observations_latestobservationsource
                                            WHERE observations_latestobservationsource.source_id = new.source_id AND observations_latestobservationsource.das_tenant_id = new.das_tenant_id) THEN
                          UPDATE observations_latestobservationsource
                          SET observation_id=NEW.id,
                              recorded_at=NEW.recorded_at,
                              source_id=NEW.source_id,
                              das_tenant_id=NEW.das_tenant_id
                          WHERE observations_latestobservationsource.source_id = NEW.source_id AND observations_latestobservationsource.das_tenant_id = NEW.das_tenant_id;
                      END IF;
                  ELSE
                      INSERT INTO observations_latestobservationsource(source_id, observation_id, recorded_at, das_tenant_id)
                      VALUES (new.source_id, new.id, new.recorded_at, new.das_tenant_id);
                  END IF;
                  RETURN New;
              END;
              $$;
              """

NEW_DELETE_LATEST_OBSERVATION_SOURCE = """
        CREATE OR REPLACE FUNCTION delete_latest_observation_source()
            RETURNS TRIGGER
            LANGUAGE plpgsql
        AS
        $$
        DECLARE
            tmp_source      UUID;
            tmp_observation UUID;
            tmp_recorded_at TIMESTAMP;
            tmp_das_tenant_id UUID;
        BEGIN
            IF not exists(SELECT *
                          FROM observations_latestobservationsource
                          WHERE observations_latestobservationsource.source_id = OLD.source_id AND observations_latestobservationsource.das_tenant_id = OLD.das_tenant_id) THEN
                IF exists(SELECT *
                          FROM observations_observation
                          WHERE source_id = OLD.source_id AND das_tenant_id = OLD.das_tenant_id
                          ORDER BY recorded_at DESC
                          LIMIT 1) THEN
                    SELECT source_id, id, recorded_at, das_tenant_id
                    INTO tmp_source, tmp_observation, tmp_recorded_at, tmp_das_tenant_id
                    FROM observations_observation
                    WHERE source_id = OLD.source_id AND das_tenant_id = OLD.das_tenant_id
                    ORDER BY recorded_at DESC
                    LIMIT 1;
                    INSERT INTO observations_latestobservationsource(source_id, observation_id, recorded_at, das_tenant_id)
                    VALUES (tmp_source, tmp_observation, tmp_recorded_at, tmp_das_tenant_id);
                END IF;
            END IF;
            RETURN NEW;
        END;
        $$;
        """


class Migration(migrations.Migration):
    dependencies = [
        ("observations", "0184_add_subjectsubtype_icons_secretary_bird_and_european_roller"),
    ]
    operations = [
        migrations.AlterModelOptions(
            name="latestobservationsource",
            options={"base_manager_name": "objects", "default_manager_name": "objects"},
        ),
        migrations.RemoveConstraint(
            model_name="latestobservationsource",
            name="observations_latestobservationsource_tenant_source_unique",
        ),
        migrations.RunPython(code=regenerate_primary_keys, reverse_code=migrations.RunPython.noop),
        migrations.RunSQL(
            sql=DROP_INDEX_SQL,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql="DROP TRIGGER IF EXISTS trigger_insert_latest_observation_source on observations_observation;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql="DROP TRIGGER IF EXISTS trigger_update_latest_observation_source on observations_observation;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql="DROP TRIGGER IF EXISTS trigger_delete_latest_observation_source on observations_observation;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        # Update functions
        migrations.RunSQL(
            sql=NEW_INSERT_LATEST_OBSERVATION_SOURCE,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql=NEW_UPDATE_LATEST_OBSERVATION_SOURCE,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql=NEW_DELETE_LATEST_OBSERVATION_SOURCE,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql="""
                CREATE TRIGGER trigger_insert_latest_observation_source
                    AFTER INSERT
                    ON observations_observation
                    FOR EACH ROW
                EXECUTE PROCEDURE insert_latest_observation_source();
                """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql="""
                CREATE TRIGGER trigger_update_latest_observation_source
                    AFTER UPDATE
                    ON observations_observation
                    FOR EACH ROW
                EXECUTE PROCEDURE update_latest_observation_source();
                """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql="""
                CREATE TRIGGER trigger_delete_latest_observation_source
                    AFTER DELETE
                    ON observations_observation
                    FOR EACH ROW
                EXECUTE PROCEDURE delete_latest_observation_source();
                """,
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
