# Generated by Django 3.2.21 on 2024-12-03 16:12

from django.db import migrations

from observations.migration_utils import TenantSubjectSubTypeLoader

subject_subtype_loader = TenantSubjectSubTypeLoader(subject_type_value="wildlife").add_subject_subtype(
    display="White Rhino",
    value="white_rhino",
)


class Migration(migrations.Migration):

    dependencies = [
        ("observations", "0186_add_message_indices"),
    ]

    operations = [
        migrations.RunPython(
            code=subject_subtype_loader.load,
            reverse_code=migrations.RunPython.noop,
        )
    ]
