# Generated by Django 3.2.21 on 2024-11-28 21:21


from django.db import migrations, models

drop_subjectsource_location_index_sql = "DROP INDEX IF EXISTS public.observations_subjectsource_location_id;"
drop_subjectsource_source_id_index_sql = "DROP INDEX IF EXISTS public.observations_subjectsource_source_id_8c96d9ab;"
drop_subjectsource_subject_id_index_sql = "DROP INDEX IF EXISTS public.observations_subjectsource_subject_id_61906dcb;"


class Migration(migrations.Migration):

    dependencies = [
        ("observations", "0187_add_white_rhino_icon"),
    ]

    operations = [
        migrations.RunSQL(
            sql=drop_subjectsource_location_index_sql,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql=drop_subjectsource_source_id_index_sql,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql=drop_subjectsource_subject_id_index_sql,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AddIndex(
            model_name="subjectsource",
            index=models.Index(fields=["das_tenant", "subject"], name="observation_das_ten_90495a_idx"),
        ),
        migrations.AddIndex(
            model_name="subjectsource",
            index=models.Index(fields=["das_tenant", "source"], name="observation_das_ten_5618ce_idx"),
        ),
        migrations.AddIndex(
            model_name="subjectsource",
            index=models.Index(fields=["das_tenant", "location"], name="observation_das_ten_7c0473_idx"),
        ),
    ]
