# Generated by Django 3.2.21 on 2024-12-14 22:13

import django_multitenant.fields

import django.db.models.deletion
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("observations", "0188_add_subjectsource_indexes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commonname",
            name="subject_subtype",
            field=django_multitenant.fields.TenantForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="observations.subjectsubtype"
            ),
        ),
    ]
