# Generated by Django 3.2.21 on 2025-01-31 21:39

from django.db import migrations

NEW_INSERT_LATEST_OBSERVATION_SOURCE = """
        CREATE OR REPLACE FUNCTION insert_latest_observation_source()
            RETURNS TRIGGER
            LANGUAGE plpgsql
        AS
        $$
        BEGIN

            INSERT INTO observations_latestobservationsource(source_id, observation_id, recorded_at, das_tenant_id)
            VALUES (NEW.source_id, NEW.id, NEW.recorded_at, NEW.das_tenant_id)
            ON CONFLICT ON CONSTRAINT observations_latestobservationsource_pkey
            DO UPDATE SET
                observation_id = EXCLUDED.observation_id,
                recorded_at = EXCLUDED.recorded_at
            WHERE observations_latestobservationsource.recorded_at < EXCLUDED.recorded_at; -- Only update if newer

            RETURN NEW;
        END;
        $$;
        """


class Migration(migrations.Migration):

    dependencies = [
        ("observations", "0189_alter_commonname_subject_subtype"),
    ]

    operations = [
        migrations.RunSQL(
            sql="DROP TRIGGER IF EXISTS trigger_insert_latest_observation_source on observations_observation;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql=NEW_INSERT_LATEST_OBSERVATION_SOURCE,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql="""
                CREATE TRIGGER trigger_insert_latest_observation_source
                    AFTER INSERT
                    ON observations_observation
                    FOR EACH ROW
                EXECUTE PROCEDURE insert_latest_observation_source();
                """,
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
