# Generated by Django 3.2.21 on 2025-02-06 20:29

from django.db import migrations

from observations.migration_utils import TenantSubjectSubTypeLoader

subject_subtype_loader = TenantSubjectSubTypeLoader(subject_type_value="wildlife").add_subject_subtype(
    display="Camel",
    value="camel",
)


class Migration(migrations.Migration):

    dependencies = [
        ("observations", "0190_lastestobservation_trigger"),
    ]

    operations = [
        migrations.RunPython(
            code=subject_subtype_loader.load,
            reverse_code=migrations.RunPython.noop,
        )
    ]
