# Generated by Django 3.2.25 on 2025-03-25 15:20
from django.db import migrations

from observations.migration_utils import TenantSubjectSubTypeLoader

subject_subtype_loader = (
    TenantSubjectSubTypeLoader(subject_type_value="wildlife")
    .add_subject_subtype(
        display="Whale Shark",
        value="whale-shark",
    )
    .add_subject_subtype(
        display="Bird of Prey",
        value="bird-of-prey",
    )
)


class Migration(migrations.Migration):

    dependencies = [
        ("observations", "0191_add_camel"),
    ]

    operations = [
        migrations.RunPython(
            code=subject_subtype_loader.load,
            reverse_code=migrations.RunPython.noop,
        )
    ]
