# Generated by Django 3.2.25 on 2025-05-04 23:41

from django.db import migrations

from observations.migration_utils import TenantSubjectSubTypeLoader

subject_subtype_loader = TenantSubjectSubTypeLoader(subject_type_value="wildlife").add_subject_subtype(
    display="Donkey",
    value="donkey",
)


class Migration(migrations.Migration):

    dependencies = [
        ("observations", "0192_whale_shark_icon"),
    ]

    operations = [
        migrations.RunPython(
            code=subject_subtype_loader.load,
            reverse_code=migrations.RunPython.noop,
        )
    ]
