# Generated by Django 3.2.25 on 2025-05-20 00:58


from django.db import migrations

import observations.models

NEW_INSERT_LATEST_OBSERVATION_SOURCE = """
        CREATE OR REPLACE FUNCTION insert_latest_observation_source()
            RETURNS TRIGGER
            LANGUAGE plpgsql
        AS
        $$
        BEGIN
            -- Only insert if exclusion_flags = 0
            IF NEW.exclusion_flags = 0 THEN
                INSERT INTO observations_latestobservationsource(source_id, observation_id, recorded_at, das_tenant_id)
                VALUES (NEW.source_id, NEW.id, NEW.recorded_at, NEW.das_tenant_id)
                ON CONFLICT ON CONSTRAINT observations_latestobservationsource_pkey
                DO UPDATE SET
                    observation_id = EXCLUDED.observation_id,
                    recorded_at = EXCLUDED.recorded_at
                WHERE observations_latestobservationsource.recorded_at < EXCLUDED.recorded_at; -- Only update if newer
            END IF;

            RETURN NEW;
        END;
        $$;
        """

NEW_UPDATE_LATEST_OBSERVATION_SOURCE = """
        CREATE OR REPLACE FUNCTION update_latest_observation_source()
            RETURNS TRIGGER
            LANGUAGE plpgsql
        AS
        $$
        DECLARE
            tmp_source      UUID;
            tmp_observation UUID;
            tmp_recorded_at TIMESTAMP;
            tmp_das_tenant_id UUID;
        BEGIN
            -- If the updated observation is now excluded and it's the current latest
            IF NEW.exclusion_flags != 0 AND EXISTS(
                SELECT 1
                FROM observations_latestobservationsource
                WHERE observations_latestobservationsource.source_id = NEW.source_id
                AND observations_latestobservationsource.das_tenant_id = NEW.das_tenant_id
                AND observations_latestobservationsource.observation_id = NEW.id
            ) THEN
                -- Find the next newest non-excluded observation
                SELECT source_id, id, recorded_at, das_tenant_id
                INTO tmp_source, tmp_observation, tmp_recorded_at, tmp_das_tenant_id
                FROM observations_observation
                WHERE source_id = NEW.source_id
                AND das_tenant_id = NEW.das_tenant_id
                AND exclusion_flags = 0
                AND id != NEW.id
                ORDER BY recorded_at DESC
                LIMIT 1;

                -- If we found a non-excluded observation, update the latest
                IF tmp_observation IS NOT NULL THEN
                    UPDATE observations_latestobservationsource
                    SET observation_id = tmp_observation,
                        recorded_at = tmp_recorded_at
                    WHERE source_id = NEW.source_id
                    AND das_tenant_id = NEW.das_tenant_id;
                ELSE
                    -- If no non-excluded observations found, delete the latest
                    DELETE FROM observations_latestobservationsource
                    WHERE source_id = NEW.source_id
                    AND das_tenant_id = NEW.das_tenant_id;
                END IF;
            -- Normal update case for non-excluded observations
            ELSIF NEW.exclusion_flags = 0 THEN
                IF EXISTS(SELECT 1
                        FROM observations_latestobservationsource
                        WHERE observations_latestobservationsource.source_id = NEW.source_id
                        AND observations_latestobservationsource.das_tenant_id = NEW.das_tenant_id) THEN
                    IF NEW.recorded_at > (SELECT observations_latestobservationsource.recorded_at
                                        FROM observations_latestobservationsource
                                        WHERE observations_latestobservationsource.source_id = NEW.source_id
                                        AND observations_latestobservationsource.das_tenant_id = NEW.das_tenant_id) THEN
                        UPDATE observations_latestobservationsource
                        SET observation_id = NEW.id,
                            recorded_at = NEW.recorded_at
                        WHERE source_id = NEW.source_id
                        AND das_tenant_id = NEW.das_tenant_id;
                    END IF;
                ELSE
                    INSERT INTO observations_latestobservationsource(source_id, observation_id, recorded_at, das_tenant_id)
                    VALUES (NEW.source_id, NEW.id, NEW.recorded_at, NEW.das_tenant_id);
                END IF;
            END IF;
            RETURN NEW;
        END;
        $$;
        """


NEW_DELETE_LATEST_OBSERVATION_SOURCE = """
        CREATE OR REPLACE FUNCTION delete_latest_observation_source()
            RETURNS TRIGGER
            LANGUAGE plpgsql
        AS
        $$
        DECLARE
            tmp_source      UUID;
            tmp_observation UUID;
            tmp_recorded_at TIMESTAMP;
            tmp_das_tenant_id UUID;
        BEGIN
            IF not exists(SELECT *
                          FROM observations_latestobservationsource
                          WHERE observations_latestobservationsource.source_id = OLD.source_id AND observations_latestobservationsource.das_tenant_id = OLD.das_tenant_id) THEN
                IF exists(SELECT *
                          FROM observations_observation
                          WHERE source_id = OLD.source_id AND das_tenant_id = OLD.das_tenant_id
                          ORDER BY recorded_at DESC
                          LIMIT 1) THEN
                    SELECT source_id, id, recorded_at, das_tenant_id
                    INTO tmp_source, tmp_observation, tmp_recorded_at, tmp_das_tenant_id
                    FROM observations_observation
                    WHERE source_id = OLD.source_id AND das_tenant_id = OLD.das_tenant_id
                    ORDER BY recorded_at DESC
                    LIMIT 1;
                    INSERT INTO observations_latestobservationsource(source_id, observation_id, recorded_at, das_tenant_id)
                    VALUES (tmp_source, tmp_observation, tmp_recorded_at, tmp_das_tenant_id);
                END IF;
            END IF;
            RETURN NEW;
        END;
        $$;
        """


class Migration(migrations.Migration):

    dependencies = [
        ("observations", "0193_donkey"),
    ]

    operations = [
        migrations.RunSQL(
            sql="DROP TRIGGER IF EXISTS trigger_insert_latest_observation_source on observations_observation;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql="DROP TRIGGER IF EXISTS trigger_update_latest_observation_source on observations_observation;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql="DROP TRIGGER IF EXISTS trigger_delete_latest_observation_source on observations_observation;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql=NEW_INSERT_LATEST_OBSERVATION_SOURCE,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql=NEW_UPDATE_LATEST_OBSERVATION_SOURCE,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql=NEW_DELETE_LATEST_OBSERVATION_SOURCE,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql="""
                CREATE TRIGGER trigger_insert_latest_observation_source
                    AFTER INSERT
                    ON observations_observation
                    FOR EACH ROW
                EXECUTE PROCEDURE insert_latest_observation_source();
                """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql="""
                CREATE TRIGGER trigger_update_latest_observation_source
                    AFTER UPDATE
                    ON observations_observation
                    FOR EACH ROW
                EXECUTE PROCEDURE update_latest_observation_source();
                """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql="""
                CREATE TRIGGER trigger_delete_latest_observation_source
                    AFTER DELETE
                    ON observations_observation
                    FOR EACH ROW
                EXECUTE PROCEDURE delete_latest_observation_source();
                """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AlterModelManagers(
            name="latestobservationsource",
            managers=[
                ("objects", observations.models.LatestObservationSourceManager()),
            ],
        ),
    ]
