# Generated by Django 3.2.25 on 2025-09-01 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("observations", "0194_los_exclusion_filter"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subject",
            options={
                "base_manager_name": "objects",
                "default_manager_name": "objects",
                "permissions": (
                    ("view_last_position", "Permission to view the last reported position of a Subject only."),
                    ("view_real_time", "Access to real-time observations."),
                    (
                        "view_delayed",
                        "Access to a 24 hour delayed observation feed. No real-time or last reported position.",
                    ),
                    ("subscribe_alerts", "Permission to subscribe to an alert on this Subject."),
                    (
                        "change_alerts",
                        "Permission to configure alerts for subject, includes setting geofences, proximity and immobility settings.",
                    ),
                    (
                        "change_view",
                        "An admin permission to change which users can view a Subject and their view permission.",
                    ),
                    ("access_begins_7", "Can view tracks no more than 7 days old"),
                    ("access_begins_16", "Can view tracks no more than 16 days old"),
                    ("access_begins_30", "Can view tracks no more than 30 days old"),
                    ("access_begins_60", "Can view tracks no more than 60 days old"),
                    ("access_begins_all", "Can view all historical tracks"),
                    ("access_ends_0", "Can view tracks no less than 0 days old"),
                    ("access_ends_1", "Can view tracks no less than 1 day old"),
                    ("access_ends_3", "Can view tracks no less than 3 days old"),
                    ("access_ends_7", "Can view tracks no less than 7 days old"),
                    (
                        "can_view_gear_regardless_location",
                        "Can view gear/subject regardless of location restriction (lat/lon not required).",
                    ),
                ),
            },
        ),
    ]
