# Generated by Django 3.2.25 on 2025-10-15 21:47

from django.db import migrations, models

from utils.migrations.update_primary_key import drop_constraint

APP_NAME = "observations"


def drop_constraints(apps, schema_editor):
    for constraint in (
        "observations_subjectgroupsubject_id_1b6329fa_uniq",
        "observations_subjectgrou_subjectgroup_id_subject__e3dd0951_uniq",
    ):
        drop_constraint(
            app=APP_NAME,
            model="SubjectGroupSubject",
            constraint=constraint,
        )


class Migration(migrations.Migration):

    dependencies = [
        ("observations", "0195_alter_subject_options"),
    ]

    operations = [
        migrations.RunPython(code=drop_constraints, reverse_code=migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="subjectgroupsubject",
            constraint=models.UniqueConstraint(
                fields=("das_tenant", "subjectgroup", "subject"), name="observations_subjectgroupsubject_tenant_unique"
            ),
        ),
    ]
