# Generated by Django 3.2.25 on 2025-10-27 16:16

from django.db import migrations

from observations.migration_utils import TenantSubjectSubTypeLoader

wildlife_subtype_loader = TenantSubjectSubTypeLoader(subject_type_value="wildlife").add_subject_subtype(
    display="Badger", value="badger"
)


class Migration(migrations.Migration):

    dependencies = [
        ("observations", "0196_subjectgroupsubject"),
    ]

    operations = [
        migrations.RunPython(wildlife_subtype_loader.load, reverse_code=migrations.RunPython.noop),
    ]
