# Generated by Django 3.2.25 on 2025-10-27 20:56

from django.db import migrations

from observations.migration_utils import TenantSubjectSubTypeLoader

wildlife_subtype_loader = (
    TenantSubjectSubTypeLoader(subject_type_value="wildlife")
    .add_subject_subtype(display="Opossum", value="opossum")
    .add_subject_subtype(display="Tree Kangaroo", value="tree-kangaroo")
    .add_subject_subtype(display="Lyrebird", value="lyrebird")
)


class Migration(migrations.Migration):

    dependencies = [
        ("observations", "0197_badger"),
    ]

    operations = [
        migrations.RunPython(wildlife_subtype_loader.load, reverse_code=migrations.RunPython.noop),
    ]
