# Generated by Django 3.2.25 on 2026-01-09 00:25

from django.db import migrations

from observations.migration_utils import TenantSubjectSubTypeLoader

subject_subtype_loader = TenantSubjectSubTypeLoader(subject_type_value="wildlife").add_subject_subtype(
    display="Vicuna",
    value="vicuna",
)


class Migration(migrations.Migration):

    dependencies = [
        ("observations", "0198_opossum"),
    ]

    operations = [
        migrations.RunPython(
            code=subject_subtype_loader.load,
            reverse_code=migrations.RunPython.noop,
        )
    ]
