# Generated by Django 3.2.25 on 2025-11-27 00:11

import uuid

import django.contrib.gis.db.models as gis_models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("observations", "0199_vicuna"),
    ]

    operations = [
        # Create table with all constraints and indexes using raw SQL
        migrations.RunSQL(
            sql="""
                -- Create table without FK constraints first
                CREATE TABLE "observations_observationsegment" (
                    "id" uuid NOT NULL PRIMARY KEY,
                    "geometry" geometry(LINESTRING,4326) NOT NULL,
                    "speed_kmh" double precision NOT NULL,
                    "time_gap_ms" double precision NOT NULL,
                    "distance_meters" double precision NOT NULL,
                    "start_recorded_at" timestamp with time zone NOT NULL,
                    "end_recorded_at" timestamp with time zone NOT NULL,
                    "exclusion_flags" bigint NOT NULL,
                    "created_at" timestamp with time zone NOT NULL,
                    "updated_at" timestamp with time zone NOT NULL,
                    "das_tenant_id" uuid NOT NULL,
                    "end_observation_id" uuid NOT NULL,
                    "start_observation_id" uuid NOT NULL,
                    "subject_id" uuid NOT NULL
                );

                -- Add FK to core_dastenant
                ALTER TABLE "observations_observationsegment"
                ADD CONSTRAINT "observations_observa_das_tenant_id_fk"
                FOREIGN KEY ("das_tenant_id")
                REFERENCES "core_dastenant" ("id")
                DEFERRABLE INITIALLY DEFERRED;

                -- Add composite FK to observations_observation (partitioned table) for start_observation
                ALTER TABLE "observations_observationsegment"
                ADD CONSTRAINT "observations_observa_start_obs_fk"
                FOREIGN KEY ("das_tenant_id", "start_observation_id")
                REFERENCES "observations_observation" ("das_tenant_id", "id")
                DEFERRABLE INITIALLY DEFERRED;

                -- Add composite FK to observations_observation (partitioned table) for end_observation
                ALTER TABLE "observations_observationsegment"
                ADD CONSTRAINT "observations_observa_end_obs_fk"
                FOREIGN KEY ("das_tenant_id", "end_observation_id")
                REFERENCES "observations_observation" ("das_tenant_id", "id")
                DEFERRABLE INITIALLY DEFERRED;

                -- Add composite FK to observations_subject for subject
                ALTER TABLE "observations_observationsegment"
                ADD CONSTRAINT "observations_observa_subject_fk"
                FOREIGN KEY ("das_tenant_id", "subject_id")
                REFERENCES "observations_subject" ("das_tenant_id", "id")
                DEFERRABLE INITIALLY DEFERRED;

                -- Add indexes
                CREATE INDEX "observation_das_ten_844e39_idx"
                ON "observations_observationsegment" ("das_tenant_id", "subject_id", "start_recorded_at");

                CREATE INDEX "observation_das_ten_ff294d_idx"
                ON "observations_observationsegment" ("das_tenant_id", "subject_id", "end_recorded_at");

                CREATE INDEX "observation_start_o_68bbbe_idx"
                ON "observations_observationsegment" ("start_observation_id", "end_observation_id");

                CREATE INDEX "observation_das_ten_aee6b0_idx"
                ON "observations_observationsegment" ("das_tenant_id", "subject_id", "exclusion_flags");

                CREATE INDEX "observations_observationsegment_geometry_idx"
                ON "observations_observationsegment"
                USING GIST ("geometry");
                -- Add unique constraint
                ALTER TABLE "observations_observationsegment"
                ADD CONSTRAINT "observations_observationsegment_unique_segment"
                UNIQUE ("start_observation_id", "end_observation_id");
            """,
            reverse_sql="DROP TABLE IF EXISTS observations_observationsegment CASCADE;",
            # This tells Django to update its internal state to track the model
            state_operations=[
                migrations.CreateModel(
                    name="ObservationSegment",
                    fields=[
                        ("id", models.UUIDField(primary_key=True, serialize=False, default=uuid.uuid4)),
                        ("geometry", gis_models.LineStringField(srid=4326)),
                        ("speed_kmh", models.FloatField()),
                        ("time_gap_ms", models.FloatField()),
                        ("distance_meters", models.FloatField()),
                        ("start_recorded_at", models.DateTimeField(db_index=True)),
                        ("end_recorded_at", models.DateTimeField(db_index=True)),
                        ("exclusion_flags", models.BigIntegerField()),
                        ("created_at", models.DateTimeField(auto_now_add=True)),
                        ("updated_at", models.DateTimeField(auto_now=True)),
                        ("das_tenant_id", models.UUIDField()),
                        ("start_observation_id", models.UUIDField()),
                        ("end_observation_id", models.UUIDField()),
                        ("subject_id", models.UUIDField()),
                    ],
                ),
            ],
        ),
    ]
