# Generated by Django 3.2.25 on 2025-11-27 00:11
# Replaced to create observations_observationsegment as partitioned by start_recorded_at
# with pg_partman config (3-year retention). See docs/development/observation-segment-partitioning-plan.md

import uuid

import django.contrib.gis.db.models as gis_models
from django.db import migrations, models

FORWARD_SQL = """
-- 1. Create parent table partitioned by start_recorded_at (monthly).
-- PK (das_tenant_id, id, start_recorded_at) for constraint exclusion and consistency with Observation.
CREATE TABLE IF NOT EXISTS "observations_observationsegment" (
    "id" uuid NOT NULL,
    "geometry" geometry(LINESTRING,4326) NOT NULL,
    "speed_kmh" double precision NOT NULL,
    "time_gap_ms" double precision NOT NULL,
    "distance_meters" double precision NOT NULL,
    "start_recorded_at" timestamp with time zone NOT NULL,
    "end_recorded_at" timestamp with time zone NOT NULL,
    "exclusion_flags" bigint NOT NULL,
    "created_at" timestamp with time zone NOT NULL,
    "updated_at" timestamp with time zone NOT NULL,
    "das_tenant_id" uuid NOT NULL,
    "end_observation_id" uuid NOT NULL,
    "start_observation_id" uuid NOT NULL,
    "subject_id" uuid NOT NULL,
    PRIMARY KEY ("das_tenant_id", "id", "start_recorded_at")
) PARTITION BY RANGE ("start_recorded_at");

-- 2. Add FKs and constraints on parent (propagate to children)
ALTER TABLE "observations_observationsegment"
ADD CONSTRAINT "observations_observa_das_tenant_id_fk"
FOREIGN KEY ("das_tenant_id")
REFERENCES "core_dastenant" ("id")
DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "observations_observationsegment"
ADD CONSTRAINT "observations_observa_start_obs_fk"
FOREIGN KEY ("das_tenant_id", "start_observation_id")
REFERENCES "observations_observation" ("das_tenant_id", "id")
DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "observations_observationsegment"
ADD CONSTRAINT "observations_observa_end_obs_fk"
FOREIGN KEY ("das_tenant_id", "end_observation_id")
REFERENCES "observations_observation" ("das_tenant_id", "id")
DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "observations_observationsegment"
ADD CONSTRAINT "observations_observa_subject_fk"
FOREIGN KEY ("das_tenant_id", "subject_id")
REFERENCES "observations_subject" ("das_tenant_id", "id")
DEFERRABLE INITIALLY DEFERRED;

CREATE INDEX "observation_das_ten_844e39_idx"
ON "observations_observationsegment" ("das_tenant_id", "subject_id", "start_recorded_at");

CREATE INDEX "observation_das_ten_ff294d_idx"
ON "observations_observationsegment" ("das_tenant_id", "subject_id", "end_recorded_at");

CREATE INDEX "observation_das_ten_aee6b0_idx"
ON "observations_observationsegment" ("das_tenant_id", "subject_id", "exclusion_flags");

-- Unique constraint must include partition key (start_recorded_at) per PostgreSQL rules
ALTER TABLE "observations_observationsegment"
ADD CONSTRAINT "observations_observationsegment_unique_segment"
UNIQUE ("start_observation_id", "end_observation_id", "start_recorded_at");

-- 3. Register with pg_partman (creates default partition and template)
SELECT partman.create_parent(
    p_parent_table := 'public.observations_observationsegment',
    p_control := 'start_recorded_at',
    p_interval := '1 month',
    p_premake := 5,
    p_default_table := true,
    p_automatic_maintenance := 'on'
);

-- 4. Set retention and infinite_time_partitions for ObservationSegment
UPDATE partman.part_config
SET infinite_time_partitions = false,
    retention = '3 years'
WHERE parent_table = 'public.observations_observationsegment';
"""

REVERSE_SQL = """
DELETE FROM partman.part_config
WHERE parent_table = 'public.observations_observationsegment';

DROP TABLE IF EXISTS observations_observationsegment CASCADE;
"""


class Migration(migrations.Migration):

    dependencies = [
        ("observations", "0199_vicuna"),
    ]

    operations = [
        migrations.RunSQL(
            sql=FORWARD_SQL,
            reverse_sql=REVERSE_SQL,
            state_operations=[
                migrations.CreateModel(
                    name="ObservationSegment",
                    fields=[
                        ("id", models.UUIDField(primary_key=True, serialize=False, default=uuid.uuid4)),
                        ("geometry", gis_models.LineStringField(srid=4326)),
                        ("speed_kmh", models.FloatField()),
                        ("time_gap_ms", models.FloatField()),
                        ("distance_meters", models.FloatField()),
                        ("start_recorded_at", models.DateTimeField(db_index=True)),
                        ("end_recorded_at", models.DateTimeField(db_index=True)),
                        ("exclusion_flags", models.BigIntegerField()),
                        ("created_at", models.DateTimeField(auto_now_add=True)),
                        ("updated_at", models.DateTimeField(auto_now=True)),
                        ("das_tenant_id", models.UUIDField()),
                        ("start_observation_id", models.UUIDField()),
                        ("end_observation_id", models.UUIDField()),
                        ("subject_id", models.UUIDField()),
                    ],
                ),
            ],
        ),
    ]
