# Generated by Django 3.2.25 on 2026-02-23 00:00

from django.db import migrations

from observations.migration_utils import TenantSubjectSubTypeLoader

subject_subtype_loader = TenantSubjectSubTypeLoader(subject_type_value="wildlife").add_subject_subtype(
    display="Deer",
    value="deer",
)


class Migration(migrations.Migration):

    dependencies = [
        ("observations", "0199_vicuna"),
    ]

    operations = [
        migrations.RunPython(
            code=subject_subtype_loader.load,
            reverse_code=migrations.RunPython.noop,
        )
    ]
