# Generated by Django 3.2.25 on 2025-11-27 00:11
# Replaced to create observations_observationsegment as partitioned by start_recorded_at.
# When pg_partman is available: register with partman (3-year retention).
# When pg_partman is not (e.g. CI): create default partition only. See observation-segment-partitioning-plan.md

import logging
import uuid

import django.contrib.gis.db.models as gis_models
from django.db import migrations, models

logger = logging.getLogger(__name__)

# Parent table + constraints only (no default partition; partman or manual step creates it)
SQL_TABLE_AND_CONSTRAINTS = """
CREATE TABLE IF NOT EXISTS "observations_observationsegment" (
    "id" uuid NOT NULL,
    "geometry" geometry(LINESTRING,4326) NOT NULL,
    "speed_kmh" double precision NOT NULL,
    "time_gap_ms" double precision NOT NULL,
    "distance_meters" double precision NOT NULL,
    "start_recorded_at" timestamp with time zone NOT NULL,
    "end_recorded_at" timestamp with time zone NOT NULL,
    "exclusion_flags" bigint NOT NULL,
    "created_at" timestamp with time zone NOT NULL,
    "updated_at" timestamp with time zone NOT NULL,
    "das_tenant_id" uuid NOT NULL,
    "end_observation_id" uuid NOT NULL,
    "start_observation_id" uuid NOT NULL,
    "subject_id" uuid NOT NULL,
    PRIMARY KEY ("das_tenant_id", "id", "start_recorded_at")
) PARTITION BY RANGE ("start_recorded_at");

ALTER TABLE "observations_observationsegment"
ADD CONSTRAINT "observations_observa_das_tenant_id_fk"
FOREIGN KEY ("das_tenant_id")
REFERENCES "core_dastenant" ("id")
DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "observations_observationsegment"
ADD CONSTRAINT "observations_observa_start_obs_fk"
FOREIGN KEY ("das_tenant_id", "start_observation_id")
REFERENCES "observations_observation" ("das_tenant_id", "id")
DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "observations_observationsegment"
ADD CONSTRAINT "observations_observa_end_obs_fk"
FOREIGN KEY ("das_tenant_id", "end_observation_id")
REFERENCES "observations_observation" ("das_tenant_id", "id")
DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "observations_observationsegment"
ADD CONSTRAINT "observations_observa_subject_fk"
FOREIGN KEY ("das_tenant_id", "subject_id")
REFERENCES "observations_subject" ("das_tenant_id", "id")
DEFERRABLE INITIALLY DEFERRED;

CREATE INDEX "observation_das_ten_844e39_idx"
ON "observations_observationsegment" ("das_tenant_id", "subject_id", "start_recorded_at");

CREATE INDEX "observation_das_ten_ff294d_idx"
ON "observations_observationsegment" ("das_tenant_id", "subject_id", "end_recorded_at");

CREATE INDEX "observation_das_ten_aee6b0_idx"
ON "observations_observationsegment" ("das_tenant_id", "subject_id", "exclusion_flags");

ALTER TABLE "observations_observationsegment"
ADD CONSTRAINT "observations_observationsegment_unique_segment"
UNIQUE ("start_observation_id", "end_observation_id", "start_recorded_at");
"""

SQL_PARTMAN_REGISTER = """
SELECT partman.create_parent(
    p_parent_table := 'public.observations_observationsegment',
    p_control := 'start_recorded_at',
    p_interval := '1 month',
    p_premake := 5,
    p_default_table := true,
    p_automatic_maintenance := 'on'
);

UPDATE partman.part_config
SET infinite_time_partitions = false,
    retention = '3 years'
WHERE parent_table = 'public.observations_observationsegment';
"""

SQL_DEFAULT_PARTITION_MANUAL = """
CREATE TABLE observations_observationsegment_default PARTITION OF observations_observationsegment DEFAULT;
"""

REVERSE_SQL = """
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'partman' AND table_name = 'part_config') THEN
    DELETE FROM partman.part_config WHERE parent_table = 'public.observations_observationsegment';
  END IF;
END $$;
"""

REVERSE_SQL_DROP = "DROP TABLE IF EXISTS observations_observationsegment CASCADE;"


def _partman_extension_installed(cursor):
    cursor.execute("SELECT 1 FROM pg_extension WHERE extname = 'pg_partman';")
    return cursor.fetchone() is not None


def create_partitioned_observation_segment(apps, schema_editor):
    with schema_editor.connection.cursor() as cursor:
        for stmt in _split_sql(SQL_TABLE_AND_CONSTRAINTS):
            cursor.execute(stmt)

        if _partman_extension_installed(cursor):
            logger.info("pg_partman is installed; registering observations_observationsegment and setting retention.")
            for stmt in _split_sql(SQL_PARTMAN_REGISTER):
                cursor.execute(stmt)
        else:
            logger.info(
                "pg_partman is not installed; creating default partition only. "
                "In production, install pg_partman and register the table for future partitions and retention."
            )
            cursor.execute(SQL_DEFAULT_PARTITION_MANUAL)


def _split_sql(sql):
    """Return list of non-empty statements (psycopg2 executes one statement per call)."""
    return [s.strip() for s in sql.split(";") if s.strip()]


def reverse_partitioned_observation_segment(apps, schema_editor):
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(REVERSE_SQL)
        cursor.execute(REVERSE_SQL_DROP)


class Migration(migrations.Migration):

    dependencies = [
        ("observations", "0199_vicuna"),
    ]

    operations = [
        migrations.RunPython(create_partitioned_observation_segment, reverse_partitioned_observation_segment),
        migrations.CreateModel(
            name="ObservationSegment",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False, default=uuid.uuid4)),
                ("geometry", gis_models.LineStringField(srid=4326)),
                ("speed_kmh", models.FloatField()),
                ("time_gap_ms", models.FloatField()),
                ("distance_meters", models.FloatField()),
                ("start_recorded_at", models.DateTimeField(db_index=True)),
                ("end_recorded_at", models.DateTimeField(db_index=True)),
                ("exclusion_flags", models.BigIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("das_tenant_id", models.UUIDField()),
                ("start_observation_id", models.UUIDField()),
                ("end_observation_id", models.UUIDField()),
                ("subject_id", models.UUIDField()),
            ],
        ),
    ]
