# Generated by Django 3.2.25 on 2026-02-24 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0200_deer'),
        ('observations', '0202_observationsegment_created_at_index'),
    ]

    operations = [
    ]
