# Generated by Django 3.2.21 on 2026-04-10


from django.db import migrations

from observations.migration_utils import TenantSubjectSubTypeLoader

# From 0168_moose_icons
wildlife_subtype_loader_0168 = (
    TenantSubjectSubTypeLoader(subject_type_value="wildlife")
    .add_subject_subtype(display="Moose", value="moose")
    .add_subject_subtype(display="Pronghorn", value="pronghorn")
    .add_subject_subtype(display="Rocky Mountain Bighorn Sheep", value="bighorn_sheep_rocky_mountain")
    .add_subject_subtype(display="Desert Bighorn Sheep", value="bighorn_sheep_desert")
)

# From 0174_duicker_icons
wildlife_subtype_loader_0174 = (
    TenantSubjectSubTypeLoader(subject_type_value="wildlife")
    .add_subject_subtype(display="Duiker", value="duiker")
    .add_subject_subtype(display="Frog", value="frog")
    .add_subject_subtype(display="Gorilla", value="gorilla")
    .add_subject_subtype(display="Hirola", value="hirola")
    .add_subject_subtype(display="Manta ray", value="mantaray")
    .add_subject_subtype(display="Sloth", value="sloth")
)

# From 0178_sheepicons
wildlife_subtype_loader_0178 = (
    TenantSubjectSubTypeLoader(subject_type_value="wildlife")
    .add_subject_subtype(display="Sheep", value="sheep")
    .add_subject_subtype(display="Mule", value="mule")
    .add_subject_subtype(display="Wild Boar", value="wild_boar")
    .add_subject_subtype(display="Mule Deer", value="mule_deer")
    .add_subject_subtype(display="Jaguar", value="jaguar")
    .add_subject_subtype(display="Black Jaguar", value="jaguar_black")
    .add_subject_subtype(display="Macaw", value="macaw")
    .add_subject_subtype(display="Tortoise", value="tortoise")
)

aircraft_subtype_loader = TenantSubjectSubTypeLoader(subject_type_value="aircraft").add_subject_subtype(
    display="Drone Quad-copter", value="drone_quadcopter"
)


class Migration(migrations.Migration):
    dependencies = [
        ("observations", "0204_align_observationsegment_unique_constraint"),
    ]

    operations = [
        migrations.RunPython(wildlife_subtype_loader_0168.load, reverse_code=migrations.RunPython.noop),
        migrations.RunPython(wildlife_subtype_loader_0174.load, reverse_code=migrations.RunPython.noop),
        migrations.RunPython(wildlife_subtype_loader_0178.load, reverse_code=migrations.RunPython.noop),
        migrations.RunPython(aircraft_subtype_loader.load, reverse_code=migrations.RunPython.noop),
    ]
