# Generated by Django 3.2.25 on 2026-04-02 16:03

from django.db import migrations

import observations.models


class Migration(migrations.Migration):

    dependencies = [
        ("observations", "0205_wildboar"),
    ]

    operations = [
        migrations.CreateModel(
            name="CSVObservationImport",
            fields=[],
            options={
                "verbose_name": "Import Observations",
                "verbose_name_plural": "Import Observations",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("observations.observation",),
            managers=[
                ("objects", observations.models.ObservationManager()),
            ],
        ),
    ]
