# Generated by Django 4.2.28 on 2026-02-16 15:01

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("observations", "0206_csv_observation_import_proxy"),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name="message",
            index_together=set(),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["das_tenant", "sender_id", "message_time"], name="observation_das_ten_50164f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["das_tenant", "receiver_id", "message_time"], name="observation_das_ten_8aeec2_idx"
            ),
        ),
        migrations.AlterField(
            model_name="announcementuser",
            name="id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="sourcegroup",
            name="children",
            field=models.ManyToManyField(
                blank=True,
                related_name="_parents",
                through="observations.SourceGroupChildren",
                to="observations.sourcegroup",
            ),
        ),
        migrations.AlterField(
            model_name="sourcegroupchildren",
            name="id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="sourcegrouppermissionset",
            name="id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="sourcegroupsource",
            name="id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="subjectgroup",
            name="children",
            field=models.ManyToManyField(
                blank=True,
                related_name="_parents",
                through="observations.SubjectGroupChildren",
                to="observations.subjectgroup",
            ),
        ),
        migrations.AlterField(
            model_name="subjectgroupchildren",
            name="id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="subjectgrouppermissionset",
            name="id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="subjectgroupsubject",
            name="id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="subjectstatus",
            name="id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
