apiVersion: v1
kind: ConfigMap
metadata:
  namespace: <<namespace>>
  name: site-configmap
data:
  DB_HOST: "<<db-host-name>>"
  DB_PORT: "5432"
  DB_NAME: "<<db-name>>"
  DB_USER: "<<db-user>>"
  DB_PASSWORD: "<<db-password>>"
  STORAGE_ACCOUNT: "<<storage-account-name>>"
  STORAGE_CONTAINER: "<<storage-container>>"
  STORAGE_ACCOUNT_KEY: "<<storage-account-key>>"
  STORAGE_BASE_PATH: "<<storage-base-path>>"
  USE_AZURE_STORAGE: "<<use-azure-storage>>"
  SMS_ID: "<<sms_id>>"
  SMS_TOKEN: "<<sms_token>>"

