apiVersion: v1
kind: ConfigMap
metadata:
  namespace: <<namespace>>
  name: datastore-configmap
data:
  DB_HOST: "<<db-host-name>>"
  DB_PORT: "5432"
  DB_NAME: "<<db-name>>"
  DB_USER: "<<db-user>>"
  DB_PASSWORD: "<<db-password>>"
  BLOB_STORAGE_URL: "<<blob-storage-url>>"
  BLOB_STORAGE_KEY: "<<blob-storage-key>>"
  BLOB_ROOT_PATH: "<<blob-storage-key>>"
  USE_AZURE_STORAGE: "<<use-azure-storage>>"

