apiVersion: v1
kind: ConfigMap
metadata:
  name: site-configmap
data:
  SMARTCONNECT_PROVIDER_DAS_TOKEN: "<<dev-smartconnect-provider-das-token>>"
  SMARTCONNECT_PROVIDER_DAS_API: "https://dev.pamdas.org/api/v1.0"