apiVersion: v1
kind: ConfigMap
metadata:
  namespace: <<namespace>>
  name: site-configmap
data:
  SMARTCONNECT_PROVIDER_DAS_TOKEN: "<<integration-smartconnect-provider-das-token>>"
  SMARTCONNECT_PROVIDER_DAS_API: "https://integration.pamdas.org/api/v1.0"
