apiVersion: v1
kind: ConfigMap
metadata:
  name: ndoki-configmap
data:
  NDOKI_SMARTCONNECT_PROVIDER_DAS_TOKEN: "<<ndoki-smartconnect-provider-das-token>>"
  NDOKI_SMARTCONNECT_PROVIDER_DAS_API: "https://smartconnect.pamdas.org/api/v1.0"