import pytz, datetime
from collections import Counter

from django.utils import timezone
from django.shortcuts import render
from django.views.generic import TemplateView
from django.template.response import TemplateResponse
from rest_framework import status
from rest_framework.response import Response

from rest_framework import serializers, views, permissions
from django.views.generic.base import TemplateResponseMixin, ContextMixin
from reports.reports import get_events, get_conservancies


class ReportDateParameters(serializers.Serializer):
    since = serializers.DateTimeField(default=None)
    before = serializers.DateTimeField(default=None)


class ReportView(views.APIView):
    def dispatch(self, request, report_key, *args, **kwargs):
        print(args, kwargs)
        if report_key == 'sitrep':
            return SituationReportView().dispatch(request, *args, **kwargs)


class SituationReportView(views.APIView, TemplateResponseMixin, ContextMixin, ):

    permission_classes = (permissions.IsAuthenticated,)

    response_class = TemplateResponse
    # content_type = 'application/vnd.openxmlformats-officedocument.wordprocessingml.document'
    # template_engine = 'docx_template'
    # template_name = 'lewa_sitrep_template.docx'

    def get(self, request, *args, **kwargs):

        qs = ReportDateParameters(data=request.query_params)
        if not qs.is_valid():
            return Response(data=qs.errors, status=status.HTTP_400_BAD_REQUEST)

        qs = qs.validated_data
        now = timezone.now()
        since = qs.get('since') or  (now - datetime.timedelta(hours=24))
        before = qs.get('before') or now


        context = self.get_context_data(since=since, before=before, **kwargs)
        return self.render_to_response(context)

    def render_to_response(self, context, **response_kwargs):

        response = super().render_to_response(context, **response_kwargs)
        response['Content-Disposition'] = 'attachement; filename={}'.format(context['report_filename'])
        return response

    def get_context_data(self, since, before, **kwargs):
        '''
        This applies brute-force the the events, marching through the various sections of a Sit Rep and filling in the
        blanks.
        :param kwargs:
        :return:
        '''
        conservancies = get_conservancies()

        report_date = timezone.now()
        report_date_str = report_date.strftime('%Y-%m-%d %H:%M:%S %Z')

        events = get_events(since, before)

        # black_rhino_sightings = list(map(lambda e: (e.attributes['conservancy'], e.event_type),
        #                             [x for x in events if x.event_type.value in ('black_rhino_sighting',)]))
        #
        # white_rhino_sightings = list(map(lambda e: (e.attributes['conservancy'], e.event_type),
        #                             [x for x in events if x.event_type.value in ('white_rhino_sighting',)]))



        wildlife_sightings = [
            {'conservancy': conservancy['name'],
                  'total_rhino_black': -1,
                  'total_rhino_white': -1,
                  'total_sightings': len([_ for _ in events if _.event_type.value in ('black_rhino_sighting', 'white_rhino_sighting')
                                          and _.attributes.get('conservancy') == str(conservancy['id'])]),
                  'rhino_sightings': [
                      {'type': 'Black Rhino',
                       'count': len([_ for _ in events if _.event_type.value == 'black_rhino_sighting'
                                     and _.attributes.get('conservancy') == str(conservancy['id'])])
                       },
                      {'type': 'White Rhino',
                       'count': len([_ for _ in events if _.event_type.value == 'white_rhino_sighting'
                                     and _.attributes.get('conservancy') == str(conservancy['id'])])
                       },
                      ]
                  }
            for conservancy in conservancies]

        context = {
            'report_filename': 'sitrep_report-{}.docx'.format(report_date.strftime('%Y-%m-%d')),
            'report_date': report_date.astimezone(pytz.timezone('Africa/Nairobi')).strftime(
                '%-d %B %Y %Z'),
            'report_daterange_text': 'Including events from: {} to: {}'.format(since.isoformat(), before.isoformat()),
            'footer_text': 'Report generated by DAS user {username} at {report_date}'.format(report_date=report_date_str,
                                                                                         username=self.request.user.get_username()),

            'wildlife_sightings': wildlife_sightings,


            'rhino_births': [],

            'rhino_missing': [
                {'name': 'Folly', 'value': 4},
                {'name': 'Elvis', 'value': 3},
                {'name': 'Muturi', 'value': 4},
                {'name': 'Seneiya + calf 1', 'value': 3},
            ],

            'rhino_territorial_movement': [

            ],

            'other_sightings': [
                {'conservancy': 'Lewa',
                 'total_sightings': 125,
                 'sightings': [
                     {'species': 'elephant', 'count': 50},
                     {'species': 'buffalo', 'count': 75},
                 ]
                 },
                {'conservancy': 'Borana',
                 'total_sightings': 170,
                 'sightings': [
                     {'species': 'elephant', 'count': 118},
                     {'species': 'buffalo', 'count': 52},
                 ]
                 },

            ],

            'gap_counts': [
                {'gap_name': 'Leparua 2 Gap', 'species': 'elephant', 'total_in': 4, 'total_out': 0},
            ],

            'rainfall': [
                {'conservancy_name': 'Lewa'},
                {'conservancy_name': 'Borana'},
                {'conservancy_name': 'Sera'},
            ],

        }

        return context

