import datetime, pytz
from django.shortcuts import render
from django.views.generic import TemplateView
from django.template.response import TemplateResponse

from rest_framework.views import APIView
from rest_framework.permissions import IsAuthenticated
from django.views.generic.base import TemplateResponseMixin, ContextMixin

class ReportView(APIView, TemplateResponseMixin, ContextMixin, ):


    permission_classes = (IsAuthenticated,)

    """
    A view that renders a template.  This view will also pass into the context
    any keyword arguments passed by the URLconf.
    """
    def get(self, request, *args, **kwargs):
        context = self.get_context_data(**kwargs)
        return self.render_to_response(context)

    def render_to_response(self, context, **response_kwargs):

        response = super().render_to_response(context, **response_kwargs)
        response['Content-Disposition'] = 'attachement; filename={}'.format(context['report_filename'])
        return response

    response_class = TemplateResponse
    content_type = 'application/vnd.openxmlformats-officedocument.wordprocessingml.document'

    template_engine = 'docx_template'
    template_name = 'lewa_sitrep_template.docx'

    def get_context_data(self, **kwargs):
        return self.build_context()


    def build_context(self):
        report_date = pytz.utc.localize(datetime.datetime.utcnow())
        report_date_str = report_date.strftime('%Y-%m-%d %H:%M:%S %Z')
        context = {
            'report_filename': 'sitrep_report-{}.docx'.format(report_date.strftime('%Y-%m-%d')),
            'report_date': report_date.astimezone(pytz.timezone('Africa/Nairobi')).strftime(
                '%d-%b-%y %Z'),
            'footer_text': 'Report generated by DAS user {username} at {report_date}'.format(report_date=report_date_str,
                                                                                         username=self.request.user.get_username()),
            'wildlife_sightings': [
                {'convervancy': 'Lewa',
                 'total_rhino_black': 62,
                 'total_rhino_white': 66,
                 'rhino_sightings': [
                     {'type': 'Black Rhino', 'count': 53},
                     {'type': 'White Rhino', 'count': 61}
                 ],
                 'total_sightings': 114
                 },
                {'convervancy': 'Borana',
                 'total_rhino_black': 21,
                 'total_rhino_white': 0,
                 'total_sightings': 11,
                 'rhino_sightings': [
                     {'type': 'Black Rhino', 'count': 11},
                     {'type': 'White Rhino', 'count': 0}
                 ]},
                {'convervancy': 'Sera',
                 'total_rhino_black': 10,
                 'total_rhino_white': 0,
                 'total_sightings': 8,
                 'rhino_sightings': [
                     {'type': 'Black Rhino', 'count': 8},
                     {'type': 'White Rhino', 'count': 0}
                 ]},
            ],

            # 'rhino_births':

            'rhino_missing': [
                {'name': 'Folly', 'value': 4},
                {'name': 'Elvis', 'value': 3},
                {'name': 'Muturi', 'value': 4},
                {'name': 'Seneiya + calf 1', 'value': 3},
            ],

            'rhino_territorial_movement': [

            ],

            'other_sightings': [
                {'conservancy': 'Lewa',
                 'total_sightings': 125,
                 'sightings': [
                     {'species': 'elephant', 'count': 50},
                     {'species': 'buffalo', 'count': 75},
                 ]
                 },
                {'conservancy': 'Borana',
                 'total_sightings': 170,
                 'sightings': [
                     {'species': 'elephant', 'count': 118},
                     {'species': 'buffalo', 'count': 52},
                 ]
                 },

            ],

            'gap_counts': [
                {'gap_name': 'Leparua 2 Gap', 'species': 'elephant', 'total_in': 4, 'total_out': 0},
            ],

            'rainfall': [
                {'conservancy_name': 'Lewa'},
                {'conservancy_name': 'Borana'},
                {'conservancy_name': 'Sera'},
            ],

        }

        return context

