# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-21 15:20
from __future__ import unicode_literals

import accounts.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import mptt.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 30 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=30, unique=True, validators=[django.core.validators.RegexValidator('^[\\w.@+-]+$', 'Enter a valid username. This value may contain only letters, numbers and @/./+/-/_ characters.')], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('phone', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('is_email_alert', models.BooleanField(default=False, help_text='Should email alerts be sent to this user.', verbose_name='email alert')),
                ('is_sms_alert', models.BooleanField(default=False, help_text='Should sms alerts be sent to this user.', verbose_name='sms alert')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
            ],
            options={
                'swappable': 'AUTH_USER_MODEL',
                'verbose_name': 'user',
                'abstract': False,
                'verbose_name_plural': 'users',
            },
            managers=[
                ('objects', accounts.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='PermissionSet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='name')),
                ('category', models.CharField(choices=[('view_animals', 'View Animals'), ('operational_group', 'Operational Group'), ('view_patrols', 'View Patrol Teams'), ('view_vehicles', 'View Vehicles'), ('alerts', 'Alerts'), ('actions', 'Actions'), ('admin', 'Admin')], max_length=100, verbose_name='permission set category')),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('mptt_level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, help_text="The permission set's parent set. None, if it is a root node.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='accounts.PermissionSet', verbose_name='parent')),
                ('permissions', models.ManyToManyField(blank=True, to='auth.Permission', verbose_name='permissions')),
            ],
            options={
                'verbose_name_plural': 'permission_sets',
                'verbose_name': 'permission_set',
            },
            managers=[
                ('objects', accounts.models.PermissionSetManager()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='permission_sets',
            field=models.ManyToManyField(blank=True, help_text='The permission sets this user belongs to. A user will get all permissions granted to each of their permission sets.', related_name='user_set', related_query_name='user', to='accounts.PermissionSet', verbose_name='permission_sets'),
        ),
    ]
