# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-08 17:16
from __future__ import unicode_literals

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_step_two'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='permissionset',
            managers=[
                ('objects', accounts.models.PermissionSetManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='permissionset',
            name='level',
        ),
        migrations.RemoveField(
            model_name='permissionset',
            name='lft',
        ),
        migrations.RemoveField(
            model_name='permissionset',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='permissionset',
            name='rght',
        ),
        migrations.RemoveField(
            model_name='permissionset',
            name='tree_id',
        ),
        migrations.AddField(
            model_name='permissionset',
            name='members',
            field=models.ManyToManyField(blank=True, to='accounts.PermissionSet'),
        ),
        migrations.AlterField(
            model_name='user',
            name='permission_sets',
            field=models.ManyToManyField(blank=True, help_text='The permission sets this user belongs to. A user will get all permissions granted to each of their permission sets.', to='accounts.PermissionSet'),
        ),
    ]
