# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-18 18:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_pset members'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': ('view_user', "View a user's information."), 'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
