# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-10 15:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_event_revision'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permissionset',
            name='parent',
        ),
        migrations.AddField(
            model_name='permissionset',
            name='children',
            field=models.ManyToManyField(blank=True, related_name='_parents',
                                         to='accounts.PermissionSet'),
        ),
        migrations.AddField(
            model_name='permissionset',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='permissionset',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='permissionset',
            name='permissions',
            field=models.ManyToManyField(blank=True,
                                         related_name='permission_sets',
                                         to='auth.Permission'),
        ),
    ]
