# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-12 14:23
from __future__ import unicode_literals

from django.contrib.auth.models import Permission
from django.db import migrations

import utils.models


def populate_pss(apps, schema_editor):
    utils.models.migrate_permissions(apps)
    db_alias = schema_editor.connection.alias
    PermissionSet = apps.get_model(app_label="accounts", model_name="PermissionSet")

    objs = PermissionSet.objects.using(db_alias).bulk_create(
        [
            PermissionSet(
                **{
                    "pk": "e5c21688-be36-4dbd-b8cd-fc9cb7467bb5",
                    "created_at": "2016-07-07T1:00:00.000000+00:00",
                    "updated_at": "2016-07-07T1:00:00.000000+00:00",
                    "name": "All Users",
                }
            ),
            PermissionSet(
                **{
                    "pk": "7f292e0e-3c4b-4dc4-a865-7be41bd5ea7e",
                    "created_at": "2016-07-07T1:00:00.000000+00:00",
                    "updated_at": "2016-07-07T1:00:00.000000+00:00",
                    "name": "Administer All Users",
                }
            ),
        ]
    )

    perms = [
        Permission.objects.get_by_natural_key("add_user", "accounts", "user"),
        Permission.objects.get_by_natural_key("change_user", "accounts", "user"),
        Permission.objects.get_by_natural_key("delete_user", "accounts", "user"),
    ]
    objs[1].permissions.set([perm.id for perm in perms])
    objs[1].save()


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0007_group_update"),
    ]

    operations = [
        migrations.RunPython(populate_pss),
    ]
