# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-12 14:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0007_group_update"),
    ]

    operations = [
        # migrations.RunPython(populate_pss), Move to accounts 0031
    ]
