# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-14 12:07
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_unique_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='additional',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}, verbose_name='additional data'),
        ),
    ]
