# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-29 12:27
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_user_additional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='additional',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}, null=True, verbose_name='additional data'),
        ),
    ]
