# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-12 14:23
from __future__ import unicode_literals

from django.db import migrations
from django.core.management import call_command
from django.contrib.auth.management import create_permissions


def populate_admin(apps, schema_editor):
    # initial data references permissions
    apps.models_module = True
    create_permissions(apps, verbosity=0)

    apps.models_module = None
    call_command('loaddata', 'initial_admin')


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20161129_1227'),
    ]

    operations = [
        migrations.RunPython(populate_admin),
    ]
