# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-06-19 17:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_additional'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='act_as_profiles',
            field=models.ManyToManyField(blank=True, help_text='The list of user profiles that this user can act as.',
                                         related_name='_user_act_as_profiles_+', to=settings.AUTH_USER_MODEL, verbose_name='user profiles'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_nologin',
            field=models.BooleanField(
                default=False, help_text='Prevent the user from logging in. The account is active, but the users password is not active.', verbose_name='no login'),
        ),
    ]
