# Generated by Django 2.0.13 on 2019-08-30 13:53

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='additional',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True, verbose_name='additional data'),
        ),
    ]
