# Generated by Django 2.0.13 on 2020-01-31 10:47

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='accepted_eula',
            field=models.BooleanField(default=False),
        )
    ]
