# Generated by Django 2.0.13 on 2020-02-12 10:29

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_accepted_eula_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='EULA',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid1, primary_key=True, serialize=False)),
                ('version', models.CharField(max_length=30, unique=True)),
                ('eula_url', models.URLField()),
                ('active', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserAgreement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date_accepted', models.DateTimeField(auto_now_add=True, verbose_name='Date Accepted')),
                ('accepted', models.BooleanField(default=False)),
                ('eula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userterms', to='accounts.EULA')),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='additional',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True, verbose_name='additional data'),
        ),
        migrations.AddField(
            model_name='useragreement',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userterms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eula',
            name='users',
            field=models.ManyToManyField(blank=True, through='accounts.UserAgreement', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='useragreement',
            unique_together={('user', 'eula')},
        ),
    ]
