# Generated by Django 2.2.9 on 2020-08-18 13:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_EarthRanger_EULA_ver2020-04-01'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='act_as_profiles',
            field=models.ManyToManyField(blank=True, help_text='The list of user profiles that this user can act as.', to=settings.AUTH_USER_MODEL, verbose_name='user profiles'),
        ),
    ]
