# Generated by Django 3.1 on 2022-06-22 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_asymmetric_rship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='additional',
            field=models.JSONField(
                blank=True, default=dict, null=True, verbose_name='additional data'),
        ),
    ]
