# Generated by Django 3.2 on 2023-03-22 21:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0023_use_models_JSONField_instead_postgres_fields_JSONField"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="pin",
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
