# Generated by Django 3.2 on 2023-04-24 16:47

from django.conf import settings
from django.core.mail import EmailMultiAlternatives
from django.db import migrations
from django.db.models import Count, Subquery


def delete_and_report_repeated_user_pin(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    User = apps.get_model(app_label="accounts", model_name="User")
    repeated_pins = (
        User.objects.using(db_alias)
        .values("pin")
        .filter(pin__isnull=False)
        .annotate(pin_count=Count("pin"))
        .order_by("pin")
        .filter(pin_count__gt=1)
    )
    users_with_repeated_pin = User.objects.filter(pin__in=Subquery(repeated_pins.values("pin")))

    if users_with_repeated_pin.exists():
        send_duplicate_pin_report(users_with_repeated_pin)
        users_with_repeated_pin.update(pin=None)


def send_duplicate_pin_report(users):
    sender = f"EarthRanger Notifications <{settings.FROM_EMAIL}>"
    receiver = "EarthRanger Support <support@earthranger.com>"
    subject = "Users with duplicate PIN"
    message = [
        "Hello Support Team,\n",
        f'The follwing users of site "{settings.UI_SITE_NAME}" ({settings.UI_SITE_URL}) have non unique PIN so each of them has been nulled.\n',
        "Users with duplicate PIN:\n",
    ]
    message.extend(map(user_to_string, users))
    body = "\n".join(message)
    email_message = EmailMultiAlternatives(subject=subject, body=body, from_email=sender, to=[receiver])
    email_message.send()


def user_to_string(user):
    return f"- {user.first_name} {user.last_name} ({user.username})"


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0024_add_pin_field_in_user_model"),
    ]

    operations = [
        migrations.RunPython(delete_and_report_repeated_user_pin, reverse_code=migrations.RunPython.noop),
    ]
