# Generated by Django 3.2 on 2023-06-29 17:58

import logging

from django.db import migrations

logger = logging.getLogger(__name__)


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0025_unset_non_unique_user_pin_values"),
    ]

    # vacated this migration on Aug 31, 2023, as not needed for a clean migration
    operations = []
