# Generated by Django 3.2 on 2023-06-29 17:58

import logging
from datetime import timedelta

from django.db import migrations
from django.db.models import F

logger = logging.getLogger(__name__)


def delete_longer_tokens(apps, schema_editor):
    AccessToken = apps.get_model("oauth2_provider", "AccessToken")

    deleted, _ = (
        AccessToken.objects.annotate(duration=F("expires") - F("created"))
        .filter(duration__gte=timedelta(days=172799))
        .delete()
    )
    logger.info("Deleted %d access tokens", deleted)


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0025_unset_non_unique_user_pin_values"),
    ]

    operations = [
        migrations.RunPython(delete_longer_tokens, reverse_code=migrations.RunPython.noop),
    ]
