# Generated by Django 3.2.19 on 2023-08-24 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("admin", "0001_initial"),
        ("accounts", "0027_change_useragreement_pk_type_to_uuid"),
        ("core", "0006_add_das_tenant_model"),
        ("activity", "0130_create_event_geometry_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="das_tenant",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="core.dastenant"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="user",
            unique_together={("id", "das_tenant")},
        ),
    ]
