# Generated by Django 3.2.19 on 2023-08-24 19:41
import logging

from django.apps import apps
from django.conf import settings
from django.db import migrations

from core.utils import DASTenantManagement, update_tenant_models
from utils.tenant.managers import set_tenant

logger = logging.getLogger(__name__)


def populate_das_tenant_in_user_model(unused, schema_editor):
    User = apps.get_model("accounts", "User")

    class_models = [User]

    das_tenant_management = DASTenantManagement(domain=settings.SERVER_FQDN)
    tenant = das_tenant_management.get_or_create_tenant()
    set_tenant(domain=settings.SERVER_FQDN)

    if tenant:
        update_tenant_models(models=class_models, tenant=tenant)
    else:
        logger.error("DAS Tenant not found.")


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0028_add_das_tenant_into_user_model"),
    ]

    operations = [migrations.RunPython(code=populate_das_tenant_in_user_model, reverse_code=migrations.RunPython.noop)]
