# Generated by Django 3.2.19 on 2023-09-19 12:02
# This approach is taken from Django documentation
#
# For details See: /writing-migrations/#changing-a-manytomanyfield-to-use-a-through-model
# at https://docs.djangoproject.com/en/3.2/howto
import uuid
from functools import partial

import django.db.models.deletion
from django.db import migrations, models

from utils.migrations import populate_model_uuid_column

ACCOUNTS = "accounts"
AUTH = "auth"
PERMISSIONSET_FIELD = "permissionset"
ID_COLUMN = "id"
MANY_TO_MANY_FIELD = "permissions"
MODEL_NAME = "PermissionSetPermission"
PERMISSIONSET_MODEL = "PermissionSet"
PERMISSION_MODEL = "Permission"
PERMISSION_FIELD = "permission"
UUID_COLUMN = "uuid"

NEW_TABLE_NAME = f"{ACCOUNTS}_{MODEL_NAME.lower()}"
OLD_TABLE_NAME = f"{ACCOUNTS}_{PERMISSIONSET_MODEL.lower()}_{MANY_TO_MANY_FIELD}"

populate_uuid = partial(populate_model_uuid_column, ACCOUNTS, MODEL_NAME, UUID_COLUMN)


class Migration(migrations.Migration):
    dependencies = [(ACCOUNTS, "0029_populate_das_tenant_in_user_model")]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=f"ALTER TABLE {OLD_TABLE_NAME} RENAME TO {NEW_TABLE_NAME}",
                    reverse_sql=f"ALTER TABLE {NEW_TABLE_NAME} RENAME TO {OLD_TABLE_NAME}",
                ),
            ],
            state_operations=[
                migrations.CreateModel(
                    name=MODEL_NAME,
                    fields=[
                        ("id", models.AutoField(serialize=True)),
                        (
                            PERMISSIONSET_FIELD,
                            models.ForeignKey(
                                default=uuid.uuid4,
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name=PERMISSIONSET_FIELD,
                                to=f"{ACCOUNTS}.{PERMISSIONSET_MODEL.lower()}",
                            ),
                        ),
                        (
                            PERMISSION_FIELD,
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name=PERMISSION_FIELD,
                                to=f"{AUTH}.{PERMISSION_MODEL.lower()}",
                            ),
                        ),
                    ],
                    options={"abstract": False},
                ),
                migrations.AlterField(
                    model_name=PERMISSIONSET_MODEL.lower(),
                    name=MANY_TO_MANY_FIELD,
                    field=models.ManyToManyField(
                        to=f"{ACCOUNTS}.{PERMISSIONSET_MODEL.lower()}",
                        blank=True,
                        through=f"{ACCOUNTS}.{MODEL_NAME}",
                        related_name="permission_sets",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name=MODEL_NAME.lower(),
            name=UUID_COLUMN,
            field=models.UUIDField(null=True),
        ),
        migrations.RunPython(populate_uuid),
        migrations.RemoveField(
            model_name=MODEL_NAME.lower(),
            name=ID_COLUMN,
        ),
        migrations.RenameField(
            model_name=MODEL_NAME.lower(),
            old_name=UUID_COLUMN,
            new_name=ID_COLUMN,
        ),
        migrations.AlterField(
            model_name=MODEL_NAME.lower(),
            name=ID_COLUMN,
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=True),
        ),
    ]
