# Generated by Django 3.2.19 on 2023-09-21 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_migrate_oauth_tables_to_das_custom_models"),
        ("accounts", "0029_populate_das_tenant_in_user_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="permissionset",
            name="das_tenant",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="core.dastenant"
            ),
        ),
    ]
