# Generated by Django 3.2.19 on 2023-09-26 04:26


import django.db.models.deletion
from django.db import migrations, models

from utils.migrations.update_primary_key import add_tenant_to_primary_key

APP_NAME = "accounts"
MODEL_NAME = "PermissionSetPermission"

accounts_models = [
    "User",
    # "UserAgreement",
    # "EULA"
]


def regenerate_primary_keys(apps, schema_editor):
    add_tenant_to_primary_key(APP_NAME, accounts_models)


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0031_change_pk_type_to_uuid_for_permissionset_permissions"),
    ]

    operations = [
        migrations.AddField(
            model_name=MODEL_NAME,
            name="das_tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name=f"{APP_NAME}_{MODEL_NAME}",
                to="core.dastenant",
            ),
        ),
        migrations.RemoveConstraint(
            model_name="permissionset",
            name="accounts_permissionset_tenant_unique",
        ),
        migrations.AlterUniqueTogether(
            name="user",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="permissionset",
            constraint=models.UniqueConstraint(
                fields=("das_tenant", "name"), name="accounts_permissionset_tenant_name_unique"
            ),
        ),
        migrations.RunPython(code=regenerate_primary_keys, reverse_code=migrations.RunPython.noop),
    ]
