# Generated by Django 3.2.19 on 2023-09-26 04:26


import django.db.models.deletion
from django.db import migrations, models

APP_NAME = "accounts"
MODEL_NAME = "PermissionSetPermission"


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0031_change_pk_type_to_uuid_for_permissionset_permissions"),
    ]

    operations = [
        migrations.AddField(
            model_name=MODEL_NAME,
            name="das_tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name=f"{APP_NAME}_{MODEL_NAME}",
                to="core.dastenant",
            ),
        ),
        migrations.AddConstraint(
            model_name=MODEL_NAME,
            constraint=models.UniqueConstraint(
                fields=("id", "das_tenant"), name=f"{APP_NAME.lower()}_{MODEL_NAME.lower()}_tenant_unique"
            ),
        ),
    ]
