# Generated by Django 3.2.19 on 2023-09-25 21:28
import logging

from django.apps import apps
from django.conf import settings
from django.db import migrations

from core.utils import DASTenantManagement, update_tenant_models

logger = logging.getLogger(__name__)


def populate_tenant_into_models(unused, schema_editor):
    das_tenant_management = DASTenantManagement(domain=settings.SERVER_FQDN)
    tenant = das_tenant_management.get_or_create_tenant()
    PermissionSetPermission = apps.get_model("accounts", "PermissionSetPermission")

    if tenant:
        update_tenant_models(models=[PermissionSetPermission], tenant=tenant)
    else:
        logger.error("DAS Tenant not found.")


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0032_add_das_tenant_to_permissionset_permission"),
    ]

    operations = [
        migrations.RunPython(
            populate_tenant_into_models,
            migrations.RunPython.noop,
        )
    ]
