# Generated by Django 3.2.19 on 2023-09-26 04:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_migrate_oauth_tables_to_das_custom_models"),
        ("accounts", "0033_populate_permissionset_permission_with_tenant"),
    ]

    operations = [
        migrations.AlterField(
            model_name="permissionsetpermission",
            name="das_tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="accounts_permissionsetpermission",
                to="core.dastenant",
            ),
        ),
    ]
