# Generated by Django 3.2.19 on 2023-09-25 20:18
import logging

from django.apps import apps
from django.conf import settings
from django.db import migrations

import utils.models
from core.utils import DASTenantManagement, update_tenant_models
from utils.tenant.managers import set_tenant

logger = logging.getLogger(__name__)


def populate_permissions_set(unused, _):
    PermissionSet = apps.get_model("accounts", "PermissionSet")

    class_models = [PermissionSet]

    das_tenant_management = DASTenantManagement(domain=settings.SERVER_FQDN)
    tenant = das_tenant_management.get_or_create_tenant()
    set_tenant(domain=settings.SERVER_FQDN)

    if tenant:
        update_tenant_models(models=class_models, tenant=tenant)
    else:
        logger.error("DAS Tenant not found.")


def apply_permissions_sets(unused, _):
    utils.models.migrate_permissions(apps)
    # we specifically do not use loaddata_with_tenant here
    # the following two lines were added here, but don't work for sites that have already migrated to this point
    # maybe if these records already exist, we ignore them?

    # call_command("loaddata", "initial_pss", app_label="accounts")  # comes from accounts 0008
    # call_command("loaddata", "reported_by_permission_set", app_label="accounts")  # comes from accounts 0014


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0034_alter_permissionsetpermission_das_tenant"),
    ]

    operations = [
        migrations.RunPython(code=apply_permissions_sets, reverse_code=migrations.RunPython.noop),
        migrations.RunPython(code=populate_permissions_set, reverse_code=migrations.RunPython.noop),
    ]
