# Generated by Django 3.2.19 on 2023-10-03 22:57

import django.db.models.deletion
from django.db import migrations, models

import utils.migrations.columns


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_populate_oauth_models_with_tenant"),
        ("accounts", "0035_populate_permission_sets"),
    ]

    operations = [
        migrations.AlterField(
            model_name="permissionsetpermission",
            name="das_tenant",
            field=models.ForeignKey(
                default=utils.migrations.columns.default_tenant_id,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="accounts_permissionsetpermission",
                to="core.dastenant",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="das_tenant",
            field=models.ForeignKey(
                default=utils.migrations.columns.default_tenant_id,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.dastenant",
            ),
        ),
    ]
