# Generated by Django 3.2.21 on 2023-10-27 16:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0037_alter_permissionset_das_tenant"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name="email address"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["das_tenant", "email"], name="accounts_user_email_index"),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.UniqueConstraint(
                fields=("das_tenant", "email"), name="accounts_user_unique_email_across_tenatns"
            ),
        ),
    ]
