# Generated by Django 3.2.21 on 2023-11-14 19:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0038_made_email_unique_across_tenants"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                error_messages={"unique": "A user with that username already exists."},
                help_text="Required. 30 characters or fewer. Letters, digits and @/./+/-/_ only.",
                max_length=30,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[\\w.@+-]+$",
                        "Enter a valid username. This value may contain only letters, numbers and @/./+/-/_ characters.",
                    )
                ],
                verbose_name="username",
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["das_tenant", "username"], name="accounts_user_username_index"),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.UniqueConstraint(
                fields=("das_tenant", "username"), name="accounts_user_unique_username_across_tenatns"
            ),
        ),
    ]
