# Generated by Django 3.2.21 on 2023-11-19 20:13

from django.db import migrations

import accounts.models.permissionset


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0039_made_username_unique_across_tenants"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="permissionsetpermission",
            managers=[
                ("objects", accounts.models.permissionset.PermissionSetPermissionManager()),
            ],
        ),
    ]
