# Generated by Django 3.2.21 on 2023-11-20 18:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0040_alter_permissionsetpermission_managers"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"base_manager_name": "objects", "verbose_name": "user", "verbose_name_plural": "users"},
        ),
    ]
