# Generated by Django 3.2.19 on 2023-09-26 04:26


from django.db import migrations

from utils.migrations.update_primary_key import add_tenant_to_primary_key

APP_NAME = "accounts"

accounts_models = [
    "PermissionSet",
]


def regenerate_primary_keys(apps, schema_editor):
    add_tenant_to_primary_key(APP_NAME, accounts_models)


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0041_usermanager"),
    ]

    operations = [
        migrations.RunPython(code=regenerate_primary_keys, reverse_code=migrations.RunPython.noop),
    ]
