# Generated by Django 3.2.21 on 2023-11-25 00:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0042_regenerate_pk_permission_set"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="permissionset",
            options={
                "base_manager_name": "objects",
                "default_manager_name": "objects",
                "verbose_name": "permission set",
                "verbose_name_plural": "permission sets",
            },
        ),
    ]
