# Generated by Django 3.2.21 on 2023-11-27 18:35

import django_multitenant.fields

import django.db.models.deletion
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0043_alter_permissionset_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="permissionsetpermission",
            name="permissionset",
            field=django_multitenant.fields.TenantForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="accounts.permissionset"
            ),
        ),
    ]
