# Generated by Django 3.2.21 on 2023-12-01 17:00

import uuid
from functools import partial

from django_multitenant.fields import TenantForeignKey

import django.db.models.deletion
from django.db import migrations, models

import utils.migrations.columns
from utils.migrations import populate_model_uuid_column
from utils.migrations.update_primary_key import add_tenant_to_primary_key

APP_NAME = "accounts"
ACCOUNTS_MODELS = ["PermissionSetChildren"]

populate_uuid = partial(populate_model_uuid_column, "accounts", "PermissionSetChildren", "uuid")


def regenerate_primary_keys(apps, schema_editor):
    add_tenant_to_primary_key(APP_NAME, ACCOUNTS_MODELS)


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0044_add_tenantforeignkey_into_permissionsetpermission"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="ALTER TABLE accounts_permissionset_children RENAME TO accounts_permissionsetchildren",
                    reverse_sql="ALTER TABLE accounts_permissionsetchildren RENAME TO accounts_permissionset_children",
                ),
            ],
            state_operations=[
                migrations.CreateModel(
                    name="PermissionSetChildren",
                    fields=[
                        ("id", models.AutoField(serialize=False)),
                        (
                            "from_permissionset",
                            TenantForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                to="accounts.PermissionSet",
                            ),
                        ),
                        (
                            "to_permissionset",
                            TenantForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                to="accounts.PermissionSet",
                            ),
                        ),
                    ],
                ),
                migrations.AlterField(
                    model_name="PermissionSet",
                    name="children",
                    field=models.ManyToManyField(
                        to="self",
                        related_name="_parents",
                        through="accounts.PermissionSetChildren",
                        through_fields=("from_permissionset", "to_permissionset"),
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="PermissionSetChildren",
            name="uuid",
            field=models.UUIDField(null=True),
        ),
        migrations.RunPython(
            code=populate_uuid,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name="PermissionSetChildren",
            name="id",
        ),
        migrations.RenameField(
            model_name="PermissionSetChildren",
            old_name="uuid",
            new_name="id",
        ),
        migrations.AlterField(
            model_name="PermissionSetChildren",
            name="id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=True),
        ),
        migrations.AlterModelManagers(
            name="PermissionSetChildren",
            managers=[
                ("objects", utils.models.CommonTenantManager()),
            ],
        ),
        migrations.AlterModelOptions(
            name="permissionsetchildren",
            options={"base_manager_name": "objects", "default_manager_name": "objects"},
        ),
        migrations.AddField(
            model_name="PermissionSetChildren",
            name="das_tenant",
            field=models.ForeignKey(
                default=utils.migrations.columns.default_tenant_id,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.dastenant",
            ),
        ),
        migrations.RunPython(code=regenerate_primary_keys, reverse_code=migrations.RunPython.noop),
    ]
