# Generated by Django 3.2.21 on 2023-12-07 19:24

import django_multitenant.fields

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0015_delete_unique_constraints"),
        ("accounts", "0045_custom_through_model_permissionsetchildren"),
    ]

    operations = [
        migrations.AlterField(
            model_name="permissionset",
            name="children",
            field=models.ManyToManyField(
                blank=True,
                related_name="_parents",
                through="accounts.permissionsetchildren",
                to="accounts.PermissionSet",
            ),
        ),
        migrations.AlterField(
            model_name="permissionsetchildren",
            name="from_permissionset",
            field=django_multitenant.fields.TenantForeignKey(
                db_column="from_permissionset_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="self",
                to="accounts.permissionset",
            ),
        ),
        migrations.AlterField(
            model_name="permissionsetchildren",
            name="to_permissionset",
            field=django_multitenant.fields.TenantForeignKey(
                db_column="to_permissionset_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children_to",
                to="accounts.permissionset",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="permissionsetchildren",
            unique_together={("das_tenant", "from_permissionset", "to_permissionset")},
        ),
        migrations.AlterModelTable(
            name="permissionsetchildren",
            table="accounts_permissionsetchildren",
        ),
    ]
