# Generated by Django 3.2.21 on 2023-12-05 18:32
import uuid
from functools import partial

from django_multitenant.fields import TenantForeignKey

import django.db.models.deletion
from django.db import migrations, models

import utils.models
from utils.migrations import populate_model_uuid_column

APP_NAME = "accounts"
ID_COLUMN = "id"
MODEL_NAME = "ActAsProfiles"
UUID_COLUMN = "uuid"

populate_uuid = partial(populate_model_uuid_column, APP_NAME, MODEL_NAME, UUID_COLUMN)


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0046_auto_20231207_1124"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="ALTER TABLE accounts_user_act_as_profiles RENAME TO accounts_actasprofiles",
                    reverse_sql="ALTER TABLE accounts_actasprofiles RENAME TO accounts_user_act_as_profiles",
                ),
            ],
            state_operations=[
                migrations.CreateModel(
                    name="ActAsProfiles",
                    fields=[
                        (
                            "id",
                            models.AutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        (
                            "from_user",
                            TenantForeignKey(
                                on_delete=django.db.models.deletion.DO_NOTHING,
                                to="accounts.User",
                            ),
                        ),
                        (
                            "to_user",
                            TenantForeignKey(
                                on_delete=django.db.models.deletion.DO_NOTHING,
                                to="accounts.User",
                            ),
                        ),
                    ],
                ),
                migrations.AlterField(
                    model_name="user",
                    name="act_as_profiles",
                    field=models.ManyToManyField(
                        to="accounts.User",
                        through="accounts.ActAsProfiles",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="actasprofiles",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.RunPython(populate_uuid),
        migrations.RemoveField(
            model_name="actasprofiles",
            name="id",
        ),
        migrations.RenameField(
            model_name="actasprofiles",
            old_name="uuid",
            new_name="id",
        ),
        migrations.AlterField(
            model_name="actasprofiles",
            name="id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=True),
        ),
        migrations.AlterModelManagers(
            name="actasprofiles",
            managers=[
                ("objects", utils.models.CommonTenantManager()),
            ],
        ),
        migrations.AddField(
            model_name="actasprofiles",
            name="das_tenant",
            field=models.ForeignKey(
                default=utils.migrations.columns.default_tenant_id,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.dastenant",
            ),
        ),
    ]
