# Generated by Django 3.2.21 on 2023-12-14 18:56

from django.db import migrations, models

from utils.migrations.update_primary_key import (
    add_tenant_to_primary_key,
    drop_constraint,
)

APP_NAME = "accounts"


accounts_models = ["ActAsProfiles"]


def regenerate_primary_keys(apps, schema_editor):
    add_tenant_to_primary_key(APP_NAME, accounts_models)


def drop_constraints(apps, schema_editor):
    drop_constraint(
        app=APP_NAME,
        model="ActAsProfiles",
        constraint="accounts_actasprofiles_id_68665e88_uniq",
    )
    drop_constraint(
        app=APP_NAME,
        model="ActAsProfiles",
        constraint="accounts_user_act_as_pro_from_user_id_to_user_id_5eb8fa13_uniq",
    )


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0047_custom_many_to_many"),
    ]

    operations = [
        migrations.RunPython(code=regenerate_primary_keys, reverse_code=migrations.RunPython.noop),
        migrations.RunPython(code=drop_constraints, reverse_code=migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="actasprofiles",
            constraint=models.UniqueConstraint(
                fields=("from_user", "to_user", "das_tenant"),
                name="accounts_user_act_as_pro_from_user_id_to_user_id_5eb8fa13_uniq",
            ),
        ),
    ]
