# Generated by Django 3.2.21 on 2024-02-25 21:44


import uuid
from functools import partial

from django_multitenant.fields import TenantForeignKey

import django.db.models.deletion
from django.db import migrations, models

import utils.migrations.columns
from core.utils import backfill_through_model_with_tenant
from utils.migrations import populate_model_uuid_column
from utils.migrations.update_primary_key import add_tenant_to_primary_key

APP_NAME = "accounts"
ACCOUNTS_MODELS = ["UserPermissionSet"]

CURRENT_TABLE_NAME = "accounts_user_permission_sets"
NEW_TABLE_NAME = "accounts_userpermissionset"


populate_uuid = partial(populate_model_uuid_column, "accounts", "UserPermissionSet", "uuid")
populate_through_model_tenant_id = partial(
    backfill_through_model_with_tenant, "accounts_user", "id", NEW_TABLE_NAME, "user_id"
)


def regenerate_primary_keys(apps, schema_editor):
    add_tenant_to_primary_key(APP_NAME, ACCOUNTS_MODELS)


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0048_regenerate_primary_key_act_as_profiles"),
    ]
    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=f"ALTER TABLE {CURRENT_TABLE_NAME} RENAME TO {NEW_TABLE_NAME}",
                    reverse_sql=f"ALTER TABLE {NEW_TABLE_NAME} RENAME TO {CURRENT_TABLE_NAME}",
                ),
            ],
            state_operations=[
                migrations.CreateModel(
                    name="UserPermissionSet",
                    fields=[
                        ("id", models.AutoField(serialize=False)),
                        (
                            "user",
                            TenantForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                to="accounts.User",
                            ),
                        ),
                        (
                            "permissionset",
                            TenantForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                to="accounts.PermissionSet",
                            ),
                        ),
                    ],
                ),
                migrations.AlterField(
                    model_name="user",
                    name="permission_sets",
                    field=models.ManyToManyField(
                        blank=True,
                        help_text="The permission sets this user belongs to. A user will get all permissions granted to each of their permission sets.",
                        related_name="user_set",
                        through="accounts.UserPermissionSet",
                        to="accounts.PermissionSet",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="userpermissionset",
            name="uuid",
            field=models.UUIDField(null=True),
        ),
        migrations.RunPython(
            code=populate_uuid,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name="userpermissionset",
            name="id",
        ),
        migrations.RenameField(
            model_name="userpermissionset",
            old_name="uuid",
            new_name="id",
        ),
        migrations.AlterField(
            model_name="userpermissionset",
            name="id",
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, editable=False, serialize=True),
        ),
        migrations.AlterModelManagers(
            name="userpermissionset",
            managers=[
                ("objects", utils.models.CommonTenantManager()),
            ],
        ),
        migrations.AlterModelOptions(
            name="userpermissionset",
            options={"base_manager_name": "objects", "default_manager_name": "objects"},
        ),
        migrations.AddField(
            model_name="userpermissionset",
            name="das_tenant",
            field=models.ForeignKey(
                default=utils.migrations.columns.default_tenant_id,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.dastenant",
                related_name="accounts_userpermissionset",
            ),
        ),
        migrations.RunPython(
            code=regenerate_primary_keys,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RunPython(
            code=populate_through_model_tenant_id,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
