# Generated by Django 3.2.21 on 2024-02-25 21:44


import uuid
from functools import partial

from django_multitenant.fields import TenantForeignKey

import django.db.models.deletion
from django.db import migrations, models

import utils.migrations.columns
from utils.migrations import populate_model_uuid_column
from utils.migrations.update_primary_key import add_tenant_to_primary_key

APP_NAME = "accounts"
ACCOUNTS_MODELS = ["UserPermissionSet"]

populate_uuid = partial(populate_model_uuid_column, "accounts", "UserPermissionSet", "uuid")


def regenerate_primary_keys(apps, schema_editor):
    add_tenant_to_primary_key(APP_NAME, ACCOUNTS_MODELS)


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0048_regenerate_primary_key_act_as_profiles"),
    ]
    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="ALTER TABLE accounts_user_permission_sets RENAME TO accounts_userpermissionset",
                    reverse_sql="ALTER TABLE accounts_userpermissionset RENAME TO accounts_user_permission_sets",
                ),
            ],
            state_operations=[
                migrations.CreateModel(
                    name="UserPermissionSet",
                    fields=[
                        ("id", models.AutoField(serialize=False)),
                        (
                            "user",
                            TenantForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                to="accounts.User",
                            ),
                        ),
                        (
                            "permissionset",
                            TenantForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                to="accounts.PermissionSet",
                            ),
                        ),
                    ],
                ),
                migrations.AlterField(
                    model_name="User",
                    name="permission_sets",
                    field=models.ManyToManyField(
                        to="self",
                        related_name="user_set",
                        through="accounts.UserPermissionSet",
                        through_fields=("user", "permissionset"),
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="UserPermissionSet",
            name="uuid",
            field=models.UUIDField(null=True),
        ),
        migrations.RunPython(
            code=populate_uuid,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name="UserPermissionSet",
            name="id",
        ),
        migrations.RenameField(
            model_name="UserPermissionSet",
            old_name="uuid",
            new_name="id",
        ),
        migrations.AlterField(
            model_name="UserPermissionSet",
            name="id",
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, editable=False, serialize=True),
        ),
        migrations.AlterModelManagers(
            name="UserPermissionSet",
            managers=[
                ("objects", utils.models.CommonTenantManager()),
            ],
        ),
        migrations.AlterModelOptions(
            name="userpermissionset",
            options={"base_manager_name": "objects", "default_manager_name": "objects"},
        ),
        migrations.AddField(
            model_name="UserPermissionSet",
            name="das_tenant",
            field=models.ForeignKey(
                default=utils.migrations.columns.default_tenant_id,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.dastenant",
            ),
        ),
        migrations.RunPython(
            code=regenerate_primary_keys,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
