# Generated by Django 3.2.21 on 2024-03-08 18:03

import django_multitenant.fields

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0049_auto_20240225_1344"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="actasprofiles",
            options={"base_manager_name": "objects", "default_manager_name": "objects"},
        ),
        migrations.RemoveConstraint(
            model_name="actasprofiles",
            name="accounts_user_act_as_pro_from_user_id_to_user_id_5eb8fa13_uniq",
        ),
        migrations.AlterField(
            model_name="actasprofiles",
            name="from_user",
            field=django_multitenant.fields.TenantForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="others",
                related_query_name="others",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="actasprofiles",
            name="to_user",
            field=django_multitenant.fields.TenantForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddConstraint(
            model_name="actasprofiles",
            constraint=models.UniqueConstraint(
                fields=("das_tenant", "from_user", "to_user"), name="accounts_actasprofiles_tenant_from_to_unique"
            ),
        ),
    ]
