# Generated by Django 3.2.21 on 2024-03-21 23:05

from django.db import migrations, models

from utils.migrations.update_primary_key import (
    add_tenant_to_primary_key,
    drop_constraint,
)

APP_NAME = "accounts"


def regenerate_primary_keys(apps, schema_editor):
    add_tenant_to_primary_key(APP_NAME, ["PermissionSetPermission"])


def drop_constraints(apps, schema_editor):
    for constraint in (
        "accounts_permissionset_p_permissionset_id_permiss_ae67763e_uniq",
        "accounts_permissionsetpermission_id_f54df606_uniq",
        "accounts_permissions_permission_id_5b7e3342_fk_auth_perm",
    ):
        drop_constraint(
            app=APP_NAME,
            model="PermissionSetPermission",
            constraint=constraint,
        )


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0050_actasprofileconstraint"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="permissionsetpermission",
            options={"base_manager_name": "objects", "default_manager_name": "objects"},
        ),
        migrations.RunPython(code=regenerate_primary_keys, reverse_code=migrations.RunPython.noop),
        migrations.RunPython(code=drop_constraints, reverse_code=migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="permissionsetpermission",
            constraint=models.UniqueConstraint(
                fields=("das_tenant", "permissionset", "permission"),
                name="accounts_permissionsetpermission_tenant_unique",
            ),
        ),
    ]
