# Generated by Django 3.2.21 on 2024-04-05 13:37
from functools import partial

import django_multitenant.fields

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import utils.migrations.columns
import utils.models
from core.utils import backfill_through_model_with_tenant
from utils.migrations.update_primary_key import (
    add_tenant_to_primary_key,
    drop_constraint,
)

APP_NAME = "accounts"
APP_MODELS = ["UserAgreement"]


def regenerate_primary_keys(apps, schema_editor):
    add_tenant_to_primary_key(APP_NAME, APP_MODELS)


populate_through_model_tenant_id = partial(
    backfill_through_model_with_tenant, "accounts_user", "id", "accounts_useragreement", "user_id"
)


def drop_constraints(apps, schema_editor):
    for constraint in ("accounts_useragreement_id_77da7947_uniq",):
        drop_constraint(
            app=APP_NAME,
            model="UserAgreement",
            constraint=constraint,
        )


class Migration(migrations.Migration):

    dependencies = [
        # ideally we have this core dependency, but it throws off the migration order
        # ("core", "0024_recreate_useragreement_eula_fk"),
        ("accounts", "0051_permissionsetpermission_constraint"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="useragreement",
            options={"base_manager_name": "objects", "default_manager_name": "objects"},
        ),
        migrations.AlterModelManagers(
            name="useragreement",
            managers=[
                ("objects", utils.models.CommonTenantManager()),
            ],
        ),
        migrations.AddField(
            model_name="useragreement",
            name="das_tenant",
            field=models.ForeignKey(
                default=utils.migrations.columns.default_tenant_id,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.dastenant",
            ),
        ),
        migrations.RunPython(
            code=regenerate_primary_keys,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="useragreement",
            name="user",
            field=django_multitenant.fields.TenantForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="userterms", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.RunPython(
            code=populate_through_model_tenant_id,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RunPython(code=drop_constraints, reverse_code=migrations.RunPython.noop),
        migrations.AlterUniqueTogether(
            name="useragreement",
            unique_together={("das_tenant", "user", "eula")},
        ),
    ]
