# Generated by Django 3.2.21 on 2024-04-12 22:31


from django.db import migrations

from utils.migrations.update_primary_key import drop_constraint
from utils.permission_sets import set_permissions_set_hash

APP_NAME = "accounts"
APP_MODELS = ["UserAgreement"]


def drop_constraints(apps, schema_editor):
    for constraint in ("accounts_useragreement_id_77da7947_uniq",):
        drop_constraint(
            app=APP_NAME,
            model="UserAgreement",
            constraint=constraint,
        )


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0052_useragreement"),
    ]

    operations = [
        migrations.RunPython(code=drop_constraints, reverse_code=migrations.RunPython.noop),
        migrations.AlterUniqueTogether(
            name="useragreement",
            unique_together={("das_tenant", "user", "eula")},
        ),
        migrations.RunPython(
            set_permissions_set_hash,
            migrations.RunPython.noop,
        ),
    ]
