# Generated by Django 3.2.21 on 2024-05-16 16:25

from django.db import migrations, models

SQL = """
ALTER TABLE accounts_userpermissionset
    DROP CONSTRAINT IF EXISTS accounts_user_permission_user_id_permissionset_id_a4d19283_uniq;
"""

REVERT_SQL = """
ALTER TABLE accounts_userpermissionset
    DROP CONSTRAINT IF EXISTS accounts_userpermissionset_unique_across_tenants;

ALTER TABLE accounts_userpermissionset
    ADD CONSTRAINT accounts_user_permission_user_id_permissionset_id_a4d19283_uniq
        UNIQUE (user_id, permissionset_id);
"""


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0053_useragreement_constraint"),
    ]

    operations = [
        migrations.RunSQL(
            sql=SQL,
            reverse_sql=REVERT_SQL,
        ),
        migrations.AlterModelOptions(
            name="userpermissionset",
            options={},
        ),
        migrations.AddConstraint(
            model_name="userpermissionset",
            constraint=models.UniqueConstraint(
                fields=("das_tenant", "user", "permissionset"),
                name="accounts_userpermissionset_unique_across_tenants",
            ),
        ),
    ]
