# Generated by Django 3.2.21 on 2024-07-01 15:45

from django.apps import apps
from django.conf import settings
from django.db import migrations

from core.models import DASTenant
from utils.json import load_from_file
from utils.tenant.managers import TenantContextManager

JSON_FILE = f"{settings.BASE_DIR}/das_server/fixtures/initial_data.json"


def code(migration_apps, schema_editor):
    PermissionSet = apps.get_model("accounts", "PermissionSet")

    initial_data_objects = load_from_file(file_path=JSON_FILE)

    reported_by_users_json = list(
        filter(
            lambda perms: str(perms.get("fields", {}).get("name")) == "Reported By Users",
            initial_data_objects,
        )
    )[0]
    fields = reported_by_users_json.get("fields", {})
    fields.pop("children")

    for tenant in DASTenant.objects.all():
        fields["das_tenant"] = tenant
        with TenantContextManager(tenant.domain):
            try:
                existing_permission_set = PermissionSet.objects.get(name="Reported By Users")
                existing_permission_set.name += "_changed"
                existing_permission_set.save(update_fields=["name"])
            except PermissionSet.DoesNotExist:
                existing_permission_set = None

            if not existing_permission_set:
                reported_by_users_perm_set = PermissionSet.objects.create(**fields)

            elif reported_by_users_json["pk"] != str(getattr(existing_permission_set, "id", "")):
                reported_by_users_perm_set = PermissionSet.objects.create(id=reported_by_users_json["pk"], **fields)

                for related_field_name in ("user_set", "subjectgroup_set", "sourcegroup_set", "children"):
                    existing_related_object = getattr(existing_permission_set, related_field_name)
                    objects = existing_related_object.filter(das_tenant_id=tenant.id)

                    related_object = getattr(reported_by_users_perm_set, related_field_name)
                    related_object.add(*objects)

                permissions = existing_permission_set.permissions.all()
                reported_by_users_perm_set.permissions.add(*permissions)

                existing_permission_set.delete()


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0054_change_unique_constraint_userpermissionset"),
    ]

    operations = [
        migrations.RunPython(
            code=code,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
