# Generated by Django 3.2.21 on 2024-09-23 22:19
import logging

from django.db import connection, migrations

logger = logging.getLogger(__name__)


def delete_permissions(apps, _):
    Permission = apps.get_model("auth.permission")
    permissions_to_delete = Permission.objects.filter(codename__endswith="_geographic_distance")

    permission_ids = [permission.id for permission in permissions_to_delete]
    if permission_ids:
        logger.info(f"Deleting {len(permission_ids)} permissions that end in _geographic_distance")
        with connection.cursor() as cursor:
            delete_permissionsetpermissions = (
                "DELETE FROM accounts_permissionsetpermission WHERE permission_id IN %(p_ids)s;"
            )
            cursor.execute(delete_permissionsetpermissions, {"p_ids": tuple(permission_ids)})

            delete_permissions = "DELETE FROM auth_permission WHERE id IN %(p_ids)s;"
            cursor.execute(delete_permissions, {"p_ids": tuple(permission_ids)})


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0055_fix_permission_set_reported_by_users"),
    ]

    operations = [
        migrations.RunPython(
            code=delete_permissions,
            reverse_code=migrations.RunPython.noop,
        )
    ]
