# Generated by Django 3.2.21 on 2024-09-23 22:19
from django.db import migrations


def delete_permissions(apps, _):
    Permission = apps.get_model("auth.permission")
    permissions_to_delete = Permission.objects.filter(codename__endswith="_geographic_distance")
    permissions_to_delete.delete()


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0055_fix_permission_set_reported_by_users"),
    ]

    operations = [
        migrations.RunPython(
            code=delete_permissions,
            reverse_code=migrations.RunPython.noop,
        )
    ]
