# Generated by Django 3.2.21 on 2024-10-17 20:27

from django.db import migrations

SQL = """
DELETE
FROM accounts_permissionsetpermission psp
where psp.permissionset_id in (SELECT psp.permissionset_id
                               FROM accounts_permissionsetpermission psp
                                        LEFT JOIN accounts_permissionset ps ON ps.id = psp.permissionset_id
                               WHERE ps.id IS NULL);
"""


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0056_delete_geographic_distance_legacy_permissions"),
    ]

    operations = [
        migrations.RunSQL(
            sql=SQL,
            reverse_sql=migrations.RunSQL.noop,
        )
    ]
