# Generated by Django 3.2.25 on 2025-11-26 23:39

from django.db import migrations

SQL = """
ALTER TABLE accounts_permissionsetchildren
    DROP CONSTRAINT IF EXISTS accounts_permissionsetchildren_id_0c7ede5d_uniq;

ALTER TABLE accounts_permissionsetchildren
    DROP CONSTRAINT IF EXISTS accounts_permissionset_c_from_permissionset_id_to_57506d20_uniq;
"""


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0057_delete_permissionsetpermission_record_referencing_not_existing_permissionset"),
    ]

    operations = [
        migrations.RunSQL(
            sql=SQL,
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
