# Generated by Django 3.2.25 on 2025-12-05 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0057_delete_permissionsetpermission_record_referencing_not_existing_permissionset"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="auth0_id",
            field=models.CharField(
                blank=True, help_text="Auth0 subject identifier (sub claim)", max_length=256, null=True
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.UniqueConstraint(
                condition=models.Q(auth0_id__isnull=False),
                fields=("das_tenant", "auth0_id"),
                name="accounts_user_unique_auth0_id_per_tenant",
            ),
        ),
    ]
