# Generated by Django 3.2.25 on 2025-12-10 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0058_permissionsetchildren'),
        ('accounts', '0059_add_auth0_id_column'),
    ]

    operations = [
    ]
