# Generated by Django 3.2.25 on 2026-03-02 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0060_merge_20251210_2033"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_system",
            field=models.BooleanField(
                default=False,
                help_text="Designates whether this user is an automatically generated system user.",
                verbose_name="system user",
            ),
        ),
    ]
