# Generated by Django 3.2.25 on 2026-03-03 11:19

from django.db import migrations

from accounts.system_users import SYSTEM_USERNAMES
from utils.tenant.managers import UnsetDASTenantContextManager


def forward_func(apps, schema_editor):
    with UnsetDASTenantContextManager():
        User = apps.get_model("accounts", "User")
        User.objects.filter(username__in=SYSTEM_USERNAMES).update(is_system=True)


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0061_add_is_system_to_user"),
        ("das_server", "0001_squashed_0002_add_kml_application"),
    ]

    operations = [
        migrations.RunPython(forward_func, migrations.RunPython.noop),
    ]
