# Generated by Django 3.2.25 on 2026-03-03 11:19

from django.db import migrations

SYSTEM_USERNAMES = [
    "er_system",
    "system_analyzers",
    "gfwwebhookuser",
    "das_oauth_act",
    "deleted",
]


def forward_func(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    db_alias = schema_editor.connection.alias
    User.objects.using(db_alias).filter(username__in=SYSTEM_USERNAMES).update(is_system=True)


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0061_add_is_system_to_user"),
    ]

    operations = [
        migrations.RunPython(forward_func, migrations.RunPython.noop),
    ]
