# Generated by Django 4.2.28 on 2026-02-16 15:01

import uuid

import django.db.models.deletion
from django.db import migrations, models

import utils.migrations.columns


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0031_django_42"),
        ("accounts", "0062_populate_is_system_for_existing_users"),
    ]

    operations = [
        migrations.AlterField(
            model_name="actasprofiles",
            name="id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="permissionset",
            name="children",
            field=models.ManyToManyField(
                blank=True,
                related_name="_parents",
                through="accounts.PermissionSetChildren",
                to="accounts.permissionset",
            ),
        ),
        migrations.AlterField(
            model_name="permissionsetchildren",
            name="id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="permissionsetpermission",
            name="das_tenant",
            field=models.ForeignKey(
                default=utils.migrations.columns.default_tenant_id,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s",
                to="core.dastenant",
            ),
        ),
        migrations.AlterField(
            model_name="permissionsetpermission",
            name="id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="useragreement",
            name="id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="userpermissionset",
            name="das_tenant",
            field=models.ForeignKey(
                default=utils.migrations.columns.default_tenant_id,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s",
                to="core.dastenant",
            ),
        ),
        migrations.AlterField(
            model_name="userpermissionset",
            name="id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
