global:
  slack_api_url: ${ALERTS_SLACK_URL}

route:
  group_by: [alertname, datacenter, app]
  receiver: shared-services-slack

receivers:
- name: 'shared-services-slack'
  slack_configs:
  - api_url: ${ALERTS_SLACK_URL}
    channel: ${ALERTS_SLACK_CHANNEL}
    send_resolved: true

