global:
  slack_api_url: 'https://hooks.slack.com/services/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'

route:
  group_by: [alertname, datacenter, app]
  receiver: shared-services-slack

receivers:
- name: 'shared-services-slack'
  slack_configs:
  - api_url: 'https://hooks.slack.com/services/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'
    channel: ${ALERTS_SLACK_CHANNEL}
    send_resolved: true

