apiVersion: v1
kind: Endpoints
metadata:
  name: az-postgres # Must be same as service name
  namespace: default
subsets:
  - addresses:
      - ip: das-postgres-us-azure.postgres.database.azure.com
    ports:
      - port: 5432