apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  type: LoadBalancer
  loadBalancerIP: <<static-ip>>
  ports:
  - port: 80
    targetPort: 8000
    name: http-port
  - port: 443
    targetPort: 443
    name: https-port
  selector:
    das.component: nginx
