apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: smartconnect-provider-etl
spec:
  schedule: "*/20 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          imagePullSecrets:
          - name: gcr-secret
          containers:
          - name: smartconnect-provider-etl
            image: gcr.io/padas-app/etl/smartconnect-provider:<<smartconnect-provider-version>>
            env:
            - name: DAS_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: site-configmap
                  key: SMARTCONNECT_PROVIDER_DAS_API
            - name: DAS_TOKEN
              valueFrom:
                configMapKeyRef:
                  name: site-configmap
                  key: SMARTCONNECT_PROVIDER_DAS_TOKEN

          restartPolicy: Never