apiVersion: v1
kind: ConfigMap
metadata:
  namespace: <<infra-namespace>>
  name: prometheus-configmap
data:
  rules.yaml: |-
    groups:
    - name: elasticsearch.alert.rules
      rules:
      - alert: ElasticsearchClusterYellow
        expr: elasticsearch_cluster_health_status{color="yellow"}==1
        for: 2m
        labels:
          severity: warning
        annotations:
          description: 'Elasticsearch cluster status is YELLOW'
      - alert: ElasticsearchClusterRed
        expr: elasticsearch_cluster_health_status{color="red"}==1
        for: 2m
        labels:
          severity: page
        annotations:
          description: 'Elasticsearch cluster status is RED'
      - alert: ElasticsearchJvmUsageHigh
        expr: |
          (
            elasticsearch_jvm_memory_used_bytes{area="heap", es_data_node="true"} /
            elasticsearch_jvm_memory_max_bytes{area="heap", es_data_node="true"}
          ) > 0.85
        for: 10m
        labels:
          severity: warning
        annotations:
          description: 'Elasticsearch JVM heap usage is over 85%'
      - alert: ElasticsearchJvmUsageCritical
        expr: |
          (
            elasticsearch_jvm_memory_used_bytes{area="heap", es_data_node="true"} /
            elasticsearch_jvm_memory_max_bytes{area="heap", es_data_node="true"}
          ) > 0.9
        for: 10m
        labels:
          severity: page
        annotations:
          description: 'Elasticsearch JVM heap usage is over 90%'
