apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: prometheus
spec:
  serviceName: "prometheus"
  updateStrategy:
    type: RollingUpdate
  replicas: 1
  template:
    metadata:
      labels:
        component: prometheus
    spec:
      imagePullSecrets:
        - name: infra-secret
      securityContext:
        runAsUser: 1000
        fsGroup: 2000
      containers:
      - image: gcr.io/ss-infrastructure/baseimages/monitoring/prometheus:<<monitoring-version>>
        name: prometheus
        resources:
          requests:
            cpu: "100m"
            memory: 1000Mi
          limits:
            cpu: "100m"
            memory: 1000Mi
        readinessProbe:
          httpGet:
            path: /#/ready
            port: 9090
          initialDelaySeconds: 10
          timeoutSeconds: 30
        livenessProbe:
          httpGet:
            path: /-/healthy
            port: 9090
          initialDelaySeconds: 30
          timeoutSeconds: 30
        volumeMounts:
        - mountPath: /prometheus
          name: prometheus-data
        - mountPath: /project.specific.rules
          name: project-specific-rules
        env:
        - name: ALERTMANAGER_URL
          value: http://alertmanager:9093
        - name: ENVIRONMENT_NAME
          value: <<cluster-name>>

      - name: prometheus-server-configmap-reload
        image: "jimmidyson/configmap-reload:v0.2.2"
        imagePullPolicy: "IfNotPresent"
        args:
          - --volume-dir=/project.specific.rules
          - --webhook-url=http://localhost:9090/-/reload
        volumeMounts:
          - name: project-specific-rules
            mountPath: /project.specific.rules
            readOnly: true
        resources:
          limits:
            cpu: 10m
            memory: 10Mi
          requests:
            cpu: 10m
            memory: 10Mi
      volumes:
      - name: project-specific-rules
        configMap:
          name: prometheus-configmap
        items:
        - key: rules.yaml
          path: rules.yaml
  volumeClaimTemplates:
  - metadata:
      name: prometheus-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: ssd 
      resources:
        requests:
          storage: 30Gi
      selector:
        matchLabels:
          component: prometheus

