apiVersion: v1
kind: Service
metadata:
  name: grafana
spec:
  ports:
  - port: 3000
    targetPort: 3000
  selector:
    component: grafana
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: grafana
spec:
  template:
    metadata:
      labels:
        component: grafana
    spec:
      imagePullSecrets:
        - name: gcr-secret
      containers:
      - image: gcr.io/padas-app/utility/grafana:<<grafana-version>>
        name: grafana
        resources:
          requests:
            cpu: "25m"
          limits:
            cpu: "1"
        env:
        - name: PROMETHEUS_URL
          valueFrom:
            configMapKeyRef:
              name: default-configmap
              key: PROMETHEUS_URL