apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: nginx
spec:
  template:
    metadata:
      labels:
        das.component: nginx
    spec:
      imagePullSecrets:
        - name: gcr-secret
      containers:
      - image: gcr.io/padas-app/nginx:<<git-utility-sha>>
        name: das-nginx
        resources:
          requests:
            cpu: "75m"
        ports:
        - containerPort: 443
        - containerPort: 8000
        - containerPort: 9001
        env:
        - name: WEB_SERVICE_NAME
          valueFrom:
            configMapKeyRef:
              name: default-configmap
              key: WEB_SERVICE_NAME
        - name: BUNDLE_CRT
          valueFrom:
            configMapKeyRef:
              name: default-configmap
              key: BUNDLE_CRT
        - name: PAMDAS_ORG_PRIVATE_KEY_PEM
          valueFrom:
            configMapKeyRef:
              name: default-configmap
              key: PAMDAS_ORG_PRIVATE_KEY_PEM