apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: worker
spec:
  template:
    metadata:
      labels:
        das.component: worker
    spec:
      imagePullSecrets:
        - name: gcr-secret
      containers:
      - image: gcr.io/padas-app/worker:<<git-server-sha>>
        name: das-worker
        resources:
          requests:
            cpu: "100m"
        env:
        - name: API_HOST
          valueFrom:
            configMapKeyRef:
              name: default-configmap
              key: API_HOST
        - name: API_PORT
          valueFrom:
            configMapKeyRef:
              name: default-configmap
              key: API_PORT
