# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-20 22:32
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('model', models.CharField(max_length=50)),
                ('field', models.CharField(max_length=40)),
                ('value', models.CharField(blank=True, max_length=40)),
                ('display', models.CharField(blank=True, max_length=100)),
                ('sub_choice_of', models.ManyToManyField(blank=True, to='core.Choice')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='choice',
            unique_together=set([('model', 'field', 'value')]),
        ),
    ]
