# Generated by Django 2.0.2 on 2018-07-07 17:43

from django.db import migrations, models
import uuid
import os

util_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), 'sql', 'util'))

util_files = ['aggregate.sql',
              'get_current_timeofday.sql',
              'get_foreign_key_cmd_by_db_owner.sql',
              'get_primary_key_columns.sql',
              'get_primary_key_where_clause.sql',
              'get_table_column.sql',
              'get_table_column_and_type.sql',
              'get_table_foreign_key.sql',
              'get_table_index.sql',
              'get_update_table_columns.sql',
              'get_update_where_clause.sql',
              'is_schema_exists.sql',
              'update_sequence.sql',
              'update_all_sequence.sql',
              'export_data.sql',
              'view.sql'
              ]

SQL_COMMANDS = ""
for util in util_files:
    with open(os.path.join(util_dir, util)) as file:
        SQL_COMMANDS += "\n" + file.read()


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0005_auto_20161007_1303'),
    ]

    operations = [
        migrations.RunSQL(SQL_COMMANDS, "SELECT 1;"),
        migrations.CreateModel(
            name='QueryHistory',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('pid', models.IntegerField(verbose_name='The OS process id')),
                ('elapsed', models.DurationField()),
                ('wait_event', models.CharField(blank=True, max_length=100, null=True)),
                ('cpu_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('mem_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('query', models.TextField(db_index=True)),
                ('digest', models.CharField(db_index=True, max_length=512, verbose_name='The sha1 digest of the query field')),
            ],
            options={
                'verbose_name': 'query history',
                'verbose_name_plural': 'query histories',
            },
        ),
        migrations.AlterIndexTogether(
            name='queryhistory',
            index_together={('pid', 'digest', 'updated_at')},
        ),
    ]
