# Generated by Django 3.2.19 on 2023-08-03 18:12

import django_multitenant.mixins
import django_multitenant.models

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0005_auto_20161007_1303"),
    ]

    operations = [
        migrations.CreateModel(
            name="DASTenant",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("domain", models.CharField(max_length=100)),
            ],
            options={
                "abstract": False,
            },
            bases=(django_multitenant.mixins.TenantModelMixin, models.Model),
            managers=[
                ("objects", django_multitenant.models.TenantManager()),
            ],
        ),
    ]
