# Generated by Django 3.2.19 on 2023-08-11 06:41

from django.db import migrations


def _migrate_oauth_applications(apps, schema_editor):
    Application = apps.get_model("oauth2_provider", "Application")
    DASApplication = apps.get_model("core", "DASApplication")

    for app in Application.objects.all():
        DASApplication.objects.create(
            client_id=app.client_id,
            client_type=app.client_type,
            user_id=app.user_id,
            client_secret=app.client_secret,
            redirect_uris=app.redirect_uris,
            post_logout_redirect_uris=app.post_logout_redirect_uris,
            authorization_grant_type=app.authorization_grant_type,
            name=app.name,
            skip_authorization=app.skip_authorization,
            created=app.created,
            updated=app.updated,
            algorithm=app.algorithm,
        )


def _migrate_oauth_grants(apps, schema_editor):
    DASApplication = apps.get_model("core", "DASApplication")
    DASGrant = apps.get_model("core", "DASGrant")
    Grant = apps.get_model("oauth2_provider", "Grant")

    for grant in Grant.objects.all():
        das_application = DASApplication.objects.get(client_id=grant.application.client_id)

        DASGrant.objects.create(
            user=grant.user,
            code=grant.code,
            application=das_application,
            expires=grant.expires,
            redirect_uri=grant.redirect_uri,
            scope=grant.scope,
            created=grant.created,
            updated=grant.updated,
            code_challenge=grant.code_challenge,
            code_challenge_method=grant.code_challenge_method,
            nonce=grant.nonce,
            claims=grant.claims,
        )


def _migrate_oauth_id_tokens(apps, schema_editor):
    DASApplication = apps.get_model("core", "DASApplication")
    DASIDToken = apps.get_model("core", "DASIDToken")
    IdToken = apps.get_model("oauth2_provider", "IdToken")

    for id_token in IdToken.objects.all():
        das_application = None
        if id_token.application:
            das_application = DASApplication.objects.get(client_id=id_token.application.client_id)

        DASIDToken.objects.create(
            user=id_token.user,
            jti=id_token.jti,
            application=das_application,
            expires=id_token.expires,
            scope=id_token.scope,
            created=id_token.created,
            updated=id_token.updated,
        )


def _migrate_oauth_access_tokens(apps, schema_editor):
    AccessToken = apps.get_model("oauth2_provider", "AccessToken")
    DASAccessToken = apps.get_model("core", "DASAccessToken")
    DASApplication = apps.get_model("core", "DASApplication")
    DASIDToken = apps.get_model("core", "DASIDToken")
    DASRefreshToken = apps.get_model("core", "DASRefreshToken")

    for access_token in AccessToken.objects.all():
        das_application = DASApplication.objects.get(client_id=access_token.application.client_id)

        das_id_token = None
        if access_token.id_token:
            das_id_token = DASIDToken.objects.get(jti=access_token.id_token.jti)

        das_access_token = DASAccessToken.objects.create(
            user=access_token.user,
            token=access_token.token,
            id_token=das_id_token,
            application=das_application,
            expires=access_token.expires,
            scope=access_token.scope,
            created=access_token.created,
            updated=access_token.updated,
        )

        refresh_token = access_token.source_refresh_token
        if refresh_token:
            das_refresh_token = DASRefreshToken.objects.create(
                user=refresh_token.user,
                token=refresh_token.token,
                application=das_application,
                access_token=das_access_token,
                created=refresh_token.created,
                updated=refresh_token.updated,
                revoked=refresh_token.revoked,
            )

            das_access_token.source_refresh_token = das_refresh_token
            das_access_token.save()


def _migrate_oauth_refresh_tokens(apps, schema_editor):
    DASAccessToken = apps.get_model("core", "DASAccessToken")
    DASApplication = apps.get_model("core", "DASApplication")
    DASRefreshToken = apps.get_model("core", "DASRefreshToken")
    RefreshToken = apps.get_model("oauth2_provider", "RefreshToken")

    for refresh_token in RefreshToken.objects.all():
        das_application = DASApplication.objects.get(client_id=refresh_token.application.client_id)
        das_access_token = DASAccessToken.objects.get(token=refresh_token.access_token.token)

        DASRefreshToken.objects.create(
            user=refresh_token.user,
            token=refresh_token.token,
            application=das_application,
            access_token=das_access_token,
            created=refresh_token.created,
            updated=refresh_token.updated,
            revoked=refresh_token.revoked,
        )


def migrate_oauth_models(apps, schema_editor):
    _migrate_oauth_applications(apps, schema_editor)
    _migrate_oauth_grants(apps, schema_editor)
    _migrate_oauth_id_tokens(apps, schema_editor)
    _migrate_oauth_access_tokens(apps, schema_editor)
    _migrate_oauth_refresh_tokens(apps, schema_editor)


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_add_oauth_custom_models"),
        ("das_server", "0002_er_track"),
    ]

    operations = [
        migrations.RunPython(
            code=migrate_oauth_models,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
