# Generated by Django 3.2.19 on 2023-08-11 06:41


from django.db import migrations


def migrate_oauth_models(apps, schema_editor):
    AccessToken = apps.get_model("oauth2_provider", "AccessToken")
    Application = apps.get_model("oauth2_provider", "Application")
    Grant = apps.get_model("oauth2_provider", "Grant")
    IdToken = apps.get_model("oauth2_provider", "IdToken")
    RefreshToken = apps.get_model("oauth2_provider", "RefreshToken")

    DASAccessToken = apps.get_model("core", "DASAccessToken")
    DASApplication = apps.get_model("core", "DASApplication")
    DASGrant = apps.get_model("core", "DASGrant")
    DASIDToken = apps.get_model("core", "DASIDToken")
    DASRefreshToken = apps.get_model("core", "DASRefreshToken")

    created_das_applications = []
    das_access_tokens = {}

    def _get_application_id_from_created_apps_list(client_id):
        results = list(filter(lambda application: application.client_id == client_id, created_das_applications))
        if results:
            return results[0].id
        return None

    def _migrate_oauth_applications():
        das_applications = []
        for app in Application.objects.values():
            del app["id"]
            das_applications.append(DASApplication(**app))
        return DASApplication.objects.bulk_create(das_applications)

    def _migrate_oauth_grants():
        das_grants = []
        for grant in Grant.objects.values(
            "application__client_id",
            "application_id",
            "claims",
            "code",
            "code_challenge",
            "code_challenge_method",
            "created",
            "expires",
            "nonce",
            "redirect_uri",
            "scope",
            "updated",
            "user_id",
        ):
            grant["application_id"] = _get_application_id_from_created_apps_list(grant["application__client_id"])
            del grant["application__client_id"]

            das_grants.append(DASGrant(**grant))
        DASGrant.objects.bulk_create(das_grants)

    def _migrate_oauth_id_tokens():
        das_id_tokens = []
        for id_token in IdToken.objects.values(
            "application__client_id",
            "application_id",
            "created",
            "expires",
            "jti",
            "scope",
            "updated",
            "user_id",
        ):
            id_token["application_id"] = _get_application_id_from_created_apps_list(id_token["application__client_id"])
            del id_token["application__client_id"]

            das_id_tokens.append(DASIDToken(**id_token))
        DASIDToken.objects.bulk_create(das_id_tokens)

    def _migrate_oauth_access_tokens_with():
        das_access_tokens = []
        for access_token in AccessToken.objects.values(
            "application__client_id",
            "application_id",
            "created",
            "expires",
            "id_token",
            "id_token__jti",
            "scope",
            "token",
            "updated",
            "user_id",
        ):
            access_token["application_id"] = _get_application_id_from_created_apps_list(
                access_token["application__client_id"]
            )
            del access_token["application__client_id"]

            access_token["id_token"] = None
            if access_token["id_token__jti"]:
                access_token["id_token"] = DASIDToken.objects.get(jti=access_token["id_token__jti"])
            del access_token["id_token__jti"]

            das_access_tokens.append(DASAccessToken(**access_token))
        tokens = DASAccessToken.objects.bulk_create(das_access_tokens)
        return {at.token: at.id for at in tokens}

    def _migrate_oauth_refresh_tokens():
        das_refresh_tokens = []

        for refresh_token in RefreshToken.objects.values(
            "access_token_id",
            "access_token__token",
            "application__client_id",
            "application_id",
            "created",
            "revoked",
            "token",
            "updated",
            "user_id",
        ):
            refresh_token["application_id"] = _get_application_id_from_created_apps_list(
                refresh_token["application__client_id"]
            )
            del refresh_token["application__client_id"]

            try:
                refresh_token["access_token_id"] = das_access_tokens[refresh_token["access_token__token"]]
            except KeyError:
                refresh_token["access_token_id"] = None
            finally:
                del refresh_token["access_token__token"]

            das_refresh_tokens.append(DASRefreshToken(**refresh_token))
        DASRefreshToken.objects.bulk_create(das_refresh_tokens)

    created_das_applications = _migrate_oauth_applications()
    _migrate_oauth_grants()
    _migrate_oauth_id_tokens()
    das_access_tokens = _migrate_oauth_access_tokens_with()
    _migrate_oauth_refresh_tokens()


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_add_oauth_custom_models"),
        ("das_server", "0002_er_track"),
    ]

    operations = [
        migrations.RunPython(
            code=migrate_oauth_models,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
