# Generated by Django 3.2.19 on 2023-09-26 00:09

import django_multitenant.fields

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_migrate_oauth_tables_to_das_custom_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="dasaccesstoken",
            name="das_tenant",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="core.dastenant"
            ),
        ),
        migrations.AddField(
            model_name="dasapplication",
            name="das_tenant",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="core.dastenant"
            ),
        ),
        migrations.AddField(
            model_name="dasgrant",
            name="das_tenant",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="core.dastenant"
            ),
        ),
        migrations.AddField(
            model_name="dasidtoken",
            name="das_tenant",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="core.dastenant"
            ),
        ),
        migrations.AddField(
            model_name="dasrefreshtoken",
            name="das_tenant",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="core.dastenant"
            ),
        ),
        migrations.AlterField(
            model_name="dasaccesstoken",
            name="application",
            field=django_multitenant.fields.TenantForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="core.dasapplication"
            ),
        ),
        migrations.AlterField(
            model_name="dasgrant",
            name="application",
            field=django_multitenant.fields.TenantForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.dasapplication"
            ),
        ),
        migrations.AlterField(
            model_name="dasidtoken",
            name="application",
            field=django_multitenant.fields.TenantForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="core.dasapplication"
            ),
        ),
        migrations.AlterField(
            model_name="dasrefreshtoken",
            name="application",
            field=django_multitenant.fields.TenantForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.dasapplication"
            ),
        ),
    ]
