# Generated by Django 3.2.19 on 2023-09-26 00:30
import logging

from django.conf import settings
from django.db import migrations

from core.utils import DASTenantManagement, update_tenant_models

logger = logging.getLogger(__name__)

core_models = ["DASApplication", "DASAccessToken", "DASGrant", "DASIDToken", "DASRefreshToken"]


def populate_tenant_into_models(apps, schema_editor):
    class_models = [apps.get_model("core", model_name) for model_name in core_models]

    das_tenant_management = DASTenantManagement(domain=settings.SERVER_FQDN)
    tenant = das_tenant_management.get_or_create_tenant()

    if tenant:
        update_tenant_models(models=class_models, tenant=tenant)
    else:
        logger.error("DAS Tenant not found.")


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_add_das_tenant_columns_to_oauth_models"),
    ]

    operations = [
        migrations.RunPython(
            populate_tenant_into_models,
            migrations.RunPython.noop,
        ),
    ]
