# Generated by Django 3.2.19 on 2023-10-02 03:34

from django.db import migrations

from utils.migrations.update_primary_key import add_tenant_to_primary_key

core_models = ["DASApplication", "DASAccessToken", "DASGrant", "DASIDToken", "DASRefreshToken"]


def regenerate_primary_keys(apps, schema_editor):
    add_tenant_to_primary_key("core", core_models)


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_populate_oauth_models_with_tenant"),
    ]

    operations = [
        migrations.RunPython(code=regenerate_primary_keys, reverse_code=migrations.RunPython.noop),
    ]
