# Generated by Django 3.2.21 on 2023-10-23 16:25

import django_multitenant.fields

import django.db.models.deletion
from django.db import migrations

import utils.migrations.columns


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0011_regenerate_primary_keys"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dasaccesstoken",
            name="das_tenant",
            field=django_multitenant.fields.TenantForeignKey(
                default=utils.migrations.columns.default_tenant_id,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.dastenant",
            ),
        ),
        migrations.AlterField(
            model_name="dasapplication",
            name="das_tenant",
            field=django_multitenant.fields.TenantForeignKey(
                default=utils.migrations.columns.default_tenant_id,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.dastenant",
            ),
        ),
        migrations.AlterField(
            model_name="dasgrant",
            name="das_tenant",
            field=django_multitenant.fields.TenantForeignKey(
                default=utils.migrations.columns.default_tenant_id,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.dastenant",
            ),
        ),
        migrations.AlterField(
            model_name="dasidtoken",
            name="das_tenant",
            field=django_multitenant.fields.TenantForeignKey(
                default=utils.migrations.columns.default_tenant_id,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.dastenant",
            ),
        ),
        migrations.AlterField(
            model_name="dasrefreshtoken",
            name="das_tenant",
            field=django_multitenant.fields.TenantForeignKey(
                default=utils.migrations.columns.default_tenant_id,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.dastenant",
            ),
        ),
    ]
