# Generated by Django 3.2.21 on 2023-11-16 01:58

import django_multitenant.fields
import oauth2_provider.generators

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0012_make_das_tenant_field_required"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dasaccesstoken",
            name="id_token",
            field=django_multitenant.fields.TenantOneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="access_token",
                to="core.DASIDToken",
            ),
        ),
        migrations.AlterField(
            model_name="dasaccesstoken",
            name="source_refresh_token",
            field=django_multitenant.fields.TenantOneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="refreshed_access_token",
                to="core.DASRefreshToken",
            ),
        ),
        migrations.AlterField(
            model_name="dasaccesstoken",
            name="user",
            field=django_multitenant.fields.TenantForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="core_dasaccesstoken",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="dasapplication",
            name="client_id",
            field=models.CharField(default=oauth2_provider.generators.generate_client_id, max_length=100),
        ),
        migrations.AlterField(
            model_name="dasapplication",
            name="user",
            field=django_multitenant.fields.TenantForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="core_dasapplication",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="dasgrant",
            name="user",
            field=django_multitenant.fields.TenantForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="core_dasgrant", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="dasidtoken",
            name="user",
            field=django_multitenant.fields.TenantForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="core_dasidtoken",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="dasrefreshtoken",
            name="access_token",
            field=django_multitenant.fields.TenantOneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="refresh_token",
                to="core.DASAccessToken",
            ),
        ),
        migrations.AlterField(
            model_name="dasrefreshtoken",
            name="user",
            field=django_multitenant.fields.TenantForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="core_dasrefreshtoken",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="dasaccesstoken",
            index=models.Index(fields=["das_tenant", "token"], name="core_dasacc_das_ten_19a210_idx"),
        ),
        migrations.AddIndex(
            model_name="dasapplication",
            index=models.Index(fields=["das_tenant", "client_id"], name="core_dasapp_das_ten_e8a419_idx"),
        ),
        migrations.AddIndex(
            model_name="dasgrant",
            index=models.Index(fields=["das_tenant", "code"], name="core_dasgra_das_ten_1e21e9_idx"),
        ),
        migrations.AddIndex(
            model_name="dasidtoken",
            index=models.Index(fields=["das_tenant", "jti"], name="core_dasidt_das_ten_d76454_idx"),
        ),
        migrations.AddIndex(
            model_name="dasrefreshtoken",
            index=models.Index(fields=["das_tenant", "token"], name="core_dasref_das_ten_8859d5_idx"),
        ),
        migrations.AddConstraint(
            model_name="dasaccesstoken",
            constraint=models.UniqueConstraint(
                fields=("das_tenant", "token"), name="core_dasaccesstoken_unique_token_across_tenants"
            ),
        ),
        migrations.AddConstraint(
            model_name="dasapplication",
            constraint=models.UniqueConstraint(
                fields=("das_tenant", "client_id"), name="core_dasapplication_unique_client_across_tenants"
            ),
        ),
        migrations.AddConstraint(
            model_name="dasgrant",
            constraint=models.UniqueConstraint(
                fields=("das_tenant", "code"), name="core_dasgrant_unique_code_across_tenants"
            ),
        ),
        migrations.AddConstraint(
            model_name="dasidtoken",
            constraint=models.UniqueConstraint(
                fields=("das_tenant", "jti"), name="core_dasidtoken_unique_jti_across_tenants"
            ),
        ),
        migrations.AddConstraint(
            model_name="dasrefreshtoken",
            constraint=models.UniqueConstraint(
                fields=("das_tenant", "token"), name="core_dasrefreshtoken_unique_token_across_tenants"
            ),
        ),
    ]
