# Generated by Django 3.2.21 on 2023-11-20 01:06

from django.db import migrations

import core.models.oauth
import utils.models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0013_auto_20231115_1758"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="dasaccesstoken",
            managers=[
                ("objects", utils.models.CommonTenantManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="dasapplication",
            managers=[
                ("objects", core.models.oauth.DASApplicationManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="dasgrant",
            managers=[
                ("objects", utils.models.CommonTenantManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="dasidtoken",
            managers=[
                ("objects", utils.models.CommonTenantManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="dasrefreshtoken",
            managers=[
                ("objects", utils.models.CommonTenantManager()),
            ],
        ),
    ]
