# Generated by Django 3.2.21 on 2023-11-23 17:56

from django.db import migrations

from utils.migrations.update_primary_key import drop_constraint

APP_NAME = "core"


def drop_constraints(apps, schema_editor):
    drop_constraint(
        app=APP_NAME,
        model="DASAccessToken",
        constraint="core_dasaccesstoken_source_refresh_token_id_key",
    )


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0014_auto_20231119_1706"),
    ]

    operations = [
        migrations.RunPython(code=drop_constraints, reverse_code=migrations.RunPython.noop),
    ]
