# Generated by Django 3.2.21 on 2023-12-03 00:26

from django.db import migrations

import core.models.core


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0015_delete_unique_constraints"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="dastenant",
            managers=[
                ("objects", core.models.core.DASTenantManager()),
            ],
        ),
    ]
