# Generated by Django 3.2.21 on 2024-01-18 21:33
from django.conf import settings
from django.db import migrations, models

from utils.json import load_from_file

SQL = """
DO
$$
    DECLARE
        row                  RECORD;
        old_id               INTEGER;
        new_id               INTEGER;
        temp_content_type_id INTEGER;
        distinct_records     INTEGER;
    BEGIN
        select count(*)
        into distinct_records
        from django_content_type dct
                 full outer join temp_content_type tct on dct.id = tct.id
        where dct is distinct from tct;

        if distinct_records > 0 then
            -- DROP FK
            alter table auth_permission
                drop constraint auth_permission_content_type_id_2f476e4b_fk_django_co;
            alter table django_admin_log
                drop constraint django_admin_log_content_type_id_c4bce8eb_fk_django_co;
            alter table activity_event
                drop constraint activity_event_reported_by_content__81040fb0_fk_django_co;
            alter table activity_eventattachment
                drop constraint activity_eventattach_content_type_id_b6440fce_fk_django_co;
            alter table activity_eventfile
                drop constraint activity_eventfile_usercontent_type_id_b3a3b1ed_fk_django_co;
            alter table activity_patrolfile
                drop constraint activity_patrolfile_usercontent_type_id_031d6880_fk_django_co;
            alter table activity_patrolsegment
                drop constraint activity_patrolsegme_leader_content_type__165f10e0_fk_django_co;
            alter table analyzers_subjectanalyzerresult
                drop constraint analyzers_subjectana_subject_analyzer_con_864bc490_fk_django_co;
            alter table observations_message
                drop constraint observations_message_receiver_content_typ_56719c81_fk_django_co;
            alter table observations_message
                drop constraint observations_message_sender_content_type__ec59feb7_fk_django_co;
            alter table tracking_sourceplugin
                drop constraint tracking_sourceplugi_plugin_type_id_0e392da4_fk_django_co;

            for row in select * from django_content_type order by id
                LOOP
                    select id
                    into temp_content_type_id
                    from temp_content_type
                    where app_label = row.app_label and model = row.model;
                    if temp_content_type_id is null then
                        temp_content_type_id = -1; /* if the content type id does not match a record in the temp_content_type table, move it above 1000 */
                    end if;
                    update django_content_type set id = row.id + 1000 where id = row.id;
                    if row.id <> temp_content_type_id then
                        update django_content_type set id = row.id + 1000 where id = row.id;
                    end if;
                END LOOP;

            for row in select * from django_content_type order by id
                LOOP
                    if row.model <> 'tempcontenttype' then
                        if row.id > 1000 then
                            old_id = row.id - 1000;
                            select id into new_id from temp_content_type where app_label = row.app_label
                                                                           and model = row.model;
                            if new_id is null then
                                new_id = row.id; /* if the content type id does not match a record in the temp_content_type table, move it above 1000 */
                            end if;
                            update django_content_type set id = new_id where id = row.id;
                            update auth_permission set content_type_id = new_id where content_type_id = old_id;
                            update activity_event
                            set reported_by_content_type_id = new_id
                            where reported_by_content_type_id = old_id;
                            update activity_eventattachment set content_type_id = new_id where content_type_id = old_id;
                            update activity_eventfile
                            set usercontent_type_id = new_id
                            where usercontent_type_id = old_id;
                            update activity_patrolfile
                            set usercontent_type_id = new_id
                            where usercontent_type_id = old_id;
                            update activity_patrolsegment
                            set leader_content_type_id = new_id
                            where leader_content_type_id = old_id;
                            update django_admin_log set content_type_id = new_id where content_type_id = old_id;
                            update analyzers_subjectanalyzerresult
                            set subject_analyzer_content_type_id = new_id
                            where subject_analyzer_content_type_id = old_id;
                            update observations_message
                            set sender_content_type_id = new_id
                            where sender_content_type_id = old_id;
                            update observations_message
                            set receiver_content_type_id = new_id
                            where receiver_content_type_id = old_id;
                            update tracking_sourceplugin set plugin_type_id = new_id where plugin_type_id = old_id;
                        end if;
                    end if;
                END LOOP;

        END IF;
    END;
$$
"""

JSON_FILE = f"{settings.BASE_DIR}/core/migrations/data/golden_set_contenttypes.json"


def insert_into_temp_content_type(apps, schema_editor):
    TempContentType = apps.get_model(app_label="core", model_name="TempContentType")
    temps = []
    for bct in load_from_file(file_path=JSON_FILE):
        temps.append(TempContentType(id=bct["pk"], **bct["fields"]))
    TempContentType.objects.bulk_create(temps)


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0048_regenerate_primary_key_act_as_profiles"),
        ("activity", "0176_defaultmanager"),
        ("analyzers", "0054_add_globalforestwatchsubscription_custom_manager"),
        ("choices", "0028_regenerate_pk_choices_models"),
        ("core", "0016_alter_dastenant_managers"),
        ("das_server", "0002_er_track"),
        ("mapping", "0061_regenerate_primary_keys"),
        ("observations", "0166_add_topi_and_meerkat_wildlife_icons"),
        ("reports", "0014_delete_unique_constraints"),
        ("tracking", "0037_custom_through_model_new_subject_excluded_subject_types"),
        ("usercontent", "0012_filecontentrevision_regenerate_pk"),
    ]

    operations = [
        migrations.CreateModel(
            name="TempContentType",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("app_label", models.CharField(max_length=100)),
                ("model", models.CharField(max_length=100, verbose_name="python model class name")),
            ],
            options={
                "verbose_name": "content type",
                "verbose_name_plural": "content types",
                "db_table": "temp_content_type",
                "unique_together": {("app_label", "model")},
            },
        ),
        migrations.RunPython(
            insert_into_temp_content_type,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RunSQL(
            sql=SQL,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.DeleteModel(
            name="TempContentType",
        ),
    ]
