# Generated by Django 3.2.21 on 2024-01-18 21:33
from django.conf import settings
from django.db import migrations, models

from utils.json import load_from_file

SQL = """
CREATE OR REPLACE FUNCTION update_fk_ids(old_id INTEGER, new_id INTEGER) RETURNS VOID AS
$$
BEGIN
    UPDATE auth_permission
    SET content_type_id = new_id
    WHERE content_type_id = old_id;

    UPDATE activity_event
    SET reported_by_content_type_id = new_id
    WHERE reported_by_content_type_id = old_id;

    UPDATE activity_eventattachment
    SET content_type_id = new_id
    WHERE content_type_id = old_id;

    UPDATE activity_eventfile
    SET usercontent_type_id = new_id
    WHERE usercontent_type_id = old_id;

    UPDATE activity_patrolsegment
    SET leader_content_type_id = new_id
    WHERE leader_content_type_id = old_id;

    UPDATE django_admin_log
    SET content_type_id = new_id
    WHERE content_type_id = old_id;

    UPDATE analyzers_subjectanalyzerresult
    SET subject_analyzer_content_type_id = new_id
    WHERE subject_analyzer_content_type_id = old_id;

    UPDATE observations_message
    SET sender_content_type_id = new_id
    WHERE sender_content_type_id = old_id;

    UPDATE tracking_sourceplugin
    SET plugin_type_id = new_id
    WHERE plugin_type_id = old_id;
END;
$$ LANGUAGE plpgsql;

DO
$$
    DECLARE
        row      RECORD;
        old_id   INTEGER;
        new_id   INTEGER;
        last_seq INTEGER;
    BEGIN
        -- DROP FK
        ALTER TABLE auth_permission
            DROP CONSTRAINT IF EXISTS auth_permission_content_type_id_2f476e4b_fk_django_co;
        ALTER TABLE django_admIN_log
            DROP CONSTRAINT IF EXISTS django_admIN_log_content_type_id_c4bce8eb_fk_django_co;
        ALTER TABLE activity_event
            DROP CONSTRAINT activity_event_reported_by_content__81040fb0_fk_django_co;
        ALTER TABLE activity_eventattachment
            DROP CONSTRAINT IF EXISTS activity_eventattach_content_type_id_b6440fce_fk_django_co;
        ALTER TABLE activity_eventfile
            DROP CONSTRAINT IF EXISTS activity_eventfile_usercontent_type_id_b3a3b1ed_fk_django_co;
        ALTER TABLE activity_patrolfile
            DROP CONSTRAINT IF EXISTS activity_patrolfile_usercontent_type_id_031d6880_fk_django_co;
        ALTER TABLE activity_patrolsegment
            DROP CONSTRAINT IF EXISTS activity_patrolsegme_leader_content_type__165f10e0_fk_django_co;
        ALTER TABLE analyzers_subjectanalyzerresult
            DROP CONSTRAINT IF EXISTS analyzers_subjectana_subject_analyzer_con_864bc490_fk_django_co;
        ALTER TABLE observations_message
            DROP CONSTRAINT IF EXISTS observations_message_receiver_content_typ_56719c81_fk_django_co;
        ALTER TABLE observations_message
            DROP CONSTRAINT IF EXISTS observations_message_sender_content_type__ec59feb7_fk_django_co;
        ALTER TABLE trackINg_sourceplugIN
            DROP CONSTRAINT IF EXISTS trackINg_sourceplugi_plugIN_type_id_0e392da4_fk_django_co;

        -- move content types to high id
        FOR row IN SELECT * FROM django_content_type ORDER BY id
            LOOP
                old_id = row.id;
                new_id = old_id + 1000;

                -- UPDATE content type id
                UPDATE django_content_type SET id = new_id WHERE id = old_id;

                -- UPDATE FK
                PERFORM update_fk_ids(old_id, new_id);
            END LOOP;

        -- Move content type to id from golden SET
        FOR row IN SELECT * FROM django_content_type ORDER BY id
            LOOP
                old_id = row.id;

                SELECT id
                INTO new_id
                FROM temp_content_type ct
                WHERE ct.app_label = row.app_label
                  AND ct.model = row.model;

                IF new_id IS NOT NULL THEN
                    -- UPDATE content type id
                    UPDATE django_content_type SET id = new_id WHERE id = old_id;

                    -- UPDATE FK
                    PERFORM update_fk_ids(old_id, new_id);
                ELSE
                    RAISE NOTICE 'ROW NOT FOUND: %', row;
                END IF;
            END LOOP;

        SELECT id
        INTO last_seq
        FROM django_content_type
        WHERE id < 1000
          AND model != 'tempcontenttype'
        ORDER BY id DESC
        LIMIT 1;

        PERFORM SETVAL('django_content_type_id_seq', last_seq + 1, FALSE);
    END;
$$
"""

JSON_FILE = f"{settings.BASE_DIR}/core/migrations/data/golden_set_contenttypes.json"


def insert_into_temp_content_type(apps, schema_editor):
    TempContentType = apps.get_model(app_label="core", model_name="TempContentType")
    temps = []
    for bct in load_from_file(file_path=JSON_FILE):
        temps.append(TempContentType(id=bct["pk"], **bct["fields"]))
    TempContentType.objects.bulk_create(temps)


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0048_regenerate_primary_key_act_as_profiles"),
        ("activity", "0176_defaultmanager"),
        ("analyzers", "0054_add_globalforestwatchsubscription_custom_manager"),
        ("choices", "0028_regenerate_pk_choices_models"),
        ("core", "0016_alter_dastenant_managers"),
        ("das_server", "0002_er_track"),
        ("mapping", "0061_regenerate_primary_keys"),
        ("observations", "0166_add_topi_and_meerkat_wildlife_icons"),
        ("reports", "0014_delete_unique_constraints"),
        ("tracking", "0037_custom_through_model_new_subject_excluded_subject_types"),
        ("usercontent", "0012_filecontentrevision_regenerate_pk"),
    ]

    operations = [
        migrations.CreateModel(
            name="TempContentType",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("app_label", models.CharField(max_length=100)),
                ("model", models.CharField(max_length=100, verbose_name="python model class name")),
            ],
            options={
                "verbose_name": "content type",
                "verbose_name_plural": "content types",
                "db_table": "temp_content_type",
                "unique_together": {("app_label", "model")},
            },
        ),
        migrations.RunPython(
            insert_into_temp_content_type,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RunSQL(
            sql=SQL,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.DeleteModel(
            name="TempContentType",
        ),
    ]
