# Generated by Django 3.2.21 on 2024-01-18 21:33

from django.db import migrations, models

base_content_types = [
    {"model": "core.tempcontenttype", "pk": 1, "fields": {"app_label": "accounts", "model": "permissionset"}},
    {"model": "core.tempcontenttype", "pk": 2, "fields": {"app_label": "accounts", "model": "permissionsetpermission"}},
    {"model": "core.tempcontenttype", "pk": 3, "fields": {"app_label": "accounts", "model": "user"}},
    {"model": "core.tempcontenttype", "pk": 4, "fields": {"app_label": "accounts", "model": "useragreement"}},
    {"model": "core.tempcontenttype", "pk": 5, "fields": {"app_label": "accounts", "model": "eula"}},
    {"model": "core.tempcontenttype", "pk": 6, "fields": {"app_label": "admin", "model": "logentry"}},
    {"model": "core.tempcontenttype", "pk": 7, "fields": {"app_label": "auth", "model": "permission"}},
    {"model": "core.tempcontenttype", "pk": 8, "fields": {"app_label": "auth", "model": "group"}},
    {"model": "core.tempcontenttype", "pk": 9, "fields": {"app_label": "contenttypes", "model": "contenttype"}},
    {"model": "core.tempcontenttype", "pk": 10, "fields": {"app_label": "sessions", "model": "session"}},
    {"model": "core.tempcontenttype", "pk": 11, "fields": {"app_label": "oauth2_provider", "model": "application"}},
    {"model": "core.tempcontenttype", "pk": 12, "fields": {"app_label": "oauth2_provider", "model": "grant"}},
    {"model": "core.tempcontenttype", "pk": 13, "fields": {"app_label": "oauth2_provider", "model": "accesstoken"}},
    {"model": "core.tempcontenttype", "pk": 14, "fields": {"app_label": "oauth2_provider", "model": "refreshtoken"}},
    {"model": "core.tempcontenttype", "pk": 15, "fields": {"app_label": "oauth2_provider", "model": "idtoken"}},
    {"model": "core.tempcontenttype", "pk": 16, "fields": {"app_label": "observations", "model": "sourcegroup"}},
    {"model": "core.tempcontenttype", "pk": 17, "fields": {"app_label": "observations", "model": "sourceprovider"}},
    {"model": "core.tempcontenttype", "pk": 18, "fields": {"app_label": "observations", "model": "source"}},
    {"model": "core.tempcontenttype", "pk": 19, "fields": {"app_label": "observations", "model": "observation"}},
    {"model": "core.tempcontenttype", "pk": 20, "fields": {"app_label": "observations", "model": "subjectsource"}},
    {
        "model": "core.tempcontenttype",
        "pk": 21,
        "fields": {"app_label": "observations", "model": "subjectsourcesummary"},
    },
    {"model": "core.tempcontenttype", "pk": 22, "fields": {"app_label": "observations", "model": "subjecttype"}},
    {"model": "core.tempcontenttype", "pk": 23, "fields": {"app_label": "observations", "model": "subjectsubtype"}},
    {
        "model": "core.tempcontenttype",
        "pk": 24,
        "fields": {"app_label": "observations", "model": "subjecttracksegmentfilter"},
    },
    {"model": "core.tempcontenttype", "pk": 25, "fields": {"app_label": "observations", "model": "subjectgroup"}},
    {"model": "core.tempcontenttype", "pk": 26, "fields": {"app_label": "observations", "model": "subject"}},
    {"model": "core.tempcontenttype", "pk": 27, "fields": {"app_label": "observations", "model": "subjectsummary"}},
    {
        "model": "core.tempcontenttype",
        "pk": 28,
        "fields": {"app_label": "observations", "model": "subjectpositionsummary"},
    },
    {"model": "core.tempcontenttype", "pk": 29, "fields": {"app_label": "observations", "model": "commonname"}},
    {"model": "core.tempcontenttype", "pk": 30, "fields": {"app_label": "observations", "model": "subjectstatus"}},
    {
        "model": "core.tempcontenttype",
        "pk": 31,
        "fields": {"app_label": "observations", "model": "subjectstatuslatest"},
    },
    {"model": "core.tempcontenttype", "pk": 32, "fields": {"app_label": "observations", "model": "region"}},
    {"model": "core.tempcontenttype", "pk": 33, "fields": {"app_label": "observations", "model": "socketclient"}},
    {"model": "core.tempcontenttype", "pk": 34, "fields": {"app_label": "observations", "model": "usersession"}},
    {
        "model": "core.tempcontenttype",
        "pk": 35,
        "fields": {"app_label": "observations", "model": "subjectmaximumspeed"},
    },
    {"model": "core.tempcontenttype", "pk": 36, "fields": {"app_label": "observations", "model": "gpxtrackfile"}},
    {"model": "core.tempcontenttype", "pk": 37, "fields": {"app_label": "observations", "model": "message"}},
    {"model": "core.tempcontenttype", "pk": 38, "fields": {"app_label": "observations", "model": "announcement"}},
    {
        "model": "core.tempcontenttype",
        "pk": 39,
        "fields": {"app_label": "observations", "model": "latestobservationsource"},
    },
    {"model": "core.tempcontenttype", "pk": 40, "fields": {"app_label": "analyzers", "model": "subjectanalyzerresult"}},
    {"model": "core.tempcontenttype", "pk": 41, "fields": {"app_label": "analyzers", "model": "observationannotator"}},
    {
        "model": "core.tempcontenttype",
        "pk": 42,
        "fields": {"app_label": "analyzers", "model": "immobilityanalyzerconfig"},
    },
    {
        "model": "core.tempcontenttype",
        "pk": 43,
        "fields": {"app_label": "analyzers", "model": "geofenceanalyzerconfig"},
    },
    {
        "model": "core.tempcontenttype",
        "pk": 44,
        "fields": {"app_label": "analyzers", "model": "featureproximityanalyzerconfig"},
    },
    {
        "model": "core.tempcontenttype",
        "pk": 45,
        "fields": {"app_label": "analyzers", "model": "subjectproximityanalyzerconfig"},
    },
    {
        "model": "core.tempcontenttype",
        "pk": 46,
        "fields": {"app_label": "analyzers", "model": "environmentalsubjectanalyzerconfig"},
    },
    {
        "model": "core.tempcontenttype",
        "pk": 47,
        "fields": {"app_label": "analyzers", "model": "lowspeedpercentileanalyzerconfig"},
    },
    {
        "model": "core.tempcontenttype",
        "pk": 48,
        "fields": {"app_label": "analyzers", "model": "lowspeedwilcoxanalyzerconfig"},
    },
    {"model": "core.tempcontenttype", "pk": 49, "fields": {"app_label": "analyzers", "model": "subjectspeedprofile"}},
    {"model": "core.tempcontenttype", "pk": 50, "fields": {"app_label": "analyzers", "model": "speeddistro"}},
    {
        "model": "core.tempcontenttype",
        "pk": 51,
        "fields": {"app_label": "analyzers", "model": "globalforestwatchsubscription"},
    },
    {"model": "core.tempcontenttype", "pk": 52, "fields": {"app_label": "tracking", "model": "sourceplugin"}},
    {"model": "core.tempcontenttype", "pk": 53, "fields": {"app_label": "tracking", "model": "savannahplugin"}},
    {"model": "core.tempcontenttype", "pk": 54, "fields": {"app_label": "tracking", "model": "demosourceplugin"}},
    {"model": "core.tempcontenttype", "pk": 55, "fields": {"app_label": "tracking", "model": "inreachplugin"}},
    {"model": "core.tempcontenttype", "pk": 56, "fields": {"app_label": "tracking", "model": "awthttpplugin"}},
    {"model": "core.tempcontenttype", "pk": 57, "fields": {"app_label": "tracking", "model": "inreachkmlplugin"}},
    {
        "model": "core.tempcontenttype",
        "pk": 58,
        "fields": {"app_label": "tracking", "model": "skygisticssatelliteplugin"},
    },
    {"model": "core.tempcontenttype", "pk": 59, "fields": {"app_label": "tracking", "model": "firmsplugin"}},
    {"model": "core.tempcontenttype", "pk": 60, "fields": {"app_label": "tracking", "model": "awetelemetryplugin"}},
    {"model": "core.tempcontenttype", "pk": 61, "fields": {"app_label": "tracking", "model": "spidertracksplugin"}},
    {"model": "core.tempcontenttype", "pk": 62, "fields": {"app_label": "tracking", "model": "sirtrackplugin"}},
    {"model": "core.tempcontenttype", "pk": 63, "fields": {"app_label": "tracking", "model": "vectronicsplugin"}},
    {"model": "core.tempcontenttype", "pk": 64, "fields": {"app_label": "tracking", "model": "awtplugin"}},
    {
        "model": "core.tempcontenttype",
        "pk": 65,
        "fields": {"app_label": "tracking", "model": "sourceproviderconfiguration"},
    },
    {"model": "core.tempcontenttype", "pk": 66, "fields": {"app_label": "mapping", "model": "map"}},
    {"model": "core.tempcontenttype", "pk": 67, "fields": {"app_label": "mapping", "model": "tilelayer"}},
    {"model": "core.tempcontenttype", "pk": 68, "fields": {"app_label": "mapping", "model": "featuretype"}},
    {"model": "core.tempcontenttype", "pk": 69, "fields": {"app_label": "mapping", "model": "featureset"}},
    {"model": "core.tempcontenttype", "pk": 70, "fields": {"app_label": "mapping", "model": "featuresetfeaturetype"}},
    {"model": "core.tempcontenttype", "pk": 71, "fields": {"app_label": "mapping", "model": "spatialfile"}},
    {"model": "core.tempcontenttype", "pk": 72, "fields": {"app_label": "mapping", "model": "polygonfeature"}},
    {"model": "core.tempcontenttype", "pk": 73, "fields": {"app_label": "mapping", "model": "linefeature"}},
    {"model": "core.tempcontenttype", "pk": 74, "fields": {"app_label": "mapping", "model": "pointfeature"}},
    {"model": "core.tempcontenttype", "pk": 75, "fields": {"app_label": "mapping", "model": "spatialfeaturegroup"}},
    {
        "model": "core.tempcontenttype",
        "pk": 76,
        "fields": {"app_label": "mapping", "model": "spatialfeaturegroupquery"},
    },
    {
        "model": "core.tempcontenttype",
        "pk": 77,
        "fields": {"app_label": "mapping", "model": "spatialfeaturegroupstatic"},
    },
    {"model": "core.tempcontenttype", "pk": 78, "fields": {"app_label": "mapping", "model": "displaycategory"}},
    {"model": "core.tempcontenttype", "pk": 79, "fields": {"app_label": "mapping", "model": "spatialfeaturetypetag"}},
    {"model": "core.tempcontenttype", "pk": 80, "fields": {"app_label": "mapping", "model": "spatialfeaturetype"}},
    {"model": "core.tempcontenttype", "pk": 81, "fields": {"app_label": "mapping", "model": "spatialfeaturefile"}},
    {"model": "core.tempcontenttype", "pk": 82, "fields": {"app_label": "mapping", "model": "spatialfeaturerevision"}},
    {"model": "core.tempcontenttype", "pk": 83, "fields": {"app_label": "mapping", "model": "spatialfeature"}},
    {"model": "core.tempcontenttype", "pk": 84, "fields": {"app_label": "mapping", "model": "arcgisgroup"}},
    {"model": "core.tempcontenttype", "pk": 85, "fields": {"app_label": "mapping", "model": "arcgisconfiguration"}},
    {"model": "core.tempcontenttype", "pk": 86, "fields": {"app_label": "mapping", "model": "arcgisitem"}},
    {"model": "core.tempcontenttype", "pk": 87, "fields": {"app_label": "activity", "model": "community"}},
    {"model": "core.tempcontenttype", "pk": 88, "fields": {"app_label": "activity", "model": "eventclass"}},
    {"model": "core.tempcontenttype", "pk": 89, "fields": {"app_label": "activity", "model": "eventfactor"}},
    {"model": "core.tempcontenttype", "pk": 90, "fields": {"app_label": "activity", "model": "eventcategory"}},
    {"model": "core.tempcontenttype", "pk": 91, "fields": {"app_label": "activity", "model": "eventtype"}},
    {
        "model": "core.tempcontenttype",
        "pk": 92,
        "fields": {"app_label": "activity", "model": "refreshrecreateeventdetailview"},
    },
    {"model": "core.tempcontenttype", "pk": 93, "fields": {"app_label": "activity", "model": "eventrelationshiptype"}},
    {"model": "core.tempcontenttype", "pk": 94, "fields": {"app_label": "activity", "model": "eventfilerevision"}},
    {"model": "core.tempcontenttype", "pk": 95, "fields": {"app_label": "activity", "model": "eventfile"}},
    {"model": "core.tempcontenttype", "pk": 96, "fields": {"app_label": "activity", "model": "eventrelationship"}},
    {"model": "core.tempcontenttype", "pk": 97, "fields": {"app_label": "activity", "model": "eventrevision"}},
    {"model": "core.tempcontenttype", "pk": 98, "fields": {"app_label": "activity", "model": "event"}},
    {"model": "core.tempcontenttype", "pk": 99, "fields": {"app_label": "activity", "model": "eventrelatedsegments"}},
    {"model": "core.tempcontenttype", "pk": 100, "fields": {"app_label": "activity", "model": "eventrelatedsubject"}},
    {
        "model": "core.tempcontenttype",
        "pk": 101,
        "fields": {"app_label": "activity", "model": "eventattachmentrevision"},
    },
    {"model": "core.tempcontenttype", "pk": 102, "fields": {"app_label": "activity", "model": "eventattachment"}},
    {"model": "core.tempcontenttype", "pk": 103, "fields": {"app_label": "activity", "model": "eventnoterevision"}},
    {"model": "core.tempcontenttype", "pk": 104, "fields": {"app_label": "activity", "model": "eventnote"}},
    {"model": "core.tempcontenttype", "pk": 105, "fields": {"app_label": "activity", "model": "eventdetailsrevision"}},
    {"model": "core.tempcontenttype", "pk": 106, "fields": {"app_label": "activity", "model": "eventdetails"}},
    {"model": "core.tempcontenttype", "pk": 107, "fields": {"app_label": "activity", "model": "eventphotorevision"}},
    {"model": "core.tempcontenttype", "pk": 108, "fields": {"app_label": "activity", "model": "eventphoto"}},
    {"model": "core.tempcontenttype", "pk": 109, "fields": {"app_label": "activity", "model": "eventclassfactor"}},
    {"model": "core.tempcontenttype", "pk": 110, "fields": {"app_label": "activity", "model": "eventfilter"}},
    {"model": "core.tempcontenttype", "pk": 111, "fields": {"app_label": "activity", "model": "eventprovider"}},
    {"model": "core.tempcontenttype", "pk": 112, "fields": {"app_label": "activity", "model": "eventsource"}},
    {"model": "core.tempcontenttype", "pk": 113, "fields": {"app_label": "activity", "model": "eventsourceevent"}},
    {"model": "core.tempcontenttype", "pk": 114, "fields": {"app_label": "activity", "model": "notificationmethod"}},
    {"model": "core.tempcontenttype", "pk": 115, "fields": {"app_label": "activity", "model": "alertrule"}},
    {"model": "core.tempcontenttype", "pk": 116, "fields": {"app_label": "activity", "model": "eventnotification"}},
    {"model": "core.tempcontenttype", "pk": 117, "fields": {"app_label": "activity", "model": "tsvectormodel"}},
    {"model": "core.tempcontenttype", "pk": 118, "fields": {"app_label": "activity", "model": "person"}},
    {"model": "core.tempcontenttype", "pk": 119, "fields": {"app_label": "activity", "model": "membershiptype"}},
    {"model": "core.tempcontenttype", "pk": 120, "fields": {"app_label": "activity", "model": "team"}},
    {"model": "core.tempcontenttype", "pk": 121, "fields": {"app_label": "activity", "model": "teammembership"}},
    {"model": "core.tempcontenttype", "pk": 122, "fields": {"app_label": "activity", "model": "patrolrevision"}},
    {"model": "core.tempcontenttype", "pk": 123, "fields": {"app_label": "activity", "model": "patrol"}},
    {"model": "core.tempcontenttype", "pk": 124, "fields": {"app_label": "activity", "model": "patrolnoterevision"}},
    {"model": "core.tempcontenttype", "pk": 125, "fields": {"app_label": "activity", "model": "patrolnote"}},
    {"model": "core.tempcontenttype", "pk": 126, "fields": {"app_label": "activity", "model": "patrolfilerevision"}},
    {"model": "core.tempcontenttype", "pk": 127, "fields": {"app_label": "activity", "model": "patrolfile"}},
    {"model": "core.tempcontenttype", "pk": 128, "fields": {"app_label": "activity", "model": "patroltype"}},
    {
        "model": "core.tempcontenttype",
        "pk": 129,
        "fields": {"app_label": "activity", "model": "patrolsegmentmembership"},
    },
    {"model": "core.tempcontenttype", "pk": 130, "fields": {"app_label": "activity", "model": "patrolsegmentrevision"}},
    {"model": "core.tempcontenttype", "pk": 131, "fields": {"app_label": "activity", "model": "patrolsegment"}},
    {"model": "core.tempcontenttype", "pk": 132, "fields": {"app_label": "activity", "model": "patrolconfiguration"}},
    {
        "model": "core.tempcontenttype",
        "pk": 133,
        "fields": {"app_label": "activity", "model": "patrolconfigurationsubjectgroup"},
    },
    {"model": "core.tempcontenttype", "pk": 134, "fields": {"app_label": "activity", "model": "eventgeometryrevision"}},
    {"model": "core.tempcontenttype", "pk": 135, "fields": {"app_label": "activity", "model": "eventgeometry"}},
    {"model": "core.tempcontenttype", "pk": 136, "fields": {"app_label": "core", "model": "dastenant"}},
    {"model": "core.tempcontenttype", "pk": 137, "fields": {"app_label": "core", "model": "dasaccesstoken"}},
    {"model": "core.tempcontenttype", "pk": 138, "fields": {"app_label": "core", "model": "dasapplication"}},
    {"model": "core.tempcontenttype", "pk": 139, "fields": {"app_label": "core", "model": "dasgrant"}},
    {"model": "core.tempcontenttype", "pk": 140, "fields": {"app_label": "core", "model": "dasidtoken"}},
    {"model": "core.tempcontenttype", "pk": 141, "fields": {"app_label": "core", "model": "dasrefreshtoken"}},
    {"model": "core.tempcontenttype", "pk": 142, "fields": {"app_label": "choices", "model": "dynamicchoice"}},
    {"model": "core.tempcontenttype", "pk": 143, "fields": {"app_label": "choices", "model": "choice"}},
    {"model": "core.tempcontenttype", "pk": 144, "fields": {"app_label": "choices", "model": "subchoiceof"}},
    {"model": "core.tempcontenttype", "pk": 145, "fields": {"app_label": "choices", "model": "disablechoice"}},
    {"model": "core.tempcontenttype", "pk": 146, "fields": {"app_label": "reports", "model": "sourceproviderevent"}},
    {"model": "core.tempcontenttype", "pk": 147, "fields": {"app_label": "reports", "model": "sourceevent"}},
    {
        "model": "core.tempcontenttype",
        "pk": 148,
        "fields": {"app_label": "usercontent", "model": "filecontentrevision"},
    },
    {"model": "core.tempcontenttype", "pk": 149, "fields": {"app_label": "usercontent", "model": "filecontent"}},
    {
        "model": "core.tempcontenttype",
        "pk": 150,
        "fields": {"app_label": "usercontent", "model": "imagefilecontentrevision"},
    },
    {"model": "core.tempcontenttype", "pk": 151, "fields": {"app_label": "usercontent", "model": "imagefilecontent"}},
    {"model": "core.tempcontenttype", "pk": 152, "fields": {"app_label": "choices", "model": "actiontaken"}},
    {"model": "core.tempcontenttype", "pk": 153, "fields": {"app_label": "choices", "model": "behavior"}},
    {"model": "core.tempcontenttype", "pk": 154, "fields": {"app_label": "choices", "model": "causeofdeath"}},
    {"model": "core.tempcontenttype", "pk": 155, "fields": {"app_label": "choices", "model": "color"}},
    {"model": "core.tempcontenttype", "pk": 156, "fields": {"app_label": "choices", "model": "conservancy"}},
    {"model": "core.tempcontenttype", "pk": 157, "fields": {"app_label": "choices", "model": "fencesection"}},
    {"model": "core.tempcontenttype", "pk": 158, "fields": {"app_label": "choices", "model": "health"}},
    {"model": "core.tempcontenttype", "pk": 159, "fields": {"app_label": "choices", "model": "species"}},
    {"model": "core.tempcontenttype", "pk": 160, "fields": {"app_label": "choices", "model": "station"}},
    {"model": "core.tempcontenttype", "pk": 161, "fields": {"app_label": "gis", "model": "postgisgeometrycolumns"}},
    {"model": "core.tempcontenttype", "pk": 162, "fields": {"app_label": "gis", "model": "postgisspatialrefsys"}},
    {"model": "core.tempcontenttype", "pk": 163, "fields": {"app_label": "accounts", "model": "permissionsetchildren"}},
    {"model": "core.tempcontenttype", "pk": 164, "fields": {"app_label": "accounts", "model": "actasprofiles"}},
    {
        "model": "core.tempcontenttype",
        "pk": 165,
        "fields": {"app_label": "observations", "model": "subjectgroupchildren"},
    },
    {
        "model": "core.tempcontenttype",
        "pk": 166,
        "fields": {"app_label": "observations", "model": "sourcegroupchildren"},
    },
    {
        "model": "core.tempcontenttype",
        "pk": 167,
        "fields": {"app_label": "tracking", "model": "sourceproviderconfigurationnamechangeexcludedsubjecttypes"},
    },
    {
        "model": "core.tempcontenttype",
        "pk": 168,
        "fields": {"app_label": "tracking", "model": "sourceproviderconfigurationnewsubjectexcludedsubjecttypes"},
    },
    {"model": "core.tempcontenttype", "pk": 169, "fields": {"app_label": "mapping", "model": "spatialfeaturetypetags"}},
]

SQL = """
DO $$
DECLARE row RECORD;
old_id INTEGER;
new_id INTEGER;
temp_content_type_id INTEGER;
distinct_records INTEGER;
BEGIN
-- disable triggers
set session_replication_role to replica;

select count(*) into distinct_records
from django_content_type dct
         full outer join temp_content_type tct on dct.id = tct.id
where dct is distinct from tct;

if distinct_records > 0 then
    for row in select * from django_content_type
LOOP

    select id into temp_content_type_id from temp_content_type where app_label = row.app_label and model = row.model;
    if not row.id = temp_content_type_id then
        update django_content_type set id = row.id + 1000 where id = row.id;
    end if;
END LOOP;

-- second loop
for row in select * from django_content_type
LOOP

    if not row.model = 'tempcontenttype' then
        if row.id > 1000 then

        old_id = row.id - 1000;

            select id into new_id from temp_content_type where app_label = row.app_label and model = row.model;

            update public.django_content_type set id = new_id where id = row.id;

            update auth_permission set content_type_id = new_id where content_type_id = old_id;

            update activity_event set reported_by_content_type_id = new_id where reported_by_content_type_id=old_id;

            update activity_eventattachment set content_type_id = new_id where content_type_id=old_id;

            update activity_eventfile set usercontent_type_id = new_id where usercontent_type_id=old_id;

            update activity_patrolfile set usercontent_type_id = new_id where usercontent_type_id=old_id;

            update activity_patrolsegment set leader_content_type_id = new_id where leader_content_type_id=old_id;

            update django_admin_log set content_type_id = new_id where content_type_id=old_id;

            update analyzers_subjectanalyzerresult set subject_analyzer_content_type_id = new_id where subject_analyzer_content_type_id=old_id;

            update auth_permission set content_type_id = new_id where content_type_id = old_id;

            update observations_message set sender_content_type_id = new_id where sender_content_type_id=old_id;

            update observations_message set receiver_content_type_id = new_id where receiver_content_type_id=old_id;

            update tracking_sourceplugin set plugin_type_id = new_id where plugin_type_id=old_id;
        end if;
    end if;


END LOOP;
END IF;

-- enable triggers
set session_replication_role to default;

END;
$$
"""


def insert_into_temp_content_type(apps, schema_editor):
    TempContentType = apps.get_model(app_label="core", model_name="TempContentType")
    temps = []
    for bct in base_content_types:
        temps.append(TempContentType(id=bct["pk"], **bct["fields"]))
    TempContentType.objects.bulk_create(temps)


def test(*args):
    raise Exception("TEST")


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0016_alter_dastenant_managers"),
    ]

    operations = [
        migrations.CreateModel(
            name="TempContentType",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("app_label", models.CharField(max_length=100)),
                ("model", models.CharField(max_length=100, verbose_name="python model class name")),
            ],
            options={
                "verbose_name": "content type",
                "verbose_name_plural": "content types",
                "db_table": "temp_content_type",
                "unique_together": {("app_label", "model")},
            },
        ),
        migrations.RunPython(
            insert_into_temp_content_type,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RunSQL(
            sql=SQL,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.DeleteModel(
            name="TempContentType",
        ),
    ]
