# Generated by Django 3.2.21 on 2024-02-06 20:21

from django.db import migrations

sql_create_fks = """
DO
$$
    BEGIN
        -- RECREATE FK
        ALTER TABLE auth_group_permissions
            ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm
                FOREIGN KEY (permission_id) REFERENCES auth_permission
                    DEFERRABLE INITIALLY DEFERRED;

        ALTER TABLE accounts_permissionsetpermission
            ADD CONSTRAINT accounts_permissions_permission_id_5b7e3342_fk_auth_perm
                FOREIGN KEY (permission_id) REFERENCES auth_permission
                    DEFERRABLE INITIALLY DEFERRED;
    END
$$
"""


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0020_set_base_permissions"),
    ]

    operations = [
        migrations.RunSQL(
            sql=sql_create_fks,
            reverse_sql=migrations.RunSQL.noop,
        )
    ]
