# Generated by Django 3.2.21 on 2024-02-14 20:04

from django.conf import settings
from django.db import migrations

from core import tms_api_client

domain = settings.SERVER_FQDN
domain_blacklist = (
    "localhost",
    "root.dev.pamdas.org",
    "europe-west3-01.staging.pamdas.org",
    "europe-west3-01.pamdas.org",
)

sql_create_fks = ""

if domain not in domain_blacklist:
    tenant_data = tms_api_client.get_tenant_data(domain=domain)

    TENANT_RANGE_START = tenant_data["permissionsCustomSequenceStart"]
    TENANT_RANGE_END = tenant_data["permissionsCustomSequenceEnd"]

    if not TENANT_RANGE_START or not TENANT_RANGE_END:
        raise Exception("Tenant does not have custom permissions range")

    sql_move_custom_permissions = f"""
        DO
        $$
            DECLARE
                ROW                        RECORD;
                OLD_ID                     INTEGER;
                LOOP_INDEX                 INTEGER;
                RANGE_START                INTEGER;
                RANGE_END                  INTEGER;
                CURRENT_CUSTOM_PERMISSIONS INTEGER;

            BEGIN
                RANGE_START = {TENANT_RANGE_START};
                RANGE_END = {TENANT_RANGE_END};
                SELECT COUNT(id) INTO CURRENT_CUSTOM_PERMISSIONS FROM public.auth_permission WHERE codename LIKE '%:%';

                IF CURRENT_CUSTOM_PERMISSIONS <= (RANGE_END - RANGE_START) then

                    -- DROP FK
                    ALTER TABLE auth_group_permissions
                        DROP CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm;

                    ALTER TABLE accounts_permissionsetpermission
                        DROP CONSTRAINT accounts_permissions_permission_id_5b7e3342_fk_auth_perm;

                    LOOP_INDEX = RANGE_START;

                    FOR row IN SELECT * FROM public.auth_permission WHERE codename LIKE '%:%' ORDER BY id
                        LOOP
                            OLD_ID = row.id;

                            UPDATE public.auth_permission SET id = LOOP_INDEX WHERE id = row.id;

                            UPDATE auth_group_permissions SET permission_id = LOOP_INDEX WHERE permission_id = OLD_ID;

                            UPDATE accounts_permissionsetpermission

                            SET permission_id = LOOP_INDEX
                            WHERE permission_id = OLD_ID;

                            LOOP_INDEX = LOOP_INDEX + 1;
                        END LOOP;

                    PERFORM pg_catalog.setval('auth_permission_id_seq', LOOP_INDEX, true);
                ELSE
                    RAISE EXCEPTION 'Custom permissions are out-range';
                END IF;
            END
        $$
        """

    sql_create_fks = """
        DO
        $$
            BEGIN
                -- RECREATE FK
                ALTER TABLE auth_group_permissions
                    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm
                        FOREIGN KEY (permission_id) REFERENCES auth_permission
                            DEFERRABLE INITIALLY DEFERRED;

                ALTER TABLE accounts_permissionsetpermission
                    ADD CONSTRAINT accounts_permissions_permission_id_5b7e3342_fk_auth_perm
                        FOREIGN KEY (permission_id) REFERENCES auth_permission
                            DEFERRABLE INITIALLY DEFERRED;
            END
        $$
    """
else:
    NEW_TABLE_SEQUENCE = 20000000

    sql_move_custom_permissions = f"""
    DO
    $$
    DECLARE
        CURRENT_SEQUENCE INTEGER;
    BEGIN

        SELECT last_value INTO CURRENT_SEQUENCE FROM auth_permission_id_seq;

        IF CURRENT_SEQUENCE < {NEW_TABLE_SEQUENCE} then
            ALTER SEQUENCE auth_permission_id_seq RESTART WITH {NEW_TABLE_SEQUENCE} ;
        END IF;
    END
$$;
    """


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0021_recreate_fks_group_permissio_and_permission_permissions_permission"),
    ]

    operations = [
        migrations.RunSQL(
            sql=sql_move_custom_permissions,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql=sql_create_fks,
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
