# Generated by Django 3.2.21 on 2024-03-21 22:00

import json
import uuid

from django.conf import settings
from django.db import migrations, models

JSON_FILE = f"{settings.BASE_DIR}/core/migrations/data/golden_set_eulas.json"

SQL = """
DO
$$
    DECLARE
        row          RECORD;
        old_eula_id  TEXT;
        temp_eula_id TEXT := NULL;

    BEGIN
        ALTER TABLE accounts_useragreement
            DROP CONSTRAINT accounts_useragreement_eula_id_795ac082_fk_accounts_eula_id;

        for row in select * from accounts_eula order by id
            LOOP
                select id
                into temp_eula_id
                from core_eulatemp
                where version = row.version;

                IF temp_eula_id IS NOT NULL THEN
                    old_eula_id = row.id;

                    -- CHANGE ID
                    UPDATE accounts_eula SET id = temp_eula_id::UUID where id = row.id;

                    -- UPDATE FK
                    UPDATE accounts_useragreement set eula_id = temp_eula_id::UUID where eula_id::TEXT = old_eula_id;
                END IF;
                old_eula_id := NULL;
            END LOOP;
    END ;
$$
"""


def open_json_file(json_file: str):
    with open(json_file, "r") as json_file:
        return json.load(json_file)


def load_golden_eula(apps, schema_editor):
    EULATemp = apps.get_model(app_label="core", model_name="EULATemp")

    base_eulas = open_json_file(JSON_FILE)

    for eula in base_eulas:
        EULATemp.objects.create(**eula)


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0022_custom_permissions_migration"),
    ]

    operations = [
        migrations.CreateModel(
            name="EULATemp",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ("version", models.CharField(max_length=30, unique=True)),
                ("eula_url", models.URLField()),
                ("active", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "EULATemp",
                "verbose_name_plural": "EULATemps",
            },
        ),
        migrations.RunPython(
            load_golden_eula,
            migrations.RunPython.noop,
        ),
        migrations.RunSQL(
            sql=SQL,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.DeleteModel(name="EULATemp"),
    ]
