# Generated by Django 3.2.21 on 2024-03-21 22:00

import uuid

from django.db import migrations, models

SQL = """
DO
$$
    DECLARE
        row          RECORD;
        old_eula_id  TEXT;
        temp_eula_id TEXT;

    BEGIN
        -- DROP CONSTRAINGS accounts_useragreement_eula_id_795ac082_fk_accounts_eula_id
        ALTER TABLE accounts_useragreement
            DROP CONSTRAINT accounts_useragreement_eula_id_795ac082_fk_accounts_eula_id;

        for row in select * from accounts_eula order by id
            LOOP
                select id
                into temp_eula_id
                from core_eulatemp
                where version = row.version;

                raise notice '%', row.id;
                raise notice '%', temp_eula_id;
                raise notice ' ';

                old_eula_id = row.id;
                raise notice 'OLD: %', old_eula_id;

                -- CHANGE ID
                UPDATE accounts_eula SET id = temp_eula_id::UUID where id = row.id;

                -- UPDATE FK
                UPDATE accounts_useragreement set eula_id = temp_eula_id::UUID where eula_id::TEXT = old_eula_id;

            END LOOP;

    END;
$$
"""

EULAS = [
    {
        "created_at": "2023-11-25 16:35:01.790525+00",
        "updated_at": "2023-11-25 16:35:01.790541+00",
        "id": "948d74d8-8bb0-11ee-ab46-5a63f26ed110",
        "version": "EarthRanger_EULA_ver2020-02-12",
        "eula_url": "https://earthranger.com/EULA",
        "active": False,
    },
    {
        "created_at": "2023-11-25 16:35:02.098615+00",
        "updated_at": "2023-11-25 16:35:02.098632+00",
        "id": "94bcc9d6-8bb0-11ee-ab46-5a63f26ed110",
        "version": "EarthRanger_EULA_ver2020-02-27",
        "eula_url": "https://earthranger.com/EULA",
        "active": False,
    },
    {
        "created_at": "2023-11-25 16:35:02.164628+00",
        "updated_at": "2023-11-25 16:35:02.164642+00",
        "id": "94c6e29a-8bb0-11ee-ab46-5a63f26ed110",
        "version": "EarthRanger_EULA_ver2020-04-01",
        "eula_url": "https://earthranger.com/EULA",
        "active": True,
    },
]


def load_golden_eula(apps, schema_editor):
    EULATemp = apps.get_model(app_label="core", model_name="EULATemp")
    for eula in EULAS:
        EULATemp.objects.create(**eula)


def fail(*args):
    # pass
    raise Exception("test")


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0022_custom_permissions_migration"),
    ]

    operations = [
        migrations.CreateModel(
            name="EULATemp",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ("version", models.CharField(max_length=30, unique=True)),
                ("eula_url", models.URLField()),
                ("active", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "EULATemp",
                "verbose_name_plural": "EULATemps",
            },
        ),
        migrations.RunPython(
            load_golden_eula,
            migrations.RunPython.noop,
        ),
        migrations.RunSQL(
            sql=SQL,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.DeleteModel(name="EULATemp"),
    ]
