# Generated by Django 3.2.21 on 2024-03-26 22:09

from django.db import migrations

SQL = """
    -- CREATE CONSTRAINT
    ALTER TABLE accounts_useragreement
        ADD CONSTRAINT accounts_useragreement_eula_id_795ac082_fk_accounts_eula_id
            FOREIGN KEY (eula_id) REFERENCES accounts_eula
                DEFERRABLE INITIALLY DEFERRED;
"""


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0023_set_base_eula"),
    ]

    operations = [
        migrations.RunSQL(
            sql=SQL,
            reverse_sql=migrations.RunSQL.noop,
        )
    ]
