# Generated by Django 3.2.21 on 2024-06-21 17:29
from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ("core", "0024_recreate_useragreement_eula_fk"),
    ]

    operations = []  # code move to core 0026
