# Generated by Django 3.2.21 on 2024-08-22 16:33

from django.apps import apps
from django.conf import settings
from django.contrib.auth.models import Permission
from django.db import migrations

from core.models import DASTenant
from utils.json import load_from_file
from utils.tenant.managers import TenantContextManager, UnsetDASTenantContextManager

JSON_FILE = f"{settings.BASE_DIR}/core/migrations/data/golden_set_permissions.json"


def create_export_permission_set_and_permission(migration_apps, schema_editor):
    PermissionSet = apps.get_model("accounts", "PermissionSet")
    User = apps.get_model(settings.AUTH_USER_MODEL)

    golden_set_permissions = load_from_file(file_path=JSON_FILE)

    event_permission_list = list(
        filter(lambda perms: str(perms["fields"]["codename"]) == "view_export_event_data", golden_set_permissions)
    )
    observation_permission_list = list(
        filter(lambda perms: str(perms["fields"]["codename"]) == "view_export_observation_data", golden_set_permissions)
    )

    if event_permission_list and observation_permission_list:
        event_permission, _ = Permission.objects.get_or_create(
            id=event_permission_list[0]["pk"], defaults=event_permission_list[0]["fields"]
        )
        observation_permission, _ = Permission.objects.get_or_create(
            id=observation_permission_list[0]["pk"], defaults=observation_permission_list[0]["fields"]
        )

        with UnsetDASTenantContextManager():
            for tenant in DASTenant.objects.all():
                with TenantContextManager(tenant.domain):
                    export_permission_set, _ = PermissionSet.objects.get_or_create(
                        name="Can Export Data", das_tenant_id=tenant.id
                    )

                    export_permission_set.permissions.add(event_permission)
                    export_permission_set.permissions.add(observation_permission)

                    users_ids = User.objects.filter(is_active=True, das_tenant_id=tenant.id)
                    export_permission_set.user_set.add(*users_ids)


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0025_add_export_permission_set_and_permission"),
    ]

    operations = [
        migrations.RunPython(
            create_export_permission_set_and_permission,
            migrations.RunPython.noop,
        ),
    ]
