# Generated by Django 3.2.21 on 2024-09-09 23:54
from django.contrib.auth.models import Permission
from django.db import migrations


def fix_export_data_permissions(apps, schema):
    for codename in ["view_export_event_data", "view_export_observation_data"]:
        for permission in Permission.objects.filter(codename__contains=codename):
            new_code_name = permission.codename.replace("view", "can")
            permission.codename = new_code_name
            permission.save(update_fields=["codename"])


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0026_add_export_permission_set_and_permission_with_unsetdastenantcontextmanager"),
    ]

    operations = [migrations.RunPython(code=fix_export_data_permissions)]
