# Generated by Django 3.2.21 on 2024-10-09 18:59

from django.db import migrations


def remove_tenant_hash_prefix_for_export_permissions_codename(apps, schema_editor):
    Permission = apps.get_model("auth.Permission")

    can_export_event_data = Permission.objects.filter(codename__endswith="can_export_event_data").first()
    can_export_observation_data = Permission.objects.filter(codename__endswith="can_export_observation_data").first()

    event_codename = can_export_event_data.codename.split(":")
    observations_codename = can_export_observation_data.codename.split(":")

    if len(event_codename) == 2:
        can_export_event_data.codename = event_codename[1]
        can_export_event_data.save(update_fields=["codename"])

    if len(observations_codename) == 2:
        can_export_observation_data.codename = observations_codename[1]
        can_export_observation_data.save(update_fields=["codename"])


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0027_fix_export_data_permissions"),
    ]

    operations = [
        migrations.RunPython(
            code=remove_tenant_hash_prefix_for_export_permissions_codename,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
