# Generated by Django 3.2.25 on 2025-05-15 01:57

import oauth2_provider.settings as oauth2_settings

from django.db import migrations

from utils.middleware import EFB_APPLICATION_ID


def create_efb_application(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    Application = apps.get_model(oauth2_settings.APPLICATION_MODEL)

    defaults = dict(
        client_type="Confidential",
        authorization_grant_type="password",
        client_secret="",
        name="Event Form Builder Admin App",
        skip_authorization=True,
    )
    Application.objects.using(db_alias).get_or_create(client_id=EFB_APPLICATION_ID, defaults=defaults)


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0028_remove_prefixex_tenant_hash_from_export_data_permissions"),
        ("das_server", "0002_er_track"),
    ]

    operations = [
        migrations.RunPython(
            code=create_efb_application,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
