# Generated by Django 3.2.25 on 2025-05-15 01:57

from django.db import migrations

from utils.middleware import EFB_APPLICATION_ID


def create_efb_application(apps, schema_editor):
    DASApplication = apps.get_model("core", "DASApplication")

    DASApplication.objects.get_or_create(
        client_id=EFB_APPLICATION_ID,
        defaults={
            "client_type": "Confidential",
            "authorization_grant_type": "password",
            "client_secret": "",
            "name": "Event Form Builder Das App",
        },
    )


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0028_remove_prefixex_tenant_hash_from_export_data_permissions"),
        ("core", "0006_add_das_tenant_model"),
    ]

    operations = [
        migrations.RunPython(
            code=create_efb_application,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
