# Generated by Django 3.2.25 on 2025-05-15 01:57

import logging

import oauth2_provider.settings as oauth2_settings

from django.db import migrations

from core.models import DASTenant
from utils.middleware import EFB_APPLICATION_ID
from utils.tenant.exceptions import TenantNotFoundException
from utils.tenant.managers import TenantContextManager, UnsetDASTenantContextManager

logger = logging.getLogger(__name__)


def create_efb_application(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    Application = apps.get_model(oauth2_settings.APPLICATION_MODEL)

    defaults = dict(
        client_type="Confidential",
        authorization_grant_type="password",
        client_secret="",
        name="Event Form Builder Admin App",
        skip_authorization=True,
    )

    with UnsetDASTenantContextManager():
        das_tenants = DASTenant.objects.all()

    for tenant in das_tenants:
        domain = tenant.domain
        try:
            with TenantContextManager(domain):
                Application.objects.using(db_alias).get_or_create(client_id=EFB_APPLICATION_ID, defaults=defaults)
        except (DASTenant.DoesNotExist, TenantNotFoundException):
            logger.warning(
                "DASTenant with domain %s does not exist in TMS, when creating efb application for that domain",
                domain,
            )


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0028_remove_prefixex_tenant_hash_from_export_data_permissions"),
        ("das_server", "0002_er_track"),
    ]

    operations = [
        migrations.RunPython(
            code=create_efb_application,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
