# Generated by Django 3.2.25 on 2025-08-25 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0029_efb_new_oauth_app"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="dasaccesstoken",
            name="core_dasacc_das_ten_19a210_idx",
        ),
        migrations.AlterField(
            model_name="dasaccesstoken",
            name="token",
            field=models.CharField(max_length=255),
        ),
    ]
