# Generated by Django 2.0.13 on 2019-12-03 20:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureFlag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(choices=[('er_mobile_app_features', 'ER Mobile App Features')], max_length=100, unique=True)),
                ('value', models.BooleanField(default=False)),
            ],
        ),
    ]
