project-id: padas-app
cluster-name: partners
version-prefix: dev
server-branch-name: develop
web-branch-name: develop
namespace: training
iaas: gcp
das-static-ip: 35.247.26.97
iaas-workspace: padas-app
deployment-plan: integration

