# #######################################
# PgCat: Connection Pooler Configuration
# #######################################
#
# Used for local development. Make sure it mimics the configurations in
# dev/prod as it is a way to test that new local features will work with the
# deployed infrastructure.
#
# Configured pools
# ----------------
#
# Currently, two pools are configured for different use cases:
#
# 1. `main`: Query routing of reads/writes + transaction pooling
# 2. `proxy_primary`: Proxy to the primary db instance + session pooling
#
#
# Deployed configurations
# -----------------------
#
# - dev: https://github.com/PADAS/er-flux-infra/blob/main/apps/dev/pgcat/values.yaml#L26
# - prod: https://github.com/PADAS/er-flux-infra/blob/main/apps/prod/pgcat/values.yaml#L24
# - prod-me: https://github.com/PADAS/er-flux-infra/blob/main/apps/prod-me/pgcat/values.yaml#L24
# - prod-us: https://github.com/PADAS/er-flux-infra/blob/main/apps/prod-us/pgcat/values.yaml#L24
# - stage: https://github.com/PADAS/er-flux-infra/blob/main/apps/stage/pgcat/values.yaml
#
#
# Link to the official PgCat configuration documentation: https://github.com/postgresml/pgcat/blob/main/CONFIG.md

[general]
host = "0.0.0.0"
port = 6432
server_tls = true # required by AlloyDB
admin_username = "pgcat"
admin_password = "pgcat"

# pools configuration
# -------------------

## pool: `main`
##
## Description: Pool that does reads/writes routing + transaction pooling
##
[pools.main]
pool_mode = "transaction"
default_role = "primary"
query_parser_enabled = true
query_parser_read_write_splitting = true
primary_reads_enabled = false

[pools.main.users.0]
username = "das"
password = "das"
pool_size = 100
min_pool_size = 0

[pools.main.shards.0]
servers = [
  ["postgis", 5432, "primary"],
  ["postgis-replica", 5432, "replica"]
]
database = "das"

## pool: `proxy_primary`
##
## Description: Pool that just acts as a proxy for the primary DB instance with
##              session mode.
##
[pools.proxy_primary]
pool_mode = "session"
default_role = "primary"
query_parser_enabled = false
query_parser_read_write_splitting = false
primary_reads_enabled = true

[pools.proxy_primary.users.0]
username = "das"
password = "das"
pool_size = 100
min_pool_size = 0

[pools.proxy_primary.shards.0]
servers = [
  ["postgis", 5432, "primary"],
]
database = "das"
