---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: <<infra-namespace>>
  name: filebeat-config
  labels:
    k8s-app: filebeat
    kubernetes.io/cluster-service: "true"
data:
  ssl.pem: <<pamdas-org-ssl-cert>>
  ssl.key: <<pamdas-org-ssl-key>>
  ca.pem: <<pamdas-org-ssl-ca>>
  filebeat.yml: |-
    filebeat:
      prospectors:
      - type: docker
        containers.ids:
        - "*"
        processors:
          - add_kubernetes_metadata:
              in_cluster: true
        multiline:
          pattern: '^\s'
          match: after
      config.modules:
        path: ${path.config}/modules.d/*.yml
        reload.enabled: false

    output.logstash:
      hosts: ['<<log_url>>']
      ssl.certificate_authorities: ["/etc/filebeat/ca.pem"]
      ssl.certificate: "/etc/filebeat/ssl.pem"
      ssl.key: "/etc/filebeat/ssl.key"

---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  namespace: <<infra-namespace>>
  name: filebeat
  labels:
    k8s-app: filebeat
    kubernetes.io/cluster-service: "true"
spec:
  template:
    metadata:
      labels:
        k8s-app: filebeat
        kubernetes.io/cluster-service: "true"
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: filebeat
        image: docker.elastic.co/beats/filebeat:6.3.1
        args: [
          "-c", "/etc/filebeat/filebeat.yml",
          "-e",
        ]
        securityContext:
          runAsUser: 0
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 50m
            memory: 100Mi
        volumeMounts:
        - name: config
          mountPath: /etc/filebeat
          readOnly: true
        - name: data
          mountPath: /usr/share/filebeat/data
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
      volumes:
      - name: config
        configMap:
          name: filebeat-config
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      - name: data
        emptyDir: {}
