# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-07 13:03
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActionTaken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('order', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Behavior',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('order', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='CauseOfDeath',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('order', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('model', models.CharField(max_length=50)),
                ('field', models.CharField(max_length=40)),
                ('value', models.CharField(blank=True, max_length=40)),
                ('display', models.CharField(blank=True, max_length=100)),
                ('ordernum', models.SmallIntegerField(blank=True, null=True)),
                ('sub_choice_of', models.ManyToManyField(blank=True, to='choices.Choice')),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('order', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Conservancy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('order', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='DynamicChoice',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('model_name', models.CharField(max_length=100, verbose_name='Model lookup')),
                ('criteria', models.CharField(max_length=100, verbose_name='Criteria')),
                ('value_col', models.CharField(max_length=100, verbose_name='Value column')),
                ('display_col', models.CharField(max_length=100, verbose_name='Display column')),
            ],
        ),
        migrations.CreateModel(
            name='FenceSection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('order', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Health',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('order', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('order', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('order', models.IntegerField(blank=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='choice',
            unique_together=set([('model', 'field', 'value')]),
        ),
    ]
