# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-01-17 17:16
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('choices', '0003_auto_20161102_1530'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('ordernum', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Incident Statuses',
                'verbose_name': 'Incident Status',
            },
        ),
    ]
