# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-04-05 20:11
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('choices', '0006_additional_choice_fields'),
    ]

    operations = [
        # migrations.CreateModel(
        #     name='AnimalAge',
        #     fields=[
        #         ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
        #         ('name', models.CharField(max_length=100)),
        #         ('ordernum', models.IntegerField(blank=True, null=True)),
        #     ],
        # ),
        # migrations.CreateModel(
        #     name='AnimalSex',
        #     fields=[
        #         ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
        #         ('name', models.CharField(max_length=100)),
        #         ('ordernum', models.IntegerField(blank=True, null=True)),
        #     ],
        # ),
        # migrations.CreateModel(
        #     name='CarcassAge',
        #     fields=[
        #         ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
        #         ('name', models.CharField(max_length=100)),
        #         ('ordernum', models.IntegerField(blank=True, null=True)),
        #     ],
        # ),
        # migrations.CreateModel(
        #     name='ChoiceModel',
        #     fields=[
        #         ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
        #         ('name', models.CharField(max_length=100)),
        #         ('ordernum', models.IntegerField(blank=True, null=True)),
        #     ],
        # ),
        # migrations.CreateModel(
        #     name='CriticalSightingType',
        #     fields=[
        #         ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
        #         ('name', models.CharField(max_length=100)),
        #         ('ordernum', models.IntegerField(blank=True, null=True)),
        #     ],
        # ),
        # migrations.CreateModel(
        #     name='Crops',
        #     fields=[
        #         ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
        #         ('name', models.CharField(max_length=100)),
        #         ('ordernum', models.IntegerField(blank=True, null=True)),
        #     ],
        # ),
        # migrations.CreateModel(
        #     name='DetectionType',
        #     fields=[
        #         ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
        #         ('name', models.CharField(max_length=100)),
        #         ('ordernum', models.IntegerField(blank=True, null=True)),
        #     ],
        # ),
        # migrations.CreateModel(
        #     name='Direction',
        #     fields=[
        #         ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
        #         ('name', models.CharField(max_length=100)),
        #         ('ordernum', models.IntegerField(blank=True, null=True)),
        #     ],
        # ),
        # migrations.CreateModel(
        #     name='FenceDamage',
        #     fields=[
        #         ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
        #         ('name', models.CharField(max_length=100)),
        #         ('ordernum', models.IntegerField(blank=True, null=True)),
        #     ],
        # ),
        # migrations.CreateModel(
        #     name='FenceLocation',
        #     fields=[
        #         ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
        #         ('name', models.CharField(max_length=100)),
        #         ('ordernum', models.IntegerField(blank=True, null=True)),
        #     ],
        # ),
        # migrations.CreateModel(
        #     name='FireCause',
        #     fields=[
        #         ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
        #         ('name', models.CharField(max_length=100)),
        #         ('ordernum', models.IntegerField(blank=True, null=True)),
        #     ],
        # ),
        # migrations.CreateModel(
        #     name='FireStatus',
        #     fields=[
        #         ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
        #         ('name', models.CharField(max_length=100)),
        #         ('ordernum', models.IntegerField(blank=True, null=True)),
        #     ],
        # ),
        # migrations.CreateModel(
        #     name='InjuryCause',
        #     fields=[
        #         ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
        #         ('name', models.CharField(max_length=100)),
        #         ('ordernum', models.IntegerField(blank=True, null=True)),
        #     ],
        # ),
        # migrations.CreateModel(
        #     name='InjuryType',
        #     fields=[
        #         ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
        #         ('name', models.CharField(max_length=100)),
        #         ('ordernum', models.IntegerField(blank=True, null=True)),
        #     ],
        # ),
        # migrations.CreateModel(
        #     name='KeySpecies',
        #     fields=[
        #         ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
        #         ('name', models.CharField(max_length=100)),
        #         ('ordernum', models.IntegerField(blank=True, null=True)),
        #     ],
        # ),
        # migrations.CreateModel(
        #     name='MedicalEquipmentRequired',
        #     fields=[
        #         ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
        #         ('name', models.CharField(max_length=100)),
        #         ('ordernum', models.IntegerField(blank=True, null=True)),
        #     ],
        # ),
        # migrations.CreateModel(
        #     name='MedicalEvacSecurity',
        #     fields=[
        #         ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
        #         ('name', models.CharField(max_length=100)),
        #         ('ordernum', models.IntegerField(blank=True, null=True)),
        #     ],
        # ),
        # migrations.CreateModel(
        #     name='PoacherCampAge',
        #     fields=[
        #         ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
        #         ('name', models.CharField(max_length=100)),
        #         ('ordernum', models.IntegerField(blank=True, null=True)),
        #     ],
        # ),
        # migrations.CreateModel(
        #     name='SnareAge',
        #     fields=[
        #         ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
        #         ('name', models.CharField(max_length=100)),
        #         ('ordernum', models.IntegerField(blank=True, null=True)),
        #     ],
        # ),
        # migrations.CreateModel(
        #     name='SnareStatus',
        #     fields=[
        #         ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
        #         ('name', models.CharField(max_length=100)),
        #         ('ordernum', models.IntegerField(blank=True, null=True)),
        #     ],
        # ),
        # migrations.CreateModel(
        #     name='TracksType',
        #     fields=[
        #         ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
        #         ('name', models.CharField(max_length=100)),
        #         ('ordernum', models.IntegerField(blank=True, null=True)),
        #     ],
        # ),
        # migrations.CreateModel(
        #     name='TrafficActivity',
        #     fields=[
        #         ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
        #         ('name', models.CharField(max_length=100)),
        #         ('ordernum', models.IntegerField(blank=True, null=True)),
        #     ],
        # ),
        # migrations.CreateModel(
        #     name='TrafficType',
        #     fields=[
        #         ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
        #         ('name', models.CharField(max_length=100)),
        #         ('ordernum', models.IntegerField(blank=True, null=True)),
        #     ],
        # ),
        # migrations.CreateModel(
        #     name='TypeOfIllegalActivity',
        #     fields=[
        #         ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
        #         ('name', models.CharField(max_length=100)),
        #         ('ordernum', models.IntegerField(blank=True, null=True)),
        #     ],
        # ),
        # migrations.CreateModel(
        #     name='TypeOfShots',
        #     fields=[
        #         ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
        #         ('name', models.CharField(max_length=100)),
        #         ('ordernum', models.IntegerField(blank=True, null=True)),
        #     ],
        # ),
        # migrations.CreateModel(
        #     name='TypeOfTrophy',
        #     fields=[
        #         ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
        #         ('name', models.CharField(max_length=100)),
        #         ('ordernum', models.IntegerField(blank=True, null=True)),
        #     ],
        # ),
        # migrations.CreateModel(
        #     name='VehicleType',
        #     fields=[
        #         ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
        #         ('name', models.CharField(max_length=100)),
        #         ('ordernum', models.IntegerField(blank=True, null=True)),
        #     ],
        # ),
        # migrations.CreateModel(
        #     name='VehicleTypes',
        #     fields=[
        #         ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
        #         ('name', models.CharField(max_length=100)),
        #         ('ordernum', models.IntegerField(blank=True, null=True)),
        #     ],
        # ),
        # migrations.CreateModel(
        #     name='WeaponTypes',
        #     fields=[
        #         ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
        #         ('name', models.CharField(max_length=100)),
        #         ('ordernum', models.IntegerField(blank=True, null=True)),
        #     ],
        # ),
    ]
