# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-08-10 19:45
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('choices', '0007_accidenttype_animalage_animalsex_carcassage_choicemodel_criticalsightingtype_crops_detectiontype_dir'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalCondition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4,
                                        primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('ordernum', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Animal Condition',
                'verbose_name_plural': 'Animal Conditions',
            },
        ),
        migrations.CreateModel(
            name='ArrestNationality',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4,
                                        primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('ordernum', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Arrest Nationality',
                'verbose_name_plural': 'Arrest Nationalities',
            },
        ),
        migrations.CreateModel(
            name='ArrestVillageName',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4,
                                        primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('ordernum', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Arrest Village Name',
                'verbose_name_plural': 'Arrest Village Names',
            },
        ),
        migrations.CreateModel(
            name='ReasonForArrest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4,
                                        primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('ordernum', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Reason for Arrest',
                'verbose_name_plural': 'Reasons for Arrest',
            },
        ),
        migrations.CreateModel(
            name='SpoorAge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4,
                                        primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('ordernum', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'SPOOR Age',
                'verbose_name_plural': 'SPOOR Ages',
            },
        ),
        migrations.CreateModel(
            name='SpoorFootType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4,
                                        primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('ordernum', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'SPOOR Foot Type',
                'verbose_name_plural': 'SPOOR Foot Types',
            },
        ),
    ]
