# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-08-10 21:55
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('choices', '0008_animalcondition_arrestnationality_arrestvillagename_reasonforarrest_spoorage_spoorfoottype'),
    ]

    operations = [
        migrations.CreateModel(
            name='SnareAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4,
                                        primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('ordernum', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Snare Action',
                'verbose_name_plural': 'Snare Actions',
            },
        ),
    ]
