# Generated by Django 2.0.13 on 2019-09-10 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choices', '0010_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='delete_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
