# Generated by Django 2.0.13 on 2019-08-31 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choices', '0010_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='icon',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
