# Generated by Django 2.0.13 on 2019-09-16 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choices', '0010_choices'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisableChoice',
            fields=[
            ],
            options={
                'verbose_name': 'Disable Choice',
                'verbose_name_plural': 'Disable Choices',
                'proxy': True,
                'indexes': [],
            },
            bases=('choices.choice',),
        ),
        migrations.AddField(
            model_name='choice',
            name='delete_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='choice',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
