# Generated by Django 2.0.13 on 2019-09-13 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choices', '0011_choice_delete_on'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisableChoice',
            fields=[
            ],
            options={
                'verbose_name': 'Disable Choice',
                'verbose_name_plural': 'Disable Choices',
                'proxy': True,
                'indexes': [],
            },
            bases=('choices.choice',),
        ),
        migrations.AddField(
            model_name='choice',
            name='activate',
            field=models.BooleanField(default=True),
        ),
    ]
