# Generated by Django 2.0.13 on 2019-10-01 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choices', '0011_auto_20190916_0828'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='icon',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
