# Generated by Django 2.2.9 on 2020-03-10 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choices', '0012_choice_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='model',
            field=models.CharField(choices=[('activity.event', 'Field Reports'), ('accounts.user.User', 'User'), ('mapping.TileLayer', 'Maps'), ('observations.region', 'Region'), ('observations.Source', 'Sources'), ('activity.eventtype', 'Field Report Type')], default='activity.event', max_length=50),
        ),
    ]
