# Generated by Django 2.2.9 on 2020-06-12 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('choices', '0014_meta'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='disablechoice',
            options={'verbose_name': 'Disabled Choice'},
        ),
    ]
