# Generated by Django 3.2.19 on 2023-08-04 19:05
import uuid
from functools import partial

from django.db import migrations, models

from utils.migrations import copy_model_column, populate_model_uuid_column

APP_NAME = "choices"
CHOICE_NAME_COLUMN = "choice_name"
ID_COLUMN = "id"
MODEL_NAME = "DynamicChoice"
UUID_COLUMN = "uuid"


populate_uuid_column = partial(populate_model_uuid_column, APP_NAME, MODEL_NAME, UUID_COLUMN)
copy_column_id_to_choice_name = partial(copy_model_column, APP_NAME, MODEL_NAME, ID_COLUMN, CHOICE_NAME_COLUMN)


class Migration(migrations.Migration):
    dependencies = [("choices", "0018_use_models_JSONField_instead_postgres_fields_JSONField")]

    operations = [
        migrations.AddField(model_name=MODEL_NAME.lower(), name=UUID_COLUMN, field=models.UUIDField(null=True)),
        migrations.AddField(
            model_name=MODEL_NAME.lower(), name=CHOICE_NAME_COLUMN, field=models.CharField(max_length=100, null=True)
        ),
        migrations.RunPython(populate_uuid_column),
        migrations.RunPython(copy_column_id_to_choice_name),
        migrations.RemoveField(model_name=MODEL_NAME.lower(), name=ID_COLUMN),
        migrations.RenameField(model_name=MODEL_NAME.lower(), old_name=UUID_COLUMN, new_name=ID_COLUMN),
        migrations.AlterField(
            model_name=MODEL_NAME.lower(),
            name=CHOICE_NAME_COLUMN,
            field=models.CharField(max_length=100, null=False, unique=True, verbose_name="Choice name"),
        ),
        migrations.AlterField(
            model_name=MODEL_NAME.lower(),
            name=ID_COLUMN,
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
