# Generated by Django 3.2.19 on 2023-08-31 01:07
import uuid
from functools import partial

import django.db.models.deletion
from django.db import migrations, models

from utils.migrations import populate_model_uuid_column

APP_NAME = "choices"
FROM_CHOICE = "from_choice"
ID_COLUMN = "id"
MANY_TO_MANY_FIELD = "sub_choice_of"
MODEL_NAME = "SubChoiceOf"
REFERED_MODEL = "Choice"
TO_CHOICE = "to_choice"
UUID_COLUMN = "uuid"

NEW_TABLE_NAME = f"{APP_NAME}_{MODEL_NAME.lower()}"
OLD_TABLE_NAME = f"{APP_NAME}_{REFERED_MODEL.lower()}_{MANY_TO_MANY_FIELD}"

populate_uuid = partial(populate_model_uuid_column, APP_NAME, MODEL_NAME, UUID_COLUMN)


class Migration(migrations.Migration):
    dependencies = [(APP_NAME, "0019_alter_dynamicchoice_id")]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=f"ALTER TABLE {OLD_TABLE_NAME} RENAME TO {NEW_TABLE_NAME}",
                    reverse_sql=f"ALTER TABLE {NEW_TABLE_NAME} RENAME TO {OLD_TABLE_NAME}",
                ),
            ],
            state_operations=[
                migrations.CreateModel(
                    name=MODEL_NAME,
                    fields=[
                        ("id", models.AutoField(serialize=True)),
                        (
                            FROM_CHOICE,
                            models.ForeignKey(
                                default=uuid.uuid4,
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name=FROM_CHOICE,
                                to=f"{APP_NAME}.{REFERED_MODEL.lower()}",
                            ),
                        ),
                        (
                            TO_CHOICE,
                            models.ForeignKey(
                                default=uuid.uuid4,
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name=TO_CHOICE,
                                to=f"{APP_NAME}.{REFERED_MODEL.lower()}",
                            ),
                        ),
                    ],
                    options={"abstract": False},
                ),
                migrations.AlterField(
                    model_name=REFERED_MODEL.lower(),
                    name=MANY_TO_MANY_FIELD,
                    field=models.ManyToManyField(
                        blank=True, through=f"{APP_NAME}.{MODEL_NAME}", to=f"{APP_NAME}.{REFERED_MODEL}"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name=MODEL_NAME.lower(),
            name=UUID_COLUMN,
            field=models.UUIDField(null=True),
        ),
        migrations.RunPython(populate_uuid),
        migrations.RemoveField(
            model_name=MODEL_NAME.lower(),
            name=ID_COLUMN,
        ),
        migrations.RenameField(
            model_name=MODEL_NAME.lower(),
            old_name=UUID_COLUMN,
            new_name=ID_COLUMN,
        ),
        migrations.AlterField(
            model_name=MODEL_NAME.lower(),
            name=ID_COLUMN,
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=True),
        ),
    ]
