# Generated by Django 3.2.19 on 2023-09-25 22:26

import uuid

import django_multitenant.fields

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_migrate_oauth_tables_to_das_custom_models"),
        ("choices", "0020_change_subchoiceof_pk_type_to_uuid"),
    ]

    operations = [
        migrations.AddField(
            model_name="choice",
            name="das_tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="choices_choice",
                to="core.dastenant",
            ),
        ),
        migrations.AddField(
            model_name="dynamicchoice",
            name="das_tenant",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="core.dastenant"
            ),
        ),
        migrations.AddField(
            model_name="subchoiceof",
            name="das_tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="choices_subchoiceof",
                to="core.dastenant",
            ),
        ),
        migrations.AlterField(
            model_name="subchoiceof",
            name="from_choice",
            field=django_multitenant.fields.TenantForeignKey(
                default=uuid.uuid4,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="from_choice",
                to="choices.choice",
            ),
        ),
        migrations.AlterField(
            model_name="subchoiceof",
            name="to_choice",
            field=django_multitenant.fields.TenantForeignKey(
                default=uuid.uuid4,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="to_choice",
                to="choices.choice",
            ),
        ),
        migrations.AddConstraint(
            model_name="choice",
            constraint=models.UniqueConstraint(fields=("id", "das_tenant"), name="choices_choice_tenant_unique"),
        ),
        migrations.AddConstraint(
            model_name="dynamicchoice",
            constraint=models.UniqueConstraint(fields=("id", "das_tenant"), name="choices_dynamicchoice_tenant_unique"),
        ),
        migrations.AddConstraint(
            model_name="subchoiceof",
            constraint=models.UniqueConstraint(fields=("id", "das_tenant"), name="choices_subchoiceof_tenant_unique"),
        ),
    ]
