# Generated by Django 3.2.19 on 2023-09-25 21:28
import logging

from django.conf import settings
from django.db import migrations

from core.utils import DASTenantManagement, update_tenant_models

logger = logging.getLogger(__name__)


def populate_tenant_into_models(apps, schema_editor):
    models_names = ["Choice", "DynamicChoice", "SubChoiceOf"]
    class_models = [apps.get_model(f"choices.{model_name}") for model_name in models_names]

    das_tenant_management = DASTenantManagement(domain=settings.SERVER_FQDN)
    tenant = das_tenant_management.get_or_create_tenant()

    if tenant:
        update_tenant_models(models=class_models, tenant=tenant)
    else:
        logger.error("DAS Tenant not found.")


class Migration(migrations.Migration):
    dependencies = [
        ("choices", "0021_add_das_tenant_to_choices_models"),
    ]

    operations = [
        migrations.RunPython(
            populate_tenant_into_models,
            migrations.RunPython.noop,
        ),
    ]
