# Generated by Django 3.2.19 on 2023-10-02 04:02

from django.db import migrations

from utils.migrations.update_primary_key import add_tenant_to_primary_key

choices_models = ["Choice", "DynamicChoice", "SubChoiceOf"]


def regenerate_primary_keys(apps, schema_editor):
    add_tenant_to_primary_key("choices", choices_models)


class Migration(migrations.Migration):
    dependencies = [
        ("choices", "0022_populate_choices_with_tenant"),
    ]

    operations = [
        migrations.RunPython(code=regenerate_primary_keys, reverse_code=migrations.RunPython.noop),
    ]
