# Generated by Django 3.2.19 on 2023-10-03 23:29

import django.db.models.deletion
from django.db import migrations, models

import utils.migrations.columns


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_populate_oauth_models_with_tenant"),
        ("choices", "0023_regenerate_primary_keys"),
    ]

    operations = [
        migrations.AlterField(
            model_name="choice",
            name="das_tenant",
            field=models.ForeignKey(
                default=utils.migrations.columns.default_tenant_id,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="choices_choice",
                to="core.dastenant",
            ),
        ),
        migrations.AlterField(
            model_name="dynamicchoice",
            name="das_tenant",
            field=models.ForeignKey(
                default=utils.migrations.columns.default_tenant_id,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.dastenant",
            ),
        ),
        migrations.AlterField(
            model_name="subchoiceof",
            name="das_tenant",
            field=models.ForeignKey(
                default=utils.migrations.columns.default_tenant_id,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="choices_subchoiceof",
                to="core.dastenant",
            ),
        ),
    ]
