# Generated by Django 3.2.21 on 2023-11-02 18:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("choices", "0024_make_das_tenant_field_required"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dynamicchoice",
            name="choice_name",
            field=models.CharField(blank=True, max_length=100, verbose_name="Choice name"),
        ),
        migrations.AddIndex(
            model_name="dynamicchoice",
            index=models.Index(fields=["das_tenant", "choice_name"], name="dynamicchoice_choice_name_idx"),
        ),
        migrations.AddConstraint(
            model_name="dynamicchoice",
            constraint=models.UniqueConstraint(
                fields=("das_tenant", "choice_name"), name="choices_dynamicchoice_unique_choice_name_across_tenants"
            ),
        ),
    ]
