# Generated by Django 3.2.21 on 2023-11-20 00:35

from django.db import migrations

import choices.models
import utils.models


class Migration(migrations.Migration):
    dependencies = [
        ("choices", "0026_remove_unused_models"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="choice",
            managers=[
                ("objects", choices.models.ChoiceManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="dynamicchoice",
            managers=[
                ("objects", utils.models.CommonTenantManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="subchoiceof",
            managers=[
                ("objects", utils.models.CommonTenantManager()),
            ],
        ),
    ]
