# Generated by Django 3.2.21 on 2023-11-23 16:58

from django.db import migrations

from utils.migrations.update_primary_key import drop_constraint

APP_NAME = "choices"


def drop_constraints(apps, schema_editor):
    drop_constraint(
        app=APP_NAME,
        model="DynamicChoice",
        constraint="choices_dynamicchoice_id_51812571_uniq",
    )
    drop_constraint(
        app=APP_NAME,
        model="SubChoiceOf",
        constraint="choices_subchoiceof_id_887797d8_uniq",
    )


class Migration(migrations.Migration):
    dependencies = [
        ("choices", "0027_auto_20231119_1706"),
    ]

    operations = [
        migrations.RunPython(code=drop_constraints, reverse_code=migrations.RunPython.noop),
    ]
