# Generated by Django 3.2.21 on 2024-06-19 19:00

from django.apps import apps
from django.db import migrations

from utils.tenant.managers import TenantContextManager

CHOICE_MODEL = "mapping.TileLayer"
CHOICE_FIELD = "service_type"


def create_new_tile_type_choices(_migration_apps, _):
    Choice = apps.get_model("choices", "Choice")
    DASTenant = apps.get_model("core", "DASTenant")

    for tenant in DASTenant.objects.all():
        with TenantContextManager(domain=tenant.domain):
            Choice.objects.get_or_create(
                das_tenant_id=tenant.id,
                model=CHOICE_MODEL,
                field=CHOICE_FIELD,
                value="wms_basemap",
                defaults=dict(
                    display="WMS Basemap",
                ),
            )


class Migration(migrations.Migration):

    dependencies = [
        ("choices", "0028_regenerate_pk_choices_models"),
    ]

    operations = [
        migrations.RunPython(create_new_tile_type_choices, migrations.RunPython.noop),
    ]
