# Generated by Django 3.2.21 on 2024-10-18 16:58

from django.db import migrations, models

from utils.migrations.update_primary_key import drop_constraint


def fix_choices_subchoiceof(apps, schema):
    drop_constraint(
        app="choices",
        model="SubChoiceOf",
        constraint="choices_choice_sub_choic_from_choice_id_to_choice_98b1ae44_uniq",
    )


# delete stale indexes
drop_from_choice_index_sql = "DROP INDEX IF EXISTS public.choices_choice_sub_choice_of_from_choice_id_ccdd7f9a;"
drop_to_choice_index_sql = "DROP INDEX IF EXISTS public.choices_choice_sub_choice_of_to_choice_id_f7012d69;"
drop_das_tenant_index_sql = "DROP INDEX IF EXISTS public.choices_subchoiceof_das_tenant_id_097907d8;"


class Migration(migrations.Migration):

    dependencies = [
        ("choices", "0029_add_mapping_layers_wms_and_vector"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subchoiceof",
            options={"base_manager_name": "objects", "default_manager_name": "objects"},
        ),
        migrations.AddIndex(
            model_name="subchoiceof",
            index=models.Index(fields=["das_tenant", "from_choice"], name="choices_sub_das_ten_464638_idx"),
        ),
        migrations.AddIndex(
            model_name="subchoiceof",
            index=models.Index(fields=["das_tenant", "to_choice"], name="choices_sub_das_ten_0462ab_idx"),
        ),
        migrations.AddConstraint(
            model_name="subchoiceof",
            constraint=models.UniqueConstraint(
                fields=("das_tenant", "from_choice_id", "to_choice_id"),
                name="choices_subchoiceof_unique_across_tenants",
            ),
        ),
        migrations.RunPython(fix_choices_subchoiceof),
        migrations.RunSQL(drop_from_choice_index_sql),
        migrations.RunSQL(drop_to_choice_index_sql),
        migrations.RunSQL(drop_das_tenant_index_sql),
    ]
