# Generated by Django 3.2.25 on 2025-06-12 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("choices", "0030_fix_subchoiceof_missing_tenant_aware"),
    ]

    operations = [
        migrations.AlterField(
            model_name="choice",
            name="model",
            field=models.CharField(
                choices=[
                    ("activity.event", "Event"),
                    ("activity.eventtype", "Event Type"),
                    ("accounts.user.User", "User"),
                    ("mapping.TileLayer", "Maps"),
                    ("observations.region", "Region"),
                    ("observations.Source", "Sources"),
                ],
                default="activity.event",
                max_length=50,
            ),
        ),
    ]
