### Create an event
POST https://{{host}}/activity/events/
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "event_details": {
    "animals_involved": "1",
    "number_people_involved": 4,
    "type_accident": "Crash"
  },
  "event_type": "accident_rep",
  "icon_id": "accident_rep",
  "is_collection": false,
  "location": {
    "latitude": 20.625454386445615,
    "longitude": -103.41988563537596
  },
  "priority": 0,
  "reported_by": null,
  "time": "2022-03-29T16:57:35.360Z",
  "title": "Crash on"
}

###
