GET https://{{host}}/observations
Accept: application/json
Authorization: Bearer {{token}}

###
POST https://{{host}}/observations
Accept: application/json
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "location": {
    "latitude": "20.420935",
    "longitude": "-103.313486"
  },
  "created_at": "2022-04-29T11:17:50.784914",
  "recorded_at": "2022-04-29T11:17:50.784914",
  "additional": {
    "speed": 10,
    "temperature": 20
  },
  "source": "5a954689-e950-4235-96f9-9e9a4b76e839"
}

###
