GET https://{{host}}/activity/patrols/
Accept: application/json
Authorization: Bearer {{token}}

### Comment
GET https://{{host}}/activity/patrols/d5b590fb-e8fe-4e3e-a883-c4a0c95decbe/
Accept: application/json
Authorization: Bearer {{token}}

###
