daily_report_enabled = "True"
time_zone            = "Africa/Nairobi"
show_track_days      = "365"
patrol_enabled       = "True"
tableau_enabled      = "True"
tableau_site_id = "Demo1"
tableau_default_dashboard = "EarthRangerEventReportsSummary_demo"