mapping_features_v2       = "true"
time_zone                 = "Africa/Nairobi"
track_length              = "60"
tableau_enabled           = "True"
tableau_default_dashboard = "er_standard_analytics/summary"
