time_zone            = "Africa/Nairobi"
patrol_enabled       = "True"
daily_report_enabled = "True"
tableau_enabled      = "True"
tableau_site_id = "Demo1"
tableau_default_dashboard = "er_standard_analytics_stg/summary"
