mapping_features_v2  = "false"
time_zone            = "Africa/Nairobi"
twilio_account_sid   = "<provided-twilio_account_sid>"
twilio_auth_token    = "<provided-twilio_auth_token>"
whatsapp_from_number = "<provided-whatsapp_from_number>"
daily_report_enabled = "True"