mapping_features_v2       = "true"
time_zone                 = "Africa/Nairobi"
tableau_enabled           = "True"
tableau_default_dashboard = "er_standard_analytics/summary"
alerts_rate_limit         = "30"
