# -*- coding: utf-8 -*-
# Generated by Django 1.9b1 on 2015-11-19 17:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_input', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pluginconf',
            name='plugin_class',
            field=models.CharField(max_length=100, null=True, verbose_name='plugin class'),
        ),
        migrations.AlterField(
            model_name='pluginconf',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='pluginconf',
            name='plugin_name',
            field=models.CharField(max_length=100, null=True, verbose_name='plugin name'),
        ),
        migrations.AlterField(
            model_name='pluginconf',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
