name: Build das-server
on:
  push:
    branches:
      - develop
      - 'release-**'
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_sphinx_docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Sphinx docs
        run: |
          pip3 install -r dependencies/requirements-docs.txt
          cd docs
          make html
      - name: Upload Sphinx docs
        uses: actions/upload-artifact@v4
        with:
          name: sphinx_docs
          path: docs/_build/html
  build:
    uses: ./.github/workflows/build_docker.yml
    needs: build_sphinx_docs
    with:
      environment: padas-app
      artifact-download: true
      artifact-name: sphinx_docs
      artifact-path: ./das/sphinx_docs
      repository: europe-west3-docker.pkg.dev/padas-app/er-mt/das-server
      tag: ${{ github.head_ref || github.ref_name }}-${{ github.run_number }}
      dockerfile: circleci-docker/Dockerfile

  unit-test1:
    uses: ./.github/workflows/_unit-tests.yml
    needs: build
    with:
      image: "europe-west3-docker.pkg.dev/padas-app/er-mt/das-server:${{ github.head_ref || github.ref_name }}-${{ github.run_number }}"
      command: |
        pytest --reuse-db --junitxml=/testresults/junit/result_suite_one.xml --maxfail=15 accounts/tests mapping/tests reports/tests rt_api/tests tracking/tests
        pytest --reuse-db --junitxml=/testresults/junit/result_suite_three.xml --maxfail=15 analyzers/tests utils/tests
        pytest --reuse-db --junitxml=/testresults/junit/result_suite_four.xml --maxfail=15 choices/tests das_server/tests observations/tests core/tests

  unit-test2:
    uses: ./.github/workflows/_unit-tests.yml
    needs: build
    with:
      image: "europe-west3-docker.pkg.dev/padas-app/er-mt/das-server:${{ github.head_ref || github.ref_name }}-${{ github.run_number }}"
      command: pytest --reuse-db --junitxml=/testresults/junit/result_suite_two.xml --maxfail=15 activity/tests sensors/tests revision/test
