name: Build das-server
on:
  push:
    branches:
      - era-9426

jobs:
  build:
    uses: PADAS/gundi-workflows/.github/workflows/build_docker.yml@v2
    with:
      environment: padas-app
      repository: europe-west3-docker.pkg.dev/padas-app/er-mt/das-server
      tag: ${{ github.head_ref || github.ref_name }}-${{ github.run_number }}
      dockerfile: circleci-docker/Dockerfile

  test-suite1:
    uses: ./.github/workflows/_unit-tests-yml
    with:
      command: pytest --reuse-db --junitxml=/testresults/junit/result_suite_one.xml --maxfail=15 accounts/tests mapping/tests reports/tests rt_api/tests tracking/tests

  test-suite2:
    uses: ./.github/workflows/_unit-tests-yml
    with:
      command: pytest --reuse-db --junitxml=/testresults/junit/result_suite_two.xml --maxfail=15 activity/tests sensors/tests revision/test

  test-suite3:
    uses: ./.github/workflows/_unit-tests-yml
    with:
      command: pytest --reuse-db --junitxml=/testresults/junit/result_suite_three.xml --maxfail=15 analyzers/tests utils/tests

  test-suite4:
    uses: ./.github/workflows/_unit-tests-yml
    with:
      command: pytest --reuse-db --junitxml=/testresults/junit/result_suite_four.xml --maxfail=15 choices/tests das_server/tests observations/tests core/tests
