name: Build das-server on Pull Request
on:
  pull_request:
    types:
      - labeled
      - opened
      - synchronize
      - reopened

jobs:
  build:
    if: contains(github.event.pull_request.labels.*.name, 'deploy')
    uses: PADAS/gundi-workflows/.github/workflows/build_docker.yml@v1-stable
    with:
      environment: padas-app
      repository: europe-west3-docker.pkg.dev/padas-app/er-mt/das-server
      tag: ${{ github.sha }}
      dockerfile: circleci-docker/Dockerfile

