apiVersion: v1
kind: Service
metadata:
  name: alertmanager
spec:
  ports:
  - port: 9093
    targetPort: 9093
  selector:
    component: alertmanager
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: alertmanager
spec:
  serviceName: "alertmanager"
  updateStrategy:
    type: RollingUpdate
  replicas: 1
  template:
    metadata:
      labels:
        component: alertmanager
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port:   '9100'
    spec:
      imagePullSecrets:
        - name: gcr-secret
      containers:
      - image: gcr.io/padas-app/utility/prometheus-alertmanager:<<alertmanager-version>>
        name: alertmanager
        resources:
          requests:
            cpu: "25m"
          limits:
            cpu: "500m"
        volumeMounts:
        - mountPath: /alertmanager
          name: alertmanager-data
        env:
        - name: ALERTMANAGER_PUBLIC_IP
          valueFrom:
            configMapKeyRef:
              name: default-configmap
              key: ALERT_MANAGER_STATIC_IP
        - name: ALERTS_SLACK_CHANNEL
          valueFrom:
            configMapKeyRef:
              name: default-configmap
              key: ALERTS_SLACK_CHANNEL
        - name: ALERTS_SLACK_URL
          valueFrom:
            configMapKeyRef:
              name: default-configmap
              key: ALERTS_SLACK_URL
        - name: SEND_ALERTS
          valueFrom:
            configMapKeyRef:
              name: default-configmap
              key: SEND_ALERTS
      - image: prom/node-exporter:<<node-exporter-version>>
        name: disk-exporter
        resources:
          requests:
            cpu: "10m"
          limits:
            cpu: "500m"
        volumeMounts:
        - mountPath: /alertmanager
          name: alertmanager-data
        ports:
        - containerPort: 9100
  volumeClaimTemplates:
  - metadata:
      name: alertmanager-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "ssd"
      resources:
        requests:
          storage: 20Gi
      selector:
        matchLabels:
          component: alertmanager
